paasta_tools/cli/cmds/status.py

Previously, you had to determine the service name from the app id. This causes `paasta status` to explicitly specify the service name.
This is PAASTA-12553

Make paasta status show the service name

---

.travis.yml

I was looking at the published packages on PyPI and noticed that the last published version of `paasta-tools` is 0.66.6: https://pypi.python.org/pypi/paasta-tools
It looks like when build time improvements were made as part of #1337, the conditional wasn't updated too, so the deploy step has been skipped for any tagged versions since.

Fix condition within PyPI deploy step.

---

paasta_tools/utils.py
tests/test_chronos_tools.py
tests/test_marathon_tools.py
tests/test_utils.py

Internal ticket: PAASTA-12450
Add 64MB to memory-swap to work around PAASTA-12450 and to be able to test mesos-slave with --cgroups_limit_swap.
If --cgroups_limit_swap works as intended mesos-slave should reduce memory.memsw.limit_in_bytes from x + 64MB to x + 32MB.

Add 64MB to memory-swap to work around PAASTA-12450

---

paasta_tools/oom_logger.py
tests/test_oom_logger.py

To recognize such process names as "/nail/live/yelp" and "python batch/ke"

Match process names with spaces and slashes in oom-logger

---

paasta_tools/marathon_tools.py

As per SMTSTK-192 - configure_nerve shouldn't crash when a marathon file is not found for a container still running. 
get_marathon_services_for_nerve is called [here](https://github.com/yelp/nerve-tools/blob/master/src/nerve_tools/configure_nerve.py#L289)

adjusts get_marathon_services_for_nerve to handle missing marathon files

---

paasta_tools/cli/cmds/local_run.py
tests/cli/test_cmds_local_run.py

As per PAASTA-6901. This will allow local-run to continue execution when some volumes are not available, and warn the user of the missing volumes.

checks whether volumes exist before local-run can attempt to bind

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/deployd/common.py
paasta_tools/deployd/leader.py
paasta_tools/deployd/master.py
paasta_tools/deployd/watchers.py
paasta_tools/deployd/workers.py
paasta_tools/long_running_service_tools.py
tests/deployd/test_common.py
tests/deployd/test_deployd_master.py
tests/deployd/test_watchers.py
tests/deployd/test_workers.py

This changes the bounce queue to a python PriorityQueue. It adds
everything with priority 0 by default but lets you give a service
instance a higher or lower priority. Workers will fetch higher priority
instances first and fall back to FIFO if there is a tie.

Make deployd bounce queue a priority queue

---

paasta_tools/deployd/common.py
paasta_tools/deployd/master.py
paasta_tools/deployd/watchers.py
tests/deployd/test_common.py

This makes deployd workers pick bounces triggered on startup of deployd
or on changes to public config after all other bounces are done.
The motivation is to stop "big bounces" tying up workers that could be
dealing with real service pushes or autoscaling events. A "big bounce"
is one in which a config change or a code change in paasta_tools means
that we need to recreate every marathon app.

De-prioritise startup/public config bounces

---

paasta_tools/cli/cmds/status.py

Right now `paasta status` will read every service configuration and then filter. This can take a good 15 seconds as it parses everything. We can skip listing services that do not match the service filter.

Add a prefilter before reading service configuration files

---

example_cluster/docker-compose.override.yml
paasta_tools/generate_deployments_for_service.py
paasta_tools/paasta_remote_run.py
paasta_tools/paasta_serviceinit.py

adhoc instances are now sort of adopted by remote-run cmd, except the "interactive" one because we don't care about it?
also only status command is handled for now.

remote runs in paasta_serviceinit

---

docs/source/yelpsoa_configs.rst
paasta_tools/check_oom_events.py
tests/test_check_oom_events.py

Internal ticket: PAASTA-567
Add the check_oom_events option to the monitoring section. Defaults to 'True'.
Catch NotImplementedError to fix PAASTA-12659

Toggle check_oom_events on a per-instance basis.

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

This check can prevent us to scale up or down. I don't see the use case where it protects us.
Let's just remove it!?

Cluster autoscaler ignore unfufilled sfr

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

describe instances has a limit of 200 at a time from aws, so we should call it with 199 ips at a time.
Fixes #1501

Chunk calls to aws describe instances to 199 at a time

---

paasta_tools/check_marathon_services_replication.py
paasta_tools/mesos_tools.py
paasta_tools/monitoring_tools.py
paasta_tools/smartstack_tools.py
tests/test_check_marathon_services_replication.py
tests/test_smartstack_tools.py

* Remove unused 'client' from check_service_replication
* Pass cluster to marathon_tools.get_expected_instance_count_for_namespace() to avoid calling load_system_paasta_config() at https://github.com/Yelp/paasta/blob/master/paasta_tools/marathon_tools.py#L927
* Cache mesos_tools.get_slaves for 10 seconds. This reduces the number of calls to mesos-master from 105 (76 seconds) to 9 (11 seconds) on norcal-prod.

PAASTA-12576: Optimize check_marathon_service runtime.

---

paasta_tools/contrib/get_containers_and_ips.py

It also sends commands via the HAProxy socket file to add and remove entries from the map without requiring HAProxy to reload. It'll just run via cron for now, but later on it would be better to use docker [pre and post hooks](https://github.com/moby/moby/issues/28837) for this instead of cron.

Add script to generate HAProxy map file

---

paasta_tools/paasta_remote_run.py

when task config can't be constructed

[remote-run] print nicer error messages

---

paasta_tools/mesos_maintenance.py
tests/test_mesos_maintenance.py

Currently we giveup undraining if we can't unreserve resources. I think
maybe this can happen for old hosts that have gone away or in other
circumstances. Either way we try again to unreserve later so it is not
essential that we fail early in this case. The downside of failing here
is the cleanup maint script may never finish.

Make cleanup maintenance pass if unreserving fails

---

paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/marathon_tools.py
paasta_tools/utils.py

I'm adding both soa-config knobs for choosing a shard and listing previous shards, as well as system functions to read marathon servers and previous marathon servers, as well as a client loader to get all those clients en-masse.
I didn't want to write tests or docs so early if this is not the approach we want. Let me know if you think this is the right approach to get us off on the right foot, idk maybe write a test exercising get_marathon_clients ? And docs.

Added in config loading and client generation for sharded marathon configurations

---

paasta_tools/paasta_serviceinit.py

We used to ignore adhoc things in paasta status, but now we don't and it raises a NotImplementedError for users. 
While "technically" correct, I think it is a bad developer experience and I think it would be better if we just skipped past them.

Make paasta status ignore adhoc instances again

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/mesos/exceptions.py
paasta_tools/mesos/master.py

I am, however, unsure whether we should continue in the face of a leader election.  It could produce a state where two cluster autoscalers are running at once.
Fixes #1503

Make cluster autoscaler gracefully handle a mesos leader election

---

paasta_tools/mesos_tools.py
tests/test_mesos_tools.py

PAASTA-11595
This is a temporary fix that will be eventually undone as part of https://github.com/Yelp/paasta/pull/1528.

temporarily ignore orphan_tasks in mesos_tools.get_all_running_tasks

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/utils.py
paasta_tools/generate_deployments_for_service.py
tests/cli/test_cmds_wait_for_deployment.py
tests/test_generate_deployments_for_service.py

I want to reduce the scope of what wait-for-deployment does, to prevent future issues where we add something and it has the potential for breaking w-f-d.

Make wait-for-deployment only inspect marathon instances

---

paasta_tools/api/views/instance.py

With the new chronos paasta api endpoint, we were calling the /master/frameworks call, which is expensive. 
I already have a PR merged to not ask for chronos tasks on wait-for-deployment. This makes it so we don't ask for this endpoint unless we on verbose mode.

Only fall for mesos task counts on the paasta api in verbose mode

---

mypy.ini
paasta_tools/bounce_lib.py
paasta_tools/deployd/workers.py
paasta_tools/frameworks/native_scheduler.py
paasta_tools/frameworks/native_service_config.py
paasta_tools/long_running_service_tools.py
paasta_tools/marathon_tools.py
paasta_tools/setup_marathon_job.py
paasta_tools/utils.py
tests/deployd/test_workers.py
tests/test_marathon_tools.py
tests/test_setup_marathon_job.py
tox.ini

This adds type annotations to long_running_service_tools, marathon_tools, setup_marathon_job, and related tests. I did this work to help make sure the sharding change is correct.
#1552 has the actual meat of the sharding change -- this PR is separate so that #1552's diff is cleaner.

Add type annotations to marathon-related things

---

paasta_tools/api/api.py
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/marathon_serviceinit.py
paasta_tools/marathon_tools.py
requirements.txt
tests/api/test_instance.py

Info is grabbed from /v2/queue in marathon, and if available summarized and printed with paasta status
This may require bumping the marathon-python version?
Fixes #1408

Add potential reasons for app deployments being stalled to paasta status and api

---

example_cluster/docker-compose.override.yml
example_cluster/paasta/marathon.json
paasta_itests/docker-compose.yml
paasta_itests/steps/setup_steps.py
paasta_tools/marathon_tools.py
tox.ini

This is not a shard-only config, this is still in hybrid mode, like our real infrastructure.
However, it allows itest-specific room so you could make assertions about an individual shard, like:
```
marathon shard N should have appid foo
```
with the raw clients available in the paasta_itests context with this PR.

Added sharded marathon servers to the paasta_itests and example_cluster

---

yelp_package/dockerfiles/itest/chronos/Dockerfile
yelp_package/dockerfiles/itest/marathon/Dockerfile

We were not using the webupd8 java anyway, we were using the java that came from openjdk9-headless as a zookeeper dep (pretty sure).

Make chronos itest use xenial and upate gpg key for bintray

---

paasta_tools/marathon_tools.py
setup.py

PAASTA-13173
@solarkennedy - this does not exactly follow the ticket's description but I think it might be easier.
The end result is that we will be able to log to streams of all services running on this host from bash using something like this:
```
echo foo | /path/to/paasta/python -c 'import sys; from paasta_tools.marathon_tools import broadcast_log_all_services_running_here; broadcast_log_all_services_running_here(sys.stdin.read().strip())'
```
I think it's a bit less disruptive than rewriting entire script in python.

add broadcast_log_all_services_running_here

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

If an agent disapears from the mesos state while running the cluster
autoscaler, the cluster autoscaler needs to take into account the fact
that it no longer exists.  This updates the autoscaler to only look at
currently existing agents at each loop while scaling down

Filter out slaves from the slaves list if not in mesos state

---

paasta_tools/cleanup_chronos_jobs.py

internal ticket: PAASTA-13323
This method can return None for jobs that have no interval.

Fix cleanup_chronos_jobs for jobs with no interval

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

This changes the cluster autosclaler so that within one resource, it will attempt to kill multiple slaves at once.
Basically, it creates a coroutine per slave to kill, and then runs that until it hits `await asyncio.sleep(5)`.  At which point the execution will be suspended, and the `downscale_aws_resource` will resume, going on to the next slave.  At the end of `downscale_aws_resource`, we wait until all coroutines have completed (or been canceled) before returning.
The logic in `downscale_aws_resource` is a bit iffy, but I'm confident in the proper interactions between having multiple `gracefully_terminate_slave`s and `wait_and_terminate`s running at at time.
This is not actually multithreaded, as only one coroutine will run at once, but there is a bit of difficulty around setting the …

Async scale down cluster resource (ie parallel draining+killing of slaves in an sfr/asg)

---

paasta_tools/drain_lib.py

I think expiration doesn't mean anything when we post 'up' to hacheck.

include expiration only when draining in HacheckDrainMethod

---

paasta_tools/drain_lib.py

OPS-12282
Current 15 second timeout for both connect and read operations seems too generous to me. Let's reduce it to 3s connect timeout and 1s read timeout? I think these numbers are good even though reduction from 15 to this level might be a bit too aggressive.
requests lib supports passing timeout as int/float or as tuple - https://github.com/requests/requests/blob/master/requests/api.py#L32

reduce hacheck timeout in drain_lib

---

paasta_tools/mesos_maintenance.py

We currently fail to undrain hosts if they are marked as `draining` but have no resources dynamically reserved for the purpose of maintenance. This change attempts to fix that.

Only try to unreserve maint reserved resources if there are some

---

setup.py

Jenkins doesnt seem to be respecting requirements.txt , its still using 0.9.0

Update setup.py to use marathon >= 0.9.2

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py

Since the state summary doesn't include tasks, and the utilization_error
part needs to know about those

The cluster autoscaler needs to full state to calulate usage

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/paasta_metastatus.py
tests/autoscaling/test_autoscaling_cluster_lib.py

Also makes metastatus do fewer state calls if you want autoscaling info
fixes #1583

Only call state once on the cluster autoscaler

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

If the cluster autoscaler can't find utilization for a region/pool, assume error is zero, so that no autoscaling will be attempted for that region/pool

Fix error when a pool isn't ready when the cluster autoscaler tries to run

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

Just set the utilization_error to 0, since metastatus won't actually scale anything

Fix autoscaling info for metastatus

---

paasta_tools/monitoring/check_mesos_outdated_tasks.py
setup.py
tests/monitoring/test_check_mesos_outdated_tasks.py

internal ticket: PAASTA-13357
This check looks for containers serving previous versions.
```
./check_mesos_outdated_tasks.py --bounce-time 2
CRITICAL - There are 2 tasks running in norcal-prod that are more than 2h older than their last bounce.
SERVICE.INSTANCE                COMMIT    CREATED               HOSTNAME                     CONTAINER
yelp-main.mobile_alerts_update  addafd00  2017-10-11 15:28:46   paasta23-r6-sfo2             23c11d92-4ad9-467c-98e2-4b5767d6e5af-S1.9e84d80f-64b6-49fb-b609-ff49dd0300c6
yelp-main.elites_csv_kew_worke  1e332c88  2017-10-20 14:21:15   paasta64-r1-sfo2             a3e48ca4-3bb6-463f-af46-7595829d04ff-S39.1ff04304-c7b4-415e-a49c-28d5f7096f47
```

check_mesos_outdated_tasks

---

paasta_tools/cli/cmds/status.py

```
$ paasta status -s fluffy -c norcal-devc -i main -d ~/proj/yelpsoa-configs
Warning: it looks like fluffy has not been deployed anywhere yet!
%s No deployments in deployments.json yet.
Has Jenkins run?
```
(note the `%s` in the output)
```
$ paasta status -s fluffy -c norcal-devc -i main -d ~/proj/yelpsoa-configs
Warning: it looks like fluffy has not been deployed anywhere yet!
fluffy has no deployments in deployments.json yet.
Has Jenkins run?
```

paasta status: fix string interpolation in error message

---

paasta_tools/paasta_remote_run.py

File "/usr/bin/paasta_remote_run", line 554, in <module>
main(sys.argv[1:])
File "/usr/bin/paasta_remote_run", line 550, in main
actions[args.action](args)
File "/usr/bin/paasta_remote_run", line 297, in remote_run_start
soa_dir, instance, instance_type, constraints = extract_args(args)
ValueError: not enough values to unpack (expected 7, got 6)

extract_args doesn't return a constraint

---

paasta_tools/paasta_remote_run.py
requirements.txt

Note that paasta_remote_run on tron is broken because it uses the default pool instead of taskproc https://github.com/Yelp/paasta/blob/master/paasta_tools/paasta_remote_run.py#L412. I am going to pin paasta on tron for now until all the tron paasta_remote_run instances have the taskproc pool setting.

Fixed paasta_remote_run and added task logging executor

---

paasta_tools/cli/cmds/local_run.py
requirements.txt
tests/cli/test_cmds_local_run.py

I've been using `paasta local-run` a lot recently, and it's kind of annoying that the port keeps changing on me.
What if we hashed the service name and the username and then always tried to use that port? The vast majority of the time, we should be able to get the same port over and over.
(ephemeral-port-reserve will fall back to a random port if the requested port is unavailable)

Make "paasta local-run" try to use the same port repeatedly

---

docs/source/cluster_autoscaling.rst

I did a brain dump on the cluster autoscaler.
missing: anything about the async/await.  That should probably be mentioned.  Also will need to be updated for cluster boost.
It can probably be a bit more clear about what I mean by region✕pool, and why it works like that.

RFC: Add cluster autoscaler docs

---

paasta_tools/cli/cmds/local_run.py

Although I hate to do it, it looks like we can't trust docker to pull 2 images simultaneously :(

Make paasta local-run lock on pulls

---

mypy.ini
paasta_itests/paasta_deployd.feature
paasta_itests/steps/paasta_deployd_steps.py
paasta_itests/steps/setup_steps.py
paasta_tools/deployd/watchers.py
paasta_tools/marathon_tools.py
paasta_tools/secret_tools.py
paasta_tools/utils.py
tests/deployd/test_watchers.py
tests/test_marathon_tools.py
tests/test_secret_tools.py
tox.ini

This adds the neccessary logic to the bounce code so that services will
be bounced when the related json files containing a secret are updated
*and* the signature of a secret used by that service changes.
* Make deployd aware of json files in secrets subdir and get it to
check if marathon app id has changed
* Check env vars in marathon config for SECRET(my-secret) format and
retreive signature for inclusion in config hash
* itest to check it works

Add bounce logic for json secret files

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/marathon_serviceinit.py
paasta_tools/marathon_tools.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_marathon_serviceinit.py
tests/test_marathon_tools.py

Notable change: This moves the "Autoscaling Info" section of verbose status out of the per-app section and into the per-job section, which seems like the correct thing to do -- get_autoscaling_info queries information about all running apps, instead of just the particular app in question. (Bonus! this might reduce calls to Mesos's /master/state.)

Make service autoscaler work with multiple marathon shards.

---

paasta_itests/docker-compose.yml
tox.ini
yelp_package/dockerfiles/itest/api/Dockerfile
yelp_package/dockerfiles/itest/mesos/Dockerfile

* bump docker-compose to 1.17.1
* reuse paasta_Itests images when it is possible instead of rebuilding them
* docker-ce 17.03.2 in paasta_itests

Reuse paasta_itest images

---

paasta_tools/marathon_tools.py
paasta_tools/setup_marathon_job.py
tests/test_setup_marathon_job.py

I noticed this was happening during big bounces and lucy bounces. Here is what happens:
* paasta restart (or other signal) is initiated more than 1 time, like run paasta restart 100 times
* 100 apps are created, all waiting, 1 "new app" is the desired one
* The bounce never tries to scaled down those old apps, so they have to launch, then it drains, etc.
This same "take in the slack" technique was already being applied to the new_app on scaledown. Now it will also be applied to all the other old apps, because we are also scaling those down too.

Always fix the slack of old marathon apps when bouncing

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py

Allows the cluster autoscaler to act on cancelled_running sfrs with missing instances

---

paasta_tools/cli/cmds/metastatus.py
tests/cli/test_cmds_metastatus.py

internal ticket: PAASTA-13069
It allows us to define 'Marathon RO' as a list that contains URLs for each configured shard.
If this is OK, I'm going to update dashboard_links.json and to use these links in paasta status as well.

Support arrays in dashboard_links.json

---

paasta_tools/marathon_serviceinit.py

It should fix the following exception in paasta status.
```
ERROR:__main__:Traceback (most recent call last):
File "/usr/bin/paasta_serviceinit", line 203, in main
clients=clients.marathon(),
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/marathon_serviceinit.py", line 459, in perform_command
tasks, out = status_marathon_job_verbose(service, instance, clients, cluster, soa_dir, job_config)
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/marathon_serviceinit.py", line 220, in status_marathon_job_verbose
autoscaling_info = get_autoscaling_info(clients, job_config)
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_service_lib.py", line 498, in get_autoscaling_info
apps_with_clients = …
```

Fix TypeError in status_marathon_job_verbose

---

paasta_tools/cli/cmds/local_run.py
tests/cli/test_cmds_local_run.py

Internal ticket: OPS-12441
paasta local-run shouldn't publish a container's port(s) for non-http (--no-healthcheck) batches.

paasta local-run --no-healthcheck shouldn't publish a container's ports

---

example_cluster/paasta/dashboard_links.json
paasta_itests/paasta_api.feature
paasta_itests/steps/paasta_api_steps.py
paasta_itests/steps/setup_steps.py
paasta_tools/api/api.py
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/marathon_dashboard.py
paasta_tools/marathon_dashboard.py
paasta_tools/marathon_tools.py
setup.py
tests/api/test_marathon_dashboard_api.py
tests/test_marathon_dashboard.py
yelp_package/dockerfiles/itest/api/dashboard_links.json
yelp_package/dockerfiles/itest/api/marathon.json

This is a first pass at adding a script to spit out information about the service instances in a cluster and their associated marathon shard. The API will ultimately get queries and displayed as a nice dashboard by an external service.
TODO:
* Add a real unit test
* Add type annotations

Initial Support for a Sharded Marathon Dashboard

---

paasta_tools/marathon_dashboard.py

The code was producing broken shard_urls for non-sharded clusters. This should make it work properly.

Make marathon_dashboard work for non-sharded clusters

---

docs/source/autoscaling.rst

It was causing markup for the offset parameter for the proportional decision policy to be interpreted incorrectly, leaving the offset parameter label un-styled.
bug is here: https://paasta.readthedocs.io/en/latest/autoscaling.html, cmd+f `:offset:`
adding a little space was all that sphinx needed to render this correctly. tested interactively with `make docs` locally.

Fixes a small typo in the autoscaling documentation

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/metrics/metastatus_lib.py
paasta_tools/paasta_metastatus.py
tests/metrics/test_metastatus_lib.py

This fixes something that's been bothering me for a while, which is that there's no easy way to see resource utilization for a pool broken down by region. You currently either get region or pool, but can't distinguish default/uswest1-prod and default/sfo12-prod.
Example output: https://fluffy.yelpcorp.com/i/tdFCpRCrnWRHpF0p1HQLtmXhXthj5VSg.html
One thing I expect to be somewhat controversial, and am not very tied to: This adds the groupings (region and pool by default) before the hostname in the `-vvv` output. I think this will be useful, as currently with `-vvv` it's impossible to know what pool a host is in.

Make metastatus able to group by multiple values properly

---

docs/source/generated/paasta_tools.paasta_service_config.rst
docs/source/generated/paasta_tools.rst
paasta_tools/adhoc_tools.py
paasta_tools/check_marathon_services_replication.py
paasta_tools/chronos_tools.py
paasta_tools/paasta_service_config.py
paasta_tools/utils.py
tests/test_check_marathon_services_replication.py
tests/test_paasta_service_config.py

TLDR; An idea of a new way to work with yelpsoa-configs, so that to only read them once and to not use any caches.
Right now to iterate over instances of MarathonServiceConfig, we usually read yelpsoa-configs once  to get the service-instance pairs (get_services_for_cluster), and then we read the same files many times to create MarathonServiceConfig objects (load_marathon_service_config).
Moreover we implemented cache https://github.com/Yelp/paasta/blob/master/paasta_tools/marathon_tools.py#L160 to solve some performance issues caused by this approach.
The idea is to get rid of all the complexity by introducing a new class (PaastaServiceConfig ) which is capable of creating instance configs without re-reading yaml files.
I adjusted check_marathon_services_replication to show how it would …

Instance configs experiments

---

debian/paasta-tools.links
paasta_tools/cli/cmds/boost.py
paasta_tools/paasta_cluster_boost.py

Plus minor cli fixes.
Ideally I'd like to add integration tests:
get, set, get, clear, get
to make sure that this toolchain is working properly

Passing boost arguments only when action is set

---

paasta_tools/frameworks/constraints.py
paasta_tools/frameworks/native_scheduler.py
paasta_tools/frameworks/native_service_config.py
paasta_tools/native_mesos_scheduler.py
paasta_tools/setup_marathon_job.py
requirements.txt
setup.py

Deployd broke after #1653 was merged, because of errors like `There is no current event loop in thread 'Worker6'.`
This should fix that, by creating event loops where necessary. It also cleans up some boilerplate using the https://github.com/notion/a_sync library.

Avoid using default event loop on secondary threads.

---

paasta_tools/cli/cmds/logs.py
requirements.txt
tests/cli/test_cmds_logs.py

- Fix log tailer discovery
- Fix date handling for range logs (timezone issues + fetching today's logs)
- Upgrade to new yelp_clog version with gzip decompression working in python3
I run different tests and they all seem to return the correct results.

Fix tail discovery, date handling and upgrade yelp_clog

---

paasta_tools/marathon_tools.py
paasta_tools/utils.py
tests/test_marathon_tools.py

We briefly discussed the idea of automatically adding a `['hostname', 'UNIQUE']` constraint to small services running in production. This would avoid situations where all of their tasks end up running on the same agent, which might then go away and cause replication issues.

RFC: Automatically add ['hostname', 'UNIQUE'] to small services

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/autoscaling/cluster_boost.py
paasta_tools/cli/cmds/boost.py
paasta_tools/cli/utils.py
paasta_tools/paasta_cluster_boost.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_cluster_lib.py
tests/test_paasta_cluster_boost.py

* Apply the cluster boost only on CPU resource
* Fix the call from a paasta boost
* Figure out the region(s) automatically
* Replaced get by status to remove confusion:
- get is for the autoscaler
- status is for a human to check

Better cluster boost

---

paasta_tools/marathon_tools.py
tests/test_marathon_tools.py

I originally made paasta only add the hostname unique constraint to small services running in production clusters. Enforcing this in code was rather stupid. We have the system paasta config setting. Simply omitting it from our non-production clusters will be sufficient. This will also give us the ability to test this feature more in non-prod clusters.

Allow auto hostname unique in non-prod clusters

---

paasta_tools/cli/cmds/status.py
paasta_tools/cli/utils.py
tests/cli/test_cmds_status.py

This makes paasta status take max(latencies) instead of sum(latencies), with respect to paasta_serviceinit time to complete.

Perform paasta status ssh in parallel

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/cli/utils.py
paasta_tools/contrib/emit_allocated_cpu_metrics.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_service_lib.py

Although ideally this number would be available "for free", mts's are expensive, and we don't need to emit this "constant" for every docker container at yelp.
To that end, I made this script that emits the metric directly. It doesn't change that much, so I'm think of running every 5m or so on masters.

Added a script to emit additional paasta metrics

---

paasta_tools/drain_lib.py

This is just a quick patch, we should refactor to make this configurable
really. The problem this helps with is when the deployd queues get large
it is possilbe that a draining task goes past its draining timeout
before it is re-processed. At that point we are in an infinite loop of
draining and undraining and things never get better. So this isn't a fix
for performance issues but does move the cliff edge a bit further back.

Bump drain timeout for hacheck

---

paasta_tools/deployd/master.py

This log line is logged every 0.1s and we have the number in a graph
anyway.

Reduce deployd log verbosity

---

paasta_tools/cli/schemas/adhoc_schema.json
paasta_tools/mesos_tools.py
paasta_tools/paasta_remote_run.py
paasta_tools/utils.py

This is for TASKPROC-166 to enable paasta_remote_run schedule tasks on more than one mesos clusters. Note that "role" is added to adhoc schema so that resources with non-taskproc role can be used. This also helps TASKPROC-169 where "paasta remote_run" was stuck because resources with "*" role do not match the default taskproc role.
The change is tested on devc:
tronplayground-uswest1adevc: $ sudo .tox/py36/bin/paasta_remote_run.py start --service taskproc_canary --instance remote --cluster norcal-stageg --verbose
tronplayground-uswest1adevc: $ sudo .tox/py36/bin/paasta_remote_run.py start --service taskproc_canary --instance remote --cluster norcal-devc --verbose

Enabled paasta_remote_run to connect to diffferent mesos clusters

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/bounce_lib.py
paasta_tools/frameworks/native_scheduler.py
paasta_tools/frameworks/task_store.py
paasta_tools/mesos_tools.py
requirements.txt

We seem to be leaking file descriptors of ZK clients. Calling `zk.stop()` is not enough so add a bunch of `zk.close()` calls where appropriate.

Close connections to Zookeeper properly

---

paasta_tools/cli/cmds/validate.py

Here is the new error message looks like:
✓ Successfully validated schema: chronos-nova-prod.yaml
✓ Successfully validated schema: adhoc-norcal-prod.yaml
✓ Successfully validated schema: chronos-norcal-prod.yaml
✓ Successfully validated schema: marathon-pnw-prod.yaml
✗ Failed to load file. More info: http://paasta.readthedocs.io/en/latest/yelpsoa_configs.html: /nail/home/chl/git/yelpsoa-configs/yelp-main/marathon-norcal-stagef.yaml
File "/nail/home/chl/paasta/.tox/py36/bin/paasta", line 11, in <module>
load_entry_point('paasta-tools', 'console_scripts', 'paasta')()
File "/nail/home/chl/paasta/paasta_tools/cli/cli.py", line 121, in main
File "/nail/home/chl/paasta/paasta_tools/cli/cmds/validate.py", line 295, in …

validate error message improvement

---

paasta_tools/check_marathon_services_replication.py
tests/test_check_marathon_services_replication.py

This is a subtle change to ensure that we atleast check Marathon
replication when we cannot check smartstack replication due to multiple
namespaces. This should mean that services which do not advertise into
the same namespace as their service_instance name will atleast have
their replication checked against Marathon.

Check marathon replication on non-default reg

---

paasta_tools/bounce_lib.py

The idea is to let this function raise exceptions so deployd can detect and handle them.
Fixes #1706

Make paasta_tools.bounce_lib.kill_old_ids raise exceptions for deployd

---

paasta_tools/cli/schemas/marathon_schema.json

We no longer have any services using `nerve_ns` in their marathon configs. It has been deprecated for quite some time. Let's remove it from the schema to prevent its use going forward. Unfortunately, removing the Python logic surrounding nerve_ns will require a bit more work since we never fully updated all of the codebase to handle registrations and the multiple namespaces.

Stop allowing nerve_ns in marathon files

---

paasta_itests/steps/paasta_serviceinit_steps.py
paasta_tools/api/views/instance.py
paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/cli/cmds/status.py
paasta_tools/marathon_serviceinit.py
paasta_tools/marathon_tools.py
paasta_tools/paasta_serviceinit.py
paasta_tools/utils.py
tests/api/test_instance.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_marathon_serviceinit.py

I'm tired of having to do paasta status -v to see information relevant to the bounce.
Most of the time I don't actually care about the individual tasks, so I don't need to see that; I just need the numbers and statuses.

Make paasta status display information about all marathon apps, even without -v.

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py

This prevents situations like that:
`2018-02-07 23:07:45,907:INFO:paasta_tools.autoscaling.autoscaling_cluster_lib.SpotAutoscaler.sfr-******************:Found 100.00% slaves registered in mesos for this resource (31/31)
2018-02-07 23:07:48,384:ERROR:paasta_tools.autoscaling.autoscaling_cluster_lib.SpotAutoscaler.sfr-******************:Didn't find enough candidates to kill. This shouldn't happen so let's not kill anything! Amount wanted to decrease: 2.4105, killable capacity: 2.41`

Rounding capacity to terminate too

---

paasta_tools/cli/schemas/marathon_schema.json
tests/cli/test_cmds_validate.py

We added support in the code to treat instances whose name begins with an underscore (`_`) as templates. This was to assist with dealing with yaml anchors/templating. However, we never updated our marathon schema file to support this.
This is PAASTA-13886

Update marathon schema to allow instance names to begin with an underscore

---

paasta_tools/paasta_service_config_loader.py
tests/test_paasta_service_config_loader.py

Another breakage from #1722: anything that calls `PaastaServiceConfigLoader.instance_configs()` (including `check_marathon_services_replication`) now gets a `NoDeploymentsAvailable` exception if there's any instances for the service/cluster in question that do not have a corresponding entry in deployments.json. The v1 deployments json object (which we used to use in PaastaServiceConfigLoader for marathon configs) returns an empty branch dict instead of raising an error.
This has `instance_configs` simply skip over any instances where `NoDeploymentsAvailable` gets raised. This does mean that the set of instances returned will be different depending on whether `PaastaServiceConfigLoader` is initialized with `load_deployments=True` or `False`.

Have PaastaServiceConfigLoader.get_instances() skip instances which have no version marked for deployment.

---

paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_status.py

This confused someone a bit earlier.
```
$ paasta status -c norcal-prod -s yelp_main -i my_important_kew_worker
yelp_main doesn't have any instances matching my_important_kew_worker on norcal-prod.
```
(This makes it look like you misspelled the instance rather than the service.)
```
$ paasta status -c norcal-prod -s yelp_main -i my_important_kew_worker
The service "yelp_main" does not exist.
Did you mean any of these?
yelp-main
[another suggestion]
[another suggestion]
[another suggestion]
[another suggestion]
```

Slightly better "paasta status" output for a bad service name

---

yelp_package/dockerfiles/lucid/Dockerfile
yelp_package/dockerfiles/trusty/Dockerfile
yelp_package/dockerfiles/xenial/Dockerfile

This is needed by vault_tools -> crypto_lib -> pygpgme.
It's really only needed for the yelp internal build which is why Travis
passed.

Add libgpgme as a dependency

---

paasta_tools/chronos_tools.py
tests/test_chronos_tools.py

This is a very strange one. I was able to repro via tdd.
It only happens on monthly jobs, and only when a tz is set.
I'm sure the bug is "somewhere" in here:
https://github.com/taichino/croniter/blob/master/src/croniter/croniter.py#L179
But......... this is the fastest way to get past this bug.

Fix a bug in check_chronos_jobs for monthly jobs

---

paasta_tools/cli/cmds/spark_run.py

pyspark, spark-shell and spark-submit already have this option. jupyter users also want this option. However, due to https://issues.apache.org/jira/browse/TOREE-427, the %AddJar magic is broken. As a workaround, this PR adds --jars as a spark-run option, to satisfy needs from both sides.
~/paasta/.tox/py36/bin/paasta spark-run --cluster pnw-devc --jars /spark_client/target/data_pipeline_spark-0.1.0-SNAPSHOT.jar --cmd "spark-submit /spark_client/python_example.py"

Added the jars option for spark-run

---

paasta_tools/secret_providers/vault.py
tests/secret_providers/test_vault.py
yelp_package/extra_requirements_yelp.txt

This version has:
* saner string encoding
* support for SUDO_USER which will make paasta local-run --pull work
with vault
cc @filipposc5

Bump vault_tools version

---

general_itests/steps/deployments_json_steps.py
paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/cmds/push_to_registry.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_push_to_registry.py

See internal ticket for details.

Add --verify-image-exists flag for PAASTA-14050

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

yelp-dm has a different way of launching a jupyter notebook server. It becomes a general use case when spark-run is used on a service other than the default services/spark. This change is to make SPARK_OPTS available for non-default jupyter commands.

Moved SPARK_OPTS out from jupyter

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

spark-run mounts $PWD:/spark_client:rw at the moment. There are cases where users want to mount with a different local_path:container_path. This change makes $PWD:/spark_driver:rw as default, and allows users to mount a different directory with --work-dir.

Added an option to mount a different spark driver work dir

---

paasta_tools/cli/utils.py
tests/cli/test_utils.py

The format mesos uses for the container name they pass to docker seems to
have changed in a recent version of mesos. This fixes our docker_
commands which rely on using the container name.

Fix docker_ commands container name

---

paasta_tools/cli/cmds/local_run.py
paasta_tools/cli/cmds/secret.py
paasta_tools/secret_providers/__init__.py
paasta_tools/secret_providers/vault.py
paasta_tools/secret_tools.py
tests/cli/test_cmds_local_run.py
tests/cli/test_cmds_secret.py
tests/secret_providers/test_secret_providers.py
tests/secret_providers/test_vault.py
tests/test_secret_tools.py
yelp_package/extra_requirements_yelp.txt

* Extend secret provider so that it can write secrets to your local
checkout of yelpsoa-configs
* Extend secret provider so it can decrypt secrets (just useful to have)
* Add cli module to call these secret provider methods
the motivation is to deprecate the paasta_secret cli which is in the
internal vault_tools package in favour of this which is generic and
imports the vault_tools package for the vault provider (which is
currently the only one implemented).

Add paasta secret cli module

---

paasta_tools/cli/cmds/local_run.py
tests/cli/test_cmds_local_run.py

For instances where we don't have a vault token but need to run
local-run non interactively it is useful to have an option that skips
decrypting secrets so that the non-interactive script isn't prompted for
a password.
This adds that option. The downside is that you just get the secret ref
left in the env var and not the plaintext.

Add --skip-secrets option to local-run

---

paasta_tools/utils.py
tests/test_utils.py

It gets team from get_team() method. Otherwise if that wasn’t set in the configuration the environment variable won’t be set.

Add PAASTA_MONITORING_TEAM environment variable

---

paasta_tools/utils.py

Dependencies are silently ignored if you are missing a ``dependencies_reference`` entry, even if there is only a single 'main' namespace. This caused a bit of confusion when trying to use firewalls. I think it makes sense to use a default for this. 
If 'main' isn't a good default, (is this a Yelp thing or is a default elsewhere in PaaSTA?) maybe we can just check for a dependency of the same name as the namespace.

Make get_dependencies return main by default even if no reference exists

---

paasta_tools/utils.py
tests/test_utils.py

Don't add .git to default yelp git urls. Fixes #1756

---

paasta_tools/secret_tools.py
tests/test_secret_tools.py

We recently ended up throwing this error when a non-string crept in to
an environment variable. Just as belt and braces we should catch this
TypeError since a bogus env var cannot be a secret ref.

Fix TypeError checking for secret_ref

---

paasta_tools/cli/cmds/start_stop_restart.py

Previous output:
`This service will soon be gracefully started/restarted, replacing old instances accordingto the bounce method chosen in soa-configs.`

Fix a spacing issue

---

paasta_tools/cli/schemas/chronos_schema.json
paasta_tools/cli/schemas/marathon_schema.json

Enforce types on fields in monitoring dict of json schema.
This is really to prevent team becoming a non-string which can cause
errors now we pass it into the containers' environment.

Add monitoring schema

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_service_lib.py

The previous filter only worked properly with service declaring one CPU. It didn't take into account the fact that we use and store a normalized CPU usage
This implementation of the filter compare the CPU usage of tasks according to their own limit with the burst limit that we enforce.
I added tests and detailled tables to make sure the logic works

Fix Bogus CPU value filter

---

paasta_itests/paasta_deployd.feature
paasta_tools/deployd/watchers.py
tests/deployd/test_watchers.py

When deployd starts it must add watches to all the zookeeper nodes for
autoscaled services. This also enqueues the services. This is normally
fine except in a "big bounce" scenario in which we don't want all
autoscaled services enqueued at startup.
This change passes an enqueue paramater to the watcher functions so that
new nodes that are created are enqueued for a bounce but nodes that are
enumerated on startup are not.
Note: I'm also re-enabling some autoscaling tests which used to be flakey but which I think we should be running. I'll run multiple travis builds to hopefully assert they are not flakey.

Prevent autoscalerwatcher adding services on start

---

paasta_tools/cli/cmds/start_stop_restart.py
paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_start_stop_restart.py

Fixes #1774
I had meant to do this refactor when I started #1770 (hence why I pulled the filter-specific arguments into their own function), but didn't follow through.

Add --registration argument to stop/start/restart by refactoring to use add_instance_filter_arguments.

---

paasta_tools/cli/cmds/local_run.py

I don't want people blindly using sudo all the time, so this check only makes it use sudo when we "have to".
Technically you could use paasta without a registry that requires auth.
Hopefully this change will be an ok "compromise" between magic and non-surprising behavior.
But really I don't want auto-sudo so Tron can run this command *and* have the permission to kill it later.
cc @qui cc @bobtfish

Only use sudo with paasta local-run when there is no docker config available

---

paasta_tools/cli/cmds/spark_run.py

1. Added PAASTA_CLUSTER to executor envs so that scribe logs do not have a blank cluster field;
2. Removed --cluster restrictions so that we don't have to change spark-run when spark-run expands to other clusters. Puppet is the place to control if spark-run is provisioned in a Mesos cluster;
3. Added the --aws-profile option to enable non-default AWS profile.

Added PAASTA_CLUSTER to executor envs and spark-run option changes

---

paasta_tools/cli/cmds/status.py
paasta_tools/utils.py
tests/cli/test_cmds_status.py
tests/test_utils.py

Test procedure:
Step 1 - Create bogus file
~/.../yelpsoa-configs/careers (master)$ ls -la
lrwxrwxrwx   1 bryanp users    28 Mar 26 12:56 adhoc-nova-prod.yaml -> careers/adhoc-nova-prod.yaml
...
~/.../yelpsoa-configs/careers (master)$
Step 2 - Recreate bug
~/.../yelpsoa-configs/careers (master)$ paasta status
✗ No deploy.yaml exists, so your service cannot be deployed.
Push a deploy.yaml and run `paasta generate-pipeline`.
More info: http://y/yelpsoa-configs
~/.../yelpsoa-configs/careers (master)$
~/.../yelpsoa-configs/careers (master)$ paasta validate
✓ Successfully validated schema: marathon-nova-prod.yaml
...
~/.../yelpsoa-configs/careers (master)$
<note: no errors mentioned despite having a broken symlink>
Step 3 - Fix and retry
~/.../yelpsoa-configs/careers (master)$ paasta status …

PAASTA-13077 bogus error on symlink bug fix

---

paasta_tools/cli/cmds/local_run.py

It makes sense to have the default in a path that is easier to access
for users other than root. This is so that different roles with
different users and token permissions can standardise on the path of the
token they need for local-run.

Change default vault token path

---

yelp_package/dockerfiles/trusty/Dockerfile
yelp_package/dockerfiles/xenial/Dockerfile

itest_trusty and itest_xenial are failing on our internal build servers, due to the extra dependencies that we add in. If I run the commands manually, I get:
```
x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
```
when trying to build grpcio, due to a lack of g++.
grpcio comes from:
```
Collecting grpcio>=1.0.0; extra == "grpc" (from googleapis-common-protos[grpc]<2.0dev,>=1.5.2->google-cloud-dataproc->mrjob->yelp-logging==1.0.37->-r ./requirements.txt (line 105))
```
This branch shouldn't really change much on Travis.

Fix internal build

---

paasta_tools/cli/cmds/spark_run.py

Bailing out is preferred over using max() to avoid spark-run with unexpected behavior.

Make sure spark-run executor_cores is less than max_cores

---

example_cluster/paasta/api.json
paasta_itests/paasta_deployd.feature
paasta_itests/steps/paasta_deployd_steps.py
paasta_tools/deployd/watchers.py
tests/deployd/test_watchers.py

This makes it so the autoscaler watcher explicitly creates a node watch
on keys called "instances". Before this would only be the case if the
parent folder and instances key were created at nearly the same time.
i.e. the instances child existed by the time the watcher was being
created for the containing folder. Note that the added itest was failing
before I made this change.

Fix autoscaler watcher missing new service

---

paasta_tools/cli/cmds/spark_run.py

With this change, Spark frameworks without a Jupyter notebook connection will be terminated if the Jupyter kernel has been idle for more than one hour. Frameworks with a Jupyter notebook connection but using 32+ CPUs will also get terminated.

Added timeout for spark-run Jupyter kernels

---

paasta_tools/cli/cmds/remote_run.py

TASKPROC-194: increase the default staging timeout for remote-run

---

paasta_tools/cli/cmds/spark_run.py

CH per instance report is broken. Note that spark.mesos.task.labels in https://spark.apache.org/docs/latest/running-on-mesos.html is not the right config to use. Below is from docker inspect with spark.mesos.executor.docker.parameters.
"Image": "docker-paasta.yelpcorp.com:443/services-spark:paasta-8a92fdcc9c48026a28d83d0463b7ef7fdaf2ee59",
"WorkingDir": "/work",
"Entrypoint": [
"/bin/sh"
],
"Labels": {
"paasta_instance": "client_hliu",
"paasta_service": "spark"
}

Added Docker labels to spark-run executors

---

paasta_tools/cli/cmds/logs.py

It is hard to "discover" what scribereader commands people could use if they wanted to. I'm hoping this might help. Only works if people add a -v

Make paasta logs print out scribereader commands in verbose mode

---

paasta_tools/setup_marathon_job.py
tests/test_setup_marathon_job.py

This fixes the logging of exceptions thrown in drain method calls. Currently we're just logging lines like:
`"crossover bounce killing task service.instance.git04ae7ac8.configf2363b35.1bb8453d-48e2-11e8-af2e-fe0836cdcca9 due to exception in is_safe_to_kill: "`
This gives us a proper traceback.

Print tracebacks when catching drain method exceptions

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

This is to fix "the input device is not a TTY" when running spark-submit with tron.

Do not use --it for spark-submit and jupyter

---

paasta_tools/drain_lib.py

Relates to the 503s found in OPS-13121. Basically, when we bounce larger apps, and drain a large number of tasks at once, we get a bunch of errors like this:
crossover bounce killing task REDACTED due to exception in is_safe_to_kill: Traceback (most recent call last):
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/setup_marathon_job.py", line 195, in add_to_tasks_to_kill_if_safe_to_kill
if task.state != 'TASK_RUNNING' or await drain_method.is_safe_to_kill(task):
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/drain_lib.py", line 279, in is_safe_to_kill
info = await self.get_spool(task)
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/drain_lib.py", line 234, in get_spool
headers={'User-Agent': get_user_agent()},
File …

Bump hacheck timeouts to avoid mass-timeouts when draining many tasks at once.

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/mesos_maintenance.py
paasta_tools/setup_marathon_job.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_cluster_lib.py
tests/test_mesos_maintenance.py

We are trying a new approach with mesos to not send offers from hosts in
maintenance mode. If this works we should not need to reserve the
resources on an agent to prevent tasks getting launched there. This
commit adds a config flag to disable the reservation in both the bounce
logic and the cluster autoscaler. Doing this behind a config flag to
just enable in the places where we have patched mesos first for testing.
If everything works out okay I can double back and remove the
reservation code.

Add a flag to disable reservation on maint calls

---

paasta_tools/deployd/common.py
tests/deployd/test_common.py

This error ocassionally crops up when a service specifies an invalid
constraint. Currently it isn't caught and causes one or more of the
watchers in deployd to die which causes freqeunt leader elections. It
should be safe to catch and log.
NB: by invalid I mean restricting to a set of agents that does not exist.

Catch NoSlavesAvailableError in deployd

---

paasta_tools/utils.py

Another remote_run traceback, I think this should fix
```
File "/usr/bin/paasta", line 11, in <module>
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cli.py", line 121, in main
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/remote_run.py", line 248, in paasta_remote_run
graceful_exit=graceful_exit,
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/utils.py", line 757, in run_on_master
popen_kwargs=popen_kwargs,
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/utils.py", line 1856, in _run
for linestr in iter(process.stdout.readline, b''):
File …
```

Encode newlines before sending them to stdin

---

paasta_tools/tron/client.py
tests/tron/test_tron_client.py

Without this, Tron returns the "Named Configuration Template" stuff along with the actual config, so it's always different and the script will update every namespace.

Don't get header so that config diff is accurate

---

paasta_tools/remote_git.py
tests/test_remote_git.py

This is to (eventually) allow us to ping authors in slack who are part of a push.
It only needs to work on "yelpy" git servers, but leaves room to get authors via other means for different git servers (maybe in the future we can curl bitbucket or something)

Added a get_authors remote git command for better slack notifications

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/remote_git.py
tests/cli/test_cmds_mark_for_deployment.py
tests/test_remote_git.py

Based on #1829, this connects the two and makes it so we will ping authors when their deploy is ready.
@chriskuehl do you think this approach is "better" (comparing before/after sha) or do I need to go all the way and do exactly what the existing thing does, which is always compare against the "production_deploy_group" ?

Ping Slack with authors

---

paasta_tools/paasta_remote_run.py

Although a special case, locust needs this because they are an "adhoc" service that doesn't have real deployments.

Don't load deployments if a docker_image is provided in remote-run

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
tests/autoscaling/test_autoscaling_cluster_lib.py

More or less treating a cancelled_running SFR with no instances the same way we treat a cancelled SFR.  Let me know if you think that's too aggressive.
Also we've seen SFRs sit in this state more or less indefinitely (until we manually cancel them), and this may make us less likely to notice that.  Is that at all problematic?

Make SpotAutoscaler cleanup cancelled_running SFR with no instances

---

paasta_tools/cli/cmds/mark_for_deployment.py
tests/cli/test_cmds_mark_for_deployment.py

Since this situation is idempotent, and we do it every day with daily builds, I think we want to suppress these notifications.
@chriskuehl

Don't send slack noifications if the old and new commits are the same

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

raise an error if conflicting namespaces are detected during in `get_tron_namespaces_for_cluster`

[tron tools] error on namespace conflict

---

requirements-minimal.txt
requirements.txt
setup.py

sorry for the drive-by, friends :)
I was testing out https://github.com/asottile/seed-isort-config and wanted to see if I could find any unused requirements.
As far as I can tell the two things I've removed aren't direct dependencies:
```
$ git grep yelp_bytes
$ git grep yelp_encodings
$ git grep websocket
requirements.txt:websocket-client==0.44.0
```

Remove a few unused requirements

---

paasta_tools/cli/schemas/marathon_schema.json

This is required for sfn_autoscaling.
Testing:
Manually tested by creating a virtualenv.

Add a custom key for "sfn_autoscaling" to marathon_schema.

---

.pre-commit-config.yaml

`flake8` (and the other ast-loading hooks) also check this

check-ast is no longer useful now that paasta is py3+

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_cluster_lib.py

I'm splitting this into a maximum increase and maximum decrease so that
I can reduce the maximum decrease without affecting the autoscaler's
ability to scale up.
The motivation is that because we now have multiple SFRs to speed up
scaling down we end up decreasing by 20% on each one and because we
round down to the nearest whole number we are effectively being more
aggressive than before both in speed and amount that we scale down.
So I've reduced the default max decrease to 10% and made it
configurable via /etc/paasta.

Split out MAX_CLUSTER_DELTA for cluster autoscaler

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

Pass aws credentials via the environment rather than as ``--env key=value``. This prevents you from being able to see the keys using ``ps``
Fixes #1851 
To verify this code works:
```
>>> os.execlpe('docker', *['docker', 'run', '-it', '--env', 'foo', 'ubuntu', {'foo': 'bar'}])
root@dd9e6ceafaee:/# echo $foo
bar
```

Added safer passing of credentials to spark

---

paasta_tools/api/api.py
paasta_tools/api/settings.py
paasta_tools/api/views/instance.py
paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/mesos_tools.py
requirements.txt
setup.py
tests/api/test_instance.py
tests/autoscaling/test_autoscaling_cluster_lib.py
tests/test_mesos_tools.py

- Switch to gunicorn for the API, so that we don't have to use gevent's monkey-patching to get concurrency, since that breaks asyncio.
- Fix some call sites I missed when changing the mesos module to async

Fix more async problems

---

paasta_tools/async_utils.py
paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/mesos/cluster.py
paasta_tools/mesos/master.py
paasta_tools/mesos/mesos_file.py
paasta_tools/mesos/util.py
paasta_tools/mesos_tools.py
paasta_tools/metrics/metastatus_lib.py
paasta_tools/paasta_metastatus.py
tests/autoscaling/test_autoscaling_cluster_lib.py
tests/mesos/test_cluster.py
tests/test_mesos_tools.py

When running the cluster_autoscaler in a stage environment, I found a few problems.
It's an error to call a function that has been decorated with @async.to_blocking from within an async coroutine, unless it (or something further up the call stack) is launched on a different thread, e.g. via a_sync.run / a_sync.to_async. You get something like
```
File "/nail/home/krall/pg/paasta/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 1276, in autoscale_cluster_resource
await scaler.scale_resource(current, target)
File "/nail/home/krall/pg/paasta/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 502, in scale_resource
target_capacity=target_capacity,
File "/nail/home/krall/pg/paasta/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line …
```

Even more async fixes.

---

paasta_tools/chronos_rerun.py
tests/test_chronos_rerun.py

fixes an issue where we'd attempt to interpolate the command with
contextvaribales even if the command is None:

ensure cmd is not None before interpolating

---

paasta_tools/cli/cmds/local_run.py
paasta_tools/secret_providers/vault.py
tests/cli/test_cmds_local_run.py

Normally I think it is ok for functions to raise, but with local-run, the output goes to real users, and I would prefer they see something friendlier ("permission denied"), also I like the hint.
I considered not catching all exceptions, but there are a lot of possibilities for it to go wrong, including lots of generic NoneType and Callable error junk (which is why I changed the ImportError'd stubs to be more functional)

Print a friendlier error to local-run users when secret decryption fails

---

paasta_tools/contrib/check_registered_slaves_aws.py

`check_registered_slaves_aws.py` is producing the following error:
```
File "/opt/venvs/paasta-tools/bin/check_registered_slaves_aws.py", line 58, in <module>
main()
File "/opt/venvs/paasta-tools/bin/check_registered_slaves_aws.py", line 52, in main
if check_registration(threshold):
File "/opt/venvs/paasta-tools/bin/check_registered_slaves_aws.py", line 22, in check_registration
dry_run=True,
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/autoscaling/autoscaling_cluster_lib.py", line 959, in __init__
super(AsgAutoscaler, self).__init__(*args, **kwargs)
TypeError: __init__() missing 3 required positional arguments: 'utilization_error', 'max_increase', and 'max_decrease'
```
This appears to be due to the ClusterAutoscaler class …

Fix check registered slaves aws

---

paasta_tools/autoscaling/ec2_fitness.py
paasta_tools/mesos_tools.py
tests/autoscaling/test_autoscaling_cluster_lib.py
tests/autoscaling/test_ec2_fitness.py
tests/test_mesos_tools.py

I wasn't able to use framework's principle to count chronos, taskproc and spark as batch tasks because taskproc uses the http api where authentication is not enforced. In addition, framework's name is hard to control in spark and taskproc apps. As a workaround, this PR counts all non-marathon tasks as batch tasks. 
AWS claims that "The typical frequency of interruption for Spot Instances in the last 30 days was less than 5% on average." with the new spot pricing model. Hopefully with this change, batch jobs are more stable.

Count all non marathon tasks as batch tasks

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

Without this, the deploy script doesn't send expected_runtime to Tron.
Tested this with the partnerships namespace, which has already started using expected_runtime!

Deploy expected_runtime field for tronfig

---

paasta_tools/docker_wrapper.py
tests/test_docker_wrapper.py

Since PaaSTA passes environment variable values to a Docker container
via `VAR=val docker --env VAR`, fixing `docker_wrapper.py` to read those
values not only from the command line arguments but also from the
environment.

Fix `docker_wrapper.py` doesn't see environment variables

---

.travis.yml

I have three justifications but opinions welcome:
* It seems to be about as stable as the itests give or take
* It occassionally has caught bugs that we don't cover in the itests and
have ended up pushing to prod
* I use it quite a bit for development and it's a pita if it's been
broken by some minor thing that can be hard to work out if it changed
some time in the past.

Make travis fail if we break example cluster

---

debian/paasta-tools.links
paasta_tools/api/views/instance.py
paasta_tools/cli/utils.py
paasta_tools/list_kubernetes_service_instances.py
paasta_tools/utils.py
setup.py
tests/test_list_kubernetes_service_instances.py
tests/test_utils.py

This is needed to get generate_deployments working for kubernetes- yaml
files. I've deliberately left paasta status not implemented for now.
This also adds the list_kubernetes_service_instances script so we can
start with the list|xargs setup_kubernetes_job like pattern before we
add support for the k8s instances to deployd.
NB: I think this should be safe, I've read some code and checked things still work in the example cluster. I guess the itests should flag if I've broken anything else.

Add kubernetes as an instance type

---

paasta_tools/smartstack_tools.py
tests/test_smartstack_tools.py

Because pods can re-use IPs we only want to wait for one backend to be
healthy since any unhealthy backend could be from an old pod that has
terminated but which synapse hasn't garbage collected yet.

Minor fix to k8s nerve readiness check

---

paasta_tools/cli/cmds/docker_exec.py
tests/cli/test_cmds_docker_exec.py

This lets you do `paasta docker_exec ... --user=root`, which is something I often want to do when exec-ing into a container (the `nobody` user isn't always so useful for troubleshooting).
Currently my workflow is `paasta docker_exec`, let it find me a container to exec into, then SSH to the host again and `docker exec --user=root` into it. This argument will let me skip those manual steps.

Add --user flag to `paasta docker_exec`

---

paasta_tools/cli/cmds/validate.py
paasta_tools/cli/schemas/tron_schema.json
paasta_tools/tron/tron_timeutils.py
paasta_tools/tron_tools.py
tests/cli/test_cmds_validate.py
tests/test_tron_tools.py

Added a JSON schema for Tron configs, and `validate` methods for TronActionConfig and TronJobConfig. `paasta validate` will check the schema and call validate on the configs. Eventually, the goal is to have all of the checks that are done with our pre-commit script and `tronfig` to be included here instead. If `paasta validate` passes, we should be confident that Tron will accept the config.
There's some extra logic in the CLI to support something like `paasta validate -s tron/prod`, so that we can use this in a pre-commit hook for those files, too. Not the cleanest, but I figure it's better than maintaining multiple types of pre-commit checks.
This shows the general approach I'm going for. If this looks reasonable, I'll add tests. And then we can follow up with more check methods.

Starting point for validation of Tron configs

---

paasta_tools/deployd/master.py
paasta_tools/metrics/metrics_lib.py
tests/metrics/test_metrics_lib.py

It's useful to know when deployd is "stuck" and just constantly crashing
and electing a new leader. This adds a counter that we can chart/alert
on.

Add a metric for leader elections

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

Adds a setting to TronJobConfig so it won't try to load deployments, since deployments.json isn't always available in soaconfigs for validation.

Don't load deployments for Tron validation

---

paasta_tools/cli/cmds/local_run.py

Currently, if you don't want local-run to run in interactive mode,
you must specify an instance. This is now specified in local-run's
help page.

Add better documentation for local-run

---

paasta_tools/deployd/common.py
paasta_tools/list_marathon_service_instances.py
tests/deployd/test_common.py
tests/test_list_marathon_service_instances.py

We currently only catch the ways we know it can go wrong. There's a lot
of user input and our validation with commit hooks can only be so good.
We need deployd to continue if only one marathon app dict is malformed
so this catches all Exceptions.

Catch exceptions on format_marathon_app_dict

---

docs/source/yelpsoa_configs.rst
paasta_tools/adhoc_tools.py
paasta_tools/chronos_tools.py
paasta_tools/cli/schemas/tron_schema.json
paasta_tools/kubernetes_tools.py
paasta_tools/marathon_tools.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/test_marathon_tools.py
tests/test_tron_tools.py
tests/test_utils.py

I think this is a change that we wanted anyway.
While working on `paasta local-run` for tron, I was chasing down there `None` was coming from when trying to pull docker images. In reaction to that, I added some "defensive" code to protect against `None` in our InstanceConfigs and unified the `__repr__` so Tron could use it.
While doing that though, I needed to get cluster in everywhere. This change allows us to set `cluster` at the Tron Job level instead of each action.
Note: I'm a little concerned that I don't fully understand the intent of the parameterized test on :186 on `test_tron_tools.py`.

Unified __repr__ across paasta instance objects and send cluster into all TronActionConfigs

---

paasta_tools/cli/cmds/remote_run.py
paasta_tools/paasta_remote_run.py

When tron runs a remote-run job on pnw-prod, the dynamodb name is taskproc-events-pnw-prod. However, the aws_region is us-west-1, which only has taskproc-events-norcal-prod.
An alternative fix is to infer aws region from paasta cluster name. For example, region will be us-west-2 if the paasta cluster is pnw-prod. Since the problem is only seen with tron (which is not an usual paasta remote-run configuration), I choose to add an option to override the incorrect aws_region config on tron servers. 
Tested on mesosstage (us-west-1) against pnw-devc (us-west-2) cluster.

Added a remote_run option to override dynamodb aws_region config

---

paasta_tools/contrib/emit_synapse_services_metrics.py

cc @somic @bplotnick @jnb 
I want to have metrics from our service mesh available "for free" to our service owners. I'm thinking it will be useful to them for the following use-cases:
* free dashboards  (y/paasta-status)
* easy to integrate with the slo framework
* easy to retrieve for auto-rollback / push on green tooling
Additionally, when we move to envoy, we'll be able to update this script and live in "dual" mode, and these other tools won't have to change maybe? Maybe we'll need to translate the metric name.
I'm sure we'll have to update the metric whitelist over time, and maybe munge them to be friendlier.
Also the hack to just assume the backend name is service.instance isn't super great long term.

RFC: smartstack errors meteorite emitter

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

It seems that doing a "replace" is better than an "update" since it
covers cases where your new deployment removes keys from the deployment.
It still seems to trigger a RollingUpdate or whatever strategy you have
defined rather than literally replacing the deployment object.

For k8s deployments PUT not PATCH

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

You can omit but k8s then chooses the latest version which seems to be a
beta spec. So I think we ought to hard code the version of the schema
here.

Set k8s deployment spec version

---

paasta_tools/cli/cmds/status.py
paasta_tools/cli/utils.py
paasta_tools/monitoring_tools.py
paasta_tools/tron_tools.py
tests/cli/test_utils.py
tests/test_monitoring_tools.py

This is a small refactor I need in order to allow paasta local-run to work with tron without circular imports.

Move list_teams to monitoring_tools

---

paasta_tools/mesos_tools.py
tests/test_mesos_tools.py

paasta staus -vv is already pretty verbose, I don't think we need this.

Removed EOF message from paasta status output.

---

paasta_tools/setup_tron_namespace.py

It makes it just a little easier to debug when it is predictable and consistent

Always deploy tron namespaces in a sorted order

---

paasta_tools/cleanup_maintenance.py

This shouldn't be needed on our patched version of k8s that doesn't send
offers to maint'd hosts. This adds a flag so I can disable it in the
cron job that cleans up maint'd hosts.

Add flag to disable reservation cleanup

---

paasta_tools/tron_tools.py

With master config file, we would be able to validate more stuff, such as valid_node, correctly rendered command, and so on.

using tronfig validate with master

---

requirements-minimal.txt
setup.py

This fixes #1804 by switching to "loosely" pinned requirements for `setup.py` and `requirements-minimal.txt`. This should have no effect on the main application until the requirements are upgraded in `requirements.txt`
As a side bonus, this makes `setup.py` use the requirements from `requirements-minimal.txt`. This is a relatively common pattern internally for packages that are both standalone applications and libraries.

unpin minimal/library requirements

---

paasta_tools/setup_marathon_job.py
tests/test_setup_marathon_job.py

**Summary**
This mimics the internal functionality for event_detector which was
recently decommissioned. Emits an event name-spaced `deploy.paasta`
and along with this sends cluster, instance and service as a dimension.
Open to instrument more dimensions if need be.

Add paasta deploy events using yelp_meteorite.

---

paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_job.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_job.py

This gives the k8s logic the ability to manage StatefulSets. We manage
them the same way as Deployments. The distinguishing factor is that they
support dynamic EBS volumes that follow the Pods. The new yelpsoa syntax
looks like:
```
persistent_volumes:
- container_path: /mnt/whatever
size: 10
mode: RW
```
Note this is deliberately a bit MVP. The StorageClass has to be created
by hand and we don't enforce constraints on AZ yet so you must be
careful to create everything in 1 AZ.

Add support for StatefulSets

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/list_marathon_service_instances.py
tests/cli/test_cmds_mark_for_deployment.py
tests/test_list_marathon_service_instances.py

https://jira.yelpcorp.com/browse/PAASTA-14607
Can specify the following types in a deploy.yaml file:
- notify_after_mark
- notify_after_good_deploy
- notify_after_auto_rollback
- notify_after_abort

Enable/Disable types of Slack notifications

---

paasta_tools/cli/cmds/spark_run.py

This is to add sudo to "docker push" to non docker-dev registries (e.g. spam). They are going to add sudo::conf puppet changes to allow users without root privilege to run "docker push".

Added sudo for docker push to non docker-dev registries

---

paasta_tools/cli/schemas/tron_schema.json
paasta_tools/tron_tools.py
tests/test_tron_tools.py

`mesos_address` is a MASTER-level setting and can't be set in actions anymore, so the tronfig we generate is invalid. (https://github.com/Yelp/Tron/pull/509)
If we take mesos_address out, we don't need the cluster_fqdn_format and default cluster anymore. The cluster name just comes from the filename (i.e. tron-norcal-prod) now.

Remove cluster address from Tron actions

---

docs/source/yelpsoa_configs.rst
mypy.ini
paasta_tools/bounce_lib.py
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/setup_marathon_job.py
paasta_tools/smartstack_tools.py
tests/test_bounce_lib.py

Add type annotations to smartstack_tools. Clean up unused is_task_in_smartstack.
With #1924, we made a particular race condition much worse: Synapse only restarts haproxy once a minute on each box, with each box restarting at a different point in the minute. Since we consider a task healthy as soon as any of the 20 boxes we query has it up, this means that if a bounce goes very quickly (all tasks come up within a minute), we might drain all old tasks simultaneously, before all boxes have had a chance to restart haproxy to get the new tasks, causing 503s.
This change makes it so that all 20 boxes have to agree that the task is up (by default - configurable by changing haproxy_min_fraction_up to something less than 1 -- something like 0.001 would be roughly equivalent to the current …

Make filter_tasks_in_smartstack need a task to be up on more than one box to consider it healthy.

---

paasta_tools/contrib/check_deployd_leader_election.sh

Small script to check the number of contenders for a deployd leader and
alert if less than a certain number. We've seen a couple of cases where
a bug can cause the python processes to hang even though they've given
up leadership. In this case we might not have anyone left to take over
and this alert should let us know.

Add deployd leader election check

---

paasta_tools/kubernetes_tools.py

Annoyingly k8s doesn't like the None here and returns 0 deployments
rather than all deployments. However, an empty string does work.
This was breaking the deployment script because it was finding no
deployments and trying to recreate them and getting 409

Fix k8s label selector

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/slack.py
tests/cli/test_cmds_mark_for_deployment.py
tests/test_slack.py

The new Slack notifications are great at providing tons of information, but they can be pretty noisy as the typical notification takes up between 5 and 9 lines of chat (plus another 5-8 lines in many cases, when we have a mark-for-deployment followed immediately by a successful deployment notification):
I was thinking we could use Slack attachments or something to hide most of this information away in a collapsible summary, but I was surprised to not be able to find any way to do this.
Instead, what if we had a one-line summary in the main channel, and posted all the additional details in a thread followup? Here's how those same two messages look with this change:
Clicking to expand the thread has the rest of the information:
I haven't updated tests or anything yet, mostly just looking …

Make Slack notifications more concise

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/kubernetes_tools.py
tests/cli/test_cmds_wait_for_deployment.py
tests/test_kubernetes_tools.py

* generalise checking of marathon status in wait-for-deployment cli to
check "long_running_status" which is either k8s or marathon
* Ensure that app_count in the HTTP status API is an accurate
representation of whether k8s has finished a deployment by counting
pods for a service with unique shas.
* Ensure deployment info for StatefulSet is also accurate. Note that
until https://github.com/kubernetes/kubernetes/pull/62943 is released
the status of a StatefulSet deployment may not be 100% accurate.

Make k8s wait-for-deployment work

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/cli/schemas/adhoc_schema.json
paasta_tools/cli/schemas/chronos_schema.json
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_chronos_tools.py
tests/test_kubernetes_tools.py
tests/test_marathon_tools.py
tests/test_utils.py

- Currently, we enforce a 10x burst on cpu usage via the cpu_burst_pct parameter in PaaSTA configs, but this has led to jobs using too many cpus.
- I changed cpu_burst_pct (i.e. multiplicative) to cpu_burst_add (i.e. additive), which provides a lower and much safer cpu limit.
- Instead of a 10x default, we default to 1 additional cpu.
- I also changed related code in kubernetes and chronos tools, as well as the autoscaling lib (i.e. marathon) to use the new parameter instead.
- Relevant tests were changed as well.
- make test
- We initially considered changing from 10x to 2x, but even 2x is too much for jobs that request more cpus. A +1 is more than enough for smaller jobs, and will not adversely affect larger jobs. If they need more, they can supply their own cpu_burst_add.
- [UPDATE] …

Change cpu_burst_pct to cpu_burst_add 

---

paasta_tools/marathon_dashboard.py
tests/test_marathon_dashboard.py

* Used PaastaServiceConfigLoader for each service in the cluster
* Some refactoring of inefficient code: e.g. pull out constant operations out of the loop
* Able to create dashboard for `norcal-prod` very quickly (within 2 sec); tested by rsyncing code to norcal-prod box and running manually

Optimized create_marathon_dashboard

---

paasta_tools/contrib/emit_allocated_cpu_metrics.py
paasta_tools/contrib/emit_synapse_services_metrics.py
paasta_tools/contrib/paasta_update_soa_memcpu.py

This makes the dimensions we emit consistently named. This must be shipped and release with the other changes in order to minimize dashboard breakage.

Make paasta-related dimensions consistent

---

paasta_tools/api/api.py
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/metastatus.py
paasta_tools/cli/cmds/metastatus.py
paasta_tools/cli/utils.py
paasta_tools/paasta_metastatus.py
paasta_tools/utils.py

Add HTTP API to executes the code used to generate output of `paasta metastatus` on the HTTP API server side, and returns the output and the exit code for that.
Use that HTTP API to generate result for `paasta metastatus` instead of using `ssh ... /usr/bin/paasta_metastatus` if `USE_API_ENDPOINT` environment variable is `true`.
```
$ paasta metastatus -c norcal-stagef -vv -a >/tmp/paasta-metastatus-ORIG
$ USE_API_ENDPOINT=1 paasta metastatus -c norcal-stagef -vv -a >/tmp/paasta-metastatus-NEW 
$ diff -u /tmp/paasta-metastatus-ORIG /tmp/paasta-metastatus-NEW
--- /tmp/paasta-metastatus-ORIG 2018-09-14 04:15:49.874849796 -0700
+++ /tmp/paasta-metastatus-NEW  2018-09-14 04:15:37.787245547 -0700
@@ -27,8 +27,8 @@
Resource id                Pool      State   Current  Target  Min capacity  Max …
```

`paasta metastatus` via HTTP API

---

paasta_tools/cli/cmds/logs.py
tests/cli/test_cmds_logs.py

- Bug (behavior): Whenever `paasta logs` would be called to get marathon and chronos log lines, an exception would be raised
- Bug (code): Functions that deal with marathon and chronos logs decode log lines, assuming they are byte-strings.
- Fix: Remove the lines, since the log lines are now passed as normal str by scribereader.
- python paasta_tools/cli/cli.py log ...
- make test
- Might this be a hold out from Python 2->3?

Remove decode on marathon and chronos log lines

---

paasta_tools/api/api.py
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/objgraph.py
requirements-minimal.txt
requirements.txt

Add the following `objgraph`-based endpoints to help debugging memory
leaks:
* `/v1/objgraph_show_most_common_types?limit=20` to output most common
types sorted by instance count.
* `/v1/objgraph_show_backrefs_for_type/SomeTypeName?max_objects=20&max_depth=3`
to output back references for objects of given type.
All endpoints write their output into the `paasta-api` log.
You should run `paasta-api` with the `PAASTA_API_OBJGRAPH` environment
variable defined to enable these endpoints.
Please see https://mg.pov.lt/objgraph/ for an information about using
`objgraph` for memory leak investigation.

Add Paasta API objgraph endpoints

---

docs/source/yelpsoa_configs.rst

By @solarkennedy's request, I have added some documentation for the `cpu_burst_add` parameter under the cpus bullet point, just so people know it exists and specifies a number of cpus (no longer percentage based).

Add docs for cpu_burst_add

---

general_itests/steps/deployments_json_steps.py
paasta_tools/cli/cmds/start_stop_restart.py
paasta_tools/cli/cmds/status.py
tests/api/test_client.py
tests/cli/test_cmds_start_stop_restart.py
tests/cli/test_cmds_status.py

This makes it so paasta status will force use of the HTTP api for k8s
instances whilst still defaulting to the SSH api for other instance
types. As we add features to the HTTP api e.g. for marathon app status
we can migrate it over to using the HTTP by adding to
HTTP_ONLY_INSTANCE_CONFIG.
I think I've fixed all the tests but lets see what travis says...

Update paasta status to use http api when needed

---

paasta_tools/chronos_rerun.py
paasta_tools/chronos_tools.py
paasta_tools/cli/cmds/local_run.py
paasta_tools/cli/schemas/chronos_schema.json
paasta_tools/tron_tools.py
tests/cli/test_cmds_local_run.py
tests/test_chronos_rerun.py
tests/test_chronos_tools.py
tests/test_tron_tools.py

Now that Tron commands use {} instead of %, parse_time_variables needs to handle those differently for local-run.
Chronos commands still use % now... The 2nd commit provides a migration path forward:
1. Release this version of paasta tools
2. change all commands to {} in soaconfigs, with use_percent_format: False
3. Change parse time variables to always use {} instead of percent
4. Remove use_percent_format from soaconfigs
5. Remove use_percent_format from paasta tools
Alternatively, we could not bother with migrating and leave use_percent hardcoded to True for Chronos. Then we wouldn't need the 2nd commit at all.

Add {}-type formatting for Tron commands

---

paasta_tools/api/api.py
requirements-minimal.txt
requirements.txt

Add Python interpreter CLI available via a Unix domain socket.

Remote Python interpreter for `paasta-api`

---

paasta_tools/contrib/migrate_chronos_percent_format.py

We can use `--include-flag` first, then run it without once we're safely on the next version where {}-format is default. In case we need to go back on paasta tools for whatever reason, we can also use `--downgrade` to go back to %.
I wanted to keep the diffs as small as possible, so this processes the files line-by-line to preserve formatting as much as possible. Ugly, but it works! 😬

Script for migrating Chronos commands to {}-formatting or back

---

paasta_tools/api/views/marathon_dashboard.py
paasta_tools/async_utils.py
paasta_tools/mesos/master.py
paasta_tools/mesos/mesos_file.py
paasta_tools/mesos/slave.py
paasta_tools/mesos/task.py

Add `cleanup_self` to `@async_ttl_cache` and use it for all methods
`@async_ttl_cache` decorator caches a function call result using a key
composed from function's args values.  If it's used for a method, it
will use `self` as a part of the key, creating a strong reference to the
class instances in the internal cache as a result.  After some time,
references to the class instances are removed, so the class instance
reference in the cache becomes the only existing reference to that class
instance, and since the method is never called with that class instance
as a `self` arg, the corresponding record in the internal cache is never
expired, creating the memory leak as a result.
Introducing `cleanup_self` arg to `@async_ttl_cache` decorator, so while
it's `True` the decorator creates a weak …

Fix paasta api memory leak

---

paasta_tools/cli/cmds/local_run.py
paasta_tools/tron_tools.py
tests/test_tron_tools.py

I know I just made a screencast explaining how to properly use dumb-init with complex shell commands, but we can solve this for every user simultaneously with this option, and eliminate an entire class of user-error by not making them have another set of quotes and stuff with `/bin/sh -c 'something'`
Tron on paasta is greenfield, so I'm not afraid of pushing this change for tron things only.
@chriskuehl

Run all tron actions in paasta with the docker '--init' option

---

paasta_tools/contrib/get_containers_and_ips.py

APOLLO-565: Add a flag on updating haproxy on the map updates.
This commit adds a flag (--update-haproxy) which when provide updates
the haproxy with updated map information. The map file contains
the internal bridge IP address of a service and mesos task information
of the service.
This changes the present default behavior which updates haproxy on every
map update. This is not scalable (often fails with `Errno 11`)
and not needed since with synapse haproxy is restarted quite often.
The map_file is part of haproxy.cfg which means we don't need to
actively update haproxy, instead rely on these restarts for haproxy
to pick up updated info.
Note that we are only changing the default, hence, to revert to old behavior,
the flag (--update-haproxy) needs to be provided wherever it is invoked …

APOLLO-565: Add a flag on updating haproxy on the map updates

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/autoscaler.py
paasta_tools/long_running_service_tools.py
tests/api/test_autoscaler.py

This change
* adds the function get_instances_without_limiting() which gets number of instance required as calculated by autoscaler without limiting.
* adds response parameter calculated_instance which exposes this in the API endpoint v1/services/{service}/{instance}/autoscaling.
This change is to find out the acutal desired instances, since min & max
instance values could be adjusted by the operators/users in emergency
scenarious to pre-scale the services.
Example response now
```
{
"desired_instances": 3,
"calculated_instances": 2
}
```

Expose calculated (pre-limited) number of instance by autoscaler

---

paasta_tools/firewall_update.py
paasta_tools/utils.py
tests/test_utils.py

This removes our hilarious suggestions of:
```
Error: bumpy.main doesn't look like it has been configured to run on the norcal-devc cluster.
Did you mean one of: main, main, main?
Did you mean one of: main, main?
```
Because we are appending the entire suggestion string lolz.
Also I'm not sure why this function is so inefficient, it iterates over *all* services, even though we know the service name?

Fix suggestions on bad instance names

---

paasta_tools/cli/cmds/spark_run.py

The problem can be reproduced by starting two python shell and run pick_random_port('spark'). I am keeping the spark container name (mesos framework name) to minimize name collision.

Added pid to spark pick_random_port hash key

---

paasta_tools/api/api.py

Don't output the following scary exception into the log, as that is expected
when `paasta-api` runs on a master without Kubernetes:
```
ERROR:paasta_tools.api.api:Error while initializing KubeClient
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/api/api.py", line 128, in setup_paasta_api
settings.kubernetes_client = kubernetes_tools.KubeClient()
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/kubernetes_tools.py", line 785, in __init__
kube_config.load_kube_config(config_file='/etc/kubernetes/admin.conf')
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 470, in load_kube_config
config_persister=config_persister)
File …
```

Don't log expected exception for `paasta-api`

---

paasta_itests/chronos_rerun.feature
paasta_tools/chronos_rerun.py
paasta_tools/chronos_tools.py
paasta_tools/cli/cmds/local_run.py
paasta_tools/tron_tools.py
tests/cli/test_cmds_local_run.py
tests/test_chronos_rerun.py
tests/test_chronos_tools.py
tests/test_tron_tools.py

Step 3 of https://github.com/Yelp/paasta/pull/1996
use_percent_format is allowed in the Chronos schema, but it won't be used anywhere. We can remove it after step 4.

Remove percent formatting

---

paasta_tools/utils.py

This was the only other place in our codebase where we were doing unicode decoding with stuff that comes from the user (paasta_print already did it).

Replace unicode errors from user-inputted stuff

---

requirements.txt

Small change to bump task-processing in paasta to 0.1.3.
make test
I'd like to make release and push it to dev and stage, before going to prod. Too safe?

Bump task-processing to 0.1.3 over 0.0.16

---

paasta_tools/long_running_service_tools.py
tests/test_kubernetes_tools.py
tests/test_long_running_service_tools.py

right now we default to looking at 'mode' in smartstack.yaml for
what mode should be used for healthchecks. there is nothing in place
that one must include mode for a service, and healthcheck mode 'should'
be enough. ensure that we look at 'healthcheck_mode' before 'mode' when
figuring out the healthcheck for a service.
also fixes a bug that meant that healthcheck_cmd was ignored if it was
specified in smartstack.yaml rather than the instance config
Edit: I guess this raises the question of what having 2 keys is even for? outside of healthchecks, what do we care about the mode for?

use healthcheck_mode before mode

---

paasta_tools/frameworks/native_service_config.py
paasta_tools/kubernetes_tools.py
paasta_tools/marathon_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

kubernetes requires cmd to be a list of strings, rather than a string.
support splitting a string into a list, or even supplying a list as the
cmd

convert cmd to a list for kubernetes deployments

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

`V1PodCondition.status` is a string, see
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PodCondition.md

Fix `is_pod_ready()` always returns `True`

---

paasta_tools/cli/schemas/tron_schema.json
paasta_tools/tron_tools.py
tests/test_tron_tools.py

In soaconfigs, jobs and actions can be dicts or lists, and the formatted version that we deploy always uses dicts.
Tested setup_tron_namespace against mesosstage, with both lists and dicts in the soaconfig file. The final config is the same either way, and Tron accepts it.

Tron dicts

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Since we don't use cluster DNS for kubernetes, set kubernetes pods DNS
policy to `Default` to prevent the following warnings:
```
Type     Reason             Age                 From                                      Message
----     ------             ----                ----                                      -------
Warning  MissingClusterDNS  1m (x937 over 19h)  kubelet, ip-10-40-11-76.dev.yelpcorp.com  pod: "opengrok-main--k8s-74c99f7487-7tz6p_paasta(d29ca9d6-d2ea-11e8-b7c5-06b74992d402)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
```

Set kubernetes pods DNS policy to `Default`

---

.pre-commit-config.yaml
paasta_tools/cli/fsm/autosuggest.py
paasta_tools/deployd/master.py

See the "Seeing autopep8 failures on Jenkins? Run pre-commit autoupdate" email.

Update pre-commit hooks to fix internal build

---

paasta_tools/deploy_marathon_services
paasta_tools/generate_all_deployments
paasta_tools/paasta_deploy_chronos_jobs
paasta_tools/paasta_deploy_tron_jobs

I added this to all the bash scripts that I think need it?  I guess this could break things somewhere if something's been silently failing and now noisily fails?

set pipefail on our bash scripts

---

paasta_tools/cli/schemas/tron_schema.json

This breaks get_tron_instance_list_from_yaml. I think I left it here for backwards-compatibility, but now there's no reason to allow them for jobs in service directories.
`paasta validate` gets called in the pre-receive for all tron files in service directories.

Null Tron jobs not allowed

---

paasta_tools/cli/cmds/info.py
tests/cli/test_cmds_info.py

Tron uses "[namespace].[job_name].[action_name]", and this breaks paasta info command.

fix paasta info bug

---

paasta_tools/metrics/metastatus_lib.py
paasta_tools/paasta_metastatus.py

Remove `Agent count` column instead of `GPU (used/total)` one.
While here also replaced hardcoded `yelp.com/` prefix for Kubernetes
labels with the `maybe_add_yelp_prefix()` function call.
Before:
```
Per Node Utilization
Region        Hostname                                    CPU (used/total)  RAM (used/total)      Disk (used/total)    Agent count
uswest1-devc  10-40-10-205-uswest1adevc.dev.yelpcorp.com  0.00/16 (0.00%)   100.0M/29.4G (0.33%)  5.8G/58.1G (10.00%)  1
uswest1-devc  10-40-10-244-uswest1adevc.dev.yelpcorp.com  0.00/16 (0.00%)   100.0M/29.4G (0.33%)  5.8G/58.1G (10.00%)  1
uswest1-devc  10-40-11-189-uswest1adevc.dev.yelpcorp.com  0.00/16 (0.00%)   100.0M/29.4G (0.33%)  5.8G/58.1G (10.00%)  1
uswest1-devc  kubestage1-uswest1adevc.dev.yelpcorp.com    0.00/2 (0.00%) …
```

Fix `paasta metastatus -vvv` output for Kubernetes

---

paasta_tools/cli/cmds/metastatus.py

Switch `paasta metastatus` to use the HTTP API endpoint by default.
It can be forced to use the old ssh-based method by specifying a false
value for `USE_API_ENDPOINT` environment variable, e.g.:
```
$ USE_API_ENDPOINT=0 paasta metastatus -c somecluster -vv -a
```

Use HTTP API for `paasta metastatus` by default

---

paasta_tools/cli/cmds/local_run.py
paasta_tools/cli/cmds/secret.py
paasta_tools/secret_tools.py
tests/cli/test_cmds_local_run.py
tests/cli/test_cmds_secret.py
tests/test_secret_tools.py

This will look in the _shared directory for shared secrets when calculating the config hash for any service.
Adding/updating with the CLI works without changes, by passing in `--service _shared`, as long as there is a service.yaml file in the _shared folder for soaconfigs. (See my soaconfigs review.)

Support shared paasta secrets

---

paasta_tools/autoscale_all_services.py
paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/mesos/slave.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_autoscale_all_services.py

Probably best to review the commits independently
* The first is a change to caching which I think is safe? Hopefully nothing long-running is going to break?
* The second makes it possible to run multiple autoscalers (e.g. using xargs). By default it will stick with the current behaviour of iterating through all the services sequentially

Service autoscaler performance stuff

---

paasta_tools/autoscaling/autoscaling_cluster_lib.py
paasta_tools/autoscaling/load_boost.py
paasta_tools/cli/cmds/boost.py
paasta_tools/paasta_cluster_boost.py
tests/autoscaling/test_load_boost.py
tests/test_paasta_cluster_boost.py

I'd like to re-use the cluster boost logic to boost the service
autoscalers on a per-service level. Soon we will only need the
clusterman metrics bit for clusters anyway so I intend to separate that
block completely soon. This is just the refactor and I will add the
changes to the service autoscaler and boost cli in a second commit.
This:
* renames the module to load_boost.
* makes all the functions take a zk_boost_path which is {region}/{pool}
for cluster boost but can be like {cluster}/{service}/{instance} for the
service autoscaler
* adds some tests and tidy up

Re-factor paasta cluster boost

---

paasta_tools/cli/schemas/adhoc_schema.json
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/marathon_tools.py
paasta_tools/utils.py
tests/test_utils.py

I ran setup_marathon_job.py dsc-test-service.gpu manually with below patch on a mesos master. The task can grab 1 gpu and run in a mesos containerizer.
V2: 
*Removed containerizer type from config. Instead, it is inferred depending on if gpu is used.
*Changed gpus type from float to int.

Add the Mesos containerizer to Marathon

---

paasta_tools/paasta_metastatus.py
paasta_tools/paasta_remote_run.py
tests/test_paasta_metastatus.py

The change was tested with 
$ .tox/py36/bin/paasta_metastatus.py -s dsc-test-service -i gpu -vvv
$ .tox/py36/bin/paasta_remote_run.py start -s taskproc_canary -i remote -c norcal-devc

Check get_gpus() return value for meta-status and remote-run

---

paasta_tools/cli/cmds/logs.py

- Sometimes logs are read in as byte strings, but we attempt to decode them as strs, which can result in errors.
- This change checks if log lines are bytes; if they are, we convert them to strs first.
- manual testing
- According @solarkennedy, @EvanKrall may have strong opinions about this. However, given that some people need this, I suggest making this change, at least temporarily, until we can come to an agreement about how to do this better going forward.

Read Marathon and Chronos logs as strings not bytes

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/adhoc_schema.json
paasta_tools/cli/schemas/chronos_schema.json
paasta_tools/cli/schemas/marathon_schema.json
tests/cli/test_cmds_validate.py

This has been undocumented and not allowed via the json schema for a while.

Allow underscores in instance configs for marathon/chronos/adhoc

---

paasta_tools/marathon_tools.py

```
File "/usr/bin/configure_nerve", line 11, in <module>
File "/opt/venvs/nerve-tools/lib/python3.6/site-packages/nerve_tools/configure_nerve.py", line 313, in main
) + get_kubernetes_services_running_here_for_nerve(
File "/opt/venvs/nerve-tools/lib/python3.6/site-packages/paasta_tools/marathon_tools.py", line 1070, in get_marathon_services_running_here_for_nerve
cluster = system_paasta_config.get_cluster()
File "/opt/venvs/nerve-tools/lib/python3.6/site-packages/paasta_tools/utils.py", line 1563, in get_cluster
raise PaastaNotConfiguredError('Could not find cluster in configuration directory: %s' % self.directory)
paasta_tools.utils.PaastaNotConfiguredError: Could not find cluster in configuration directory: /etc/paasta/\u001b[0m …
```

Fix `get_cluster()` throws `PaastaNotConfiguredError` on non-PaaSTA hosts

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

The actual command for `healthcheck_cmd` is a string in SOA config, but
Kubernetes expects a list of `argv`s for it's `V1ExecAction.command`, so
just call `/bin/sh -c` with given command string here.

Fix `healthcheck_cmd` not working for kube

---

paasta_tools/py.typed

Add `py.typed` file, which is a marker required by PEP-561 to indicate
that a package provides typing annotations.
See https://www.python.org/dev/peps/pep-0561/#packaging-type-information
for details.
Tested on [synapse-tools](https://github.com/Yelp/synapse-tools) by running `mypy` with `ignore_missing_imports = False` before and after 
```
$ touch ./.tox/mypy/lib/python3.6/site-packages/paasta_tools/py.typed
```

Add marker that paasta_tools provides typing annotations

---

paasta_tools/cli/cmds/spark_run.py

Tested with a spark run with --spark-args "spark.cores.max=10 spark.executor.cores=5" and make sure the docker run command on the mesos agent has "--cpus=5".

Constrain the maximum cpu a Spark executor can use

---

paasta_tools/chronos_tools.py

Some chronos service instances depend on template "instances", which start with underscores. They are not valid instance names but are valid template names, but we don't differentiate between the two when loading dependencies. This change creates an exception during that loading process.

Ignore starting underscores in instance names in chronos dependencies

---

paasta_tools/cli/cmds/cook_image.py

- By default, we set `soa_dir` in `paasta_cook_image` to None, instead of `DEAULT_SOA_DIR`, which causes service name validation to fail.
- I've added the local yelpsoa-configs directory option (-y) to cook-image as well as a conditional to use the default arg, so that service name validation passes.
- manual testing

Add -y option for cook-image

---

example_cluster/dind-cluster-v1.11.sh
example_cluster/example-cluster-test-k8s.sh

Looks like this script has been changing upstream and I assume the
docker images it pulls have changed too hence ours isn't working. This
pulls the latest version from the upstream repo which should hopefully
work.
See https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/262
for a discussion on the idea of making this script static once released
and tagging the docker images so they don't change
Also see
https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/255 which
I think is the actual issue for the problem.

Try with the latest k8s dind script

---

paasta_tools/cli/cmds/local_run.py
tests/cli/test_cmds_local_run.py

- This change causes local-run to stream docker logs while health checking
- I have also removed the complete docker log output after health checking, given that we are streaming. Now, only the container exit code is printed.
- Manual testing with the `example_happyhour` service
- log output example: https://gist.github.com/kawaiwanyelp/6945e383e6a82b6ead09b21fcfee40b5
- Getting the next log line is done via `next(generator)`. This call blocks until the generator finishes, or there is a new log line available. As a result, this call cannot be on the main thread; it must be in its own thread. If the generator is already 'executing', there isn't a way to close it, even with `generator.close()`, which raises an exception telling the caller that the generator is still executing. Hence, after …

Stream docker logs while healthchecking local-run

---

paasta_tools/mesos_tools.py
tests/test_mesos_tools.py

Sometimes they don't have dots and I think we can ignore these because
they won't be paasta services.
I think this is safe? This was breaking graceful_mesos_shutdown but the code is used by configure nerve so we should be pretty careful that this makes sense...

Catch error parsing mesos task IDs

---

paasta_tools/marathon_tools.py

The volumes key was left out previously. The marathon 1.4 documentation wasn't clear about whether it is supported. I have tested this in pnw-devc with dsc-test-service.gpu to cat one of paasta mounted file.

Added volumes to mesos containerizer marathon dict

---

yelp_package/extra_requirements_yelp.txt

pre-commit end-of-file newline fixer keeps wanting to modify paasta secrets. @Qmando made vault-tools add a newline to the end of the secrets files back in June, but we're running a version from March. This bumps to the latest version.

Bump vault-tools to get newlines at end of secrets files

---

yelp_package/extra_requirements_yelp.txt

Fixes token error on `paasta secret add` caused by incompatible return
type from the previous version of vault_tools...

Bump vault_tools

---

paasta_tools/cli/cmds/local_run.py

Before this change:
`Error: No deployments.json found in ../yelpsoa-configs/my_service.You can generate this by running:generate_deployments_for_service -d ../yelpsoa-configs -s my_service`

Add spacing between sentences

---

paasta_tools/cli/cmds/check.py
paasta_tools/cli/utils.py
tests/cli/test_cmds_check.py

I like that `get_deploy_group` returns `None` on tron stuff. 
But I think the tools that print the listed deploy groups should filter it out.

Filter out 'None' deploy groups now that we have tron

---

paasta_tools/cli/cmds/security_check.py

We sort of forgot this existed because it hasn't been working. Now that it's working again, we're finding it disruptive. We'd like to remove the sensu alerting for now while we re-think how to do this (it'll probably end up being implemented inside the security-check command itself).
(This is APPSEC-998 internally.)

don't emit sensu events from security-check

---

paasta_tools/remote_git.py

It is taking longer than 20s in yelp-main, since the repo is so big. Increasing timeout should be helpful.
More details are [here](https://jira.yelpcorp.com/browse/PAASTA-15089).

increase timeout when talking to git

---

paasta_tools/cli/cmds/remote_run.py
paasta_tools/paasta_remote_run.py
tox.ini

- Currently, `remote-run` args are sort of wonky:
- Some args do not and cannot work (e.g. `-y`, which cannot work since `paasta remote-run` SSHs to a master to run a task, and so cannot take local soa-configs with it)
- Some args do not work but should (e.g. `--dry-run`)
- Some args are internal, but are exposed via `paasta remote-run` (e.g. `--aws-region`, which determines which dynamodb table we persist to; this isn't a user concern, however)
- In this PR, I have:
- Reorganized arguments so that actions only have the options specific to them instead of sharing some irrelevant ones
- Moved 'internal' options to `paasta_remote_run`, which is 'called' from `paasta remote-run`, but isn't meant to be publicly used (like `-y`, `--debug`, etc.)
- Make `--dry-run` work
- manual testing (since …

Reorganize remote-run args and make paasta_remote_run respect `--dry-run`

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

Tested this locally and the SparkSignal continues work when we send the additional dimensions

send webui_url as well as framework_name to Clusterman during spark-run

---

paasta_tools/cli/cmds/mark_for_deployment.py

(Follow-up to #1959)
Quite a few people have expressed that having the "Authors" ping inside a thread can be annoying. I agree -- while it keeps the notifications in the main channel concise, it makes it hard to dismiss the notifications (you have to actually open the thread in Slack).
Let's try moving the authors list back into the original message, while keeping the rollback instructions, Jenkins links, etc. in the thread?
It looks like this:

Move authors back above the thread in mark-for-deployment's Slack notifications

---

requirements.txt

`itest_trusty` for the yelp package is failing a good portion of the time (unsure why not always?) with
```
21:24:40 [trusty] Error: version conflict: requests 2.19.0 (.tox/manpages/lib/python3.6/site-packages) <-> requests>=2.21.0 (from hvac>=0.2.17->vault-tools==0.7.24->-r /work/requirements.txt (line 120))
```

bump requests to 2.21.0 to fix failing itest_trusty

---

docs/source/yelpsoa_configs.rst

This adds documentation for the `fixed_delay` field in `smartstack.yaml`.
Please see the (internal, see branch name) related ticket for more information.
`make docs` passes with this as result:

Document delay injection in smartstack.yaml

---

paasta_tools/cli/cmds/mark_for_deployment.py

Whoops. In #2090 I missed this, we're including authors in both the thread and the initial message now for this one specific message.

Remove duplicate authors list on "Finished deployment"

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

1. removed spark_ui_port from Jupyter spark.app.name. create_spark_session() will append a fresh ui_port to spark.app.name.
2. Dot not print Spark monitoring URL for the jupyter command. It will be printed from create_spark_session() in notebooks. 
3. removed pyspark as the default command so that command in instance_config can be picked up.

Remove spark_ui_port from Jupyter spark.app.name

---

paasta_tools/cli/cmds/remote_run.py
paasta_tools/paasta_remote_run.py

- Currently, remote-run does not support retries.
- I've added an option to specify the number of retries remote-run should do; by default it is 0.
- Currently, if remote-run finishes (by success or failure), it does nothing more. If the user does a detached run or otherwise is not watching remote-run go, then the user would never know the results of the task until they check things manually.
- I've added email notifications to alert the user of the results of the final attempt of the task run.
- The user's email address defaults to the $EMAIL env variable, but can be set manually. If the env variable is not set or the user doesn't specify an email address, there will be no notification. This will happen if remote-run is used by, say, a non-human user.
- manual testing on norcal-devc
- …

Add remote-run retries and notification emails

---

paasta_tools/contrib/paasta_update_soa_memcpu.py

The pre-commit hook for yelpsoa-configs uses width=120.

Set yaml width to 120 for rightsizing script

---

paasta_tools/cli/cmds/secret.py

Sometimes you could accidentally encrypt an empty string and since that generates a non-empty ciphertext, you might not notice.

Add a warning if the secret is empty

---

paasta_tools/paasta_serviceinit.py

I'm not sure why we ignore `interactive` instances. This behavior triggers a bug for services that have only `interactive` instances, where return_codes has no entries, so `sys.exit(max(return_codes))` prints a traceback.
Seems like we should just go ahead and try to look for remote run `interactive` instances.

Show status for 'interactive' adhoc instances too.

---

paasta_tools/autoscaling/load_boost.py

* make flake8 shut up about white space
* pass in the pool as the app_identifier for clusterman.  This works right now because we assume that the pool name and the app identifier are the same thing, this will break at some point in the future if/when that assumption no longer holds.  But honestly, I'm kinda hoping we're not using boost at that point anyways so *shrug*
Confirmed this works on the jade_m5 pool.

make boost work for non-default pools

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

I think this is the only extra thing I need to run a basic operator as a
paasta service.

Allow setting service account for k8s

---

paasta_tools/secret_providers/__init__.py
paasta_tools/secret_providers/vault.py
tests/secret_providers/test_vault.py
yelp_package/extra_requirements_yelp.txt

This makes it possible to override the vault transit key used for
encyption/decryption in service.yaml. This will allow services to
specify their own key and then customise the policies to determine who
has access to decrypt/encrypt.

Make vault key settable

---

paasta_tools/marathon_tools.py
tests/test_marathon_tools.py

There are some other apps also want to use marathon which make deployd unhappy. The change ignore all marathon apps if they are not the top folder, so that we can have a better work separation.

ignore folders in marathon

---

.travis.yml
Makefile
paasta_tools/autoscaling/pause_service_autoscaler.py
requirements-dev.txt
tox.ini

Any particular reason we need that pin?
The reason i made this PR is `make test` was failing worse than it usually does on macos.

Bump versions of pip, tox and virtualenv in Makefile, make tests pass on macos

---

paasta_tools/cli/cmds/autoscale.py
paasta_tools/cli/cmds/cook_image.py
paasta_tools/cli/cmds/emergency_restart.py
paasta_tools/cli/cmds/emergency_start.py
paasta_tools/cli/cmds/emergency_stop.py
paasta_tools/cli/cmds/generate_pipeline.py
paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/cmds/pause_service_autoscaler.py
paasta_tools/cli/cmds/push_to_registry.py
paasta_tools/cli/cmds/rerun.py
paasta_tools/cli/cmds/secret.py
paasta_tools/cli/cmds/start_stop_restart.py
paasta_tools/cli/utils.py
paasta_tools/utils.py
tests/cli/test_cmds_cook_image.py
tests/cli/test_cmds_generate_pipeline.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_pause_service_autoscaler.py
tests/cli/test_cmds_push_to_registry.py
tests/cli/test_cmds_rerun.py
tests/cli/test_cmds_secret.py
tests/cli/test_cmds_start_stop_restart.py
tests/test_utils.py

This commit creates an "audit log" of administrative actions taken on services
and clusters. The goal of this log is to provide a central view of actions
being taken to services across the platform. Currently this information is both
incompletely and inconsistently logged, and the information that is logged is
distributed across every service's individual logs, which is challenging and
slow to collate.
This change also renames the setting for the 'file' log writer that was
previously named 'delimeter' to 'delimiter', because spelling.
I've tested this change by:
* running the unit tests (spoiler: they passed)
* running the itests (spoiler: they passed)
* poking around with the [example cluster](https://paasta.readthedocs.io/en/latest/installation/example_cluster.html)
The example cluster …

Creates an audit log across services

---

paasta_tools/kubernetes_tools.py
paasta_tools/setup_crd.py
paasta_tools/setup_kubernetes_job.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py
tests/test_setup_crd.py
tests/test_setup_kubernetes_job.py

Pushing for early feedback. This is a script that allows us to specify a
file prefix like flinkcluster- or cassandra- etc. and map it to a
kubernetes custom object like FlinkCluster. For now it just adds the
neccessary metadata and submits the instances YAML config as the spec for
the k8s object. Like other paasta things we sha and check the sha to see
if we need to update.
Unit tests to follow if we think this is the way to go.

Add setup custom resource script

---

paasta_tools/cleanup_kubernetes_crds.py
paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_crd.py
paasta_tools/setup_kubernetes_job.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_job.py

Probably easiest to review commits separately:
* Prefix paasta k8s labels with paasta_ 
* Enable registration of non-paasta k8s services
I haven't been careful to make this backwards compatible. Right now it takes destroying the exisiting resources and causes de-registration of running things in nerve. I think I'm okay with that at the moment because we don't have too much running. I have tested this on kubestage and it will require a bump of nerve-tools too.

K8S nerve updates

---

paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_cr.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_cr.py

This makes it possible to set the CustomResources that we will sync in
kubernetes as a paasta config dictionary. Means we can add more custom
resources without releasing paasta_tools.

Add config for kubernetes custom resources

---

paasta_tools/cli/schemas/tron_schema.json
tests/cli/test_cmds_validate.py

- In order to complete adding disk support to Tron, we need to make sure tronfigs can be validated by paasta, which includes the new disk field
make test

Add disk to tron validation

---

paasta_tools/setup_kubernetes_cr.py
tests/test_setup_kubernetes_cr.py

We need to list all services not just ones with known instance types. By
definition custom CRs can have many file prefixes.

List all services for setup_kubernetes_cr

---

paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

This is so I can test a new version of hacheck with a patch to read the
service IP from X-Haproxy-Server-State as we already do for marathon
ports. If this works then we wont need hacheck in a sidecar for
kubernetes services.

Make using hacheck sidecars optional

---

paasta_tools/cli/cmds/security_check.py

Raise `paasta security-check` timeout to 3600 seconds to match `paasta itest`.
The security-check command now builds a service image for itself if it can't find the one created by `paasta itest`, that means we sometimes hit the 300s timeout. 3600s (the same as `paasta itest` has) should be sufficient (since security-check should take no longer than itest).

raise `paasta security-check` timeout

---

paasta_tools/list_marathon_service_instances.py
paasta_tools/metrics/metastatus_lib.py
tests/metrics/test_metastatus_lib.py
tests/monitoring/test_check_marathon_has_apps.py

Fix issue of deployd: https://fluffy.yelpcorp.com/i/1Lwj7NqfBwpc8NHrqtPDxPjjN2J53PCR.html
git grep list_apps and trying to make them all use marathon_tools instead.

marathon list_apps should use the function from marathon_tools

---

paasta_tools/cli/cmds/metastatus.py
paasta_tools/paasta_metastatus.py
tests/test_paasta_metastatus.py

Test
```
(py36) mingqiz@dev9-uswest1cdevc:~/paasta/paasta_tools/api/views (PAASTA-9049) $ paasta metastatus  -s example_happyhour -c mesosstage -i main -vv
here
paasta-mesosstage.yelp:5054
Master paasta_tools version: 0.83.5
Master leader: 10-40-11-110-uswest1adevc.dev.yelpcorp.com
Mesos Status: OK
Quorum: masters: 3 configured quorum: 2
Frameworks:
Framework: marathon count: 3
Framework: chronos count: 1
CPUs: 4.34 / 297 in use (1.46%)
Memory: 15.76 / 1294.35GB in use (1.22%)
Disk: 24.00 / 7972.80GB in use (0.30%)
No GPUs found!
Tasks: running: 9 staging: 0 starting: 0
Nodes: active: 15 inactive: 0
Resources Grouped by region
Region        CPU (used/total)  RAM (used/total)    Disk (used/total)   GPU (used/total)  Agent count
uswest1-devc  4.34/297 (1.46%)  15.8G/1.3T (1.22%)  24.0G/7.8T …
```

added mesos leader to metastatus command output

---

paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_status.py

Switch `paasta status` to use the HTTP API endpoint by default.
It can be forced to use the old ssh-based method by specifying a false
value for `USE_API_ENDPOINT` environment variable, e.g.:
```
$ USE_API_ENDPOINT=0 paasta status -c somecluster -s someservice -i someinstance -vv
```

Use HTTP API for `paasta status` by default

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

- As in title
- For now, we do not want to turn on tron monitoring in paasta if a job does not have monitoring set. However, we do want to expose the job's team no matter what.
- manual testing

Expose tron monitoring info to paasta

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

- Filter non-tron monitoring keys, since if we pass them through, tron will freak out
make test
- I wanted to use `paasta_tools.cli.cmds.validate.get_schema`, but that would be a circular dependency because `validate` depends on `tron_tools`. I still wanted to use the tron schema as the source of truth, so I decided to "copy" the `get_schema` functionality over to `tron_tools`. It is a little ugly :(

Filter non-tron monitoring keys

---

paasta_itests/README.md
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/cli/cmds/status.py
paasta_tools/cli/utils.py
paasta_tools/flinkcluster_tools.py
paasta_tools/utils.py
tests/test_utils.py

```shell
$ paasta status -c kubestage -s compute-infra-test-service -i flink-stream-sql-demo
service: compute-infra-test-service
cluster: kubestage
instance: flink-stream-sql-demo
Flink version: 1.6.3
Jobs: 1 running, 0 finished, 0 failed, 0 cancelled
10 taskmanagers, 17/20 slots available
Jobs:
Job Name                         State       Started
scribeheartbeat_auditing         RUNNING     2019-02-25 06:44:35 (7 hours ago)
$ paasta status -c kubestage -s compute-infra-test-service -i flink-stream-sql-demo -v
service: compute-infra-test-service
cluster: kubestage
instance: flink-stream-sql-demo
Flink version: 1.6.3 54e6cde @ 18.12.2018 @ 02:34:17 UTC
Jobs: 1 running, 0 finished, 0 failed, 0 cancelled
10 taskmanagers, 17/20 slots available
Jobs:
Job Name                         State …
```

`paasta status` for Flink on Kubernetes

---

yelp_package/dockerfiles/itest/chronos/Dockerfile
yelp_package/dockerfiles/itest/marathon/Dockerfile
yelp_package/dockerfiles/itest/mesos/Dockerfile

There isn't a 1.7.2 package just yet in the mesossphere apt repos.  I'll make myself a reminder to check for that next week.

use mesos 1.7.1 in itests

---

paasta_tools/cli/cmds/check.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/cli/test_cmds_check.py
tests/test_tron_tools.py

If the deploy_group doesn't exist in deploy.yaml, the error message looks like:
✗ tron-mesosstage.yaml is invalid:
deploy_group everything1 is not in deploy.yaml
More info: http://tron.readthedocs.io/en/latest/jobs.html

validate deploy groups for Tron in paasta validate

---

docs/source/yelpsoa_configs.rst

- Updated the docs to reflect the new tron monitoring behavior, where paasta now defaults to `monitoring.yaml`.
- Related to: https://github.com/Yelp/Tron/pull/621

Add docs for monitoring defaults

---

paasta_tools/setup_kubernetes_cr.py
tests/test_setup_kubernetes_cr.py

we want the initial state to be running: this'll have the same semantics
as paasta start/stop, where any changes to the desired state are
forgotten with each deployment

set the desired state of the custom resource

---

paasta_tools/cli/cmds/status.py

```
$ paasta status -c kubestage -s stream_sql
service: stream_sql
cluster: kubestage
instance: main_k8s
Flink version: 1.6.4
State: running
Jobs: 2 running, 0 finished, 1 failed, 0 cancelled
```

Show flink cluster state in `paasta status`

---

paasta_tools/cli/cmds/status.py
paasta_tools/flinkcluster_tools.py

```
$ paasta status -c kubestage -s stream_sql -i main_k8s
service: stream_sql
cluster: kubestage
instance: main_k8s
Flink version: 1.6.4
URL: http://flink.k8s.paasta-kubestage.yelp:31080/stream--sql-main--k8s
State: running
Jobs: 2 running, 0 finished, 0 failed, 0 cancelled
10 taskmanagers, 74/80 slots available
Jobs:
Job Name                         State       Started
copy_of_scribeheartbeat_auditing RUNNING     2019-03-13 10:22:08 (a day ago)
scribeheartbeat_auditing         RUNNING     2019-03-13 10:22:43 (a day ago)
$ paasta status -c kubestage -s stream_sql -i main_k8s -v
service: stream_sql
cluster: kubestage
instance: main_k8s
Flink version: 1.6.4 6f41481 @ 14.02.2019 @ 20:51:48 CST
URL: http://flink.k8s.paasta-kubestage.yelp:31080/stream--sql-main--k8s
State: running
Jobs: 2 …
```

Show flinkcluster dashboard URLs without -v flag

---

paasta_tools/utils.py

Sometimes logs are going to have extra newlines at the end, which makes paasta logs look funny.

Strip leading and trailing whitespace in paasta logs

---

paasta_tools/autoscaling/load_boost.py

`set_boost_factor` is only called in two places:
* [clear_cluster_boost](https://github.com/Yelp/paasta/blob/master/paasta_tools/autoscaling/load_boost.py#L224) which isn't setting `send_clusterman_metrics`
* [paasta_cluster_boost](https://github.com/Yelp/paasta/blob/master/paasta_tools/paasta_cluster_boost.py#L117) which is already setting it.
Let's just make it the default.

make sure we send clusterman metrics when clearing the boost

---

paasta_tools/cli/cmds/local_run.py
paasta_tools/cli/cmds/spark_run.py

`paasta local-run --dry-run` is supposed to print a JSON dict like this:
```
$ paasta local-run --dry-run -s yelp-main -c norcal-devc -i main
["paasta_docker_wrapper", "run", "--env", "PAASTA_SERVICE", "--env", "PAASTA_INSTANCE", "--env", "PAASTA_CLUSTER", "--env", [...]
```
However when a volume is missing, it prints this as the first line (to stdout):
```
Warning: Path /nail/live/private does not exist on this host. Skipping this binding.
```
This then causes tools that try to parse the output to try to parse the warning as JSON. Let's send it to stderr instead?
Before:
```
$ paasta local-run --dry-run -s yelp-main -c norcal-devc -i main | jq .
parse error: Invalid numeric literal at line 1, column 2
```
After:
```
$ paasta local-run --dry-run -s yelp-main -c norcal-devc -i main | jq . …
```

Use stderr for warning about missing volumes

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

This is roughly ready but I'm still doing some full tests of using this to run mrjobs on an actual cluster.

add spark-run option for mrjobs

---

paasta_tools/deployd/master.py
paasta_tools/deployd/metrics.py
paasta_tools/deployd/watchers.py
paasta_tools/deployd/workers.py
tests/deployd/test_deployd_master.py
tests/deployd/test_metrics.py
tests/deployd/test_watchers.py
tests/deployd/test_workers.py

I think this is an easier to understand name, in the code and on the graphs.
I'll make one PR per rename for my own sanity and so we can bikeshed things one at a time.

Rename the deployd inbox_q to 'instances_that_need_to_be_bounced_in_the_future'

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/tron/client.py

This is an experimental branch to see what it would take to get tron stuff in `paasta status`.
I think I want `paasta status` to be able see tron stuff for a couple reasons:
* Gets users to "feel" like they are interacting with paasta?
* Understands the `--cluster` argument instead of requiring users to "be" in the right place
But there are some serious downsides:
* The concept of looking at a whole "job" doesn't match up with the status api (which looks at individual actions
* The concept of a run_id doesn't fit anywhere in the paasta api?
* Idk, I just feel like it would take a lot of work to get feature parity with tronview.
Is this the direction you think we should go? (getting paasta status with feature parity with tronview?)

RFC: Added tron support in the paasta api

---

paasta_tools/cli/cmds/secret.py
paasta_tools/cli/schemas/adhoc_schema.json
paasta_tools/cli/schemas/chronos_schema.json
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/cli/schemas/tron_schema.json
tests/cli/test_cmds_secret.py

Secret names with dashes are commonly used, like `my-secret`. But dashes aren't allowed in bash variables.

Remove characters that are not allowed in env vars

---

paasta_tools/autoscaling/load_boost.py
paasta_tools/paasta_cluster_boost.py
tests/autoscaling/test_load_boost.py
tests/test_paasta_cluster_boost.py

In #2179 I tried to made sure we were sending clusterman metrics when we cleared the boost (I think that since we switched to using Clusterman we haven't been clearing the boost), but I didn't realize that I needed to fix some of the wiring.  This PR fixes that and adds a test of the clusterman_metrics functionality in the `load_boost` module.

fix cluster boost clearing script

---

paasta_tools/automatic_rollbacks.py
paasta_tools/cli/cmds/mark_for_deployment.py
tests/cli/test_cmds_mark_for_deployment.py

This doesn't yet introduce the `abandon`/`complete` states, but it does let you roll back while waiting for deployment, and roll forward when waiting for rollback.

Have the wait-for-deployment state machine also wait for rollback.

---

paasta_tools/contrib/kill_bad_containers.py

It looks like this happens every once in a while in the past 30 days. 
I don't know why, so I've made the script print out what it does know and exit non-zero so we'll get a ticket. (instead of stack tracing)

Make kill_bad_containers handle the edge case where a second container is missing

---

paasta_tools/cli/cmds/local_run.py

This is pretty easy to repro with a bash script that redirects stdin:
```
paasta local-run --skip-secrets --pull --no-healthcheck --cluster foo --service bar --instance batach  --cmd '/bin/true' </dev/null
...
the input device is not a TTY
```
But we only want `--tty` when the *input* is a tty, output doesn't really matter.

Only use a tty for local-run if stdin is a tty.

---

paasta_tools/cli/cmds/mark_for_deployment.py

Print the command to roll back at the same time that we send the slack message.

move rollback command earlier

---

paasta_tools/automatic_rollbacks.py
paasta_tools/cli/cmds/mark_for_deployment.py
tests/cli/test_cmds_mark_for_deployment.py

Add complete and abandon states; make deployed/rolled_back not terminal.
This makes the user click a button before we exit, giving them the chance
to roll back even once the deploy is at 100%.

Add complete/abandon states

---

paasta_tools/check_spark_jobs.py
setup.py

Add the script to bin/, and make sure there is no output if there are no long-running frameworks we want to report.

Fixups to check_spark_jobs

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

This will have the effect of running Spark driver docker container with extra parameters `--runtime=nvidia --env NVIDIA_VISIBLE_DEVICES=all`, which will allow deep learning libraries such as tensorflow-gpu running inside Spark driver process to work. Such libraries can then be used inside the driver process to build the model which even though does not need GPU compute, it does require CUDA for the library initialisation to complete.

Add --nvidia command line option to spark-run

---

paasta_tools/cli/cmds/secret.py

This is just used by humans at the moment so we haven't cared about the
whitespace that much. I've updated a runbook where I tell people they
can "recreate" a secret using this as the stdin. We need to not print
the newline in that case.

Don't print newline when decrypting

---

paasta_tools/deployd/master.py
paasta_tools/deployd/metrics.py
paasta_tools/deployd/watchers.py
paasta_tools/deployd/workers.py
tests/deployd/test_deployd_master.py
tests/deployd/test_metrics.py
tests/deployd/test_watchers.py
tests/deployd/test_workers.py

`instances_that_need_to_be_checked_up_on` is the best string I can think of that represents what the `inbox.to_bounce` list "is".

Renamed 'inbox' gauge to 'instances_that_need_to_be_checked_up_on'

---

paasta_tools/cli/cmds/check.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/cli/test_cmds_check.py
tests/test_tron_tools.py

This is a small refactor to make it easier to use the same deploy_group validation code we have in tron for all things.

Dry out git_pipeline_deploy_groups

---

paasta_tools/cli/cmds/spark_run.py
paasta_tools/clusterman.py
yelp_package/extra_requirements_yelp.txt

Core ML suggested we always print the message in spark_tools, so doing the same here. If it's over the warning threshold, the message turns red and gets an extra "WARNING". 
Example:
```
$ python paasta_tools/cli/cli.py spark-run --cmd pyspark
Please wait while the image (docker-paasta.yelpcorp.com:443/services-spark:paasta-aaef4e8357a941b35085da120b6572e9a876e721) is pulled (times out after 5m)...
paasta-aaef4e8357a941b35085da120b6572e9a876e721: Pulling from services-spark
Digest: sha256:57821f1f7f23249e105ac154a8ce4543297d4a9d135e93f44ad1c5aaa9f34180
Status: Image is up to date for docker-paasta.yelpcorp.com:443/services-spark:paasta-aaef4e8357a941b35085da120b6572e9a876e721
Spark monitoring URL http://dev54-uswest1adevc.dev.yelpcorp.com:45653
Sending resource request metrics to …
```

Print message about cost when emitting resource request for Spark

---

debian/paasta-tools.links

Stop using the compatibility dir and use the standard completion dir, introduced in bash-completion 2.x. Completion scripts in there are lazily loaded, which defers the ~40ms cost of invoking the completion registration.

Place the bash completion script in the completion dir

---

paasta_tools/docker_wrapper.py
tests/test_docker_wrapper.py

Internal tracking ticket: PAASTA-15442
This will enable us to workaround
https://github.com/github/gh-ost/issues/734

Change the max hostname length to be 60 instead of 63.

---

debian/paasta-tools.links
paasta_tools/dump_locally_running_services.py
setup.py

Adds a script to dump the output of `get_marathon_services_running_here_for_nerve` in JSON format on the command line.
This will be used to determine which services are running on the current host in order to set up proper proxy routing.
Since this script just calls `get_marathon_services_running_here_for_nerve` directly, the existing tests in `tests/test_marathon_tools.py` and `paasta_itests/marathon.feature' are sufficient.

Paasta dump locally running services script

---

paasta_tools/cli/cmds/itest.py

to allow for services whose itests take longer than an hour.

Add --timeout parameter to paasta itest

---

paasta_tools/api/client.py
paasta_tools/utils.py
requirements-minimal.txt
requirements.txt
tests/api/test_client.py

This is so we can support SSL from the swagger client. This is only
enabled once we configure https endpoints for our API. It also supports
presenting client certificates. I tested this all with the
example-cluster and an nginx proxy and it seems to work fine.

Support SSL for paasta-api client

---

example_cluster/paasta/clusters.json
general_itests/deployments_json.feature
general_itests/fake_etc_paasta/clusters.json
general_itests/fake_soa_configs/fake_deployments_json_service/marathon-test-cluster.yaml
general_itests/steps/deployments_json_steps.py
paasta_tools/utils.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_status.py
tests/test_utils.py

rather than dynamically generating the list out of a regex, use the list
of clusters that is defined in system paasta config. This will stop files
distributed with yelpsoa-configs but not managed by paasta-tools from
causing issues when they have unexpected naming conventions
internal ticket PAASTA-15450 - accompanying puppet review /r/404806 which needs to be shipped first

move source of truth of valid clusters to config

---

paasta_tools/contrib/get_container_allocation.py
paasta_tools/contrib/get_running_task_allocation.py

I was thinking we could run this in a cron job, pipe the output of this into a scribe log, and ingest that into splunk.
The contents of this log should be enough to track how long each task runs and how many resources it uses. We can also join this with the DockerStats logs, for utilization data, through the mesos_container_id - the DockerStats include container_name, which is just `mesos-{mesos_container_id}`. 
Does this look reasonable?

Script for getting resource allocation for each task

---

paasta_tools/contrib/get_running_task_allocation.py

Small fix - the script returns a KeyError on Jenkins frameworks, which don't have container info in the task. The other keys the script expects are `statuses` and `resources`, which I think will always exist.

Mesos task does not always have container info

---

paasta_tools/cli/cmds/spark_run.py
paasta_tools/utils.py
tests/cli/test_cmds_spark_run.py
tests/test_chronos_tools.py
tests/test_marathon_tools.py

For spark-run we need to manually override the value, because it loads other instance configs (e.g. adhoc, marathon, etc).

Add instance type as env variable

---

paasta_tools/automatic_rollbacks/slo.py

This fixes the crash we saw on Friday.

Don't crash if no SLOs are defined for a service.

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

- As it's needed by operator-sdk for some functionalities like leader election, see https://github.com/operator-framework/operator-sdk/blob/a9ee17ecae3d1de4e1231ed46fb4d6bc69769054/pkg/k8sutil/k8sutil.go#L94

Pass POD_NAME to kubernetes pods

---

paasta_tools/cli/cmds/spark_run.py

make test
.tox/py36-linux/bin/paasta spark-run --spark-args 'spark.history.fs.logDirectory=s3a://TEST_PATH ' --cmd history-server

Fix spark-run history-server class path

---

paasta_tools/marathon_tools.py
tests/test_marathon_tools.py

This is part 1 for CORESERV-7915 (internal ticket). It makes `get_marathon_services_running_here_for_nerve(...)` return the deploy group and paasta instance for each service instance. Part 2 of the same ticket happens in `nerve-tools` where we add this information to each service's labels.
We might also want to do that in the future for Kubernetes service when these become a thing but for now this is out of scope; someone attempting canary instance routing on a Kubernetes service will only be unable to do it.
All tests pass; I've had to modify three to include the new data and `autopep8` had some fun but no other major changes to tests were required.

Return deploy_group and paasta_instance for marathon services

---

paasta_tools/deployd/common.py
paasta_tools/deployd/workers.py
tests/deployd/test_common.py
tests/deployd/test_deployd_master.py
tests/deployd/test_watchers.py
tests/deployd/test_workers.py

We currently include bounces where we just run setup_marathon_job and
find that the state is already good. In our dashboards we mostly exclude
this by just excluding stuff less than 60s which is the default sleep
between reprocessing. That's not always the case though if the queues
are busy or we ever change that sleep. This should ditch the metric for
things that aren't processed more than once i.e. they aren't really
bounced.

Fix deployd bounce_length timer

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Since now we're using CoreDNS to resolve service IPs, let's switch back
to using `ClusterFirst` DNS policy for kube pods.

Use ClusterFirst DNS policy for kube pods

---

debian/paasta-tools.links
docs/source/generated/paasta_tools.cleanup_kubernetes_crd.rst
docs/source/generated/paasta_tools.rst
paasta_tools/cleanup_kubernetes_crd.py
setup.py

Since we're using `*_kubernetes_crd` names everywhere else, and also use `cleanup_kubernetes_crd` in the existing crontab, let rename `cleanup_kubernetes_crds` into `cleanup_kubernetes_crd`.

mv cleanup_kubernetes_crds cleanup_kubernetes_crd

---

paasta_tools/autoscaling/autoscaling_service_lib.py
tests/autoscaling/test_autoscaling_service_lib.py

This will provide us with detailed information about steady state operation of the autoscaler, most common failure modes and provide the data we'll use to set thresholds for automatic alerting about dangerous utilization before moving ahead with that.
I considered writing to clog directly here but it's inside a loop for all the master's autoscaling decisions, so stdout getting piped over seems preferable almost? Downside is that a service's (not the central) log will be harder to read without grepping for `event`. Open to ideas here.
Make test green. Make itest green.
This is tracked by PAASTA-15443.

Begin logging service autoscaler state in a json format

---

paasta_tools/deployd/master.py
paasta_tools/deployd/workers.py
paasta_tools/setup_marathon_job.py
tests/deployd/test_workers.py
tests/test_setup_marathon_job.py

I'm trying my best to really understand how deployd works.
My queue renaming helps, but there is still the `to_bounce` queue, which isn't really the bounce_now or bounce_later queues.
I have a hunch that we might have a bottleneck on the single inbox worker. I also think we could get rid of the bounce_now queue entirely and just have a bounce_now and bounce_later queue.
For now this is just more logging and stuff.

Updated deployd logging a bit

---

paasta_tools/cleanup_tron_namespaces.py
paasta_tools/list_tron_namespaces.py
paasta_tools/setup_tron_namespace.py
paasta_tools/tron_tools.py
tests/test_tron_tools.py

This isn't "that" much simpler than the other PR I guess.
But fundamentally this "simplifies" the code in two ways:
* we remove code that existed to support reading namespaces in non-service dirs
* We remove the "other_config" concept, and explicitly load the MASTER namespace in its own way, instead of treating MASTER namespaces and service namespaces like they are the same.

Only support configuring tron jobs from service directories

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

set intelligent defaults for spark.sql.shuffle.partitions.
Spark sets a default value of 200. 
We set it to default to 2*spark.cores.max, and print a warning message that ideally the user
should be setting this themselves.
Also, added tests that verify that we default to twice the number of max cores only when the 
user does not provide a value for spark.sql.shuffle.partitions.
make test green.

Spark set intelligent defaults shuffle partitions

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

make test green
make itest green
This review changes paasta spark-run to set the aws_region in the environment, in 
addition the the aws creds which are already set in the environment.
We want aws_region to be set in the environment because we are removing aws creds management from spark_etl, and many flows in spark_etl require an aws region to be specified.

Coreml 838 set aws region spark run

---

paasta_tools/automatic_rollbacks/slack.py
paasta_tools/automatic_rollbacks/state_machine.py
paasta_tools/cli/cmds/mark_for_deployment.py
tests/automatic_rollbacks/test_slack.py

1. call `send_initial_slack_message` in `SlackDeploymentProcess.__init__` to avoid the race condition where the `periodically_update_slack` thread fails because `self.slack_channel_id` hasn't been initialized yet
2. Add a method to check if a deploy process is done, for the srv-configs integration

Small updates to deployment processes

---

docs/source/yelpsoa_configs.rst
general_itests/fake_soa_configs_local_run/fake_simple_service/tron-test-cluster.yaml
general_itests/fake_soa_configs_tron/fake_simple_service/tron-test-cluster.yaml
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/cli/test_cmds_status.py
tests/test_tron_tools.py
tests/test_utils.py

I was able to unify the `job` loading code, but not quite the action loading code.
For action names, we really just need the name, and not the other code for parsing other things about the action, so I thought it was an ok compromise.

No jobs keyword again

---

paasta_tools/automatic_rollbacks/slo.py

Having this set to 300 seconds was misguided. Several services have SLOs that are tuned to have a sensitive threshold but a long duration/low percent_of_duration. These SLOs are made flaky by messing with the max_duration, resulting in automatically-rolled-back pushes that were actually fine.

Expand max_duration on SLOWatcher to 3600 seconds.

---

paasta_tools/cli/cmds/mark_for_deployment.py

Easy way out, for now. I'll come back with another PR to un-suppress Slack notifications if the deployment is unfinished.

Suppress mark_for_deployment Slack notifications when SHA is unchanged

---

paasta_tools/api/auth_decorator.py
paasta_tools/api/client.py
paasta_tools/secret_providers/__init__.py
paasta_tools/secret_providers/vault.py
paasta_tools/utils.py
tests/api/test_auth_decorator.py
tests/api/test_client.py
tests/secret_providers/test_vault.py
yelp_package/extra_requirements_yelp.txt

Issues a certificate via vault if https is enabled for the API endpoint.
If the certificate is expired then we renew it and retry the request.

Add certificate issue/renewal logic

---

paasta_tools/autoscaling/autoscaling_service_lib.py

We are seeing some outlier utilization that doesn't agree with meteorite utilization. It makes sense that this code is why, so let's log these as errors so they will flow through the rest of the log pipeline and we can count them and understand when and why it happens.

Increase log level of autoscaler http utilization timeouts

---

paasta_tools/automatic_rollbacks/slo.py

Whoops. I meant to hide the emojis when in a terminal state, but otherwise show them.

Fix inverted logic for showing SLO emojis

---

paasta_tools/check_spark_jobs.py
tests/test_check_spark_jobs.py

Guess from the framework user and name. It won't work for Spark apps defined in code, which are often run by root and have a custom framework name, but those should be covered by the service notification.
Also return with the appropriate return code so we can control the frequency that our team gets the full check output.

Email Spark framework users if possible

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

It is pretty "normal" for a user to add a new service with tronfig that isn't deployed yet.
I think we should warn, but not block a tronfig update for this. A developer will get notified because their job is failing, which should encourage them to deploy it.
This is different than doing validation on a typo'd deploy_group, this should be tackled in a different way.

Fail gracefully when a tron service hasn't been deployed yet

---

paasta_tools/automatic_rollbacks/slack.py
paasta_tools/automatic_rollbacks/slo.py

Show a list of all failing and missing SLOs. Use colors on failing/recovery messages to make them easier to parse.

Make SLO failures easier to grok

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/utils.py
tests/test_utils.py

We don't use this.
We've lived with --init for a while, I don't think we'll ever use it.

Removed the option to disabled docker init

---

paasta_itests/bounces.feature
paasta_tools/drain_lib.py

An attempt to improve itests in response to DAR-634. We have tests to make sure the bounce makes progress when some draining methods are failing, might as well check all of them.
This would have caught the error in DAR-634 (fails at L135, "the old app should be running") if we took out the "Intentionally crashing for testing purposes" so that the Exception has no args and would have triggered the e.args[0] IndexError. But now we have a unit test for both the 0 arg and 1 arg cases, so keeping it seems reasonable?

Error on all methods in draining itest

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

The error message is as follows:
> HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 12 Jul 2019 20:22:37 GMT', 'Content-Length': '1214'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment.apps \"yelp-main-main--uswest1\" is invalid: [spec.template.spec.volumes[1].name: Invalid value: \"host--slash-etcslash-yelp--clog.json\": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'), spec.template.spec.containers[0].volumeMounts[1].name: Not found: \"host--slash-etcslash-yelp--clog.json\"]","reason":"Invalid","details":{"name": …

fix volume naming in kubernetes tools to support files

---

general_itests/fake_soa_configs_validate/fake_valid_service/chronos-test-cluster.yaml
general_itests/fake_soa_configs_validate/fake_valid_service/deploy.yaml
general_itests/validate.feature
paasta_tools/chronos_tools.py
paasta_tools/cli/cmds/validate.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/cli/test_cmds_validate.py

This is the new #1 mistake we make at yelp, now `paasta validate` will actually run the `validate` functions and validate things.

Actually validate the instance configs when we run paasta validate

---

paasta_tools/cli/cmds/check.py
paasta_tools/cli/utils.py
tests/cli/test_cmds_check.py

We no longer have performance-check in our deploy.yaml template, so we
can go ahead and stop making people that run "paasta check" on a new
service think that they've done something wrong.

Remove performance-check from paasta check

---

paasta_tools/cli/cmds/logs.py

Scribe could send several instances of the same message, in which case
`paasta logs` output duplicating log lines.
This change prevents that by merging duplicating Scribe messages into a
single message.

Prevent duplicates in `paasta logs` output

---

paasta_tools/cli/cmds/secret.py

We've seen people get confused by the instructions and either 1) get an extra newline in their secret, or 2) attempt to terminate stdin using just ctrl+d's (no newline), which in Python due to a weird bug causes your last character to get cut off.
This clarifies the instructions to say you should type in your secret then type exactly one newline and one ctrl+d. Then for good measure it echos back the secret so you can confirm that it didn't cut anything off or insert any stray newlines. There's no risk of leaking secrets this way because typing in the secret makes it show up on stdout anyway.

[paasta secret add]  clarify how to terminate stdin and echo secret to stdout for confirmation

---

paasta_tools/automatic_rollbacks/slack.py
paasta_tools/cli/cmds/mark_for_deployment.py

Also, print all slack thread messages to stdout. Clean up erroneously-committed print statement.

Ping people after various deployment steps when notify_after_ config options are set.

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Add capabilities for containers. For example, yelp-main main_uswest1 instances needs these capabilities: "DAC_OVERRIDE", "CHOWN", "SETGID", "SETUID"]

cap_add support in k8s

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

We need to send the "real" name to vault_tools when decrypting. So in
other words my fix in https://github.com/Yelp/paasta/pull/2321 was not
quite right.

Fix secret name sanitisation

---

paasta_tools/cassandracluster_tools.py
paasta_tools/flink_tools.py
paasta_tools/utils.py

Just temporary whilst we fix a bug and move to using the same units as
everything else.

Drop mem validation for cassandra

---

paasta_tools/kubernetes_tools.py

get_security_context would return None if nothing is specified for cap_add.

fix type for security context in k8s

---

paasta_tools/cli/cmds/local_run.py

It was missing a space in the string concatenation.

Fix a typo in the help message

---

paasta_tools/kubernetes_tools.py
paasta_tools/marathon_tools.py
tests/test_kubernetes_tools.py
tests/test_marathon_tools.py

This is so that we send the IP of Kubernetes Pods to Nerve in this
header. That way a system level hacheck knows what IP to check against.
Note that I am also making us send the header in the case of marathon
tasks. This is so we can use the same hacheck for both marathon and
kubernetes tasks.

Pass X-Nerve-Check-IP to configure_nerve

---

paasta_tools/api/api.py
paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/cli/cmds/start_stop_restart.py

No error:
```
$ PAASTA_SYSTEM_CONFIG_DIR=~/etc-paasta paasta stop -s beam_happyhour -c norcal-devc
You are about to stop the following instances:
Either --instances or --clusters not specified. Asking for confirmation.
cluster = norcal-devc, instance = main
Are you sure you want to stop these 1 instances?
(y/N)? y
```
with error
```
$ PAASTA_SYSTEM_CONFIG_DIR=~/etc-paasta paasta stop -s beam_happyhour -c norcal-devc
You are about to stop the following instances:
Either --instances or --clusters not specified. Asking for confirmation.
cluster = norcal-devc, instance = main
Are you sure you want to stop these 1 instances?
(y/N)? y
ERROR: Error while setting state stop of beam_happyhour.main: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', …
```

Use PaaSTA API server for `paasta start/stop` Flink commands

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

For the `yelp_spam` service, we do not configure the AWS credential arguments of `paasta spark-run`. Our AWS credentials are not present on the batch machine, so it wouldn't be possible for Paasta to load them until the service is started. Instead, our service configures AWS credentials (and the resulting Spark configuration changes) itself.
When we use `paasta spark-run` (invoked by tron), Paasta fails to find AWS credentials and crashes, with the traceback below:
```
File "/usr/bin/paasta", line 10, in <module>
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cli.py", line 124, in main
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/spark_run.py", …
```

Do not require AWS credentials for paasta spark-run

---

yelp_package/extra_requirements_yelp.txt

Install `monk` 0.7.0 to fix broken `yelp-clog` 3.3.1 dependencies.
For testing, built `deb` package, installed it locally, and checked that the issue was fixed.
Also run `make test` and `make itest`.

Fix broken yelp-clog dependencies

---

paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_job.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_setup_kubernetes_job.py

I tested on kubestage. I installed this package, disabled it for all other than the three apps I used for the test, and ran `bash -c "paasta_list_kubernetes_service_instances | shuf |xargs setup_kubernetes_job -v"`
Change: https://reviewboard.yelpcorp.com/r/428545/
Result: https://fluffy.yelpcorp.com/i/TrKP15nGsZmRLP1WlTnR0TBHHwg9w74D.html

refactor setup_kubernetes_job to use controller_wrappers

---

paasta_tools/cli/cmds/status.py
paasta_tools/cli/utils.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_status.py
tests/cli/test_cmds_wait_for_deployment.py
tests/cli/test_utils.py

Filter out clusters and instances more aggressively when fetching service status. This brings y-m status walltime from ~20s down to ~5s.
Also refactored `get_instance_configs_for_service` a bit.

Speedup paasta status for services with many instances

---

requirements-dev-minimal.txt
requirements-dev.txt

Newer versions of pre-commit are able to run hooks in parallel, leading to faster hook runs, both at commit time and test time.
Before this, `pre-commit run --all-files` takes 100.79 seconds on my devbox; afterwards, it takes 27.53 seconds.

Upgrade pre-commit

---

paasta_tools/deployd/master.py
paasta_tools/deployd/metrics.py
paasta_tools/deployd/workers.py
tests/deployd/test_deployd_master.py
tests/deployd/test_metrics.py

[Here](https://app.signalfx.com/#/dashboard/EB0FKzIAgAA?groupId=EB0FKkdAcAA&configId=EB0FL7GAgAA&startTimeUTC=1565659876000&endTimeUTC=1565662563000) is an example of where I'm going with this -- you can see the yelp-main cert bump from 18:41 to 18:48, then at 18:59 I restarted deployd, so from 18:59 to 19:11 you can see the startup behavior.
During the yelp-main bump, because so many instances are added to the queue at once, you can see `instances_with_past_deadline` jump, as well as `max_time_past_deadline` and `average time past deadline` (which is `max_time_past_deadline` / `instances_with_past_deadline`) on the second chart. You can also see how we stop processing the backlog when all these to-be-bounced-immediately instances show up.
The backlog = `instances_to_bounce_now` - …

Add new metrics about deployd queues.

---

requirements.txt

python-iptables==0.11.0 doesn't work on bionic as the libraries have:
1. changed location
2. changed version
see: https://github.com/ldx/python-iptables/issues/203

Upgrade python-iptables to work on bionic

---

requirements.txt

I should have done this intially, but I was hoping that the error I was
seeing on bionic was just due to the hacky way I was installing
paasta-tools for testing. With this change, paasta local-run works on
bionic with no `XTablesError` errors (or needing to set any env
variables).

Bump python-iptables to latest (0.14.0)

---

requirements.txt

This reverts commit 0800b0800f2848b3820d3262014ab97758df7f31, reversing
changes made to 0ee9bd3ff170b9723f57075d478289048e4991d6.
This is being reverted since it breaks `paasta_docker_wrapper` with:
```
File "/opt/venvs/paasta-tools/bin/paasta_docker_wrapper", line 6, in <module>
from paasta_tools.docker_wrapper import main
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/docker_wrapper.py", line 23, in <module>
from paasta_tools.firewall import DEFAULT_SYNAPSE_SERVICE_DIR
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/firewall.py", line 12, in <module>
from paasta_tools import iptables
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/iptables.py", line 11, in <module>
import iptc
File …
```

Revert "Merge pull request #2369 from Yelp/bump-iptables-latest"

---

.pre-commit-config.yaml

`black` already does everything which `autopep8` can.
Also with `black` we don't need to use `flake8` for formatting, but we
still can use it to find errors, so let's run it after `black`.

Removed autopep8 and use flake8 after black

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Added a check if a pod is a paasta service by checking if it has labels to eliminate an NoneType is not subscriptable exception.

PAASTA-15618 Added a check if a pod is a paasta service

---

paasta_tools/autoscaling/autoscaling_service_lib.py
tests/autoscaling/test_autoscaling_service_lib.py

The affects the moving_average forcast policy.  If the usage was low for
several minutes, this could affect the average enough to prompt scaling
down in more than one service autoscaler run.
This prevents that case by refusing to scale down if the current usage
is greater than the setpoint (or the high point of the good_enough_window).
Internal ticket PAASTA-15711
I could also add some logging of what this would do in different situations; eg, what it would have done before this change, or what it would do with an exponentially weighted average.

RFC: Prevent scaling down services if the utilization > setpoint

---

paasta_tools/autoscaling/autoscaling_service_lib.py
tests/autoscaling/test_autoscaling_service_lib.py

The autoscaler can complain about task_data_insufficient in situations where we have _too many_ tasks.
I'm not exactly sure how apps are getting into this situation, but I think it can happen if the autoscaler runs but SMJ doesn't actually adjust a marathon app downwards. It may also happen during bounces?
In any case, I think it's unnecessary to protect against this. It's also causing false alarms on our `Paasta autoscaler daytime not scaling` alert.

Don't consider task data insufficient if there are too many tasks.

---

Jenkinsfile

Without this, debItestUpload clones master when it begins, which may have changed since the build started.

Pass commit to debItestUpload so we upload the same version we test

---

paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes_tools.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_kubernetes_tools.py

Summary
* HPA is only created for deployments.
* Whenever setup_kubernetes_job runs, HPA is synced to the lastest autoscaling setting. It is created, updated, or deleted based on yelpsoa_config setting.
* existing number of replicas in deployment objects do not change when the service is updated if autoscaling is enabled. 
* I assume when instance keyword exists in yelpsoa_config, autoscaling is disabled.
Tested on kubestage.
https://fluffy.yelpcorp.com/i/rcMS6M9r6jVP8ncJ557z6lQb5RRFsDzq.html

Add HPA for paasta services(k8s deployments)

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/flink_tools.py

This will expose metadata in API endpoint, hence allowing us to extend `paasta status` to show more useful information for Flink instances.
A separate pull request to use this metadata in `paasta status` yet to come.

Add Flink metadata to paasta_tools API

---

Jenkinsfile

Reverts Yelp/paasta#2377 as `debItestUpload` fails after the change.

Revert "Pass commit to debItestUpload so we upload the same version we test"

---

yelp_package/dockerfiles/bionic/Dockerfile
yelp_package/dockerfiles/gitremote/Dockerfile
yelp_package/dockerfiles/itest/api/Dockerfile
yelp_package/dockerfiles/itest/chronos/Dockerfile
yelp_package/dockerfiles/itest/hacheck/Dockerfile
yelp_package/dockerfiles/itest/httpdrain/Dockerfile
yelp_package/dockerfiles/itest/marathon/Dockerfile
yelp_package/dockerfiles/itest/mesos/Dockerfile
yelp_package/dockerfiles/itest/zookeeper/Dockerfile
yelp_package/dockerfiles/trusty/Dockerfile
yelp_package/dockerfiles/xenial/Dockerfile

Different approach to improving build speed and avoiding timeouts.
Travis uses [us-east-1](https://github.com/travis-ci/terraform-config/blob/master/gce-production-2/main.tf) in gce, so just use their local mirror.

Use gce ubuntu mirrors for better apt-get performance

---

paasta_tools/cli/cmds/status.py

Show config SHA from metadata, for Flink clusters only
It is conceivable that in the future we could extend this to show more data, or handle metadata for other types of clusters (if API is extended as well). At this moment we only have demand for config SHA in Flink,  though.

Show config SHA from Flink metadata

---

paasta_tools/api/views/instance.py

Removes obsolete condition which was preventing deployment `git sha` from being displayed by `paasta status` command. That condition was needed before we started properly building deplyments.json for flink containers and it no longer applies.

Show git sha for flink

---

paasta_tools/bounce_lib.py
tests/test_bounce_lib.py

We *think* this should be relatively non-disruptive and will cause us to not treat really-long-running services which Marathon has lost healthcheck state for as "unhappy".

treat tasks that are old with missing healthchecks as happy

---

Jenkinsfile

This is take 2; take 1 was 7ff3d0432, which was reverted in 9b9233713
because debItestUpload didn't support keyword arguments. Releng has
since fixed this.

Pass commit to debItestUpload so we upload the same version that we've tested.

---

requirements-minimal.txt
requirements.txt
tests/test_paasta_metastatus.py

Not sure how to fully test this.
metastatus tests were trying to connect kubestage, so I mocked them out.
Upgrading for good measure, but also to remove a YAML loading warning.

Bumped to the latest version of the k8s client

---

paasta_tools/mesos_maintenance.py

We are hammering the Mesos API and sometimes it times out, preventing things like maintenance clean ups from happening. To alleviate this problem, I have bumped the default read timeout for the Mesos API from 1s to 2s.
`make test`

Change mesos api read timeout from 1s to 2s

---

paasta_itests/paasta_deployd.feature
paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/long_running_service_tools.py
tests/autoscaling/test_autoscaling_service_lib.py

The last time I pushed this we tried to clamp in s-m-j, but @EvanKrall pointed out that we already clamp when we read values from ZK, so there's no need to try to do this logic again in s-m-j.  So this time we're _only_ removing the code that clamps when writing to ZK, which should solve the problems where we sometimes bottom out to min_instances even if there's load on the cluster.

apply min/max instance clamps only when reading from zookeeper, not when writing

---

paasta_tools/async_utils.py
paasta_tools/mesos/master.py
tests/test_async_utils.py

Currently if the future raises an exception, we store that in the cache, and we never end up executing the logic that changes its `last_update` timestamp back to something other than `float("Inf")`.  This makes sure that we remove the cache entry on exception.
This also handles a subtle race condition where two coroutines get the same in-flight future out of the cache, and one of them returns long before the other.  The first to return will either set the `last_update` timestamp on the entry so that it eventually expires, or, if the future raised an exception, it will delete the cache entry.  It's possible that, before the second coroutine gets to run again, a third coroutine will run the cached method and insert a new in-flight coroutine into the cache.  If the second coroutine gets …

Stop async_ttl_cache from caching failures

---

paasta_tools/cli/cmds/status.py

A cluster in startup phase may report incomplete job data. Trying to show these only creates problems, so let's just skip over.

ignore incomplete jobs

---

paasta_tools/autoscaling/autoscaling_service_lib.py
tests/autoscaling/test_autoscaling_service_lib.py

Based on https://github.com/Yelp/paasta/pull/2398 which I plan to merge shortly, so ignore the changes to marathon_tools.py
I think the docstring I added to filter_autoscaling_tasks justifies this change pretty well.

Make service autoscaler consider tasks healthy if they are in smartstack, even if Marathon thinks they are unhealthy.

---

paasta_tools/cli/cmds/local_run.py

I don't feel comfortable pushing out a change that could break lots of things like this, even if it is "cleaner".

Always used local env variables in paasta local-run

---

paasta_tools/cli/cmds/status.py
paasta_tools/flink_tools.py
paasta_tools/setup_kubernetes_cr.py
tests/test_setup_kubernetes_cr.py

This change implies that we will perhaps want to apply similar design to other K8s resources, because of the addition of a k8s metadata label.
The idea is to store a `yelp.com/dashboard_url` in `metadata:labels` ; this is created inside `setup_kubernetes_cr.py` ; the actual URL string-building function is `get_dashboard_url` and is likely to change. At this moment the assumption is that we want to maintain sanitized name at its current location and also that we will not bother defining Flink dashboard url in configuration for **every** cluster, so this function is capable of building a "default" one, same as the old function 'flink_tools.get_dashboard_url' did.
Yet to update integration tests for this one.

Store flink dashboard url in metadata:annotations

---

paasta_tools/autoscaling/autoscaling_service_lib.py
tests/autoscaling/test_autoscaling_service_lib.py

#2414 introduced a bug:
https://github.com/Yelp/paasta/pull/2414/files#diff-699ef1f9441fd1dab1f660ff54347041R922
The previous iteration of this code checked `task.id.startswith(someprefix)` for every task in every app, but task ids always start with the app id so #2414 only looked at the app id.
However, I forgot that Marathon prefixes app ids with `/`, leading this code to always find zero tasks.
This change reintroduces the changes from #2414 (which were reverted in https://github.com/Yelp/paasta/commit/e49a45f33dc7e457ef1411a881ba9e29a9750500) and strips leading slashes from the app id before checking for the prefix.

Fix more liberal healthchecks

---

paasta_tools/cli/cmds/start_stop_restart.py
tests/cli/test_cmds_start_stop_restart.py

This is "None" sometimes, but I don't think we need to print remote_refs anyway

Make sure we only print strings when running start/stop/restart.

---

paasta_tools/cli/cmds/status.py

The output of `paasta status` (without `-v`) can be confusing if exceptions are shown. They should be only shown when verbose mode is enabled.

Only show exceptions in status when verbose

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

The error happens when the secret contains '_', such as https://sourcegraph.yelpcorp.com/sysgit/yelpsoa-configs@0a71a848abe35298acd96630a727abd586ee80b1/-/blob/waitlist_pages/marathon-pnw-prod.yaml#L10:5
The error messages for reference:
File "/usr/bin/setup_kubernetes_job", line 191, in <module>
main()
File "/usr/bin/setup_kubernetes_job", line 90, in main
soa_dir=soa_dir,
File "/usr/bin/setup_kubernetes_job", line 138, in setup_kube_deployments
app.create(kube_client)
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/kubernetes/application/controller_wrappers.py", line 193, in create
create_deployment(kube_client=kube_client, formatted_deployment=self.item)
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/kuber …

fix error when secret contains underscore

---

paasta_tools/deployd/leader.py
tests/deployd/test_leader.py

It turns out that we have an extra `client.stop()` call to the ZK client
which can happen too early in a ZK connection flap. We already cleanup
later here:
https://github.com/Yelp/paasta/blob/1048a41a45cae134750281843b61480f84cf9015/paasta_tools/utils.py#L3176
so it should be safe to drop this.
The sequence of the bug is like so:
* Connection to ZK drops and we start retry loop to reconnect
* After 10s the ZK session times out and a new leader picks up somewhere
* This triggers a LOST transition which triggers `_terminate` and calls
`stop()` on the client
* Meanwhile the main thread exits and so the `__exit__` is called on the
lock we hold in ZK
https://github.com/python-zk/kazoo/blob/ab0cd00c12624b07dcc3b2d62aa96f8f1e658f65/kazoo/recipe/election.py#L53
* This blocks forever because we've …

Fix duplicate leader bug

---

paasta_tools/cli/utils.py
tests/cli/test_utils.py

this came up in deploy-prod:
```
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cli.py", line 124, in main
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/cmds/boost.py", line 121, in paasta_boost
verbose=args.verbose,
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/utils.py", line 685, in execute_paasta_cluster_boost_on_remote_master
master=master,
local variable 'master' referenced before assignment
```

Fix error handling when master is not available

---

paasta_tools/check_flink_services_health.py
paasta_tools/cli/cmds/status.py
paasta_tools/flink_tools.py
paasta_tools/setup_kubernetes_cr.py
tests/test_check_flink_services_health.py
tests/test_flink_tools.py
tests/test_setup_kubernetes_cr.py

This will add HTTP call to Flink dashboard inside the monitoring job, and in turn compare the number of taskmanagers (as reported by Flink) against the expected number. Since this call makes use of a significant part of the stack, it is a good end-to-end test.
Extended the unit test for the "happy path", yet need to extend unit tests to cover error cases (e.g. dashboard not reachable etc.)
Note, as a result of refactoring there is also an internal change in how dashboard URL is reported by `paasta status` because now annotation will contain the full URL rather than only "root" part.

Verify number of taskmanagers reported by Flink dashboard when monitoring

---

paasta_tools/cli/cli.py

I can't work out why these started showing up in the first place, but this at least should make them stop (at least for the CLI, I didn't really want to silence them everywhere?)

silence deprecation warnings

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

WIth this change together with replacing '_' with '-' in yelpsoa_configs, we can avoid majority  of errors like https://fluffy.yelpcorp.com/i/tvb8Mwj1txVq4QDGSxm8LkFDRx5VWKTH.html 
I'm not sure where else container name is used. Definitely let me know if you know. Just ignore this PR if you don't know.

use instance name as container name to avoid 63 character restriction

---

paasta_tools/kubernetes_tools.py

I found this bug when I was migrating. Should have tested all configs manually beforehand.

fix another hpa bug (target_average_utilization has to be int)

---

paasta_tools/flink_tools.py

As per https://requests.kennethreitz.org/en/master/_modules/requests/exceptions/ , some of the `requests` exceptions inherit from `ConnectionError` and these need to be handled, too. Also we want to show `e.response` when available

Improve error reporting

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/cmds/check.py
paasta_tools/cli/cmds/validate.py
tests/cli/test_cmds_validate.py

Check if service name is longer than 63 for all serivces.
Check if instance name is longer than 63 for k8s instances.

validate instance/service names no more than 63 characters

---

docs/source/bouncing.rst
docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/kubernetes_schema.json

This should be enough to deprecate upthendown. We just need to change upthendown to crossover when migrating to k8s then.

deprecate upthedown bounce methoed for k8s

---

requirements-minimal.txt
requirements.txt

even though it is only used for type checking, we still need included so
the import works

add missing boto3-type-annotations req

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

This can fail if the labels aren't there. If they aren't labelled they
shouldn't be in the filter so just skipping them.

Fix k8s pod filter

---

paasta_tools/flink_tools.py

This function was left over from merge of #2426, but is not used anymore

Remove unused function

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Set `ephemeral-storage` resource and limit for pods according to the
configuration, setting the disk quota as a result.
Please note that that is a soft disk quota which doesn't prevent a pod
from using more disk space than requested.  Instead of that, Kubernetes
evicts the violating pod, which then either rescheduled to another node
or becomes `Evicted`.  Please see the corresponding KEP for more
information:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20180906-quotas-for-ephemeral-storage.md

Set disk quota for k8s

---

paasta_tools/cli/cmds/spark_run.py

@qui said:
> no, because that info isn’t readily available from the Mesos master, but the labels are
> i mean, the environment variables are used by the DockerStats collector
> both are necessary
> the paasta_instance_resource_utilization_summary report joins the tmp_paasta_allocation report (which uses labels) and the fullerite data (which uses env)
So this change makes the Docker labels match the environment variables, which should make this stuff show up in Splunk.

set the paasta_instance docker label for spark-run

---

paasta_tools/check_oom_events.py

This has been broken since Oct 24 (though the relevant block has been in yelpsoa for four months).
```
File "/usr/bin/check_oom_events", line 207, in <module>
main(sys.argv)
File "/usr/bin/check_oom_events", line 201, in main
send_sensu_event(instance_config, oom_events, args)
File "/usr/bin/check_oom_events", line 174, in send_sensu_event
"tip": "Try bumping the memory limit past %dMB" % instance.get_mem(),
TypeError: %d format: a number is required, not str
```

check_oom_events shouldn't crash on a parsing error

---

paasta_tools/flink_tools.py

I just noticed that some exceptions from `urllib3` are not automatically converted to `requests.RequestException`, so we need to handle them explicitly.

Handle urllib3 exceptions

---

paasta_tools/flink_tools.py

Reverts Yelp/paasta#2521
oops, this is not needed. The `urllib3` exceptions are leaking elsewhere.

Revert "Handle urllib3 exceptions"

---

paasta_tools/mesos_tools.py

>   File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/mesos_tools.py", line 752, in get_mesos_slaves_grouped_by_attribute
>     sorted_slaves = sorted(slaves, key=lambda slave: slave["attributes"].get(attribute))
> TypeError: '<' not supported between instances of 'str' and 'NoneType'
I don't know why attribute would be none. But setting it to '' should fix the issue.

fix paasta status error on stagef

---

paasta_tools/cli/cmds/local_run.py
tests/cli/test_cmds_local_run.py

This doesn't do anything fancy about sidecars or whatever yet, but will prevent local-run from crashing when running it for something in stagef.
This code looks a little overkill? But maybe we need room for more stuff and other frameworks?

Basic support for paasta local-run for k8s

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/cmds/rollback.py
paasta_tools/utils.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_rollback.py

We want to track rollback rates for services in EE Metrics, so we've instrumented both the `paasta rollback` command and the Slack/SLO rollback events to log to the same audit stream that we use for m-f-d.
I wanted to log this as part of the existing _log_audit calls in m-f-d, but it doesn't seem like there's any way of knowing at that point if we're rolling back and why.
**testing done**: 
- `make test itest`
- manual (i.e., clicking buttons and checking the audit stream)
**questions**:
- writing tests for the state machine stuff doesn't look particularly simple from what I saw - any ideas here?
- I added an enum for type safety, but not sure if it'd be preferable to just use simple named constants and type things as `str` - in the same vein, would we prefer TypedDicts for all new dicts …

RELENG-41130: Track PaaSTA rollback events

---

paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

I changed the behavior of get_enable_nerve_readiness_check so that the condition when it's triggered is the same as check_haproxy. enable_nerve_readiness_check param is never used in yelpsoa_configs so it's fine. I think we probably want to paasta configs later. It does not make sense to put check_haproxy under bounce_health_params anymore, as it is irrelevant to bouncing essentially.

supports min_task_uptime and check_haproxy in k8s

---

paasta_tools/cleanup_kubernetes_cr.py
paasta_tools/cleanup_kubernetes_crd.py
paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes/application/tools.py
paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_cr.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_cr.py

this is a subset of my reverted pull request. Don't remove old labels, just don't read them anywhere.

Replace reads of old kubernetes labels

---

paasta_tools/cli/cmds/status.py

Currently, it is assumed that job name length will be 32 characters. While checking paasta status we see that name of jobs is getting trimmed. If we avoid cutting the names, it will  be useful while using the flink-supervisor cli. Refer to FLINK-1830 for further details.

Avoid cutting name of flink jobs running in cluster

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

With k8s, in some sense we are moving forward with the pause container, to keep all the random namespaces together. 
But in a different sense, we are moving backwards, because the pid namespaces are not shared (they used to be by default, but then that was reverted). 
Because of this, now "every" container needs to solve the dumb-init problem again, which I don't want.
Instead, I would like to turn this option on for all paasta pods, so that we don't need to add dumb-init to every container we run.
Ref: "Some Context on PID Namespace Sharing"

Always share the process namespace in k8s pods

---

paasta_tools/api/views/instance.py
paasta_tools/cli/cmds/status.py
tests/api/test_instance.py
tests/cli/test_cmds_status.py

`paasta status` should report Evicted pods when querying a K8s cluster.
This change adds the evicted node count on the kubernetes status line:
> Kubernetes:   Healthy - up with (1/1) instances (1 evicted). Status: Running
And also sets the pod status as **Evicted** when listing pods, including the eviction reason:
>        [podname]  [nodename]  2019-11-10T18:58 (8 hours ago)  Healthy
>        [podname]  [nodename]  2019-11-10T18:55 (8 hours ago)  Evicted
>           Pod ephemeral local storage usage exceeds the total limit of containers 512Mi.

PAASTA-15937 Display evicted nodes on paasta status

---

paasta_tools/drain_lib.py
paasta_tools/setup_marathon_job.py
tests/test_drain_lib.py
tests/test_setup_marathon_job.py

I have two goals:
* want to make it easy to see what url we were trying to hit and make it really obvious what the code was
* I want paasta logs lines to always just be one line, I don't think we need the whole traceback in there (if you think we need the traceback, I think I would prefer to just `log` it.

Make it easier to understand http draining exceptions

---

paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/setup_kubernetes_job.py
tests/test_setup_kubernetes_job.py

by adding -c flag for cluster instead of reading it from system configs in various places

Make setup_kubernetes_job more testable

---

paasta_tools/utils.py

Importing yelp_clog somehow turns on DeprecationWarning on bionic (python 3.6.8).
The `warnings.filterwarnings` in `paasta_tools/cli/cli.py` doesn't catch all of them because the ones from kubernetes happen at import time.
```python
(paasta-tools)
drolando@dev128-uswest1adevc pg
~>  python
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client as kube_client
>>> from kubernetes import config as kube_config
>>>
```
```python
(paasta-tools)
drolando@dev128-uswest1adevc pg
~>  python
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clog
>>> from kubernetes import client as …
```

Silence DeprecationWarnings on python 3.6.8 (bionic)

---

Makefile
tox.ini

Adds a make target that lets you easily install the pre-commit hooks for this repo without having to run the entire test suite.
There doesn't seem to be a generic virtualenv (.paasta only contains tox, no other dependencies afaict), so I had to create a new one (.tox/install-hooks). But since the only dependency is pre-commit I don't think it's a big deal

Add install-hooks make and tox targets

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

The length of the docker volume can't be more than 63 characters. Also, persistent name can't be more than 253 characters.

limit the length of the volume name

---

paasta_tools/cli/cmds/spark_run.py

This is to allow users pass in whatever spark.driver.extraJavaOptions. Dderby.system.home is part of the default in the Spark-on-PaaSTA debian.

Remove spark.driver.extraJavaOptions from spark-run non-configurable options

---

.travis.yml

We now have bionic devboxes and other hosts. We should make sure the
itest_bionic tests pass then.

Make bionic tests required

---

paasta_tools/api/views/instance.py

previously, we occasionally emitted `None`, which would cause a 500 as this is not allowed by the schema. 0 is the correct value to emit in this case anyway.

ready_replicas should always be an int

---

paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes_tools.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_kubernetes_tools.py

* Added a metrics selector that allows sfx adapter to filter out cluster specific metrics
* Fix api version.
Tested on kubestage.

Fix hpa to work with sfx metrics adapter

---

paasta_tools/check_marathon_services_replication.py
paasta_tools/cli/cmds/status.py
paasta_tools/marathon_tools.py
requirements-minimal.txt
requirements.txt
tests/test_check_marathon_services_replication.py
tests/test_marathon_tools.py

Basically, the paasta API was outputting timestamps for Marathon tasks/apps that were off by 7 or 8 hours; we had code in the CLI to correct this. The Paasta API was producing correct timestamps for k8s, but we copy-pasted the same correction code from the Marathon status CLI, which resulted in incorrect timestamps.
The first commit fixes the k8s bug; the second commit fixes the paasta API for marathon tasks and removes the correction; it does so by bumping marathon-python to a version that [produces TZ-aware datetime objects](https://github.com/thefactory/marathon-python/pull/267)

Fix times in paasta status for k8s; fix timestamps in CLI for marathon

---

paasta_tools/cassandracluster_tools.py

Currently failing because the API expects a paasta bounce method not a
kubernetes one. Hardcoding it to crossover since it doesn't matter that
much for cassandra and will just appear in the status API.

Fix paasta status for cassandra

---

yelp_package/dockerfiles/xenial/Dockerfile
yelp_package/dockerfiles/xenial/requirements.txt

Think a new release of virtualenv is causing some failure in pip install
for example cluster. Trying this pin which I think will fix it..

Fix example cluster build

---

paasta_tools/cli/cmds/validate.py

Otherwise, it throws exception:
File "/nail/home/chl/paasta/.tox/py36/bin/paasta", line 11, in <module>
load_entry_point('paasta-tools', 'console_scripts', 'paasta')()
File "/nail/home/chl/paasta/paasta_tools/cli/cli.py", line 166, in main
File "/nail/home/chl/paasta/paasta_tools/cli/cmds/validate.py", line 430, in paasta_validate
if not paasta_validate_soa_configs(service, service_path):
File "/nail/home/chl/paasta/paasta_tools/cli/cmds/validate.py", line 401, in paasta_validate_soa_configs
if not validate_service_name(service):
File "/nail/home/chl/paasta/paasta_tools/cli/cmds/validate.py", line 133, in validate_service_name
if len(sanitise_kubernetes_name(service)) > 63:
File …

paasta validate has to take service argument

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

If the first word of the command wasn't actual spark command, we'd end up with things like `adhoc_username_USER` which is useless.

better parsing of spark command when env variables are set

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/remote_git.py
tests/cli/test_cmds_mark_for_deployment.py

Not all git hosts are gitolite, and relying on the authors-of-changeset
gitolite script is not an option for repositories hosted there.
Since most calls to this command are automated, Release
Engineering will be modifying those calls to pass in the git authors
directly. This change enables that.
For those manual calls by developers, we intend to pull out the username
of the developer from OS calls, which will be done in a future CR.
This argument is an append action, so authors will be passed in via --author user1 --author user2 and so on.
I started writing a unit test for this change, but none of the tests in https://github.com/Yelp/paasta/blob/master/tests/cli/test_cmds_mark_for_deployment.py seem to be at that low of a level. Would appreciate opinions on if it's necessary or not.

Add additional authors as a CLI argument

---

docs/source/yelpsoa_configs.rst

Now that endpoint timeout overrides are in GA, we should add their usage to the docs.

Endpoint timeout override doc update

---

paasta_tools/cli/cmds/mark_for_deployment.py

`git_authors` is the return error text from the get_authors method, not `authors`.  This corrects to the right variable name so that errors will show up in slack pings.

Print right error output when no authors found for mark-for-deployment

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

This PR enables users to have the jupyterhub experience on their local boxes for whatever reason. It opens additional opportunities since /nail/home is mounted (required for aws creds). Users are expected to use images with the yelp_jupyterhub package, for example, the docker-dev.yelpcorp.com/core-ml-centralized-jupyterhub-gpu image.

replace jupyter with jupyter-lab in spark-run

---

general_itests/fake_soa_configs_validate/fake_invalid_service/kubernetes-test-cluster.yaml
general_itests/fake_soa_configs_validate/fake_invalid_service/kubernetes-test-cluster2.yaml
general_itests/fake_soa_configs_validate/fake_invalid_service/kubernetes-test-cluster3.yaml
general_itests/fake_soa_configs_validate/fake_invalid_service/marathon-test-cluster.yaml
general_itests/fake_soa_configs_validate/fake_valid_service/kubernetes-test-cluster.yaml
general_itests/steps/validate_steps.py
paasta_tools/cli/cmds/validate.py
paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Design a new autoscaling configuration before implementing it. Only validation part is added and fully tested now.
**Purpose**
* Add support for external metrics based on any signalfx metrics, multiple metrics, and memory. 
* Simplify existing autoscaling configuration by removing unused parameters. 
* Make the new configuration as simple as possible and as powerful as possible, while restrict potential intended user mistakes. 
**Complex User cases**
*  Scale instance A based on instance B
*  Use the same signalfx metrics for multiple instances across different clusters. 
*  Set canary to a certain percent of non-canary by using the number of instances of non-canary as metrics. 
I believe all of above use cases could be supported by allowing users to customize the dimension of their …

validate new autoscaling configurations

---

paasta_tools/check_flink_services_health.py
paasta_tools/check_kubernetes_services_replication.py
paasta_tools/check_marathon_services_replication.py
paasta_tools/check_services_replication_tools.py
paasta_tools/monitoring_tools.py
tests/test_check_flink_services_health.py
tests/test_check_kubernetes_services_replication.py
tests/test_check_marathon_services_replication.py
tests/test_check_service_replication_tools.py
tests/test_monitoring_tools.py

first commit unifies the two scripts for monitoring replication in mesos/marathon and kubernetes
second commit adds logic to emit metrics about the replication of each service and also track replication in aggregate in a cluster so that we can alert when there are widespread problems with the service mesh (instead of waiting for folks to complain to us)
I have already run all of these scripts on the norcal-devc masters and they work and emit metrics.

Check services replication metrics

---

paasta_tools/kubernetes/bin/kubernetes_remove_evicted_pods.py
setup.py

Adds kubernetes_remove_evicted_pods script which removes Evicted pods and notifies service owners.
Sample invocation:
```
$ sudo ./kubernetes_remove_evicted_pods.py -d /nail/home/gabrielv/services
INFO:__main__:Pods in evicted state: ['gabrielv-deployment-5f4585b554-clzk8', 'compute-infra-test-service-main--k8s-5c7dd5589f-bsf4s']
INFO:__main__:Could not get service name for pod gabrielv-deployment-5f4585b554-clzk8
INFO:__main__:Notifying owners for service compute-infra-test-service
INFO:__main__:Removing pod compute-infra-test-service-main--k8s-5c7dd5589f-bsf4s
```
This produces the following Sensu alert:
```
The following pods have been evicted and will be removed from the cluster:
- compute-infra-test-service-main--k8s-5c7dd5589f-bsf4s: Pod ephemeral local storage usage exceeds the …
```

PAASTA-15954 Add kubernetes_remove_evicted_pods script

---

paasta_tools/cleanup_kubernetes_cr.py
paasta_tools/cleanup_kubernetes_crd.py
paasta_tools/cli/cmds/status.py
paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes/application/tools.py
paasta_tools/kubernetes_tools.py
paasta_tools/metrics/metastatus_lib.py
paasta_tools/setup_kubernetes_cr.py
paasta_tools/setup_kubernetes_crd.py
tests/test_kubernetes_tools.py

* rename `maybe_add_yelp_prefix` with `paasta_prefixed`
* fix `paasta_prefixed` for discovery attributes, that aren't under `paasta.yelp.com` namespace
* replace hardcoded namespacing with `paasta_prefixed` everywhere

More consistent paasta prefixed attributes

---

paasta_tools/api/views/instance.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
paasta_tools/smartstack_tools.py
paasta_tools/utils.py
tests/api/test_instance.py
tests/test_utils.py

Paasta codebase is littered with long `if ... elif` chains switching on `instance_type` values. I'm trying to make instance type more of a first-class citizen by moving everything related to how certain instance types are handled into their own modules. Currently we can largely categorize paasta codebase in following big categories:
a) api handles request/response and how things are represented on the wire
b) cli handles commands, args parsing and rendering to terminal
c) various `_tools` and other modules dealing with concrete tech (mesos, kubernetes, tron)
In this PR I'm adding `paasta_tools.instance` layer that should sit in between [ab] and [c].
Eventually it's useful to have a more pluggable system where modules or other binaries can be registered in paasta configuration system to …

Instance support modules

---

paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/api/test_instance.py

- don't error out when `_sha` labels aren't present, we may be looking at operator-created pods and those don't necessarily carry over all the labels
- look into deployments, replica sets and stateful sets for `_sha` labels

Kubernetes active sha fix

---

paasta_tools/cli/cmds/mark_for_deployment.py
tests/cli/test_cmds_mark_for_deployment.py

Notify service config git master of deployments directly for yelp services
Context for change:
Currently, to mark a service for deployment, tags are pushed to the
service's git repository, and a gitolite hook reads those tags, then
notifies sysgit, which has the master copy of our service configs, to
generate a deployment for that service. That hook lives here:
https://sourcegraph.yelpcorp.com/packages/py-gitolite@e4e52bf91f3351b840e012b8373e642c2db0032f/-/blob/gitolite/hooks/repo_specific/paasta_deploymentsd.py#L21-41
And the service on sysgit that just calls `generate_deployment_for_service` lives here:
https://sourcegraph.yelpcorp.com/sysgit/puppet@02d24429c51c6f27e9aa9b1adc0401a1b0558842/-/blob/modules/paasta_tools/files/paasta-deploymentsd
Release Engineering is moving paasta …

Notify service config git master of deployments directly for yelp services

---

.activate.sh
.deactivate.sh
.dockerignore
.travis.yml
Makefile
docs/source/generated/paasta_tools.rst
paasta_tools/cli/cmds/spark_run.py
paasta_tools/mesos_tools.py
paasta_tools/paasta_remote_run.py
paasta_tools/setup_tron_namespace.py
paasta_tools/spark_tools.py
paasta_tools/tron_tools.py
requirements-minimal.txt
requirements.txt
tests/cli/test_cmds_spark_run.py
tests/test_spark_tools.py
tests/test_tron_tools.py
tests/test_utils.py
tox.ini

This uses the changes in https://github.com/Yelp/service_configuration_lib/pull/39 to set up a spark environment for Tron.  Tested manually, but there's still going to be more work to do.
I also made changes so that we actually get a "real" development virtualenv for paasta, cuz I'm sick of typing `.tox/py36-linux/bin/pytbnon` all the time.

Use the service configuration library to set up Spark on Tron

---

paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_status.py

**Description:**
The following code is used to make `paasta status` easier by combining the _service_ and _instance_ names together delimited by a period.
**Testing Done:**
* `make test`
* Added manual unit tests (3 tests parameterized):
- `pytest tests/cli/test_cmds_status.py -k "test_apply_args_filters_shorthand_notation"`
* Try with optional positional argument: `paasta status example_happyhour.canary`

Paasta status support shorthand notation

---

paasta_tools/cli/cmds/validate.py
tests/cli/test_cmds_validate.py

Tronfig has been moved to service directory, so let's remove the related validation codes.

remove paasta validate for tron directory

---

paasta_tools/dump_locally_running_services.py

I've tested this script at stagef, and it works fine. However, I've noticed the nerve_dict is different between marathon services and kubernetes services. The [marathon service's](https://sourcegraph.yelpcorp.com/mirrors/Yelp/paasta@f317d96d83a2ff8da5c1e6985fe804b0c2d8038c/-/blob/paasta_tools/marathon_tools.py#L1147) nerve dict has the keys including "port", "paasta_instance", "deploy_group" and "extra_healthcheck_headers", while [kubernetes service's](https://sourcegraph.yelpcorp.com/mirrors/Yelp/paasta@f317d96d83a2ff8da5c1e6985fe804b0c2d8038c/-/blob/paasta_tools/kubernetes_tools.py#L1282) nerve dict only has "port" and "service_ip".

let ingress envoy know kubernets services

---

paasta_tools/cli/cmds/autoscale.py

Description:
The following code is used to catch bravado exception 404s when a user specifies an unknown service name or a service that does not have autoscaling configured. Instead of returning the stack trace, we relay an error message.
Testing Done:
* `make test`
* Example of service without autoscaling configured: `paasta autoscale -c norcal-prod -s billing -i sfn_flat_rate_subscription_bookkeeping_worker --set=30`

Fix paasta autoscale error messaging

---

paasta_tools/cli/cmds/spark_run.py
paasta_tools/spark_tools.py
paasta_tools/tron_tools.py
tests/cli/test_cmds_spark_run.py
tests/test_spark_tools.py
tests/test_tron_tools.py

manual testing in a local dev environment, confirmed that metrics show up in DynamoDB after running setup_tron_namespace and watching the job run.

send clusterman metrics info as environment variables to Tron

---

debian/rules
requirements-bootstrap.txt

Set requirements to the state they were in `0.93.2` version of
`paasta-tools` and pin `pip` to `18.1`.

Update requirements-bootstrap.txt to the state in v0.93.2

---

paasta_tools/cli/cmds/status.py

Currently, if a flink cluster is in unrecoverable state, paasta status doesn't show pod status while pods might be running and some of them might be in crashloopbackoff if we check them using kubectl. The change will enable paasta status -v to show pod status if it is available irrespective of the state of the cluster.

Showing pod status irrespective of state of flink cluster

---

paasta_tools/cli/cmds/status.py

We updated the Flink resource for k8s to have information on the state of each container. This change was done as a workaround for https://github.com/kubernetes/kubernetes/issues/76619 
In case where container state is not running, it would be a better idea to show the state of the container and reason for container to be in that state. Pod phase will still be running in cases of containers in waiting state.

Adding container state and reason in case container is not running

---

paasta_tools/docker_wrapper.py
paasta_tools/docker_wrapper_imports.py
tests/test_docker_wrapper.py

Python imports are sometimes slow and we pay the price for that on every `docker inspect`, which does not need them, and which is executed by Mesos very often.
Let's move them to a separate file and import in the body of the function, so we have our cake (i.e. do not pay the price of imports when `add_firewall` is not used) and eat it too (i.e. `add_firewall` working as usual when needed). Moving all the imports to a separate file was necessary to maintain mocks inside unit tests for the `docker_wrapper`.

Delay paasta_tools imports inside docker_wrapper.add_firewall

---

paasta_tools/contrib/get_running_task_allocation.py
paasta_tools/kubernetes_tools.py
requirements-minimal.txt
requirements.txt
tests/test_kubernetes_tools.py

We also want task allocation information for Kubernetes instances to track usage and costs.
I copied the logic for parsing k8s resources from https://github.com/Yelp/clusterman/blob/d0dffafac346f1736b608a5a2d266641a1f8b71b/clusterman/kubernetes/util.py#L33 and put it in kubernetes_tools because it seems useful for other purposes.

Add Kubernetes to running task script

---

paasta_tools/contrib/mass-deploy-tag.sh
paasta_tools/generate_deployments_for_service.py
paasta_tools/utils.py
tests/cli/test_cmds_info.py
tests/test_utils.py

All `services/` repositories are on github.yelpcorp.com now, and any
stragglers outside of that namespace have their git_url manually
specified in their config. New repositories are always created on
GitHub, so changing the default host to GitHub lets new services work
without requiring extra config changes

Swap default service location from gitolite to GitHub

---

paasta_tools/tron_tools.py

We made it!
There are no jobs at yelp that do not have an explicit executor/node.
I think implicit is better than explicit (sane defaults) when it comes to lots and lots of configs that humans have to interact with all the time, so I would like to make the default executor/node be paasta.
After shipping, I would like to simplify all our tron job configs by removing the things that are already set with this default.

Make the default tron executor and node be paasta

---

paasta_tools/cli/cmds/mark_for_deployment.py
tests/cli/test_cmds_mark_for_deployment.py

The old way of finding authors was to call a gitolite command that
finds the authors between two commits. For services on GitHub, we pass
in the authors when making a mark-for-deployment call, so there is no
benefit to trying to call this gitolite command on a GitHub repository.
This change was prompted by the noisiness of timed deploys for shas
already on master not having authors passed in, and paasta's slackbot
complaining about not being able to find any authors from GitHub as a 
fallback when there are no authors for gitolite either.
I updated all `git_url=None` in tests to have a reasonable value, since get_authors_to_be_notified  requires an actual string and adding a check for the case where `git_url` is None doesn't make a lot of sense, since it will always actually exist for …

Don't try to retrieve authors from GitHub repos with gitolite commands

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/api/views/instance.py
paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/cmds/status.py
paasta_tools/envoy_tools.py
paasta_tools/smartstack_tools.py
paasta_tools/utils.py
tests/api/test_instance.py
tests/cli/test_cmds_status.py
tests/cli/test_cmds_wait_for_deployment.py
tests/envoy_admin_clusters_snapshot.txt
tests/test_envoy_tools.py

This reverts commit ced20ed9a12e3757eaf8c75d7c8b97717a12c663 which was created by #2640 which was a revert of #2595. This effectively restores #2595 . No new changes are introduced in this PR.
We've fixed the issues which were caused by missing envoy configuration.

Restore Report Envoy backend status #2595

---

docs/source/hpa.rst
general_itests/fake_soa_configs_validate/fake_valid_service/kubernetes-test-cluster.yaml
paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

I changed how target_average_value in kuberentes is set (for uwsgi and http metrics). It was originally timed 100 and is not anymore. cpu and memory metrics is timed by 100 as required.

change kubernetes service autoscaling target metrics units

---

paasta_tools/kubernetes_tools.py

The error messages said it violdates the swagger format:
https://fluffy.yelpcorp.com/i/fg0MF8L3tHTkPVKl9wGvhjfJdzQwK7wS.html
And it turns out the error message should be string rather than list:
https://sourcegraph.yelpcorp.com/mirrors/Yelp/paasta/-/blob/paasta_tools/api/api_docs/swagger.json#L885

fix error messaage violates swag format error

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/tron_schema.json
paasta_tools/tron_tools.py
tests/test_tron_tools.py

Some spark jobs require aws credentials be read from a yaml file on disk, and be provided to spark driver container as env variables ("AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY").
We need to support aws_credentials_yaml option, which is the path to aws credential yaml file on disk, and read them in code, as well as aws_region option, which is used to populate AWS_DEFAULT_REGION env variable.

Add aws_credentials_yaml and aws_region options

---

paasta_tools/envoy_tools.py

paasta status would error when retrieving envoy status if socket.gethostbyaddr failed on a k8s pod IP. The hostname is only used for display purposes, so this defaults the hostname to the raw IP if socket.gethostbyaddr fails.

Default hostname when getting envoy status to raw IP address if lookup fails

---

paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/test_tron_tools.py
tests/test_utils.py

We can simplify the tron logic because we don't have to worry about
jobs and actions being lists. They are always dicts now.
This is in preparation for changing the way we read instance configs
(PAASTA-16300). Ideally that would be a single function, e.g.
read_instance_configs, that all other tools can use.

Refactor instance listing into a single function

---

paasta_tools/cli/schemas/kubernetes_schema.json

So, in paasta_tools we just set the pod disruption budget to (1 - bounce_margin_factor).  For services that only have 1 replica, if we want them to be able to be bounced or evicted, we need to have a PDB of 1, which means we need a bounce_marge_factor of 0, but this is currently disallowed.

allow 0 bounce margin factor for k8s

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/cli/cmds/status.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/cli/test_cmds_status.py
tests/test_kubernetes_tools.py

I've made it so that when using -vv or -vvv with `paasta status` for a k8s service, k8s errors will be included, in addition to any stdout or stderr. It looks like [this] (https://gist.github.com/kawaiwanyelp/5bfd63bbfd1c7d440099af4ff838b1ac).
The errors and instance output are per container per pod. Pods themselves don't record any aggregated error states for its containers. So, even if a container is in a crash loop, the pod may still be "healthy" (we show this in `paasta status`, and I'd like to fix that in a separate PR).
`make test`
manual testing by making a local `paasta-api` process talk to a real dev k8s cluster

Add k8s deployment errors to paasta status (-vv or -vvv)

---

paasta_tools/cassandracluster_tools.py

- As the statefulset names of Cassandra clusters have been simplified

Use simplified Cassandra deployment name

---

paasta_tools/cli/schemas/tron_schema.json
paasta_tools/tron_tools.py
requirements-minimal.txt
requirements.txt
tests/test_tron_tools.py

This PR also fixes an issue of `executor: spark` on mesos, where `spark.mesos.executor.docker.volumes` need to have lower-cased file modes, like `ro` and `rw`.

Initial paasta support for tron on k8s

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/cli/cmds/status.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/cli/test_cmds_status.py
tests/test_kubernetes_tools.py

#2684 was reverted because `paasta status` resulted in an `UnboundLocalError`. This PR un-reverts it and fixes the error, as well as adding a new test case to account for non-error cases.
`make test`

Un-revert #2684 and fix the UnboundLocalError exception raised when using `paasta status`

---

paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Currently, we just show pod hostnames in `paasta status` like `ip-00-00-00-00.us-west-1.compute.internal`, but this review makes it so that real hostnames are shown instead, making them directly copyable for SSH-ing.
`make test`
Manual testing with a local paasta-api connected to a test k8s cluster

Show real hostname for k8s pods in paasta status

---

paasta_tools/adhoc_tools.py
paasta_tools/cassandracluster_tools.py
paasta_tools/flink_tools.py
paasta_tools/frameworks/native_scheduler.py
paasta_tools/frameworks/native_service_config.py
paasta_tools/kafkacluster_tools.py
paasta_tools/kubernetes_tools.py
paasta_tools/marathon_tools.py
paasta_tools/paasta_service_config_loader.py
paasta_tools/utils.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_firewall_update.py
tests/test_kubernetes_tools.py
tests/test_marathon_tools.py
tests/test_paasta_service_config_loader.py
tests/test_utils.py

The design in PAASTA-16256 specifies that configuration from automated sources can be stored in a new subdirectory in each service's yelpsoa-configs. For example,
```
foo_service/
marathon-norcal-devc.yaml
service.yaml
deploy.yaml
auto/
marathon-norcal-devc.yaml
```
The regular instance config in `marathon-norcal-devc.yaml` is deep-merged with `auto/marathon-norcal-devc.yaml`, such that keys are only used from `auto` if they are not specified in the regular file.
For example, given
```
marathon-norcal-devc.yaml
----
foo:
cpus: 1
mem: 20
bar:
cpus: 2
auto/marathon-norcal-devc.yaml
----
foo:
mem: 30
bar:
mem: 30
```
The result would be `mem: 20` for `foo` and `mem: 30` for `bar`.
I've implemented this in `utils.load_service_instance_config(s)` and replaced all the places that we load …

Load instance configs everywhere with utils function that includes automated config

---

paasta_tools/cli/cmds/logs.py
paasta_tools/utils.py

`run_code_over_scribe_envs()` invokes the `callback()` function for every logging component. But callback() ignores the `component` param and uses `components` instead.  This gets passed down to the log filtering functions, which end up matching log lines more than once.
This bug affects print_last_n_logs, print_logs_by_time and tail_logs. But the first two do not expose the problem thanks to [paasta/pull/2322](https://github.com/Yelp/paasta/pull/2322). 
Note that we still need to keep the fix on pull/2322 as scribe is still duplicating log lines when pulling data in non-streaming mode.

PAASTA-15540 Fix duplicated log lines on `paasta logs -f`

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_status.py

***Summarized Context***
These changes adds support for getting more details in the `paasta status` commands. I have also refactored the code that handles printing different output for different instance types like `flink`, `marathon` and make it generic so that adding new type is easier. To make it consistent I had to change the method signatures of all custom status printing commands and make is consistent with the following interface
```python
InstanceStatusWriter = Callable[
[
NamedArg(str, "cluster"),
NamedArg(str, "service"),
NamedArg(str, "instance"),
NamedArg(List[str], "output"),
NamedArg(Any, "status"),
NamedArg(int, "verbose"),
],
int,
]
```
***Testing Done***
```make test```
**Output**
```================================================================================== 1874 …
```

[KAFKA-25246] Adds support for kafka cluster status in `paasta status`

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

This PR adds root priviledge to both driver and executor containers as
well as specifying `spark.mesos.uri` configuration. These 2 in
combiniation should fix the issue where spark executors cannot be
created on mesos slaves due to 401 to private docker registry.

Fix docker registry permission issue

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

To support `deploy_blacklist` and `deploy_whitelist` for k8s instances, I've implemented logic to convert those configs to node affinities. I've also taken the liberty of converting the pool selector (previously implemented as a node selector) into a node affinity so that it's all unified.
`make test`
Manual testing using `setup_kubernetes_job` to create test pods with the new node affinities
While testing, I found out that `kubectl describe pod` _does not_  show affinities, only selectors. However, it will still show failures if the affinities result in no scheduleable nodes, which can be confusing. It is possible to see them using `kubectl get pod -o json`, which shows the raw pod configs, and I've documented this in the code. I haven't seen any reported issues so it doesn't seem like …

Implement deploy_whitelist and deploy_blacklist for k8s pods as node affinities

---

paasta_tools/autoscaling/load_boost.py
paasta_tools/cli/cmds/boost.py
yelp_package/dockerfiles/itest/api/Dockerfile

Some users may need to set boost above 3.0, allow that if they set --force already. For clusters scaled by clusterman, they will not exceed max_capacity in any case.

Also allow extraordinarily high boost values when --force is passed

---

paasta_tools/contrib/check_orphans.py

```
paasta-mesos-master::10-81-63-228-uswest2bdevc.dev.yelpcorp.com :
check_orphan_registrations : True
/opt/venvs/paasta-tools/bin/check_orphans.py:39: YAMLLoadWarning:
calling yaml.load() without Loader=... is deprecated, as the default
Loader is unsafe. Please read https://msg.pyyaml.org/load for full
details.   x = yaml.load(f) WARNING:check_orphans:error getting file
from 10.144.177.10 WARNING:ch
```

Fix `check_orphans.py` uses unsafe yaml loader

---

paasta_tools/tron_tools.py
requirements-minimal.txt
requirements.txt
tests/test_tron_tools.py

This includes multiple enhancements and bug fixes of
service-configuration-lib 2.4.1, including attaching volumes to spark
executor pods.

Bump service-configuration-lib version to 2.4.1

---

debian/rules
requirements-bootstrap.txt
requirements.txt
yelp_package/dockerfiles/mesos-paasta/Dockerfile
yelp_package/dockerfiles/playground/Dockerfile

setuptools v46.0.0 was released 2 days ago and removed Features, which http-parser requires. To get around this issue, I added `requirements-bootstrap.txt`, which includes the current version of setuptools PaaSTA uses, which tox installs before it installs other dependencies for tox. I also patched the debian rules to use `requirements-bootstrap.txt`. This should fix the Travis errors we've been seeing recently.
Reproduced the Travis issue locally by using the public PyPI instead of Yelp's internal PyPI (since it doesn't have the latest version of setuptools. Verified that `requirements-bootstrap.txt` resolves the bug and updates to `debian/rules` fixes the builds.

Add requirements-bootstrap to install setuptools<46.0.0

---

debian/rules
requirements-bootstrap.txt
requirements.txt
yelp_package/dockerfiles/mesos-paasta/Dockerfile
yelp_package/dockerfiles/playground/Dockerfile

I previously merged #2712 to unblock Travis, but it wound up blocking Yelp's internal PaaSTA build. I then created #2714 to fix that issue, but @vkhromov pointed out that we had previously run into performance issues (#2638). As a result, I've bumped the hard pins in `requirements-bootstrap.txt` to be in line with what PaaSTA currently uses.
ran `make itest` on both Yelp and external PyPIs. Packages were able to install successfully after I added `venv-update==3.2.4` to Yelp's internal PyPI.

Un-revert #2712 and add hard pins in requirements-bootstrap.txt

---

paasta_tools/contrib/get_running_task_allocation.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

In #2684, I made `paasta status` check the pod container statuses for error messages. And in #2694, I made `paasta status` get the real hostname for pods, instead of the node names. In both cases, if there were no containers yet (i.e. the pod hasn't been scheduled yet), it would cause an Exception because `pod.status.container_statuses` and `pod.spec.node_name` would be `None`. This PR fixes the issue by checking if they are `None` first before doing anything with them.
`make test`
manual testing on a test cluster with a node the had to run on a non-existent pool (couldn't be scheduled)
On a broader note, when inspecting k8s objects, it is important to check that whether or not they are `None` or not. Most properties are optional, according to the k8s documentation.

Make get_pod_hostname return NotScheduled if pod has not yet been scheduled

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

I previously merged and reverted #2696 after discovering that having an empty affinity object on a pod resulted in all nodes being deselected from deployment. This PR reverts that revert and accounts for the "no affinities" case by only adding an affinity object to a pod spec if there are node affinities to add. I've also added a number of tests to account for that case.
`make test`
Tested by scheduling a pod with no deploy whitelists or blacklists on a test cluster
Since releasing #2696 caused an incident, I'd like to make a release and test it in kubestage before unpinning everywhere.

Ensure a k8s affinity object is added to pods only if there are affinities to set

---

paasta_tools/oom_logger.py
tests/test_oom_logger.py

I noticed the scribe log (tmp_paasta_oom_events) didn't contain many OOM events in stagef, and all the events that were there are Tron actions (the instance name contains a period). 
Here's an OOM event from a box in stagef:
```
Task in /kubepods/burstable/podf91e9681-4741-4ef4-8f5a-182c5683df8b/0e4a814eda03622476ff47871e6c397e5b8747af209b44f3b3e1c5289b0f9772 killed as a result of limit of /kubepods/bu
rstable/podf91e9681-4741-4ef4-8f5a-182c5683df8b/0e4a814eda03622476ff47871e6c397e5b8747af209b44f3b3e1c5289b0f9772 
```

Handle /kubepods cgroup in OOM logger

---

.pre-commit-config.yaml
debian/paasta-tools.links
paasta_tools/kubernetes/bin/kube_state_metrics_collector.py
paasta_tools/utils.py
requirements-minimal.txt
requirements.txt
setup.py
tests/kubernetes/bin/test_kube_state_metrics_collector.py

Example of the config I'm imagining we'd use: https://fluffy.yelpcorp.com/i/fJhPH6pQnBrK8xqvjbg2j3NFkRB31lNJ.html
I have tested this and it does indeed output the expected data and sends data to signalfx.  I am still not super convinced that this is better than using prometheus, but I wanted to finish it at the very least to use as a backup.

Kube state metrics collector

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

I decide to correct all labels. These label selectors are used to select metrics with dimensions [here](https://reviewboard.yelpcorp.com/r/490904/)

use paasta_cluster intead of kubernetes_cluster for HPA

---

paasta_tools/contrib/rightsizer_soaconfigs_update.py

With the current default of `config_source=args.csv_report`, commit messages look like
```
Update to autotuned_defaults configs from paasta_rightsizer_memory_recs.csv
This review is based on results from the following Splunk search:
| inputlookup paasta_rightsizer_memory_recs.csv | ...
```
With this change, we could do `--source-id=$BUILD_URL` in jenkins and get
```
Update to autotuned_defaults configs from https://jenkins-deploy.yelpcorp.com/job/paasta_rightsizer/137/
This review is based on results from the following Splunk search:
| inputlookup paasta_rightsizer_memory_recs.csv | ...
```
The csv report name is still in the detail message.

Add option to pass in attribution for rightsizing changes

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

This PR also enforces root access in driver container when
spark_cluster_manager == kubernetes. This is a temporary solution to
circumvent permission issue of reading k8s cluster SSL certificates of
host machines.

Avoid connecting to mesos leader during paasta validate

---

MANIFEST.in
paasta_tools/contrib/paasta_update_soa_memcpu.py

The actual installed package only includes the top level of schemas/, we need to add recursively now that autotuned_defaults exists.
```
$ ls /opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/cli/schemas
adhoc_schema.json  kubernetes_schema.json  marathon_schema.json  tron_schema.json
```
service_owner is only used in the review description, so it should be optional like the other keys.
https://github.com/Yelp/paasta/blob/master/paasta_tools/contrib/paasta_update_soa_memcpu.py#L364

Include all schemas and fix key error for autotuned_defaults

---

paasta_tools/check_kubernetes_services_replication.py
tests/test_check_kubernetes_services_replication.py

The default is [2m](https://github.com/Yelp/paasta/blob/master/paasta_tools/monitoring_tools.py#L277)

Bump alert_after from 2m to 5m for check_kubernetes_services_replication 

---

paasta_tools/config_utils.py
tests/test_config_utils.py

This will fail the Jenkins job and alert us.

Raise error if validation fails in AutoConfigUpdater

---

paasta_tools/cli/cmds/status.py

Show job information for all jobs only in verbose mode, otherwise show only the first few jobs. Use colors to highlight job status.

FLINK-2303 status color

---

paasta_tools/kubernetes/application/tools.py
paasta_tools/kubernetes_tools.py
paasta_tools/list_kubernetes_service_instances.py
tests/test_kubernetes_tools.py
tests/test_list_kubernetes_service_instances.py

list_kubernetes_service_instances currently shows service and instance names composed with a dot. I'm adding an option to show k8s sanitised names instead, i.e. the names deployments and statefulsets use when created by PaaSTA. I'm doing this so i can grep for the name of the paasta-contract-monitor's deployment from the source of truth (PaaSTA), and delete the deployment periodically so the PCM actually properly tests scheduling.
`make test`
manual testing on a test cluster
@drmorr0, I noticed that the Pd Disruption Budgets created by PaaSTA do not use any sanitised names. However, in the interest of not deleting the budgets that we have now, I'm not going to properly sanitise them in this review. I've added a TODO.

Add option in list_kubernetes_service_instances to show sanitised names

---

paasta_tools/deployd/watchers.py
tests/deployd/test_watchers.py

This is wrong:
```
paasta_tools.deployd.watchers.YelpSoaEventHandler:Looking for things to bounce for autotuned_defaults because /nail/etc/services/spectre_buster/autotuned_defaults/marathon-norcal-prod.yaml changed.
```

Fix service name in deployd for autotuned_defaults changes

---

paasta_tools/kubernetes/bin/kubernetes_remove_evicted_pods.py

I just commented it out for all services because I think this should not happen on stateful sets. They all use ebs volumes.

Turn off pod eviction alerts for stateless services

---

.pre-commit-config.yaml

A bump in this package broke our build, so I would like to stop that.
I'm also investigating how we can freeze all the things.

Pin aspy.refactor_imports in pre-commit to get a reproducible build

---

.travis.yml
k8s_itests/Makefile
k8s_itests/deployments/paasta/fake_etc_paasta/api_endpoints.json
k8s_itests/deployments/paasta/fake_soa_config/compute-infra-test-service/deployments.json
k8s_itests/docker-compose.yml
k8s_itests/test_autoscaling.py
k8s_itests/utils.py
tox.ini
yelp_package/dockerfiles/itest/k8s/Dockerfile
yelp_package/dockerfiles/itest/k8s/wait_paasta_api.sh

I didn't really want to do this since it's slow. But there are more refactoring than I thought to run it outside a container. I give up. 
I'll add a local docker registry later if I can. It's hard as kind runs in docker network, so it cannot talk to host network.

Make k8s_itests run in docker containers

---

paasta_tools/cli/cmds/status.py

- if not all jobs are being shown, print a warning to use -v to see them all
- -v option now shows all jobs, -vv needed to see pods, exceptions etc
- only color the status, rather than the whole line
Note: I planned to put Sofya on this PR too but she doesn't seem to be a member of the Yelp GH org, I'll send the PR to her for an unofficial review
Screenshots:
- normal usage (no -v), showing warning: https://yelp-shootie.appspot.com/shot/4582659305504768
- with -v, showing all jobs: https://yelp-shootie.appspot.com/shot/5166412535431168
- with -vv, showing all jobs and pods, exceptions etc: https://yelp-shootie.appspot.com/shot/4884504471666688
- with <3 jobs available, warning isn't shown: https://yelp-shootie.appspot.com/shot/4503976779710464

FLINK-2303 further changes

---

paasta_tools/oom_logger.py
tests/test_oom_logger.py

For autotune, we want to be able to join the oomkill logs with tmp_paastaallocations logs.
However currently the oomkill log only contains the docker id while paasta alllocation only contains docker id (when running on k8s) or mesos_task_id (when running on mesos)
This PR adds mesos_task_id to the log. If running on kubernetes, it will have the value 'null'
Also adding the useful memory limit of the container at the time of the OOM

Log mesos container id and memory limit with OOMkills

---

paasta_tools/oom_logger.py

I think this will be more useful for dashboards to see the impact of memory request changes. I don't think you can count events in sfx, unfortunately.

Emit metric for OOMs

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/check_kubernetes_services_replication.py
paasta_tools/cli/cmds/status.py
paasta_tools/instance/hpa_metrics_parser.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
paasta_tools/long_running_service_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

This branch is based on PAASTA-16313. 
This is the api part of implementation for HPA added. There will be anotehr PR for the client part. 
Tested with itest. More tests will be added in the client part. 
```
$ curl http://0.0.0.0:33222/v1/services/compute-infra-test-service/autoscaling/status
{"service": "compute-infra-test-service", "instance": "autoscaling", "git_sha": "a0ec9b36", "kubernetes": {"app_count": 1, "desired_state": "start", "bounce_method": "crossover", "app_id": "compute-infra-test-service-autoscaling", "pods": [], "replicasets": [], "expected_instance_count": 1, "deploy_status": "Waiting", "running_instance_count": 0, "create_timestamp": 1584934018.0, "namespace": "paasta", "autoscaling_status": {"min_instances": 1, "max_instances": 10, "metrics": [{"name": "memory", …
```

Expose HPA status and SFX metrics in paasta status

---

general_itests/steps/tail_paasta_logs.py
paasta_tools/cli/cmds/logs.py
tests/cli/test_cmds_logs.py

This PR adds --strip-headers, which causes paasta logs to just print the timestamp and message, skipping cluster, instance, log level and component. This was requested by Connectors, because the long headers make Flink logs quite difficult to read.
**Examples**
without strip-headers: https://yelp-shootie.appspot.com/shot/4643532397084672
with strip-headers: https://yelp-shootie.appspot.com/shot/4551395315810304
I would quite like to remove the 
This was requested for Flink services, but works equally well for regular PaaSTA services. Here it is for Apollo:
without strip-headers: https://yelp-shootie.appspot.com/shot/4594127790931968
with strip-headers: https://yelp-shootie.appspot.com/shot/4594127790931968
I'd like to strip the hostname and commit too, but those are part of the `message` …

Add --strip-headers option to paasta logs (PAASTA-16280)

---

paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/firewall.py
paasta_tools/long_running_service_tools.py
paasta_tools/utils.py
tests/test_firewall.py

Adds a new soa configuration variable, `inbound_network_mode` that accepts the following attributes:
* `full`: the default. No change versus existing behavior.
* `restrict`: adds a single iptables rule to `REJECT` all traffic for the service's `dport` at the end of the chain.
Advice welcome on testing this to verify the iptables chain works as expected. Unit tests otherwise added and pass as expected.
Context: PAASTA-16455

Add ability for services to opt out of inbound network traffic

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/check_kubernetes_services_replication.py
paasta_tools/cli/cmds/status.py
paasta_tools/instance/hpa_metrics_parser.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
paasta_tools/long_running_service_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

The only difference is in hpa_metrics_parser.py file (the last commit). I tested it on stagef this time. 
```
mingqiz@kube2-uswest1cstagef:~$ curl http://0.0.0.0:5054/v1/services/compute-infra-test-service/downthenup/status
{"service": "compute-infra-test-service", "instance": "downthenup", "git_sha": "41a908ac", "kubernetes": {"app_count": 1, "desired_state": "start", "bounce_method": "downthenup", "app_id": "compute-infra-test-service-downthenup", "pods": [], "replicasets": [], "expected_instance_count": 3, "deploy_status": "Running", "running_instance_count": 3, "create_timestamp": 1583533470.0, "namespace": "paasta", "autoscaling_status": {"min_instances": 3, "max_instances": 15, "metrics": [{"name": "http", "target_value": "400m"}, {"name": "http", "current_value": "0"}], …
```

Fix HPA status

---

paasta_tools/setup_kubernetes_cr.py
tests/test_setup_kubernetes_cr.py

Individual CRs can fail if missing deployments, we should only exit
1/page if a large enough proportion fail that means it's likely that the
script or deployment process is broken. As a "quick" fix I'm setting
that proportion to 100%

Only exit 1 if we fail to setup all CRs

---

paasta_tools/api/api_docs/swagger.json

Our swagger definition declares `pod.status.reason` and `pod.status.message`
with the types `['string','null']`. But Swagger 2.0 doesn't support null
as a data type. Luckily [bravado-core offers](https://bravado-core.readthedocs.io/en/stable/models.html#allowing-null-values-for-properties) the `x-nullable` extension
which can be used on this situation.
Manual tests:
- `paasta status -v` working when pod.status.reason and pod.status.message are both null
```
$ PAASTA_SYSTEM_CONFIG_DIR=~/etc-paasta paasta status -s compute-infra-test-service -c cluster -i main_k8s -v
service: compute-infra-test-service
cluster: cluster
instance: main_k8s
Git sha:    41a908ac (desired)
State:      Configured - Desired state: Started
Kubernetes:   Healthy - up with (10/10) instances (0 evicted). Status: …
```

PAASTA-16466 Fix `paasta status` regression with evicted pods

---

paasta_tools/oom_logger.py
tests/test_oom_logger.py

kubernetes has different hierarchies of cgroups depending on the qos for
the pod. for burstable and best effort QoS, a seperate namespace is
created under the /kubepods namespace (/kubepods/besteffort or
/kubepods/burstable), but for guaranteed qos the task is placed in the
/kubepods cgroup.
this fixes the regex we use to parse info from syslog output about the
pod that's killed by using an optional, non-capturing group to mark the
qos class used

PAASTA-16510 fix k8s oom regex

---

k8s_itests/test_autoscaling.py
paasta_tools/cli/cmds/status.py

WIth verbose 1
```
paasta_tools_1  | .
paasta_tools_1  | service: compute-infra-test-service
paasta_tools_1  | cluster: mingqiz-k8s-test
paasta_tools_1  |     instance: autoscaling
paasta_tools_1  |     Git sha:    a0ec9b36 (desired)
paasta_tools_1  |     State:      Configured - Desired state: Started
paasta_tools_1  |     Kubernetes:   Critical - up with (0/10) instances (0 evicted). Status: Waiting (new tasks waiting for capacity to become available)
paasta_tools_1  |       App created: 2020-03-30 21:04:05 (2 seconds ago). Namespace: paasta
paasta_tools_1  |     Autoscaling status:
paasta_tools_1  |        min_instances: 1
paasta_tools_1  |        max_instances: 1
paasta_tools_1  |        desired instances: 0
paasta_tools_1  |        last scale time: N/A
paasta_tools_1  | …
```

Add autoscaling status in paasta client

---

paasta_tools/api/api_docs/swagger.json
paasta_tools/cli/cmds/status.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/cli/test_cmds_status.py
tests/test_kubernetes_tools.py

We read the Kubernetes event stream to find the status message.
Unfortunately there is no way to get the event stream for _all_
"subobjects" from a Deployment, so we just look at a whitelisted set of
Kubernetes objects to get events from.  We then aggregate all of the
event streams, sort them, and take the most recent one as the status
message.
I also fixed a minor bug where services that have been `paasta stop` ed
would still show up as "Waiting" instead of "Stopped".
You can see the results of this here: https://fluffy.yelpcorp.com/i/6Tv1p2vQ5Kmssb5LTJHnZZJvnFgTVfbT.html
Line 10 shows that the container is failing for some reason
Line 26 shows that the service is stopped (this used to say `Waiting`)
Line 58 shows that there are capacity issues in the cluster
Lines 74, 98, and 110 show …

Provide better status updates from Kubernetes

---

k8s_itests/scripts/install-kind.sh

We have a new forked repo for kind which is now part of the Yelp org https://github.com/Yelp/kind/. Originally, we were building k8s images for itests off a fork from @keymone https://github.com/keymone/kind. We want https://github.com/Yelp/kind/pull/1 and all future PRs to apply to paasta itests .

Install kind should use new forked repo Yelp/kind

---

paasta_tools/api/views/pause_autoscaler.py
paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes_tools.py
paasta_tools/long_running_service_tools.py
paasta_tools/setup_kubernetes_job.py
tests/api/test_pause_autoscaler.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_job.py

The following code is used to pause HPA when a user has specified `paasta pause_service_autoscaler`. Currently, if a user runs pause autoscaler, the paasta api will write to zk `time_until` in minutes and `resumed` which is a bool. 
On a cron job, `setup_kubernetes_job` will update the k8s deployment which updates HPA and makes min_instanes = current replicas. This restricts the service from scaling down, but still allows it to scale up. Note that the `update` is only ran on two conditions: if service is paused OR if service is not paused and has not been resumed yet. 
Testing Done:
* make test
* added units tests

pause HPA for kubernetes services using zk

---

paasta_tools/cli/fsm/template/{{cookiecutter.service}}/smartstack.yaml

I'm not to concerned about the fact that the url is internal only :)

Make is easy for devs to find smartstack.yaml config options

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

In an effort to give devs more control over how their nodes are scheduled, as well as offer a limited equivalent for (Marathon) constraints to k8s tasks, I've exposed node selectors and affinities under a `node_selectors` config value in soa-configs. 
This is not intended to provide a functional replacement to Marathon constraints for  k8s apps. The Kubernetes scheduler already tries to spread pods out, much better than Marathon, so we shouldn't need as strong controls. However, if a dev wants to, say, only run their instances on specific instance types, then it is possible with this feature.
I've added comments and updated the soa-configs documentation to provide an explanation on how it's supposed to work.
- `make test
- Manual testing on a test cluster
- Status quo, no `node_selectors` …

Expose k8s node selectors and node affinities for Kubernetes apps

---

paasta_tools/oom_logger.py
tests/test_oom_logger.py

The main change is just L176 in oom_logger.py. Probably spent more time on the tests than I should have, but I wanted to make sure they would catch any similar typos next time. 
test_main was never being run after https://github.com/Yelp/paasta/pull/2346 because that change moved the import of ScribeLogger into main() itself, so `from paasta_tools.oom_logger import ScribeLogger` would fail even if clog was in the venv. Since we are mocking ScribeLogger anyway, we can run the tests regardless of whether it is in the venv or not.
After I made that change, I fixed the mesos container id mock and added tests for the sfx method.

Fix kwarg name in oom count metric and add tests

---

requirements.txt

The newer version of sticht ignores any `ratelimited` errors when
talking to splunk. This should remove a lot of noise from Jenkins deploy
logs.

Update sticht to 1.1.7

---

paasta_tools/marathon_tools.py
tests/test_marathon_tools.py

The client lib expects just a string now and does this dict for you.
This removes a ton of deprecation warnings when you run certain paasta commands that interact with marathon

Stop using the deprecated dict instead of string for marathon healthchecks

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/kubernetes_tools.py
paasta_tools/setup_kubernetes_job.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_kubernetes_tools.py
tests/test_setup_kubernetes_job.py

The following code is responsible for fixing the update deployment feedback loop caused by the revision annotation being bump after each iteration of `setup_kubernetes_job`. This code removes the need for pause_service_autoscaler to depend on annotations in the metadata spec. Instead, in order to determine whether the deployment has been paused, it manually just queries the k8s API, and check the annotations on the object directly.
In addition, we've also added an extra check so deployments will not continually be updated when paused. Conditions for `setup_kubernetes_job` to run `update()`:
- If k8s deployment config sha is different than existing one.
- If HPA is paused AND the deployment has not been paused yet.
- If HPA is resumed AND the deployment is still paused.
* make test
* …

Remove annotations from metadata spec and improve pause HPA

---

paasta_tools/cli/cmds/status.py

The bug happens when the target_value of the metric is None:
Sample output is here: https://fluffy.yelpcorp.com/i/rm1q9mRVzNkJlnm2hls5G1nmxsSVpfSv.html

fix the traceback when metric value is None

---

paasta_tools/instance/kubernetes.py

They should be min_replicas/max_relicas according to
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V2beta1HorizontalPodAutoscalerSpec.md

Fix HPA spec min/max instances namings

---

paasta_tools/autoscaling/autoscaling_service_lib.py

Apparently this was the "real" fix. Previously in my tests I just made a session, but left default timeouts. After taking @Rob-Johnson 's feedback I added the 2 second timeout back in, but didn't test in prod again.
Well, the errors were still there :(
Patching in this timeout in prod makes the errors go away, so I guess I'll patch it back in here. 
If you want I'll undo my other changes and make a session per request? But I don't think a single session isn't such a bad idea.

Up the timeout for aio session for autoscaling

---

paasta_tools/check_oom_events.py
tests/test_check_oom_events.py

With autotuned_defaults running services with smaller margins on resources, we expect occasional OOMs. We want to keep these OOM alerts actionable, and don't want service owners to disable autotuned_defaults every time an OOM occurs. Even if a service isn't using autotuned_defaults, they don't necessarily need to bump memory on every OOM.
We will still be showing every OOM in dashboards and logs, and the rightsizer will take them into account - we just want to give the rightsizer some time to adjust. 
At the same time, the alert should still show serious issues with the memory value. We can explore different settings, but I'm thinking we can start with something conservative like alert_threshold=2 and check_every=5, so it will alert if any 2 containers in the same service instance OOM …

Paasta 16560 check oom events thresholds

---

paasta_tools/cli/cmds/status.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
tests/cli/test_cmds_status.py
tests/test_kubernetes_tools.py

Currently, `paasta status <service>.<instance> -vv` shows us the stdout/stderr for a specific container (`docker logs`). However, most pod errors are not caused on the application level, but usually caused by the kubernetes scheduler itself (ie, failed to pull image, pod is stuck in scheduler, etc). Therefore, on top of displaying app logs, we also want to display the k8s event logs to our users so they can figure out why their pods aren't scheduling and debug.
Here is an example output with event logs: https://fluffy.yelpcorp.com/i/LZczNbLmMhDDF503xPSL6Z0nb5JtCHq2.html#L15-17
Note that some of this code may be reused in https://github.com/Yelp/paasta/pull/2761 and vice versa. 
* make test
* manually tested on various pods in kubestage

Make paasta status display k8s event log for pods

---

paasta_tools/kubernetes_tools.py
paasta_tools/metrics/metastatus_lib.py
tests/metrics/test_metastatus_lib.py

Allocatable resource from k8s nodes describes the total resource can be allocated.
The value will not changed if the resource is allocated to the pods. To get the value
for allocated resource, we need to aggregate the resource requirement from all pods.
The sample output is here: https://fluffy.yelpcorp.com/i/7gw50nz68qbQnKhXRczwPXwl1NmGbkL2.html
I have confirmed the number matches the number reported by `kubectl describe nodes`
I don't implement the gpu part since we are not using that now.

Fix paasta metastatus reports incorrect resource usage

---

paasta_tools/api/api_docs/swagger.json

According to go-swagger:
```
The swagger spec at "/nail/home/maksym/paasta-tools-go/swagger.json" is invalid against swagger specification 2.0. see errors :
- "paths./services.get.responses.200" must validate one and only one schema (oneOf). Found none valid
- "paths./services.get.responses.200.schema" must validate one and only one schema (oneOf). Found none valid
- "paths./services.get.responses.200.schema.properties.services.items" must validate at least one schema (anyOf)                            
- "paths./services.get.responses.200.schema.properties.services.items.items" must validate at least one schema (anyOf)
- paths./services.get.responses.200.schema.properties.services.items.items in body must be of type object: "string"
```

PaaSTA swagger.json is invalid

---

paasta_tools/oom_logger.py
paasta_tools/utils.py
tests/test_oom_logger.py
yelp_package/extra_requirements_yelp.txt

Monk is the recommended way of logging at Yelp, this commit adds support
to log to Monk as well as Scribe.
Newer versions of yelp_clog support both Monk and Scribe as a backend,
depending on configuration values.
Also make the oom_logger use clog.log_line (which supports Monk and
Scribe) rather than forcing Scribe.
-----
* `make {test,itest,itest_xenial}` all pass
* Tested the `MonkLogWriter` locally (as well as ensured the updated `ScribeLogWriter` was still working), by changing `/etc/paasta/logs.json`
```
{
"log_writer": {
"driver": "monk",
"monk_host": "169.254.255.254",
"monk_port": 1473,
"monk_disable": false,
"options": {
"monk_host": "169.254.255.254",
"monk_port": 1473,
"monk_disable": false
}
}
...
}
```
```python
>> ./.tox/py36-linux/bin/python
Python 3.6.0 (default, Jan 13 …
```

Add support for logging to Monk

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/kubernetes_tools.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/test_kubernetes_tools.py

Currently our HPA-related logic only applies to k8s deployments, but in the context of setup_kubernetes_job, a paasta service instance can also be a k8s stateful set. Apply HPA config update against a stateful set can lead to issues.
For example, `is_deployment_marked_paused` method assumes a deployment with name 'foo' already exists and attempts to fetch annotations of it. In the case of a stateful set, a deployment with the same name does not exist and k8s API server will return 404, which crashes setup_kubernetes_job run.

Do not attempt to update HPA configs of a stateful set

---

paasta_tools/contrib/add_to_deploy_queue.py
paasta_tools/deployd/master.py
tests/deployd/test_deployd_master.py

Only flood the deployd queue on deployd startup if we aren't using the ZK queue.
Also added a simple script to add an arbitrary instance to the queue (I tested this on a real master and it works).

Dont flood deployd queue on start

---

extra-linux-requirements.txt
paasta_tools/cli/cmds/logs.py
requirements.txt
tests/cli/test_cmds_logs.py
yelp_package/extra_requirements_yelp.txt

scribereader 0.2.6 is over 3 years old, and data streams core is deprecating things. I'm bumping it to 0.8.0, instead of 0.8.1 (which is the latest version), because 0.8.1 removes support for uswest1. However, our logs config still have uswest1 (see `/etc/paasta/logs.json`), and I can't change it to uswest2 ahead of this fix because the current version of scribereader PaaSTA uses doesn't know about uswest2. Version 0.8.0 supports both uswest1 and uswest2, so it's a stopgap version.
- make test
- make itest_xenial
- Various `paasta logs` test runs:
- `paasta logs -s clusterman -i cluster_metrics -c pnw-prod -C app_output -v -f`
- `paasta logs -s clusterman -i cluster_metrics -c pnw-prod -C app_output -v -n 1000`
- `paasta logs -s clusterman -i cluster_metrics -c pnw-prod -C app_output -v …

Bump scribereader to 0.8.0

---

paasta_tools/firewall_update.py
tests/test_firewall_update.py

Currently, firewall_update.py only checks for outbound_firewall rules when determining whether to include smartstack mapping information (consumed downstream by iptables rules).
This change ensures that inbound_network_mode is also checked to ensure this information is made available.

Ensure inbound_network_mode propagates smartstack iptables dependencies

---

paasta_tools/long_running_service_tools.py
paasta_tools/utils.py

This method was improperly named from the outset, preventing `inbound_network_mode` from being read properly. This also did not appear to result in a crash during configuration, possibly due to use of config proxying behavior by paasta.
Renaming this should fix inbound_network_mode behavior. No test changes are necessary since the test class is already named properly (and, unfortunately, uses mocks as its strategy).

Fix name of get_inbound_network_mode method

---

paasta_tools/cli/utils.py
paasta_tools/instance/kubernetes.py
paasta_tools/nrtsearchservice_tools.py
paasta_tools/utils.py
tests/test_utils.py

Adding support to paasta to deploy [Nrtsearch](https://github.com/Yelp/nrtsearch) instances. I referred to [this](https://github.com/Yelp/paasta/commit/d62fab6e59a60550ba7d08a25642e01e74fa1caa#diff-0d44e5e2fce89bc20646d34e095c7c73) commit which similarly added support for Kafka.
`make test` passes. Also deploying an instance by running `paasta_tools.generate_deployments_for_service` and `paasta_tools.setup_kubernetes_cr` worked fine.

Added support for applying Nrtsearch k8s CRs

---

paasta_tools/cli/schemas/marathon_schema.json
paasta_tools/firewall.py
paasta_tools/firewall_update.py
paasta_tools/utils.py
tests/test_firewall.py
tests/test_firewall_update.py

For consistency with `outbound_firewall` and its collection of options. This also renames the config parameters to `accept` and `reject` to indicate what they'll do in iptables.

Rename inbound_network_mode to inbound_firewall

---

paasta_tools/deployd/common.py
paasta_tools/deployd/watchers.py
tests/deployd/test_common.py
tests/deployd/test_watchers.py

I'm trying to make it easier to figure out how long it takes deployd to bounce something by matching the marathon app ids in Splunk.

log the marathon app-id in deployd so we can better track bounce timings

---

paasta_tools/cli/schemas/marathon_schema.json

Fixes this issue in config validation:
> remote:   Validation Message: 'reject' is not one of ['full', 'restrict']

Update inbound_firewall schema to reflect the changed variable names

---

paasta_tools/api/api_docs/swagger.json

InstanceStatus/flink property gets a struct named InstanceStatusFlink, which
collides with InstanceStatus/flink/status property definition.

Fix InstanceStatusFlink name collision in go-swagger generated client

---

paasta_tools/cli/cmds/status.py

Trivial changes as described by Antonio in FLINK-2575
- State: running for the cluster should be State: Running for parity with the rest of paasta status and the word Running should be green. All the other states should be yellow (we do not have a failed state that could be red).
- The state of jobs is all uppercase (e.g.; RUNNING), but it should be just capitalized (e.g .; Running) for consistency with the rest of paasta status.
-  Flink jobs should be green if Running, red if Failed or Failing, yellow in all other cases (the list of all states is
`[ "CREATED", "RUNNING", "FAILING", "FAILED", "CANCELLING", "CANCELED", "FINISHED", "RESTARTING", "SUSPENDED", "RECONCILING" ]`)
`make itest` and `make test` pass with no changes required.

Minor formatting changes to paasta status for flink services

---

paasta_tools/mesos_maintenance.py
paasta_tools/setup_marathon_job.py
tests/test_setup_marathon_job.py

This 1) logs the ReadTimeout but keeps going, and 2) adds a cache on get_maintenance_status. We can see if the cache helps by checking the deployd logs for the timeout lines.
I tested the cache manually on a Mesos master by making a copy of mesos maintenance, making this change there, and then running a script that calls it a few times.

Reduce timeouts in setup_marathon_job from get_draining_hosts

---

extra-linux-requirements.txt
paasta_tools/check_oom_events.py
paasta_tools/cli/cmds/logs.py
requirements.txt
tests/cli/test_cmds_logs.py
tests/test_check_oom_events.py
yelp_package/extra_requirements_yelp.txt

Previously I updated scribereader to 0.8.0 but that was reverted because I didn't also update certain outdated calls in `check_oom_events` as well. This PR un-reverts the update and also updates `check_oom_events` to match as well.
`make test`
Locally ran `check_oom_events` against the `norcal-devc` cluster

Also update scribereader in check_oom_events

---

paasta_tools/api/api.py
paasta_tools/api/settings.py
paasta_tools/api/tweens/request_logger.py
tests/api/tweens/test_request_logger.py

This PR adds the a tween to the PaaSTA API to make it log response times, status codes, and exception information for requests made to clog (if available). We aren't really logging this elsewhere; once we get this into scribe, we can start processing it to see how our API is performing.
make test
Ran the API locally against the kubestage cluster with the tween set up. Had it print to the console instead of actually logging to clog.

Add tween to log request info to CLog

---

paasta_tools/oom_logger.py

Apparently we needed to downgrade yelp_clog for the scribereader update here: https://github.com/Yelp/paasta/pull/2815/files#diff-238a62906b32a2556199a125adf97658L18
But 4.1.1 requires these as positional args, they only became optional in 5.0.0.
```
File "/usr/bin/paasta_oom_logger", line 11, in <module>
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/oom_logger.py", line 191, in main
clog.config.configure(monk_disable=False)
TypeError: configure() missing 2 required positional arguments: 'scribe_host' and 'scribe_port'
```

yelp_clog 4.1.1 requires scribe host and port

---

paasta_tools/oom_logger.py

https://github.com/Yelp/paasta/pull/2819 made oom_logger stop crashing, but the lines still weren't showing up. Turns out 5.0.0 will create a monk logger if scribe_disable is True, but 4.1.1 won't, so we need to explicitly pass scribe_disable=False.
This time I created a logger with these settings and confirmed that they show up.
```
clog.config.configure(scribe_host="169.254.255.254", scribe_port=1463, monk_disable=False, scribe_disable=False)
clog.log_line('tmp_test', f'test {time.time()}')
$ scribereader -e devc tmp_test -n 10
test 1590691290.7611883
```

yelp_clog 4.1.1 doesn't create any logger if scribe_disable is True

---

paasta_tools/firewall.py
tests/test_firewall.py

Previously, this was placed at the end of `_smartstack_rules`, placing inbound filters after rules established to allow smartstack traffic. When envoy is used, this doesn't make sense. It also doesn't make sense to require a dependencies file for this filtering behavior, either.
As such, this has been moved upwards one layer and refactored accordingly. I've also included an allow for traffic from localhost, should other rules not propagate it to this location.
Including Krall as CC, due to some chatter about healthcheck traffic today. This is an opt-in feature, so this should only impact services that include it.

Refactor inbound_firewall to not depend on smartstack dependencies

---

paasta_tools/contrib/is_pod_healthy_in_smartstack.py

This should be picked up by the kubelet and displayed in the pod's events log, which should lead to more helpful error messages in the output of paasta status when the readiness probe fails
Messing with the hacheck sidecar seems potentially scary -- I might test this on kubestage first?

Make is_pod_healthy_in_smartstack report an error message when it fails

---

requirements.txt
yelp_package/extra_requirements_yelp.txt

somehow I didn't actually include the `**` as recommended by @kawaiwanyelp [here](https://github.com/Yelp/sticht/pull/15#discussion_r432034870) -- I've fixed this in sticht 1.1.9

Bump sticht to 1.1.9 to get SCRIBE_ENV fix

---

paasta_tools/cli/schemas/autotuned_defaults/kubernetes_schema.json
paasta_tools/cli/schemas/autotuned_defaults/marathon_schema.json
paasta_tools/contrib/paasta_update_soa_memcpu.py
paasta_tools/contrib/rightsizer_soaconfigs_update.py
tests/test_config_utils.py

1) Added disk support to the original rightsizer (not autotuned_defaults) and tested a local bulk update:
`/opt/venvs/paasta-tools/bin/python ~/git/paasta/paasta_tools/contrib/paasta_update_soa_memcpu.py -s ********:**************** -y ~/git/yelpsoa-configs --csv-report paasta_rightsizer_disk_recs.csv -f '*stageg*' --app yelp_computeinfra -v -l`
Fluffy of the diff
https://fluffy.yelpcorp.com/i/WGd8WMW65bZhQj8wRXr56Kn5THSxX95z.html
2) Added support to paasta_tools.contrib.rightsizer_soaconfigs_update
Tested it manually before:
```│(py36-linux) dev42-uswest1adevc:~/git/paasta/paasta_tools/contrib % /opt/venvs/paasta-tools/bin/python -m paasta_tools.contrib.rightsizer_soaconfigs_update -c paasta_rightsizer_disk_recs.csv --git-remote git@sysgit.yelpcorp.com:yelpsoa-configs -v -s …
```

Add disk recos support 

---

paasta_tools/firewall.py
tests/test_firewall.py

This currently lives in contrib/graceful_container_drain, not as a config accessor. Updated the call and test accordingly.

Fix the call to get_proxy_port for inbound firewall mode

---

paasta_tools/firewall.py
tests/test_firewall.py

Fixes a typo I introduced in inbound_firewall rules. These should be `ACCEPT`; `ALLOW` is not the correct keyword.

Fix typo in ACCEPT rules (should be ACCEPT, not ALLOW)

---

paasta_tools/firewall.py
tests/test_firewall.py

Instead of using get_proxy_port -- which may not be the correct port exposed for each running container -- this change instead uses nerve to identify the correct ports when `inbound_firewall` is set to `restrict`.

Use nerve ports instead of get_proxy_port

---

setup.py

In 1e23c51170e70ed3db0bb4acf99823af2c545f5a I restricted the glob to *.py to avoid including the __pycache__ directory, but this had the effect of also omitting shell scripts.

Also include shell scripts from contrib dir

---

paasta_tools/firewall.py

I am not sure what paasta_native refers to, but I think it's something distinctly different from what we actually want, which is marathon services. 
From an interpreter shell on a paasta agent in devc =>
```
>>> from paasta_tools.native_mesos_scheduler import paasta_native_services_running_here
>>> paasta_native_services_running_here()
[]
>>> from paasta_tools.marathon_tools import marathon_services_running_here
>>> marathon_services_running_here()
[('npm', 'main', 31026), ('replication_handler', 'data_pipeline_primary', 31541), ('salesforce_pipeline', 'account_statistics_kew_threshold_spolt', 31200), ('salesforce_pipeline', 'biz_photo_transform_spolt', 31835), ('yelp-main', 'service_eligibility_spolt', 31845), ('salesforce_pipeline', 'category_yelp_transform_spolt', 31565), …
```

Use different paasta method to dump locally running services

---

paasta_tools/cli/cmds/spark_run.py
tests/cli/test_cmds_spark_run.py

Just noticed that the spark batch will failed if people had environment settings on the batch name. 
fixed the unit tests and also tested it manually. It successfully give the correct job name with or without the environment variables in the commands.

fix the bug that spark-run failed to parse the environment variable in command

---

paasta_itests/steps/setup_marathon_job_steps.py
paasta_tools/generate_deployments_for_service.py
paasta_tools/marathon_tools.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
requirements.txt
tests/test_generate_deployments_for_service.py
tests/test_marathon_tools.py
tests/test_tron_tools.py
tests/test_utils.py

original attempt: #2814
second attempt: #2821
This time relies on https://github.com/Yelp/service_configuration_lib/pull/48 which allows me to  bypass deepcopy altogether instead of trying to cache the result of it.

Speed up generate deployments a third time

---

paasta_tools/api/api.py
paasta_tools/api/settings.py
paasta_tools/api/tweens/request_logger.py
tests/api/tweens/test_request_logger.py

I initially tried to release request logging for the PaaSTA API but it caused the API to crash when it tried to log since clog was not properly setup. I've added a function `setup_clog` that runs before the pyramid Configurator is set up, which resolves the issue.
Ran paasta-api locally with clog enabled (I did not have it enabled before, so I didn't catch the issue)

Fix request logger clog setup

---

paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py

Seems like a good idea to be able to configure things like pod's dns policy from system paasta configs.

Pod defaults from system paasta config

---

paasta_itests/steps/bounces_steps.py
paasta_tools/bounce_lib.py
paasta_tools/long_running_service_tools.py
paasta_tools/marathon_tools.py
paasta_tools/mesos_maintenance.py
paasta_tools/mesos_tools.py
paasta_tools/monitoring_tools.py
paasta_tools/paasta_metastatus.py
paasta_tools/setup_marathon_job.py
paasta_tools/tron_tools.py
paasta_tools/utils.py
tests/cli/test_cmds_info.py
tests/test_marathon_tools.py
tests/test_mesos_maintenance.py
tests/test_monitoring_tools.py
tests/test_setup_marathon_job.py

These changes drastically decrease the amount of CPU time needed by deployd's workers / setup_marathon_job.
The first commit, 546cc64, makes it so we only request information about apps that matter from Marathon.
The second and third commits, 30b7371 and 700784c, aim to reduce the number of times `load_system_paasta_config` is called by passing around SystemPaastaConfig objects to almost everything that needs it that ends up being called by deployd. (The one exception remaining in my pyflame charts is https://github.com/Yelp/paasta/blob/766c25dcf3bba640e51a4e9ba8091f63910b79bf/paasta_tools/utils.py#L2915 -- removing this would give a further 20% CPU time improvement). It turns out that even though `load_system_paasta_configs` tries very hard not to re-parse YAML, the code that determines …

Optimize deployd workers

---

paasta_tools/kubernetes_tools.py

I think stdout/stderr for k8s instances was broken in this review: https://github.com/Yelp/paasta/commit/7ac9f14e143b926d7a7672b63ba50fc7016f7914#diff-8099076c2ecaf9f1a063335425abd3c1R1511
There's no clear reason why that line was changed in that review. 
When we put the log lines into the API response, it's with a lowercase "stdout": https://github.com/Yelp/paasta/blob/master/paasta_tools/kubernetes_tools.py#L1533
I manually tested this by making this change on the paasta master in pnw-prod (I think this was relatively low-risk because it only affects the CLI side of paasta status on that box). With this change, I got tracebacks from a recently failed container through -vv, which I wasn't getting before. https://fluffy.yelpcorp.com/i/sv8Qpb2xVfsGVv8qblLT8HLRljFHWdvM.html
Let me know if …

Fix name of stdout stream for k8s status

---

requirements.txt

Updating spark namespace from `spark` to `paasta-spark` see: https://github.com/Yelp/service_configuration_lib/commit/5f5b1cd8b44b8d02f54edcb6aad43b10b84166a3

service-configuration-lib==2.4.6

---

paasta_tools/contrib/get_running_task_allocation.py
paasta_tools/kubernetes_tools.py

Current state: [get_running_task_allocation](https://sourcegraph.yelpcorp.com/mirrors/Yelp/paasta@ace761b252ddc14ebce9b98f19c12cbf1a7f0305/-/blob/paasta_tools/contrib/get_running_task_allocation.py#L222:26) is currently hard-coded to fetch task allocation metrics from kubernetes pods only for [paasta](https://sourcegraph.yelpcorp.com/mirrors/Yelp/paasta@ace761b252ddc14ebce9b98f19c12cbf1a7f0305/-/blob/paasta_tools/kubernetes_tools.py#L1828:1) namespace.
Ideal state is to emit task allocation metrics for all namespaces prefixed as `paasta`. This will eventually be used in cost reports to report cost allocation for all kubernetes pods.
The code change is backwards compatible (i.e. no need to change to the [puppet](https://sourcegraph.yelpcorp.com/sysgit/puppet@45039da539c1efac674dff4dd075424b …

Add support to emit task allocation metrics for all namespaces with matching given prefix

---

paasta_tools/autoscaling/autoscaling_service_lib.py
paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/setup_kubernetes_job.py
tests/autoscaling/test_autoscaling_service_lib.py
tests/kubernetes/application/test_controller_wrapper.py
tests/test_setup_kubernetes_job.py

Previously we only synced these if we determined that the Deployment needed to be updated, but there are cases where users change autoscaling settings (which only affect the HPA) without changing anything that affects the Deployment.
See PAASTA-16675
---
Note that I am also getting rid of the `is_paused` annotation we were putting on deployments.  This really was just so that we would know we needed to call `app.update()` so that the HPA got updated when autoscaling transitions between paused and resumed.  However, because of what I'm describing above, we actually need to check these every time, so we don't need this extra bit of coordination.
I also considered just having us update the deployment every time, since it seems like that is fine -- if no fields have changed it just bumps the …

Always sync HPAs and Pod Disruption Budgets in setup_kubernetes_job

---

.gitignore
.travis.yml
debian/paasta-tools.links
debian/rules
yelp_package/Makefile

The binary is shipped with paasta-tools deb to avoid having to deal with multiple packages providing same usr/bin/paasta link.

Use paasta-tools-go/cmd/paasta as entrypoint

---

paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Our previous attempt looked at the average load seen by each instance, which led to oscillations what the HPA wanted to scale to (see DAR-920).  This approach was found to be more stable.
See PAASTA-16756
---
The one change I made to the custom signalflow that you wrote this weekend was to add a `max(results, 0)` so we don't return something less than 0.
I tested this by running it for compute-infra-test-service.downthenup on norcal-stagef.  Here are the results that show it works: https://fluffy.yelpcorp.com/i/M4NqNV3hrjhMQCbQSPGbRKlCB9rx2FCt.html

Emulate the legacy autoscaler's approach to windowed averaging for HPAs.

---

general_itests/fake_etc_paasta/vault.json
paasta_tools/cli/cmds/validate.py
tests/cli/test_cmds_validate.py

This change adds a new test to `paasta validate` so that operators will know if any of their service instances reference a secret that doesn't exist.
The reason for this change is that mesos would allow such situations, but kubernetes would fail to bring up the service.
So an early check will help to avoid these situations.
More info on PAASTA-16499

PAASTA-16499 `paasta validate` now checks if vault secrets are defined

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/utils.py
requirements.txt
tests/cli/test_cmds_mark_for_deployment.py

WIP.
The purpose of this review is to allow for separate authz on mark-for-deployment, while allowing for other paasta commands to be executed by unprivileged paasta users. This is needed because certain git hosts (ie, Github) are unable to protect tags or implement this behavior in githooks, preventing this behavior to be enforced by git itself.

SEC-12874: Add prototypical authz to mark-for-deployment

---

paasta_tools/cli/cmds/mark_for_deployment.py
paasta_tools/cli/cmds/rollback.py
tests/cli/test_cmds_mark_for_deployment.py
tests/cli/test_cmds_rollback.py

Instead of specifying authz on the call to mark-for-deployment, this instead uses settings made available by deploy.yaml. 
Since this setting can be used by other tooling (and does not require a code rewrite to enable), this is preferred vs the previous approach.

Use deploy.yaml for push groups when performing m-f-d authz check

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Adding support for pod anti-affinity on `service` and `instance` in PaaSTA with the following DSL
```yaml
anti_affinity:
service: "service"
instance: "instance"
```
```yaml
anti_affinity:
- service: "service"
instance: "instance"
- service: "service_2"
instance: "instance_2"
```
`make test` passes

Adding support for anti-affinity in PaaSTA

---

paasta_tools/cli/cmds/mark_for_deployment.py

This fixes as bug introduced due to variable name confusion, and presents the user with a friendly error instead of a traceback when they're not authorized to continue `mark-for-deployment` or `rollback`.
This was tested manually by trying `paasta mark-for-deployment -c <sha> -l <deploy_target> -s <service> -d <soa_dir>` locally with `allowed_push_groups` set in deploy.yaml. I verified both the success case (with a user in the appropriate group) and the deny case (using my own user, which did not have the appropriate groups) manually.
Previous reviews should have sufficient testing coverage, but happy to add more here as needed.

Fix redefinition of username during ldap check, make failed checks more friendly

---

docs/source/yelpsoa_configs.rst
paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
tests/test_kubernetes_tools.py

Adding `prometheus_port` support in `yelpsoa_config` to expose extra ports for prometheus metrics scraping
`make test` passes

Adding prometheus port support in PaaSTA

---

paasta_tools/kubernetes/application/controller_wrappers.py
paasta_tools/setup_kubernetes_job.py
tests/test_setup_kubernetes_job.py

1) We don't log a JSON-ified list of service-instances updated at the
end, because we can already get that information and it just gets split
up weirdly in syslog, which would make Splunk ingestion worse.
2) Suppress logs from kazoo because these are noisy and useless most of
the time
3) Make sure that we update "related" API objects every time the script
runs (it actually did this before too, but it was less clear, because
the update was called in two different places)

minor improvements to setup_kubernetes_job

---

paasta_tools/tron_tools.py
tests/test_tron_tools.py

2 changes to make setup_tron_namespace more efficient.
You can just give Spark the zk string and it will find the leader itself: https://spark.apache.org/docs/latest/running-on-mesos.html#using-a-mesos-master-url
So we don't need to run find_mesos_leader and reconfigure each time the mesos leader changes. I've tested this in Mesosstage and the driver was able to find the leader.
But I don't think this is the cause of the slowness on tron sync deploy, because we actually don't have any jobs with `executor: spark` and `spark_cluster_manager: mesos`. They are all scheduling using k8s.
I'm not sure this is the cause of the slowness either, but it's definitely inefficient. I noticed spark and ad_targeting_batches (the namespaces with `executor: spark` jobs) are getting re-configured …

Tron 1553: reduce spark reconfiguration

---

paasta_tools/cli/schemas/kubernetes_schema.json
paasta_tools/kubernetes_tools.py
paasta_tools/long_running_service_tools.py

Added `iam_role_provider` parameter for services which can be set to
either `kiam` (default) or `aws`.  If it's set to `aws` then PaaSTA uses
the AWS pod identity solution [1] instead of `kiam` to support per-pod
IAM profiles.
[1] https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
AWS pod identity creates a token with `0600` permissions and
`root:root`:
```
-rw------- 1 root root 1498 Aug 13 12:47 /run/secrets/eks.amazonaws.com/serviceaccount/..2020_08_13_12_47_11.793276204/token
```
This prevents programs running inside containers using a non-root
account to read the token.  See [1] for details.
This CR working around that by adding
```
securityContext:
›         fsGroup: 65534
```
into the pod spec.
After that the token is owned by the given …

Support iam_role using AWS pod identity solution

---

paasta_tools/cli/cmds/status.py
tests/cli/test_cmds_status.py

This has been added to the `status` of a KafkaCluster custom resource and is not optional.

Show Kafka Zookeeper connection string in paasta status

---

mypy.ini
paasta_tools/api/views/instance.py
paasta_tools/check_flink_services_health.py
paasta_tools/check_kubernetes_services_replication.py
paasta_tools/check_marathon_services_replication.py
paasta_tools/check_services_replication_tools.py
paasta_tools/drain_lib.py
paasta_tools/envoy_tools.py
paasta_tools/instance/kubernetes.py
paasta_tools/kubernetes_tools.py
paasta_tools/monitoring_tools.py
paasta_tools/setup_marathon_job.py
paasta_tools/smartstack_tools.py
paasta_tools/utils.py
requirements.txt
tests/api/test_instance.py
tests/conftest.py
tests/test_check_flink_services_health.py
tests/test_check_kubernetes_services_replication.py
tests/test_check_marathon_services_replication.py
tests/test_check_service_replication_tools.py
tests/test_envoy_tools.py
tests/test_kubernetes_tools.py
tests/test_monitoring_tools.py
tests/test_smartstack_tools.py
tests/test_utils.py

In addition to getting replication information from Smartstack, get the
same information from Envoy, and use both of them to send notifications
about underreplicated services.
While here I also cleaned up some `mypy` stuff.

PaaSTA instance Envoy replication checks

---

paasta_tools/contrib/is_pod_healthy_in_proxy.py
paasta_tools/envoy_tools.py
paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/test_envoy_tools.py
tests/test_kubernetes_tools.py
yelp_package/dockerfiles/hacheck-sidecar/Dockerfile
yelp_package/dockerfiles/hacheck-sidecar/check_proxy_up.sh

Adds a new pod readiness script (`/check_proxy_up.sh`) that supports both Envoy and Smartstack.
For now, this readiness script won't be enabled on any service, meaning that we won't have any bounces after merging.
To enable the new readiness check on a single service, we can add the following to yelpsoa-configs (`KubernetesDeploymentConfigDict`):
```
bounce_health_params:
check_envoy
```
`check_haproxy` can be set as well to check smartstack (and can coexist with `check_envoy`).
To enable the new readiness check on every service, the following param can be added to `SystemPaastaConfigDict`
```
enable_envoy_readiness_check: true
```
`enable_nerve_readiness_check` can be set as well to check smartstack (and can coexist with `enable_envoy_readiness_check`)
- Multiple manual tests on a k8s …

MESH-857 Pod readiness checks supporting Envoy / Smartstack

---

paasta_tools/kubernetes_tools.py
paasta_tools/utils.py
tests/test_kubernetes_tools.py
tests/test_utils.py

Add the `hacheck_sidecar_volumes` paasta config key to mount volumes into the hacheck sidecar container:
Eg:
```
$ cat /etc/paasta/hacheck_sidecar_volumes.json
{
"hacheck_sidecar_volumes": [
{
"hostPath": "/etc/services",
"containerPath": "/etc/services",
"mode": "RO"
}
]
}
```
I did this independently from the existing `volumes` key as it might not be a good idea to mount every volume on that list into the sidecar container.
We need this feature so we can mount `/etc/services` into the hacheck-sidecar container. Without this file present, [get_envoy_admin_port()](https://github.com/Yelp/paasta/blob/22a35e16672d1afbf20a3c09cd90de4db59e5241/paasta_tools/utils.py#L2428) doesn't work.
Note that this change will bounce every service.
- Manually deployed the config file …

MESH-857 Adds volume_mounts to the hacheck sidecar container

---

paasta_tools/cli/utils.py
paasta_tools/utils.py
tests/test_utils.py

I realized when trying to make a git config file that the server we trigger deploys on and the server clone soa-configs from will be different, but are the same right now. So, the two need different keys in the git config.
`make test`

Separate git server from primary server in git config
