Yelp/paasta

- yelp_package/dockerfiles/bionic/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
Ubuntu `python-pip` package contains an ancient version of `pip`, which
fails to retry after network error with the following message:
```
File
"/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py",
line 228, in increment
total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
As a result, most of our Travis jobs fail on initial runs and need several manual retries.
This PR fixes that by upgrading `pip` to a more recent version.
Run Travis tests a couple of times with no failures, see https://travis-ci.org/github/Yelp/paasta/builds/720948239 and https://travis-ci.org/github/Yelp/paasta/builds/720955289
> Fix pip fails to retry after network errors

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
`get_readiness_check_script()` and `get_envoy_nerve_readiness_check_script()` will return a string such as `/check_proxy_up.sh --enable-smartstack --enable-envoy` instead of returning a List of arguments (which is what V1ExecAction expects).
This triggers the following errors when enabling Envoy readiness checks:
```
Warning  Unhealthy  60s (x29 over 5m40s)  kubelet, ip-10-114-45-230.us-west-1.compute.internal  Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"/check_proxy_up.sh --enable-smartstack --enable-envoy\": stat /check_proxy_up.sh --enable-smartstack --enable-envoy: no such file or directory": unknown
```
So I'm amending the command passed to V1ExecAction, providing each argument as a list item.
Note …
> MESH-857 Fix hacheck-sidecar command path

- docs/source/yelpsoa_configs.rst
- paasta_tools/long_running_service_tools.py
there are subtle differences in what this field means for k8s and
marathon.
> improve healthcheck_grace_period_seconds docs

- paasta_tools/contrib/check_orphans.py
k8s instances have their own IP address and always run on port 8888; we can't use the instance's IP to talk to the host's xinetd anymore to find its nerve registrations.
Instead, we use the `name` field from the nerve registration, which for PaaSTA instances is the hostname of the PaaSTA host which we can use to fetch the configured nerve registrations. This is the same as the `instance_id` in the nerve config.
After this change, the number of hosts which fail to fetch registrations drops from 1658 to 32 (all timeout errors). I spot-checked a bunch of those and confirmed that it is checking the right IP, but that those hosts aren't running xinetd because they are not PaaSTA hosts at all (just some other host type using nerve for service discovery).
Note that I had to introduce DNS …
> Fix check_orphans.py to handle k8s instances

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- requirements.txt
- script.py
- tests/cli/test_cmds_spark_run.py
- tests/test_spark_tools.py
This PR does the following:
- updates the version of boto3 and botocore to support when a credential_process is defined for a profile
- updates `get_aws_credentials` method and helper functions so that it no longer fails if a a profile configured with either a `credential_process` or a `aws_session_token`. For the former, the boto3 API returns the values as expected. In the case where a profile is configure with the session token inline, added support to handle loading and reading this key from a yaml file.
**Testing**
Automated testing
`make itest` passes
Added two new tests:
1. Check for `aws_session_token` when reading from a passed yaml file
2. Verify that we read the correct profile name when passing `profile_name` to `get_aws_credentials` rather than falling back to the default …
> Update Spark Run To Work with Session Token and Credential Process

- paasta_tools/cli/schemas/autotuned_defaults/kubernetes_schema.json
- paasta_tools/contrib/paasta_update_soa_memcpu.py
- paasta_tools/contrib/rightsizer_soaconfigs_update.py
This expects a splunk field named "suggested_hacheck_cpus", and uses
that to set the request and limit for the hacheck sidecar
This results in diffs like:
```
diff --git a/ad_admin/autotuned_defaults/kubernetes-norcal-stagef.yaml b/ad_admin/autotuned_defaults/kubernetes-norcal-stagef.yaml
index 3a27aa526e..020748b927 100644
--- a/ad_admin/autotuned_defaults/kubernetes-norcal-stagef.yaml
+++ b/ad_admin/autotuned_defaults/kubernetes-norcal-stagef.yaml
@@ -11,3 +11,9 @@ main:
cpus: 0.4
mem: 466
disk: 256
+  sidecar_resource_requirements:
+    hacheck:
+      requests:
+        cpu: 0.1
+      limits:
+        cpu: 0.1
(many, many more services here)
```
> Add hacheck sidecar cpu righsizing

- paasta_tools/cli/cmds/status.py
Trivial change for PAASTA-16917: the dark blue text is pretty difficult to read, cyan is easier.
Before:
After:
`make test` and `make acceptance` pass. Tested on Mesos and k8s services.
> Print instance name in lighter blue so it's easier to read

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
it looks like last time we modified the get_aws_credentials, we forget to update tron_tools. This changes fixed the issue. 
I've ensure: 
- make test pass
- `git grep get_aws_credentials` and ensured everything in the repo is expecting three output instead of two.
> Fix tron_tools to work with aws access token

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/envoy_tools.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/models/instance_status_kubernetes.py
- tests/api/test_instance.py
- tests/cli/test_cmds_status.py
- tests/instance/test_kubernetes.py
- tests/test_envoy_tools.py
```
$ PAASTA_SYSTEM_CONFIG_DIR=~/etc-paasta paasta status -s compute-infra-test-service -c XXXXXX -i main_k8s -vv
...
Envoy:
Service Name: compute-infra-test-service.main
Backends:
XXXXXX - Healthy - in BackendType.ENVOY with (2/2) total backends UP in this namespace.
Proxied through Casper: False
Hostname:Port              Weight  Status
XXXXXX:8888               10         HEALTHY
XXXXXX:8888               10         HEALTHY
```
> MESH-848 Add Envoy support on `paasta status` for k8s services

- paasta_tools/utils.py
Not entirely happy with this filter, but I can't find a better place to put this currently.
This covers an implementation-specific edge case for user access control. Displaying this in the public repository does not reveal terribly much (this isn't Yelp-specific; it's a standard described [here](https://support.microsoft.com/en-us/help/305144/how-to-use-useraccountcontrol-to-manipulate-user-account-properties)), but I don't like making this part of the hardcoded portion of the LDAP query, nor recommend open source users adopt this particular user access strategy for all LDAP services.
I'm open to suggestions on how to templatize this better (eg, making this part of the config, or providing a more generic template for the filter). In the meantime, this isn't especially urgent, and will …
> Filter disabled users via user account control flags

- paasta_tools/kubernetes_tools.py
Without this, missing data can cause the signalfx metrics adapter to request 0 instances
> Use `extrapolation="last_value"` for custom signalflow used by HPA

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
I didn't remove all the code, to leave open the possibility of adding this info back in once we understand what's going on and see if we can optimize the query. I'll add a ticket to the postmortem about making a decision on that.
> Stop fetching events in paasta status because it is slowing down etcd

- paasta_tools/kubernetes_tools.py
error from setup_kubernetes_job:
```
"message": "HorizontalPodAutoscaler.autoscaling \"ad--landscape-main\" is invalid: [spec.minReplicas: Invalid value: 0: must be greater than or equal to 1, spec.maxReplicas: Invalid value: 0: must be greater than 0, spec.metrics: Forbidden: must specify at least one Object or External metric to support scaling to zero replicas]",
```
I just changed this yesterday for no good reason, we can change it back.
> Do not return hpa if min or max is 0

- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/auth_decorator.py
- paasta_tools/api/client.py
- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/list_deploy_queue.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/monitoring/check_capacity.py
- remove pkg_resources for version lookup because we have version constant in paasta_tools module
- add error type objects to oapi and swagger api clients
- remove explicit imports of bravado for error types
> Unify error interface between bravado and oapi clients

- paasta_tools/apply_external_resources.py
- requirements-dev-minimal.txt
- requirements-dev.txt
- tests/test_apply_external_resources.py
The goal here is to replace the cron'ed `kubectl apply` in puppet with something a little bit more intelligent.  This script creates a `.applied` directory inside `/etc/kubernetes/puppet_resources`, which tracks what's previously been applied to the cluster.  New files or changed files will get re-applied.  Things that have previously been deleted will thus exist in `.applied` but not in `puppet_resources`, and the script will run `kubectl delete` on such objects.
The script will only run on the kubernetes leader, and will rsync the `.applied` folder to the other masters.
All the operations in here are idempotent (e.g., if `kubectl apply` runs a second time, then it just won't make any changes), so this should be robust in case something goes wrong.  If the script _does_ find some errors …
> script to track and auto-apply Puppet-created kubernetes resources

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- yelp_package/Makefile
If a `prometheus_shard` option is specified in the yelpsoa-config file, set `yelp.com/paasta_prometheus_shard` and `paasta.yelp.com/config_prometheus_shard` labels to the provided shard.
This label will be used by the Prometheus Service Monitor for the given shard to discover and scrape the service.
Snippet from `sudo setup_kubernetes_job -v compute-infra-test-service.main_k8s`:
```bash
DEBUG:paasta_tools.kubernetes_tools:Complete configuration for instance is: {'api_version': 'apps/v1',
'kind': 'Deployment',
'metadata': {'annotations': None,
'cluster_name': None,
'creation_timestamp': None,
'deletion_grace_period_seconds': None,
'deletion_timestamp': None,
'finalizers': None,
'generate_name': None,
'generation': None,
'initializers': None,
'labels': {'paasta.yelp.com/config_sha': …
```
> Add label to Kubernetes services if supplied in yelpsoa-config

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
I'm tired of the pod table in `paasta status -v` being impossible to read because the rows for each pod are separated by a bunch of lines of pod events.
Isn't https://fluffy.yelpcorp.com/i/HPM4HsRzsx6mz5LBSvmfcM1bHlPJk0nx.png much nicer than https://fluffy.yelpcorp.com/i/jlvVnQqhjB3rfxwdZd8SxLFNcrtN6WDW.png?
> Only show kubernetes pod events with multiple -v's

- yelp_package/extra_requirements_yelp.txt
Scribereader >0.9.0 has support for corp clusters so we need to bump to at least that version to fix `paasta logs`, which is currently broken in our corp clusters. I'm bumping it to 0.10.0, which is the latest available version.
manually tested `paasta logs -n 1000` on a service and got the logs successfully
`make test`
`make yelpy` - made sure all yelpy packages installed with no dep issues
> Bump scribreader to 0.10.0 from 0.8.0

- paasta_tools/kubernetes_tools.py
- yelp_package/Makefile
This branch adds the `prometheus_shard` label to the Deployment's PodTemplateSpec so that Pods created as part of the Deployment also have the label.
It also moves the `prometheus_path` label to a Pod annotation. This is because the prometheus_path can be any valid URL path string (e.g. `/my_test/path`) which can include characters which are not valid for Kubernetes labels
```
a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character
```
As the prometheus_path is only required by Prometheus once the pod has already been discovered, it does not require indexing by Kubernetes and therefore does not need to be a Label.
> Add prometheus_shard and prometheus_path to Pod spec

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
Add `secret_volume` option into yelpsoa, which allows to mount an                                                      
existing secret as a file into an instance.                                                                            
Example:                                                                                                               
```                                                                                                                    
main:                                                                                                                  
secret_volumes:                                                                                                      
- container_path: /home/nobody/.ssh …
```
> Support PaaSTA secrets as files

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/paastaapi/model/instance_status_kubernetes.py
- paasta_tools/paastaapi/model/instance_status_marathon.py
- tests/api/test_instance.py
- tests/test_kubernetes_tools.py
PAASTA-17026
We've got a race condition currently with wait-for-deployment, which leads to it thinking deployments are done before they've really started.
If wait-for-deployment polls for status after the `yelpsoa-configs` cron updates deployments.json, but before the `setup_kubernetes_job` runs, and the old version is fully deployed, then:
- the app_count check on line 1247 will pass. (There's exactly one app -- the old app).
- the git_sha check on line 1260 will pass (since that only checks deployments.json)
- the deploy_status check on line 1272-1275 will pass (since the old version is still Running)
- the required_instance_count check on line 1297 will pass (since the old version is fully deployed).
This patch adds a new `active_shas` property to the status response, and checks this …
> make wait-for-deployment check the actually-running git SHAs, not just what's in deployments.json

- paasta_tools/contrib/get_running_task_allocation.py
- tests/test_kubernetes_tools.py
Add pod_name and pod_ip to tmp_paasta_allocation to create a direct mapping between service / instance and pod name / ip
[Example get_running_task_allocation output](https://fluffy.yelpcorp.com/i/QjhwT9X7W7MR8zntcx9QsPDP99HSzkmK.html)
> Add pod_name and pod_ip to tmp_paasta_allocation

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
- fixed the issue that triggers `spark.master` key not exist error when use with `--mrjob` 
The original spark job called `create_spark_conf_str` twice, and unfortunately the create_spark_conf_str will drop the `spark.master`if `--mrjob` is set.  Therefore the second time we called the function will raise the error. 
The fix updates:
1.  create_spark_conf_str is called only once
2. also update create_spark_conf_str doesn't modify the passing argument spark_conf dict to ensure the stability. 
- make test pass
- manually run with with `paasta spark-run --mrjob` works on ads devc batch` also works!
> fix spark-run with mrjob

- paasta_tools/cli/cmds/mark_for_deployment.py
For k8s instances, the `if status.marathon` line would raise ApiAttributeError so we'd never hit the `elif status.kubernetes` line -- this causes wait-for-deployment to think that this instance is neither marathon nor kubernetes, so it doesn't bother waiting for it.
> Two separate try/excepts for two separate attribute lookups

- debian/changelog
- docs/source/generated/paasta_tools.contrib.add_to_deploy_queue.rst
- docs/source/generated/paasta_tools.contrib.bounce_log_latency_parser.rst
- docs/source/generated/paasta_tools.contrib.check_orphans.rst
- docs/source/generated/paasta_tools.contrib.create_dynamodb_table.rst
- docs/source/generated/paasta_tools.contrib.delete_old_marathon_deployments.rst
- docs/source/generated/paasta_tools.contrib.emit_allocated_cpu_metrics.rst
- docs/source/generated/paasta_tools.contrib.get_running_task_allocation.rst
- docs/source/generated/paasta_tools.contrib.graceful_container_drain.rst
- docs/source/generated/paasta_tools.contrib.is_pod_healthy_in_proxy.rst
- docs/source/generated/paasta_tools.contrib.is_pod_healthy_in_smartstack.rst
- docs/source/generated/paasta_tools.contrib.kill_bad_containers.rst
- docs/source/generated/paasta_tools.contrib.mock_patch_checker.rst
- docs/source/generated/paasta_tools.contrib.paasta_get_num_deployments.rst
- docs/source/generated/paasta_tools.contrib.paasta_update_soa_memcpu.rst
- docs/source/generated/paasta_tools.contrib.rightsizer_soaconfigs_update.rst
- docs/source/generated/paasta_tools.contrib.rst
- docs/source/generated/paasta_tools.contrib.shared_ip_check.rst
- docs/source/generated/paasta_tools.contrib.utilization_check.rst
- docs/source/generated/paasta_tools.rst
- paasta_tools/__init__.py
- paasta_tools/api/client.py
- paasta_tools/contrib/get_running_task_allocation.py
- tests/test_kubernetes_tools.py
- yelp_package/Makefile
Add host_ip to get_running_task_allocation script output to simplify mapping of a running pod to a host.
Change in api/client.py is caused by an automated import reordering.
> Add host_ip to get_running_task_allocation output

- tox.ini
Newer versions of cryptography python package do not support
openssl 1.0.2 and fail tests. This change pins cryptography version to 2.8.
> Pin cryptography version to 2.8

- paasta_tools/check_services_replication_tools.py
- tests/test_check_service_replication_tools.py
This should make the alert less noisy in small clusters.
> Add minimum count of under-replicated instances to the cluster alert

- paasta_tools/contrib/check_orphans.py
This is noisy and obscuring the real message in the page. This warns
almost every time because some hosts are firewalled off and we can't get
the file so setting to debug log only so we can read the output more
clearly.
> Only log connection failures to debug

- paasta_tools/kubernetes_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/test_kubernetes_tools.py
The `behavior` field for HPA, which allows you to specify limits on scaling down, is in the v2beta2 API. This PR just updates the current code to use that API. I'll follow up with a separate PR to add the limits.
Here are the API docs I used: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#horizontalpodautoscaler-v2beta2-autoscaling
I think I've tested this for all the possible HPA branches with setup_kubernetes_job on kubestage, which means the objects are valid, but it would still be good to check that the new API requests seem equivalent to the old ones. Here are the autoscaling sections I tested:
```
autoscaling:
decision_policy: proportional
metrics_provider: http
setpoint: 0.4
autoscaling:
decision_policy: proportional
metrics_provider: http
setpoint: 0.4 …
```
> Update to v2beta2 API for HPA

- paasta_tools/kubernetes_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/test_kubernetes_tools.py
Yelp/paasta#2970 seems to be causing issues with setup_kubernetes_job by making it fail for a bit whenever a new HPA for a service needs to be created, though it does eventually succeed those services (then it fails for another service :P). This in turn blocks service deployments. So, this PR just reverts the change. We'll revisit it again later.
> Revert Yelp/paasta#2970

- paasta_tools/kubernetes_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- tests/metrics/test_metastatus_lib.py
Currently in prod, metastatus is timing out when requesting any resources with groupings (aka when verbosity>1)
This adds 2 improvements:
1. Cache any requests to ~~`kuberetes.client.get_all_nodes`~~ `kubernetes_tools.get_all_nodes` or ~~`kubernetes.client.get_all_pods`~~ `kubernetes_tools.get_all_pods`
2. Reduce `# pods` API requests to a single `get_all_pods` API request and filter in memory instead. 
- With the original code, each `get_pods_by_node` query took 1-2 seconds themselves, and there are over 599 nodes in pnw-prod. This went well over the 120 timeout for the api.
With this change, running `paasta_metastatus -vvv` returns in 1m35s, where previously it was taking >30m (I never was able to get it to finish).  As a result, running the API, it was able to return successfully even …
> Improve metastatus performance by pulling all pods at once & caching

- paasta_tools/kubernetes_tools.py
If desired_instances or current_replicas is null, the final metric will be null instead of 0. I think that would result in FailedGetExternalMetric errors instead of scaling to min for the HPA.
https://app.signalfx.com/#/temp/chart/EmkLzKRAYAA shows the result for internalapi during the DAR yesterday.
> Use above() in HPA signalflow so we do not replace null with 0

- paasta_tools/instance/hpa_metrics_parser.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/instance/test_hpa_metrics_parser.py
- tests/test_kubernetes_tools.py
There were a couple issues with https://github.com/Yelp/paasta/pull/2968:
* creating an HPA raised an error: `ValueError: Invalid value for `conditions`, must not be `None` (my tests didn't catch this because this only occurs when creating a new HPA, not updating an existing one)
* paasta status was erroring because it still expected v2beta1 objects (fix copied from https://github.com/Yelp/paasta/pull/2970)
> Update to v2beta2 API for HPA, try #2

- paasta_tools/cli/cmds/status.py
As opposed to assuming that all jobs will have name like `{service_name}.{instance}.{job_name}` and getting 2nd element after splitting. Use -1 to get the last element so that the function works for cases where job names are defined without service and instance names.
> Use -1 to get the last element of list

- paasta_tools/secret_providers/vault.py
- tests/secret_providers/test_vault.py
We can occasionally get some vault jsonsecret data with only a subset of 'valid' ecosystems listed in the `environments` data.
When a new service that has an old jsonsecret file like this is deployed to a kubernetes cluster, even if the instance to be scheduled in the new ecosystem does not actually depend on this particular jsonsecret file, `paasta_secrets_sync` will not only fail to sync this broken secret, but all following secrets and services.
Instead, I think we should treat missing ecosystems in `environments` as we do an ecosystem without encrypted data.  This way `paasta_secrets_sync` will continue on to other, correctly-generated secrets, and if the service owner really does need to fix that data they will be able to see that there is an issue with the instance not deployed due …
> PAASTA-17145: handle a missing ecosystem in vault data gracefully

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
This change makes `paasta_tools` read the set of supported storage classes from `system_paasta_config` rather than relying on hard-coded values. We can then manage these configs in Puppet which will be useful for allowing users to experiment with new StorageClasses (e.g. ones with the new `gp3` volume type).
`make test` passes
`patch` release
> Read supported storage classes from system_paasta_config

- paasta_tools/cli/cmds/secret.py
- paasta_tools/secret_providers/__init__.py
- paasta_tools/secret_providers/vault.py
- tests/cli/test_cmds_secret.py
- tests/secret_providers/test_vault.py
- yelp_package/extra_requirements_yelp.txt
This change allows to add a metadata string when creating or updating a secret which is meant to have the same value across multiple environments. This is done to allow developers to provide context about why a secret has been duplicated instead of following the best practice of using different secret value in different runtime environments. This ultimately allows to create catalogue of secrets which are meant to be replicated and detect when new duplicated secrets are added not following the convention.
The additional parameter has been implemented in the latest version of `vault-tools` (0.9.2). I recognise this is a pretty large bump for the dependency, so I'd ask reviewers to look at the library changelog for potentially breaking changes introduced in the meantime (cause I don't have …
> allow tagging secret as shared across environments

- paasta_tools/secret_providers/vault.py
- tests/secret_providers/test_vault.py
In https://github.com/Yelp/paasta/pull/2983 I broke the Vault secret provider by bumping the version of `vault-tools` because in the latest versions the `do_renew` function of the `cert_tools` module has been renamed to `do_cert_renew`. The function signature has remained the same so no other adjustment should be required.
> fix vault secret provider (s/do_renew/do_cert_renew)

- paasta_tools/secret_providers/vault.py
- tests/secret_providers/test_vault.py
I'm sorry I had to burn through 3 released just to make this work, but this should be the final one.
This parameter makes `vault-tools` not swallow exceptions in the decryption process (which was the behaviour previous to the version bump in https://github.com/Yelp/paasta/pull/2983).
> set rescue_failures parameter in Vault provider decryption

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
I cherry-picked the commit from https://github.com/Yelp/paasta/pull/2987 and just changed the metric back to status quo, kube_hpa_status_current_replicas. That means this shouldn't change anything except make it possible to change though system paasta configs.
I'm doing this to make it easier to experiment on the Signalflow in general - we have a few tickets related to that to make HPA more stable, including PAASTA-17143.
> Add signalflow for hpa to system paasta configs

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- tests/kubernetes/application/test_controller_wrapper.py
- tests/test_kubernetes_tools.py
This is a first attempt at support HPA scaling policies that were newly introduced in Kubernetes v1.18 in PaaSTA to control how quickly we scale down. Couple of things to note:
- I've had to monkey-patch the scaling policies configs into the JSON data the k8s client posts to get this to work, because the k8s client library only supports v1.17. 
- I've only created (what I think is) a sensible default so far, but the next step will be to make the defaults configurable in system paasta configs or on a per-instance basis from soa-configs.
- The sensible default is to at most per minute scale down by either 30% of current replicas or 5% of max replicas, whichever is highest. Essentially, this means we only scale down at most by 30% of max replicas, and the rate of scale down plateaus to 5% of …
> Monkey-patch default HPA scaling policy into HPA spec

- tests/test_kubernetes_tools.py
My previous PR #2984 adding scaling policies for HPA broke `make test` because the `LEGACY_AUTOSCALING_SIGNALFLOW` was removed before I merged my previous PR; however, I didn't catch it because there was no merge conflict. This PR fixes the test.
`make test`
> Fix hpa test since legacy signalfow was removed

- paasta_tools/utils.py
I'm replacing the metric **kube_hpa_status_current_replicas** with **kube_deployment_spec_replicas** on the signalflow code for the uwsgi HPA.
For details on this new metric please check PAASTA-17119.
I'm also moving the signalflow code to a paasta config variable, so that we can override it if needed.
- Installed a paasta_tools version to kubestage and confirmed that the signalflow code was updated on different HPA objects.
- This change didn't bounce any pod as the signalflow code lives on HPA objects (as an annotation).
> PAASTA-17119 Replace kube_hpa_status_current_replicas uwsgi hpa metric

- paasta_tools/setup_kubernetes_job.py
- tests/test_setup_kubernetes_job.py
This change adds a `--rate-limit` param to `setup_kubernetes_job` so that we can control how many updates are sent to the k8s API on every cronjob run.
The intention is to limit the damage that big bounces cause on our biggest clusters.
- Manually executed `setup_kubernetes_job` while removing some of the existing deployments on kubestage.
> PAASTA-17176 Add rate limit param for s_k_j

- paasta_tools/kubernetes_tools.py
deploy_group and docker_image are existing dimensions that we can't use
relabeling to include in metric scraping since they're only present in
the k8s container spec and Prometheus doesn't expose that.
most importantly, scrape_uwsgi_prometheus will be how we filter down the
set of pods that Prometheus should actually scrape - the idea is
currently that this label is only set when someone has opted into using
the uwsgi exporter, but in the future this label should be set if a
service has chosen to use uwsgi autoscaling instead of checking this
feature toggle
> Add additional labels for Prometheus use

- paasta_tools/kubernetes_tools.py
This is too long (over 63 chars) so we'll need to figure out another way
to get that information in prometheus (or just skip it if no one ever
uses it)
> Remove docker_image label

- paasta_tools/cli/cmds/logs.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_logs.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
When running `paasta logs` with an invalid instance, you will be met with an error and possible suggestions to the instance name entered.
- `make test - PASSED`
> Paasta 16369 validate instance name paasta logs

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Prometheus shards (currently deployed outside of PaaSTA) that need to
scrape metrics from a service need to be able to contact that service.
The only way to do so currently is to add a port in Smartstack in order
to make the pod ip routable (via the `paasta.yelp.com/routable_ip`
label). That port is unused and just serves to enable this behaviour.
While reserving unused ports in Smartstack is not too big a deal,
Smartstack/PaaSTA will launch a hacheck sidecar container which will run
extra healthchecks and use extra resources.
For Kubernetes operator pods, only one pod per deployment (the leader)
will have a Prometheus endpoint running (and able to accept
healthchecks). The other pods are therefore incorrectly considered
unhealthy, while they are just waiting for the lock to become …
> Make pods with a prometheus_port routable

- paasta_tools/cli/schemas/autotuned_defaults/kubernetes_schema.json
- paasta_tools/cli/schemas/autotuned_defaults/marathon_schema.json
- paasta_tools/contrib/paasta_update_soa_memcpu.py
- paasta_tools/contrib/rightsizer_soaconfigs_update.py
This makes `cpu_burst_add` a valid key in AutoConfigUpdater and fetches it from the Splunk CSV, but doesn't actually write cpu_burst_add in the rightsizer batch. This should be a no-op in terms of the configs updated in the daily cpu job.
Since we're adding suggested_cpu_burst_add to the existing cpu CSV, the `--csv-key` option will allow us to roll out the burst changes more slowly. My plan:
1. Release this change
2. Add `--csv-key cpus` to the existing Jenkins job for the cpu CSV.
3. Add cpu_burst_add to the rightsizer batch in a follow-up PR.
4. Add a new job with `--csv-key cpu_burst_add` that can be selectively applied to different clusters via the criteria filter (`-f`).
5. Once we're happy with the burst changes, we can eventually merge the two jobs back together.
I've tested the …
> Add support for auto-configuring cpu_burst_add (PAASTA-17172)

- paasta_tools/contrib/get_running_task_allocation.py
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
This fixes an assumption that pods use just a node selector. Some of the
cassandra Pods use node affinity and in practice a lot of things can
impact the node/pool that a Pod actually ends up on. This checks the Pod
to see what node it is scheduled on and gets the pool from the Nodes
labels (which I think is more reliable).
Note I tested this on kubestage but I don't know the impact if this
breaks something so please warn me if I need to be careful.
> Make get_kubernetes_metadata use actual node pool

- docs/source/soa_configs.rst
- docs/source/yelpsoa_configs.rst
This is strictly a doc update -- `routable_ip` is working as intended so we can document it.   I also noticed the `prometheus_(shard|path|port)` sections were indented incorrectly; these have been fixed.
In addition, show other examples of yelpsoa files in our top level `soa-configs` documentation, to make it clear files don't _need_ to be only `marathon-$cluster.yaml`
`make docs` succeeds and generates the expected changes.
`soa_configs.html` Before: ![Screen Shot 2021-01-26 at 5 43 47 PM](https://user-images.githubusercontent.com/2119545/105930650-cb2d2f00-5ffe-11eb-94d9-4bd603c5abee.png)
`soa_configs.html` after: 
`yelpsoa_configs.html` `kubernetes-clustename-yaml` before: 
`yelpsoa_configs.html` `kubernetes-clustername-haml` after:
> PAASTA-16376: document routable_ip option on k8s

- paasta_tools/instance/hpa_metrics_parser.py
- tests/instance/test_hpa_metrics_parser.py
We'll be using Object metrics to support Prometheus-backed HPAs, so lets
set some groundwork and make sure that we can parse said HPAs once we've
actually created some.
> Add support for parsing HPAs with Object metrics

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
This will cause issues once we add additional metrics to the HPA since
the SFX adapter will try to act on those metrics and, predictably, fail.
**NOTE: this is using https://github.com/Yelp/paasta/pull/3023 as a base to make it easier to break things up into multiple PRs - my plan is to merge the base PR and then merge this into master**
> Stop adding SFX custom metrics annotation

- paasta_tools/kubernetes_tools.py
We want to use both the SFX and Prometheus adapters for now, so we'll
add two different metric specs to our HPAs so that both of the adapters
are used concurrently (and, if there are issues with one we don't
completely kill all autoscaling)
**NOTE: this is using #3024 as a base to make it easier to break things up into multiple PRs - my plan is to merge the base PR and then merge this into master**
> Add Prometheus-backed metrics to HPAs (if configured)

- paasta_tools/setup_prometheus_adapter_config.py
- tests/test_setup_prometheus_adapter_config.py
- tox.ini
It's probably easiest to review this commit by commit.
output from `python -m paasta_tools.setup_prometheus_adapter_config -c kubestage --dry-run --verbose`: https://fluffy.yelpcorp.com/i/Zp9G7XK51LtsZ8jrJZQ56bc1SQqZ10pP.html
**NOTE: this is using #3026 as a base to make it easier to break things up into multiple PRs - my plan is to merge the base PR and then merge this into master**
> Implement setup_prometheus_adapter_config.py stubs

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
- requirements.txt
- tests/cli/test_cmds_spark_run.py
When creating a spark session, we need to also pass in the AWS_SESSION_TOKEN in order to be able to properly use the AWS creds. This PR adds the session token to the environment, and updates corresponding tests to expect this value.
Bumps the version of `service-configuration-lib` to `v2.5.3` wich has the updates in https://github.com/Yelp/service_configuration_lib/pull/60 lands which is needed to automatically use the temp aws provider.
**Testing**
Federate cred testing all done using a spark3/hadoop3 built image via https://github.yelpcorp.com/services/spark/pull/10/files
_pyspark w/ Federated Creds on Hadoop 3 image_
```
(py36-linux) srojas@dev2-uswest2adevc:~/paasta(u/srojas/SEC-13906-pass-session-token-to-spark-env○) » paasta spark-run -C pyspark --image docker-dev.ye …
```
> Pass AWS_SESSION_TOKEN During Spark Environment Creation

- debian/changelog
- paasta_tools/__init__.py
- yelp_package/Makefile
Version tag + bump via `make release`. Turns out bumping the version in `yelp_package/Makefile` and running `make release` was easy enough to follow
> Released 0.97.64 via make release

- paasta_tools/setup_prometheus_adapter_config.py
This is a fail-safe to stop us from deleting all rules, but this is
currently tripping up our alerting on clusters that don't have
Prometheus-enabled HPAs
> Stop returning non-zero when no rules are generated

- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- tests/cli/test_cmds_status.py
- tests/instance/test_kubernetes.py
Modified the API request to retrieve the replicaset data without having to use the verbose option when running `paasta status`.
**Verbose Option Deactivated**
**Verbose Option Activated**
> Shows replicaset table in nonverbose request

- paasta_tools/setup_prometheus_adapter_config.py
kube-state-metrics seems to occasionally get overloaded and we miss a
scrape every now and then - this leads to us dividing by NaN which is
then interpreted as 0 by either the HPA or the Prometheus adapter.
This is undesirable since it'll potentially cause us to scale down
unexpectedly, so we "fix" it by grabbing the highest value seen in the
last ~10 scrapes whenever we encounter a NaN.
Additionally, we include the offset used to counteract the fact that our
previous metrics collector tied up a uWSGI worker in our new PromQL
so that we scale exactly the same.
> Handle missing metrics and include offset for Prometheus HPAs

- paasta_tools/cli/cmds/logs.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_logs.py
- tests/cli/test_utils.py
PAASTA-17231 validated instances with suffixes in a way where it only will validate the string before the suffix. This was a great fix for Flink instances for example.
`paasta logs -s stream_sql -i main.SUPERVISOR`
In this case, verify_instances will only validate `main`.
However, this fix excluded tron instance names which required the strings before and after the suffix to be validated. 
`paasta logs -s reminder -i compute-infrastructure-oncall-us.compute-infrastructure-oncall-us`
In this case, verify_instances will validate the entire string `compute-infrastructure-oncall-us.compute-infrastructure-oncall-us`.
This change allows for both instances with suffixes to be validated correctly.
`make test` - PASSED
> PAASTA-17261-Paasta-Logs-Support-Tron-Instance-Names

- yelp_package/extra_requirements_yelp.txt
new version is loading various logging dependencies lazily, which shaves some 600ms off loading time of various subcommands
```
before:
paasta list-clusters  1.06s user 0.14s system 98% cpu 1.219 total
after:
paasta list-clusters  0.45s user 0.14s system 97% cpu 0.607 total
```
> bump yelp-clog to 5.1.0

- paasta_tools/setup_prometheus_adapter_config.py
Previously we were just doing strict dictionary equality, but this
breaks down when your values are lists and those lists aren't in the
same order.
> Sort Prometheus rulesets for easier comparison

- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
- yelp_package/dockerfiles/hacheck-sidecar/Dockerfile
- yelp_package/dockerfiles/hacheck-sidecar/Makefile
Doing some housekeeping on the readiness check settings:
- pin paasta-tools on the hacheck sidecar image. The pinned version is the one that's currently installed on the latest hacheck image.
- hacheck Makefile now includes the latest commit SHA when tagging new images.
- remove the default for hacheck_sidecar_image_url as we rely on the value set on /etc/paasta. If /etc/paasta isn't setting any value, I'd rather have s_k_j failling than bouncing things with the wrong hacheck img.
- adjust the default value for envoy_readiness_check_script
This is a noop: envoy_readiness_check_script and hacheck_sidecar_image_url are managed through puppet at the moment.
> MESH-1070 Cleanup readiness check settings

- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- tests/test_kubernetes_tools.py
See PAASTA-17257
---
Because this is very Kubernetes-specific behavior, I've opted to try to expose the fields without modification (including leaving them camel cased).  I am also slightly worried that this is a bit brittle because we don't currently validate the autoscaling section of soa-configs, and it might be easy to get it wrong which could mess up setup_kubernetes_job...but I also don't expect this to be commonly-used behavior and we need it now so I kind of vote we just do it?
> Allow HPA scaledown policies to be overridden from soa configs

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We suggest people use `paasta local-run` for ad-hoc batch jobs, but currently there's no way to add arbitrary volume mounts. This means our best advice for users who want to pass an input file to a batch job is to make a yelpsoa-configs change with an `extra_volumes` entry, which is pretty clunky.
This change adds a `--volume` parameter. (Note that `-v` already exists and means verbose.)
> Add --volume parameter to local-run. PAASTA-1262, PAASTA-16089

- paasta_tools/cli/cmds/logs.py
- paasta_tools/setup_kubernetes_job.py
- paasta_tools/utils.py
I'm doing three things:
1. Make stdout/stderr the default components in paasta status. Most users only care about these components anyway, and it will mean the paasta logs by default will return faster, since we only need to look at app_output logs.
2. Remove Mesos/Marathon language from `paasta logs --help`, to avoid confusing users. The only exception is the `marathon` component, which I've listed as deprecated, since we're mainly on k8s anyway.
3. Organize the `paasta logs --help` text better so that more information is in the help text itself, from than the epilog. This should help users understand the components, and use the arg more.
Tested by running `paasta logs` in my env. 
what paasta logs looks like now: https://fluffy.yelpcorp.com/i/533mRdzpTDlqqS1Lh9Dj7sqljRXGdK1g.html
> Make stdout/stderr default in paasta logs, and improve its help text

- paasta_tools/autoscaling/forecasting.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/setup_prometheus_adapter_config.py
- tests/test_kubernetes_tools.py
- tests/test_setup_prometheus_adapter_config.py
This additionally allows us to use `cpu` as a metrics provider instead of continuing to propagate `mesos_cpu` when we're not using Mesos anymore.
NOTE: we'll still continue to use the built-in CPU scaling that k8s provides for safety.
> Implement CPU-based moving average window autoscaling

- paasta_tools/cli/cmds/local_run.py
I think this probably has been messed up since the transition to python3?
See PAASTA-17039
---
I tested that this works with a local-run.  The `end=""` is needed so that we don't add extra newlines since the stdout/err already has newlines (I figure this is slightly better than `.strip()`?)
> Don't print bytes objects when tailing local-run container stdout/stderr

- requirements.txt
Bumping the Paasta's version of Sticht to v1.1.13 to add fix to the Key Errors involving slo watchers.
`make test` - PASSED
> PAASTA-17227 - Bump Sticht Version to Resolve Key Errors

- paasta_tools/cli/fsm/template/{{cookiecutter.service}}/smartstack.yaml
Make the default smartstack.yaml for new services use discover: habitat and advertise: [habitat, region] so new services take advantage of az aware routing
> Use discover: habitat and advertise: [habitat, region] in fsm for smartstack

- paasta_tools/cli/schemas/autotuned_defaults/kubernetes_schema.json
- paasta_tools/cli/schemas/autotuned_defaults/marathon_schema.json
- paasta_tools/contrib/paasta_update_soa_memcpu.py
- paasta_tools/contrib/rightsizer_soaconfigs_update.py
- tests/test_config_utils.py
Just appending to already autotunable resources. At some point I would love to refactor this a bit and maybe delete old cruft in paasta_update_soa_memcpu.py but it's not really an emergency for now.
> Add support for min and max instances in autotuned_defaults

- Jenkinsfile
I want to start building focal packages for py-gitolite, but it depends on paasta-tools.
Debs are already built in github actions (https://github.com/Yelp/paasta/blob/master/.github/workflows/ci.yml#L42), so I just need to update the jenkins job to build + upload them.
`make itest_focal` succeeds
> Build and upload deb for focal

- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
Before we delete this, let's make a toggle for it and try it on a few instances.
> Gate signalfx HPA metrics behind a default-true toggle. PAASTA-17097

- paasta_tools/cli/cmds/status.py
This Commit set `include_smartstack` to `False` and thus removing haproxy section from the status command
> PAASTA-17311, removed haproxy section from the paasta status field

- paasta_tools/contrib/check_manual_oapi_changes.sh
This fixes our internal jenkins build which runs `tox -e general_itests`, which in turn runs `pre-commit run --all-files`.  general_itests were broken after removing pre-commit's global exclusion of all `paasta_tools/paastaapi` files in #3081. 
This changes the script to skip the file-based check since *all* files will be returned during `pre-commit run --all-files`, but still catches situations where `make openapi-codegen` generates a diff that has not yet been committed, which should be caught. 
Verified a commit with a manual modification to `paasta_tools/paastaapi/model/kubernetes_pod.py` fails the precommit:
```
check that oapi.yaml is updated if paastaapi changes.......................Failed
hookid: check-oapi-schema
paasta_tools/paastaapi must not be modified manually
Please revert …
```
> Do not run file-based oapi check during itests

- paasta_tools/smartstack_tools.py
- tests/test_smartstack_tools.py
Request replication information from all available sources and fail only
if all of them are unavailable.
> Don't fail if one of replication info source isn't available

- paasta_tools/check_flink_services_health.py
- paasta_tools/check_kubernetes_services_replication.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/check_oom_events.py
- paasta_tools/check_services_replication_tools.py
- paasta_tools/monitoring_tools.py
- tests/test_check_flink_services_health.py
- tests/test_check_kubernetes_services_replication.py
- tests/test_check_marathon_services_replication.py
- tests/test_check_service_replication_tools.py
- tests/test_monitoring_tools.py
This PR does a number of things:
- Adds `--dry-run` for the oom and replication event checker
- Updates the tip for the oom checker
- Moves a lot of context from the output to the description of replication alert events. This is because the output was so long that it would prevent the tip and runbook from showing up in Slack alerts (400 char limit). The description was also not well-used. 
- Changes the default replication alert runbook to y/paastatools for help debugging services (we should probably create a dedicated runbook or section for this)
`make test`
manual testing using `--dry-run` to see the sensu events
manual testing and seeing slack alert messages
> Shorten replication alert output, and add tip + runbook, and add OOM alert tip

- README.md
For now: just docs about how we use the HPA and how service deploys
work
> Add links to internal docs

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Adding `pod_management_policy` to StatefulSets spec to make it configurable, right now without this option we are using the default [OrderedReady](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#orderedready-pod-management) option, it would be helpful for monk to adopt the [Parallel](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management) policy when scaling up during an incident.
The config required in yelpsoa-config would be something like
```
pod_management_policy: Parallel
```
`make test` passed
I reckon rolling out this change should not lead to sts restart existing pods, as the default config is `OrderedReady` but please let me know if there is anything I have missed or if there is any other concern about this change.
> MONK-2327 Add pod management policy support to StatefuleSets

- paasta_tools/contrib/get_running_task_allocation.py
- tests/test_kubernetes_tools.py
In order to have a better precision of data for autoscaling we need to be able to distinguish between different versions of the service. This change fetches {{config_sha}} and {{git_sha}} Docker labels and adds them to the
allocation report.
[An example of the updated script output](https://fluffy.yelpcorp.com/i/1dn48x5kNn30NHG6xQR0tlD60QHH6Frl.html)
> Add release info to k8s task allocation

- paasta_tools/kubernetes_tools.py
Annotation values have to be strings. This patch has been tested on kube1-uswest1astagef:
```
paasta-tools:
Installed: 0.98.00-yelp2
Candidate: 0.98.00-yelp2
Version table:
*** 0.98.00-yelp2 100
100 /var/lib/dpkg/status
davent@kube1-uswest1astagef:~$ sudo setup_kubernetes_job statsite.main
INFO:__main__:Updating statsite-main-619eca5e0c3e96c5a12299eff0ce7ab2e087ea52-configa4a38a09 because configs have changed.
INFO:__main__:Ensuring related API objects for statsite-main-619eca5e0c3e96c5a12299eff0ce7ab2e087ea52-configa4a38a09 are in sync
INFO:root:poddisruptionbudget statsite-main up to date
INFO:paasta_tools.kubernetes.application.controller_wrappers:No HPA required for statsite-main/name in paasta
```
Result applied as expected:
```
metadata:
annotations:
iam.amazonaws.com/role: "" …
```
> Annotation values my be strings

- requirements.txt
5.4.0 in our internal pypi index was built without CLoader support. 5.4.1 has it (and we fixed this problem for future uploads of pyyaml, context at https://yelp.slack.com/archives/CDBRTGJF8/p1614211751114300). Having CLoader available should make all yaml parsing much faster.
I noticed this when I was running the .tools/generate-historical-infrastructure-stats.py script in yelpsoa-configs, which uses the paasta venv and assumes that CSafeLoader is available.
> Update pyyaml to 5.4.1 for CLoader support internally

- docs/source/yelpsoa_configs.rst
The default value seems to be as 10mins in the source code (https://github.com/Yelp/paasta/blob/master/paasta_tools/check_kubernetes_services_replication.py#L49)
> Fixing the documentation for the alert_after value

- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_validate.py
Let's ensure that people don't try to set a (setpoint, offset)
pair that is invalid.
NOTE: I've deleted the existing autoscaling validation code as it was
only checking for an autoscaling configuration that we moved away from
(`horizontal_autoscaling`) - see #2582 for the initial implementation of
this and #2979 for its removal.
> Add autoscaling configuration validation

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
nerve-tools uses paasta as a dependency, so without doing this we can't
use any new paasta features there.
we only stopped uploading sdists with the migration to GHA since we
wanted to focus on getting public CI back up and public PyPI uploads
could wait a bit.
lastly, I've also added back wheel uploads since it seems like we had
stopped doing that for a while in travis (and i'm assuming that wasn't
on purpose).
> Configure GHA to upload an sdist+wheel to public pypi

- paasta_tools/utils.py
- tests/test_marathon_tools.py
- tests/test_utils.py
For the benefit of mypy in yelpsoa-configs templating.
> Define proper type for monitoring key in InstanceConfigDict.

- paasta_tools/setup_kubernetes_job.py
- tests/test_setup_kubernetes_job.py
If one instance is misconfigured and hits an exception, it will cause the entire run to fail and will not progress to the other service instances that have yet to be setup.
> PAASTA-17337 - capturing instance misconfiguration exceptions for setup_kubernetes_job

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
Since rolling this out in one go will bounce all services, we need to roll it out carefully and slowly.
> Add registration labels to pods

- paasta_tools/contrib/get_running_task_allocation.py
- tests/contrib/test_get_running_task_allocation.py
Currently, cpu recommendations are not super accurate because we don't know how much CPU a task can really use before getting throttled ([cpus + cpu_burst_add](https://github.com/Yelp/paasta/blob/master/paasta_tools/kubernetes_tools.py#L987) AKA cpus limit in k8s). We currently only keep track of the requested cpus.
We could get that info out of band in the hourly report we are using for autotuned_defaults by parsing the configuration directly but we would lose time accuracy. I am OK to do that if you have strong opinion against this change.
This PR adds cpus_limit to the allocation log which will enable us to track this accurately and ultimately make better recommendations.
I know this file is in contrib but I felt like it deserved some unit tests, so I added a test directory and one …
> Add cpus_limit to paasta allocation

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
According to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/, labels can only have one /. I'm using registrations.paasta instead of something like paasta.yelp.com/registrations_service_name because there's also a maximum of 63 characters allowed to the label's name section, which is whatever follows the slash, so using a subdomain seems to be a wiser solution.
Also tested this manually by running it on kubestage's k8s CM leader
> Change the label keys for registrations

- paasta_tools/contrib/deploy_group_update.py
This PR utilizes changes made in https://github.com/Yelp/paasta/pull/3141 to automatically mutate and push to configs. Given CLI arguments, this script will check if the service `args.service` has deploy group `args.deploy_group`, and if not, will modify `args.kube_file` and `deploy.yaml`, and insert data to create a new deploy group `args.deploy_group_prefix.deploy_group` with instance count `args.instance_count`. `args.non_relevant_steps` is provided to ignore miscellaneous deploy steps.
> adds script to automatically add deploy groups

- paasta_tools/contrib/deploy_group_update.py
This script has two minor bugs:
1.  The script does not exit upon hitting the error condition (`deploy_groups` and `pipeline_steps` being out of sync)
2. Does not properly check against existence in `deploy_groups` (`deploy_groups` is keyed on `prefix.group_name`, and prior, we only checked if `group_name` exists in `deploy_groups`, which would never be True)
> Fix deploy_group_update script bugs

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This change adds support for updating/adding the `default_volumes` key into MASTER config, using the paasta system-level default volumes (i.e. /etc/paasta/volumes.json).
A manual dry-run of `setup_tron_namespace` shows it would generate the expected config: https://fluffy.yelpcorp.com/i/zqDppdXcs5zTqjzXBxX3Lv2DdBg3t7Pd.html
Note that this currently only _updates_ the `k8s_options` key if it already exists in MASTER config (i.e. we've already specified it manually in yelpsoa-configs ourselves), to allow us to gate this only to tron servers that have already been updated with k8s support.
> TRON-1625: Support adding paasta default_volumes to tron master k8s config

- .github/workflows/pypi.yml
https://github.com/Yelp/paasta/pull/3138/files made our default docker registry our internal yelpcorp.com one, but for github actions we need to override back to DockerHub.
This just adds the empty `DOCKER_REGISTRY`  envvar to both jobs in the `pypi` workflow, just as we configured in the `ci` workflow in #3138.
> Fix GHA pypi workflow's DOCKER_REGISTRY

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
- tests/test_kubernetes_tools.py
This updates the paasta secret sync to optionally sync yelpsoa-config specified secrets into a namespace different than `paasta`, but leaves the default as `paasta`.
In addition to creating the resources in the new namespace, the naming convention changes from `paasta-` prefixed to `{namespace}-` prefixed.
I have added tests to verify leaving namespace unspecified results in reading from/writing to the `paasta` namespace.
Manual test runs against kubestage also work as expected:
```
$  KUBECONFIG=./etc_paasta_for_development/admin.conf PAASTA_SYSTEM_CONFIG_DIR=./etc_paasta_for_development/ python paasta_tools/kubernetes/bin/paasta_secrets_sync.py -n tron compute-infra-test-service -v
INFO:__main__:new-test-secret for compute-infra-test-service not found, creating
$ …
```
> Update paasta secret sync to support other namespaces

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
Currently, we warn users when their deployment has reached 75% of the mfd timeout. This 75% is hardcoded, which isn't great. So, I've added an option to mfd to make the warn percentage configurable.
I've also lowered the default pct to 50% to leave more time for stuck bounce debugging. At 75% with a default 1hr/3600s timeout, we only get 15m of debugging time, which means by the time we've taken action, the deploy has already timed out, forcing users to restart Jenkins. 50% or 30m is better. If we find that some services naturally deploy slower, we can raise the warn pct for their mfd since it is now configurable.
`make test` passes
manual test on `compute-infra-test-service` works. i ran the following command, and got a warning at 15s, after which it timed out at 30s, as expected:
``` …
```
> Make wait-for-deployment warn pct time configurable

- paasta_tools/cli/cmds/status.py
- paasta_tools/utils.py
- tests/cli/test_cmds_status.py
After having a new and more helpful paasta status, it's hidden behind an obscure flag. This PR adds support for `paasta status --old` and for setting the `paasta_status_version` in `etc/paasta`
Note:  `paasta_status_version` needs to be set in `etc/paasta` to make the --new version the default one
> PAASTA-17414 make paasta status --new the default

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/setup_tron_namespace.py
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We're handling the toggles in PaaSTA rather than Tron since the
cluster-level config isn't easily available when setting up an
ActionRun, so we will instead use setup_tron_namespace to configure Tron
to use either Mesos or Kubernetes.
Additionally, we'll need to add some translation layers for things like
Mesos constraints/Docker parameters, so we might as well centralize that
here rather than setup Mesos here and Kubernetes in Tron.
The general idea here is that we want our config sync to handle toggling the 
use of k8s - disabling k8s for an entire cluster will lead to this sync setting
`use_k8s` to false for all jobs and therefore set the executor back to `mesos`
for everything
> Scaffold out the k8s toggles for tronjobs

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
*Note*: This branch is based off of #3121 and will not be merged until that PR has been merged to master. 
We now need to create a separate `secret_env` key in generated tronfig for paasta secrets in tron k8s jobs so we can correctly pull from k8s Secret resources created by our `paasta_secrets_sync` job.
This change will do the generation of the `secrets_env` key only if k8s is enabled at both the cluster and job level.
tests pass cleanly, and a manual run against a test job (`compute-infra-test-service.test_frequent`) with `use_k8s: true` and  a `MASTER` config with `k8s_options` with `enabled: true` generates the expected tronfig: https://fluffy.yelpcorp.com/i/xl2mlTChtNJk37TMqGCkpxlpNwDdDlLP.html#L162-187
(Note the new `secret_env` section and the lack of a `TEST_SECRET` key in the …
> TRON-1738: Setup k8s env secrets in setup_tron_namespace

- paasta_tools/contrib/service_shard_update.py
This PR reworks the previously added `deploy_group_update` script to be a bit smarter and require less information from the caller side. Now, the caller does not need to understand deploy groups/ecosystems/etc, and can just call this script with a shard name alone.
When this script is called, it now performs the following operations:
1.  If `args.shard_name` is missing from the deploy config, it adds all missing groups (usually for dev, stage, prod)
2. Goes through all kubernetes cluster config files and checks if `args.shard_name` exists in each, if not, add it
3. If `args.shard_name` does not exist in the `args.service` smartstack file, add it
> rework service sharding script

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We don't want to turn this on for existing Mesos tronjobs since the logs
won't be used in that case.
We'll be using logspout to ship tronjob logs to our logging streams and
then displaying those in Tron rather than doing what we did with
Tron-on-Mesos and asking Mesos (or, in this case, K8s) to feed us logs
periodically.
> Add logspout feature flag to all tron on k8s containers

- requirements-minimal.txt
It's used in paasta_tools/utils.py, so we should declare it in the minimal requirements.
ldap3 is probably a transitive dependency of something else right now, since it's in the `requirements.txt` file, but anything that installs Paasta as a package wouldn't know that it needs `ldap3` too.
> Add ldap3 to requirements-minimal.txt

- paasta_tools/cli/cmds/spark_run.py
When `--image` option is provided with spark-run for testing the local changes in the prod environment, it always get stuck in `Initial Job has not accepted any resources'
Failing test case: https://fluffy.yelpcorp.com/i/1VWddpH6C1RhFndkn1F1Wk90x6vLDvTc.html
Passing test case: https://fluffy.yelpcorp.com/i/0K0GzS9X1GqwV3zTLlHLlDQfGxlGN7WD.html
It looks like we need to set the spark.mesos.uris with the docker configuration path over here: https://sourcegraph.yelpcorp.com/Yelp/service_configuration_lib@93583d28aa04153fbe9551bc1980fe5214551ac0/-/blob/service_configuration_lib/spark_config.py#L398:31
even if image is passed as an argument.
Discussion thread: https://yelp.slack.com/archives/CA53J9UJ0/p1625088032466700?thread_ts=1625039677.423700&cid=CA53J9UJ0
Ticket: COREML-2501
> Get docker configuration even if image is not provided

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
After some discussion on an internal PR, we've decided that we'd rather
have a single toggle for per-instance log routing.
> Make Logspout per-instance logging flag generic

- paasta_tools/cli/schemas/deploy_schema.json
- paasta_tools/cli/schemas/smartstack_schema.json
- paasta_tools/config_utils.py
- paasta_tools/contrib/rightsizer_soaconfigs_update.py
- paasta_tools/contrib/service_shard_update.py
- tests/test_config_utils.py
This PR:
- adds smartstack and deploy file validation
- removes the ability to disable validation that I had added a while ago
- removes hardcoded AUTO_SOACONFIG_SUBDIR const when validating
- removes `suggest_smartstack_proxy_port` in favor of `None` in `service_shard_update.py`
> Remove port in service_shard_update and add deploy/smartstack validation

- tests/test_config_utils.py
I had a bad reference to `AUTO_SOACONFIG_SUBDIR` - replaced it with the corrected import. Verified `make test` passes locally.
> fix failing test by fixing import

- paasta_tools/cli/schemas/deploy_schema.json
The paasta jenkinsfile parser supports this, but you can't actually commit it because it'll fail validation because it's not in the schema.
> Allow the `warn` key in deploy.yaml pipeline steps.

- requirements-minimal.txt
- requirements.txt
Allows usage of modern version with security fix:
```
requests-cache@0.4.10: upgrade to 0.6.0.dev1 for Arbitrary Code Execution [high severity][https://snyk.io/vuln/SNYK-PYTHON-REQUESTSCACHE-1089050]
```
> Remove upper pin on requests-cache

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
PAASTA-17446 for details. If the kubelet is down the services can still
be running so we don't want to tell nerve that there are no services
since that will cause it to deregister the services. I think that is
safe although it is very unsafe if we accidentally stopped all the
kubelets (and we have done that before). We also restart kubelets to
renew certs which triggers this case and deregisters services for a few
minutes before re-registering them when the kubelet starts again.
That creates some unnecessary churn in the mesh.
> Stop returning no services if kubelet down

- .activate.sh
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/tron_tools.py
- requirements.txt
- tests/cli/test_cmds_spark_run.py
- tests/test_tron_tools.py
Manual
```
./paasta_tools/cli/cli.py spark-run --cluster-manager kubernetes --cluster pnw-devc --cmd ' spark-submit /code/virtualenv_run/bin/spark_etl_runner.py --feature-config /code/batch/xxx/job_configs/xxx.yaml --env-config-path /nail/srv/configs/xxx.yaml --team-name xxx --notify-email y@elp.com --start-date 2021-08-15 --end-date 2021-08-15 --publish-path s3a://yelp-xxx-west-2/x/ -v ' --spark-args ' spark.cores.max=60 spark.executor.memory=13g spark.executor.cores=2 spark.driver.memory=13g spark.driver.cores=2 spark.jars.ivy=/tmp/.ivy spark.executor.instances=30' --service xxx
```
Succeeds: https://fluffy.yelpcorp.com/i/LfQ0XQ47l5s0jCF1pbnBS289ddH855mx.html
> Add new option to spark-run to choose which cluster manager to use

- docs/source/yelpsoa_configs.rst
Support for regex-matching was recently added in the mesh, so just updating these docs to make sure they reflect reality.
> Update endpoint timeout override docs to include regex-matching

- docs/source/yelpsoa_configs.rst
I accidentally missed this in #3184; adding this now so that tests will actually pass.
> Fix whitespace in docs

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
This makes `paasta mark-for-deployment --wait-for-deployment` use the new bounce status endpoint for progress instead of the instance status endpoint. The case logic is basically the same, just a little simplified.
This PR also deprecates support for bouncing Marathon instances. If instances of that type are bounced, they will considered non-supported/unbounceable instances.
`make test`
manual testing of `check_if_instance_is_done` on local `paasta api` on kubestage
e2e testing using `mark-for-deployment`, against kubestage as well
> Make m-f-d poll bounce status endpoint for progress

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This requires https://github.com/Yelp/Tron/pull/827 to be
merged/deployed before this can be merged/deployed itself
Verified by running `paasta_setup_tron_namespace -a --cluster norcal-corp --dry-run -d ~/pg/sysgit/yelpsoa-configs/` locally on a checkout modified to have k8s enabled on norcal-corp on a job using `cap_add`:
```yaml
actions:
run:
cap_add:
- NET_RAW
cap_drop:
- SETPCAP
- MKNOD
- AUDIT_WRITE
- CHOWN
- NET_RAW
- DAC_OVERRIDE
- FOWNER
- FSETID
- KILL
- SETGID
- SETUID
- NET_BIND_SERVICE
- SYS_CHROOT
- SETFCAP
```
and, on a job with no added caps:
```yaml
cap_add: []
cap_drop:
- SETPCAP
- MKNOD
- AUDIT_WRITE
- CHOWN
- NET_RAW
- DAC_OVERRIDE
- FOWNER
- FSETID
- KILL
- SETGID
- SETUID
- NET_BIND_SERVICE
- SYS_CHROOT
- SETFCAP
```
> Send cap_{add,drop} for k8s tronjobs

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/tron_tools.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
Just like we do for normal paasta services, we only expose a
`node_selectors` key and then translate that into the correct format
internally. However, unlike paasta services, we don't turn these into
the corresponding k8s representation since this is meant to be POSTed to
the Tron API.
I refactored some of the existing selector/affinity code for k8s
services in order to be able to reuse them as I didn't want to have to
duplicate those functions just so that we could use them for Tron.
> Send node selectors and affinities to tron

- paasta_tools/cli/cmds/status.py
- paasta_tools/flink_tools.py
- tests/cli/test_cmds_status.py
- tests/test_flink_tools.py
- Get job exceptions from Flink REST API instead of flink object
- Add tests for print flink status for different scenarios
_Not sure if there is a better way rather than calling the job/exceptions endpoint for each job._
> FLINK-3725 Query flink REST API for exceptions 

- requirements.txt
Bump service-configuration-lib==2.5.8.
Merging and running `make release` if all the checks pass successfully.
> [COREML-2570] fix k8s volumes being mounted twice

- paasta_tools/setup_istio_mesh.py
services.yaml doesn't include namespaces without proxy_port,
those namespaces are still routable via header and sockets so
we need to set them up in istio
> [setup_istio_mesh] walk soa_dir when loading namespaces in setup_istio_mesh

- paasta_tools/utils.py
The 5 seconds interval massively increases the load on the etcd nodes. The change introduced here: https://github.com/Yelp/paasta/commit/de82504539b7f45cf2319da92fac400166ef1d70 reduces the interval from 60 to 5 seconds. This PR reverses that change to reduce the load on etcd during y-m and other service bounces.
> Increase default polling interval to 60 seconds

- paasta_tools/cli/utils.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/monkrelaycluster_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
Adding functionality to paasta to propagate the yelpsoa-configs values to the operator. Currently, this is a basic version that does not hold any information about kubernetes in the way the cassandra operator works
> Monk 2524 add kubernetes status for monkrelayclusters

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
- Use ThreadPoolExecutor and futures to parallelize calls to flink rest api
- Modify one test to return the correct response with case of no exceptions
> FLINK-3725: Add concurrency in getting flink job exceptions

- docs/source/yelpsoa_configs.rst
As actually _using_ regex-matching causes many errors, removing this from the docs so that people don't accidentally use it.
> Remove docs on regex-matching endpoint timeouts for now

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
As part of the PaaSTA Workload Contract, we should be setting these
labels on Pods that we launch so that our tooling (e.g., OPA) knows what
to do with them.
> Send PaaSTA Workload Contract labels to Tron

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/docker_wrapper.py
- tests/test_docker_wrapper.py
In PAASTA-17466, an internal user reported that PAASTA_HOST is not a
resolvable hostname. This is because we're unconditionally mangling that
value and adding a uuid that dates back to when PaaSTA ran on Mesos.
This PR stops unconditionally setting certain Mesos-only environment
variables and additionally stops mangling the hostname we pass to Docker
if Mesos environment variables aren't set
> [local-run] Conditionally set MESOS env vars + unmangle docker hostname

- paasta_tools/contrib/service_shard_update.py
This branch adds an env key and bugsnag paasta secret api key to kubernetes configs. This is so that these keys will not have to be manually added to shards.
* `make test` passes.
> Add env and bugsnag paasta secret key to kubernetes configs

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/paastaapi/model/kubernetes_container_v2.py
- tests/instance/test_kubernetes.py
- tests/test_kubernetes_tools.py
This PR will make pre-restart/previous container output show in `paasta status -vv` and above if there has been a recent restart. Previous output does not replace the current container's output.
`make test`
local testing against norcal-stagef
Will this PR, `paasta status -vv` gets pretty busy, and is even more unusable for larger instances.
> Make pre-restart container output available for recent restarts in paasta -vv

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
- Auto generate pod affinity with weights specified by the user
- Pod affinity in this case is preferred but not guaranteed, the higher number user specify the tighter bin packing will be
- Pod affinity dependent on spark.kubernetes.allocation.batch.size, the smaller spark.kubernetes.allocation.batch.size is the tighter bin packing will be
testing done with 
```paasta spark-run -a --cluster-manager kubernetes --cluster pnw-devc --pool stable_batch --cmd ' spark-submit /code/virtualenv_run/bin/spark_etl_runner.py --feature-config /code/batch/campaign_info_daily/job_configs/bidding_history_daily.yaml --env-config-path /nail/srv/configs/ad_bidding_transform.yaml --team-name ad_market_dynamics --notify-email gcoll+ad_market_dynamics+batch@yelp.com --start-date 2021-08-08 --end-date 2021-08-08 …
```
> Auto generate pod template for pod affinity with weights specified by the user [COREML-2557]

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This is a hardcoded k8s limit and tron instance names can easily be >63
characters in length since they're {job name}.{action name} and these
are often pretty descriptive names.
> Ensure paasta.yelp.com/instance length is <=63 chars for tron

- paasta_tools/instance/kubernetes.py
`paasta status` would crash on evicted pods because the API tries to get status conditions for non-scheduled pods, but those don't exist for evicted pods. This PR makes it so that we check for evicted status first before we try to get status conditions.
- `make test`
- manual testing by setting up a paasta api on a real cluster, then running paasta status against the local api to test the api fix. instead of crashing, `paasta status` now returns properly, and the pod status is `Evicted` as expected.
I couldn't test this by simulating eviction using the eviction api or draining a node, because pods are quickly rescheduled, and don't stay in the `Evicted` state. I essentially had to wait for a real evicted pod in a real cluster. In our busiest cluster though, it does happen regularly so it …
> Fix paasta status crash on evicted pods bug

- paasta_tools/oom_logger.py
- tests/test_oom_logger.py
With a recent kernel upgrade, we got these improvements to oom-killer logs, which gave us a structured, key=value formatted summary log line: 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ef8444ea01d7442652f8e1b8a8b94278cb57eafd
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f0c867d9588d9efc10d6a55009c9560336673369
But this also removed the `Task in /kubepods...` line we had been using to fetch container IDs, so we have been missing OOM events for the hosts on the latest kernels.
This PR fixes oom_logger.py to also match the new one-line summary using essentially the same regex we used for the original `Task in /kubepods...` records. 
Note that I've left fetching the process_name from the `<process_name> invoked oom-killter` …
> PAASTA-17456: Update oom_logger to handle new structured oom-kill logs

- requirements-minimal.txt
- requirements.txt
`make test` passes.
Test was also performed with a successful manual run:
```
TRON_JOB_NAMESPACE=xxx TRON_JOB_NAME=xxx TRON_ACTION=xxx ./paasta_tools/cli/cli.py spark-run --cluster pnw-devc --service ad_bidding_transform --pool stable_batch --cluster-manager kubernetes --cmd 'TRON_JOB_NAMESPACE=xxx TRON_JOB_NAME=xxx TRON_ACTION=xxx spark-submit /code/virtualenv_run/bin/spark_etl_runner.py --feature-config /code/batch/xxx/job_configs/xxx.yaml --env-config-path /nail/srv/configs/xxx.yaml --team-name xxx --no-notification --start-date 2021-09-14 --end-date 2021-09-14 --publish-path s3a://yxxx-us-west-2/gcoll/k8s_darklaunch/ ' --spark-args ' spark.executor.instances=8 spark.executor.memory=16g spark.executor.cores=4 spark.driver.memory=8g '
```
Setting `TRON_ACTION` and `TRON_JOB_NAME` to …
> bump service_configuration_lib to 2.6.0

- paasta_tools/iptables.py
The best practice is to match `typename` with variable name.
For example, `mypy` reports any other usages as errors: https://github.com/python/mypy/pull/11206#issuecomment-927985235
> Fixes `namedtuple` type name

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
As we progress through our migration, we want to ensure that any new
Tronjobs on clusters that have already been fully migrated run on k8s by
default.
This PR will be accompanied by an internal Puppet PR that will provide
the configuration that this is looking at.
> Add ability to read the default use_k8s value from disk

- paasta_tools/prune_completed_pods.py
We've been seeing two weird issues in one of our stage clusters:
1) Pods in an Error state with no PodScheduled condition
2) Pods returned by list_namespaced_pod 404ing when we attempt to delete
them through delete_namespaced_pod
I was unable to repro 1) even after running this script in dry-run mode
for several days and was similarly unable to repro 2).
Since this is just a cleanup script, I decided to just log that we hit
an exception in these cases and continue on under the assumption that
these will either be cleaned up once the k8s API stops being flaky or
we'll be able to actually get more information on issue 1) with the
added logging and fix the issue at the root.
> Make paasta_prune_completed_pods less likely to crash

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
Currently, we only send a single annotation: the one that toggles
whether or not a Pod gets an internally-routable IP
> Send Pod annotations to Tron

- docs/source/yelpsoa_configs.rst
Reverts Yelp/paasta#3204
Now that we're fairly confident adding regex-matched timeouts won't break anything, I'm adding this again.
> Republish docs on regex-matching endpoint timeouts

- paasta_tools/contrib/timeouts_metrics_prom.py
The script loops through all yelpsoa folders and parses smartstack.yaml to get either `endpoint_timeouts` or `timeout_server_ms` value. Then we convert timeouts values into prometheus format using `prometheus_client` lib and save into the textfile with name ending with `.prom` which will be scraped by node exporter.
- If `endpoint_timeouts` is defined, we record per endpoint timeouts value. 
- If  `timeout_server_ms` is given, we record `timeout_server_ms` value as default path `/`
- Otherwise, we take default 1000ms  timeout_server_ms 
The metrics format as below:
```
yelpsoaconfig_endpoint_timeouts_ms{path="/consumer_app/devices/braze/info",upstream="push_notifications.main.egress_cluster"} 10000.0
yelpsoaconfig_endpoint_timeouts_ms{path="default",upstream="mysql_read_security.main.egres …
```
> Record prometheus yelpsoaconfig timeouts metrics

- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- tests/instance/test_kubernetes.py
This change uses asyncio.gather(return_exceptions=True) so we can leave existing try/except logic where they are when handling individual task results, rather than having to add it when we gather the tasks.
In addition, this catches the somewhat new exception where we are running into a timeout when fetching pods.  As the majority of the status won't be useful if we can't fetch pods, this also adds an error message useful for the user when we hit this problem.
In addition, because we use `pods_for_service_instance` only in status and `force_delete_pods`, where we typically _need_ the full results, I've bumped the timeout from the default 10s to 15s to reduce how many people hit this, while we investigate api slowness.
Finally this standardizes how we're patching some of our …
> PAASTA-17500: Handle more timeouts in new kubernetes status

- requirements-minimal.txt
- requirements.txt
Simply make paasta use the new service_configuration_lib change (https://github.com/Yelp/service_configuration_lib/pull/71).
> [COREML-2694] bump service_configuration_lib to 2.7.0

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_rollback.py
- tests/cli/test_cmds_start_stop_restart.py
This caused an incident several months ago when a user without permissions or understanding of the process accidentally stopped a bunch of instances
See PAASTA-17412
> Require that users have push permissions to start/stop/restart instances

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Setting the docker container memory limit to 2x of the spark driver limit.
Cpu limit I am currently setting the same as the spark.driver.cores.
If needs to be higher kindly let me know.
I have added the manual test results in the ticket COREML-2743
I will test one of the heavy batches in production once the code is reviewed.
> Set driver container memory and cpu limits

- paasta_tools/autoscaling/pause_service_autoscaler.py
We've run into confusion with this a couple times, first with the region failover exercise on 2021-11-18, and again today. This seems like a simple change to do to make it just a bit clearer.
> Add units (minutes) to autoscaler pause output

- requirements-minimal.txt
- requirements.txt
Simple package bump after pushing https://github.com/Yelp/service_configuration_lib/pull/72
Will release with `make release`
Tested with 
```
make clean dev
./paasta_tools/cli/cli.py spark-run --cluster pnw-devc --service xxx --pool stable_batch --cluster-manager kubernetes --cmd 'spark-submit /code/virtualenv_run/bin/spark_etl_runner.py --feature-config /code/batch/xxx/job_configs/xxx.yaml --env-config-path /nail/srv/configs/xxx.yaml --team-name xxx --no-notification --start-date 2021-09-16 --end-date 2021-09-16 --publish-path s3a://yelp-xxx-west-2/gcoll/k8s_darklaunch/ ' --spark-args ' spark.executor.instances=8 spark.executor.memory=16g spark.executor.cores=4 spark.driver.memory=8g spark.driver.cores=5'
```
> [COREML-2800] bump service-configuration-lib==2.8.0 (spark.scheduler.maxRegisteredResourcesWaitingTime for k8s)

- tox.ini
- yelp_package/dockerfiles/itest/hacheck/Dockerfile
Github is currently browning out access to unauth'd git and will be
fully disabling it in the coming months.
> Stop using unauthenticated git protocol for behave

- paasta_tools/cli/cmds/validate.py
- paasta_tools/utils.py
- tests/cli/test_cmds_validate.py
See PAASTA-17522 - but tl;dr: this can be a footgun (and especially so
for uwsgi-based services)
> Add validation for users overriding CPU request on CPU-scaled instances

- paasta_tools/tron_tools.py
We don't actually want to talk to the k8s API during tronfig validation
- and much less to create service accounts.
We take advantage of the handy-dandy for_validation flag available in
TronActionConfig (which is set when `paasta validate` calls the tronfig
creation/validation functions) to do this skipping without having to
touch any other code.
> Skip k8s service account shenanigans during tronfig validation

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- yelp_package/dockerfiles/itest/api/Dockerfile
- yelp_package/dockerfiles/itest/k8s/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
Our itest setup is annoyingly tangled and there's a lot of xenial
dockerfiles, so I'm dropping the itests from GHA until we have more time
to fix things correctly (likely by just removing all the mesos
code/itests)
> Drop xenial GHA builds

- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
Issuing 'paasta restart' of a flink service is not supported but we currently fail silently. This patch adds an intercept to notify the user about what happened and suggests a workaround.
> [FLINK-3869] Fail explicitly for Flink service `restart`

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
The value of status.nodes shouldn't be None normally, however, this PR ensures
that paasta status command will not break even if it is.
Verify it by running:
```
$ paasta status -s service -c cluster -i instance
service: service
cluster: cluster
instance: instance
Git sha:    xxxxxxxx (desired)
Cassandra cluster:
State: Running
Nodes: No node status available
```
> cassandra status: fix error when status.nodes is None

- paasta_tools/contrib/service_shard_update.py
For some reason, this was not caught in the branch check but is causing a failure during build
> fixes formatting

- paasta_tools/cli/cmds/spark_run.py
Fix this issue where pod name based on the filename of the batch is too long >63 chars:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://k8s.pnw-prod.paasta:6443/api/v1/namespaces/paasta-spark/pods. Message: Pod "generate-xxxxxxxxxxxxxxxxx-event-log-spark-app-f63a027ed986911e-exec-1" is invalid: metadata.labels: Invalid value: "exec-paasta_spark_generate_xxxxxxxxxxxxxxxxx_event_log_batch": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "exec-paasta_spark_generate_xxxxxxxxxxxxxxxxxx_event_log_batch": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, …
```
> Limit pod name to 63 chars for spark runs

- paasta_tools/kubernetes_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/conftest.py
- tests/test_kubernetes_tools.py
- tests/test_marathon_tools.py
- tests/test_tron_tools.py
- tests/test_utils.py
I previously made the `PAASTA_SOA_CONFIGS_SHA` env var available to what I thought was only long-running service containers, but because I made the change in `utils.py`, all containers configured through `paasta-tools` got it to. Because I only made sure the new env var doesn't affect config hashing for long-running services, Tron jobs were continuously reconfigured, causing an incident. 
To fix the issue, I've moved the env var setting to happen only for k8s long-running containers, and reverted changes to Marathon (which we no longer use) and `utils.py`.
`make test`
> Only expose PAASTA_SOA_CONFIGS_SHA to k8s long-running service containers

- paasta_tools/cli/cmds/spark_run.py
- requirements.txt
- tests/cli/test_cmds_spark_run.py
* make `kubernetes` the default option for `--cluster-manager`
* introduce `--disable-compact-bin-packing` which defaults to False
* make `--enable-compact-bin-packing` an always-True option which is basically a dummy option.
* update tests
> [COREML-2697] spark-run defaults to kubernetes

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
Display node's StartTime, when this value is available. We want to make sure nothing breaks even when StartTime is not available. We have added a test for this scenario as well.
Context: DREIMP-7929
> DREIMP-7929: add pod start time to Cassandra status writer

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
This PR uses the new status "properties" (a list of key-values), as provided by the Cassandra Operator, to print Cassandra status. Here's an example of a properties list:
```python
"properties": [
{
"verbosity": 0,
"name": "IP",
"value": "10.93.210.204",
"type": "string",
},
{
"verbosity": 0,
"name": "Available",
"value": True,
"type": "bool",
},
],
```
Which would be equivalent to this existing (to be deprecated) structure:
```python
{
"ip": "10.93.210.204",
"available": True,
}
```
While the old mechanism looks shorter, it is less flexible, and the information that it is neglecting is hard coded in Paastas status code (eg "ip" is displayed as "IP" and "startTime" can be parsed as a time value). Furthermore, adding, removing and modifying a new property requires coordination between the …
> DREIMP-7988: Use properties list in Cassandra status writer

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
We previously started work on running Spark drivers on Mesos directly
(rather than having them run on physical boxes), but this was never
used. I'm deleting the existing code so that we can start anew.
We're generally going to take the same approach here (i.e., have a
spark_args dictionary in soaconfigs that configures everything so
that users don't need to learn anything new/can use existing spark
knowledge + we don't have to stay on top of what Spark options exist to
add native support for them).
That said, I've added some schema checking for options that I've seen be
used somewhat frequently.
NOTE: this is completely unused at the moment, just splitting this into
its own PR to make future PRs smaller :p
> Add schema support for executor: spark

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
This is causing us to scale up our legacy mesos pools when k8s jobs
launch.
This does also mean that we won't print any cost warnings, but we should
probably get Core ML to refactor this further once we've stopped the
bleeding with this PR to get that feature back.
> Skip clusterman metrics for spark-on-k8s

- paasta_tools/cli/cmds/cook_image.py
- tests/cli/test_cmds_cook_image.py
CID would like this so that Jenkins can skip itesting and just cook an
image if tests have already passed pre-merge.
Unless --commit is passed, paasta cook-image will behave as it always
has.
> Teach paasta cook-image --commit

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
when the service and instance name are long enough, this can make the secret name hit k8s' 63 character limit, resulting in an error:
```
"reason":"FieldValueInvalid","message":"Invalid value: \"secret-boto-key-service-name-instance-name-blah-blah\": must be no more than 63 characters"
```
This should fix the issue by using the limit_size_with_hash function provided for exactly this purpose. I'm applying it to both the secret name and the volume name.
Tests pass, though I haven't done any additional testing.
> Add hash limit function to boto_keys secret names

- paasta_tools/api/client.py
- paasta_tools/secret_providers/__init__.py
- paasta_tools/secret_providers/vault.py
- paasta_tools/utils.py
- tests/api/test_client.py
- tests/secret_providers/test_vault.py
I don't think the paasta CA is used/actually works - all the config we have internally points the API to HTTP, and the CA config is only present in a subset of dev regions.
Lets remove to to simplify Vault config and avoid confusion unless we plan to work on this soon.
> Remove paastaca

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- tox.ini
We've had a couple pre-commit failures sneak in since `make test`
doesn't install/run hooks (and none of the toxenvs run in GHA do so
either)
> Run pre-commit as part of make test + readd general_itests

- .pre-commit-config.yaml
- paasta_tools/api/client.py
- paasta_tools/contrib/check_manual_oapi_changes.sh
- paasta_tools/secret_providers/vault.py
- tests/api/test_client.py
- tests/secret_providers/test_vault.py
There were some other PRs merged in between the last pre-commit fix and
getting pre-commit running in GHA again
We were also running check_manual_oapi_changes once for every file whenever
we ran `pre-commit run --all-files`, which was making things unhappy when
the hook was run in parallel (since `make openapi-codegen` mucks with files)
> Fix additional pre-commit failures + fix oapi hook

- paasta_tools/cli/schemas/tron_schema.json
We're deploying a version of tron that includes a pysensu-yelp version
that allows users to set the issuetype for any jira tickets that are
created - but the tron schema is strict and won't allow this to be set
without having a schema entry for the config key
> Allow issuetype key in tron monitoring configs

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
- tests/cli/test_cmds_spark_run.py
We're in a bit of a weird situation with spark where we want to run
stuff in a separate sparl-specific cluster, but there's a lot of
assumptions in the paasta codebase where the cluster you're running
stuff on will be populated by {workload}-{cluster}.yaml files - and we
don't really want to embark on migrating all the existing configuration
(since that requires that we migrate/work on a bunch of other stuff like
Tron to "natively" support this as a separate cluster in the same way as
every other cluster works)
> Add/Use cluster aliases for paasta spark-run

- paasta_tools/setup_kubernetes_job.py
- tests/test_setup_kubernetes_job.py
In setup_marathon_job, when we updated a deployment and caused a bounce, we emitted a `deploy.paasta` event to our metrics provider.
We lost that during the migration to kubernetes, which meant these events no longer showed up in the dashboards we present to service owners.
This change re-adds events, although now under `paasta.deploy` events rather than `deploy.paasta` events, with additional information whether the deploy was `created` or `updated`.  I swapped to be `paasta`-prefixed since that follows the other paasta-generated events we've been adding in e.g. mark-for-deployment.
Let me know if you think these should be logged with a different name/prefix. 
Manually running setup_kubernetes_job for compute-infra-test-service.status_test in infrastage generated the events in SFX as …
> Add deploy events to setup_kubernetes_job

- general_itests/fake_etc_paasta/api_endpoints.json
In https://github.com/Yelp/paasta/pull/3293 I added a dependence on api_endpoints (just to get valid cluster names) for `mark-for-deployment`, which broke `general_itests`.
This adds a dummy api_endpoints so mark-for-deployment works as expected.
> Add fake api_endpoints.json for general_itests

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
First fix attempt: https://github.com/Yelp/paasta/pull/3299/files
This change wasn't sufficient. We encountered an error when setting `boto_keys` for some services saying that the label attached to the ConfigMap object used to store secret signatures is too long:
(Service name changed slightly for the paste)
```
...HTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ConfigMap \\\"paasta-secret-servicename-this--one--just--has--a--really--long--instance--name-paasta-boto-key-servicename-this--one--just-yvib-signature\\\" is invalid: metadata.labels: Invalid value: \\\"servicename-this--one--just--has--a--really--long--instance--name\\\": must be no more than 63 characters\",\"reason\":\"Invalid\",\"details\":{\"name\":\"paasta- …
```
> Limit size of service name labels for signatures and volume mount names

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
By default it'll continue to use 10s as delay for hacheck, but we can switch it (per cluster) with puppet like
```
paasta_tools::config_file {'hacheck':
config => {
'hacheck_match_initial_delay' => true,
}
}
```
(probably in conjunction with a bunch of manual prep work)
> COMPINFRA-989: fix healthcheck_grace_period_seconds not being set for hacheck

- paasta_tools/instance/kubernetes.py
We've been throwing 500 errors when requesting kubernetes instance status while pods are being created; this occurs immediately after creation and does not yet have a `PodScheduled` condition yet.
This will now only override reason/message with scheduling errors if we do find a `PodScheduled` condition, and leave them at the values from `pod.status.reason`/`pod.status.message` if we don't find it.
> Only use PodScheduled condition if we find it

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
This fixes an edge case that can happen if the ConfigMap containing the signature is deleted but the secret exists, and may be out of date.
In that scenario:
- It doesn't find the signature, so it tries to create a new secret
- That fails with a 409
- The signature hash is set to the correct value
- On next run, the signature will look correct and it will do nothing
- The actual secret would only get updated once the actual value changes
Now, it will update the secret value anyway to the correct value.
We encountered this scenario when upgrading paasta to 0.123, because the name of the ConfigMap object changed. This left some services with an outdated secret value.
> Update boto_keys secret if it already exists

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_tron_namespace.py
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
It's a little annoying to be developing on this on a box with no creds,
so let's take advantage of the for_validation flag on all our config
options to allow us to skip any actual k8s operations as we would when
validating configs whenever we want to dry-run
> Allow for dry-running paasta_setup_tron_namespace

- requirements.txt
- yelp_package/extra_requirements_yelp.txt
Update scribereader to 0.15 to get paasta logs working in uswest2-corpprod
> Update scribereader to 0.15

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
This just sets up some scaffolding for what we need to actually start a
driver - a follow-up PR will actually do all the spark_args dict parsing
and use the code from this PR to turn that into a command line
> Add skeleton for generating spark driver env/cmd

- paasta_tools/instance/kubernetes.py
- tests/instance/test_kubernetes.py
This should fix the occasional 500s we get when a pod has recently started and has a container state with an empty `started_at` property.  
```
2022-03-25 12:26:53 | ERROR:paasta_tools.api.views.exception:Traceback (most recent call last):
2022-03-25 12:26:53 | AttributeError: 'NoneType' object has no attribute 'timestamp'
2022-03-25 12:26:53 | start_timestamp = this_state["started_at"].timestamp()
2022-03-25 12:26:53 | File "/opt/venvs/paasta-tools/lib/python3.7/site-packages/paasta_tools/instance/kubernetes.py", line 830, in get_pod_containers
2022-03-25 12:26:53 | "containers": containers_task.result(),
2022-03-25 12:26:53 | File "/opt/venvs/paasta-tools/lib/python3.7/site-packages/paasta_tools/instance/kubernetes.py", line 776, in get_pod_status
2022-03-25 12:26:53 | "pods": await …
```
> Handle potentially empty but present started_at property of pod state

- paasta_tools/api/views/instance.py
Currently we're seeing quite a few 500s during deployments when wait-for-deployment is hitting the `bounce_status` endpoint, but the logs are blank.
The full body of the response is simply `ERROR:  `, due to https://github.com/Yelp/paasta/blob/master/paasta_tools/api/views/exception.py#L43-L44 , and the logged error only includes the apparently-blank message:     `log.error(exc.msg)`
I'm suspecting that this is running into a problem during `paasta_tools.instance.kubernetes.bounce_status`, so this change should now include the traceback in the response if we run into a problem here, rather than just the error itself.
This mirrors our error handling above on lines 838-840 if we do not have a valid instance, for example.
> Return a traceback when we hit an error in bounce_status

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
We need a way to compare two KubeDeployment's that is not sensitive to
an autoscaler changing the amount of replicas present - otherwise, when
we go to compare the current and target deployment, we could oscillate
between what the autoscaler (HPA, in this case) has set a Deployments
replicas to and what setup_kubernetes_job saw prior to an HPA
scale-{up,down}
To accommplish this, we use the fact that we attach an annotation with
the autoscaling policy name to every autoscaled deployment and set the
replicas field of our internal KubeDeployment object to None for
anything that is autoscaled - which should be the same as leaving that
value unspecified (which will then let the HPA be the only thing
managing the replicas for a Deployment)
> Set KubeDeployment replicas to None for autoscaled deployments

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
Right now, drivers will start and spin up executors - but these
executors will instantly crash since they can't communicate with the
driver.
This change sets things up so that drivers can be started in a way that
makes them reachable by the executors they start
> Forward Spark ports to Tron/task_proc

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
Reverts Yelp/paasta#3333
forgot that I needed to fully deploy Tron since I added a new key to the payload we send to the Tron API to configure jobs
> Revert "Forward Spark ports to Tron/task_proc"

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/api/test_instance.py
- tests/cli/test_cmds_wait_for_deployment.py
- tox.ini
We are occasionally seeing slowness grabbing responses from the k8s api, but eventually things do return.
This forces paasta_tools.api.views.instance to slightly modify the response body if we hit this particular issue such that mark-for-deployment/wait-for-deployment can identify this specific response & print a more friendly error to users.
I also considered throwing a 599 rather than a 500 for this issue to make things even more easily identifiable, however 599 is not exactly an HTTP standard, and this does still represent an error on the backend where we cannot return a valid repsonse to the user.  Let me know if it makes sense to go w/ an alternate return code here.
Previously during deploys where we wait-for-deployment, we would see only …
> Catch timeout issues in bounce_status and present less-drastic error message

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
The original approach here used an annotation that was only present for uwsgi-scaled services. To fix this, we'll add another label and use that instead in order to prevent any issues from our existing metrics collectors potentially getting confused by a new value for the existing annotation
> Add autoscaled label

- mypy.ini
- paasta_tools/cli/cmds/push_to_registry.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/utils.py
- tests/cli/test_cmds_push_to_registry.py
We want push-to-registry to support the new docker image name:
`services-{service}:paasta-{git_sha}-{extrastuff}`
The relevant ticket for this is:
https://jira.yelpcorp.com/browse/COMPINFRA-1039
> Support additional version information in push-to-registry

- paasta_tools/cli/cmds/status.py
Currently if an instance has been manually stopped with paasta stop, paasta status will show State: Stopping when instance count is 0. The state should show Stopped when the process is complete.
[Before](https://fluffy.yelpcorp.com/i/MD36h6KW5gqMbVDWPgzj6sl0341xgdJC.html)
[After](https://fluffy.yelpcorp.com/i/3TztB9xmgdCQQnw1MnfC19KPB94TrJtl.html)
> Update to check all status versions before setting state to stopped

- docs/source/yelpsoa_configs.rst
As a post-mortem improvement, clear up the documentation around healthchecks on k8s, and add the additional insight we learned
https://jira.yelpcorp.com/browse/PAASTA-17644
> improve healthcheck docs as post-moretem for 1520

- paasta_tools/cli/cmds/spark_run.py
- requirements.txt
- tests/cli/test_cmds_spark_run.py
Issue: Spark users on kubernetes no longer able to see expected cost of the job on their driver logs as it used to be on mesos.
Ticker: COREML-3192
Changes:
1. Spark users can see the cost of their job on driver logs
2. Make sure spark users don't give invalid pool. 
To avoid this issue: https://yelp.slack.com/archives/C027FRM6285/p1652552586482009
Test:
1. make test
2. Manual test(s)
```
Selected cluster manager: mesos
Sending resource request metrics to Clusterman
Resource request (4 cpus and 9010 MB memory total) is estimated to cost $0.064 per hour
Setting docker memory and cpu limits as 2g, 1 core(s) respectively.
```
```
Selected cluster manager: kubernetes
Resource request (4 cpus and 9010 MB memory total) is estimated to cost $0.064 per hour
Setting docker memory and cpu limits as …
```
> Add check for valid pools and get spark cost for emitted for jobs on k8s

- paasta_tools/cli/cmds/mark_for_deployment.py
Example output when not passing --wait-for-deployment: https://yelp.slack.com/archives/CA7BTF81J/p1654049006105819 (same as screenshot)
Example output when passing --wait-for-deployment (same as status quo): https://yelp.slack.com/archives/CA7BTF81J/p1654049042095339
> Don't show progress in slack when not waiting for deployment. PAASTA-17585

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
Currently configure_nerve uses [get_kubernetes_services_running_here_for_nerve](https://github.com/Yelp/nerve-tools/blob/master/src/nerve_tools/configure_nerve.py#L365-L368) to determine whether to report a local pod.
This caused an issue recently when a pod was stuck in `Terminating` for a long time, but its IP had already been reassigned to a different pod on the same host.  `get_kubernetes_running_services_for_nerve` reported the terminating pod, which then kept it in nerve configuration.  Because the new pod used the same healthcheck uri and returned a healthy result, the registration for the old pod continued to exist.
Currently our smartstack-registered pods' hacheck containers have a preStop that immediately marks the instance as down in the service mesh.  It seems correct to also …
> Add a toggle to exclude terminating pods when reporting local pods to nerve

- paasta_tools/generate_deployments_for_service.py
- tests/test_generate_deployments_for_service.py
Initially we wanted the git-tag format to be:
`paasta-{deploy_group}-{image_version}-{timestamp}-deploy`
However, this made it hard to parse when the deploy group included a `"-"`. As a result, we're instead opting for:
`paasta-{deploy_group}:{image_version}-{timestamp}-deploy`
This changes the format in the most recent changes. We'll use this format going forward in the upcoming changes.
> Update git-tag format in generate-deployments-for-service

- .github/workflows/ci.yml
- paasta_tools/cli/schemas/deploy_schema.json
Bumping paasta's deploy.yaml schema to match our internal py-gitolite version.
See https://github.yelpcorp.com/packages/py-gitolite/pull/58 for more information.
This change does not add schema validation to `paasta validate`, just ensures the schema is in sync w/ our validation script's copy.
> Update deploy_schema.json to restrict deploy group names

- mypy.ini
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
- paasta_tools/deployment_utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_rollback.py
- tests/cli/test_utils.py
- tests/test_deployment_utils.py
This adds a new DeploymentVersion type that contains just `sha` and `image_version`.  When converting this type to a string, it should only return the sha if image_version is None, but print the full version otherwise -- this should help keep user-presented output consistent w/ status quo until things actually start getting `image_version`.
Where rollback previously dealt with just listing past shas for deployment info, I've converted it to use this new class.
This required adding the `image_version` keyword to `paasta_tools.cli.cmds.mark_for_deployment.mark_for_deployment` but this leaves the actual mark-for-deployment changes to a separate task.
I confirmed that the command still works as expected w/o an `--image-version`, and the output is nearly identical with status quo:
old: …
> COMPINFRA-1080: Update rollback to support new extra image metadata

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
`paasta_tools.cli.cmds.status.get_actual_deployments` was the last remaining non-test usecase depending on the v1 version of deployments.json, and in particular depending on the current format of our docker images as `service-<servicename>:paasta-<gitsha>`.  
As docker_image format will be changing with our no-commit redeploy project this quarter, this PR updates `get_actual_deployments` to use the information from the v2 deployment information, which stores gitsha directly, rather than needing to parse it from the docker image.  This required using `get_instance_config` to be able to match an instance to a deploy group in order to grab the git sha and maintain `get_actual_deployments`'s original return value.
`get_actual_deployments` was used in:
* paasta_tools/cli/cmds/status.py
* …
> Update get_actual_deployments to use deployments.json v2

- paasta_tools/cli/cmds/status.py
This is for:
[COMPINFRA-1043](https://jira.yelpcorp.com/browse/COMPINFRA-1043)
The output should look like:
```
service: pii_logging_detection
cluster: pnw-prod
instance: main
Git sha:    409f8265 (desired)
State: Running
Running versions:
Rerun with -v to see all replicas
409f8265 (image_version: none) - Started 2022-05-17 12:33:09 (20 hours ago)
Replica States: 1 Healthy
instance: pii_logging_detection_kafka_sampling.run
Tron job: pii_logging_detection_kafka_sampling
Dashboard: http://y/tron-pnw-prod#job/pii_logging_detection.pii_logging_detection_kafka_sampling
```
We could also make it so that it stays the same if image_version is unset to keep the status-quo? Happy to do it either way.
> Show image-version in new paasta status

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
This reverts commit 85e798f933ecd5d216bac6c7e74ec9e734128207.
This commit is ~suspected~ confirmed to cause a severe performance hit on `paasta status` requests for large instances.
> Revert "Update get_actual_deployments to use deployments.json v2"

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/paastaapi/model/instance_bounce_status.py
- paasta_tools/paastaapi/model/instance_status_kubernetes.py
- paasta_tools/paastaapi/model/instance_status_marathon.py
- paasta_tools/utils.py
- tests/api/test_instance.py
- tests/cli/test_cmds_wait_for_deployment.py
- tests/instance/test_kubernetes.py
- tests/test_kubernetes_tools.py
Instead of caring about `active_shas`, we want to look at `active_versions` which include the new `image_version` information. This adds another element to the tuple that used to represent `versions`; I wonder if we should just add something like `DeploymentVersion` to the API and just use that instead, happy to go with either!
> Change active_shas to active_versions

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
argparse struggles to parse into bool types.  `--auto-set-temporary-credentials-provider=False` resulted in `auto_set_temporary_credentials_provider="False"`, which of course equals True and meant that service_configuration_lib wouldn't disable the temporary credentials provider...
So making this be more standard "store_true" flow even if it is somewhat annoying due to the double negatives
> Fix argparse for disabling temporary credential provider in spark cli

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
MLCOMPUTE-184
We have added optimal timeouts for 77% of batches. 
* Adding auto-timeout for remaining batches and for any new batches.
* Adding option to manually add timeout with argument
Will push it on Monday.
Tests:
* Local
* Manual dev runs
Monitoring:
* We will get notified on our slack notifications channel for any timed out jobs, if need manual adjustment
> Add default timeout for all remaining spark jobs

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
The rollout of https://github.com/Yelp/paasta/pull/3382, broke use-cases for batch runs without spark-submit commands.
I noticed there weren't any unit test cases for when the command is not `spark-submit`
Description: 
1. Add fix for non spark-submit commands
2. Add more unit-test cases for non spark-submit commands (pyspark and bin/bash)
3. Continue even if the timeout couldn't be added with `warning`
4. Add more manual test cases and reproduction of error
Test cases: 
* make test
* Reproduction of error: https://fluffy.yelpcorp.com/i/VXcrTsXlldv20BRmSHb1Jn32rmBP1jKl.html (Without the fix)
* With `pyspark`: https://fluffy.yelpcorp.com/i/dfTF6VWl8SHl7djr4VZpqN9T31Sn7KzQ.html#L1 (With fix)
* With `spark-submit` with `timeout` added: …
> Add fix for auto timeout add for non spark-submit commands

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/cmds/cook_image.py
--dry-run can, in certain cases, actually result in Make doing real
work. To ensure that we don't inadvertantly run anything while figuring
out if a Makefile does respond to a target, we'll switch to using
--question which won't execute anything.
> Use make --question to check if a Makefile has a given target

- paasta_tools/cli/cmds/validate.py
The `paasta validate -v` command is supposed to print the date and time of the next 5 cron runs for valid schedules. This wasn't making use of the soa_dir argument in `load_tron_service_config()` which means it was always using the default value and local changes to yelpsoa had no impact.
Added a new job and updated the schedule for it:
- [Initial add of kevins_cool_job](https://fluffy.yelpcorp.com/i/MLRLFNG174qsNLVpkQpxs3B5zx0k9CdH.html)
- [Updating kevins_cool_job](https://fluffy.yelpcorp.com/i/Sw0pd5Q7VcJhKqBvpFH0MbC2rghw9G6m.html)
Also added a todo for TRON-1761 to address the issues I found with cron validation in Tron.
> Add soa_dir arg to verbose logging

- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/utils.py
- tests/cli/test_cmds_mark_for_deployment.py
This is the initial work for using image-version in mark-for-deployment on top of the wait-for-deployment changes.
> Use image-version in mark-for-deployment

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
1. Enabled AQE: adaptive query execution by default.
2. Log Signalfx url and final command. There were not originally logged in tron web ui. 
Useful for debugging.
Test result added as a comment in ticket: [MLCOMPUTE-17](https://jira.yelpcorp.com/browse/MLCOMPUTE-17)
Rollout plan:
1. Live Experiment Stage: Roll this pr out
2. Monitoring: 1 week: Observe on internal channel for any unexpected behavior, impacted runtimes of spark batches
- Rollback, debug and fix any unprecedented issues
4. GA: Roll the change out on service_configuration_lib and rollback this change
> Enable spark.sql.adaptive.enabled to true for all spark jobs

- paasta_tools/instance/kubernetes.py
- paasta_tools/smartstack_tools.py
We sometimes see single hosts have envoy issues, and having these
cascade into paasta status breaking for the pool these hosts are in is
not a great experience.
To minimize the impact here, grab a random host from the target pool
rather than the "first".
> Randomize host selected in mesh_status

- paasta_tools/cli/schemas/deploy_schema.json
This just adds a new option to deploy.yaml steps to enable our enable_automated_deploys param.
This just keeps the schema in sync w/ our internal copy used for yelpsoa-configs-checker.
> Add enable_automated_deploys param to deploy_schema.json for no-commit (automated) deploys

- paasta_tools/cli/schemas/deploy_schema.json
@krall pointed out that the `enable_automated_deploys` flag is really only controlling *redeploys* of the same service sha, so we're renaming it appropriately.
> Rename new automated redeploy option

- paasta_tools/cli/cmds/spark_run.py
- requirements.txt
- tests/cli/test_cmds_spark_run.py
This adds an option to enable Dynamic Resource Allocation (DRA) for spark jobs through a flag --enable-dra in paasta spark-run sub-command. This translates to spark.dynamicAllocation.enabled=true in spark args.
The logic for setting the desired spark configs for dra is handled in service_configuration_lib: https://github.com/Yelp/service_configuration_lib/pull/81
Testing:
Unit tests
Tested this with service_configuration_lib changes using: https://yelpwiki.yelpcorp.com/pages/viewpage.action?pageId=208483399#Sparkdevelopmentrunbook-Method1:
> MLCOMPUTE-23 | Enable DRA in paasta spark-run through a flag

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
In PAASTA-17673 we noticed that even though there's a 1s timeout set on
this V1Probe, that timeout doesn't actually kill the script that the
probe runs - which can lead to these checks stacking up in our hacheck
sidecar and overwhelming the CPU request+limit of that sidecar and
leads to the hacheck sidecar getting heavily throttled (which doesn't
help :p)
**NOTE**: this *will* cause a big bounce
> Wrap readiness check script with a timeout

- paasta_tools/cli/cmds/itest.py
- paasta_tools/utils.py
- tests/cli/test_cmds_itest.py
- tests/test_utils.py
Given that for the purposes of the deployment pipeline `paasta itest` serves pretty much the same purpose of `paasta cook-image`, i.e. building the docker image but with the addition of running the service's integration tests afterwards, I replicated what was done in https://github.com/Yelp/paasta/pull/3348.
> Support additional version information in "paasta itest"

- paasta_tools/cli/cmds/get_latest_deployment.py
- paasta_tools/utils.py
- tests/cli/test_cmds_get_latest_deployment.py
This updates `paasta get-latest-deployment` to support full DeploymentVersions with the following behavior:
* (status quo) if the deploy group specified does not have an image_version, it will print the plain sha due to the default conversion of DeploymentVersion to string
* if the deploy group specified does have an image_version, it will default to the default conversion of DeploymentVersion to string, i.e. `DeploymentVersion(sha=...,image_version=...)`
* new arg: `--sha-only`: if the caller wants *only* the sha, regardless if there is an image_version specified for this deploy group, they can do this with the `--sha-only` flag, which will behave exactly like status quo for any invocations (possibly useful for those using `get-latest-deployment` to strictly get the latest sha deployed
* …
> COMPINFRA-1248: update get-latest-deployment for full DeploymentVersion & add json option

- paasta_tools/cli/cmds/spark_run.py
This is to fix the issue that if the users provide timeout as floating hours (instead of integer ones) example: 1.0h, it would still use the default timeout value as 12h.
Few more manual test runs: https://fluffy.yelpcorp.com/i/wFH1MlCVtZR5W82DWxMm5VBw9bHGgDJp.html
> Fix regex to also assert timeout values of type float

- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_validate.py
Currently, paasta validate fails when entering any preceding comments in yelpsoa-configs.
This PR will fix the failure and join together multiline comments.
> PAASTA-17666: Fixes paasta validate to allow preceding comments

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
[MLCOMPUTE-436](https://jira.yelpcorp.com/browse/MLCOMPUTE-436)
Based on PR: https://github.com/Yelp/paasta/pull/3211 originally written by @benbariteau.
This should likely fix the docker daemon not found issue.
Definition: https://docs.python.org/3/library/os.html
```...For [execle()](https://docs.python.org/3/library/os.html#os.execle), [execlpe()](https://docs.python.org/3/library/os.html#os.execlpe), [execve()](https://docs.python.org/3/library/os.html#os.execve), and [execvpe()](https://docs.python.org/3/library/os.html#os.execvpe) (note that these all end in “e”), the env parameter must be a mapping which is used to define the environment variables for the new process (these are used instead of the current process’ environment); the functions …
```
> Use execlp instead of execlpe

- Makefile
This doesn't exist anymore - not sure how jenkins internally is fine
with this...
> Stop calling paasta_itests toxenv

- general_itests/validate.feature
- paasta_tools/cli/cmds/validate.py
- paasta_tools/utils.py
- tests/cli/test_cmds_validate.py
cpu_burst_add is added on to the `cpus` value (which we use for k8s
cpu requests to get a k8s cpu limit - and we've seen internal users
set excessively high values here (which can impact other services
running on the same node).
To discourage this without blocking legitimate usecases (/providing a
smooth transition to outright blocking this if possible in the future),
we allow users to bypass this validation by adding a special comment
(just like we do with the cpu-autoscaled-but-not-autotuned validation)
> Add validation to discourage large cpu_burst_add

- mypy.ini
- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/get_image_version.py
- paasta_tools/utils.py
- tests/cli/test_cmds_get_image_version.py
This adds a new (currently trivial) cli tool that will 'generate' a new image_version value to be used during paasta deploys.
As of right now we do only the following:
* check if automated redeploys is enabled for any deploy groups
* compare the current timestamp with the latest image_version tags found in current deployments
* If current image_versions do not start with a timestamp and cannot properly be converted to a datetime, this will essentially force a new version
* print the new image version as appropriate
This required modifying the `get_pipeline_deploy_groups` helper as that originally just gave deploy step _names_, whereas we needed the full step contents to be able to identify if any had enabled automated redeploys.
> COMPINFRA-1244: Add get-image-version cli tool to generate extra image version

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/utils.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
This PR will allow vault token path to be passed as a parameter in sync_secrets and default to /root/.vault_token if not defined to prevent any previous functions from breaking
> Adds specifying vault token path PAASTA-17437

- paasta_tools/cli/cmds/rollback.py
Added a warning message about needing to revert in git in paasta rollback.
Testing in two ways:
1) Tested the change by running the unit tests in ``test_cmds_rollback.py`` ensuring I see the warning message shown when assert results in 0. 
```
(py37-linux) emanelsabban@dev55-uswest1adevc:~/pg/paasta$ py.test -s ./tests/cli/test_cmds_rollback.py
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.7.5, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/nail/home/emanelsabban/pg/paasta/.hypothesis/examples')
rootdir: /nail/home/emanelsabban/pg/paasta, …
```
> Added a warning message to paasta rollback - PAASTA-17749

- paasta_tools/config_utils.py
- tests/test_config_utils.py
Currently, comments are thrown away due to two different issues:
1. `get_existing_configs` throws away comments
2. Writing configs throws away comments **if** the comment occurs in the yaml data itself (ie. a comment at the start of a yaml file is OK)
Resolve the first issue by using ruamel to read yaml, and resolve the second by messing with the internal structure of the read yaml file. In the future, we can combine this if/else block to more cleanly insert a header comment (as used by other contrib scripts), but this should do for now
> maintain yaml comments when autoupdating configs

- .github/workflows/ci.yml
- yelp_package/dockerfiles/bionic/Dockerfile
- yelp_package/dockerfiles/gitremote/Dockerfile
- yelp_package/dockerfiles/itest/api/Dockerfile
- yelp_package/dockerfiles/itest/hacheck/Dockerfile
- yelp_package/dockerfiles/itest/httpdrain/Dockerfile
- yelp_package/dockerfiles/itest/k8s/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/itest/zookeeper/Dockerfile
- yelp_package/dockerfiles/jammy/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
This should unblock me fixing the build in https://github.com/Yelp/nerve-tools/pull/96 by making paasta-tools debs available for the nerve-tools itests.
> Have Github Actions create a Github release for release tags.

- .github/workflows/ci.yml
Without this, it seems like even though there was a tag pointing at master for [this actions run](https://github.com/Yelp/paasta/actions/runs/2981987092), the conditional failed because github.ref was `refs/heads/master` instead of the tag.
> Run ci github actions workflow on v*.* tags as well as master.

- docs/source/yelpsoa_configs.rst
- mypy.ini
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/dump_locally_running_services.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- tests/test_kubernetes_tools.py
- tests/test_marathon_tools.py
For PEREL-3176, this should let me run two sets of pods simultaneously in the same nerve namespace, with different sizes (cpus, number of workers) but also different weights.
This should let us do side-by-side comparisons of different sizes of containers, while keeping their relative traffic levels the same. (e.g. bigger pods would get more traffic, so that percent utilization is the same for both sizes.)
Corresponding configure_nerve PR: https://github.com/Yelp/nerve-tools/pull/96
> Allow setting load balancer weight per instance in yelpsoa-configs

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
Added a condition to set Evicted pod's replica state to be Not running.
All tests are passing.
> Evicted pods should cause replica state to be 'Not Running'

- Makefile
- README.md
- paasta_tools/contrib/ide_helper.py
Added debugging settings in VS Code for some PaaSTA CLI commands and the PaaSTA API via a make target.
More specifically I added debugging settings for running tests, the paasta API and the following paasta CLI commands:
- logs
- status
- validate
- rollback
- mfd
The make target is called ``vscode_settings`` which set launch.json with default debugging configurations for the PaaSTA codebase and adds a list of recommended extensions to the extensions.json file.
I also added **Debugging** section in PaaSTA README.
I tested each CLI command by running it with a test service ``katamari_test_service``. I tested paasta api by following the steps below:
1. Ran ``make vscode_settings`` to add the launch.json and extension.json files.
2. Running the paasta api test in debugger to create the …
> Added VS code debug settings for paasta - CIPXIDEAS-209

- paasta_tools/cli/cmds/get_image_version.py
- tests/cli/test_cmds_get_image_version.py
Currently we are using `paasta get-image-version` to determine what image_version to use for a particular deploy.
Right now, we would re-use the latest image_version from the latest deploy_group with no-commits enabled, but if we are performing a new deploy due to a code change, we will want to generate a new image_version each time.
This updates get-image-version to only get the 'latest' image_version if the passed commit is the same as the deployment's git_sha.
Manually running this shows the tool behaves as expected:
```
$ paasta get-image-version -s compute-infra-test-service -c c4ac93a98809383a275df749318c5e04524fc3ab # a sha already used in a deploy, with image_version 20220906T174732
20220906T174732
$ paasta get-image-version -s compute-infra-test-service -c abcabc # passed sha …
```
> Take in commit for get-image-version

- .github/workflows/ci.yml
Very minor change, but we might as well use the github generated changelogs in releases (feel free to merge this PR)
> generate release notes now that we create releases

- paasta_tools/cli/cmds/mark_for_deployment.py
We had a few UI components that still only reported git sha during a bounce, even if we were bouncing to/from a version w/ no-commits/automated redeploys enabled.
This updates the last few components, including slack button text, which must remain <76 characters long and even then, may truncate at 30 characters ([docs](https://api.slack.com/reference/block-kit/block-elements#button__fields)).  In these situations, given we have potential plans to make `image_version` potentially even longer, it seemed prudent to just set these to `old version`/`new version` strings and allow the full versions be included in other slack messages, given we are only updating to one version during these interactive deploys.
Resulting slack thread looks something like …
> Update last few references to sha-only versions in mark-for-deployment

- yelp_package/extra_requirements_yelp.txt
This was added for pmu's Push-on-Green project, but is no longer used (and we've gone in another direction with the auto rollback systems)
> Remove unused dependency

- paasta_tools/cli/schemas/kubernetes_schema.json
This was never plumbed through for k8s and we don't seem to actually need it, so let's prevent folks from adding a misleading config option that will actually noop
NB: we could support this, but it's pretty insecure so until someone has a good reason to need this - we can punt on that.
> Delete support for using host network in k8s

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Pods in paasta namespace do not have the yelp.com/owner label, this PR adds those
To fulfil  the project - https://yelpwiki.yelpcorp.com/display/COMPUTE/Enforce+PaaSTA+workload+contract we need the labels on pods
This PR adds `compute_infrastructure_platform_experience ` as the value of the label `yelp.com/owner` for pods, the pods already have the name of the service running as the value of the label - `paasta.yelp.com/service`
```sh
akshaysha@dev56-uswest1adevc:~$ kubectl-pnw-prod get pods --all-namespaces -L yelp.com/owner
INFO: You are using an Okta authenticated kubectl wrapper
NAMESPACE                  NAME                                                                                                                                                     READY   STATUS …
```
> COMPINFRA-1495, add yelp.com/owner label to pods

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
Swap over to environment credentials provider from the temporary credentials provider.
This also allows us to drop several of the other options I had added which are no longer needed.
> Adhoc spark runs use environment credentials provider.

- requirements.txt
We have bumped the version for service_configuration_lib here - https://github.com/Yelp/service_configuration_lib/pull/90, doing the same in Paasta
> CLUSTERMAN-710, bump version for service_configuration_lib to 2.12.2

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/paasta_service_config_loader.py
- paasta_tools/paastaapi/model/instance_status.py
- paasta_tools/utils.py
- tests/api/test_instance.py
- tests/cli/test_cmds_status.py
Two issues fixed:
1. Stops using DeploymentsJsonV1 in `get_actual_deployments`. This was attempted once before but caused severe performance issues during bounces.  Because this now uses `PaastaServiceConfigLoader` those same performance issues have been mitigated, as we'll be loading the deployments.json only once per service, rather than clusters*instances times
In making this change, I found that the PaastaServiceConfigLoader comments were slightly incorrect about usage (`instance_type` vs `instance_type_class`), so fixed them
2. We had one reference to a top-level `git_sha` in our `InstanceStatus` type, so this adds an equivalent `version` field and sets it appropriately to the short representation of the DeploymentVersion.
Because this depends on a change to the API, the client side …
> COMPINFRA-1050, COMPINFRA-1043: fix paasta status output to show full version if provided

- paasta_tools/cli/cmds/secret.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_secret.py
- tests/test_kubernetes_tools.py
- tests/test_utils.py
Checks wether a service has opted-in for team level access patterns to secrets in service configs.
If so, paasta secret decrypt cli changes logic to retrieve the secrets from k8s (using kubectl), instead of the default secret provider decryption. Otherwise, the logic remains unchanged.
> Secrets for teams feature in paasta secret cli

- paasta_tools/cli/cmds/spark_run.py
- Increase executor range for mass rollout of Spark DRA to 16.
> MLCOMPUTE-216 | increase dra mass rollout executor range to 16

- docs/source/paasta_development.rst
This PR updates the readthedocs paasta documentation with the playground make targets for destroying and creating a fake cluster
> Updating docs with playground make targets

- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/utils.py
- tests/test_setup_kubernetes_cr.py
- tests/test_utils.py
The changes attempt to customly load flink configurations when updating crs of kind Flink. 
Context: 
- Yelp internal flink operator looks for changes in CRs specs and apply the changes by reconciling the flink clusters. 
- In scope of https://jira.yelpcorp.com/browse/FLINK-4103 project, this is needed to load extra configuration for auto config files on updating Flink k8s CRs (if exists)
- This is similar to the approach taken when reading instances configs for paasta services with autotune (y/autotune)
Open questions: 
- Is this the right way to modify? Any feedback would be appreciated given the basic knowledge of paasta I have. 
- How to test this is completely working without rolling it out? 
- Why the [step](https://github.com/Yelp/paasta/actions/runs/3242377865/jobs/5315550295) is …
> FLINK-4163: Add more generic config loading for setup cr

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
We've started stuffing some of the stuff that's Tron-specific in InstanceConfigDict - but this is a common base TypedDict that's used by all instances
> Fix TronActionConfig config_dict typing

- paasta_tools/contrib/get_running_task_allocation.py
- tests/contrib/test_get_running_task_allocation.py
Most of the namespaces that "belong" to PaaSTA are prefixed with paasta, with the exception of tron.
This teaches this script how to include additional namespaces in its output and sets the default to ["tron"] to avoid having to roll anything out :p
> Teach get_running_task_allocation about non-prefixed namespaces

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/utils.py
For the time being, we're not able to run SLO Watcher Threads and Metric Watcher Threads at the same time. 
If there are no SLOs present, Metric Watcher Threads may run.
> SLO Watcher Threads take precendence over Metric Watcher Threads

- .pre-commit-config.yaml
- paasta_tools/contrib/check_orphans.py
Because we now remove terminating pods from nerve config immediately, it seems like we're running into a race condition where this check can catch us between configure-nerve updating the config and nerve removing the affected registrations from zookeeper. This normally happens very quickly (within a second or two) in dev, but I suspect might take a little longer in prod due to the # of registrations per host (unconfirmed, but the alert behavior seems to support this).
This change to the script allows us to at least configure the 2 checks separately so we can continue to alert immediately if we see collisions, but alert only if orphans stick around after some configurable period of time (i.e. alert_after). 
Currently from searching splunk, the identified orphans come up only once in the …
> Allow us to check service mesh orphans separately from collisions

- .pre-commit-config.yaml
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
- tests/test_utils.py
Currently there is no way to override the default pool for tronjobs. We want to be able to enable the default pool as spam for the tron-spam-pnw-prod environment to remove unnecessary configuration needed in yelpsoaconfigs after finishing the migration to k8s for spam-pnw-prod.
This allows us to override the default pool via puppet for tron.
> TRON-1818: Updates paasta tools to allow tron pool override

- paasta_tools/list_tron_namespaces.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
[MLCOMPUTE-516](https://jira.yelpcorp.com/browse/MLCOMPUTE-516)
Add support for syncing paasta secrets onto k8s clusters for `paasta-spark` namespace 
The issue was `tron` instance_type is mapped with `tron` namespace, which is mapped with `tron*` .yaml files.
Added description:
These changes also take care of many edge cases with existing way of choosing and restructuring the tricky and confusing  tron namespaces. 
Trick used is, `spark` instance_type maps to `tron*` .yaml files and `paasta-spark` namespace.
Testing: 
* Unit tests
* Manual tests: 
-- I have manually tested if I am able get get correct instance list for instance_type , `spark`
Result in the ticket. 
I can try to run this sync script manually if:
-- I can get permission from CI to run it and
-- I have authorization to run …
>  Sync paasta spark secrets for paasta-spark namespace

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
For PaaSTA generated Kubernetes resources, we set the `yelp.com/owner` label to CIPX by default.
We should do the same for TRON generated Kubernetes resources.
Signed-off-by: Max Falk <gfalk@yelp.com>
> TRON-1824: change default owner of Tron generated resources to CIPX

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Added a parameter ``namespace`` in ``KubernetesDeploymentConfigDict`` and replaced hardcoded ``paasta`` namespace in ``kubernetes_tools.py`` file with the new namespace parameter.
Tested manually and using unit tests
> Added support for namespace parameter in soaconfigs - PAASTA-17791

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
- Enable Spark DRA by default
- Remove mass enabling through executor range logic
> MLCOMPUTE-216 | enable DRA by default in paasta spark-run

- Makefile
- k8s_itests/Makefile
- k8s_itests/deployments/kind/cluster-devbox.yaml
- k8s_itests/deployments/kind/cluster.yaml
- k8s_itests/scripts/containerd_registry_setup.py
- k8s_itests/scripts/set-paasta-registry-credentials.sh
This PR adds the default pool tag and the Yelp docker registry credentials to the local kind nodes
> Adding Yelp docker registry credentials to kind cluster

- .coveragerc
- .gitignore
- requirements-dev-minimal.txt
- requirements-dev.txt
- tests/test_marathon_tools.py
- tox.ini
The repo doesn't have code coverage set up, making it difficult to know which code paths are covered by unit tests
Add coverage dependencies and call pytest with coverage for `test` and `test-yelpy` Makefile targets
Ran unit tests
Note: the one test change is because of this change that happens when running with coverage vs not:
```
___________________________________ TestMarathonTools.test_get_marathon_client ____________________________________
self = <tests.test_marathon_tools.TestMarathonTools object at 0x7fb7f53040d0>
def test_get_marathon_client(self):
fake_url = ["nothing_for_me_to_do_but_dance"]
fake_user = "the_boogie"
fake_passwd = "is_for_real"
with mock.patch(
"paasta_tools.marathon_tools.MarathonClient", autospec=True
) as client_patch: …
```
> PAASTA-17808: Add code coverage to paasta unit test targets

- paasta_tools/kubernetes_tools.py
paasta status doesn't show the status of services not in "paasta" namespace.
Check what namespace is specified in soaconfigs and get status of instance in that namespace
- Unit tests pass
- Manual testing:
Tested on infrastage by running the paasta API and then point it to my version of soaconfigs and then running paasta status and point it to my version of soaconfigs. Output matches what is deployed on infrastage for service ``compute-infra-test-service`` :  https://fluffy.yelpcorp.com/i/XtHBSwDf0sPtfgsjFHL7mX7bNRKG61sP.html
> Ensure paasta status supports arbitrary namespaces - PAASTA-17825

- tests/autoscaling/test_autoscaling_service_lib.py
- tests/test_marathon_tools.py
- tests/test_utils.py
Some tests used `assert mock_object.called_once_with()`. The return value of `called_once_with()` is a mock object which always evaluates to true which means it always passes the assertion.
> Fix mock usage

- tests/conftest.py
This PR bypass raising an exception when calling `time.sleep()` in tests since is called by VSCode (debugpy) and PyCharm (pydevd) debugger
> Not raising exeptions in tests if debugpy or pydevd are loaded

- paasta_tools/cli/cmds/logs.py
- paasta_tools/cli/utils.py
When I was testing paasta logs with my own soaconfigs I wasn't getting logs for any instance I added. This is because even though I specified my soaconfig with -d flag, it wasn't being passed to ``list_all_instances_for_service`` function and thus it always was set to the default soaconfig
> passing soadir specified with -d flag when listing all instances of a service 

- paasta_tools/list_kubernetes_service_instances.py
- tests/test_list_kubernetes_service_instances.py
This PR adds `group_lines.py`(file from puppet) functionality into `paasta_list_kubernetes_service_instances`
> Adding group_lines.py functionality to paasta

- paasta_tools/setup_kubernetes_job.py
Before, we called create_application_object passing ``cluster=service_instance.get_cluster()`` and when the service_instance is none then it would crash. Also, later on in the function it might crash when doing ``service_instance_config.format_kubernetes_app()`` in ``create_application_object``.
Don't call `` create_application_object`` when ``service_instance`` is None but ensure we add the tuple whether it's (False, None) or (True, None) to applications list. This way later if we have (False, None) in the list it would return 1 :
`` return (False, None) not in applications``  as this is what we return end of ``setup_kube_deployments`` function
> Call create_application_object only when a service instance exist

- docs/source/autoscaling.rst
This is a follow up from #dar-1587.
In addition to this PR I have also updated our internal [confluence guide](https://yelpwiki.yelpcorp.com/display/PAASTA/HOWTO%3A+Autoscale+Your+PaaSTA+Service) to mention this.
> Add documentation note about using non-standard uwsgi_stats_port

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
There's internal users that would like to configure a Service Account
with specific permissions for use in their batches.
Right now, we can only dynamically create Service Accounts - and these
are generally only used for Pod Identity (or, they're mapped 1:1 with an
existing Role).
This PR enables users to explicitly set service_account_name in their
action configs and have that be plumbed all the way through to Tron
> Enable explicitly setting service_account_name in tron actions

- paasta_tools/contrib/get_running_task_allocation.py
The output of these is impossible to filter namespace-wise right now without joining on a whole bunch of data - let's just include the namespace directly and save ourselves some trouble
> Include namespace if get_running_task_allocation output

- paasta_tools/setup_prometheus_adapter_config.py
- paasta_tools/utils.py
- tests/test_setup_prometheus_adapter_config.py
This will allow us to slowly lower the impact of the offset parameter by decreasing this value from 1.0 -> 0 rather than completely removing it all at once (and potentially exposing problems hidden by our overscaling)
> Enable setting a multiplier to uwsgi offset config

- paasta_tools/setup_prometheus_adapter_config.py
- tests/test_setup_prometheus_adapter_config.py
In this PR we remove hardcoded "paasta" namespace in ``setup_prometheus_adapter_config`` file and replace it with the namespace from soaconfigs. We also ensure that we call ``ensure_namespace`` for all namespaces not just "paasta"
- Unit tests pass
- manually tested it on paasta playground and I see the adapter-config map created:
```
(py37-linux) emanelsabban@dev55-uswest1adevc:~/pg/paasta$ KUBECONFIG="./k8s_itests/kubeconfig" kubectl get configmap -n custom-metrics
NAME               DATA   AGE
adapter-config     1      22s
```
Describing configmap: https://fluffy.yelpcorp.com/i/hLq5wHQ8rXS4G0PM0mKzh0trzNr9Mh6k.html
> removing hardcoded paasta ns in setup_prometheus_adapter_config file - PAASTA-17777

- paasta_tools/cli/cmds/secret.py
- tests/cli/test_cmds_secret.py
This allows you to run tests and other non-paasta tasks (`make test`, integration/acceptance tests, service start-dev, etc) , with environment variables sourced directly from paasta secrets.
Along the way I refactored the argument parsing here, I tried to keep it as close as possible to previous behavior but it might be a bit stricter (in particular you can't put arguments between `paasta secret` and `add/update/decrypt` anymore)
```
$ .tox/py37-linux/bin/paasta secret run --help
usage: secret run [-h] [-y YELPSOA_CONFIG_ROOT] -s SERVICE -i INSTANCE -c
CLUSTERS [--vault-auth-method {token,ldap}]
[--vault-token-file VAULT_TOKEN_FILE]
[cmd [cmd ...]]
Runs a command with the secret environment variables from a given service
instance. The command is run directly, not in a Docker container. …
```
> adds "paasta secret run" subcommand

- paasta_tools/check_kubernetes_services_replication.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/check_services_replication_tools.py
- paasta_tools/kubernetes_tools.py
- tests/test_check_service_replication_tools.py
This PR adds support to arbitrary namespaces for paasta services.
Unit tests pass
**Note:** Added the elif  block because I realized that we call main() passing namespaces for ``check_cassandracluster_services_replication`` and ``check_flink_services_health``
> Adding support to any ns that runs a paasta service in check_kubernetes_services_replication - PAASTA-17846

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Seeking feedback on this proposed change to add more AWS functionality to local-run. The goal of this is to allow local-run to run within an AWS role context, to emulate what happens in a normal paasta context when pod identity (or kiam) is set.
This supports several scenarios:
- The service has an iam role configured, and you want to assume that role
- You want to specify a different role to assume
- You want to use whatever role aws-okta provides
Unless one of these new arguments is specified, behavior will be identical to before. 
If `--assume-pod-identity` is provided, it will check the relevant instance config for `iam-role`, and attempt to assume that role by using the aws-okta for an account matching the current runtimeenv. 
if `--use-okta-role` is provided, it will attempt to get …
> Add support for aws assume role in local-run

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
- tests/test_tron_tools.py
This PR adds an option `--force-spark-resource-configs` for `paasta spark-run` for users to skip the changes made by:  
https://github.com/Yelp/service_configuration_lib/pull/97
> Add force-spark-resource-configs option

- paasta_tools/cassandracluster_tools.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- paasta_tools/vitess_tools.py
- tests/cli/test_cmds_local_run.py
- tests/test_kubernetes_tools.py
- tests/test_paasta_metastatus.py
In this PR, we pass namespace to all the functions that requires it, otherwise it will be hardcode to "paasta" namespace.
These changes provide support for arbitrary namespaces in **paasta local-run** and **paasta_metastatus**.
passes unit tests
Note: The functions below also must be changed by passing namespace  but I didn't change them since they fall under ``paasta_secrets_sync.py`` work:
- ``create_secret``
- ``create_plaintext_dict_secret``
- ``update_secret``
- ``update_plaintext_dict_secret``
- ``update_kubernetes_secret_signature``
- ``create_kubernetes_secret_signature``
- ``get_kubernetes_secret_signature``
[WIP functions] Still looking into these functions:
- ``list_all_deployments`` -- > in metastatus_lib.py (Done- addressed in second commit)
- ``get_all_pods_cached`` -- > in …
> Ensure we pass ns to functions in kubernetes_tools.py - PAASTA-17857

- paasta_tools/prune_completed_pods.py
Add an option `--pending-minutes` in `paasta_prune_completed_pods` script to cleanup pending pods older than a certain threshold.
Test run in devbox with the following command:  
```bash
KUBECONFIG=/etc/kubernetes/paasta.conf KUBECONTEXT=pnw-devc paasta_prune_completed_pods --namespace paasta-spark -m 60 --error-minutes 60 --pending-minutes 1 --dry-run -v
```
> Add support for pruning pending pods

- paasta_tools/cli/cmds/secret.py
- tests/cli/test_cmds_secret.py
This aligns `paasta secret decrypt` with `paasta local-run` and `paasta secret run` (#3541) both of which don't require a password to do the Vault authentication.
This enables `paasta secret decrypt` to be called (potentially repeatedly) from scripts without getting password prompts.
> allow paasta secret decrypt to use token vault auth

- paasta_tools/cli/cmds/secret.py
- tests/cli/test_cmds_secret.py
This change is to play nicely with [`pgctl`](https://github.com/Yelp/pgctl), which wants a single process (for ease of signal handling): https://pgctl.readthedocs.io/en/latest/user/quickstart.html#writing-playground-services
(`pgctl-poll-ready` also does some file descriptor juggling which doesn't work with `subprocess`)
There's no cleanup in `paasta_tools.cli.cli.main` beyond catching `KeyboardInterrupt` so this change should be transparent (we aren't cutting off any cleanup actions): https://github.com/Yelp/paasta/blob/d336d2a58089eab453f2ffc870ad399653494b47/paasta_tools/cli/cli.py#L257
and I've also been using this locally.
> paasta secret run: subprocess.run -> os.execvpe

- paasta_tools/cli/schemas/adhoc_schema.json
https://github.com/Yelp/paasta/pull/3532 added a feature that allows `local-run` to use the `iam_role` setting of a service to assume the role locally. This means that `iam_role` now has a use case for being configured in adhoc service instances, as that is where `local-run` will read from by default. This allows you to set those.
> Add iam_role and provider to adhoc schema

- requirements-minimal.txt
- requirements.txt
Bump service-configuration-lib to v2.14.5.
Tested via running `paasta spark-run` locally.
> Bump service-configuration-lib to v2.14.5

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
The secrets for owner team implementation uses the wrong key for referencing shared secrets
Copied [the same pattern used elsewhere](https://github.com/Yelp/paasta/blob/2e1cafdc687f231eca07388f468bf4b00ebb95cd/paasta_tools/kubernetes_tools.py#L2083) to reference the correct secret name when the secret is a shared one
Confirmed this works with a service that uses shared secret and has `secrets_for_owner_team: true`
```
@@ -10,5 +10,6 @@ main:
+    PAASTA_SECRET_MY_SHARED_SECRET: SHARED_SECRET(test-shared)
```
```
$ paasta local-run --service the-service --cluster the-cluster -i main --interactive --pull
Re-executing paasta local-run --pull with sudo..
[...]
nobody@the-host:/code$ env | grep SHARED
PAASTA_SECRET_MY_SHARED_SECRET=SHARED_SECRET_TEST
nobody@the-host:/code$ exit
```
Without the …
> Support shared secrets in secrets for owner team

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
- Default DRA enable logic has been moved to service-configuration-lib
- Bump up service-configuration-lib version to 2.15.1
> MLCOMPUTE-537 | remove DRA enable logic, bump up version

- paasta_tools/cli/cmds/spark_run.py
MLCOMPUTE-700
Manual Test run: MLCOMPUTE-700
Expectation: Jobs on batch pool should run faster. There is no downside of this config as long the spark job is running. 
Context in the ticket.
> Set correct value of spark.kubernetes.decommission.script 

- paasta_tools/cli/cmds/local_run.py
This change supports older boto(2) clients that use AWS_SECURITY_TOKEN. While this has been deprecated for some time, I don't see any reason why we should support it.
> Add AWS_SECURITY_TOKEN to local-run assume-role env vars

- paasta_tools/cleanup_kubernetes_jobs.py
this should help cleanup_kubernetes_job not crash when it finds services with `instances: 0`.
> If existing_app has status.replicas=None, treat it as 0 replicas.

- paasta_tools/cli/cmds/secret.py
Fixes a bug found by @danielpops where `paasta secret run -y ...` would not reflect local changes made to an instance's environment variables (would always use the environment config from system yelpsoa-configs).
> [paasta secret run]  pass -y through to get_instance_config

- paasta_tools/cli/schemas/autotuned_defaults/kubernetes_schema.json
- paasta_tools/cli/schemas/kubernetes_schema.json
We have a couple instances in our code where we assume that these limits are inclusive, but recent changes to metric collection have shown that this is not true :)
Rather than try to fix every location where we made this incorrect assumption - let's just make that assumption reality.
> Make resource minimums in k8s schemas inclusive

- Makefile
- mypy.ini
- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/cli/cmds/status.py
- paasta_tools/delete_kubernetes_deployments.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/paastaapi/model/kubernetes_version.py
- tests/instance/test_kubernetes.py
- tests/test_delete_kubernetes_deployments.py
example output with new API (which returns namespace for each version): https://fluffy.yelpcorp.com/i/JV5mGznpQ8kZZlSGr1J5r4VJq68gNc0K.html (see lines 31, 35, 39).
example output with old API (which doesn't include namespace, and doesn't include versions in the old namespace): https://fluffy.yelpcorp.com/i/r5zMQhHCfdssxNsgkFFJZFHbnsrwqq6R.html
> Show status of apps in other namespaces, in case migration to a new namespace gets stuck.

- paasta_tools/cli/cmds/secret.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_secret.py
- tests/cli/test_utils.py
k8s secrets decryption used to rely on the default paasta namespace. Adding some functionality to trace back from a secret name to the instance types where it is used, followed by k8s namespaces that they are stored under.
Keeping a fallback to default, in case the mapping fails.
> Make paasta secrets for teams decrypt available for multiple instance types and namespaces

- paasta_tools/oom_logger.py
- tests/test_oom_logger.py
When cgroups are being handled by systemd, their name changes a fair bit, as it becomes the path to a scope unit, which causes existing expressions not to match any event. This adds a new regex which can extract the Docker container ID from those events as well.
In the process I noticed a bit of repeated code, to which I'm allergic, so time for a for loop. Added a `break` statement as well as it's definitely not necessary to test more regexes if one matched already.
> add support for systemd cgroup driver to oom_logger

- tox.ini
Just like in Clusterman, looks like we're not pinning dependencies for a tox env and are finally getting bit by that
related clusterman pr: https://github.com/Yelp/clusterman/pull/318
> Temporarily upper-bound urllib3

- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/status.py
This PR will clear threads after catching a `KeyboardInterrupt` to make sure that `paasta status` don't spookily 👻👻 take over people’s terminals
> Clearing paasta status threads after catching KeyboardInterrupt

- paasta_tools/cli/cmds/secret.py
There have been 3 PRs so far that wanted to add passing Vault token to the CLI `paasta secret`: https://github.com/Yelp/paasta/pull/3598 https://github.com/Yelp/paasta/pull/3588 but #3596  was merged
Since `vault_auth_method="token"` falls back to LDAP authentication, we don't have to change the default argument. However, because current directory is hard-coded the script must be run in the soa directory.
Was not sure if `DEFAULT_SOA_DIR` was safe to change
```diff
@@ -231,7 +231,7 @@ def _add_common_args(parser: argparse.ArgumentParser, allow_shared: bool = True)
"--yelpsoa-config-root",
dest="yelpsoa_config_root",
help="A directory from which yelpsoa-configs should be read from",
-        default=DEFAULT_SOA_DIR,
+        default="./",
)
```
The change should be safe because previously …
> Change default directory to `paasta secret {add,update}`

- paasta_tools/cli/cmds/secret.py
Changing default directory in argparse resulted in YM playground failing, so hard-coding location only for `add` and `update` commands which retain original behaviour.
Introduced by https://github.com/Yelp/paasta/pull/3603
> Hard-code current directory only for `paasta secret {add,update}`

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We've since upgraded the version of Docker we run and, according to https://github.com/moby/moby/pull/37781 - this has now been fixed.
Even without having found that PR, I'm pretty confident that this issue has been fixed as we pull an ungodly amount of simultaneous images in our kube nodes and have never seen issues like this :)
> Revert local-run locking from PAASTA-13417

- tests/cli/test_cmds_spark_run.py
I introduced some new arguments to `get_aws_credentials` call in #3584 and accidentally broke these tests. This fixes them.
> Fix spark-run tests after #3584

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
Since secret data is not needed until actually it needs to be created, we can delay fetching them. Otherwise, Vault gets too many requests because cronjob runs every minute.
Tested locally https://fluffy.yelpcorp.com/i/s2HZJKSjqgjXWv89t5PGhD5qXrcMkxWc.html
> Postpone getting secret data until it is needed

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Explicitly specify docker image digest instead of using image tag when launching a spark cluster to avoid inconsistent docker image between the driver and executors.
run locally in a service repo which has a cook-image makefile target.
```bash
aws-okta -r core-ml -a dev -k -p dev
paasta/.tox/py37-linux/bin/paasta spark-run --build --aws-profile=dev --cmd "spark-submit /work/integration_tests/s3.py"
paasta/.tox/py37-linux/bin/paasta spark-run --image docker-dev.yelpcorp.com/paasta-spark-run-chi --aws-profile=dev --cmd "spark-submit /work/integration_tests/s3.py"
paasta/.tox/py37-linux/bin/paasta spark-run --service spark --aws-profile=dev --cmd "spark-submit /work/integration_tests/s3.py"
```
Log output:  
In SparkUI:  
Log output:  
In SparkUI:
> Use sha256 digest for paasta spark-run

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
- tox.ini
`paasta spark-run` (when run with `--use-eks`) will require a different set of configuration: we'll be using a kubeconfig with the standard EKS setup rather than giving spark a URL to our masters + certs to auth with.
Technically can we do the env var shenanigans inside service-configuration-lib, but imo the added layer makes changing spark things more painful then necessary - and, most importantly, doesn't really use anything like PaastaSystemConfig or srv-configs in a standard way to support changing values without a PaaSTA or service-configuration-lib release.
> Add support for --use-eks in paasta spark-run

- paasta_tools/cli/cmds/spark_run.py
This change avoids the error when `docker pull` fails before correct url can be passed.
> returns image url in case docker pull fails

- paasta_tools/utils.py
- tests/test_utils.py
Reading environment variable NO_COLOR to check if ANSI colors should be omitted, see https://no-color.org/
> Adding support for disabling ANSI colors

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
This reverts commit 31d37224ee6764cfa0492927ea4eae437adba926, reversing changes made to a0fda947793b5834857d58dc80e2c2151feeeaa1.
I expect to un-revert this shortly -- this is just to get the repo back into a state that's equivalent to 0.175.1 but with a working bionic build.
> Revert "Merge branch 'u/krall/dont_sync_to_unused_namespaces'"

- yelp_package/dockerfiles/uwsgi_exporter-sidecar/Dockerfile
- yelp_package/dockerfiles/uwsgi_exporter-sidecar/Makefile
This change updates us to the latest uwsgi_exporter binary + builds a sidecar using an Ubuntu Jammy base image rather than an ancient Xenial base image.
Additionally, we now explicitly call the Make targets we're interested in (test and build) rather than the default (which goes into a very full-featured common Makefile that does a whole lot of things we don't necerssarily want to run)
> Update uwsgi_exporter dockerfile + build

- paasta_tools/cli/schemas/kubernetes_schema.json
I am adding autoscaling support for gunicorn services to paasta - allowing for existing uwsgi paasta services to switch to gunicorn.
This is a multi-part process:
Add `metrics_provider: gunicorn' to schema
> Add `metrics_provider: gunicorn' to schema

- yelp_package/dockerfiles/uwsgi_exporter-sidecar/Makefile
Jenkins has credentials available in a more "normal" way and doesn't need to sudo to docker push
> Update docker push command in CI for sidecars

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
- tests/cli/test_cmds_spark_run.py
Rather than forcing the addition of --use-eks to everything we may want to migrate to EKS, we can instead set a system-level default and instead allow users to override that value.
> Allow setting a default for Spark target cluster type

- yelp_package/dockerfiles/gunicorn_exporter-sidecar/.gitignore
- yelp_package/dockerfiles/gunicorn_exporter-sidecar/Dockerfile
- yelp_package/dockerfiles/gunicorn_exporter-sidecar/Makefile
- yelp_package/dockerfiles/gunicorn_exporter-sidecar/gunicorn.mapping
I am adding autoscaling support for gunicorn services to paasta - allowing for existing uwsgi paasta services to switch to gunicorn.
This is a multi-part process:
Add new statsd-exporter sidecar (named gunicorn-exporter-sidecar)
* Replicate the `uwsgi_exporter-sidecar` setup
* listens on 9117 for the prometheus scraper
* Provides total worker and worker busy stats for prometheus consumption
The `statsd-exporter` comes from https://github.com/prometheus/statsd_exporter
A gunicorn paasta service sends metrics via statsd to the exporter sidecar. Prometheus scrapes metrics from the sidecar.
> Introduce gunicorn_exporter-sidecar

- paasta_tools/utils.py
I've rolled this out through puppet overrides everywhere - this just changes the default here should we remove the puppet override
> Update the default uwsgi_exporter image to the latest

- docs/source/yelpsoa_configs.rst
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
- yelp_package/extra_requirements_yelp.txt
Ticket: PAASTA-17941
Problem
-----
On EKS, we cannot configure the default Kubernetes scheduler with pod topology constraints.
But to support the Karpenter migration and to be able to tune our spread of Pods across zones and nodes, we want to be able to configure cluster wide topology constraints via PaaSTA.
Solution
-----
Add a `topology_spread_constraints` option to the PaaSTA system config that allows defining rules to spread Pods across topologies per cluster.
For example to try spreading Pods evenly across both nodes and availability zones, we'd set:
```
topology_spread_constraints:
- max_skew: 1
topology_key: "topology.kubernetes.io/zone"
when_unsatisfiable: "ScheduleAnyway"
- max_skew: 1
topology_key: "kubernetes.io/hostname"
when_unsatisfiable: "ScheduleAnyway"
```
This can be …
> PAASTA-17941: add topology spread constraints option

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_crd.py
- paasta_tools/setup_kubernetes_internal_crd.py
- requirements.txt
- tests/test_kubernetes_tools.py
As part of our kubernetes upgrade (to 1.22) we need to upgrade kubernetes libraries being used to support k8s 1.22.
The kubernetes client library got updated in this PR to v24.2.0 and the proper tests were updated
[PAASTA-17925](https://jira.yelpcorp.com/browse/PAASTA-17925)
> Upgrading kubernetes client library to v24.2.0

- paasta_tools/kubernetes_tools.py
Problem
-----
Currently, if the Topology Spread Constraints option is set, `setup_kubernetes_job` will fail because the pod spec kwarg `topologySpreadConstraints` is not valid.
Solution
-----
Use snake_case `topology_spread_constraints` instead. Apparently the translation to valid k8s json manifests happens at a later stage.
Signed-off-by: Max Falk <gfalk@yelp.com>
> PAASTA-17941: fix topology spread constraint option by using snake_case instead of camelCase

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_crd.py
- paasta_tools/setup_kubernetes_internal_crd.py
- requirements.txt
- tests/test_kubernetes_tools.py
Need to do a clean release of PaaSTA v0.183.0 that we can release to production.
This PR is currently blocking that release because PaaSTA cannot apply CRDs with version `v1beta1`.
We'll re-apply this PR once 183 is released.
Reverts Yelp/paasta#3632
> Revert "Upgrading kubernetes client library to v24.2.0"

- docs/source/autoscaling.rst
- docs/source/installation/getting_started.rst
- docs/source/yelpsoa_configs.rst
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/setup_prometheus_adapter_config.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
- tests/test_setup_prometheus_adapter_config.py
I am adding autoscaling support for gunicorn services to paasta - allowing for existing uwsgi paasta services to switch to gunicorn.
This is a multi-part process:
Duplicate uwsgi logic for gunicorn
* Update utilities and tools
* Add scaling rule
* Add gunicorn sidecar when requested
* Label pod appropriately
I've duplicated most of uwsgi logic for gunicorn.
Changes from uwsgi:
* Dropped support for `offset` since that option is deprecated
* Assume prometheus will always be used.
I've validated this branch in our staging environment with a gunicorn service. I was able to see the service scale up and down in response to changes in worker utilization.
> Gunicorn autoscaling

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/setup_kubernetes_crd.py
- requirements-minimal.txt
- requirements.txt
- tests/test_kubernetes_tools.py
- tests/test_setup_kubernetes_cr.py
As part of our upgrade to k8s 1.22 we need to support both api extensions for v1 and v1beta1 on our  `setup_kubernetes_crd` scripts in order to make a smooth transition to 1.22
[PAASTA-17925](https://jira.yelpcorp.com/browse/PAASTA-17925)
> Adding support for extensions v1 v1beta1

- .gitignore
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/secret_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- requirements.txt
- tests/test_tron_tools.py
Ticket: [TRON-1636](https://jira.yelpcorp.com/browse/TRON-1636)
This  pipes secret_volumes in tron. It was already set up in kubernetes, so most of the work here was adjusting the tests.
- Had to use a file-based approach to figure out if the secret is shared or not, as it's not explicit for secret_volumes.
- Added a TronSecretVolume type to allow passing secret_volume_name to Tron/task_processing, so they don't have to figure that out themselves.
- Tested with patched wheel of https://github.com/Yelp/task_processing/pull/188. So once this task_proc PR is merged, we should update requirements.txt
This was tested with 2 real tron jobs and patched paasta and tron on our `tron-infrastage` box.
Success: https://fluffy.yelpcorp.com/i/bsJZQ3TlDR9N6fx3dNjT6WQfT0NVGh03.html
Jobs config: …
> TRON-1636: Setup tron secret_volumes in setup_tron_namespace

- paasta_tools/setup_kubernetes_cr.py
- tests/test_setup_kubernetes_cr.py
Fixing setup_kubernetes_cr exception due to missing objects
[PAASTA-17925](https://jira.yelpcorp.com/browse/PAASTA-17925)
> Fixing setup_kubernetes_cr exception

- paasta_tools/setup_tron_namespace.py
Currently `setup_tron_namespace` can fail prematurely if there is an error updating the `MASTER_NAMESPACE`.
One situation in which we can throw an error when updating this namespace is when a job namespace has a future-scheduled run using a node which we are trying to remove in the MASTER config -- we find no issues with the new MASTER config on its own, so we attempt to update the configuration. However, upon trying to apply the new configuration to the tron [MasterControlProgram](https://github.com/Yelp/Tron/blob/master/tron/mcp.py#L47-L54), we will throw the error since the job configuration (whose namespace has not been modified) is no longer valid. 
While we were properly tracking exceptions when updating service namespaces, we were not doing so for the MASTER namespace, which meant …
> TRON-1968: Catch exceptions when updaitng MASTER config

- paasta_tools/cli/cmds/check.py
- tests/cli/test_cmds_check.py
Since we added `parallel` step support to `deploy.yaml`, `paasta check` has been complaining about pipelines that run the `security-check` in parallel with anything else (which is actually what we provide as a default nowadays!).
This updates `paasta check` to now also look at parallel steps to verify we have a security-check step, along with a test to verify.
> COMPINFRA-2938: Support security-check in parallel steps

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- Makefile
- debian/rules
- general_itests/fake_simple_service/Dockerfile
- general_itests/fake_simple_service/Makefile
- requirements-bootstrap.txt
- tox.ini
- yelp_package/Makefile
- yelp_package/dockerfiles/bionic/Dockerfile
- yelp_package/dockerfiles/gitremote/Dockerfile
- yelp_package/dockerfiles/hacheck-sidecar/Dockerfile
- yelp_package/dockerfiles/itest/api/Dockerfile
- yelp_package/dockerfiles/itest/hacheck/Dockerfile
- yelp_package/dockerfiles/itest/httpdrain/Dockerfile
- yelp_package/dockerfiles/itest/k8s/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/itest/zookeeper/Dockerfile
- yelp_package/dockerfiles/jammy/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/playground/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
- yelp_package/extra_requirements_yelp.txt
Internal ticket: CORESERV-12777
The general idea is to (1) remove pip-custom-platform, (2) stop hard-coding the PyPI registry URL in places where it's possible, and (3) hard-code the platformed registry at least if we have to.
We set the registry URL globally in `/etc/pip.conf` on Yelp hosts and inside Yelp's Docker images, so we should be able to get away with not specifying it in most locations. This also allows us to take advantage of the platform-specific registries which no longer need pip-custom-platform. Unfortunately it is not so easy to rely on this for many of the Docker images so I had to hard-code the platform-specific registry.
Same idea as https://github.com/Yelp/Tron/pull/921.
Passed locally on a yelpcorp host:
> Don't hard-code legacy yelpcorp PyPI registry, remove pip-custom-platform

- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/tron_tools.py
All this is needed for this to work in paasta local-run is to add it to adhoc_schema.json, conveniant!
Tested locally here: https://yelp.slack.com/archives/C048HCBDD0U/p1690896906993479
I also included a patch about a KeyError because it was trying to grab a non-existent optional key.
> SEC-18177: Enable secret_volumes in adhoc jobs

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
We may make a different cluster for spark in dev, but we don't really want to deal with a soaconfigs migration in case we decide to rollback
This PR transparently sets the right eks cluster params based on whether or not eks usage is toggled on or off
> Add support for eks cluster not matching --cluster spark arg

- .gitignore
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
Currently the default limits/request of the hacheck, uwsgi containers is huge for a sidecar containers.
making these configuration configurable.
for now I have set the default limit as same as the current limit.
> make sidecar resource limit configurable

- paasta_tools/utils.py
Missing port number here. This needs to match the tag exactly: https://github.com/Yelp/paasta/blob/master/yelp_package/dockerfiles/gunicorn_exporter-sidecar/Makefile#L5
> Fix `gunicorn_exporter_sidecar_image_url`

- requirements-minimal.txt
This most often pops up as folks unable to use paasta validate when they have the soaconfigs venv activated as pip will grab the latest kubernetes version available - which is not guaranteed to work with our code in paasta.
> Add kubernetes upper-bound for things using paasta as a library

- k8s_itests/deployments/kind/cluster-devbox.yaml
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/secret_providers/__init__.py
- paasta_tools/secret_providers/vault.py
- paasta_tools/utils.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
- tests/test_kubernetes_tools.py
https://fluffy.yelpcorp.com/i/67hDPrWrG31CtcZRZf0RB17HqJg8XqXZ.html
Pasting in fluffy for security reasons
(updated Aug 9, 2023 @ 1:46pm)
> Introduced new soa key for rotating database passwords

- paasta_tools/eks_tools.py
- tests/test_eks_tools.py
I'm reusing the same config Dict ``KubernetesDeploymentConfigDict`` for ``EksDeploymentConfig`` as we want this class to be similar to ``KubernetesDeploymentConfig``
unit tests for eks_tools.py
> Creating an instance type class for EKS - PAASTA-17991

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
To mainly include the following changes:
* Assign spark.app.id to a more intuitive name
* Pick spark ui port with preference
* Temporary adding `--add-id` argument for explicitly specifying spark.app.id when anything goes wrong
Full list: https://github.com/Yelp/service_configuration_lib/compare/v2.18.0...v2.18.6
```bash
. ./.tox/py38-linux/bin/activate
paasta spark-run --aws-credentials-yaml=/etc/boto_cfg/mrjob.yaml --cmd "spark-submit /work/integration_tests/s3.py"
```
Spark UI:  
With `--app-id` provided:
> Bump service-configuration-lib to v2.18.6

- general_itests/fake_soa_configs/fake_deployments_json_service/eks-test-cluster.yaml
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_validate.py
This PR checks for EKS instance types wherever we check for Kubernetes instance types. Since eks_schema.json is a symbolic link to kubernetes_schema.json, I had to override in ``def get_schema(file_type)`` the eks file_type since eks_schema.json doesn't actually exist so we get none 
- Adjusting the unit tests to account for "eks"
> Update paasta validate to use eks instance type where necessary - PAASTA-17992

- paasta_tools/utils.py
- tests/test_list_kubernetes_service_instances.py
- tests/test_utils.py
This PR adds "eks" to the list of instance_types which allows us when running paasta_list_kubernetes_service_instances to specify "-t eks". This only spit out eks instances "eks-clustername.yaml" in soaconfigs.
Tested on paasta playground. I added an ``eks-kind-emanelsabban-k8s-test.yaml`` file with two instances in playground soa configs and ran ``paasta_list_kubernetes_service_instances -t eks -c kind-${env:USER}-k8s-test -d ./soa_config_playground`` I got back the two instances in this yaml file:
```
(py38-linux) emanelsabban@dev208-uswest1adevc:~/pg/paasta$  cd /nail/home/emanelsabban/pg/paasta ; /usr/bin/env /nail/home/emanelsabban/pg/paasta/.tox/py38-linux/bin/python /nail/home/emanelsabban/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/.. …
```
> Update paasta_list_kubernetes_service_instances to show only eks instances when specified - PAASTA-17986

- yelp_package/Makefile
See https://github.com/orgs/community/discussions/65227 - it appears that GH is doing something that is breaking wget's automatic cipher selection.
From wget's docs:
> If ‘auto’ is used, the SSL library is given the liberty of choosing
> the appropriate protocol automatically, which is achieved by
> sending a TLSv1 greeting. This is the default
I assume that this means that GH is blocking the TLSv1 greeting in an unexpected way, thereby breaking wget.
> Explictly set wget cipher suite

- paasta_tools/cli/schemas/kubernetes_schema.json
Add active-requests to the kubernetes schema. The use of `active-requests` in example happyhour scaling config was failing. https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/34128
```
+ git checkout sclg/COREJAVA-869/enable_active_requests_autoscaling_ehh_stagef
Already on 'sclg/COREJAVA-869/enable_active_requests_autoscaling_ehh_stagef'
Your branch is ahead of 'origin/sclg/COREJAVA-869/enable_active_requests_autoscaling_ehh_stagef' by 17 commits.
(use "git push" to publish your local commits)
+ /usr/bin/yelpsoa-configs-checker
example_happyhour_java
✓ Successfully validated schema: kubernetes-everywhere-testopia.yaml
✓ Successfully validated schema: kubernetes-norcal-devc.yaml
✓ Successfully validated schema: kubernetes-norcal-stageg.yaml
✓ Successfully validated schema: …
```
> [COREJAVA-869] Add active requests to kubernetes schema

- paasta_tools/check_kubernetes_services_replication.py
- paasta_tools/check_services_replication_tools.py
This PR adds a flag ``--eks``, if set then we pass in ``EksDeploymentConfig`` class.
Tried running ``check_kubernetes_services_replication`` on the Kind cluster using the ``eks`` flag and ``eks-kind-emanelsabban-k8s-test`` in soaconfigs with two instances: ``eks-autoscaling`` and ``eks-new_instance_test``. Result
```
(py38-linux) emanelsabban@dev208-uswest1adevc:~/pg/paasta$  cd /nail/home/emanelsabban/pg/paasta ; /usr/bin/env /nail/home/emanelsabban/pg/paasta/.tox/py38-linux/bin/python /nail/home/emanelsabban/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 56691 -- -m paasta_tools.check_kubernetes_services_replication -d ./soa_config_playground --eks compute-infra-test-service.eks-autoscaling …
```
> Update check_kubernetes_services_replication to have an optional --eks flag - PAASTA-17989

- paasta_tools/spark_tools.py
- tests/test_spark_tools.py
- Updated Spark volume names regex to match alphanumeric names. 
- Also failing with an error message if the name is incorrect.
According to K8s documentation:
```
Volume names must be - a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```
So I am replacing the regex to be the same.
Testing with failed and successful runs:
https://fluffy.yelpcorp.com/i/KGd5qFPK9fW3SSHPQXpHZPBXf5b7Md52.html
> MLCOMPUTE-1008 | update regex for Spark volume names to be alphanumeric

- .gitignore
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Ticket: PAASTA-18017
This fixes the issue of secret usage when the "service: something" override is used.
Test simply confirms that service name while decrypting is based on the instance_config service name, not the service name given by the CLI args
tested on dev6:
test action (did not use private.py since there is no devc version): https://fluffy.yelpcorp.com/i/lK6F4r99Sm0sHmjWhHNS3BdC2tdBVdvv.html
result: https://fluffy.yelpcorp.com/i/XBRnjNSccFTMpr5kvrkr0g7zGmqgCLCw.html
> PAASTA-18017: Read secret where instance service is defined, rather than service defined in CLI args.

- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/autoscale.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/mesh_status.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/utils.py
- tests/api/test_autoscaler.py
- tests/api/test_instance.py
- tests/cli/test_cmds_autoscale.py
- tests/cli/test_cmds_mesh_status.py
We do a tiny bit of lying here in order to keep the same paasta cluster name in the soaconfigs filenames (and CLI), but introduce the concept of an api cluster so that we can direct queries for things running from eks-* files to the correct PaaSTA API
This has somewhat been tested on my local PaaSTA playground and I've added some unit tests :)
> Add API support for paasta <CMD>ing eks-* instances

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
We added the option for explicitly specifying Spark app id in #3682 as a safety measure for rolling out the new app id naming convention.
Now the new naming convention has been fully rolled out without any problem and no one is currently using the option. So I'm going to remove the option to cleanup the logic and avoid problems caused by user explicitly set the id.
> MLCOMPUTE-746 | Remove the spark app-id option

- paasta_tools/setup_prometheus_adapter_config.py
Add the kube_deployment label to envoy metrics aggregation
COREJAVA-888
[Tested the query in grafana.](https://grafana.yelpcorp.com/explore?orgId=1&left=%7B%22datasource%22:%22P0A14DA14C82905AE%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22avg_over_time%28%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20sum%28%5Cn%20%20%20%20%20%20%20%20label_replace%28avg%28%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20paasta_instance:envoy_cluster__egress_cluster_upstream_rq_active%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20paasta_cluster%3D%27norcal-stagef%27,%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20paasta_service%3D%27example_happyhour_java%27,%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20paasta_instance%3D%27main%27%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20 …
> [COREJAVA-888] Add kube deployment label to envoy metrics aggregation

- paasta_tools/setup_prometheus_adapter_config.py
Avoid using label_replace in series query. 
Using promql within the query would fail the metrics discovery.
```
curl 'http://thanoslocal-compute-infra-hpa-infrastage.discovery:9090/api/v1/series?match%5B%5D=label_replace%28label_replace%28paasta_instance%3Aenvoy_cluster__egress_cluster_upstream_rq_active%7Bpaasta_cluster%3D%27infrastage%27%2Cpaasta_service%3D%27example_happyhour_java%27%2Cpaasta_instance%3D%27main%27%7D%2C%27kube_deployment%27%2C+%27example--happyhour--java-main%27%2C+%27%27%2C+%27%27%29%2C%27kube_namespace%27%2C+%27paastasvc-example--happyhour--java%27%2C+%27%27%2C+%27%27%29&start=16946'
{"status":"error","errorType":"bad_data","error":"1:14: parse error: unexpected \"(\""}
```
Tested manually by replacing the query in stagef and load testing on example_happhour_java. …
> [COREJAVA-897] Avoid using label_replace in series query

- paasta_tools/cleanup_kubernetes_jobs.py
- tests/test_cleanup_kubernetes_jobs.py
This PR adds the ``--eks`` flag which will allow us to load the eks instance type instead of the kubernetes instance type when used
- Modified the unit tests to account for the flag
- Manually tested cleanup kubernetes job on paasta playground:
1. without the usage of the ``--eks`` flag and the usage of ``--force`` flag:
```
emanelsabban@dev208-uswest1adevc:~$ kubectl --context kind-emanelsabban-k8s-test --kubeconfig /nail/home/emanelsabban/pg/paasta/k8s_itests/kubeconfig get pods -A
NAMESPACE            NAME                                                              READY   STATUS        RESTARTS   AGE
eks-autoscaling      compute-infra-test-service-eks-autoscaling-6545db6bfb-4sk94       1/1     Terminating   0          4d4h
eks-autoscaling …
```
> Add eks support for cleanup kubernetes job - PAASTA-17988

- paasta_tools/setup_prometheus_adapter_config.py
As the metric from envoy is already aggregated for us, there would only ever be a single data point for the metric. 
When we try to calculate the missing instances we do `{ready_pods} - count({load_per_instance}) by (kube_deployment),`
So, the missing instance count, will always be `{ready_pods} - 1` as there is only a single data point and the count would always be 1. This tells the HPA that there is data only from a single pod. 
When calculating the total load, we are almost doubling it as we think there is only data coming from 1 pod and we try to worst case estimate that every pod is at full capacity.
This change will remove any calculations around missing instances as we cannot figure that out with the data within the HPA as we record aggregated metrics already. so we only have a …
> [COREJAVA-901] Remove calculation of missing instances as it can't be calculated with data in HPA

- paasta_tools/config_utils.py
- tests/test_config_utils.py
We have started generating autotuned_defaults for the cassandra_k8s service. However, autotuned configs generation is failing (search for `cassandra-paasta-autotune` in y/jenkins) while validating the filenames.
```
[2023-09-13T10:55:24.220Z] ERROR:paasta_tools.config_utils:Files failed validation, not committing changes
[2023-09-13T10:55:24.521Z] Traceback (most recent call last):
[2023-09-13T10:55:24.521Z]   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2023-09-13T10:55:24.521Z]     return _run_code(code, main_globals, None,
[2023-09-13T10:55:24.521Z]   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[2023-09-13T10:55:24.521Z]     exec(code, run_globals)
[2023-09-13T10:55:24.521Z]   File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/c …
```
> COMPINFRA-3079: Add cassandracluster to known autotuned config types

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Added a pass through argument for docker run --shm-size to the spark-run command. Allows the user to set a value for `docker run --shm-size` via `paasta spark-run` using the `--docker-shm-size` option.
> Added --docker-shm-size for spark-run

- paasta_tools/cli/schemas/autotuned_defaults/cassandracluster_schema.json
Follow-up to https://github.com/Yelp/paasta/pull/3703
`rightsizer_soaconfigs_update` is failing for Cassandra autotune recs because validation doesn't pass.
```
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/config_utils.py", line 244, in commit_to_remote
raise ValidationError
paasta_tools.config_utils.ValidationError
```
followed by
```
Failed to find schema to validate against.
```
The JSON schema file is not available for Cassandra CRD spec in the autotune directory `paasta_tools/cli/schemas/autotuned_defaults/` https://github.com/Yelp/paasta/blob/32c4cb7d310a5e174c7b3f120505f04f89adb9aa/paasta_tools/cli/cmds/validate.py#L165-L175
I've added a spec similar to `kubernetes_schema.json`. The format for sidecar resource spec is slightly different, I'm omitting it as …
> COMPINFRA-3079: Add cassandracluster crd autotune spec schema

- paasta_tools/cli/cmds/status.py
We haven't used SFX for autoscaling in quite some time and this confuses people that see it referenced in the output of `paasta status`
At some point we'll want to replace this with a dashboard that visualizes how the Prometheus-based autoscaling works - but that's for future-us to do :)
> Remove sfx autoscaling link

- .github/workflows/ci.yml
This will have two side effects:
1) it'll be easier to find what failed (rather than having to wade
through an ocean of python setup logs)
2) hopefully make things faster since we'll do all these tests in
parallel.
> Run tox envs in parallel in GHA tests

- paasta_tools/contrib/rightsizer_soaconfigs_update.py
At the moment, the script raises an exception when trying to extract `disk` values from cassandracluster recommendation values:
```
$ /opt/venvs/paasta-tools/bin/python ./paasta_tools/contrib/rightsizer_soaconfigs_update.py --csv-report cassandra_paasta_rightsizer_disk_recs.csv --csv-key disk --splunk-creds **** --source-id fake-source-id --app yelp_dre --local-dir=~/pg/sysgit/yelpsoa-configs
INFO:root:Found services to rightsize
File "./paasta_tools/contrib/rightsizer_soaconfigs_update.py", line 254, in <module>
main(args)
File "./paasta_tools/contrib/rightsizer_soaconfigs_update.py", line 213, in main
results = get_recommendations_by_service_file(
File "./paasta_tools/contrib/rightsizer_soaconfigs_update.py", line 192, in …
```
> Create new function for getting cassandracluster result values

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/utils.py
- tests/cli/test_cmds_validate.py
Since we removed kiam from our environments, we can stop supporting it and set the default of `iam_role_provider` to be `aws` now (similar to how this is already configured for tron)
In addition, that means iam_role must always be an AWS IAM role ARN, which has some very specific structure.
This applies the valid patterns per [aws's docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-names) and adds some minor tests to check a few different cases
> Validate iam_role and stop supporting kiam

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
IAM role names are allowed to include uppercase letters, but we used the exact iam_role name when we created the associated serviceaccounts, which do *not* allow uppercase letters, which resulted in 
```
Invalid value: "..." a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?
```
This change simply uses the lowercased version of iam_role in the normalized version used to generate the serviceaccount name, while still preserving the casing in the annotation as necessary for pod identity to work.
tests w/ the playground also confirmed that specifing an iam_role with capitalized letters resulted in a valid …
> Support uppercase IAM role names

- paasta_tools/setup_prometheus_adapter_config.py
- tests/test_setup_prometheus_adapter_config.py
This is purely refactor PR to setup passing of instance_config to all scaling rules methods. 
The instance_config will be used later in `create_instance_active_requests_scaling_rule` to read registrations configured in yelpsoa configs. 
Updated the unit tests.
COREJAVA-995
> [COREJAVA-995] Refactor to pass instance_config to all scaling rules

- paasta_tools/cli/cmds/validate.py
- paasta_tools/setup_prometheus_adapter_config.py
- tests/cli/test_cmds_validate.py
- tests/test_setup_prometheus_adapter_config.py
If any services uses registrations and there is exactly one registration, in the active-requests scaler, use the registration name instead of paasta instance name in the metrics query as envoy tracks metrics at smartstack level.
ex - For language models - they have a custom registration - https://github.yelpcorp.com/sysgit/yelpsoa-configs/blob/master/language_models/kubernetes-pnw-prod.yaml#L13 .. hence the envoy metrics are tracked with the registration name.  
```
paasta_instance:envoy_cluster__egress_cluster_upstream_rq_active{paasta_cluster='pnw-prod',paasta_service='language_models',paasta_instance='main'}
vs
paasta_instance:envoy_cluster__egress_cluster_upstream_rq_active{paasta_cluster='pnw-prod',paasta_service='language_models',paasta_instance='main_uswest2'} 
```
Added unit …
> [COREJAVA-998] Use registration name for paasta_instance name if a single custom registration is used

- paasta_tools/setup_prometheus_adapter_config.py
Same as with secrets, we could just do this for the set of things that are only on EKS OR self-managed k8s - but it doesn't seem worth the effort and will make it easier to flip back and forth between the two
(same as with the secrets PR - I need to run this on kubestage, but I'm pretty confident this is fine :))
> Sync autoscaling rules for EKS instances

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
We could also teach this to only sync secrets for self-managed OR EKS clusters individually - but that seems like more effort (and there's no real harm to syncing these to both: in fact, it makes rolling back even easier since there's no need to wait for secrets to re-sync)
> Sync paasta secrets for eks instances as well

- Makefile
- paasta_tools/cli/cmds/secret.py
- paasta_tools/delete_kubernetes_deployments.py
- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- tests/cli/test_cmds_secret.py
- tests/kubernetes/application/test_controller_wrapper.py
- tests/metrics/test_metastatus_lib.py
- tests/test_cleanup_kubernetes_jobs.py
- tests/test_delete_kubernetes_deployments.py
- tests/test_kubernetes_tools.py
Incidentally, I spotted and fixed a bug in `paasta secret decrypt` where it wasn't passing the correct arguments to `get_secret` in certain situations.
Since `paasta` is no longer a reasonable default value for namespace, I deleted that default value for all the functions I could find that take namespace as an argument.
> Change the default k8s namespace for kubernetes services.

- paasta_tools/utils.py
- tests/test_utils.py
For some instance types that are autotuned (e.g., `kubernetes`), we may
have a largely-similar instance type (e.g., `eks`) and the ability to
trivially move instances back and forth between these.
For these, there's a couple different options for how to handle
autotune:
1) have tooling/documentation to migrate data between
`autotuned_defaults/` files on instance moves + teach the autotune
machinery what the correct cluster/filename to update should be (as
well as teach autotune how to gather data correctly)
2) have tooling/documentation to temporarily pin the new instance type at
the old autotuned request until autotune has updated with the new
instance type data
3) add some form of aliasing and pretend (at the autotune level) that
there's a single instance type for these largely-similar …
> Add support for autotuned type aliases

- paasta_tools/cli/cmds/local_run.py
When running `paasta local-run` in unprivileged containers mode, `docker_client.attach` would cause paasta to crash with
```
Your service is now running! Tailing stdout and stderr:
Exception in thread Thread-1:
File "/usr/lib/python3.8/http/client.py", line 556, in _get_chunk_left
chunk_left = self._read_next_chunk_size()
File "/usr/lib/python3.8/http/client.py", line 523, in _read_next_chunk_size
return int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
File "/usr/lib/python3.8/http/client.py", line 588, in _readinto_chunked
chunk_left = self._get_chunk_left()
File "/usr/lib/python3.8/http/client.py", line 558, in _get_chunk_left …
```
> Use docker_client.logs instead of docker_client.attach during paasta local-run

- paasta_tools/config_utils.py
- tests/test_config_utils.py
When specifying branch name with `--branch`, first time we push succeeds, however, the second time it will fail, because the remote branch (from the first run) is based on a different commit than the new branch (from the second run):
```
+ ./.tox/py38-linux/bin/python ./paasta_tools/contrib/rightsizer_soaconfigs_update.py --csv-report sina_all.csv --splunk-creds xxxx --source-id fake-source-id --app yelp_dre --branch sina/test-cassandra-autotune -v --push-to-remote
INFO:root:Found 5 services to rightsize
Cloning into '/nail/tmp/tmp9lyrzip5'...
remote: Enumerating objects: 3861161, done.
remote: Counting objects: 100% (2129/2129), done.
remote: Compressing objects: 100% (359/359), done.
remote: Total 3861161 (delta 1828), reused 1992 (delta 1769), pack-reused 3859032
Receiving objects: …
```
> DREIMP-10150: Base new commits on remote branch, if it exists

- requirements-minimal.txt
- requirements.txt
To include changes from https://github.com/Yelp/service_configuration_lib/pull/132.
Test by running paasta spark-run locally:
```bash
paasta spark-run --aws-profile=dev --cmd "spark-submit /work/integration_tests/s3.py"
```
> Bump service-configuration-lib to v2.18.9

- paasta_tools/cli/cmds/spark_run.py
In #3728 we changed the `--docker_registry`'s default value from our `DEFAULT_SPARK_DOCKER_REGISTRY` and instead leave it undefined by default.
However, we still used `args.docker_registry` in our check whehter we needed sudo to push ot this registry, rather than using the generated `registry_uri`, which caused all runs with `--build` to try to sudo to push the registry, which doesn't work w/ the default registry.
This fixes to use our new registry_uri which should be either the requested docker_registry or the service's default, to get back to the normal behavior.
> Use the correct registry_uri to check if we need to sudo

- .gitignore
- Makefile
- paasta_tools/contrib/create_paasta_playground.py
- paasta_tools/contrib/render_template.py
- requirements-dev-minimal.txt
- requirements-dev.txt
- added paasta-cronjobs make target
- setup-kubernetes-job
- cleanup-kubernetes-job
- paasta-secrets-sync
- generate_deployments_for_service
- added VSCode debugpy as dev requirement
- made paasta playground not overrwrite existing paasta confs or yelpsoa-configs
> Improvements to PaaSTA Playground

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Adding LimitRanges for PaaSTA managed namespaces with `ensure_namespace()`
> Adding LimitRanges for paasta managed namespaces

- paasta_tools/cleanup_kubernetes_jobs.py
- paasta_tools/setup_kubernetes_job.py
- tests/test_setup_kubernetes_job.py
making `setup_kubernetes_jobs.py` and `cleanup_kubernetes_jobs.py` aware of "_downthenup_" instance types bounces across namespaces
> making skj and ckj aware of downthenup bounces across namespaces

- docs/source/yelpsoa_configs.rst
- paasta_tools/check_services_replication_tools.py
- paasta_tools/cli/schemas/kubernetes_schema.json
Remove the restriction that namespaces must start with paastasvc-, and remove the same assumption from check_services_replication_tools.py
> Allow non-paastasvc namespaces

- paasta_tools/api/views/instance.py
- paasta_tools/instance/kubernetes.py
- tests/api/test_instance.py
Currently, paasta_tools.instance.kubernetes.bounce_status  is the only thing we should be currently using that depends on [get_kubernetes_app_by_name](https://github.com/Yelp/paasta/blob/master/paasta_tools/kubernetes_tools.py#L3443-L3458) .  The other uses were in 'old' paasta status and no longer used.
This function attempted to fetch the k8s resource tied to a service+instance in a cluster, naively attempting to get a statefulset if the deployment wasn't found. This is left to raise the k8s ApiException giving us a 404 when it can't find the statefulset either.  In most situations, this should work fine, as the k8s resource is pretty much guaranteed by the time we hit this call, since the configs that would lead to that resource being created are also required to make it this far in …
> Catch statefulset missing as 404 in API bounce_status

- paasta_tools/kubernetes_tools.py
This should prevent surprises where someone puts a paasta service into an operator's namespace and all of the sudden there's a LimitRange affecting all their pods.
https://jira.yelpcorp.com/browse/PAASTA-18105
> Only manage LimitRanges in paastasvc-* namespaces

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
We're currently getting the error
```
File "/usr/bin/paasta_secrets_sync", line 732, in <module>
main()
File "/usr/bin/paasta_secrets_sync", line 163, in main
get_services_to_k8s_namespaces_to_allowlist(
File "/usr/bin/paasta_secrets_sync", line 262, in get_services_to_k8s_namespaces_to_allowlist
INSTANCE_TYPE_TO_K8S_NAMESPACE[instance_type]
KeyError: 'eks'
```
This is because we generally handle paasta k8s instance types in the block above, where we are able to infer the desired namespace from the instance config, and only intend to store non-paasta mappings from instance types to their single namespaces in `INSTANCE_TYPE_TO_K8S_NAMESPACE`. 
This updates this code to check all paasta k8s instance types (currently only `kubernetes`+`eks`)
> Fix paasta secrets sync namespace checking for eks instances

- paasta_tools/cli/schemas/kubernetes_schema.json
- tests/cli/test_cmds_validate.py
We've had a couple of instances where folks have put in an invalid namespace in soaconfigs - this will block that from happening whenever folks run `paasta validate` locally or when the integration pipeline does so.
> Add validation for namespaces in `paasta validate`

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
It looks like we added a new condition with the intent that we would start to rollback if any SLO or new generic 'rollback metric' started to fail.
However, a valid transition's `conditions` must *all* be true to enable the transition.  As we don't yet have any services using metric rollbacks, a service would likely only ever be failing SLOs (`any_slo_failing`) but not ever failing rollback metrics (`any_metric_failing`). 
This replaces the two separate any_*_failing conditions with the new `any_rollback_condition_failing` method which applies the intended logic already of returning true if either any_slo_failing or any_metric_failing: https://github.com/Yelp/sticht/blob/master/sticht/rollbacks/base.py#L245-L246 
This was preventing the "Disable auto-rollbacks" button to be displayed as …
> Fix conditions for displaying disable auto rollbacks button

- paasta_tools/paasta_execute_docker_command.py
- tests/test_paasta_execute_docker_command.py
From [reading Podman's implementation of this API](https://github.com/containers/podman/blob/v3.4.4/libpod/container_exec.go#L253-L255), it will just refuse to start any exec which is not in status=created, so reusing an existing one that already completed is just not a supported behaviour.
> do not reuse execs with podman

- paasta_tools/cli/cmds/spark_run.py
Applied when arguments are provided [https://github.com/Yelp/paasta/blob/08c14d329080a0ef8ce29a7a26ac29b022446c06/paasta_tools/cli/cmds/spark_run.py#L702] requires a fix that can go into other prs and potentially not needed when driver is on k8s
> MLCOMPUTE-1035 Update dnsPolicy

- .readthedocs.yaml
- requirements-docs.txt
RTD changed things a few months back and now require a new v2 config file: https://docs.readthedocs.io/en/stable/config-file/v2.html
This adds the new file and fixes a jinja dependency issue in requirements-docs.txt for py3.8; we need to stay <3.1 per https://github.com/readthedocs/readthedocs.org/issues/9038 
We should review the requirements, this may be instead improved by a bump to many of the other requirements-docs but this just gets builds passing again as a first step. 
verified in a personal rtd instance https://readthedocs.org/projects/test-jfong-project/builds/22496330/
> Add readthedocs v2 config file, update to py38, and fix requirements

- debian/paasta-tools.links
This makes sure our new `check_autoscaler_max_instances` script  from #3747  is available in our standard PATHs like our other system scripts
Upon building the new deb & installing on a test box, I can see the symlink is created appropriately:
```
$ sudo dpkg -i dist/paasta-tools_0.209.0-yelp1_amd64.deb
(Reading database ... 1664070 files and directories currently installed.)
Preparing to unpack .../paasta-tools_0.209.0-yelp1_amd64.deb ...
Unpacking paasta-tools (0.209.0-yelp1) over (0.209.0-yelp1) ...
ls -l /usr/bin/check_auto
Setting up paasta-tools (0.209.0-yelp1) ...
Successfully updated /opt/venvs/paasta-tools/bin/python3.8
$ ls -l /usr/bin/check_autoscaler_max_instances
lrwxrwxrwx 1 root root 61 Dec 14 15:55 /usr/bin/check_autoscaler_max_instances -> …
```
> Add missing symlink for check_autoscaler_max_instances

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
This removes the deprecated use_k8s flag now that we are fully on Kubernetes.
> PAASTA-18143: remove use_k8s deprecated flag

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/views/instance.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/api/service_api.py
We have nothing actually running smartstack so attempting to get that information in a paasta API call will fail.
While I wasn't brave enough to outright delete this code yet (it _may_ be useful to have this prior art to show how to toggle one mesh provider in mesh_status vs another?), let's at least set the default to False to prevent accidental uses which can clog the API logs with errors.
> Set include_smartstack default to False since we no longer support it

- paasta_tools/cli/cmds/validate.py
- paasta_tools/tron_tools.py
- tests/cli/test_cmds_validate.py
This is based on https://github.com/Yelp/paasta/pull/3753 but has an additional commit that speeds up paasta validate by about 3-4x by reducing the number of times we parse yaml or generate all the TronActionConfigs for an individual service.
> Optimize paasta validate

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Because of https://github.com/containers/podman/issues/14779, `docker push` has different behavior w.r.t. the local vs remote image digest value when run in privileged vs unprivileged mode. This was causing `paasta spark run` commands using `--build` to fail to allocate an executor node in unprivileged container mode because it was referring to an image digest that paasta couldn't find because it only exists on the devbox where `paasta spark run` is called.
Parse the message from the remote docker registry when running `docker push` during `paasta spark run --build` so that we always use the server version of the image digest as the source of truth.
Ran `paasta spark run` manually for both `--pull` and `--build` with this patch and confirmed the executor can be allocated and the jobs can …
> Always use docker registry server's digest information for pushed spark images

- debian/paasta-tools.links
- paasta_tools/contrib/habitat_fixer.py
- setup.py
We're seeing some weirdness with Karpenter where one of our custom labels (yelp.com/habitat) is sometimes being set as a random integer.
While we debug this, we have enough information to write a script to fix these.
> Add workaround script to fix habitat labels

- debian/paasta-tools.links
This is what I get for naming the file differently from the command - `paasta_habitat_fixer` does not work as bin/ does not contain a paasta_habitat_fixer.py
> Fix debian link

- paasta_tools/contrib/habitat_fixer.py
Turns out that I didn't read the admin kubeconf closely enough and missed that the context names there are prefixed with kubernetes-admin@
> Guess the correct context (or allow override) in paasta_habitat_fixer

- paasta_tools/cli/utils.py
While running `paasta mesh-status`, I was getting an odd error indicating that we were trying to get information for an EksInstance for an instance and cluster that should not have been running on EKS.
Turns out that this is due to us naively getting the first instance_config from the results of get_instance_configs_for_service, which was not honoring the `clusters` argument.
This change now starts to honor said clusters argument.
All uses of this function either did not pass the `clusters` arg (and therefore used the full list of supported clusters from system configs), or expected only a single instance and was impacted by this same bug.
No clusters arg:
* generate_deployments_for_service: https://github.com/Yelp/paasta/blob/master/paasta_tools/generate_deployments_for_service.py#L139 …
> Fix get_instance_configs_for_service to use cluster arg

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/mesh_status.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/api/service_api.py
- tests/api/test_instance.py
- tests/cli/test_cmds_status.py
- tests/instance/test_kubernetes.py
This removes the include_smartstack parameter everywhere and associated references in our code, since we no longer support it anywhere in our environment.
Since we deployed https://github.com/Yelp/paasta/pull/3752 , shipping this should now be safe as any clients that remove include_smartstack in their requests with this PR will still get `include_smartstack=false` on the server side (rather than attempt to collect smartstack information and throw an error).
> Remove include_smartstack

- paasta_tools/config_utils.py
- tests/test_config_utils.py
It's possible for a service to be in one of several states:
* 100% on Yelp-managed k8s
* 100% on AWS-managed k8s
* X% on Yelp-managed k8s and 100-X% on AWS-managed k8s
Everything is fine in the first case, but for the other two we need to make sure that we load the eks- files as we cannot actually rely on the instance_type_cluster from the autotune CSV as we "fake" the instance type there to always be kubernetes
For now, we'll basically try to load both types and merge the resulting configuration to get the current configs (which we need in order to clamp autotune values if there are user-configured limits)
> Load eks- and kubernetes- files in autotune merging

- paasta_tools/kubernetes_tools.py
There was a subtle bug in the original implementation where setting only a preferred node affinity would result in a required node affinity being created with an empty match_expressions - which in our infra does not match any nodes.
This patch ensures that we only created a required node affinity if there is actually one configured.
> Allow using preferred node affinity on its own

- docs/source/autoscaling.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
We now have a centralized uwsgi-exporter set up which is responsible for scraping all uwsgi-stats-enabled services. This unfortunately means we need to standardize on stats port 8889 and stop supporting custom ports, but more importantly means we no longer need to run the uwsgi sidecar for these services.
This PR:
1. stops deploying the uwsgi sidecar at all
2. removes uwsgi_stats_port from the schema and stops using it entirely
3. updates uwsgi autoscaling docs to remove wording about the sidecar + highlight we don't support custom stats port
This *will* cause a bounce for all uwsgi-autoscaled instances due to the `scrape_uwsgi_prometheus` label removal, and will stop deploying the uwsgi sidecar in all environments.  However this should be safe as we no longer configure any prometheus to …
> Stop using uwsgi sidecars and supporting custom stats port

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
Previously, using an invalid value here would cause the service to fail to launch. Now that we're migrating away from using AWS users, people mess this up more often, and it may be desirable to let the pod launch with placeholder values.
Placeholder values instead just ignoring them and not placing keys was much simpler to implement, and only very marginally less desirable IMO. 
We still get a log line that we can alert on when this happens.
> Add placeholder value for non-existent boto_keys

- docs/source/autoscaling.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
https://github.com/Yelp/paasta/pull/3775 take 2, this time I won't accidentally merge to master before I'm ready. 🤦 
We now have a centralized uwsgi-exporter set up which is responsible for scraping all uwsgi-stats-enabled services. This unfortunately means we need to standardize on stats port 8889 and stop supporting custom ports, but more importantly means we no longer need to run the uwsgi sidecar for these services.
This PR:
- stops deploying the uwsgi sidecar at all
- removes uwsgi_stats_port from the schema and stops using it entirely
- updates uwsgi autoscaling docs to remove wording about the sidecar + highlight we don't support custom stats port
This _will_ cause a bounce for all uwsgi-autoscaled instances due to the `scrape_uwsgi_prometheus` label removal, and will stop …
> Stop using uwsgi sidecars and supporting custom stats port (Again)

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
This placeholder text was not previously base64 encoded, which resulted in a 400 error from the Kube api when trying to add it as a secret. This should resolve that issue by doing the encoding first.
> Base64 encode the boto_key missing error placeholder text

- paasta_tools/secret_tools.py
Tron and Kubernetes yelpsoa-configs parsing return different representations for secret volumes that don't have `items` explicitly defined:
kubernetes:
```
(Pdb) secret_volume
{'container_path': '/nail/tls/keystore', 'secret_name': 'cassandra_apis-ubis-tls-keystore'}
```
tron:
```
(Pdb) secret_volume
{'secret_volume_name': 'tron-secret-conversion--feed-google--conversion--api--refresh--token', 'secret_name': 'google_conversion_api_refresh_token', 'container_path': '/conversion_feed/secret.txt', 'items': []}
```
Because of this, `paasta local-run` was not working correctly with the status quo code for tron jobs that didn't have items explicitly configured
Instead of checking for the presence of the property, just use `.get` to check for truthyness
Verified via a local-run with the patch …
> Fix for secret_volumes differences in tron vs k8s

- requirements-dev.txt
- requirements.txt
Ticket: [SEC-18515](https://jira.yelpcorp.com/browse/SEC-18515)
Current boto3 version cannot use IMDSv2, let's fix that to be closer to IMDSv2 adoption.
Bumped using `pip install boto3 -U` and copying changes in requirements.txt
> SEC-18515: Bump boto3 to enable IMDSv2 usage

- paasta_tools/setup_prometheus_adapter_config.py
Currently, this script iterates over all `kubernetes` instance types only and adds them to the paasta cluster's `adapter-config`. 
This means it is skipping any rules needed for `eks` instance types.
This change also adds rules for `eks` types for a cluster.  This does mean the adapter configs in both non-EKS and EKS clusters will include rules for instances that may not be running in the local cluster, but this should not cause any issues. 
Validated in eks-infrastage and infrastage to generate the correct rules; infrastage is running example_happyhour_java.main (odd it is using uwsgi autoscaling!), while eks-infrastage is running example_happyhour.testing, and running the new version in both clusters generated the adapter-config listing both rules.
> Include both kubernetes and eks instances in prometheus adapter config

- paasta_tools/cli/cmds/status.py
This change will print out whether or not the cluster is running on EKS when invoking PaaSTA status.
Tested locally with a service already migrated onto EKS.
```
sessions.main in norcal-stageg (EKS)
Version:    7e8b2bd3 (desired)
State: Running
Running versions:
Rerun with -v to see all replicas
7e8b2bd3 - Started 2024-01-29 13:26:10 (18 hours ago)
Replica States: 3 Healthy
```
> PAASTA-18171: Displays EKS in PaaSTA Status output

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We've encountered a couple of requests to allow the use of local-run within a kubernetes pod, and to have the pod identity be passed through from parent to child container. This change causes paasta local-run to detect a web identity token, assume into the relevant role, and launch the container with that session.
Manual test here: https://fluffy.yelpcorp.com/i/fR178F7KH9Sf7Cs1FT7s2vF6507RX6SG.html
The existing behavior will remain when using any of the aws related command line options, but this will be used by default if the env variables are present. You could override this behavior by running something like `env -u AWS_WEB_IDENTITY_TOKEN_FILE paasta local-run ...`, so I didn't see the need to add another argument to do that.
This resolves the internal jira ticket SEC-18598
> allow local-run to use currently set pod identity

- tox.ini
Unfortunately, not every package on public PyPI has wheels like we generally enforce internally.
Rather than figure out what we need available to be able to install cryptography in GHA, I figured we could pin for now since this only affects k8s_itests and I presume that in the near-ish future we'll probably figure out a way to migrate our open-source stuff to Poetry/de-tox things and we can forget I ever wrote this screed.
> Downpin cryptography in k8s_itests to fix GHA build

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
- tests/conftest.py
* There are use cases when a `paasta local-run` runs with a prod role in dev environment [[thread](https://yelp.slack.com/archives/CA4N6NW93/p1706909725006629?thread_ts=1696617970.548759&cid=CA4N6NW93)]
* @danielpops suggested something simlilar https://github.com/Yelp/paasta/pull/3532#discussion_r1081774925 . That is mapping cluster (`-c`) to the account.
Expose the source AWS account as CLI-flag that is used for role assumption.
- Worked with `--assume-pod-identity` [[fluffy](https://fluffy.yelpcorp.com/i/mBMC27Lcm9tZpD54Lwg46Xdqz1hShR5t.html)]
- Worked with `--assume-role-arn` [[fluffy](https://fluffy.yelpcorp.com/i/XDxmSWVqmT6PKZ5fPscWVsRG3TQCfFGR.html)]
- Without `-a prod` running on dev you get AccessDenied as expected [[fluffy](https://fluffy.yelpcorp.com/i/sMVMlM6cNSfpzlC7JbG0SqCK8 …
> Expose AWS account for role assumption

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
At the moment, you cannot pre-create secrets on a new dual-name cluster since the namespaces for services will not yet have been created by setup_kubernetes_job (and they may not have been created by Flux yet either).
We can fix this by calling ensure_namespace() in the secret sync code - the caching we have on ensure_namespace()/get_all_namespaces() means that this *should* be pretty fast as it should be grabbing cached data most of the time.
> Call ensure_namespace() in paasta_secrets_sync

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Address edge case of using `spark-run` with registries with authentication gated by unix permissions.
> spark_run: fix pulling images from authenticated registries

- Makefile
- paasta_tools/contrib/check_manual_oapi_changes.sh
This fixes a change made with the unprivileged containers switch which causes openapi-codegen to fail. The full url is needed now to pull the image from the docker registry.
> Fixes local tests and openapi-codegen

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
To provide a way for users to test their Spark tronfig (driver on k8s) with the ad-hoc `paasta spark-run`.
This implementation just simply loads the yaml file and parse selected fields instead to using `tron_tools` to avoid tron-specific logic being included to the existing `paasta spark-run` and let user able to test simplified configs.
With tronfig`~/tmp/tron-spark-pnw-devc.yaml`
```
_role_template: &role_template
iam_role: arn:aws:iam::<account_id>:role/spark_test_role
iam_role_provider: aws
spark_driver_test_paasta_secrets:
schedule: "cron */30 * * * *"
deploy_group: dev.pnw
enabled: false
actions:
bash:
<<: *role_template
executor: spark
env:
ENV1: env1_value
SAMPLE_ENV: SECRET(classified_sample)
pool: batch
spark_args:
spark.kubernetes.executor.secretKeyRef.SAMPLE_ENV: …
```
> MLCOMPUTE-872 | Support driver on k8s config format for paasta spark-run

- paasta_tools/setup_prometheus_adapter_config.py
We had some surprising behavior recently where an autoscaled app was crashlooping and the HPA did not keep the desired scale as-is - we believe that this is due to a mismatch in how we calculate the value we send to k8s:
The existing PromQL divides by current replica to turn things into a utilization percentage such that when the HPA multiplies later on by the number of current replicas, we reach our target replicas.
However, the HPA will actually multiply by the number of ready replicas, leading to a mismatch.
> Scale with ready pods count rather current replicas for uwsgi

- paasta_tools/api/client.py
- paasta_tools/utils.py
- tests/cli/test_cmds_status.py
- tests/conftest.py
We've noticed that sometimes the paasta API can hang/get stuck and clients end up hanging indefinitely, this fix adds a default timeout to avoid this.
> PAASTA-18005: Add default timeout to paasta-api

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/utils.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
It turns out that the slowness here was due to our hardcoded .3s sleep - we're
now syncing a lot more secrets (and generally doing more work) because of our
namespace sharding, so this sleep ends up taking quite a bit of time.
We generally haven't had to throttle much (outside of Pod creation, but that's
generally due to other constraints: e.g., cluster autoscaling and whatnot), so
it's probably fine to remove this sleep entirely for the time being.
That said, in the interest of safety, I've made this delay configurable - so if
this ends up causing issues after release (or in the far future), we can easily
tweak the delay.
> Speed up secret syncing

- general_itests/steps/paasta_execute_docker_command.py
- tox.ini
{insert rant about behave tests here}
Our itests are currently pulling images from dockerhub - which is leading to itermittent failures due to ratelimiting.
We have our own internal registries with these images mirrored, so let's use those :)
> Use internal docker registry for itest

- paasta_tools/utils.py
As-is, the error message is not particularly clear as to what is wrong.
> Fix typo in validation error message

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Solves the usual issue with file permissions when interacting with mounted user directories.
May create new issues for whatever gets run inside the container which I still need to verify.
> spark-run: properly set user under unpriv containers

- paasta_tools/cli/cmds/spark_run.py
Since when running in an unprivileged container the user is set to root, its home directory would be `/root` by default.
To fix that, we for the HOME environment variable to the right location.
Testing:
```
$ python -m paasta_tools.cli.cli spark-run --image whatever:latest --cmd 'bash' --aws-profile=dev
....
root@dev5-uswest2adevc:/work# echo $HOME
/nail/home/mpiano
root@dev5-uswest2adevc:/work# cd
root@dev5-uswest2adevc:~# pwd
/nail/home/mpiano
root@dev5-uswest2adevc:~# ls -al | head
total 552
drwxr-xr-x   41 root   root     4096 Feb 22 13:50 .
drwxr-xr-x 1445 nobody nogroup 36864 Feb 21 10:14 ..
drwxr-xr-x    3 root   root     4096 Jan 18  2023 .ansible
drwx------    2 root   root     4096 Jan  5  2023 .aptitude
drwxr-xr-x    3 root   root     4096 Feb 14 13:07 .aws
-rw-------    1 root …
```
> spark-run: set home directory when using unpriv containers

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
I don't find it particularly helpful to have 4 different conditions end up with the same `Not Running` message, so I've distinguished between them. This should help with after-the-fact debugging in situations like https://jira.yelpcorp.com/browse/COMPINFRA-2270 where we just have `paasta status` / `paasta mark-for-deployment --wait-for-deployment` output.
> Split NOT_RUNNING state into different states for different underlying conditions.

- yelp_package/Makefile
We have rolled out unprivileged docker to dev boxes, which causes the following problems when building Debian packages:
1. Does not support resolving short image names
=> Error when running `docker pull "docker.io/yelp/paastatools_bionic_container"`.
2. Has a virtual in-container uid to system uid mapping.
=> The whole repository directory will be changed to a incorrect UID/GID, causing the build abort.
This PR fixes both issues during the build process.
`make -C yelp_package PAASTA_ENV=YELP package_bionic` in devbox.
> Support building Debian package with unprivileged docker

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
As we are deprecating Spark SignalFx dashboards.
Tested by running the following cmd:
```
./.tox/py38-linux/bin/paasta spark-run --aws-profile=dev --cmd "spark-submit /work/integration_tests/s3.py"
```
> Remove spark SignalFx dashboard URLs

- k8s_itests/Makefile
- k8s_itests/deployments/kind/resources/metrics-server/1.8+/metrics-apiservice.yaml
- k8s_itests/scripts/containerd_registry_setup.py
- paasta_tools/contrib/render_template.py
Rootless podman support for PaaSTA playground. This will need a [somewhat modern version of kind](https://github.com/Yelp/kind/pull/7) and k8s nodes >=1.22
> Rootless podman support for PaaSTA playground

- paasta_tools/check_flink_services_health.py
- paasta_tools/flink_tools.py
- paasta_tools/setup_kubernetes_cr.py
- tests/test_check_flink_services_health.py
- tests/test_flink_tools.py
- tests/test_setup_kubernetes_cr.py
in EKS clusters flink dashboard has a different URL. overiding this in EKS cluster.
added a new label 'paasta.yelp.com/eks' for CR objects to identify the eks clusters, which can be used 
also updated the check_flink_services_health check: it will use --eks flag to determine the eks environment
> Updated flink ingress for eks clusters

- paasta_tools/setup_tron_namespace.py
This isn't a user-facing script, so we really should just be using logger.exception() to be as verbose as possible when there's an error
> Correctly log setup_tron_namespace exceptions

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We'd like to create a Topology Spread Constraint (TSC) for Tron pods, but these don't have a unique label to identify them as Tron-launched pods - so we'll add a workload label for this purpose.
> Add workload label to Tron pods for TSC purposes

- paasta_tools/cleanup_kubernetes_crd.py
Open-source operators may need to have N CRDs created, which is not currently suppored by PaaSTA due to our current 1 CRD per file approach.
For teach cases, we tend to manage CRDs with Flux - but PaaSTA will clean these CRDs up since they're in a PaaSTA-managed namespace, but there's no record of them in soaconfigs.
> Allow skipping cleanup of tagged CRDs

- paasta_tools/setup_kubernetes_cr.py
- tests/test_setup_kubernetes_cr.py
This will only add "paasta.yelp.com/eks" label when true, otherwise operators fails to reconcile existing stateful sets and other immutable k8s objects
> removed default eks var in kubernetes_cr.py

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Looks like we've been setting `PAASTA_PORT` to the port used to bind docker to the container port.  This conflicts with what we specify in the [paasta contract](https://paasta.readthedocs.io/en/latest/about/contract.html#http-tcp-services) which says service owners should listen on `PAASTA_PORT` inside the container.
This switches to let the instance config's `get_env` set `PAASTA_PORT` which should match our expectations, especially as we are using container port in the docker `--publish` flag: https://github.com/Yelp/paasta/blob/master/paasta_tools/cli/cmds/local_run.py#L560-L561 +
https://github.com/Yelp/paasta/blob/master/paasta_tools/cli/cmds/local_run.py#L944
The switch to defer this work to the instance config's `get_env` also meant that for Kubernetes instances, we lose the …
> Fix PAASTA_PORT in local-run containers

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
PaaSTA is on a modern-enough version of the Python kubernetes client that we don't need to monkey-patch the HPA dict anymore.
- make test
cc @jfongatyelp
> stop monkey-patching the HPA object

- docs/source/autoscaling.rst
- paasta_tools/check_autoscaler_max_instances.py
Before we make this paging, I'd like to reduce the frequency of realerting, and make sure this shows up in docsearch if you search for `check_autoscaler_max_instances`.
> Minor improvements to check_autoscaler_max_instances

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
This should make the kube_horizontalpodautoscaler_labels metric from kube-state-metrics more useful.
> Add service/instance/managed labels to HPAs. PAASTA-18226

- paasta_tools/cli/schemas/deploy_schema.json
adding a new `service_account` field for `deploy.yaml` steps. this will allow us to configure service accounts for the step being run instead of for the entire pipeline
> add service_account field for deploy.yaml

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/long_running_service_tools.py
- tests/autoscaling/test_autoscaling_service_lib.py
Following up on https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/42719, this removes good_enough_window from paasta completely.
`make test` still passes
> remove good_enough_window

- paasta_tools/cli/cmds/spark_run.py
Default value is set here:
https://sourcegraph.com/github.com/Yelp/paasta@15799523e976a7e611342e9b9b8cadfffdd3406c/-/blob/paasta_tools/utils.py?L965
Same as #3798, but remove `iam_role_provider` in the provided Tronfig.
> Allow to use default value of iam_role_provider

- paasta_tools/cli/cmds/spark_run.py
Error when running `paasta spark-run --cluster-manager local ...`
```
$ paasta spark-run --aws-profile dev --cluster-manager local --cmd 'echo done'
...
docker: Error response from daemon: fill out specgen: host directory cannot be empty. 
```
This happens after a [recent refactor](https://github.com/Yelp/paasta/pull/3679/files#diff-30f8e9c33224158fab1e77efc4004f7d2344230ea7b4ffbf64b3fca21513cc00L1467-R1228) which makes `pod_template_path` be empty when `cluster-manager` is `local`.
```
./.tox/py38-linux/bin/paasta spark-run --aws-profile=dev --cluster-manager local --cmd 'echo done'
```
> Fix volume mount of spark-run on local cluster

- paasta_tools/tron_tools.py
To make pinpointing the problem config easier.
This script is run by the Tron master and also the `integration` command in yelpsoa-config by command `yelpsoa-configs-checker`.
Before this change:
```
$ ./.tox/py38-linux/bin/paasta check -y ~/projects/sysgit/yelpsoa-configs -s spark
...
paasta_tools.tron_tools.InvalidPoolError
```
After this change:
```
$ ./.tox/py38-linux/bin/paasta check -y ~/projects/sysgit/yelpsoa-configs -s spark
...
paasta_tools.tron_tools.InvalidPoolError: Job spark.paasta_secrets_integration_test_driver_k8s.run: pool 'default' is invalid for cluster 'pnw-devc-spark'
```
> Add detailed error message for tron InvalidPoolError

- docs/source/autoscaling.rst
- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/long_running_service_tools.py
- paasta_tools/setup_prometheus_adapter_config.py
- paasta_tools/utils.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/cli/test_cmds_validate.py
- tests/test_kubernetes_tools.py
- tests/test_setup_prometheus_adapter_config.py
To ship once https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/43202 lands.
We remove offset from PaaSTA since we won't be using it anymore.
- Diff between Prometheus adapter config before and after is empty
- `make test` passes
> remove offset from paasta

- tox.ini
Without this change, `make openapi-codegen` will fail on Yelpy boxes using unprivileged containers as moving the generated code from a temp directory to the final location will encounter permissions issues due to falling back to Docker instead of Podman and not passing user/group flags to Docker
> Fix make test on Yelpy boxes

- Makefile
- tox.ini
I forgot that Jenkins does not use Podman and needs the uid/gid set for things to work
> Pass docker args in CI

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
- Picking up from https://github.com/Yelp/paasta/pull/3787
- `args.no_aws_credentials` was removed in https://github.com/Yelp/paasta/pull/3679 [[error](https://fluffy.yelpcorp.com/i/VHnLpxxbNCxSN5QmdVnt0BMtj1R81C2Q.html)]
- `get_signalfx_url()` was deleted in https://github.com/Yelp/service_configuration_lib/pull/143
- Should be safe because the dashboard says that the license has expired
> Support pod identity in `spark-run`

- paasta_tools/cli/cmds/spark_run.py
Adds an argument for using web identity tokens (pod identity) with spark run. The main implementation is in the below linked PR, and this just passes it through. 
Depends on https://github.com/Yelp/service_configuration_lib/pull/137/files. Will require a version bump of service_configuration_lib to work.
> Add support for use-web-identity in spark-run

- paasta_tools/tron_tools.py
To make it same as the default pool of `paasta spark-run`, so it won't cause problem when user did not specify `--pool` in the `paasta spark-run` command.
> Set default executor pool to batch driver on k8s

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/setup_prometheus_adapter_config.py
- tests/test_kubernetes_tools.py
- tests/test_setup_prometheus_adapter_config.py
The use_prometheus flag for uwsgi is out of date because all the uwsgi stuff should be using prometheus, and the use_prometheus flag for cpu was an experiment that never went anywhere (or so sayeth @nemacysts).  So let's just delete them both.
- make tests/tox -e mypy
- setup_prometheus_adapter_config diff for nova-prod and pnw-prod is empty
- paasta validate (even using the stricter validation in https://github.com/Yelp/paasta/pull/3835) passes for all yelpsoa services
(following up after https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/43786)
COREJAVA-1250
cc @sclg-yelp
> remove use_prometheus for cpu and uwsgi

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
This adds a new system config option, `pool_node_affinities`.
It's necessary to configure pods with a preselection of preferred 2-3 AZs per pool so that Karpenter does not try to consider all 6+ AZs in a region for scheduling decisions.
This option is a temporary solution and the proper fix will likely be to adopt something like the descheduler to achieve a better AZ balance (along with other benefits).
Signed-off-by: Max Falk <gfalk@yelp.com>
> PAASTA-18198: add pool_node_affinities to improve Karpenter AZ balance

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/check_autoscaler_max_instances.py
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/autoscaling_schema.json
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/eks_tools.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/paasta_service_config_loader.py
- paasta_tools/setup_prometheus_adapter_config.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/cli/test_cmds_validate.py
- tests/kubernetes/application/test_controller_wrapper.py
- tests/test_kubernetes_tools.py
- tests/test_setup_prometheus_adapter_config.py
This change introduces the ability to add multiple metrics configs to an HPA via paasta.  We transform the existing AutoscalingParamsDict into a new version that looks like this:
```yaml
metrics_providers:
- type: cpu
setpoint: 0.8
- type: active-requests
desired_requests_per_replica: 10
scaledown_policies: ...
max_instances_alert_threshold: ...
```
In this PR, we support both the old and the new ways of doing things, and we transform the old autoscaling params dict into the new version when we read the YAML files.  After this PR is shipped, we will do a mass-refactor of yelpsoa into the new format and remove the "transformation" code so that only the new format is supported.  
The first commit shows the bulk of the changes, and the second commit shows additional validation code and tests …
> multiple metrics support for paasta

- docs/source/autoscaling.rst
Updated the autoscaling docs; several metrics providers were missing, and we now describe how multi-metrics support works.
- make docs: the new docs look OK.
cc @sclg-yelp
> update paasta docs for multi-metrics

- yelp_package/dockerfiles/focal/Dockerfile
This adds a dockerfile so we can build the package for the handful of new focal usecases we need to support. 
`make itest_focal` from an internal box w/ this dockerfile seemed to work fine.
oddly. enough paasta-tools-go already had a focal dockerfile so no changes required there.
> CID-4094: Support focal

- paasta_tools/check_services_replication_tools.py
- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/metrics/metrics_lib.py
- paasta_tools/setup_kubernetes_job.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
- tests/test_check_service_replication_tools.py
We currently have no way of knowing conclusively whether some of our cronjobs that don't emit start/stop lines are getting slower and approximations based on existing log lines seem to have always fallen flat in previous attempts, and relies on 100% success of our syslog-based pipeline. 
Instead, let's time this from a few of our slowest cronjobs itself and emit timings with some relevant info that I think will allow us to group by the things we need.  We can always adjust dimensions/names of metrics later if they don't end up being quite right, but I'd like to see if this is a worthwhile exercise at all first.
This adds a new helper `system_timer` in metrics_lib that gives us a timer to use in various system components of paasta that have to run periodically.
It uses a few base …
> Add a timer to some of our slowest cronjobs

- paasta_tools/check_services_replication_tools.py
In #3852 I'd missed adding the `cluster` dimension to the check_services_replication timer (which is proving to be the slowest of the bunch and would most benefit from this timer!)
This brings this script in line w/ what I added for both s_k_j and paasta_sync_secrets as well.
> Add cluster to check_services_replication timer

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- requirements-gha.txt
I need to update boostrap dependencies, but the deps in GHA are co-located in the github workflow files which are sourced from the main branch.
Move dependencies into a requirements file which can be updated with the branch.
Requires a PR merge to validate the change.
> Allow python deps in GHA to be specified in branch

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
This is a very partial support of [projected volumes](https://kubernetes.io/docs/concepts/storage/projected-volumes/), but I didn't want to introduce too many new options (that we don't need) in one go.
Ideally these setting will then be automatically generated by parsing the authorization configs and setting up the volumes for the services that need them, but for a first testing phase it'd be handy to be able to just control them manually (we may end up mounting them for all services if catching changes to those configs is a pain, but it'd be nice to be selective).
PS: Tron will be fun, cause those pod definitions are handled in a completely different manner.
> support SA projected volumes

- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
Printing out the --help output when passing a short SHA is not helpful - and neither is not very loudly mentioning that changes *need* to be reverted in Git for a rollback to become permanent
> Improve paasta rollback messaging

- Makefile
- requirements-bootstrap.txt
- requirements-gha.txt
- requirements.txt
- tox.ini
`venv-update` is limited to `pip<=18.1` which does not support manylinux wheels. In order to continue supporting this repo, we need to update pip.
* Drop `venv-update`
* Update bootstrap dependencies in Makefile and GHA
* Minor fixes for newer tox and venv behaviour
> Use vanilla pip

- .github/workflows/ci.yml
- debian/rules
- yelp_package/dockerfiles/noble/Dockerfile
- yelp_package/dockerfiles/noble/mesos-slave-secret
Let's build for noble!
Noble doesn't ship with python3.8 and we need to grab it from deadsnakes ppa. We'll want to update paasta to python3.10 soon...
> Add noble package build

- paasta_tools/check_oom_events.py
- yelp_package/extra_requirements_yelp.txt
Based on the 7+ version changelog:
> Deprecated support for logging bytes lines, emitting a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) if bytes lines are logged.
A future version of yelp-clog will only support str lines. 
Removed support for the scribe protocol
Removed ScribeLogger, ScribeHandler, and ScribeMonkLogger classes.
Only Monk is supported as a backend for clog.
Removed the scribe readers
Removed NetCLogStreamReader and all other classes under the clog.readers module.
These classes are now available in the scribereader package.
none of the above seems to be used. 
Removing the only reference I could find to deprecated `clog.readers`. Everything else should be already using Monk backend and should work without changes.
Smoke test: …
> Bump yelp-clog and scribereader

- requirements-minimal.txt
- tox.ini
Current `master` pipeline is broken due to a recent release of `requests`, which seems to be incompatible with python lib for `docker`
> Pin request in k8s_itests

- paasta_tools/cli/schemas/autoscaling_schema.json
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/eks_tools.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/paasta_service_config_loader.py
Now that everything is on the "new" autoscaling schema, we can clean up all the transform code.
- make test passes
- `paasta validate` passes on all of yelpsoa:
```
> paasta list | xargs -P10 -n1 --no-run-if-empty python -m paasta_tools.cli.cli validate -y ~/src/yelpsoa-configs -s 2>&1 &> output
> grep ✗ output -A 1
> # no errors reported
```
- no changes detected between prometheus_adapter configs before and after:
```
> paasta list-clusters | xargs -I{} bash -c "python -m paasta_tools.setup_prometheus_adapter_config -d ~/src/yelpsoa-configs -c {} --dry-run &> ~/tmp/{}-prom-conf-inst-conf.new"
> git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
> paasta list-clusters | xargs -I{} bash -c "python -m paasta_tools.setup_prometheus_adapter_config -d …
```
> clean up code from old autoscaling config

- docs/source/autoscaling.rst
- paasta_tools/check_autoscaler_max_instances.py
We found that a service where the HPA is unable fetch its metrics would cause this script to error out with:
```
Would've sent an OK event for check 'check_autoscaler_max_instances.cassandra_apis.dev-v1-40'
File "/opt/venvs/paasta-tools/bin/check_autoscaler_max_instances.py", line 199, in <module>
main()
File "/opt/venvs/paasta-tools/bin/check_autoscaler_max_instances.py", line 187, in main
asyncio.run(
File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/opt/venvs/paasta-tools/bin/check_autoscaler_max_instances.py", line 128, in check_max_instances
current_value = …
```
> PAASTA-18203: Catch missing metrics in check_autoscaler_max_instances

- paasta_tools/cli/cmds/rollback.py
After we moved 'long' commit validation to `paasta rollback` in #3862 , this inadvertently broke the feature of `paasta rollback` where it listed recent deployed versions when no commit was specified.
Before this change, `paasta rollback -s paasta-contract-monitor -a` simply threw an error:
```
$ /usr/bin/paasta rollback -s paasta-contract-monitor -a
File "/opt/venvs/paasta-tools/bin/paasta", line 8, in <module>
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cli.py", line 252, in main
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cmds/rollback.py", line 241, in paasta_rollback
validate_full_git_sha(args.commit)
File …
```
> Move git sha validation in paasta rollback

- requirements.txt
- yelp_package/extra_requirements_yelp.txt
We released https://github.com/Yelp/sticht/pull/58 in sticht 1.2.0 , so this bumps in paasta accordingly to fix the issue of slack buttons no longer working.
> Bump sticht to fix slack buttons

- paasta_tools/generate_authenticating_services.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_generate_authenticating_services.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
I thought I would need to jump through many hoops, but this simple of a change should work.
* For new service instances, the list of volume gets updated dynamically on top of what is loaded from the config, so everything easy peasy there.
* For existing instances, I saw that the configuration hash is calculated on the whole pod spec, minus a couple of fields, but definitely including volumes, so if a service which was not required to do auth, and some point becomes required, the hash should mismatch and a new pod get deployed.
The only thing I'm not crazy about is hardcoding that "authenticating.yaml". Maybe I could place that in a field of the system config? Although that may be a way to add a step without much of a benefit. Very open to suggestions here.
> automatically mount service account tokens when needed

- paasta_tools/utils.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_local_run.py
- tests/test_mesos_tools.py
- tests/test_paasta_execute_docker_command.py
GHA has forced our hand by updating the version of Docker in their Ubuntu runners :p
> Migrate from docker-py to docker

- paasta_tools/contrib/service_shard_update.py
This PR updates the script to handle the new autoscaling configuration format, which now uses a list of `metrics_providers` instead of a single `metrics_provider`. The following changes were made:
- Modified the script to construct the `instance_config` with a `metrics_providers` list.
- Ensured that the `metrics_provider` and `setpoint` are added as dictionaries within the `metrics_providers` list.
- Updated the handling of the `autoscaling` configuration to match the new format specified in the provided config file.
These changes address the recent update in the autoscaling configuration format, ensuring that the script correctly handles the new structure.
> Update autoscaling config to use metrics_providers

- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/utils.py
- paasta_tools/vitesscluster_tools.py
- tests/test_vitesscluster_tools.py
*Using multiple commits to iterate on comments and making incremental changes, will squash into a single commit at the end*
Local testing:
Added a make target
```
+.PHONY: setup-kubernetes-cr
+setup-kubernetes-cr:  setup-kubernetes-job
+       export KUBECONFIG=./k8s_itests/kubeconfig;\
+       export PAASTA_SYSTEM_CONFIG_DIR=./etc_paasta_playground/;\
+       export PAASTA_TEST_CLUSTER=kind-${USER}-k8s-test;\
+       .tox/py38-linux/bin/python -m paasta_tools.setup_kubernetes_cr -d ./soa_config_playground -c kind-${USER}-k8s-test -s vitess-k8s
```
*Need to use kubeconfig context to apply CRD's in the expected namespace before vitess-k8s deployment can happen*
Test run output: https://fluffy.yelpcorp.com/i/zMjmrhtFwdqh1rz5mcvwPdRHb1XMNl13.html
Sample yelpsoa specification used for local …
> Add support for generating vitess config from minimal yelpsoa configs

- paasta_tools/cli/cmds/logs.py
`paasta logs` only supports grabbing logs from a single cluster at a time.
> Fix incorrect help text for --cluster in paasta logs

- paasta_tools/cli/cmds/logs.py
- paasta_tools/utils.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_logs.py
I think this is fully ready to go! I've tested this locally with commands like `python paasta_tools/cli/cli.py logs -s example_happyhour -c pnw-devc -i main -f` or `python paasta_tools/cli/cli.py logs -s marley -c pnw-devc -i marley2 -f`
This does depend on some changes on the vector side of things (in `splunk/vector-logs`) in order to transform logs there so that the correct fields are present so that the JSON that NATS returns doesn't need to be parsed, changed a bit, and then re-encoded again. I won't merge this until that work is done and some more testing can be performed.
In order to test I've also been modifying https://github.com/Yelp/paasta/blob/4b465c299882784f01faf4f57ccb116ca7fa7fe6/paasta_tools/utils.py#L2348-L2352 to return `pnw-devc` and not just `kubestage` so that I can …
> Add NATS tailing for vector-logs reader

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- paasta_tools/setup_tron_namespace.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
#3906 and #3903 were reverted due to issues with missing kubeconfigs on tron and ValueErrors on system nodes - these have both been fixed with 40ad655fb9c4f98887c4070446300f6a529f7ef9 (tron) and 30d5de84da9ad65caefa45168e96f8c7da6a2519 (system nodes)
> Fix ensure_service_account breakages from the get_or_create_service_account refactor

- paasta_tools/config_utils.py
It's possible for autotune results to include instances that no longer exist in a given file: either because the instance has been completely deleted or moved to another cluster.
In these cases, it should be safe to simply skip the config merge since there's nothing to merge with.
We could technically still do the config update/merge here and simply skip the resource clamping - but imo, we should simply bail out early.
> Skip autotune merging for deleted instances

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- tests/frameworks/test_native_scheduler.py
- tests/test_kubernetes_tools.py
- tests/test_utils.py
If this is set to false, do not mount the /nail/bulkdata volume
Tested by
* following instructions on [this page](https://yelpwiki.yelpcorp.com/pages/viewpage.action?pageId=234312044)
* editing `etc_paasta_playground/volumes.json` and adding the bulkdata volume
* running `docker ps | grep kind` to find the worker node container ids
* using these ids, running `docker exec -t -i <id> bash` and creating the /nail/bulkdata directory on the worker nodes
* editing `config_playground/compute-infra-test-service/kubernetes-kind-tmower-k8s-test.yaml` and setting bulkdata: false
* verifying with `KUBECONFIG=./.paasta-kube-config kubectl get deployment -n paastasvc-compute-infra-test-service -oyaml` the /nail/bulkdata volume was not added
I'm not entirely sure why `black` has reformatted the …
> Add a bulkdata flag

- paasta_tools/setup_tron_namespace.py
The previous code was creating service accounts with an extra `paasta-` prefix - which would then break when anything tried to use these SA's since they'd still be referencing the expected SA name (without the double `paasta-`)
> Correctly create Tron-related service accounts

- paasta_tools/setup_tron_namespace.py
This is mostly a disaster-recovery thing since this SA exists already - but to avoid any unpleasant times should we decide to start these clusters from scratch, it'd be best to ensure that this SA actually exists :)
(I was talking to @CaptainSame in Slack and he reminded me about this SA)
> Ensure default Spark executor SA is created in Spark clusters

- tests/cli/test_cmds_spark_run.py
❗️Must be merged after https://github.com/Yelp/paasta/pull/3901
Add tests to spark-run to make sure `get_aws_credentials()` from `service_configuration_lib` is invoked properly by the various flags passed to `paasta spark-run`: 
- `--service` should not overwrite `--aws-profile` 
- use `--service` if `--aws-profile` is absent
- in absence of a valid `--service` and `--aws-profile`, use `--aws-profile=default`
> SEC-19137 Add additional get_aws_credentials tests to `spark-run`

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_utils.py
Unit tests are a bit pointless since it's just a waterfall of mocks, but the implementation works:
```
$ paasta local-run ... --use-service-auth-token --dry-run --json-dict | jq .env.YELP_SVC_AUTHZ_TOKEN | wc -c
839
```
> local-run: add option to set service auth token in container environment

- paasta_tools/kubernetes_tools.py
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
- `spark.app.id` is generated fresh and added by service_configuration_lib with a random postfix because of which Tron keeps running update config flow every few minutes. This config should be removed and generated by yelp spark-submit wrapper or by Spark itself.
- `spark.app.name` is also generated fresh with a random timestamp and postfix which leads to the same problem. This config should be made static and potentially replaced by yelp spark-submit wrapper later
> MLCOMPUTE-1389 | remove spark.app.id and generate static spark.app.name

- paasta_tools/cli/cmds/rollback.py
I've noticed a couple folks think that paasta rollback failed because of this coloring - let's avoid some confusion and color this text yellow instead (which is more accurate anyway since it's a warning)
> Color paasta rollback warnings yellow instead of red

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/test_tron_tools.py
- Spark driver pod memory needs to allocate memory for driver memory overhead config along with the driver memory config
> MLCOMPUTE-1497 | include spark driver memory overhead in driver pod memory

- paasta_tools/cli/schemas/tron_schema.json
Following comments from @nemacysts
[here](https://yelp.slack.com/archives/CA53J9UJ0/p1721332229482589?thread_ts=1721143523.159819&cid=CA53J9UJ0)
- all we should need to do is add a boolean field to the tron schema to indicate
whether or not a job uses bulk data.
> Add uses_bulkdata to tron schema

- paasta_tools/utils.py
- paasta_tools/vitesscluster_tools.py
- tests/test_vitesscluster_tools.py
To avoid adding more traffic through envoy. Cloudmap DNS discovery is setup for all MySQL roles in dev and prod
> Use DNS names for MySQL host and avoid envoy discovery

- paasta_tools/frameworks/native_service_config.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
In global paasta config, so we can set it on a per ecosystem/region level in puppet to enable us to roll this out without having to modify every instance in yelpsoa_configs to set uses_bulkdata: true
This is part of the [new proposed rollout
plan](https://docs.google.com/document/d/1RwcJ5JVi2G0Sc2IAXA6tze2CNj2NR8WHN3-rFLjxuOU/edit#bookmark=id.edii46zhxpmu)
Tested by creating a test cluster (from [these instructions](https://yelpwiki.yelpcorp.com/pages/viewpage.action?pageId=234312044)
```
make k8s_fake_cluster
make generate_deployments_for_service
```
saving kubeconfig to a file
```
kind get kubeconfig --name tmower-k8s-test > .paasta-kube-config 
```
Editing `k8s_itests/deployments/paasta/fake_etc_paasta/clusters.json` and setting `uses_bulkdata_default` to `false`
Then running `Run …
> Allow setting a uses_bulkdata default

- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/utils.py
- paasta_tools/vitesscell_tools.py
- paasta_tools/vitesscluster_tools.py
- paasta_tools/vitesskeyspace_tools.py
- tests/test_utils.py
- tests/test_vitesscluster_tools.py
status would be broken for vitesscluster (which is fine) will fix in a later PR
Sample yelpsoa configs:
vitesscluster-infrastage-* https://fluffy.yelpcorp.com/i/n3JX00g4F596PXDCKlL4JHsRNBJsgFZC.html
vitesscell-infrastage-* https://fluffy.yelpcorp.com/i/Bt6lmxqFN9r6Xr5VjCqlxNL1js0tc4jM.html
vitesskeyspace-infrastage-* https://fluffy.yelpcorp.com/i/L5kL1WxrS550j4BJ2hbNM4cdtNgW5Mlw.html
Produced sample CR config:
vitess-k8s-vitess-control-plane: https://fluffy.yelpcorp.com/i/nrq3fJndhrWN0DthBFFx7KHJ1bqx8lSG.html
vitess-k8s-vtgate-uswest1adevc: https://fluffy.yelpcorp.com/i/L2GmQFMMmJd3VKbDT2bK64m6bsFhxRRn.html
vitess-k8s-yelp_vitess_testing_environment: https://fluffy.yelpcorp.com/i/TTsHHVrDvzzKhQ3dpNn3LQR0KxS3JG4Q.html
> Add separate fileprefix handlers for vitess crs

- paasta_tools/cli/schemas/tron_schema.json
- spark.driver.maxResultSize = 0 is used to specify unlimited max result size, so this value should be allowed
> MLCOMPUTE-1209 | allow 0 in spark.driver.maxResultSize

- paasta_tools/cleanup_kubernetes_cr.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/vitesscell_tools.py
- paasta_tools/vitesscluster_tools.py
- paasta_tools/vitesskeyspace_tools.py
- tests/test_setup_kubernetes_cr.py
Context: Vitess custom resources are created in each environment in the same kubernetes namespace. This is to not limit one namespace per custom resource created/updated/listed/deleted
> Allow to modify namespace when creating/updating/listing custom resources

- paasta_tools/cleanup_kubernetes_cr.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/vitesscell_tools.py
- paasta_tools/vitesscluster_tools.py
- paasta_tools/vitesskeyspace_tools.py
- tests/test_setup_kubernetes_cr.py
…
This reverts commit 25b86dfc3a8f2ab7aeabe30d860700c750a145c8.
> Revert "Allow to modify namespace when creating/updating/listing custom resources"

- tests/api/tweens/test_request_logger.py
- tests/cli/test_cmds_status.py
- tox.ini
These tests were failing due to difference in timestamps. This PR fixes the timestamps to match the expected ones
> Fix the timestamps errors in the failed tests

- tests/api/tweens/test_request_logger.py
This fixes the fourth test that was failing due to timestamps but making the timezone UTC so that there is no difference locally vs in pipeline
> Changing timezone to be UTC for test request logger

- paasta_tools/vitesscluster_tools.py
- tests/test_vitesscluster_tools.py
Added the scripts to the docker image in https://github.yelpcorp.com/docker-images/vitess_base/pull/21
AWS role and policy added for namespace pods in https://github.yelpcorp.com/misc/terraform-code/pull/24481
> Add lifecycle hooks for cloudmap (de)registration operations on vtgate pods

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We collectively missed that get_volumes() gets called on the TronActionConfig and not the TronJobConfig. Furthermore, we missed that we weren't actually calling get_volumes() for normal Tron jobs - instead, we were only calling get_extra_volumes() and relying on the Tron `default_volumes` config to add the usual default volumes (which differs from how services work: we always call get_volumes() as we don't distinguish between user-provided volumes and default ones when generating the config there).
I've tested this on tron-infrastage (as well as ensured tests pass for this commit), so this should be safe.
> tron: update schema for bulkdata + correctly pass extra volumes

- requirements-minimal.txt
- requirements.txt
The previous version printed out a log line for every volume that did not exist on the host running a spark config getter - but that's not necessarily an error as the set of files on a kube node do not always match those on boxes where s-c-l is being invoked from
> Bump service-configuration-lib to 2.18.22 to reduce logspam + IO

- requirements-minimal.txt
- requirements.txt
Reverts Yelp/paasta#3952 since there's one spark config that is mounting /etc/pki/spark unnecessarily and i'm running into issues setting up a test to confirm that it's indeed not necessary
> Revert "Bump service-configuration-lib to 2.18.22 to reduce logspam + IO"

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/smartstack_schema.json
This will allow fully configurable enpoints as per the changes in prometheus_exporter here https://github.yelpcorp.com/docker-images/yelpsoa-configs-mirror/pull/17
also removed namespace_alert now as namespace alerts can be disabled with the page/ticket fields
> additional endpoint schema

- paasta_tools/vitesscluster_tools.py
- tests/test_vitesscluster_tools.py
The cloudmap scripts expect srv-configs volume to be mounted on vtgate pods
> Mount srv-configs onto vtgate pods

- paasta_tools/cli/schemas/tron_schema.json
We've now moved this to the correct place in soaconfigs and can get rid of this entry from the schema (in favor of the action-level one)
> Remove unnecessary uses_bulkdata entry from tron schema

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/api/service_api.py
- tests/cli/test_cmds_status.py
- tests/instance/test_kubernetes.py
- tox.ini
Right now, for `paasta status` on any instance, we call `find_all_relevant_namespaces` to get the namespaces that have a deployment/sts for it, which in turn tries to `list_deployments` in _every_ managed namespace.
Since we should rarely need to look through _all_ managed namespaces for any running deployments (usually only when someone is moving their service), this PR just adds a new flag to go back to this behavior, but changes the default to search only the single configured namespace. 
Verified that calls to the API still work and `paasta status` honors the flag appropriately. 
The reduction is time is sorta shocking on norcal-devc:
Without all_namespaces param:
```
$ time curl "http://localhost:41893/v1/services/paasta-contract-monitor/main_eks/status?new=1 | jq '.'
...
real …
```
> PAASTA-18194: Stop querying all managed namespaces by default for paasta status

- paasta_tools/config_utils.py
We've generally decided that we'll be leaving files as eks-*.yaml - and while there's some additional steps that need to be taken, those will need to happen once we've gotten rid of all of the kubernetes-*.yaml files.
As we still have some unmigrated operators, that means we still need to wait. However, we can go ahead and update the comment in the autotune files since those have recently caused some confusion (and assume that anyone looking at autotune files is looking at them for non-operator services)
example diff:
```diff
--- a/yelp_eng_people/autotuned_defaults/kubernetes-pnw-corpdev.yaml
+++ b/yelp_eng_people/autotuned_defaults/kubernetes-pnw-corpdev.yaml
@@ -2,10 +2,10 @@
#
-# yelp_eng_people/kubernetes-pnw-corpdev.yaml.
+# yelp_eng_people/eks-pnw-corpdev.yaml.
#
-# value to …
```
> Update regular filename reference in autotune files

- paasta_tools/setup_tron_namespace.py
- paasta_tools/tron/client.py
Right now we make at most 2N calls to the Tron API during config deployments: N to get the current configs and at most N if all services have changes.
To start, I'd like to reduce this to N by allowing GET /api/config to return all the configs so that the only requests needed are POSTs for changed configs. Since I'm a little worried about how tron-pnw-prod will fare with returning all the configs in a single request, using this new endpoint is behind a feature toggle. Hopefully this works out and we don't need to add pagination to the endpoint :)
Depending on how this goes, we can look into batching up the POSTs so that we can also do that in a single request (or at least <N requests if we want to chunk things a bit more).
NOTE: this requires https://github.com/Yelp/Tron/pull/996
> Attempt to batch config loading for tron deployments

- paasta_tools/cli/cmds/logs.py
similar to scribereader https://github.com/Yelp/paasta/blob/546734de23307a263bd6fca5e2fb48f50263b6eb/paasta_tools/cli/cmds/logs.py#L611
we should be actually using `paasta_app_output_passes_filter` function to filter `stdout` and `stderr` stream log messages, as the current one doesn't respect pod filter (`-p` flag).
> Update vector-logs filter fn usage

- CODEOWNERS
This is a first draft/stab at adding CODEOWNERS for CI-owned code in general across our OSS repositories - we can likely extend this in the future so that operator owners can CODEOWNERS their files to us + them :)
> Add CODEOWNERS for CI-owned files

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/setup_kubernetes_crd.py
- requirements-minimal.txt
- requirements.txt
- tests/test_kubernetes_tools.py
We need to update the kubernetes library to newer versions. 
Containerd gives problems when looking for container image names with the kubernetes client in the current version.
PAASTA-18345
> Upgrading k8s lib

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- yelp_package/extra_requirements_yelp.txt
It can be useful to provide users the option to authenticate to services with their own identity rather than using the role associated to the instance they are running on.
Authentication with our SSO provider is all handled by an internal library, and the rest of the logic is specular to https://github.com/Yelp/paasta/pull/3922.
> local-run: add option to authenticate as the calling user

- paasta_tools/cli/schemas/smartstack_schema.json
Update smartstack_schema.json to support minimum_error_rps for error alerting
> Update smartstack_schema.json to support minimum_error_rps for error alerting

- docs/source/yelpsoa_configs.rst
Update the paasta docs with minimum_error_rps for default error alerting endpoints
> Update the paasta docs with minimum_error_rps for default error alerting endpoints

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We can currently only figure out what service/instance a log belongs to by looking at the k8s labels for the emitting pod, but label values are quite limited in length and we've got some pretty large job and/or action names, which means that the instance label for a large chunk of tronjobs ends up getting truncated.
Solution: annotations! these have a signficantly higher limit (256kb) and they can still be read by our otel collector - the only downside is that annotations cannot be used for filtering, but that's fine :)
> Add service and instance annotations to tron pods

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
It appears that containerd (or k8s 1.24?) have  changed the behavior around adding/dropping linux capabilities and added caps no longer take precedence over dropped ones
> Only drop capabilities that are not added

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
As sets are unordered, not sorting the resulting list built from set operations means that we're constantly changing the order of metadata in the final podspec, leading to bounces almost every time the s_k_j runs
> Sort dropped caps when caps are added

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/smartstack_schema.json
- Added `default_endpoint_alerting` to the example for idk, spice of life?
- Updated the descriptions for namespace-level `error_threshold_ratio` + `minimum_error_rps`
- Added descriptions for `default_endpoint_alerting`, `endpoint_error_threshold_ratio`, and `endpoint_minimum_error_rps`
- Added those three fields to the schema file as well
> Add and document new fields for default endpoint alerting

- paasta_tools/vitesscluster_tools.py
- tests/test_vitesscluster_tools.py
Remove vtgate lifecycle hooks as we're not proceeding with the fix https://github.com/Yelp/paasta/pull/3959 and would like to have functional vtgate pods for testing
> Remove vtgate lifecycle hooks

- paasta_tools/cli/schemas/smartstack_schema.json
... since RPS can reaaaaally vary, depending on your service, and floats would be useful.
> Update smartstack schema for min error rps to be numbers instead of ints

- paasta_tools/cli/cmds/get_image_version.py
- paasta_tools/utils.py
`paasta get-image-version` will output an empty string if the service has no deploy steps with `enable_automated_redeploys` enabled (for compatibility with pre-automated-redeploys behavior).
This introduces a new system config `enable_automated_redeploys_default`, itself defaulted to False, that controls whether `paasta get-image-version` treats a deploy step with no explicit `enable_automated_redeploys` as enabled or disabled.
(If set to True this doesn't actually cause automated redeploys to happen, that requires separate additional Jenkins changes.)
I ran a random `paasta get-image-version -s <service> -c <commit>` for a service with no `enable_automated_redeploys` specified and confirmed that existing behavior continues (empty string with a stderr warning), and that you do get an …
> let enable_automated_redeploys default value be configurable

- paasta_tools/cli/cmds/logs.py
Prevent `paasta logs` from crashing when timestamp field is missing in the original log  from S3. 
```
File "/opt/venvs/paasta-tools/bin/paasta", line 8, in <module>
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cli.py", line 252, in main
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cmds/logs.py", line 1538, in paasta_logs
return pick_default_log_mode(
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cmds/logs.py", line 1449, in pick_default_log_mode
log_reader.print_logs_by_time(
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/cli/cmds/logs.py", line 1212, in print_logs_by_time
if …
```
> Handle AttributeError exceptions in logs CLI

- docs/source/about/glossary.rst
- docs/source/about/paasta_principles.rst
- docs/source/about/smartstack_interaction.rst
- docs/source/autoscaling.rst
- docs/source/contributing.rst
- docs/source/deploy_groups.rst
- docs/source/generated/paasta_tools.rst
- docs/source/index.rst
- docs/source/installation/example_cluster.rst
- docs/source/installation/getting_started.rst
- docs/source/isolation.rst
- docs/source/paasta_development.rst
- docs/source/soa_configs.rst
- docs/source/style_guide.rst
- docs/source/system_configs.rst
- docs/source/workflow.rst
- docs/source/yelpsoa_configs.rst
This PR cleansup Mesos from paasta readthedocs -> https://paasta.readthedocs.io/en/latest/index.html and update with Kubernetes instead
> Cleaning up Mesos from paasta readthedocs - PAASTA-18313

- requirements-minimal.txt
- requirements.txt
This is no longer needed since we've been running Spark on just EKS for a while.
> Bump service-configuration-lib to v3 to stop mounting /etc/pki/spark

- paasta_tools/config_utils.py
- tests/test_config_utils.py
We have automated tooling that modifies eks files, but the validator workflow is setup will cause those automated changes to error if there are modified files that are not able to be validated at all (https://github.com/Yelp/paasta/blob/kedar-validate-eks/paasta_tools/config_utils.py#L253-L266)
I think this should just work given the eks schema exists here: https://github.com/Yelp/paasta/blob/334e743605aeb0d7fac01c34dd38d74013bb156d/paasta_tools/cli/schemas/eks_schema.json
> validate eks files

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
This adds support for configuring Tron-launched pods with a default Topology Spread Constraint (and node affinities) that will spread pods out across multiple AZs - otherwise, Karpenter will overwhelmingly favor a single AZ due to our config
I've double-checked that the feature flag works by running this code on
infrastage as well (as well as with the tests)
NOTE: there's a lot of test "changes", but that's mostly since I noticed
that we were inconsistently mocking load_system_paasta_config() and I wanted
to centralize things to make sure that the tests were doing the right thing.
> Add tron topology_spread_constraints support to PaaSTA

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
We've been reporting which version we are "Bouncing to" incorrectly for quite some time. 
Old status:
```
paasta-contract-monitor.main in eksstage (EKS)
Version:    5f01b83e (desired)
State: Bouncing to configd345863a <--- reports the config version from "(old)" version
Running versions:
Rerun with -v to see all replicas
5f01b83e, config6df36c8b (new) - Started 2024-11-26 12:29:06 (21 seconds ago) <--- most recent version, the one we are actually bouncing to
Replica States: 10 Warming Up
5f01b83e, configd345863a (old) - Started 2024-11-06 09:09:05 (20 days ago)
```
With my change: 
```
paasta-contract-monitor.main in eksstage (EKS)
Version:    5f01b83e (desired)
State: Bouncing to config6df36c8b
Running versions:
Rerun with -v to see all replicas
5f01b83e, config6df36c8b (new) - Started …
```
> Fix backwards "Bouncing to" status

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
This seems to work fine -- I've confirmed via the paasta playground that it's going through the V1PodDisruptionBudget code paths at least, and seems to function in the 1.24-based playground.
I tried upgrading the playground to 1.25 but then my pods are Pending forever -- I suspect it's just something with the playground. Without the changes in this PR, testing setup_kubernetes_job against the 1.25 playground results in 
```
ERROR:__main__:Error while processing: compute-infra-test-service-autoscaling-cb9e0385bfc73cb2288a5b12894720ab3d2a744f-config2468529d
File "/nail/home/krall/pg/paasta/paasta_tools/setup_kubernetes_job.py", line 324, in setup_kube_deployments
app.update_related_api_objects(kube_client)
File …
```
> s/V1beta1PodDisruptionBudget/V1PodDisruptionBudget/ for COMPINFRA-4409

- paasta_tools/contrib/service_shard_update.py
create a `--iam-role` option to provide permissions when using `service_shard_update`
> Add support for iam_role in service_shard_update

- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/autoscale.py
- paasta_tools/cli/cmds/list_namespaces.py
- paasta_tools/long_running_service_tools.py
- tests/cli/test_cmds_list_namespaces.py
Our iam_role configs depend on role owners being able to fill out which k8s namespaces their role is going to be used in in `pod_identity_namespaces`, but paasta normally is figuring out that translation, and users don't usually need to care about this info.
This `list-namespaces` tool should just spit out the namespaces their service will be using, in list format to match what our iam_roles module needs.
I don't expect people will need to specify the instance/cluster filters at all since roles can be used across those lines, but this command leaves the hard work of filtering on those values to the already-existing `get_instance_configs_for_service` util. 
The tests already capture most of the list-namespaces specific logic we want, but testing this against some example services seems to …
> PAASTA-18479: Add list-namespaces tool

- paasta_tools/cli/cmds/logs.py
- requirements-minimal.txt
- requirements.txt
This does two things.
1. reorders `paasta_*_passes_filter` evaluation logic to be more resource efficient and fast:
- running cProfile on a `paasta logs` that retrieves logs from a 5 minutes time range for a verbose stream: 
```
Thu Nov 21 09:17:28 2024    profile_res1
314520328 function calls (314346707 primitive calls) in 190.683 seconds
Ordered by: internal time
List reduced from 9965 to 20 due to restriction <20>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
6298604   28.013    0.000   43.563    0.000 isotime.py:73(parse_time)
6298667   19.141    0.000   19.141    0.000 decoder.py:343(raw_decode)
70692   15.875    0.000   15.875    0.000 {method 'read' of '_ssl._SSLSocket' objects}
6298584    9.933    0.000  129.460    0.000 …
```
> Refactor paasta logs filtering for performance

- paasta_tools/cli/cmds/logs.py
- yelp_package/extra_requirements_yelp.txt
S3LogsReader has been moved to `logreader` package. Using it instead
> Use S3LogsReader from logreader package

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
- tests/cli/test_cmds_validate.py
Since we have to manage the service account (and its pod identity annotation) if someone specifies an `iam_role` for their instance, this is probably incompatible with specifying a service_account.
Technically nothing would break with both, we just wouldn't do anything with the iam_role they'd provided and it would be more difficult for them to troubleshoot iam issues. 
This will give a validation error like the following:
And for tron:
> Disallow having service account + iam_role

- .github/workflows/ci.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Switch to v4 of the artifact actions

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126 the V2beta2 version of the HorizontalPodAutoscaler api is being deprecated in 1.26. 
This updates as per recommendations to v2, and as all of our clusters are >1.23 they should support it. 
Note that we did not use `targetAverageUtilization` that has been switched to `target.type=Utilization`+`target.averageUtilization`, as we'd already used the latter in our code.
This has been tested in paasta playground and infrastage and s_k_j was able to create/modify the appropriate HPA objects and autoscaling was successful. 
Confirmed with audit logs that paasta was sending the request to `autoscaling/v2` rather than `autoscaling/v2beta2` with the change.
> PAASTA-18383: Update V2Beta2 HPA api references to V2 for 1.26

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
This makes the change to paasta spark run so that https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/52010 will work as expected.
This works by adding the uses_bulkdata key to the intsance config if the spark job has the key present and set to true.
I have added this arg to the tests so that they pass, and also created a test so that we can check all the different ways that uses_bulkdata can be set, either on paasta spark-run as an argument, or in the instance config.
See #3995 for more information about why we're doing this.
> Add uses_bulkdata argument to paasta spark run instance_config

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
The Spark driver and executor image version can be inconsistent in a Tron action run when a job is already scheduled before the image is updated, which causes an InvalidClassException if the image's Spark version was changed.
Behavior:
- The action was run with old spark.kubernetes.container.image
- The image is different with the version in the latest Config command
- In the Tron web's `META` section, the `PAASTA_DOCKER_IMAGE` used is the latest version in the `Config command`
Set `spark.kubernetes.container.image` to `$PAASTA_DOCKER_IMAGE` when generating the spark-submit command, to read the environment variable set by Tron, which is the image that Spark driver uses.
Checking the environment variable we are referencing for Tron in this PR
```bash
$ paasta spark-run --aws-profile=dev …
```
> Fix inconsistent spark driver and executor image

- docs/source/yelpsoa_configs.rst
We've seen a couple instances where the k8s signal handling wrought a certain amount of confusion, so let's document this for users/future us.
> Add warning re: signal handling with string cmd

- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
This changes the default value of uses_bulkdata to false, meaning that we can then remove the puppet hiera value which makes the default false that way. Everywhere that puppet is installed has a default value of False, so this shouldn't require a big bounce.
> Set value for uses_bulkdata_default to False

- paasta_tools/api/api.py
- paasta_tools/api/client.py
- paasta_tools/api/tweens/__init__.py
- paasta_tools/api/tweens/auth.py
- requirements.txt
- tests/api/tweens/test_auth.py
Support for an authn/z tween in the PaaSTA API (mostly inspired by previous work).
There's nothing too surprising here. Maybe the only unusual aspect is that I picked to make "dry-run" the default rather than the other way around. It makes things easier to roll out.
For how the codebase is structured loading the token transparently could be a bit of a pain, especially if we want to maintain a bunch of un-auth endpoints, so I just added the option to set the token header in the API client. From there in the CLI implementations that need auth we can do
```python
from paasta_tools.cli.utils import get_sso_service_auth_token
...
get_paasta_oapi_client(..., get_sso_service_auth_token())
```
> auth support for paasta APIs

- paasta_tools/api/tweens/auth.py
The tween tries to access `swagger_data`, which won't be available before the swagger tween validated and loaded the request body, so it's currently failing.
I was undecided on whether to go this route, or trying to extract the "service" field from get/post data manually, but at the end I settled on moving the tween down the stack. This implementation does not include that many tweens, so I don't think not having auth right on top is going to be that impactful / dangerous.
> move auth tween below pyramid_swagger

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
- tests/test_spark_tools.py
- tests/test_tron_tools.py
Add paasta names to spark driver pod annotations.
Follow up by: https://github.com/Yelp/service_configuration_lib/pull/153 which is for executor pod annotations.
> MLCOMPUTE-2733 | Add paasta names to spark driver pod annotations

- paasta_tools/spark_tools.py
- tests/test_spark_tools.py
We check if there is already a timeout command in the user's spark command before auto adding it, but the check doesn't work with the case that an CLI argument is used, e.g. `timeout -v spark-submit`
Fix the regex which checks if timeout is already present
I test ran the `spark-submit` locally on dev-box with `timeout -v 1m`, as expected it timed out at `1m` 
command and output logs can be found [here](https://fluffy.yelpcorp.com/i/wbjZ7FrpPNGVCrg9TgXGnJcd2Hc48rVX.html)
> Fix timeout regex for spark submit command

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- tests/kubernetes/application/test_controller_wrapper.py
- tests/test_kubernetes_tools.py
One first portion of https://github.com/Yelp/paasta/pull/3986, with a couple of minor improvements, as I didn't want to bunch everything together as it'd be a pretty large change to review.
Next I'll do the API endpoints, and I'll finish with the client side bits.
> add support for k8s jobs

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/frameworks/native_service_config.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
This PR removes references to get_uses_bulkdata_default in the code because there is now no such default on disk in puppet.
> Remove references to get_uses_bulkdata_default

- paasta_tools/contrib/service_shard_update.py
follow up for https://github.com/Yelp/paasta/pull/3994
we should allow for deploys for certain environments, especially when using `--iam-role` because roles are often environment specific.
for backwards compatibility, this deploys to all environments when `--environment` is not passed in as an option.
> update service_shard_update to deploy on environment

- paasta_tools/kubernetes/remote_run.py
- paasta_tools/kubernetes_tools.py
- tests/kubernetes/test_remote_run.py
- tests/test_kubernetes_tools.py
* The documentation lied to me, pods only have `job-name` rather than `batch.kubernetes.io/job-name` (maybe it's a difference across versions, I have not checked).
* I wrongly assumed that job labels would propagate to be pod labels. I'm too naive.
> fix job pod labelling

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
This adds some extra validation for `alert_after` in tron and kubernetes/eks monitoring configs. 
Originally had hoped to create a monitoring.yaml schema + reuse definitions from within in each of these but we have some tooling that assumes each jsonschema here is self-contained so i'll need to detangle that before going that route.
For now, to prevent recurrences of these `1d` issues, this just adds individually to the separate schemas. 
new paasta validate would have caught this issue in both a tron-* and eks-* file: https://fluffy.yelpcorp.com/i/lXHsCt04BRWq9kBNjhKmq7QfBLcrfjZW.html
and am currently running validate against all services to ensure this doesn't catch anything else surprising that already exists. 
^ whoops, this caught that some folks are using a bare num of seconds for …
> COMPINFRA-4866: restrict alert_after values for tron/k8s

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
Currently, the pool that the Spark driver of _driver on k8s tron jobs_ runs on is hardcoded to **_stable_** pool, to ensure the Spark driver not being interrupted due to spot interruptions.
However, in some cases, jobs need to pull images from the other docker registry which does not work in the stable pool. We need to make the driver pool configurable.
Add the code to consider spark driver pool from config (if available) otherwise default to stable
Unit tests
> Added code to take spark driver pool from config

- paasta_tools/api/views/remote_run.py
- paasta_tools/kubernetes/bin/paasta_cleanup_remote_run_resources.py
- paasta_tools/kubernetes/remote_run.py
- paasta_tools/kubernetes_tools.py
- tests/kubernetes/bin/test_paasta_cleanup_remote_run_resources.py
- tests/kubernetes/test_remote_run.py
- tests/test_kubernetes_tools.py
`paasta remote-run` works fine now, but I noticed that unless people call `paasta remote-run stop` explicitly, the `job` resource would remain defined forever, even if the pod is terminated by the deadline being reached.
Tackling that on two different angles:
* Setting `ttl_seconds_after_finished` in the job spec should ensure that when the pod completes, the job gets cleaned up too by k8s itself.
* Adding jobs to the resources cleaned up by the cleanup script, but using the max duration as the age limit for that. Just in case k8s does not to the above correctly.
> improve cleanup of remote-run job resources

- paasta_tools/kubernetes/remote_run.py
As promised in https://github.com/Yelp/paasta/pull/4022#discussion_r2000670059.
This can only be shipped once the paasta-api permissions have been updated.
> remote-run: use k8s conf from environment

- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- debian/rules
- requirements.txt
GitHub is deprecating the 20.04 runners, and for some reason we're setting up py3.7 even though we're expecting 3.8.
Note: this required some packages bump: for some reason, `check-requirements` was reporting
that not all packages were installed -- even though the preceding tox loglines reported that
the "missing" packages were installed.
I tried to be pretty conservative with the bumps since we need to do a mass-upgrade at some
point in the future and it wasn't worth dealing with breaking changes and whatnot at the 
moment
> Use 22.04 GHA runners (+ always use py3.8)

- paasta_tools/instance/kubernetes.py
- tests/instance/test_kubernetes.py
We allow people to control the advertisement of replicas in smartstack namespaces, and we allow people to have multiple paasta instances registering to the same namespace, and we allow people to control what locations their paasta instances run in.
To gather mesh status, we collect the backends registered and group them by 'location'.  However, we then assumed all backends would appear in each 'location', which is not the case when advertising is restricted to 'habitat', for example -- mesh status would report each habitat separately, and backends from each habitat would be the only ones included. 
Normally, when advertised at the region level (our default) or above, all backends do appear in each habitat 'location' key, but advertising at the habitat level is still a valid configuration. …
> PAASTA-18666: Include backends from all locations in backeds from mesh status

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/utils.py
- tests/cli/test_cmds_spark_run.py
We want to allow reading IAM credentials from a root protected file. So that there's a single point of entry otherwise many other roles can fetch EKS token.
Currently, only a single file is mounted https://github.com/Yelp/paasta/blob/2e706a1879cbd012ad18f8e3e9324ffa62633cc8/paasta_tools/utils.py#L2736-L2737
Changing that requires changes to `/etc/paasta/spark-run.json` loaded from https://github.com/Yelp/paasta/blob/2e706a1879cbd012ad18f8e3e9324ffa62633cc8/paasta_tools/utils.py#L93-L94
populated via Puppet https://sourcegraph.yelpcorp.com/sysgit/puppet@4c6d259bc8e5cf7c48e75358a010741933591191/-/blob/modules/paasta_tools/manifests/public_config.pp?L501-508
Config changes to come from https://github.yelpcorp.com/sysgit/puppet/pull/14234
> Load credentials from file

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_remote_run.py
- tests/cli/test_utils.py
Because I'm not a huge fan of being stuck into an 80x24 size by default.
This is not dynamic, so if people resize their terminal window it'll break, but being able to react to that would be a huge pain, so going for a minimum viable product as a starting point.
> fix terminal size in remote-run interactive sessions

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
This is something that popped into Infrasec's conversations lately, as sometimes it's a bit hard to attribute specific AWS log events to service instances, [and since it's possible to inject identifiers into the User-Agent set by various AWS SDKs](https://docs.aws.amazon.com/sdkref/latest/guide/feature-appid.html), it'd be nice to get that by default from PaaSTA.
~I wouldn't want this to bump all services at the same time, nor to have to roll it out manually service-by-service with a feature flag, so I'd propose to temporarily exclude the env var form the config hash calculations, let some time pass so that services are redeployed naturally, and then clean up the exclusion. I care less about Tron deployments, since that'd be a single large update to job configs, but no disruption for …
> [rfc] add AWS app id to services env variables

- paasta_tools/cli/authentication.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/cli/utils.py
- paasta_tools/tron/client.py
- tests/cli/test_authentication.py
- tests/cli/test_utils.py
- tests/tron/test_tron_client.py
I recently discovered that there is a duplicate implementation of a Tron API client in here, so I'm giving it [the same treatment of the main implementation](https://github.com/Yelp/Tron/blob/e4310a1cd81ae18de7008b44ca8480a40b75b071/tron/commands/client.py#L57-L60).
In this case, this client is not meant to be used by human, so we are going to use Vault identities for authentication.
PS: I had to refactor the auth methods to avoid a circular import.
> add auth support for Tron client

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
As mentioned in the code comment below, the default way to enable this is per-namespace - that's somewhat annoying since we generally don't really edit namespace labels in PaaSTA post-creation (unless we're doing a one-time bulk edit): so let's instead see if we can configure the AWS LB Controller to only match on pods with this label (and remove the namespace selector)
NOTE: this pairs with https://github.yelpcorp.com/misc/compute-infra-k8s/pull/2505
> Enable labeling pods with AWS LB Controller readiness toggle

- paasta_tools/cli/authentication.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
We want to be able to set different client IDs for the different use cases.
I also renamed the authentication method to be a bit more generic (which I should have done sooner).
> differentiate auth for services and paasta apis

- paasta_tools/utils.py
- tests/test_utils.py
With the images used for remote-run toolboxes not following the paasta labelling convention, this method ended up causing the `git_sha` label for the k8s pod to contain a semicolon, and k8s got really angry about that.
Things are looking more fine after this adjustment:
```
'labels': {'paasta.yelp.com/autoscaled': 'false',
'paasta.yelp.com/cluster': 'pnw-prod',
'paasta.yelp.com/git_sha': '0.2.1',
'paasta.yelp.com/instance': 'main',
'paasta.yelp.com/job_type': 'remote-run',
'paasta.yelp.com/managed': 'true',
'paasta.yelp.com/pool': 'default',
'paasta.yelp.com/service': 'prod-toolbox-kafka',
'yelp.com/owner': 'compute_infra_platform_experience',
'yelp.com/paasta_git_sha': '0.2.1',
'yelp.com/paasta_instance': 'main',
'yelp.com/paasta_service': 'prod-toolbox-kafka'},
```
> fix get_git_sha_from_dockerurl when dealing with non-paasta image URLs

- tests/frameworks/test_task_store.py
- tests/test_docker_wrapper.py
- tests/test_firewall.py
- tests/test_firewall_logging.py
- tests/test_generate_services_file.py
- tests/test_generate_services_yaml.py
- tests/test_iptables.py
- tests/test_mac_address.py
- tests/test_utils.py
This PR resolves the Pytest deprecation warnings by migrating the fixture annotation from `pytest.yield_fixture` to `pytest.fixture`. It solves the following warnings in the [CI logs](https://github.com/Yelp/paasta/actions/runs/14738754656/job/41371316034#step:6:283):
```python
/home/runner/work/paasta/paasta/tests/test_firewall.py:83: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.  Use @pytest.fixture instead; they are the same.
```
> Migrate Pytest fixture annotation

- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
`kubectl` and other small utils I tested were perfectly happy to work with just the executable name (it makes sense since it only serves the purpose of making them believe to be in a real interactive shell), but `ssh` not so much. I suppose because it tries to call it to establish the connection, but does a direct execve without path lookup, so wants an actual path.
> ensure run_interactive_cli uses abs path for shell

- paasta_tools/cli/cmds/logs.py
- paasta_tools/setup_istio_mesh.py
- paasta_tools/smartstack_tools.py
- paasta_tools/spark_tools.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
It also fixes a few typos along the way.
> Migrate to correct logger interface

- paasta_tools/cli/schemas/service_schema.json
- paasta_tools/generate_deployments_for_service.py
Allow setting the `git_url` of a service to `None` in order to have the generate deployment step skip it. Currently, if it tries to access a repo that doesn't exist, it will crash and the generate deployment script will stop completely. Returning these empty mapping objects is the same behavior as when a service "has no valid deploy groups" so it should be handled fine.
It will only be a `None` when it's explicitly set, as it will otherwise generate a default git url.
```
~/paasta (toolbox_generate_deployment) $ paasta validate -y /nail/home/qlo/yelpsoa-configs -s prod-toolbox
✓ Successfully validated schema: adhoc-pnw-prod.yaml
✓ Successfully validated schema: service.yaml
✓ All PaaSTA Instances for are valid for all clusters
✓ All prod-toolbox's instance names in cluster norcal-devc are …
```
> Support None in `git_url` for toolboxes or other future pseudo-sevices

- requirements-minimal.txt
- requirements.txt
- tests/test_tron_tools.py
Bump service-configuration-lib to v3.3.2 to include the followings:
- https://github.com/Yelp/service_configuration_lib/pull/157
- https://github.com/Yelp/service_configuration_lib/pull/162
> MLCOMPUTE-4648 | Bump service-configuration-lib to v3.3.2

- paasta_tools/cli/cmds/remote_run.py
Add the ability to copy individual files into remote-run pods into /tmp. This covers a lot of use cases while still making it hard to modify code or copy whole directories.
```
$ paasta remote-run start -c norcal-devc -s redshift_credentials -i main --interactive --copy-file ~/test1 --copy-file ~/test2
Triggered remote-run job for redshift_credentials. Waiting for pod to come online...
Status: Pod not ready
Pod ready, establishing interactive session...
INFO: You are using an Okta authenticated kubectl wrapper
nobody@remote-run-qlo-redshift--credentials-main-d67jb:/code$ cat /tmp/test1
test
nobody@remote-run-qlo-redshift--credentials-main-d67jb:/code$ cat /tmp/test2
foo
$ paasta remote-run start -c norcal-devc -s redshift_credentials -i main --interactive --copy-file ~/test27657
Triggered …
```
> Add --copy-file for remote-run

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/kubernetes/remote_run.py
- tests/kubernetes/test_remote_run.py
pod.status.phase will still be "Running" even when the pod is terminating. "Terminating" as a status is actually determined from the deletion_timestamp and is not a _real_ status. If a user enters a container like this, they will get booted out after a few seconds.
Return a 409 (is there a better HTTP code?) status for terminating pods and keep polling. Terminating pods turn into non-existent pods, so the most likely reason for a 404 is this case. When that happens, call remote-run start again. If we still get a 404, bail out. 
- I experienced kubectl exec hanging one time, I think that was a race condition where the pod was terminating (running) but actually gone by the time kubectl exec ran. I wasn't able to reproduce that, but I think it should be solved by this. Maybe it could still …
> Remote run - handle terminating pods better

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
When an `iam_role` changes underscores to dashes or vice versa, the normalization function will treat it as identical, and the ServiceAccount won't be updated.
Actually verify the `iam_role` value matches when an existing ServiceAccount is found, and if it differs, patch it. 
Unit tests only right now. Will update here if I perform additional testing.
> Check iam_role for existing ServiceAccounts

- paasta_tools/setup_kubernetes_job.py
I'm not quite sure why `mypy`/`pyright` didn't yell at me for this, but this should silence some noise in our logs in clusters where we haven't used the override functionality
> Handle non-existent configmaps for autoscaling overrides

- requirements-minimal.txt
- requirements.txt
Upgraded **_service_configuration_lib_** to **_v3.3.4_** which includes the functionality of manually overriding the default spark run config file
https://github.com/Yelp/service_configuration_lib/releases/tag/v3.3.4
> Upgraded service_configuration_lib to v3.3.4

- paasta_tools/utils.py
- tests/cli/test_cmds_spark_run.py
I've recently created this new IAM user to replace `mrjob`. It has the necessary permissions for most Spark jobs. I'm doing this so we can eventually delete the mrjob user.
Note that this is only used if a user does *not* specify aws profile or another credentials file, so this isn't likely to break anything, as few if any spark jobs are using this yet.
> Switch default spark user from mrjob to spark_driver

- paasta_tools/kubernetes/remote_run.py
People may want to run adhoc configured instances with remote-run as they often do with local-run. To do this, we can load the adhoc deployment configuration and put the config dict into a new EKS deployment object, similar to how toolbox containers function.
I tested this with a very basic adhoc config file that only specified memory and cpu. https://fluffy.yelpcorp.com/i/QcpxxNgXnTv4WXSfgDzr2qfSDNhHn5pK.html
> Support adhoc instances in remote-run

- paasta_tools/cli/cmds/remote_run.py
> remote-run: fix toolbox property name

- paasta_tools/cli/schemas/adhoc_schema.json
We need it to override [this behaviour](https://github.com/Yelp/paasta/blob/685e73f6ccdc3a30dc7482955c679de5f7733045/paasta_tools/kubernetes_tools.py#L2411-L2423) in remote-run toolbox instances.
> add fs_group to adhoc schema

- paasta_tools/cli/cmds/validate.py
Entertainingly, our recent Tron issue caused by a cronjob with an 'impossible' date would've actually been caught in some way by a *verbose* `paasta validate`: 
```
✓ tron-infrastage.yaml is valid.
ℹ Upcoming runs for test_load_foo1:
File "/nail/home/jfong/work/yelpsoa-configs/virtualenv_run/bin/paasta", line 8, in <module>
File "/nail/home/jfong/work/yelpsoa-configs/virtualenv_run/lib/python3.8/site-packages/paasta_tools/cli/cli.py", line 253, in main
File "/nail/home/jfong/work/yelpsoa-configs/virtualenv_run/lib/python3.8/site-packages/paasta_tools/cli/cmds/validate.py", line 1011, in paasta_validate
if not paasta_validate_soa_configs(service, service_path, args.verbose):
File …
```
> TRON-2481: Attempt to generate next run dates as part of validation
