Yelp/paasta

- README.md
We previously had no mention of our IRC channel. This pull request adds a link to it in the README.
> Add a note about our IRC channel to the README

- paasta_tools/setup_chronos_job.py
- tests/test_setup_chronos_job.py
(i.e. use my recent refactors to address a TODO)
> Sort jobs so that we really clean up old ones

- .travis.yml
This Pull Request is to allow me to iterate on getting itests working in travis. Ignore it for now.
> Run itests in travis

- requirements.txt
> fix marathon package naming in requirements.txt

- comparison.md
Thanks for including Flynn in your comparison! I made some minor updates for accuracy.
> Update Flynn comparison

- docs/source/yelpsoa_configs.rst
This adds documentation for all of the keys listed in the `key_whitelist` in marathon_tools.py.
> Flesh out docs for smartstack.yaml

- paasta_tools/paasta_cli/cmds/local_run.py
- paasta_tools/paasta_cli/paasta_cli.py
- paasta_tools/paasta_cli/utils.py
- tests/paasta_cli/test_cmds_help.py
- tests/paasta_cli/test_utils.py
- Also simplified (and accurately named) the thing that discovers all the command modules.
> Fix --help for local-run and add a test

- docs/source/about/smartstack_interaction.rst
- docs/source/yelpsoa_configs.rst
> Documented the relationship between instance and nerve_ns better

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
The docstring should be explanatory enough.
> Make backoff_seconds work as a function of the instance count.

- docs/source/workflow.rst
We don't really explain this anywhere, so I figured I would add it.
> Added docs explaining the difference between difference service modes

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
This is the first part: all I want here is for the parents to be pulled in from the config, and for the validation to fail if parents are specified.
> Dependent jobs field

- requirements.txt
- setup.py
- yelp_package/dockerfiles/itest/marathon/Dockerfile
AFAIK this has the right marathon libraries to do this. Let's see if Travis agrees!
> Begin testing against marathon 11

- docs/source/about/paasta_principles.rst
This adds the whole "why do this in the first place" answer, which is kinda the 0'th principle of PaaSTA. This doc kinda assumes that you already want to build a paas yourself, so I thought we might make this 0th principle explicit in this doc?
> Added 0 principle

- paasta_tools/check_chronos_jobs.py
> update the description of check_chronos_jobs

- docs/source/yelpsoa_configs.rst
> add docs for schedule time zone field

- paasta_tools/contrib/README.md
- paasta_tools/contrib/purge_all_chronos_jobs.py
- setup.py
This adds that contrib folder I was talking about.
In addition I purged all the chronos jobs in a fit of desperation and stuck it in here.
> Added contrib location and purge_chronos_jobs

- paasta_tools/cli/cmds/local_run.py
To avoid these:
```
15:39:54 time="2016-01-19T15:39:54-08:00" level=fatal msg="Error response from daemon: Cannot start container 4ab7d672f26436db000e87d5c0939a681dff7364547b348990ee2154f8e83778: Error starting userland proxy: listen tcp 0.0.0.0:33421: bind: address already in use" 
```
We already use this strategy for other utilities (see `ephemeral-port-reserve` (internal) for where the code comes from via @bukzor).
> Pick an ephemeral port better

- paasta_tools/check_marathon_services_replication.py
- tests/test_check_marathon_services_replication.py
Fixed a bug where non-smartstack services would fail to send alerts when they start failing.
> Fixed a bug where non-smartstack services would fail to send alerts when they start failing

- docs/source/about/paasta_principles.rst
Fixes the broken link here: http://paasta.readthedocs.org/en/latest/about/paasta_principles.html
> Fix the broken link

- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/setup_chronos_job.feature
- paasta_itests/steps/chronos_steps.py
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- paasta_tools/setup_chronos_job.py
- tests/test_chronos_tools.py
- tests/test_setup_chronos_job.py
This is going to be a rolling PR.
Current Status: unit tests and integration tests pass. There aren't actually that many changes here, it was mostly work in the integration tests.
Before I merge, I'm going to evaluate the integration tests are still testing 'useful' things. I'll also test on mesosstage.
> Remove tags chronos jobs

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
This should allow us to catch some bugs that are eluding us
> chronos now gives sensu the full job id of a failed task

- tox.ini
@solarkennedy this should fix it I would think
> Install deps during manpages

- general_itests/steps/deployments_json_steps.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/utils.py
- tests/test_generate_deployments_for_service.py
Also fixed a regex bug hidden within paasta_tools.utils.list_clusters
> Fixed bugs introduced in the generate deployments rebase

- docs/source/workflow.rst
- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
This is something I've wanted for a while, but haven't pushed because it involves a big bounce to every app.
> Inject PAASTA_* variables into every task

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/remote_git.py
- paasta_tools/utils.py
- tests/test_remote_git.py
This reverts commit b2f70f449e19a1648e145dca8064525a78719641, reversing
changes made to a02373d798ae429efcc095f81638e165f05e59ba.
Conflicts:
paasta_tools/cli/cmds/start_stop_restart.py
> Revert "Merge pull request #190 from Yelp/mark_for_deployment-tags"

- general_itests/steps/fsm_wizard_steps.py
- paasta_tools/cli/cmds/fsm.py
- paasta_tools/cli/fsm/questions.py
- paasta_tools/utils.py
- tests/cli/fsm/fsm_test.py
- tests/cli/fsm/questions_test.py
We should probably discuss what the deploy groups in the default configs should be.
> fsm now generates configs that use deploy groups

- setup.py
requirements.txt was hiding this missing dependency
> Add jsonschema to setup.py

- requirements.txt
Upgrade mesos.interface to 0.23.1 per step 3 on http://paasta.readthedocs.org/en/latest/upgrading_mesos.html
> Upgrade mesos.interface to 0.23.1

- docs/source/deploy_groups.rst
- docs/source/yelpsoa_configs.rst
You can see the deploy groups rst here: http://rst.ninjs.org/?n=3482021a3416f45d4b1aee08e9713b4e&theme=nature
> Added documentation for deploy groups

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/remote_git.py
- paasta_tools/utils.py
- tests/test_generate_deployments_for_service.py
- tests/test_remote_git.py
Reverts Yelp/paasta#250
Reverting the temporary revert now that a new paasta has been tagged and released.
> Revert "Revert "Mark for deployment tags take2""

- paasta_tools/cli/cmds/metastatus.py
- tests/cli/test_cmds_metastatus.py
> made metastatus catch when no dashboard in configured

- docs/source/deploy_groups.rst
- docs/source/installation/getting_started.rst
- paasta_tools/cli/cmds/mark_for_deployment.py
> Renamed --deploy_group to --deploy-group

- paasta_tools/utils.py
- tests/test_utils.py
@EvanKrall review -- the config interpolation we talked about
> added string interpolation to deploy groups

- paasta_itests/setup_marathon_job.feature
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/bounce_lib.py
- paasta_tools/graceful_app_drain.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
for some reason scaling up using `scale_app` doesn't work unless I set `force=True`. IDK enough to determine if this is bad
> enabled scaling without bounces when editing soa_configs

- paasta_itests/paasta_metastatus.feature
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Not sure if this is enough to fix the issue with `paasta metastatus -vv` (it is tough to test this due to the nature of status/metastatus connecting to remote hosts). But I can iterate as necessary. 
Fixes #257
> Fix metastatus -vv

- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
> Added a more friendly error message when git isn't reachable.

- paasta_tools/mesos_tools.py
> Updated /state endpoint for mesos 0.25.x upgrade

- docs/source/yelpsoa_configs.rst
there will be more docs to follow up with, but this is a start
> add a note about the parents field in yelpsoa-configs

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
> respect the alert_after param in check_chronos_jobs

- paasta_tools/generate_deployments_for_service.py
@nhandler pointed out this log line was wrong
> fixed a log line in generate_deployments_for_service

- paasta_itests/environment.py
> added clean_up_zookeeper_autoscaling to environment.py

- docs/source/contributing.rst
- paasta_tools/cli/cmds/list_clusters.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_rollback.py
- tests/test_utils.py
I don't actually know how to test this to make sure the CLI actually works other than passing a string to cli.py (might not actually be bad)
> added an autocomplete to rollback git shas

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
This is papercut that should help people figure out what is wrong with their container during local-run.
> Display more data when doing the healthcheck during local-run

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/cleanup_marathon_jobs.py
- paasta_tools/monitoring_tools.py
> made cleanup_marathon_job not load soa configs for a deleted service

- docs/source/generated/paasta_tools.autoscaling_lib.rst
- docs/source/generated/paasta_tools.rst
- docs/source/workflow.rst
I'm not sure this is the right place for these docs, but I think they're worth having.
> add some docs for paasta start/stop behaviour

- README.md
> Add Bintray Badge to README

- .travis.yml
This should lighten the load on Travis and thus get us feedback sooner.
> Only have travis build on master (and pull requests).

- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
source -> overrides
destination -> defaults
> made args for deep_merge_dictionaries more descriptive

- paasta_tools/cli/cmds/get_latest_deployment.py
- tests/cli/test_cmds_get_latest_deployment.py
@asottile 
Fixes internal ticket PAASTA-3591
Fixes #359
> added a command to get a deploy group's latest deploy sha

- requirements.txt
This is the final step in the mesos 0.25.0 upgrade I performed.
> Bump mesos.interface to 0.25.0

- docs/source/upgrading_marathon.rst
> Remove docs about adding marathon-python to internal pypi

- paasta_itests/setup_chronos_job.feature
- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
This is *still* an issue - I was incorrect to close this with  #293
This is a dupe of #288, rebased onto current master.
> Set real disabled value

- debian/paasta-tools.links
- setup.py
- yelp_package/itest/ubuntu.sh
copied from a previous commit doing this
> ensure chronos rerun is distributed properly

- debian/paasta-tools.links
- paasta_tools/autoscale_all_services.py
- paasta_tools/autoscaling_lib.py
- paasta_tools/bounce_lib.py
- setup.py
- tests/test_autoscaling_lib.py
- yelp_package/itest/ubuntu.sh
Also made autoscale_all_services grab a lock in zookeeper
> added a command to autoscale all services

- tests/test_chronos_serviceinit.py
> fix test dependent on time

- tests/test_cleanup_chronos_jobs.py
> fix test missing tzinfo

- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_setup_chronos_job.py
> make docker config location configurable

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
> remove the requirement for a start time in chronos schedules

- docs/source/yelpsoa_configs.rst
- paasta_tools/marathon_tools.py
- paasta_tools/mesos_tools.py
- paasta_tools/utils.py
- tests/test_marathon_tools.py
- tests/test_mesos_tools.py
- tests/test_utils.py
- yelp_package/dockerfiles/itest/marathon/Dockerfile
> Add support for whitelisting.

- paasta_tools/cli/cmds/fsm.py
> fixed formatting in fsm

- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
Fixes `Docker container run error: Port mappings are only supported for bridge network`
> fixed net host marathon error

- docs/source/autoscaling.rst
- paasta_tools/autoscaling_lib.py
- paasta_tools/marathon_tools.py
- tests/test_autoscaling_lib.py
Also updated docs to have more info on PID controllers and autoscaling.
> Removed variable delay and other params from autoscaling

- paasta_tools/contrib/kill_orphaned_docker_containers.py
- paasta_tools/mesos_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
🐄 Make the orphaned docker script a little more monitoring-friendly
🐄 Relocate some of the functions into utils/mesos_tools 
🐄 Add test for relocated code
> Clean up orphaned docker container script

- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
closes #410 
I'm not sure the itests tell me much because of #373 ? I'm testing on mesosstage.
> Add memory swap param

- paasta_tools/cli/cli.py
The python arparser isn't very helpful when you ask for "help" or typo or a command or something like that, it simply prints the "usage" which is the
```
check,cook-image,emergency-restart,emergency-scale,emergency-start,emergency-stop,fsm,generate-pipeline,get-latest-deployment,info,itest,list,list-clusters,local-run,logs,mark-for-deployment,metastatus,performance-check,push-to-registry,rollback,security-check,start,restart,stop,status,validate
```
message. Not that helpful. This makes it so we print the full help page and respond to the "help" command.
> Make the argparser print the full help whenever an argparse issue is encountered

- paasta_tools/mesos_tools.py
Temporary monkey patch to work around the problem.
```
(py27)root@paasta1-r9-iad1:/nail/home/gcioffi/git/paasta# ./paasta_tools/paasta_serviceinit.py -v <redacted>.<redacted> status
[..]
Mesos:      Healthy - (14/14) tasks in the TASK_RUNNING state.
Running Tasks:
Mesos Task ID                         Host deployed to  Ram          CPU      Deployed at what localtime
dfcde86d-0327-11e6-ae4f-769d85214997  paasta2-r9-iad1   24/2032MB    54.1%    2016-04-15T09:34 (19 hours ago)
f8a66b08-026f-11e6-ae4f-769d85214997  paasta7-r3-iad1   24/2032MB    69.7%    2016-04-14T11:37 (a day ago)
f8a643f6-026f-11e6-ae4f-769d85214997  srv13-r7-iad1     24/2032MB    59.6%    2016-04-14T11:39 (a day ago)
f8a61ce4-026f-11e6-ae4f-769d85214997  paasta7-r3-iad1   1240/2032MB  82.7%    2016-04-14T11:37 (a day …
```
> Unknown slaves in "paasta status" workaround (PAASTA-4119)

- docs/source/workflow.rst
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> Local run memory swappiness

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> made local_run --healthcheck-only return 1 when healthchecks fail

- docs/source/workflow.rst
> improve the documentation on paasta batches

- docs/source/autoscaling.rst
- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
(9 instances)
Also made PID autoscaling able to scale as fast as it thinks is correct
New autoscaling math/voodoo is based off of [this paper](https://users.cs.duke.edu/~shivnath/papers/acdc09.pdf)
> Made autoscale able to scale down below 9

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
add instructions for rerunning the job, viewing logs and running
paasta status
> improve failure message sent by check_chronos_jobs

- docs/source/conf.py
- docs/source/yelpsoa_configs.rst
- paasta_tools/marathon_tools.py
- tox.ini
cc @mittonk
internal ticket PAASTA-4400
I'm also trying out this autorun thing so we don't have to "remember" to keep docs in sync with code.
> Document which config entries invoke a bounce

- docs/source/conf.py
- docs/source/yelpsoa_configs.rst
- paasta_tools/marathon_tools.py
- tox.ini
> Revert "Document which config entries invoke a bounce"

- paasta_tools/cli/cmds/metastatus.py
> add missing system_paasta_config arg in metastatus

- build-manpages.sh
- debian/paasta-tools.links
- docs/source/contributing.rst
- general_itests/steps/local_run_steps.py
- general_itests/steps/validate_steps.py
- setup.py
> expose CLI as console_scripts #85

- debian/paasta-tools.links
- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling_lib.py
- setup.py
- yelp_package/itest/ubuntu.sh
This exposes the autoscale_cluster code to a cli command to make it easier to iterate on, also logging.
> Added a cli entrypoint to autoscale_cluster

- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
This adds assertions that our env settings are strings.
> Validate that env settings are always strings

- paasta_tools/contrib/graceful_container_drain.py
I've used this enough times now that it should be part of the codebase. @nhandler will probably use this atleast as a basis for draining hosts in #376
> Graceful container drain

- paasta_tools/utils.py
- tests/test_utils.py
I would like to start recursively reading files from /etc/paasta.
Mostly to make it easier for autoscaling where we'll have multiple json files per aws resource and I would like to have a dedicated folder for it.
> Load paasta configs from /etc/paasta recursively

- debian/paasta-tools.links
- paasta_tools/paasta_maintenance.py
- setup.py
- tests/test_paasta_maintenance.py
This is a first pass at a `paasta maintenace` command. I need to think a bit more about how to properly do itests in a useful way, but there are some unit tests.
Connect to #376
> First pass at 'paasta maintenance' command

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Mesos 0.28.1 has been released. This change updates our itests to test against it.
> Upgrade to mesos 0.28.1

- paasta_tools/cli/cmds/logs.py
- paasta_tools/utils.py
- tests/cli/test_cmds_logs.py
- tests/test_utils.py
In preparation for adding non tailing modes to the scribe log reader
> Add support in `paasta logs` for non tailing modes

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
> Upgrade to mesos 0.28.2

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
I think the existing unit tests should cover this new functionality, but it probably also needs integration tests.
Closed #504
> Add cpu-period and cpu-quota to marathon logic

- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
Adds the cpu quota options to chronos and local-run
> Generalize cpu quota

- docs/source/yelpsoa_configs.rst
- paasta_tools/bounce_lib.py
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- tests/test_bounce_lib.py
- tests/test_setup_marathon_job.py
internal ticket: PAASTA-3304
tox tests/test_bounce_lib.py succeeded
> Allow crossover to make progress in the face of failures

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
to work well when the number of instances is small
> ceil() when using marging_factor

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_metastatus.py
- tests/cli/test_utils.py
> add the -g and -H to the cli entrypoint for metastatus

- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
> Add delayed and waiting state to paasta status for marathon jobs

- docs/source/yelpsoa_configs.rst
> [PAASTA-4955] Add docs for new options

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling_lib.py
- paasta_tools/mesos_tools.py
- tests/test_autoscaling_lib.py
- tests/test_mesos_tools.py
This is a WIP (needs testing, tests and docs etc.)
Just putting it up for early comments on the direction.
Also needs https://github.com/Yelp/paasta/pull/521/ to make the draining work and (I think) further changes to the maintenance scripts to prevent allocation of tasks to slaves in maintenance mode.
> Changes to cluster autoscaling

- paasta_tools/autoscaling_lib.py
- paasta_tools/mesos_tools.py
Log more at info so we can disable debug logging which is way too
verbose.
> Change logging for autoscaler

- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
* Adds support for weights to the spot autoscaler
* Makes multiple quick modifications to target capacity possible
* Handles an error when an instance is terminated but still reported by describe instances
> Autoscaler weights

- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
This consolidates the call to find slaves by IP into one EC2 describe
call. This prevents us hammering the EC2 api.
> Reduce EC2 API calls from autoscaler

- paasta_itests/docker-compose.yml
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Upgrade to mesos 1.0.0 in our itests
Fixes #637
> Mesos 1.0.0

- requirements.txt
- setup.py
I made "hour" support in tron, this fetches a new version that supports it.
> Bump tron to pick up 'hour' support

- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/api.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/api/views/service.py
- requirements.txt
- setup.py
- tests/api/test_instance.py
- tests/api/test_service.py
Main changes:
1. api input/output validation with swagger.json.
2. install swagger.json to paasta_tools_path/api/api_docs via package_data.
> Added pyramid_swagger to paasta-api

- paasta_tools/cli/cmds/check.py
- paasta_tools/utils.py
- tests/test_utils.py
Fixes `paasta check` for command- steps
> Add support for command- steps in check

- paasta_tools/mesos_tools.py
This is an expected error so decreasing the level and making the reason
clear.
> Make log message clearer when counting tasks

- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/test_utils.py
> pass soa_dir into guess_cluster/get_default_cluster_for_service.

- paasta_tools/paasta_metastatus.py
just some cleanup now that I've revisited this file
> delete duplicate code in metastatus

- paasta_tools/paasta_maintenance.py
- tests/test_paasta_maintenance.py
This is mostly more boilerplate, the hard part is filling in `are_local_tasks_in_danger()`
> Added skeleton for paasta_maint is_safe_to_drain

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/cmds/info.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_check.py
- tests/cli/test_cmds_info.py
Let's reimplement this in #710 in a more generic way.
> Remove yelpy links to jenkins pipeline

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/client.py
- paasta_tools/cli/cmds/status.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/api/test_client.py
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
This reverts commit 33d9e781685355c68884a57637068c650bde8cb1.
> Revert "Replace paasta-api client with swagger client"

- debian/rules
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/client.py
- paasta_tools/cli/cmds/status.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/api/test_client.py
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
This is to restore the previous revert by adding no-use-wheel option to pip.
> Replace paasta-api client with swagger client

- setup.py
I guess this used to be captured as a dependency of something...
> Add pytz to setup.py

- paasta_itests/itest_utils.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
Ping @huadongliu, I'm not sure how we got by without this?
> Disable caching on wait_for_app_to_launch_tasks

- paasta_tools/contrib/bounce_log_latency_parser.py
What I used to get bounce log data for #736 
It's pretty nasty
> added bounce log parsing script

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Reports the image correctly when running local-run. Used to be 'None'.
Also add a flag --json-dict that, when used in conjunction with --dry-run, changes the json output to be a JSON dict that's easier to parse instead of an unstructured list of strings.
> Fix image for local-run also support a dict json output

- paasta_tools/contrib/bounce_log_latency_parser.py
Now this works as an actual script 👍
> improved the bounce latency parser script

- paasta_tools/autoscale_all_services.py
- paasta_tools/autoscale_cluster.py
After d761ca6606c78d4758a51502e16d65a07c14eef0 I missed some important
imports!
> Fix ImportError after refactor in autoscaler

- tests/cli/test_cmds_local_run.py
- tests/test_check_marathon_services_replication.py
- tests/test_chronos_rerun.py
- tests/test_chronos_serviceinit.py
- tests/test_cleanup_chronos_jobs.py
- tests/test_mesos_maintenance.py
- tests/test_mesos_tools.py
- tests/test_paasta_maintenance.py
- tests/test_utils.py
We were not autospec'ing all the things and let a few errors get by, luckily I found no actual errors in the code, just tests. (except maybe for `test_clone_job_dependent`)
> Autospec all the things

- tests/test_mesos_tools.py
Somehow this got by and broke master. Let's see what travis thinks now?
> Mock out get_mesos_config

- tests/test_smartstack_tools.py
I guess this snuck through between my two other patches
> fixed another test without autospec

- general_itests/steps/local_run_steps.py
This seems to be failing intermittently? I'm just guessing but maybe
this is now taking longer after #756. I've bumped up the timeouts to see
if it helps.
> Paasta local run itest timeout

- paasta_itests/setup_marathon_job.feature
> fixed itest flake

- example_cluster/docker-compose.override.yml
- setup.py
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/cron.d/autoscale_services
- yelp_package/dockerfiles/mesos-paasta/cron.d/cleanup_chronos_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/cleanup_marathon_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_chronos_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_marathon_services
@Rob-Johnson nice easy one to review here 😄
> Fix example cluster post mesos-cli

- paasta_tools/mesos/master.py
- paasta_tools/mesos/slave.py
- paasta_tools/paasta_metastatus.py
This reverts commit b874f01621233daff9dd616547e47bd845d5f88b.
we found that this caused a bunch of problems - I'll revert and iterate.
primary @mattmb
> Revert "remove @CachedProperty decorator from master + slave state"

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos/slave.py
- paasta_tools/paasta_metastatus.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
@mattmb - this is the 'easy' version of the fix attempted in #786
> Fix status call autoscaler

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
We were rounding the new target capacity in the main downscaling loop.
This leads to a situation where terminating an instance with a weight
less than 0.5 leaves the new target capacity at the same value. This
leads to terminating more boxes than intended!
Now we only round the value to an integer just before we send it to AWS
which is the only reason we have to round it anyway.
> Fix cluster autoscaling termination loop

- paasta_tools/mesos_maintenance.py
- tests/test_mesos_maintenance.py
See 43ccfa5106e289d0194356a0433669028c898446 for motivation. I think
this must have been lost in a rebase at some point :-S
> Move task counting out of mesos maintenance

- paasta_tools/mesos_maintenance.py
- tests/test_mesos_maintenance.py
These new functions will make it easier to add monitoring checks to detect hosts that are forgotten in a draining/down state.
> Add some new functions to make it easier to monitor draining/down hosts

- paasta_itests/itest_utils.py
- paasta_itests/paasta_api.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/paasta_serviceinit_steps.py
Hopefully making itests slightly faster.
> Small itest fixes for marathon itests

- .travis.yml
`itest_xenial` appears to be working fine on Travis. Let's let Travis upload Xenial deb packages to Bintray.
> Enable xenial package uploads to bintray

- paasta_tools/cli/cmds/status.py
- requirements.txt
- setup.py
- tests/api/test_client.py
This is to fix [issue 811](https://github.com/Yelp/paasta/issues/811).
> handle paasta api errors

- paasta_tools/cleanup_maintenance.py
Looks like `mesos_maintenance` gets unhappy when passed empty lists of hostnames. Let's not do that. We should also support `-v`.
> Make cleanup-maintenance check for empty lists of hosts and support -v

- paasta_tools/cleanup_maintenance.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/paasta_maintenance.py
- tests/test_mesos_maintenance.py
- tests/test_paasta_maintenance.py
From internal ticket PAASTA-5800.
Made the copyright headers uniform.
> updated copyright years

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We... never seem to actually print out the actual healthcheck result!
> Try to make healchecks easier to understand in local-run

- paasta_tools/api/api.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/docker_exec.py
- paasta_tools/cli/cmds/docker_inspect.py
- paasta_tools/cli/cmds/docker_stop.py
- paasta_tools/cli/cmds/sysdig.py
- paasta_tools/cli/utils.py
- paasta_tools/mesos_tools.py
- tests/api/test_instance.py
- tests/cli/test_cmds_docker_exec.py
- tests/cli/test_cmds_docker_inspect.py
- tests/cli/test_cmds_docker_stop.py
- tests/cli/test_cmds_sysdig.py
- tests/cli/test_utils.py
- tests/test_mesos_tools.py
- yelp_package/dockerfiles/mesos-paasta/start.sh
* Adds a new `<service>/<instance>/tasks` API endpoint and use this for `docker_*`
* Fix sysdig task filter
* Improve API dev environment
> Fix new cli commands

- paasta_tools/cli/cli.py
- tests/cli/test_cmds_help.py
> Commandline errors exit nonzero

- paasta_tools/contrib/mock_patch_checker.py
- tests/test_chronos_tools.py
> Update mock patch checker to use the AST module

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
Let's give it a shot. Relates to https://github.com/mesosphere/marathon/issues/4581
> Try not scaling down before deleting marathon apps.

- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
> dont jump the gun adopting v2 deployments

- paasta_tools/cli/cmds/mark_for_deployment.py
> Don't set the return code of mark-for-deployment as True

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
@solarkennedy this was a subtle one! We missed how `with progressbar.ProgressBar()` works, it doesn't *require* `bar.finish()` to be called to exit. Unfortunately the tests didn't catch it either because they were exiting after the first `time.sleep` call.
---
We introduced a bug in https://github.com/Yelp/paasta/pull/837 where
we would exit from wait for deployment after the first check of all the
clusters and instances, regardless of status.
This adds back the while loop which is neccessary even with the `with
progressbar` and also improves the test case which would have caught
this regression.
> Fix waiting on mark for deployment

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
I thought I'd already shipped this but I guess not!
We are conservative when downscaling, sometimes we won't kill an
instance if it would take us below the target.
If the SFR is cancelled we need to make sure we kill at least one
instance so that we don't get stuck never killing an instance.
> Fix downscaling cancelled SFRs

- requirements-dev.txt
> Fix the build again again

- docs/source/yelpsoa_configs.rst
- paasta_tools/chronos_tools.py
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
> support chronos deploy blacklist

- paasta_itests/steps/bounces_steps.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- tests/test_marathon_tools.py
- tests/test_setup_marathon_job.py
Just scratching an itch with this PR. I've attempted to pin down some slow bits in `setup_marathon_job` and make them "better".
Not really sure how much time this might save. The getting of marathon tasks will only improve if we call this script with multiple services (which we currently don't). @mjksmith you're the expert on this right? Do you think this will help?
> Setup marathon speedup

- paasta_tools/utils.py
- tests/test_utils.py
> made the picker catch EOFError

- docs/source/adhoc_instances.rst
- docs/source/generated/paasta_tools.adhoc_tools.rst
- docs/source/workflow.rst
- docs/source/yelpsoa_configs.rst
> added adhoc instance docs

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Started going through this, and couldn't stop.
> Better healtcheck handling with paasta local-run

- paasta_tools/cli/cmds/logs.py
- requirements.txt
> fixed paasta logs -l

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
This adds an `--auto-rollback` option to mark-for-deployment so pipelines can automatically roll back to the previous sha if they fail to deploy. (timeout or manually canceled)
> Added option to automatically roll back on failures.

- yelp_package/dockerfiles/itest/chronos/Dockerfile
this is the version we've currently got deployed at Yelp.
> bump chronos version in itests

- paasta_tools/cli/cmds/wait_for_deployment.py
To follow up our conversation with @mattmb
> Give names to wait-for-deployment exceptions

- paasta_tools/metrics/metastatus_lib.py
- tests/metrics/test_metastatus_lib.py
> fix the percentage for queued Chronos jobs

- paasta_tools/cli/cmds/mark_for_deployment.py
> do a stdout flush when the progress bar may be updating

- paasta_itests/steps/setup_steps.py
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/fsm/autosuggest.py
- paasta_tools/contrib/graceful_container_drain.py
- paasta_tools/utils.py
- tests/cli/fsm/test_autosuggest.py
TRWTF is why safe_load isn't the default amirite?
Internal ticket is PAASTA-7208
> Safe load all the things

- paasta_tools/utils.py
- tests/test_utils.py
Always pass strings to this thing.
Internal ticket PAASTA-7266
> Always pass strings to the chooser

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
This expands the set of env variables exposed during local run, and adds room to simulate per-framework specific stuff. I used docker-inspect to get a snapshot of all the vars available at runtime.
Fixes #443.
Fixes #855.
> Expand the number of env variables available in local-run

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
> Load correct namespace for determining drain_method, drain_method_params, bounce_method_params.

- paasta_itests/docker-compose.yml
- requirements.txt
- yelp_package/dockerfiles/itest/marathon/Dockerfile
For https://github.com/mesosphere/marathon/issues/4769
> Use marathon 1.4.0 rc3 in itests

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/mesos_tools.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/test_mesos_tools.py
This is a fairly big refactor to add ASG support. Major things:
* Move to resource "setters" which set capacity for each type of resource but keep "scaler" the same for both
* Make list of instances a resource property so that it can be in the same place for SFRs and ASGs
* Add specific handling for ASG "delta" (we need this because we have to handle cleaning up ASGs differently)
> Autoscaler ASG support

- paasta_tools/contrib/check_registered_slaves_aws.py
This check was missed when I did the re-factor in
4fcbfb23d3e14ed94b8ba9cad9d9eb64e50d4c65
This is what's creating notification spam at the moment.
> Fix a script missed in refactor

- docs/source/yelpsoa_configs.rst
checked the output and the formatting looks good.
> update docs on cron schedule

- requirements-dev.txt
I'll hold off merging until we get our tests fixed so I can properly test this change.
> Upgrade pre-commit to 0.12.0

- yelp_package/dockerfiles/lucid/Dockerfile
A fixup from the previous commit that should actually work.
Just running itest_lucid before I merge...
> fixup! Latest pip + venv on lucid too

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
@mattmb is this really dumb? I'm hoping to encode a bit more information about 'what' is being autoscaled without having to add ``id: %s" % self.resource["id"]`` to every log line.
> try adding a logging mixin to the autoscaler

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
Currently we lock the `do_bounce` function on the service instance we are
bouncing. This moves the lock higher up to lock the `setup_service`
funcion. This should mean there can be no race conditions between two
instantiations of setup_marathon_job.
Note that this also makes failing to get the lock for a service a
non-fatal error. i.e. we just log and carry on. This is neccessary
because we sometimes expect two bounces to run at around the same time
so skipping one because it is in progress elsewhere isn't really a
problem.
The motivation for this fix is that currently two invocations of
`setup_marathon_job` can gather the same info about a service and both
decide they need to create a new marathon app. Although only one gets a
lock to do so the second may eventually get the lock and gets …
> Move bounce lock to higher level

- docs/source/yelpsoa_configs.rst
- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/native_mesos_scheduler.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
I thought for sure docker would tolerate this.
Internal ticket PAASTA-7920.
> Dedupe volumes when specified twice in a config

- paasta_tools/utils.py
- tests/test_utils.py
> Add a py2+py3 helper for sorting dictionaries

- requirements.txt
- setup.py
This is the last step in the mesos 1.1.0 upgrade.
> Upgrade mesos.interface to 1.1.0

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/marathon_tools.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/test_marathon_tools.py
This would need tests (and testing). Just posting for some feedback. Do we think this is sane? Maybe we should just hunt down these "healthcheckless" tasks and trigger a bounce for that app as @Rob-Johnson suggested?
Not included yet is converting this check to a threshold (which I still think is a good idea).
---
This makes two changes:
* Use the long marathon app_id. This means we should now only be
autoscaling the latest version of a paasta service. It also means we
can ignore any interaction with the bounce becase we are ignoring the
old service.
* Assume missing health checks are "normal" for tasks that haven't just
started. This is due to a bug in marathon where tasks can stop being
healthchecked but remain running and healthy.
> Relax service autoscaler task counting

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
Currently we connect to one smartstack endpoint to calculate which tasks
are happy for a particular service in a particular namespace. If the
host we've picked happens to have been terminated or is unreachable then
we error. This is slowing down the bounce process.
This commit makes it so that we keep trying any other relavent smartstack
host and only thow an error if we can't connect to any of them.
Internal ticket PAASTA-8357
> Try multiple haproxy endpoints during bounce

- .travis.yml
- general_itests/steps/deployments_json_steps.py
- general_itests/steps/http_drain_method_steps.py
- paasta_tools/cli/cmds/fsm.py
- paasta_tools/remote_git.py
- tests/test_remote_git.py
- tox.ini
@mattmb I took the git refs bytes change in this :) (#1037)
> general_itests pass in py3

- requirements.txt
- yelp_package/dockerfiles/itest/marathon/Dockerfile
Marathon 1.4.1 has been released. Let's start testing it out.
> Marathon 1.4.1

- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
- requirements.txt
- tests/test_check_chronos_jobs.py
> detect stuck chronos jobs

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
> Fix cron_check_chronos_jobs_staleness

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/paasta_metastatus.py
this makes the autoscaling_cluster_lib return a 'neutral' value,
and not have to be aware of how metastatus will print out the objects in
a table
@mattmb this is along the lines of what I meant.
```
(py27) bash-4.3# ./paasta_tools/paasta_metastatus.py -vv -a
Master paasta_tools version: 0.57.15
Mesos Status: OK
Quorum: masters: 3 configured quorum: 2 
Frameworks:
Framework: chronos count: 1
Framework: marathon count: 1
CPUs: 0.60 / 48 in use (1.25%)
Memory: 0.54 / 225.52GB in use (0.24%)
Disk: 6.00 / 773.95GB in use (0.78%)
Tasks: running: 6 staging: 0 starting: 0
Slaves: active: 6 inactive: 0
Connected Frameworks: expected: 2 actual: 2
Disconnected Frameworks: expected: 0 actual: 0
Inactive Frameworks: expected: 0 actual: 0
Resources Grouped by region
Region        CPU (used/total)  RAM …
```
> format autoscalinginfo objects in metastatus

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
> add schedule to the output of check_chronos_job

- paasta_tools/docker_wrapper.py
- tests/test_docker_wrapper.py
> do not add --hostname when --network=host

- paasta_tools/frameworks/native_scheduler.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
> Implement pool restrictions on native mesos framework.

- paasta_tools/cli/cmds/sysdig.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_sysdig.py
- tests/cli/test_utils.py
This is to work around some issues with ephemeral masters
> Set StrictHostKeyChecking=no

- yelp_package/dockerfiles/itest/mesos/Dockerfile
> install the mesos wheels in the master example_playground container

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
just to get my name on the board :)
> fix minor typo

- requirements.txt
- yelp_package/Makefile
This is needed to support Marathon 1.4.1
> Use marathon-python 0.8.12

- paasta_tools/docker_wrapper.py
- tests/test_docker_wrapper.py
> Fixed the meminfo docker wrapper regex and added more test

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
Print more useful commands for debugging when wait-for-deployment timeouts.
Sample output:
```
Timed out after 1 seconds, waiting for someservice in fake_group to be deployed by PaaSTA.
This probably means the deploy hasn't succeeded. The new service might not be healthy or one or more clusters could be having issues.
To debug try running:
paasta status -c cluster1 -s someservice -i instance1,instance2
paasta status -c cluster2 -s someservice -i instance3
paasta logs -c cluster1 -s someservice -i instance1,instance2 -C deploy -l 1000
paasta logs -c cluster2 -s someservice -i instance3 -C deploy -l 1000
If the service is known to be slow to start you may wish to increase the timeout on this step.
```
> more useful output in wait-for-deployment

- tests/test_marathon_tools.py
- tests/test_setup_marathon_job.py
Some tests were broken by
https://github.com/thefactory/marathon-python/pull/178
This makes them pass
> Fix the tests after a change in marathon-python

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> Always output the docker stdout on local-run in healthcheck mode

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/native_mesos_scheduler.py
- paasta_tools/paasta_remote_run.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
> [wip] Timeout on task staging

- tests/test_chronos_tools.py
every second day doesn't work well between 31st and 1st.
> Fix crontab test

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
async version of uwsgi and http providers for the service autoscaler.
> async version of uwsgi and http providers

- yelp_package/dockerfiles/itest/marathon/Dockerfile
Changelog: https://github.com/mesosphere/marathon/blob/v1.4.2/changelog.md
> Use marathon 1.4.2

- debian/rules
- yelp_package/Makefile
> Only use internal pypi when requested

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
> --deploy-group option for paasta status

- paasta_tools/api/views/instance.py
- paasta_tools/paasta_serviceinit.py
> Don't throw an exception for unknown instance types

- paasta_tools/marathon_tools.py
Cache load_marathon_service_config() for 5 seconds to avoid memorizing it forever in paasta.api.
> Cache load_marathon_service_config() for 5 seconds

- paasta_itests/paasta_deployd.feature
- paasta_itests/steps/paasta_deployd_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/bounce_lib.py
- paasta_tools/deployd/common.py
- paasta_tools/deployd/leader.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/deployd/workers.py
- paasta_tools/utils.py
- requirements.txt
- setup.py
- tests/test_bounce_lib.py
- tox.ini
This is a start on paasta-deployd
I'm trying to avoid touching the existing code base as much as possible but this does make a small change to `setup_marathon_job` job to make the poc "work".
I'll probably do a bit more work on this branch before we need to think about merging it in but it would be great to get some feedback on the high level architecture! Please don't waste your time digging too deep though as there's still likely to be quite a bit of change going on.
> [WIP] Paasta deployd

- paasta_tools/api/views/instance.py
- tests/api/test_instance.py
> Fixing status of adhoc instances for real

- paasta_itests/paasta_deployd.feature
Will this make things less flappy on travis?
> Increase timeout on deployd itests

- debian/paasta-tools.links
- paasta_tools/deployd/master.py
- setup.py
This is so I can try it out in the "real" world.
> Add entrypoint for paasta-deployd

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
Add a sample re-run command to the timeout message in wait-for-deployment
> Add a sample re-run command to the timeout message

- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
> Reduce possibility of noisy alerts due to delayed chronos jobs

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/paasta_remote_run.py
- paasta_tools/utils.py
ssh with pseudo-tty and kill tasks on term/int/hup signals
> handle interrupts, quote command properly on local side

- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
> --deploy-group for paasta start/stop/restart

- paasta_tools/deployd/master.py
- paasta_tools/utils.py
- tests/test_utils.py
This adds the bare bones obvious things we'd want to configure from
config files.
> Add some basic config options for deployd

- task_processing/interfaces/__init__.py
- task_processing/interfaces/task_execution.py
- task_processing/task_processing/__init__.py
- task_processing/task_processing/docker_task_configs.py
- task_processing/task_processing/framework.py
- task_processing/task_processing/mesos_task_execution.py
- task_processing/task_processing/runner.py
Just wrote mesos scheduler and implemented the task execution interface per the CEP. Let me know what you think about it.
> [WIP] Task processing mesos scheduler

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
> Fix wait_for_deployment with not enough instances

- paasta_tools/cli/cmds/push_to_registry.py
- tests/cli/test_cmds_push_to_registry.py
> Make 'paasta push-to-registry' refuse to overwrite an existing image

- paasta_tools/frameworks/native_scheduler.py
- tests/frameworks/test_native_scheduler.py
- set daemon attr to true on timer threads, otherwise main thread blocks on exit until timers are done
- decline blacklisted slaves with a filter to suppress further offers from same slave
- add test for blacklisting slaves
> Daemonize timer threads in remote-run, slave blacklisting changes

- paasta_tools/deployd/common.py
- paasta_tools/deployd/master.py
Include timestamp and module name
> Make logging better for deployd

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
Fixes the second bullet point in #1169
> wait-for-deployment will no longer block on Deploying or Waiting #1169

- paasta_tools/deployd/common.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/setup_marathon_job.py
- tests/deployd/test_common.py
- tests/deployd/test_deployd_master.py
- tests/deployd/test_watchers.py
This should really be two commits but I screwed up. Tests are
incoming...
> Add maintenance + public config watchers

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
If the new app is running, and there are no more old tasks, no need to log anything
> Don't log when bounce "doesn't do anything"

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_check.py
> Support adhoc.yaml in paasta check 

- paasta_tools/check_marathon_services_replication.py
- tests/test_check_marathon_services_replication.py
reduces it to once per run, rather than once per service/instance
> reduce v2/tasks call in check marathon replication

- tests/test_mac_address.py
_flock_process() doesn't shell out to flock - instead it forks and does it all in python itself. This fixes #1239
> test_mac_address no longer depends on /usr/bin/flock

- paasta_tools/frameworks/native_service_config.py
- tests/frameworks/test_native_scheduler.py
to support private docker registries
> add support for uris to native scheduler

- paasta_tools/cli/cmds/rollback.py
- tests/cli/test_cmds_rollback.py
> Paasta 6795 rollback check sha

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
internal ticket: PAASTA-7889
Verify the list of instances specified in passta start, stop, restart or status,
report if an instance doesn't exist, and continue executing the command anyway.
```
$ python paasta_tools/cli/cli.py status -s service1 -c cluster1 -i main
service1 doesn't have any instances matching main on cluster1.
Did you mean any of these?
main_sfo12
main_uswest1
cluster: cluster1
```
> report when an instance doesn't match anything

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
> Handle ConnectionError when getting list of tasks in smartstack

- paasta_tools/deployd/master.py
- tests/deployd/test_deployd_master.py
This adds some sensible defences for workers and watchers dying due to
unexpected exceptions. In the case of a watcher dying we commit suicide
and simply let another leader take over. If a worker dies then we just
restart it, unless all workers die in which case we also commit suicide.
> Deployd actions for dying threads

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/autoscaling/ec2_fitness.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/autoscaling/test_ec2_fitness.py
@mattmb I've got tests to fix and real testing to do - just thought I'd get the code up for review.
> Kill unhealthy instances first

- paasta_tools/long_running_service_tools.py
- tests/test_marathon_tools.py
This is a prerequisite for nerve-tools https://github.com/Yelp/nerve-tools/pull/35 to support body aware health check in nerve https://github.com/airbnb/nerve/blob/master/lib/nerve/service_watcher/http.rb#L41.
make test; make itest
> Support nerve body aware healthcheck

- debian/rules
- paasta_itests/paasta_native.feature
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/frameworks/native_service_config.py
- requirements.txt
- setup.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
- tox.ini
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
- yelp_package/itest/ubuntu.sh
This gets rid of the knarly mesos.native dependency and paves the way to python3 :-D
> Port the native scheduler to use pymesos

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
@mattmb I'd like to get this out and give it a go in mesosstage. what do you think?
> default healthcheck type to MESOS_HTTP

- docs/source/yelpsoa_configs.rst
- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
- tests/test_check_chronos_jobs.py
- tests/test_chronos_tools.py
internal tickets: PAASTA-11186, PAASTA-11277
> Make acceptable delay in check_chronos_jobs configurable

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
This reverts commit 7c48b91b0cc2ccf533b42fd669a609f65adb40d8.
> Revert "default healthcheck type to MESOS_HTTP"

- paasta_itests/chronos_rerun.feature
- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/chronos_rerun_steps.py
- paasta_tools/chronos_rerun.py
- tests/metrics/test_metastatus_lib.py
- tests/test_chronos_rerun.py
Fix itest failure
Make chronos rerun itest more accurate
> Fix rerun graph itest failures

- paasta_tools/firewall.py
- tests/test_firewall.py
> Allow all services access to DNS

- .travis.yml
- Makefile
- debian/rules
- itest.sh
- tox.ini
> Use private PyPI when available

- paasta_tools/firewall.py
- tests/test_firewall.py
To make things hopefully a little more obvious, this introduces a "common" chain which is used by _all_ services. That includes these 3 things as well as a jump to the DNS chain (which we also provide for free, but is slightly more complicated so gets its own chain).
Tested on mesosstage; could hit all these things with netcat after but not before.
> Allow all services to access scribe, metrics-relay, sensu

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
previous PR: #1257 
revert: #1293
internal ticket: PAASTA-11186
another attempt to remove acceptable_delay from the chronos jobs check.
* remove acceptable_delay (15m)
* increase alert_after from 2m to 15m
* add timezone information to the error message
* convert last run time from UTC to the job time zone
> Replace acceptable_delay with alert_after in check_chronos_jobs

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
This has happened a couple of times on yelp-main bounces. The steps to repro are:
1. Scale up an app to say instances: 200, don't let it scale up that far, let it get to 100 (get it into a Waiting state)
2. Do a code push (bounce)
3. Scale down an app to instances: 100
Expected: The bounce would "finish" because it would go from 200->100 and scale down that 100 of empty waiting slack
Actual: The bounce never scales down anything because there isn't anything to drain or kill, which is kinda the only way that the bounce knows how to scale down. It will wait to launch more just so it can drain+kill.
This fixes the bug by introducing the concept of "slack" and will remove slack on scaledown.
This could have been implemented as another arg for do_bounce. Let me know if you would like me to do …
> Make setup_marathon_job take care of slack instance slots on scaledown

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
> Fix check-chronos-jobs when schedule timezone is None

- paasta_tools/utils.py
Especially to help with reading autoscaler output, when actions are ran for many different services
> Print service name when paasta_print log line

- paasta_itests/README.md
Describe how to run the itests a bit faster
> Itest readme

- paasta_tools/paasta_remote_run.py
- requirements.txt
also bump task_processing and use initial delay option
> prepare task_config before initializing mesos stack

- paasta_tools/adhoc_tools.py
- paasta_tools/cli/cmds/push_to_registry.py
some things used to be bytes
now they're not
some things used to be strs
now they're not
> Fixing some encoding errors uncovered in dev/stage

- .pre-commit-config.yaml
- LICENSE
- docs/source/about/glossary.rst
- docs/source/index.rst
- docs/source/monitoring/check_classic_service_replication.rst
- docs/source/monitoring/index.rst
- docs/source/system_configs.rst
- docs/source/workflow.rst
- paasta_itests/cleanup_marathon_job.feature
- requirements-dev.txt
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_chronos_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_marathon_services
- yelp_package/dockerfiles/mesos-paasta/cron.d/paasta_generate_all_deployments
- yelp_package/dockerfiles/playground/Dockerfile
congrats, this is now the largest project that I can (probably) commit to that has pre-commit -- hope you don't mind me using it as a test bed :)
> Upgrade pre-commit and hooks

- docs/source/generated/paasta_tools.oom_finder.rst
- paasta_tools/api/api.py
> Monkey patch the standard library to make the api non-blocking

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/long_running_service_tools.py
- tests/cli/test_cmds_local_run.py
verify=False because I believe the certs here will be self-signed. Or, should I do this another way?
> Allow for https healthchecks

- paasta_itests/steps/setup_steps.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/graceful_app_drain.py
- tests/cli/test_cmds_logs.py
- tests/test_bounce_lib.py
- tests/test_utils.py
Fixed a few more places where autopep8 and add-trailing-commas disagreed -- these weren't conflicting before the last branch as add-trailing-comma was missing some cases.
> Resolve more autopep8 / add-trailing-comma conflicts

- paasta_tools/paasta_remote_run.py
- requirements.txt
blocked on https://github.com/Yelp/task_processing/pull/44
> use task processing plugin registry instead of direct imports

- paasta_tools/deployd/master.py
- tests/deployd/test_deployd_master.py
If a service is in the backlog to be bounced and there is a change to
its marathon-.yaml or deployments.json the the deploy daemon will notice
the change and if the new app that is required is not yet created then
it will add a second instance to the bounce queue. This way the queue
keeps growing.
This makes the BounceQueue drop any duplicate service instances that are
already in the queue.
> Dedupe the bounce queue

- paasta_tools/deployd/workers.py
- tests/deployd/test_workers.py
This turned into a larger diff than I expected...
I'll have another read through before someone reviews this.
> Fix worker exception handling

- paasta_tools/long_running_service_tools.py
- tests/autoscaling/test_autoscaling_service_lib.py
This is a similar change as @solarkennedy made earlier.
> One more zk.set to use bytes

- paasta_itests/docker-compose.yml
- yelp_package/dockerfiles/itest/api/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/playground/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
More cherry-picked from #1391
I figured out my blocking problem (though I'm still not 100% sure why it's different)
> Cleanup dockerfiles more

- paasta_tools/utils.py
Mostly to run chromium/selenium in the container
> Allow setting the shm-size

- requirements.txt
- setup.py
> Remove python2-specific requirements

- paasta_tools/api/api.py
- requirements.txt
Context: https://github.com/Yelp/paasta/issues/1373
Currently having problems verifying locally due to https://github.com/Yelp/paasta/issues/1406, would like to verify this change works before merging
> Add CORS to API endpoints

- paasta_tools/firewall.py
- tests/test_firewall.py
> Always whitelist Google Public DNS

- paasta_tools/paasta_remote_run.py
tron isn't retrying so this would be unexpected behaviour, possibly undesirable. will re-add it carefully later.
> drop retrying executor from the stack

- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
fwiw, this already passed in travis-ci here: https://travis-ci.org/asottile/paasta/builds/259937052
> Apply a docker best practice to itest_trusty / itest_xenial

- paasta_tools/docker_wrapper.py
- tests/test_docker_wrapper.py
> strip trailing hostname dashes

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/wait_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
> Fail wait-for-deployment if a cluster has no configured API endpoints

- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/cron.d/autoscale_services
- yelp_package/dockerfiles/mesos-paasta/cron.d/cleanup_chronos_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/cleanup_marathon_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/delete_old_marathon_deployments
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_chronos_jobs
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_marathon_services
- yelp_package/dockerfiles/mesos-paasta/cron.d/paasta_generate_all_deployments
- yelp_package/dockerfiles/mesos-paasta/start.sh
- yelp_package/dockerfiles/playground/Dockerfile
- yelp_package/dockerfiles/playground/start.sh
I hit a wall converting these to xenial so this will have to do :/
> Convert the playground and mesos dockerfiles to py36

- docs/source/yelpsoa_configs.rst
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
This is the same as the start of https://github.com/Yelp/paasta/pull/1425 , but without all the refactoring mess necessary to inject the PAASTA_TEAM var.
> Inject the PAASTA_DEPLOY_GROUP env variable

- docs/source/generated/paasta_tools.monitoring.check_capacity.rst
- paasta_tools/monitoring/check_capacity.py
- setup.py
@Rob-Johnson I missed this piece  
(also slipping in a formatting change)
> check_capacity should be added as a script

- paasta_tools/chronos_tools.py
- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/utils.py
Rather than adding a one-off rule for each one-time-use docker arg
Fixes #1411
> Allow 'extra_docker_args'

- paasta_tools/cli/cmds/logs.py
- tests/cli/test_cmds_logs.py
> Decode marathon and chronos streams as utf-8

- paasta_tools/check_chronos_jobs.py
- paasta_tools/cleanup_chronos_jobs.py
- tests/test_check_chronos_jobs.py
> check_chronos_jobs to take job runtime into account

- example_cluster/docker-compose.override.yml
- example_cluster/tests/check-api.sh
- paasta_tools/api/api.py
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/cron.d/deploy_marathon_services
- yelp_package/dockerfiles/mesos-paasta/start.sh
* Use the new split out paasta-api but in development mode
* Remove deploy marathon cron job
* Start paasta-deployd in mesosmaster container
> Enable deployd for the example cluster

- requirements.txt
Update task_processing to https://github.com/Yelp/task_processing/commit/b88c9ad4e5a826f0cdf87318945425ae18e18beb
> bump up task_processing sha

- paasta_tools/check_oom_events.py
- tests/test_check_oom_events.py
internal ticket PAASTA-567
This is the very first version of the check that I'm going to use for dogfooding.
Therefore no docstrings, no tests.
> check_oom_events initial commit

- paasta_tools/paasta_remote_run.py
- requirements.txt
> include environment vars in remote-run

- paasta_tools/list_marathon_service_instances.py
- paasta_tools/mesos_tools.py
- paasta_tools/smartstack_tools.py
- tests/test_smartstack_tools.py
Also fix type error when logging errors
> Fix type error, where whitelist gets checked against none in mesos_tools

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/utils.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Hopefully this will avoid some mesos bugs
> Don't try to drain unhealthy instances when scaling the cluster down

- paasta_tools/cli/cmds/local_run.py
> in local-run do not try to bind to a port if healthcheck is not defined

- paasta_tools/mesos_maintenance.py
> Only unreserve resources reserved for the purpose of maintenance

- requirements.txt
this includes:
- log error and exit when async callback fails https://github.com/Yelp/task_processing/pull/73
- timeout executor https://github.com/Yelp/task_processing/pull/66
- stricter check on cmd attribute https://github.com/Yelp/task_processing/pull/72
- set success field on all terminal events https://github.com/Yelp/task_processing/pull/70
> bump taskproc to current master

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/paasta_remote_run.py
- add debug flag
- set appropriate verbosity level from flags
- default to logging.WARNING
> [remote-run] log verbosity from args

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
Partially to try to figure out why it gets stuck so often
> Add more debug messages to the cluster autoscaler

- paasta_tools/long_running_service_tools.py
> remove limited instance count warning

- yelp_package/extra_requirements_yelp.txt
> Add yelp_paasta_helpers to extra_requirements_yelp

- paasta_tools/paasta_remote_run.py
Tested with "paasta_remote_run.py start --service taskproc_canary --instance fake_remote --cluster norcal-stageg" and verified paasta.remote_run.start.failed shows up in SignalFx.
> Emit meteorite counters to track paasta_remote_run failures

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> local-run will detach only if healthcheck is needed

- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
This reverts commit 7bd0ca991fccf3d1f39d2a5b6fe94362c5e8950e.
> Revert "temporarily ignore orphan_tasks in mesos_tools.get_all_runnining_tasks"

- paasta_tools/mesos/master.py
- paasta_tools/mesos/slave.py
This instruments it for every mesos api call
> Make all mesos api calls use the paasta user agent

- .pre-commit-config.yaml
- .travis.yml
- requirements-dev.txt
> Upgrade pre-commit and migrate to pygrep

- requirements.txt
- setup.py
now that https://github.com/sensu-plugins/sensu-plugin-python/issues/13 is resolved
> Use sensu-plugin-python from pypi

- paasta_itests/steps/setup_steps.py
- paasta_tools/marathon_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/monitoring/check_mesos_duplicate_frameworks.py
- paasta_tools/paasta_metastatus.py
- tests/metrics/test_metastatus_lib.py
- tests/monitoring/test_check_mesos_duplicate_frameworks.py
- tests/test_paasta_metastatus.py
Another way to implement https://github.com/Yelp/paasta/pull/1541
It compares framework IDs instead of comparing just the number of connected frameworks.
> Paasta 13123 another way

- paasta_tools/marathon_tools.py
> fix mypy failures

- requirements.txt
This includes the fix to not reconcile queued tasks.
> Bump up taskproc

- paasta_tools/chronos_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
> use caching clients in metastatus

- paasta_tools/mesos/cfg.py
- paasta_tools/mesos_tools.py
with load_mesos_config function. seems like we're not using any of the implemented functionality and probably never will.
> replace mesos.cfg.Config

- paasta_tools/mesos_maintenance.py
Similar to https://github.com/Yelp/paasta/pull/1571
3s connect timeout, 1s read timeout
> reduce http timeout in mesos_maintenance

- paasta_tools/setup_marathon_job.py
This looks like a good idea to me. See PAASTA-13315 for examples of logs.
> do not undrain unreachable tasks

- docs/source/autoscaling.rst
- paasta_tools/autoscaling/forecasting.py
> Update autoscaling docs

- paasta_tools/deployd/master.py
- paasta_tools/utils.py
- tests/deployd/test_deployd_master.py
> adds functionality to enable specific watchers in deployd

- tests/autoscaling/test_autoscaling_cluster_lib.py
Reduces time to run these tests from ~28s to ~7s
Testing indicates it reduces overall test runtime by about 20s.
fixes #1589
> Remove unnessesary calls to sleep in test_autoscaling_cluster_lib

- paasta_tools/contrib/paasta_get_num_deployments.py
> Make paasta_get_num_deployments using marathon sharded code

- paasta_tools/contrib/delete_old_marathon_deployments.py
> delete_old_marathon_deployments to use marathon sharded code

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
low hanging fruit for PAASTA-13381
By skipping unreachable tasks like this, please note that we will stop killing these checks as well because they will never be added to tasks_to_kill.
> skip unreachable tasks when draining

- paasta_tools/graceful_app_drain.py
> make graceful-app-drain using marathon sharded code

- paasta_itests/steps/paasta_api_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/api/api.py
- paasta_tools/api/settings.py
- paasta_tools/api/views/instance.py
- paasta_tools/marathon_tools.py
- tests/api/test_instance.py
- yelp_package/dockerfiles/itest/api/marathon.json
> Make PaaSTA API work with sharded marathon

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/deployd/master.py
Deployd metrics are broke, need to be fixed asap
> P1: Fix metrics names

- docs/source/autoscaling.rst
- paasta_tools/marathon_tools.py
> deprecates PID policy

- paasta_tools/autoscaling/autoscaling_service_lib.py
dupe of https://github.com/Yelp/paasta/commit/7873bdffad718f12425f840aca94c418bf1a8e5e
in another place.
> fix bug in autoscaler for sharded marathon

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
I think the logic was just backwards?
> Fix paused autoscaler logic bug

- paasta_tools/autoscaling/cluster_boost.py
- paasta_tools/paasta_cluster_boost.py
https://github.com/Yelp/paasta/pull/1587 broke some mypy tests. This fixes them.
> Fix mypy for cluster_boost

- general_itests/pylintrc
- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- requirements.txt
noticed these while glancing through
> A few python3 things

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
> deletes pid decision code

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> PAASTA-13596: fix local_run with healthcheck_only

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> Reexec paasta local-run --pull with sudo when the effective uid is not 0

- paasta_tools/contrib/paasta_update_soa_memcpu.py
I worked with sarth on perf to get this script to do the JIRA work that was being done in the splunk saved_search before.
I have put up an example of what the script does, to see it go to 
r/265677
and
PERF-2647
> Perfscript

- paasta_tools/contrib/paasta_update_soa_memcpu.py
We need the review to be self-publishing so it can run with jenkins.
> adds -p to update_soa review branch command

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
> Skip wait-for-deployment if mark-for-deployment failed

- paasta_tools/cli/cli.py
> help wanted -- fix issue 842

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
> Sanity-check mesos_cpu data.

- paasta_itests/steps/paasta_native_steps.py
- paasta_tools/autoscaling/pause_service_autoscaler.py
- paasta_tools/cli/cmds/logs.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/frameworks/native_service_config.py
- paasta_tools/marathon_dashboard.py
- paasta_tools/marathon_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_cluster_boost.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/setup_marathon_job.py
- paasta_tools/smartstack_tools.py
- paasta_tools/utils.py
- tests/monitoring/test_check_classic_service_replication.py
- tests/test_marathon_tools.py
- tests/test_setup_marathon_job.py
- tests/test_utils.py
This commit was generated automatically by https://github.com/asottile/yesqa
> Remove extraneous `# noqa` comments.

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_wait_for_deployment.py
- tests/test_generate_deployments_for_service.py
* replace generate_deployments_for_service with PaastaServiceConfig
* remove unused generate_deployments_for_service
> Wait for deployment refactoring

- yelp_package/dockerfiles/itest/marathon/Dockerfile
> Use marathon 1.4.10 in itests

- .gitignore
- paasta_tools/api/views/autoscaler.py
- paasta_tools/cli/cmds/autoscale.py
- tests/cli/test_cmds_autoscale.py
I feel a bit bad about not making tests.
But what tests should I *actually* write? I would have to mock out all the things? Maybe it could catch some autospec'y bugs?
> Added a bespoke-autoscale cli helper

- paasta_tools/api/api.py
We've been getting exceptions from paasta-api about closed connections.
The problem occurs when there are multiple requests made to the
instances endpoint at the same time. For autoscaled services we use
ZookeeperPool to pool our connections to zookeeper so that we can get
the correct number of instances. However when the API handles multiple
requests it will call `.stop()` and `.close()` on the zookeeper client
when it is possilbly still being used by another request. This leads to
exceptions like `kazoo.exceptions.ConnectionClosedError`.
I've "fixed" this by adding the `ZookeeperPool` to the api main func so
that we don't tear down the client until the whole api server quits.
> Fix randomly closing ZK connections in paasta-api

- paasta_tools/cli/cmds/boost.py
Add a missing space in the help output
> Add missing space

- paasta_tools/contrib/paasta_update_soa_memcpu.py
Few minor fixes and clarify ticket description after handling the same questions and seeing a few bugs after using this the last 2 weeks.
Update dashboard shortlink to prefill filters.
Don't drop the first result, preserve ordering of latest 3 authors, update ticket desc, dedent to fix no-tick option.
> Tweaks to paasta rightsizer script.

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/contrib/emit_allocated_cpu_metrics.py
> Always emit 'instances' to signalfx for knowing what the desired instance count is

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
cputimes are counters. They represent an absolute number of cpu seconds consumed by a process. In order to measure cpu time consumed you need to calculate the difference between the current cputime of your process and the cputime of this same process N seconds ago.
In the earlier version, I was trying to filter out a single value. It worked in the tests as they all assume that the previous cputime measure was 0
To fix this I first modified the test to simulate tasks that have been running for a long time.
Then I moved the filtering code (behind a feature toggle) where we actually have both delta time and delta cputime available.
> Filtering out the delta cpu_time, not absolute cpu_time

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_cmds_spark_run.py
- tests/cli/test_utils.py
Usage is limited to norcal-devc and pnw-devc at the moment.
> 1st iteration of paasta spark-run

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We have a class of problems at yelp where users are running paasta local-run in a production setting for things like batch jobs.
This "sounds" ok, but it means that we have paasta code that is running in the critical path of these things throughout the life of the batch job. This means that paasta errors show up in the output, etc.
I would prefer for the paasta code to get "out of the way" as soon as possible in this use case, so that we "only" have the docker layer to contend with.
To that end, this patch makes it so that we only ever detach when we have to simulate a healthcheck on a service. This never happens in the "batch" use case. To summarize:
Detach & watch:
* When we have a healtcheck we want to perform and report the results to the user
Execlp:
* Interactive mode
* Any other …
> Make paasta local-run detach only when there is a healthcheck to run.

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
> Run jupyter notebook as non-root, added spark driver options

- yelp_package/dockerfiles/lucid/Dockerfile
This reverts commit 8fa411969c3554680a80216df8d633c69798b522.
Fix internal build failure
> Revert "Drop paasta lucid image"

- yelp_package/dockerfiles/itest/marathon/Dockerfile
marathon-python is passing its tests
> Use marathon 1.4.11 in itests

- paasta_tools/deployd/watchers.py
When the watcher is built for the first time, the event would be set as None according to kazoo document. (http://kazoo.readthedocs.io/en/latest/api/recipe/watchers.html) 
Test this change at mesosstage, and the log shows deployd createed service instance after a new node had been added into zookeeper successfully:
2018-01-31 13:37:10,706:mesos1-uswest1cdevc:DEBUG:paasta_tools.deployd.watchers.AutoscalerWatcher:Node change: data = b'2', stat = ZnodeStat(czxid=253550824220, mzxid=253550824221, ctime=1517434630666, mtime=1517434630669, version=1, cversion=0, aversion=0, ephemeralOwner=0, dataLength=1, numChildren=0, pzxid=253550824220), event = None
2018-01-31 13:37:10,707:mesos1-uswest1cdevc:INFO:paasta_tools.deployd.watchers.AutoscalerWatcher:Number of instances changed or autoscaling …
> paasta deployd watches for new watches when autoscaling is enabled first time

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
I will rebase https://github.com/Yelp/paasta/pull/1726 after merging this.
> Use mesos 1.4.1 in itests

- requirements.txt
- setup.py
> Add mypy version and add it to setup.py

- paasta_tools/cli/cmds/spark_run.py
.tox/py36/bin/paasta spark-run --cluster norcal-devc --cmd pyspark
> Run spark and mesos framework as root

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
This change simplifies the Spark service Dockerfile.
~/paasta/.tox/py36/bin/paasta spark-run --build --cluster norcal-devc --cmd pyspark
~/paasta/.tox/py36/bin/paasta spark-run --build --cluster norcal-devc --cmd jupyter
~/paasta/.tox/py36/bin/paasta spark-run --build --cluster norcal-devc --cmd "spark-submit /spark_client/examples/pi.py"
> Replaced spark-run docker envs with command line options

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/utils.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- tests/cli/test_cmds_metastatus.py
- tests/cli/test_utils.py
- tests/metrics/test_metastatus_lib.py
> Humanize floats in metastatus for cpu/gpu info

- paasta_tools/mesos_maintenance.py
- tests/test_mesos_maintenance.py
Possibly needs more tests, and maybe can remove old code
> Use the operator api for maintenance, draining, and up/down

- paasta_tools/cli/cmds/spark_run.py
Users may want to use a pre-built image to run spark. For example, jupyterhub uses the same image to launch the jupyterhub server and singleuser notebook servers (spark-run).
$ ~/paasta/.tox/py36/bin/paasta spark-run --cluster norcal-devc --image docker-dev.yelpcorp.com/paasta-spark-run-hliu:latest
> Added an option to run spark from a prebuilt image

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
> Use mesos 1.5.0 in itests

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
Example output for yelp-main https://fluffy.yelpcorp.com/i/Nzzv2bbK4w36pQjz5NfkbfPhm5mwQn9D.html
> Allow paasta status to filter by registration.

- paasta_tools/chronos_serviceinit.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_native_serviceinit.py
- paasta_tools/utils.py
- tests/test_chronos_serviceinit.py
- tests/test_marathon_serviceinit.py
- tests/test_mesos_tools.py
> paasta status -v: show mesos tasks for all Marathon app versions

- paasta_tools/cli/cmds/spark_run.py
Tested with "paasta spark-run -c norcal-devc --max-cores 40 --cmd jupyter".
> Make spark-run jupyter kernel culling configurable

- Jenkinsfile
For DSC-1
Tested with the manually-copy-paste-Jenkinsfile-into-configuration workflow at https://jenkins-test.yelpcorp.com/job/Yelp-paasta/
> Initial Jenkinsfile implementation

- paasta_tools/slack.py
- paasta_tools/utils.py
- requirements-minimal.txt
- requirements.txt
I'm hoping this will be a convenient way to put things in slack, with a graceful fallback when a token is not available.
> Added a slack class to make it easy to post notifications to slack.

- paasta_tools/cli/cmds/remote_run.py
@ealter I've raised this as an alternative to your PR - lmk what you think
> default to using the system paasta config for the remote-run cluster

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/paasta_remote_run.py
- paasta_tools/utils.py
Also changed a few things to remove pyrsistent errors.
It looks like we don't have any tests in place for this thing :(
But I did test it manually and it works.
... should I write some tests? :)
> Allow specifying a custom image for remote-run

- paasta_tools/tron_tools.py
Current code generates cleanup_action with name `"None"`, fix it.
> Cleanup cleanup action name

- .pre-commit-config.yaml
- paasta_tools/setup_tron_namespace.py
- requirements-dev-minimal.txt
- requirements-dev.txt
- allow accepting multiple services to update in cli args
- add optional `--all` argument to update all namespaces
> [tron tools] update multiple namespaces in setup_tron_namespace

- paasta_tools/contrib/get_containers_and_ips.py
Since tron/batch services do not supply MESOS_TASK_ID in their docker label
(for obvious reasons), we are updating get_containers_and_ips to use
only the paasta_service and paasta_instance in the mapping generated.
Since we are using only the service and instance fields of the
MESOS_TASK_ID (of otherwise marathon services), this should suffice.
The map generated by this tool is used by the source_required plugin of Yelp/synapse_tools (https://github.com/Yelp/synapse-tools).
Tested manually on batch boxes and a paasta slave.
Further context in TRON-293.
> APOLLO-652: Make get_containers_and_ips.py compatible with tron/batch

- requirements.txt
- setup.py
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/playground/Dockerfile
Various things are broken in the example cluster
> Fix example cluster build

- paasta_tools/api/api.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/service.py
- tests/api/test_service.py
Unit testing:
make test green 
End to end manual testing looking good:
curl localhost:5054/v1/services
{"services": [["hello-world", "main"], ["hello-world", "test_chronos"], ["hello-world", "remote"]]}
> [API] Added a viewer for get_services_for_cluster

- .travis.yml
Currently broken with permission issues on some of this stuff. I suspect
travis does something in a container that rights these and then the pypi
upload can't write them? I think we can just rm and it might work?
> Maybe fix pypi upload

- paasta_tools/cli/cmds/spark_run.py
Tests:
paasta spark-run --spark-args 'spark.eventLog.enabled=true spark.eventLog.dir=s3a://{BUCKET}' --cmd 'spark-submit /work/examples/s3.py'
paasta spark-run --spark-args 'spark.history.fs.logDirectory=s3a://{BUCKET}' --cmd history-server
> Added spark-run command to start a spark history server

- paasta_tools/cli/cmds/secret.py
To metnion the yelp_servlib client library and necessary prefix.
> Edit paasta add secret instructions

- docs/source/about/paasta_principles.rst
Here is the real link:
http://paasta.readthedocs.io/en/latest/soa_configs.html
> Fix broken link to soa_configs.html

- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
> Fix paasta restart for k8s

- paasta_tools/utils.py
```
mjksmith@mydevbox:~/paasta (master) $ paasta local-run --pull -s my_cool_service -c cluster -I
Please pick a deploy group from the choices below (or "quit" to quit):
0: everything
quit
Enter number or name; return for next page
? 
```
> Local run: Don't ask me to pick a deploy group when there's only one

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Easier that I thought, we use the same values we use for marathon,
limits are "hard" requirements are "soft" but used by the scheduler.
I've tested that the code works and creates a deployment with the limits
on the container but haven't tried to actually push a container to see
what happens when you hit the limit.
> Add cpu + mem constraints to k8s

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This is the first pass for TRON-369, which validate team name at pre-commit.
> validate valid team name

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
Fixes internal ticket PAASTA-14651
> Allow chronos rerun to skip services that have not been deployed

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
> Parallelize fetching haproxy state in get_happy_tasks, and limit the number of hosts to query.

- general_itests/local_run.feature
- general_itests/steps/local_run_steps.py
- general_itests/steps/shared_steps.py
- general_itests/steps/validate_steps.py
- general_itests/validate.feature
This is me splitting up my PRs into smaller ones
> Added shared steps for behave

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
This is prerequisite to doing local-run tron.
> Handle a None deploy_group properly

- .travis.yml
- requirements.txt
- yelp_package/dockerfiles/trusty/Dockerfile
tox-pip-extensions is complaining and there is a new version of tox 3
days ago. Pinning back to see if it fixes the build.
> Attempt to fix build

- general_itests/fake_soa_configs_local_run/fake_simple_service/tron-test-cluster.yaml
- general_itests/local_run.feature
- general_itests/steps/local_run_steps.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/tron_tools.py
Should magically go green when I rebase.
> Added paasta local-run support for tron actions

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- tests/test_kubernetes_tools.py
- tests/test_setup_kubernetes_job.py
* pin k8s service instances with EBS to downthenup bounce method
* pin k8s service instances with EBS to instances=1
> Fix k8s ebs bounce

- .travis.yml
This fixes #1946 and the build by pinning tox-pip-extensions in travis.
> pin tox-pip-extensions in travis

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
@vkhromov a fix for the things you mentioned in your review
> Fix some types for k8s

- paasta_tools/list_marathon_service_instances.py
- tests/test_list_marathon_service_instances.py
https://jira.yelpcorp.com/browse/PAASTA-14708
> Changed error logging to 'debug' rather than 'event'

- .pre-commit-config.yaml
- paasta_tools/adhoc_tools.py
- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/logs.py
- paasta_tools/deployd/common.py
- paasta_tools/deployd/leader.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/metrics.py
- paasta_tools/deployd/watchers.py
- paasta_tools/deployd/workers.py
- paasta_tools/drain_lib.py
- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/frameworks/native_service_config.py
- paasta_tools/frameworks/task_store.py
- paasta_tools/iptables.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/tron_tools.py
Automated via:
- `pre-commit autoupdate`
- `pre-commit run --all-files`
- I then had to revert changing the `detect-secrets` version since it broke for some reason? didn't dig into this
Relevant changes:
- [`pyupgrade` learned how to rewrite `super()`](https://github.com/asottile/pyupgrade#super-calls)
> Upgrade pre-commit hooks

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/paasta_service_config_loader.py
- paasta_tools/utils.py
- tests/test_paasta_metastatus.py
https://jira.yelpcorp.com/browse/PAASTA-14724
> Added --service and --instance flags to metastatus command

- paasta_tools/deployd/leader.py
- paasta_tools/deployd/master.py
- tests/deployd/test_deployd_master.py
* Fix a bug where the startup stalls and process doesn't exit on abdication
* Add some logging to help catch other leadership bugs
> Deployd leader problems

- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
JSON schema doesn't know about real types like float :-(
> Make cpu_burst_add a number in json schema

- requirements-dev-minimal.txt
- requirements-dev.txt
I'll merge when this goes green
> fix hypothesis deps

- paasta_tools/clusterman.py
This was re-introduced by the refactoring that happened in #1979 (but I think this solution is a little better than the one I originally had anyway)
> Fix regression in manpages build

- paasta_tools/tron_tools.py
Fields related to external job dependencies.
> Add missing tron action fields

- paasta_tools/autoscaling/cluster_boost.py
I actually tested this this time and confirmed that metrics show up in DynamoDB.
> fix cluster boost

- debian/paasta-tools.links
- paasta_tools/check_kubernetes_services_replication.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/mesos_tools.py
- paasta_tools/monitoring_tools.py
- paasta_tools/smartstack_tools.py
- setup.py
- tests/test_check_kubernetes_services_replication.py
- tests/test_check_marathon_services_replication.py
- tests/test_kubernetes_tools.py
- tests/test_long_running_service_tools.py
- tests/test_mesos_tools.py
- tests/test_monitoring_tools.py
- tests/test_smartstack_tools.py
- yelp_package/itest/ubuntu.sh
* move black/whitelist checks to `long_running_service_tools`
* move `send_replication_event_if_under_replication` to `monitoring_tools`
* add check_kubernetes_services_replication script and necessary additions to `kubernetes_tools` to make it work
> Add check k8s replication

- paasta_tools/contrib/shared_ip_check.py
I feel a tad dirty overloading this check. It is certainly within the same spirit of what the check does, but it checks for two ports using the same ip instead of two containers using the same ip?
The output on the failing host looks like this:
```
OK - No Docker containers sharing an IP on this host.
CRITICAL - This is the second time we've seen a rule with the same target_parameters!
Rule(protocol='tcp', src='0.0.0.0/0.0.0.0', dst='0.0.0.0/0.0.0.0', target='DNAT', matches=(('tcp', (('dport', ('31537',)),)),), target_parameters=(('to-destination', ('169.254.0.24:8888',)),))
The other rule is:
Rule(protocol='tcp', src='0.0.0.0/0.0.0.0', dst='0.0.0.0/0.0.0.0', target='DNAT', matches=(('tcp', (('dport', ('31880',)),)),), target_parameters=(('to-destination', ('169.254.0.24:8888',)),))
``` …
> Expanded the shared_ip check to also check iptables rules

- paasta_tools/cli/utils.py
The test result is [here](https://fluffy.yelpcorp.com/i/XWqKMPFmvrKF3ZPS5jDxBrbgnwk47plS.html)
> generate_deployment_for_service includes Tron instances

- .pre-commit-config.yaml
- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/chronos_tools.py
- paasta_tools/firewall.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/marathon_dashboard.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/mesos_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/utils.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/metrics/test_metastatus_lib.py
- tests/test_kubernetes_tools.py
- tests/test_paasta_metastatus.py
```
$ PAASTA_SYSTEM_CONFIG_DIR=$HOME/paasta-config USE_API_ENDPOINT=1 paasta metastatus -c kubestage
Cluster: kubestage
No dashboards configured for kubestage!
Master paasta_tools version: 0.81.3
Mesos Status: OK
Marathon Status: OK
Kubernetes Status: OK
Chronos Status: OK
```
```
$ PAASTA_SYSTEM_CONFIG_DIR=$HOME/paasta-config USE_API_ENDPOINT=1 paasta metastatus -c kubestage -v
Cluster: kubestage
No dashboards configured for kubestage!
Master paasta_tools version: 0.81.3
Mesos Status: OK
Mesos is not configured to run here
Marathon Status: OK
Marathon is not configured to run here
Kubernetes Status: OK
Kubernetes deployments:   8
Pods: running: 30 pending: 1 failed: 0
CPUs: 0.00 / 54 in use (0.00%)
Memory: 0.59 / 110.83GB in use (0.53%)
Disk: 46.49 / 464.94GB in use (10.00%)
No GPUs …
```
> `paasta metastatus` for Kubernetes

- paasta_tools/utils.py
- tests/test_utils.py
> Support dicts for jobs/actions when getting list of Tron instances

- paasta_itests/paasta_native.feature
- paasta_itests/paasta_native_task_store.feature
This is probably masking a real issue, probably.
> Skip paasta native itests

- paasta_tools/cli/schemas/tron_schema.json
- Add precious attribute to tron monitoring schema
- None
> Add precious attr to tron schema

- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/chronos_schema.json
- move definitions section in  chronos schema where it belongs
- print more friendly message when loading  schema errors out
> Fix chronos schema

- yelp_package/dockerfiles/hacheck-sidecar/Dockerfile
- yelp_package/dockerfiles/hacheck-sidecar/Makefile
- yelp_package/dockerfiles/hacheck-sidecar/README
- yelp_package/dockerfiles/hacheck-sidecar/check_smartstack_up.sh
- yelp_package/dockerfiles/hacheck-sidecar/hacheck.conf.yaml
This is an example to use as a sidecar in k8s. See code here:
https://github.com/Yelp/paasta/blob/master/paasta_tools/kubernetes_tools.py#L347-L364
cc @Rob-Johnson @vkhromov
> Add hacheck sidecar Dockerfile

- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
While here also fix flake8 errors and typing annotations.
> Fix `get_all_namespaces()` return type

- docs/source/yelpsoa_configs.rst
I'm not super sure where "best" to put this.
> Added a note explaining which http return codes are healthy.

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
cc @henryzhangsta 
This adds a `--sha` option to `local-run --pull`.
> Add --sha argument to local-run.

- paasta_tools/setup_kubernetes_cr.py
- tests/test_setup_kubernetes_cr.py
Missed these in the refactor in 7c8242d15cff9b9d7e55a796ee49bd1031efc310
> Fix labels in setup_kubernetes_cr

- paasta_tools/monitoring_tools.py
> issue #2118: typo in monitoring tools

- paasta_tools/contrib/kill_bad_containers.py
I think we are ready to auto-remediate this situation instead of just alerting on it.
cc @qui @bplotnick
> Added a script to kill bad containers that share ips or ports

- paasta_tools/automatic_rollbacks.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/slack.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/test_automatic_rollbacks.py
Although not implemented yet, this adds buttons that will make it easier for me to test and collect data with.
> Added non-functional automatic rollback buttons

- paasta_tools/automatic_rollbacks.py
- tests/test_automatic_rollbacks.py
Depends on https://github.com/Yelp/paasta/pull/2142.
This adds a basic tailer that can watch the webhooks and acknowledge button presses.
> Rollback tailer

- paasta_tools/automatic_rollbacks.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/test_automatic_rollbacks.py
I can dry out the button creation if you want.
> Added fancier buttons and the ability to control the states

- paasta_tools/automatic_rollbacks.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_mark_for_deployment.py
In theory this is behind the `--auto-rollback` feature toggle, should be safe to apply.
Doesn't block me though, I can base off this branch.
> Get the state machine again

- paasta_tools/automatic_rollbacks.py
- paasta_tools/cli/cmds/logs.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_logs.py
This is an incremental step towards making the buttons do things.
> Added a slack_events tailing thread to the mark-for-deployment state machine

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
I tested by changing paasta endpoint to localhost, ran the updated paasta api, and then ran this updated client. 
Test result: the first part is message received from api.
https://fluffy.yelpcorp.com/i/tLMB4NlNxgP880cLbZ0QXqjqb8hSHxqK.html
> Added tron jobs to paasta status. paasta client part

- tests/api/test_instance.py
> Fixed tests

- paasta_tools/cli/schemas/tron_schema.json
Add priority to tron_schema.json (TRON-1051)
> Update tron_schema.json to add priority

- paasta_tools/contrib/paasta_update_soa_memcpu.py
For jira ticket creation 'PERF' has been disabled. Updating this to 'PEOBS'. Also with the right email address for peobs.
> update PERF references to PEOBS

- paasta_tools/cli/cmds/mark_for_deployment.py
Seems like a cheap way to make sure we only look at the events for our "thread" ?
> Make it so button presses only activate for a relevant thread

- paasta_tools/check_spark_jobs.py
- paasta_tools/mesos/framework.py
- tests/test_check_spark_jobs.py
Planning on running this as a cron job on masters and sending the output of the script to our team. The output will allow us to follow up with teams in case the jobs continue to run or some jobs don't correspond to valid services.
> Add script for notifying teams about long-running Spark jobs

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/flink_tools.py
- paasta_tools/utils.py
- tests/test_setup_kubernetes_cr.py
- tests/test_utils.py
Work for internal ticket FLINK-1141.  Not straightforward to test without merging. Open to ideas.
> Rename flinkcluster to flink

- yelp_package/dockerfiles/itest/hacheck/Dockerfile
> Pin hacheck build deps for test consistency

- general_itests/fake_soa_configs_validate/fake_valid_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/deploy.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/marathon-test-cluster.yaml
- paasta_tools/chronos_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_setup_chronos_job.py
- tests/test_tron_tools.py
> Added deploy_group validation to all paasta instances, not just tron

- paasta_tools/contrib/kill_bad_containers.py
This expands the functionality to handle the situation where orphaned iptables rules are left behind.
@sergsyelp
> Make kill_bad_containers clean up orphaned iptables rules

- paasta_tools/contrib/paasta_update_soa_memcpu.py
Before:
automatically updating myservice/foo-mycluster.yaml for over-provisioned cpu
After:
Rightsizing myservice.main in mycluster to make it not have over-provisioned cpu
> Try to make a better reviewboard title for the paasta rightsizer.

- requirements.txt
This new version does a much better job with strings and long lines.
> Bump ruamel for better yaml parsing

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
Skip if there are no secrets to sync
> Fix secrets syncer FileNotFoundError

- paasta_itests/steps/paasta_deployd_steps.py
I think this is the reason itests are failing so persistently in Jenkins.
> Prevent deployd from blocking on stderr in itests

- paasta_tools/tron_tools.py
I guess I extracted this function, but didn't add test coverage for it.
I can add some if you think it is warranted.
> Fix master config tron yaml loading

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This is based off of https://github.com/Yelp/paasta/pull/2249 and will be easier to read once merged.
> No jobs keyword

- paasta_tools/contrib/check_orphans.py
Since we only have basically one service that we need to blacklist in this version (other unreachable services will just fail quickly), @solarkennedy was right and we should just take the blacklisted services via command line
> orphan_checker: take blacklisted services via command line

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
We can't assume args for an exception
> Fix exception in s_m_j exception handling

- debian/paasta-tools.links
- paasta_tools/cassandracluster_tools.py
- paasta_tools/check_cassandracluster_services_replication.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- setup.py
- tests/test_utils.py
- yelp_package/itest/ubuntu.sh
Included is a bunch of boilerplate so that generate_deployments will
work for cassandracluster files.
> Add cassandracluster replication checker

- paasta_tools/drain_lib.py
- paasta_tools/hacheck.py
- requirements-minimal.txt
- requirements.txt
- tests/deployd/test_watchers.py
- tox.ini
This is to get on a new version with fixes to the timeout logic for the
client. We think this has been causing mass timeouts on calls to
hacheck. Testing on mesosstage this version does seem to work better.
Let's see if travis passes all the tests...
> Bump aiohttp

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
This reverts commit bf854de120b6d0d05bd1e322343a047cdf46dd93.
> Revert "enable spark event logging by default (#2309)"

- paasta_tools/automatic_rollbacks/slo.py
- yelp_package/extra_requirements_yelp.txt
This ended up being kinda tricky.
@kennydo I've asked for your review because I'd like to make sure I'm not doing something wrong with this logic -- and to make sure that (timeseries, metric) is sufficient to identify an slo group.
> Ignore SLOs with silent: true

- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_marathon_tools.py
This is old code I stumbled upon. We finished the mesos http transition long ago.
> only support mesos-based http healthchecks

- setup.py
It seems I need this to be able to run cleanup_kubernetes_jobs command on paasta directly.
> add cleanup_kubernetes_jobs.py to setup.py

- general_itests/steps/deployments_json_steps.py
- paasta_tools/automatic_rollbacks/slack.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/slack.py
- tests/cli/test_cmds_mark_for_deployment.py
I'm sure I've got lots of dead code still in here.
> Removed the non-state machine code for mark-for-deployment

- paasta_itests/steps/cleanup_marathon_job_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
There is nothing I need to change in puppet. I tested the commands on kubestage, and they all work.
> Fix kuberntes folder immport by running itests scripts as modules

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
tested locally with get_default_event_log_dir output the expected result
> spark event logging decides bucket based on aws credentials account

- paasta_tools/deployd/common.py
- tests/deployd/test_common.py
A simpler version of https://github.com/Yelp/paasta/pull/2357
> A third implementation of DelayDeadlineQueue that uses a background thread but not asyncio

- paasta_tools/kubernetes_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/tron_tools.py
- tox.ini
I need to upgrade mypy so get method in typeddict could be recognized. https://github.com/python/mypy/issues/3843
> upgraded mypy to 0.711

- paasta_tools/kubernetes/application/controller_wrappers.py
- tests/kubernetes/application/test_controller_wrapper.py
I was correct but  mistakenly "fixed" this after I added test....
> Fixed a typo/bug in ensure_pod_disruption_budget

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
Support two simple options for storage class name attribute for persistent volumes: `ebs` and `ebs-slow`.
> K8s storage classes

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/settings.py
- paasta_tools/api/views/instance.py
- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos/task.py
- paasta_tools/mesos_tools.py
- paasta_tools/smartstack_tools.py
- tests/api/test_instance.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/cli/test_cmds_status.py
- tests/test_marathon_serviceinit.py
- tests/test_mesos_tools.py
Eek, this is kind of big 😬 
Mostly this is a rough copy of just the data fetching parts of marathon_serviceinit.
> Marathon status api endpoint

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
The old logic for calculating authors was to take the SHA of the production_deploy_group and look at all of the changes between it and the new SHA.
In 3415c34231911f37626d3c645e99c8dee98c8d0e we lost this logic and now we're calculating authors between the old SHA for _this_ deploy group and the new SHA.
This is causing people to get pinged for pushes they're not part of. For example, if you run a push through stagef, then afterwards a second push through stageg, the people pinged in the second push will be the authors from _both_ pushes (since stageg was never updated after the first push). Additionally, we have the problem again where if we ever bump the legacy deploy groups, we'll ping everybody who has touched yelp-main in the last year (or whatever).
> Only notify authors for changes since the production_deploy_group's SHA

- paasta_tools/autoscaling/autoscaling_service_lib.py
I changed these names a long time ago
> Fix the dimensions exported by the autoscaler code. PAASTA-15725

- paasta_itests/paasta_api.feature
- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
This formats the output of the changes in https://github.com/Yelp/paasta/pull/2317
Now ready for review
> format output of updated marathon instance status api endpoint

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/setup_marathon_job.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/test_setup_marathon_job.py
This reverts commit dd69e114d4d4cfa83229078da2feb64b64c4e8a9, reversing
changes made to f675fb028d6865ddf8a4280468fea03427ba7eb7.
(these were made in https://github.com/Yelp/paasta/pull/2345)
> Revert "Merge branch 'drmorr/fix_min_instances_clamping_bug'"

- paasta_tools/async_utils.py
When I run the API server locally with `PYTHONASYNCIODEBUG=1` I get errors like 
```
ERROR:asyncio:<CoroWrapper get_cached_list_of_running_tasks_from_frameworks() running at /nail/home/selston/pg/paasta/paasta_tools/mesos_tools.py:225, created at /usr/lib/python3.6/asyncio/coroutines.py:84> was never yielded from
```
> don't create coroutines that we never await in async_ttl_cache

- paasta_tools/marathon_tools.py
A much shorter patch would have been to just change `datetime.datetime.now()` to `datetime.datetime.utcnow()`, but I think I'm of the opinion that naive datetimes are almost always an antipattern.
> Make is_old_task_missing_healthchecks deal with tz-aware datetimes

- docs/source/yelpsoa_configs.rst
- paasta_tools/api/views/instance.py
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/smartstack_tools.py
- paasta_tools/utils.py
- tests/api/test_instance.py
- tests/test_marathon_serviceinit.py
- tests/test_smartstack_tools.py
- tests/test_utils.py
I still have one test failure thats not related to my changes :| 
or maybe it is?
in test_kube_get_allowed_locations_and_hosts
E   AssertionError: Expected call: get_nodes_grouped_by_attribute(attribute='region', nodes=<function filter_nodes_by_blacklist at 0x7efff9900e18>)
E   Actual call: get_nodes_grouped_by_attribute(attribute='region', nodes=[<Mock id='139638379819696'>])
> Paasta 15613 nuke monitoring blacklist

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
So it turns out my previous fix was in the wrong place: when marathon does a leader election, it doesn't think that the task is unhealthy, it thinks it's unknown, which means that it's defined but hasn't ever executed.  So this code moves the `is_old_whatever` check.
I confirmed that this fixes the issue by hot-patching s-m-j on norcal-devc.
> trying to fix get_happy_tasks/bouncing again

- docs/source/installation/example_cluster.rst
- docs/source/testing.rst
@poros please tell me where you want more/less detail and I'll iterate on this
> add some more documentation on testing paasta

- paasta_tools/async_utils.py
- tests/test_async_utils.py
Make async_ttl_cache handle case where another coroutine deleted the cache entry it was waiting on
> Make async ttl cache handle deleted entries

- paasta_tools/check_services_replication_tools.py
Just get rid of this already, it no longer applies.
> Remove obsolete reference to PERCENTAGE

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/utils.py
- tests/test_utils.py
git grep ulimit returns nothing in this branch and also in yelpsoa-configs
> deprecate_ulimit

- paasta_tools/kubernetes/application/controller_wrappers.py
> fixed a couple cleanup_kubernetes_jobs bugs

- paasta_tools/async_utils.py
- tests/test_async_utils.py
We still shouldn't use `self` while making the key from args.
> Fix memory leak, again

- paasta_tools/cli/schemas/kubernetes_schema.json
Add the configurations shown in `marathon_schema.json`.
> make sure k8s schema supports everything in marathon schema

- paasta_tools/kubernetes/application/controller_wrappers.py
I forgot 0 means false in Python :(
> Fix a bug when instance is 0 in setup_kubernetes_jobs

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/marathon_tools.py
- paasta_tools/smartstack_tools.py
- tests/api/test_instance.py
- tests/cli/test_cmds_status.py
- tests/cli/test_cmds_wait_for_deployment.py
- tests/test_smartstack_tools.py
This shows the smartstack status.
Sample output looks like: https://fluffy.yelpcorp.com/i/0hK83L3sWXcMGlrBDnX8J3dTj1dMTSmg.html
> show health check status for verbose option

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
We don't use that anymore https://github.com/Yelp/paasta/blob/master/paasta_tools/api/api_docs/swagger.json#L976
> clean up smartstack error messages code

- paasta_tools/kubernetes_tools.py
I made a similar fix before but that's another one.
> fix the bug that cannot replica cannot be 0

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/kubernetes_tools.py
- tests/cli/test_cmds_status.py
It will look like https://fluffy.yelpcorp.com/i/7l1xdNT1Pt78DZRxqh35SZDnKx3sqpdB.html
> show replicaset for verbose option

- requirements-dev-minimal.txt
- requirements-dev.txt
if it is in requirements{.txt, -minimal.txt} then it doesn't also need
to be in requirements-dev*
> remove duplicate requirement

- paasta_tools/cli/cmds/spark_run.py
I haven't really tested this yet, I'll do that tomorrow-ish.
> make PAASTA_INSTANCE tron-aware

- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/kafkacluster_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
Think this is all we need to support adding kafkacluster yelpsoa files.
> Add KafkaCluster boilerplate

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
And also the secret names should be lower case because for some reason
k8s wants everything to be a possible DNS name even secret names...
> Ensure secret names are lower case for k8s

- paasta_tools/deployd/common.py
- paasta_tools/kubernetes_tools.py
While here also fix black error
> Add ignore for mypy error

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
First change "suggested" by black, the other change found when trying to trigger test failure
> Fix is ready check

- .pre-commit-config.yaml
- paasta_itests/steps/setup_steps.py
- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/contrib/check_orphans.py
- paasta_tools/contrib/get_running_task_allocation.py
- paasta_tools/deployd/common.py
- paasta_tools/deployd/workers.py
- paasta_tools/drain_lib.py
- paasta_tools/list_marathon_service_instances.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos/mesos_file.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/metrics/metrics_lib.py
- paasta_tools/paasta_remote_run.py
- paasta_tools/smartstack_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_help.py
- tests/cli/test_cmds_status.py
- tests/deployd/test_queue.py
- tests/test_bounce_lib.py
- tests/test_check_kubernetes_services_replication.py
- tests/test_check_marathon_services_replication.py
- tests/test_firewall.py
- tests/test_iptables.py
- tests/test_marathon_tools.py
- tests/test_monitoring_tools.py
- tests/test_remote_git.py
- tests/test_setup_marathon_job.py
> Use black 19.10b0

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/kubernetes_tools.py
- tests/cli/test_cmds_status.py
Sample output is here: https://fluffy.yelpcorp.com/i/l4C5W1WXnbLmXMtkXkGqN5m17qB3x1gG.html
This PR contains a bug fix for 0 ready_replicas of the replicaset as well.
> add vv option for kubernete instances

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
> fix paasta status for marathon and tron instances

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
I noticed the default bounce method is set to brutal. I corrected it.
> fix default bounce method

- paasta_tools/cleanup_kubernetes_cr.py
- paasta_tools/cleanup_kubernetes_crd.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes/application/tools.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/setup_kubernetes_crd.py
- tests/test_cleanup_kubernetes_jobs.py
- tests/test_kubernetes_tools.py
- tests/test_setup_kubernetes_cr.py
> Cleanup old kubernetes labels

- paasta_tools/api/views/instance.py
- paasta_tools/cassandracluster_tools.py
- paasta_tools/cli/utils.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- tests/api/test_instance.py
- tests/cli/test_utils.py
- tests/test_kubernetes_tools.py
See individual commits but basically trying to make `paasta status` show more kubernetes info for CassandraClusters
> Make cassandra paasta status work

- paasta_tools/kubernetes/application/controller_wrappers.py
- tests/kubernetes/application/test_controller_wrapper.py
See subject.
https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
> Dont ensure both min_available and max_unavailable in pod disruption budget

- paasta_tools/cli/cmds/status.py
Changes related to FLINK-1827. Tested the changes on devbox and changes are working as expected.
> Show dashboard link regardless of the state of the flink cluster

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_metastatus.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
I think this is the last PR to remove for this cleanup.
> Removed last bits of ssh-based status/metastatus execution

- paasta_tools/cli/cmds/status.py
The Flink operator is already returning a pod_status list. 
This change incorporates that info into `paasta status`.
Here is how the status would look like:
```
service: xxxxx
cluster: xxxxx
instance: main_k8s_copy
Git sha:    97cd8b76 (desired)
Config SHA: 2c215c54
Flink version: 1.6.4
URL: http://xxxxx/
State: running
Pods: 7 running, 0 evicted, 0 other
Jobs: 1 running, 0 finished, 0 failed, 0 cancelled
5 taskmanagers, 1/5 slots available
Jobs:
Job Name                     State       Started
xxxxxxx                      RUNNING     2019-11-21 05:51:40 (4 hours ago)
```
Running in verbose mode would produce the following pod list:
```
Pods:
Pod Name      Host                         Phase
xxxxxx        ip-x-x-x-x.compute.internal  Running
xxxxxx        ip-x-x-x-x.compute.internal …
```
> Report evicted pods when running paasta status on flink resources

- yelp_package/dockerfiles/trusty/Dockerfile
Applied the workaround from
https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5682159.html
> Fix Trusty itest

- paasta_tools/check_flink_services_health.py
- paasta_tools/monitoring_tools.py
- tests/test_check_flink_services_health.py
```
check_flink_services_health sends a single event per service instance
FLINK-1982
The event is going to be a combination of all the 4 checks we have in
place.
In order to re-use as much as possible the code in monitoring_tools.py,
I added an helper function where I factored out the logic for the
under-replication check without the actual sending of the event. I am
happy to change the tests for monitoring_tools.py too if you want me to;
I didn't do it to minimize the overall lines of code changed given that
I only factored out code and added a return statement.
```
```
Refactor check_under_reported_taskmanagers for better testing
FLINK-1982
This way I am able to fully test the function directly without relying
on multiple mocks in the caller.
```
> check_flink_services_health sends a single event per service instance

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
I kinda want to add a couple tests to this to make sure it's doing the right thing for commands we expect, but I didn't get around to it today.  When I get back, i guess.
> add command for adhoc spark run

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
How sophisticated we need here? I am not sure. We have a plan to retire hacheck sidecar, and it's the only sidecar we use now.
> specify sidecar resource requirements

- yelp_package/extra_requirements_yelp.txt
Lots of improvements to slo transcoder including schema changes that are required to validate SLOs for newly supported services
> Bump slo transcoder dependency

- paasta_tools/cli/schemas/kubernetes_schema.json
Corresponding review: https://github.com/Yelp/paasta/pull/2481/files#diff-d2db6a5d9fbe5697e2c04f391ebed4ccR204
> add iam_role config

- paasta_tools/kubernetes/application/controller_wrappers.py
I noticed that this HPA is not created when max_instances is removed.
> fix a small new autoscaler only bug

- paasta_tools/kubernetes/application/controller_wrappers.py
I think this should return true or false.
> fix another autoscaler bug

- docs/source/generated/paasta_tools.rst
- paasta_tools/kubernetes_tools.py
> Revert "Remove hardcoded paasta.yelp.com/ prefixes"

- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- tests/api/test_instance.py
> Revert "Kubernetes active sha fix"

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/secret_tools.py
- tests/cli/test_cmds_local_run.py
- tests/test_secret_tools.py
A follow-up PR will make paasta spark-run to use the helper function.
> Move decryption out of paasta local-run cmd

- paasta_tools/cli/cmds/spark_run.py
when I moved this to `spark_tools.py` I forgot to make sure the right arguments got passed in.  Mypy is now enabled on this function (and confirmed that this would have caught the bug).
I also spot-checked the other functions that got moved out of `spark_run.py` and confirmed that these are getting called with the correct arguments.
> fix AWS credentials regression

- paasta_tools/api/api.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/deploy_queue.py
- tests/api/test_deploy_queue.py
I already tested this locally -- I can pb you the output if you'd like.
> add api endpoint to return deploy queue

- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
jsonschema in python won't complain this, but [gojsonschema](https://github.com/xeipuuv/gojsonschema) in golang will.
> fix paasta schema bug

- paasta_tools/api/views/instance.py
- paasta_tools/cleanup_kubernetes_cr.py
- paasta_tools/cleanup_kubernetes_crd.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes/application/tools.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/setup_kubernetes_cr.py
- paasta_tools/setup_kubernetes_crd.py
- paasta_tools/smartstack_tools.py
- paasta_tools/utils.py
- tests/api/test_instance.py
- tests/instance/test_kubernetes.py
- tests/test_kubernetes_tools.py
- tests/test_utils.py
Re-merge of
- More consistent paasta prefixed attributes #2581 
- Instance support modules #2590 
- Kubernetes active sha fix #2600 
- Remove hardcoded paasta.yelp.com/ prefixes #2603
> First-class instance modules and initial kubernetes instance module

- paasta_tools/check_flink_services_health.py
... to yelp.com/container-type
> Switch flink-container-type label

- debian/rules
- requirements-bootstrap.txt
- tests/kubernetes/application/test_controller_wrapper.py
- tests/test_kubernetes_tools.py
@Bronek pointed out a couple of failed HPA tests. I fixed them.
> Fix failed HPA tests

- paasta_tools/contrib/paasta_update_soa_memcpu.py
> Fix JIRA import issue and add filter to Splunk criteria

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
A follow-up puppet change is needed to make sure paasta vault token file
is present in tron servers.
> Read spark.mesos.secret from vault

- paasta_tools/cli/cmds/mark_for_deployment.py
Example:
https://yelp.slack.com/archives/CA7BTF81J/p1578612542402700
Testing is just manual so far, it is pretty hard to write automated tests for these as is, but let me know what you think I could realistically do.
This is just a first pass. Second pass will just get the status for them, but telling them the exact status command is a great start I think.
> Added a reminder in slack notifications to run paasta status if it takes too long

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
> Revert "Read spark.mesos.secret from vault"

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
We just pass in the `SHARED_SECRET` into the environment of each of the executors.  If I understand how this all works correctly, this is what we want?
> revert vault changes and just pass in the shared secret env var

- paasta_tools/tron_tools.py
Duplicating logic here: https://github.com/Yelp/paasta/blob/master/paasta_tools/tron_tools.py#L574
I debating pulling this out into its own function but it didn't really seem worth it?  IDK, I could be convinced to do it better, though.
> fix docker_url for validation

- docs/source/generated/paasta_tools.envoy_tools.rst
- requirements-minimal.txt
- requirements.txt
This PR also added generated envoy_tools.rst doc file.
> Bump service_configuration_lib version

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/utils.py
- tests/kubernetes/application/test_controller_wrapper.py
this will enable us to have spotinst scale us down a bit more intelligently
> allow setting max_unavailable in the system_paasta_config

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
This is required for spark drivers running inside containers to have
bi-directional communication with mesos master.
> Enforce --net=host for spark type executor

- paasta_tools/setup_kubernetes_cr.py
So the script will still exit with 1. But the exception is caught. So setting up other cr won't be affected.
> Catch NoDeploymentsAvailable exception in setup_kubernetes_cr

- docs/source/hpa.rst
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
https://github.com/Yelp/fullerite/pull/434
> Fix external metrics (for uwsgi/http)

- paasta_tools/kafkacluster_tools.py
It used to be kafkacluster before I incorrectly refactored it: https://github.com/Yelp/paasta/pull/2683/files#diff-0d44e5e2fce89bc20646d34e095c7c73L104
> Filename should be kafkacluster

- paasta_tools/contrib/paasta_update_soa_memcpu.py
Adding info on the search used. This will us help differentiate between changes from the cpu report vs the mem report, for example, and in general, I think it will be nice to have more information on how the recommendations were generated in the git history.
> Attribute source for bulk commits and reviews

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/mesos_tools.py
The big win here is adding a timeout here. 
When running from a devbox it "only" fails in 15 seconds (3 * 5) instead of 15 minutes.
> Set sane timeouts and a friendly error message when the Mesos leader is unavailable

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Providing a more meaningful/distinguishable name so that we can better search the job on history server
> use batch name as spark app name 

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
This reverts commit d8a763bd46f1271d86e17b68b3a8be7a17fd327f.
The previous one seems to cause some issue. Reverting and will be working on the fix.
> Revert "use batch name as spark app name  (#2695)"

- paasta_tools/kubernetes/application/controller_wrappers.py
Right now, we only set replicas to 0.
> delete HPA when paasta stop runs

- paasta_tools/kubernetes_tools.py
-vv output: https://fluffy.yelpcorp.com/i/bsvwdKbBXkQNvhBmFzJ8JHRC3pjHLvb2.html
-vvv output: https://fluffy.yelpcorp.com/i/DsbwZ2cQP698xT19R808j64wVB5hFJLg.html
> make paasta metastatus understand k8s pool

- tests/deployd/test_queue.py
This fails half the time, and doesn't give me confidence in it.
> Removed the flakey deployd queue tests

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
Although this makes our auto scaler slower, because it starts to queue requests, it does eliminate the timeout errors.
> Always run all asyncio requests in a single session instead of one session per request

- paasta_tools/broadcast_log_to_services.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/tron_tools.py
- setup.py
- tests/test_tron_tools.py
This script is useful to emit things like "This server going down for maintenance" .
This PR adds support to Tron tasks as well as k8s ones.
> Made paasta_broadcast_log work with k8s and mesos

- paasta_tools/setup_kubernetes_job.py
- tests/test_setup_kubernetes_job.py
This PR also changes the default log level from warning to info for more
verbosity.
> Log service instance update list

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Internal ticket: PAASTA-16641. This is going to cause a big bounce.
> Set pod's dns policy to Default to use node's dns resolver

- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_generate_deployments_for_service.py
- tests/test_marathon_tools.py
- tests/test_tron_tools.py
- tests/test_utils.py
Redo of https://github.com/Yelp/paasta/pull/2814 in which I forgot to check whether the tests passed before merging.
Now that CID has moved the yelp-main git repo over, we're actually down to ~5 seconds.
> Speed up generate deployments for service again

- paasta_tools/setup_kubernetes_cr.py
Skip template entries after loading
> Fix setup_kubernetes_cr for template entries

- paasta_tools/instance/kubernetes.py
- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
PAASTA-16813
Comparison of output of a canary instance: https://fluffy.yelpcorp.com/i/49Mdt27c7klDlmjmPn3V1vzF8PXVCVfL.html
Comparison of output of a main instance: https://fluffy.yelpcorp.com/i/jV94w1nGDRQg2R2GHr2XFTBFdcfbmGnM.html (note the time difference: 2s for this branch versus 15s for the actual production paasta api. Sometimes the prod paasta API hits the 30s worker timeout enforced by gunicorn and returns a 502.
> Parallelize fetching events from kubernetes in API status endpoint, 

- yelp_package/Makefile
build paasta entrypoint using paasta-tools-go make, download release tag and verify checksum
> Improve paasta entrypoint build

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Adding support for defining prestop hook and termination grace period in PaaSTA. An example configuration for this would be as follow
```yaml
cpu: 2
lifecycle:
termination_grace_period_s: 10
pre_stop_command: 
- /bin/bash
- C
- sleep 30
```
`make test` passed and added new tests
> MONK-1127 Adding support for prestop hook and termination grace period in paasta

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
Adds support for `ebs-retain` storage class in PaaSTA
> MONK-1128  Adding support for ebs-retain storage class

- paasta_tools/kubernetes/bin/kubernetes_remove_evicted_pods.py
- tests/kubernetes/bin/test_kubernetes_remove_evicted_pods.py
> Make kubernetes_remove_evicted_pods handle pods without labels

- paasta_tools/cli/cmds/status.py
- tests/cli/test_cmds_status.py
- Indicate when a rolling-restart is in progress.
- Show only brokers when not verbose, show pod details when verbose.
(re-use logic from flink)
Output when restarting a cluster: https://fluffy.yelpcorp.com/i/K4P5t2N0q6Wz0s1bnDXQvR7rM1l0P6Q8.html
Non-verbose output: https://fluffy.yelpcorp.com/i/bvwKrXvjVtW1Cz6Vb4SWqcf7wkS2LFvs.html
Verbose output: https://fluffy.yelpcorp.com/i/PvvmDJ0H45Ss0xF1c4r04hCk2hwdb5K3.html
> Improve paasta status for Kafka clusters

- paasta_tools/check_oom_events.py
If there haven't been any OOM events recorded in the last day, the
scribe stream to track the OOM events will be empty.  This will make the
OOM checker script crash.  This fix prevents a crash in this case.
(Unfortunately if you get the scribe stream name wrong it will _also_
return the same exception, I don't know any good way to get around
that).
> Fix the check OOM event script if there aren't any OOMs

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
Adding schema for changes in https://github.com/Yelp/paasta/pull/2867 and standardizing timeout field name
> Adding schema for prestop hook in PaaSTA

- paasta_tools/contrib/rightsizer_soaconfigs_update.py
The jenkins job currently hardcodes sysgit, after this change is released I can remove it so it uses the default from the config.
> Use default git remote in config for rightsizer_soaconfigs_update.py

- paasta_tools/api/api.py
docs: https://docs.gunicorn.org/en/stable/settings.html#timeout
> Add option for gunicorn worker timeouts to the api

- paasta_tools/check_flink_services_health.py
- paasta_tools/flink_tools.py
- tests/test_check_flink_services_health.py
- tests/test_flink_tools.py
Fixing the flink service health check based on changes released in #2925
Changes tested on infrastage : https://fluffy.yelpcorp.com/i/WHmQ80fvg45tZczQB1nQK755VG6tHkn6.html
> Updating flink service check to point to correct dashboard url

- requirements.txt
bump service-configuration-lib
> bump service-configuration-lib to 2.5.2

- paasta_tools/api/client.py
pre-commit hook fails: https://jenkins-george.yelpcorp.com/job/mirrors-Yelp-paasta/2266/console
> Fix import order

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/paastaapi/model/instance_status_kubernetes.py
- paasta_tools/paastaapi/model/instance_status_marathon.py
> Return null config_sha when k8s objects don't have config_sha annotation

- paasta_tools/instance/kubernetes.py
- tests/instance/test_kubernetes.py
Use correct service name for mesh data in paasta status for kubernetes instances
> Fix paasta status mesh data for kubernetes instances

- yelp_package/dockerfiles/uwsgi_exporter-sidecar/.gitignore
- yelp_package/dockerfiles/uwsgi_exporter-sidecar/Dockerfile
- yelp_package/dockerfiles/uwsgi_exporter-sidecar/Makefile
>  Dockerfile and Makefile for building a sidecar image with uwsgi_exporter

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
> Configure uwsgi_exporter sidecar container, gated behind a per-instance toggle.

- paasta_tools/instance/kubernetes.py
- tests/instance/test_kubernetes.py
This un-reverts #2991, fixes the logic for it, and adds a test so I'm more confident that I'm not making a similar mistake.
> Fix logic for active shas

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
corrects the default value to match reality
> fix docs for healthcheck_max_consecutive_failures

- paasta_tools/cli/cmds/logs.py
- tests/cli/test_cmds_logs.py
Bug fix when running `paasta logs` for containers inside flink instances.
`make test`
> PAASTA-17231-LogSuffix-Fix

- paasta_tools/contrib/rightsizer_soaconfigs_update.py
Step 3 of the plan in https://github.com/Yelp/paasta/pull/3012.
I'll wait to release this until the Jenkinsfile change to exclude the cpu_burst_add key is merged.
> Write cpu_burst_add in autotune batch

- debian/paasta-tools.links
- paasta_tools/setup_prometheus_adapter_config.py
- setup.py
The full script is more lines than anyone wants to review at once so
I've split it into two commits/PRs: one that sets up the skeleton/logic
flow and another that actually fill in all the stub methods
**NOTE: this is using #3025 as a base to make it easier to break things up into multiple PRs - my plan is to merge the base PR and then merge this into master**
> Add skeleton for the prometheus adapter script

- paasta_tools/kubernetes_tools.py
I incorrectly rebased/merged and left this in by accident.
> Remove unused DEFAULT_AUTOSCALING_MOVING_AVERAGE_WINDOW import

- paasta_tools/contrib/is_pod_healthy_in_proxy.py
- paasta_tools/envoy_tools.py
- tests/test_envoy_tools.py
I'm modifying `are_services_up_in_pod()` so that backends for a given service are pulled from the EDS yaml files instead of the Envoy /clusters endpoint.
This is to mitigate a load issue on the Envoy admin endpoint, which is triggered when multiple pods are launched on a single node, firing a large number of readiness checks in parallel.
Note that I'm also dropping the check for `eds_health_status`. This param should be reported by the EDS, but `meshd` doesn't set it. As a consequence, Envoy always sees backends as `HEALTHY`.
> MESH-1070 Readiness check based on EDS yaml files

- paasta_tools/kubernetes_tools.py
We're currently dropping some metrics since this sidecar is getting
terminated before the main container.
> Add a preStop config for uwsgi-exporter

- paasta_tools/cli/cmds/mark_for_deployment.py
I'm adding y/stuckbounce to mark-for-deployment output in 2 places:
- The warning when the bounce is at 75% of its timeout duration
- The final timeout message
I ran m-f-d with a 1 minute timeout on a test service and saw the output for both Slack and stdout:
<details>
<summary>click to expand output</summary>
<p>
```
Waiting for deployment of 191a485cce034b076748ff6fd054ade1726ea619 for 'mesosstage.k8s' to complete...
0% ( 0 of 19) |                                                                                                                                                                                                                  | Elapsed Time: 0:00:00 ETA:  --:--:--
compute-infra-test-service.main_k8s on kubestage doesn't have the right sha yet: f8256d7d …
```
> Add stuck bounce runbook link to mark-for-deployment output

- tests/test_kubernetes_tools.py
Fix `make_itest` which failed from https://github.com/Yelp/paasta/pull/3096 sorry about overlooking this one.
> MONK-2327 Fix make itest

- paasta_tools/cli/cmds/status.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/utils.py
I'll plan to ship this in a week or so, once all the services have been off signalfx for a while.
> Remove SignalFX-related HPA code. PAASTA-17097

- paasta_tools/flink_tools.py
- tests/test_flink_tools.py
- tests/test_setup_kubernetes_cr.py
https://jira.yelpcorp.com/browse/PAASTA-17389
> PAASTA-17389.

- paasta_tools/flink_tools.py
- tests/test_flink_tools.py
- tests/test_setup_kubernetes_cr.py
Reverts Yelp/paasta#3127 as operator changes are blocked. Once operator changes are unblocked, we will release the changes again.
> The corresponding operator changes are blocked

- paasta_tools/kubernetes_tools.py
Calling kube_client.core.list_namespaced_event() was blocking the
asyncio event loop and making `paasta status -v` for services with a
large amount of Pods hang forever as the gunicorn worker serving the
request would eventually hit a timeout and die.
This PR wraps list_namespaced_event() into an awaitable and allows us to
actually make N concurrent requests instead of doing these serially.
> Stop calling a blocking function in get_events_for_object()

- paasta_tools/flink_tools.py
- tests/test_flink_tools.py
- tests/test_setup_kubernetes_cr.py
This reverts commit 36c1b6db8a95991b5387be8e61dd0966092cf9ae.
Operator changes have been unblocked.
> Unblock "PAASTA-17389".

- paasta_tools/cli/schemas/kubernetes_schema.json
Updated schema for istio sidecar option
> update schema for is_istio_sidecar_injection_enabled option

- paasta_tools/contrib/deploy_group_update.py
Modify smartstack file so new instances are accessible, cleanup variable naming, and call trigger_deploys after modifying files.
> automatically edit smartstack, call trigger_deploys

- mypy.ini
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/utils.py
First commit fixes the bug, second commit checks to see if I broke anything a similar way.
> fix 'set' object is not subscriptable error

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/utils.py
> Ping authors during bounce when new pods are unhealthy.

- paasta_tools/cli/cmds/mark_for_deployment.py
Missing f string marker in error exception.
> Add missing f string marker in exception error

- paasta_tools/cli/cmds/mark_for_deployment.py
https://jira.yelpcorp.com/browse/PAASTA-17453
> If an SLO is failing when the deploy completes, explain why the deploy isn't doing anything. PAASTA-17453

- paasta_tools/prune_completed_pods.py
The current version of this script doesn't capture Pods that end up in
Error or CreateContainerError states, and thus these end up sticking
around for a while.
There's no direct way to get what Pods are in this state, but we can use
the Failed phase as a proxy.
For now, the new arg I've added is optional until we've rolled this
version out everywhere and have updated all callsites to pass in
--error-minutes.
I'm planning on setting --error-minutes to a somewhat high value in case
we want to debug this using kubectl (so probably a couple hours?)
> Cleanup failed Pods in prune_completed_pods.py

- paasta_tools/cli/utils.py
- paasta_tools/monkrelaycluster_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
Change instance name to monkrelays
> Change instance name to monkrelays

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
We'll want to merge this after https://github.com/Yelp/Tron/pull/852
> Add Pod Identity support for Tron Pods

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/metrics/metrics_lib.py
- tests/cli/test_cmds_mark_for_deployment.py
First step to setting up a deployment SLO is to measure deployment duration is to collect the relevant metrics. This PR will collect that metric whenever `mark-for-deployment --wait-for-deployment` is run. The following restrictions apply:
- Duration is not measured whenever `--wait-for-deployment` is not used, nor if m-f-d fails due to validation errors.
- By default, the metrics collection class is `NoMetrics` (i.e. noop); to turn on collection by `meteorite`, `metrics_provider` has to be provided in system paasta configs (currently we do not set it).
- `make test`
- Manual testing using m-f-d on a test service, including with local system paasta configs with `metrics_provider` turned on
Next step is to release it, then turn on metrics collection, first in stage, then everywhere else …
> Measure deploy duration for mark-for-deployment

- paasta_tools/contrib/service_shard_remove.py
The inverse of https://github.com/Yelp/paasta/blob/master/paasta_tools/contrib/service_shard_update.py (remove a shard)
> adds service_shard_remove script

- paasta_tools/cli/cmds/validate.py
Looks like ruamel doesn't handle multiple anchors at different levels of
nesting particularly well in some cases.
Since we only really need ruamel for parsing kubernetes config files which
are generally unlikely to do similar shenanigans, we can add a flag to
only use ruamel for these (and then furthermore, only for validating CPU
overrides).
> Conditionally use ruamel in get_config_file_dict()

- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
Small formatting fixes that were failing the build
> [FLINK-3869] Adds small formatting fixes

- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
We're rewriting this for k8s and, since this is currently unused, its
easier to start from scratch.
(I'm going to follow this up with other PRs soon)
> Remove previous attempt at executor: spark for Tron

- tests/test_tron_tools.py
I previously made a change that unintentionally added a dynamically changing env var to all instances, which caused continuous reconfigurations of all tron jobs, which overloaded the Tron API. The change has been fixed, but this is a follow up by adding a test that should catch similar changes should they happen. The new test mimics what we already have for long-running services ([here](https://github.com/Yelp/paasta/blob/master/tests/test_kubernetes_tools.py#L2120)).
`make test`
> Add tron big bounce test

- paasta_tools/cli/cmds/spark_run.py
Well this was a bit embarassing..
_I can't believe I missed that line.._
> [COREML-2697] spark-run defaults to kubernetes

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
> add special handling for pseudo-service _shared

- paasta_tools/cli/schemas/deploy_schema.json
- tests/cli/test_cmds_check.py
Not quite sure how these snuck by - are we not running pre-commit in
GHA?
> Fix pre-commit failures

- paasta_tools/cli/cmds/cook_image.py
Until https://github.com/Yelp/paasta/pull/3292 is merged, we're not
running general_itests in GHA
> Fix general_itest failues in cook_image

- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_tron_namespace.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
In an upcoming PR, all of these will be used to setup the actual
commandline + env for a spark driver to run with - I'm splitting this up
into 2 PRs to make it easier to review :)
> Add some useful utils for running a Spark driver on k8s

- paasta_tools/cli/schemas/deploy_schema.json
Adding this flag to be able to display the proper step name in Slack proceed messages.
> Add display step for confirmation

- mypy.ini
- paasta_tools/cli/cmds/cook_image.py
- tests/cli/test_cmds_cook_image.py
The relevant ticket is:
https://jira.yelpcorp.com/browse/COMPINFRA-1088
> Support additional version information in cook-image

- paasta_itests/steps/paasta_native_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/utils.py
- tests/cli/test_cmds_start_stop_restart.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
- tests/test_generate_deployments_for_service.py
- tests/test_kubernetes_tools.py
- tests/test_long_running_service_tools.py
- tests/test_marathon_tools.py
- tests/test_paasta_service_config_loader.py
- tests/test_utils.py
The relevant ticket for this is:
https://jira.yelpcorp.com/browse/COMPINFRA-1041
> Support additional version information in generate-deployments-for-service

- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
The relevant ticket for this is:
https://jira.yelpcorp.com/browse/COMPINFRA-1095
This is just to get some feedback on these changes, as this is built on top of the changes in #3346, which is not merged yet.
> Support additional version information in KubernetesDeploymentConfig

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/model/kubernetes_version.py
- tests/instance/test_kubernetes.py
The relevant ticket for this is:
https://jira.yelpcorp.com/browse/COMPINFRA-1093
The PR where the labels used will be added is:
https://github.com/Yelp/paasta/pull/3350
> Support additional version information in paasta status API calls

- paasta_tools/utils.py
Added a util to return a service's production_deploy_group
> Add util for getting production_deploy_group

- Jenkinsfile
- Makefile
Setting PAASTA_ENV using the Jenkinsfile for internal builds
> Setting paasta env in jenkinsfile

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/smartstack_schema.json
- paasta_tools/long_running_service_tools.py
- tests/test_marathon_tools.py
> Adding Envoy lb_policy in smartstack schema

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/wait_for_deployment.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/utils.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
I still have to create some tests and I'm sure I forgot something, but wanted to open this up for comment early!
> Update mark-for-deployment's wait-for-deployment components to use image_version

- docs/source/adhoc_instances.rst
- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/cmds/autoscale.py
- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/cmds/pause_service_autoscaler.py
- paasta_tools/cli/cmds/secret.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/marathon_dashboard.py
This cluster no longer exists and mentions of it confuses folks.
> Remove mentions of norcal-prod

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
> Revert "Wrap readiness check script with a timeout"

- paasta_tools/cli/cmds/push_to_registry.py
- tests/cli/test_cmds_push_to_registry.py
This change makes it so that when `--image-version` is specified, `push-to-registry` will push to the Docker registry both standard tag and the "versioned tag" for the built image, allowing easier backwards compatibility.
> cli: have push-to-registry handle multiple tag conventions

- paasta_tools/kubernetes_tools.py
- tests/test_kubernetes_tools.py
https://github.com/Yelp/hacheck/pull/42 and https://github.com/Yelp/nerve-tools/pull/94
(Yes this will cause a big bounce also, hopefully we can roll this out with 0.135.3)
> MESH-1439: add SERVICE_REGISTRATIONS env to hacheck

- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/spark_tools.py
- requirements-minimal.txt
- requirements.txt
- tests/cli/test_cmds_spark_run.py
Followup from the service_configuration_lib PR to expose the local cluster manager for spark-run in MLCOMPUTE-435.
make test
> Expose --cluster-manager=local for spark-run command.

- paasta_tools/cli/cmds/status.py
Fix for the missing info that was reported earlier today on Slack.
> [FLINK-4124] Small fix to display status info

- requirements-minimal.txt
- requirements.txt
Deploying https://github.com/Yelp/service_configuration_lib/pull/85
> Bump service_configuration_library to fix an issue with spark 3.2 on mesos

- requirements-minimal.txt
- requirements.txt
Follow-up PR for https://github.com/Yelp/service_configuration_lib/pull/86
> Bump service_configurtion_lib to 2.11.2 to update signalfx link

- paasta_tools/contrib/is_pod_healthy_in_proxy.py
- paasta_tools/contrib/is_pod_healthy_in_smartstack.py
- yelp_package/Makefile
- yelp_package/dockerfiles/hacheck-sidecar/Dockerfile
Update dockerfile for hacheck to bionic (could maybe go to jammy even?) and parameterise hacheck version
> MESH-1452: update dockerfile for hacheck

- Makefile
- k8s_itests/Makefile
- k8s_itests/deployments/kind/cluster-devbox.yaml
- k8s_itests/deployments/kind/cluster.yaml
- k8s_itests/scripts/clean.sh
- k8s_itests/scripts/setup.sh
This PR adds support for the latest version of kind to be used with the PaaSTA Playground
> Fixing kind local cluster

- .gitignore
Adding [Jetbrains Fleet](https://www.jetbrains.com/fleet/) settings to .gitignore
> Adding .fleet to .gitignore

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/secret.py
- paasta_tools/kubernetes_tools.py
- tests/cli/test_cmds_secret.py
- tests/test_kubernetes_tools.py
Same as: https://github.com/Yelp/paasta/pull/3477, but for local-run cmd.
Added some refactoring of get_kubernetes_secret following [this comment](https://github.com/Yelp/paasta/pull/3477#discussion_r998496872).
> Secrets for teams opt-in feature in paasta local-run cmd

- paasta_tools/monitoring/check_k8s_api_performance.py
The purpose of this script is to measure the time it takes to call the api to get the pods for a specific namespace.
Tested the script manually
> A python script that measures the time for get pod from a specific ns - PAASTA-17789

- paasta_tools/contrib/get_running_task_allocation.py
This was accidentally missing the -- so being treated as postitional
> Fix additional_namespaces arg

- docs/source/paasta_development.rst
Updates to PaaSTA Playground documentation
> Updating paasta development docs

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
> Revert "Cap spark driver memory and disk usage"

- paasta_tools/cli/schemas/deploy_schema.json
Adding a new flag in the Paasta configs, to support no-verify-deploy by default.
> CID-2783: Adding no-verify-deploy by default flag

- requirements-minimal.txt
- requirements.txt
- tests/test_tron_tools.py
Upgrade service-configuration-lib to 2.14.1 to include fix https://github.com/Yelp/service_configuration_lib/pull/101.
> Upgrade service-configuration-lib to 2.14.1

- requirements-minimal.txt
- requirements.txt
Upgrade service-configuration-lib to include https://github.com/Yelp/service_configuration_lib/pull/102.
> Upgrade service-configuration-lib to v2.14.2

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
this is what I was suggesting [here](https://github.com/Yelp/paasta/pull/3552#discussion_r1120801499)
> Refactor paasta_secret_sync to use PaastaServiceConfigLoader

- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
Related to #3536. Choosing on `crypto_keys` field name.
> Add `crypto_keys` field

- requirements-minimal.txt
- requirements.txt
Upgrade package version to include https://github.com/Yelp/service_configuration_lib/pull/106.
> Upgrade service-configuration-lib to 2.14.4

- .gitignore
- Makefile
- debian/paasta-tools.prerm.debhelper
- k8s_itests/deployments/paasta/fake_etc_paasta/logs.json
- paasta_tools/cli/cmds/secret.py
- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/secret_providers/__init__.py
- paasta_tools/secret_providers/vault.py
- paasta_tools/secret_tools.py
- tests/cli/test_cmds_secret.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
- tests/test_kubernetes_tools.py
> Revert "[PAASTA-17844] Mount Vault KV secrets as k8s secret volumes"

- paasta_tools/contrib/rightsizer_soaconfigs_update.py
We occasionally want to disable autotune in a given cluster (or set of clusters) for reasons™ - this PR adds an option to the rightsizer script to exclude any number of clusters from having their autotune recommendations be applied
> Enable skipping clusters in autotune

- .gitignore
- Makefile
- debian/paasta-tools.prerm.debhelper
- k8s_itests/deployments/paasta/fake_etc_paasta/logs.json
- paasta_tools/cli/cmds/secret.py
- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/secret_providers/__init__.py
- paasta_tools/secret_providers/vault.py
- paasta_tools/secret_tools.py
- paasta_tools/tron_tools.py
- tests/cli/test_cmds_secret.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
- tests/test_kubernetes_tools.py
> Revert "Revert "Revert "[PAASTA-17844] Mount Vault KV secrets as k8s secret v…"

- paasta_tools/cleanup_kubernetes_jobs.py
making sure that `cleanup_k8s_job` can delete stopped instances
> Make cleanup_k8s_job delete stopped instances

- paasta_tools/cli/cmds/spark_run.py
In paasta spark-run, since the Docker image digest used to launch the Spark cluster is obtained by inspecting local Docker images, we need to ensure that the Docker image exists locally or is pulled in all scenarios.
```bash
aws-okta -r core-ml -a dev -k -p dev
docker rmi docker-dev.yelpcorp.com/ad-targeting-batches-austinzh:0.117.8
paasta spark-run --image docker-dev.yelpcorp.com/ad-targeting-batches-austinzh:0.117.8 --aws-profile=dev --cmd bash
```
Before:
After:
> Fix docker image not pulled with --image option

- paasta_tools/kubernetes/bin/paasta_secrets_sync.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/kubernetes/bin/test_paasta_secrets_sync.py
This reverts commit f1d4c69f7b6cc596897a66404c0da1a57a3f16c6.
(this reverts #3622, effectively re-merging #3617)
> Revert "Revert "Merge branch 'u/krall/dont_sync_to_unused_namespaces'""

- paasta_tools/cli/cmds/spark_run.py
Sudo is needed for getting credentials when pulling images from paasta docker registry (docker-paasta.yelpcorp.com)  
However, in our CI env, we can't connect to docker from root, and paasta docker images can be pulled with normal user.
=> Pull paasta docker images without sudo in CI env.
> Pull paasta spark docker images without sudo in CI env

- docs/source/installation/getting_started.rst
Updated links for Sensu & Mesos
> Fix broken links in Getting Started documentation

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
1. AQE is enabled by default
2. DRA docs needs to be fixed.
> Fix dra docs and remove aqe flag

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_crd.py
- paasta_tools/setup_kubernetes_internal_crd.py
- requirements.txt
- tests/test_kubernetes_tools.py
> Revert "Revert "Upgrading kubernetes client library to v24.2.0""

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_crd.py
- paasta_tools/setup_kubernetes_internal_crd.py
Fixing update_crds calls depending on apiextensions
[PAASTA-17925](https://jira.yelpcorp.com/browse/PAASTA-17925)
> Adding extensions to update_crds function

- .gitignore
- paasta_tools/cli/cmds/spark_run.py
- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/cli/schemas/tron_schema.json
- paasta_tools/secret_tools.py
- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- requirements.txt
- tests/test_tron_tools.py
Reverts Yelp/paasta#3615
#dar-2021
> Revert "TRON-1636: Setup tron secret_volumes in setup_tron_namespace"

- paasta_tools/utils.py
Fixes Secret syncing for Cassandra operator.
> adding paasta-cassandraclusters to shared secrets namespaces

- mypy.ini
- setup.py
Missed this spot in my previous py38 commit
> Update python version used by mypy/setup.py

- yelp_package/Makefile
This reverts commit 859073c4b1397cec8600f204224d113d1f4bdd5d
See https://github.com/orgs/community/discussions/65227#discussioncomment-6848413.
> Revert "Explictly set wget cipher suite (#3687)"

- paasta_tools/setup_prometheus_adapter_config.py
Add quotes around new label name in label_replace
> Add quotes around new label name in label_replace

- requirements-minimal.txt
- requirements.txt
To include changes from https://github.com/Yelp/service_configuration_lib/pull/133
> Bump service-configuration-lib to v2.18.10

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
- Function has additional logic which should be executed unconditionally
> MLCOMPUTE-1098 | fix error in parsing user spark args

- paasta_tools/kubernetes/application/controller_wrappers.py
- tests/kubernetes/application/test_controller_wrapper.py
- tests/test_kubernetes_tools.py
We previously configured `brutal` deployments already to use a `RollingUpdate` strategy w/ `max_unavailable=100%`, which should immediately kill off all old replicas & spawn a new replicaset during a rolling restart. 
This sounds like exactly what we'd want a brutal bounce to do, and should be even faster than today's brutal bounces since we won't need to wait around for paasta to delete the object & check if it has fully been deleted plus delete all pods, then finally create it again. With these configs, Kubernetes should immediately delete all pods of the old version and spawn a new replicaset of the new.
This review updates it so setup_kubernetes_job will just update the brutal deployment in the same way as all other deployments, and removes the deletion code since brutal bounces were …
> Stop deleting brutal deployments

- paasta_tools/cli/schemas/kubernetes_schema.json
- paasta_tools/kubernetes_tools.py
- paasta_tools/utils.py
- tests/test_kubernetes_tools.py
> Make it possible to specify topology_spread_constraints per service/instance.

- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- tests/conftest.py
> Improve caching in setup_kubernetes_job to reduce unnecessary work. 

- contrib/python-k8s-client.diff
- debian/rules
Build time patch for [python-k8s-client](https://github.com/kubernetes-client/python) issue [#1867](https://github.com/kubernetes-client/python/issues/1867)
> Patching python-k8s-client at build time

- paasta_tools/api/views/instance.py
While migrating a service to EKS, the PaaSTA API for the non-EKS cluster threw a 500 exception when requesting `bounce_status` for the already-migrated instance: 
```
Error handling request /v1/services/example_happyhour/testing/bounce_status
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/api/views/instance.py", line 860, in bounce_status
return pik.bounce_status(
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/instance/kubernetes.py", line 488, in bounce_status
job_config = kubernetes_tools.load_kubernetes_service_config(
File "/opt/venvs/paasta-tools/lib/python3.8/site-packages/paasta_tools/utils.py", line 213, in cache
"data": f(*args, **kwargs),
File …
```
> Catch NoConfiguration exceptions in bounce_status

- paasta_tools/cli/cmds/spark_run.py
- tests/cli/test_cmds_spark_run.py
Tested by running tests and paasta spark-run locally.
> Remove spark mesos logic

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
- tests/conftest.py
This reverts commit 0d2e44d2b653026fd34dad48c326a1689ac5dac6, reversing changes made to 39792354fc99728c6edb9fdeeb2ac3aa9a1553ed.
> Undo Revert in "Merge pull request #3794 from nurdann/master"

- docs/source/index.rst
- docs/source/persistent_volumes.rst
These are wholly undocumented and require looking at existing config, looking at the code, or asking someone on CI to figure out how to use.
Let's fix that :)
> Add some starter docs for PVs

- README.md
Mostly just correcting a few things and updating things that aren't true. I also tried to make it clearer that PaaSTA isn't intended for use outside Yelp.
> Make some updates to our README

- paasta_tools/cli/cmds/logs.py
Using -e will not always work (e.g., if you're calling `paasta logs` on something running in prod), so let's add some code to look at what the log_reader cluster_map says the scribe region/ecosystem is and correctly pick between -e and -r
> Correctly display scribe selector

- paasta_tools/api/api_docs/oapi.yaml
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/paastaapi/model/instance_status.py
This is the extension of #3797 
This will add support for Flinkeks instance type in paasta commands for `status` `start` and `stop` commands.
> added support for flinkeks in paasta cli 

- paasta_tools/contrib/service_shard_remove.py
- paasta_tools/contrib/service_shard_update.py
Updated scripts to dynamically load `eks-*` for both `service_shard_update` and `service_shard_remove` if it exists in preparation for migration. Prior to the migration there should be no changes to the status quo since we'll still fetch `kubernetes-*` configs.
> migrate config from kubernetes to eks

- paasta_tools/tron_tools.py
- paasta_tools/utils.py
- tests/test_tron_tools.py
We ended up not using this, so let's go ahead and clean things up to prevent confusion :)
> Remove STREAM_SUFFIX_LOGSPOUT code

- docs/source/adhoc_instances.rst
Let me know if there's another place it should go to.
> Add local-run role assumption usage docs

- paasta_tools/cli/utils.py
- paasta_tools/instance/kubernetes.py
- paasta_tools/nrtsearchserviceeks_tools.py
- paasta_tools/utils.py
- tests/test_nrtsearchserviceseks_tools.py
- tests/test_utils.py
Similar to #3797 but for nrtsearch
> Implement nrtsearchserviceeks custom resource for EKS clusters.

- paasta_tools/utils.py
- tests/test_utils.py
> Delete deployd-related code from SystemPaastaConfig

- paasta_tools/cli/cmds/spark_run.py
- requirements-minimal.txt
- requirements.txt
> Revert "Bump service-configuration-lib to v2.18.18"

- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
> Revert "MLCOMPUTE-1203 | Configure Spark driver pod memory and cores based on Spark args"

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- paasta_tools/tron_tools.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
> Split create_or_find_service_account into a non-mutating method and a mutating method

- paasta_tools/cli/cmds/status.py
Context: https://yelp.slack.com/archives/C060C8L80LE/p1719600589765159?thread_ts=1719520290.860989&cid=C060C8L80LE
> Add VitessDeploymentConfig to EKS_DEPLOYMENT_CONFIGS in paasta status

- paasta_tools/setup_tron_namespace.py
- paasta_tools/spark_tools.py
- paasta_tools/tron_tools.py
- tests/test_tron_tools.py
> Revert "Attempt #2 MLCOMPUTE-1203 | Configure Spark driver pod memory and cores based on Spark args"

- paasta_tools/kubernetes/application/controller_wrappers.py
- paasta_tools/kubernetes_tools.py
- paasta_tools/setup_kubernetes_job.py
- paasta_tools/tron_tools.py
- tests/test_kubernetes_tools.py
- tests/test_tron_tools.py
> Revert "Split create_or_find_service_account into a non-mutating method and a mutating method"

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/smartstack_schema.json
extend smartstack.yaml schema to include default error alerting config
> smartstack alert schema

- yelp_package/extra_requirements_yelp.txt
Updated yelp_clog enforces usage of instance profile creds over default user profile
> Bump yelp_clog version

- paasta_tools/cli/schemas/tron_schema.json
> MLCOMPUTE-1208 | fix spark args regex

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/spark_run.py
Further to #3927 when discussing spark jobs with @chi [here](https://yelp.slack.com/archives/CA8BWU65D/p1723816981990909?thread_ts=1723740835.076679&cid=CA8BWU65D) I realised there were more calls to get_volumes on instance_config
I'm not sure how to test this
> Further calls to uses_bulkdata default

- requirements-minimal.txt
- requirements.txt
- Bump up service-configuration-lib
> MLCOMPUTE-1496 | Reduce logging by service-configuration-lib

- tests/test_kubernetes_tools.py
This test should grow over time to include other commonly used options/configs: e.g., the various types of secrets and whatnot
I've verified that without https://github.com/Yelp/paasta/pull/3973, this would
always fail with a different SHA on every test run
> Add big-bounce test for non-default configs

- docs/source/yelpsoa_configs.rst
There's been recent interest in this feature, but it's not currently documented outside of the PR that added the feature.
> Document `autotune_limits`

- example_cluster/dind-cluster-v1.13.sh
https://kubernetes.io/blog/2023/03/10/image-registry-redirect/ :p
> Stop referring to k8s.gcr.io

- paasta_tools/cli/schemas/adhoc_schema.json
to allow https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/52579 to merge. More context in https://yelp.slack.com/archives/CCX9Y416V/p1737145462730669
> Add uses_bulkdata to adhoc schema

- debian/paasta-tools.links
- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- paasta_tools/kubernetes/bin/paasta_cleanup_remote_run_resources.py
- paasta_tools/kubernetes/remote_run.py
- setup.py
- tests/cli/test_cmds_remote_run.py
- tests/kubernetes/bin/test_paasta_cleanup_remote_run_resources.py
- tests/kubernetes/test_remote_run.py
> the remote-run missing bits

- paasta_tools/kubernetes/bin/paasta_cleanup_remote_run_resources.py
- paasta_tools/kubernetes/remote_run.py
- tests/kubernetes/bin/test_paasta_cleanup_remote_run_resources.py
- tests/kubernetes/test_remote_run.py
* I referenced the wrong sub-client to create namespaced roles
* While testing out the clean up script I noticed some severe lack of output, and I have only myself to blame
> more minor fixes for remote-run

- paasta_tools/cli/schemas/adhoc_schema.json
Realized right after merging https://github.com/Yelp/paasta/pull/4102 🤦
> fs_group is supposed to be an int
