- .travis.yml
We need to install tox in travis for `make test` to work.
> Install tox in travis

- paasta_tools/setup_chronos_job.py
I don't really like how this code is structured, if anyone has better opinions on what we *should* be doing, I can redo it.
We currently catch all exceptional cases in main. This is another case that can happen, and without catching the exception we will crash. But of course it isn't "that" exceptional.
In marathon we kinda split it up, some exceptions are caught in main, some are caught closer to where the actual function is invoked.
> Make setup_chronos_job handle the situation where the docker image isn't available

- paasta_tools/paasta_cli/cmds/fsm.py
This was never caught by automated tests because this bug is only triggered in interactive mode
without --service-name
> Use the right srvname

- README.md
- docs/source/about/paasta_principles.rst
This adds some docs about what makes paasta special, specifically it enumerates some of the opinions behind our "opinionated glue"
> Added paasta principles

- paasta_itests/paasta_metastatus.feature
- paasta_tools/marathon_tools.py
- requirements.txt
- setup.py
- tests/test_marathon_tools.py
- Use versions of chronos-python and marathon from pypi
- Fix a test broken by the new version of marathon
> upgrade marathon and chronos-python

- docs/source/about/paasta_principles.rst
This principle is kinda baked into how we built this, and is a significant difference compared to things like docker-swarm, where you can just run the "nginx" container from the hub, etc. So I thought it was worth noting here.
> Added reproducible principle

- paasta_tools/paasta_cli/cmds/status.py
- tests/paasta_cli/test_cmds_status.py
I wanted to try out some stuff with a new instance of the reminder service, but that service has a ton of instances so doing paasta status is slow and painful. Now we can filter instances like we can filter clusters:
```
(py)troscoe@dev2-devc:~/paasta_tools (mrtyler_instance_filter) $ ./paasta_tools/paasta_cli/paasta_cli.py status -s paasta_canary -c norcal-devc,qwer -i sensu_canary,asdf
Pipeline: https://jenkins.yelpcorp.com/view/services-paasta_canary
cluster: norcal-devc
instance: sensu_canary
Git sha:    b8517e76
Config:     configbb7d0b2a
Status:   Enabled, Started
Last:     OK (2015-11-13T16:40, a minute ago)
Schedule: R/2015-11-14T00:50:00.000Z/PT10M Epsilon: PT60S
Command:  sensu-scheduled-canary.sh
Mesos:    Not running
Warning: This service does not have any instance matching …
```
> Mrtyler instance filter

- paasta_tools/paasta_cli/cmds/mark_for_deployment.py
- tests/paasta_cli/test_cmds_mark_for_deployment.py
With this refactor it should be easier to add future functionality that makes using this a lot more user friendly. Got rid of 'clusterinstance' and separated it into cluster and instance for clarity.
> Some refactoring related to the argument 'clusterinstance'

- paasta_tools/paasta_cli/cmds/logs.py
I'd like a better way of doing this - logic for dealing with missing scribereader is sprawled into a few places now. If anyone has a better suggestion, I'm open to discussion.
> fail gracefully if you try and run paasta logs without scribe existing

- general_itests/paasta_execute_docker_command.feature
- general_itests/steps/paasta_execute_docker_command.py
We found an edge case where this failed because the image didn't already exist on the host travis was running the tests on - dockerpy doesn't pull an image if it doesn't already exist, so this addresses that.
> execute docker pull before running container

- paasta_tools/mesos_tools.py
I noticed this was broken in #paasta at 2015-10-14 22:25.
```
<troscoe> robj: tell me what you know about mesos master.CURRENT.tasks(active_only=True)
<troscoe> (Pdb) len([task['id'] for task in master.CURRENT.tasks(fltr=u'paasta_canary sensu_canary git2af124f2 config34fce6d7', active_only=True)])
<troscoe> 0
<troscoe> (Pdb) len([task['id'] for task in master.CURRENT.tasks(fltr=u'paasta_canary sensu_canary git2af124f2 config34fce6d7', active_only=False)])
<troscoe> 1000
<troscoe> this is why chronos status can only show currently running jobs :(
<troscoe> currently running mesos tasks*
<troscoe> contrast with
<troscoe> (Pdb) len([task['id'] for task in master.CURRENT.tasks(fltr='paasta--canary.main.git2af124f2.confige3ef71dd', active_only=True)])5
<troscoe> (Pdb) len([task['id'] for task …
```
> active_only=True doesn't work with chronos. Let's try it with False.

- paasta_tools/chronos_serviceinit.py
- tests/test_chronos_serviceinit.py
This addresses some concerns brought up by carroux way back in review:115197:
- paasta level "started/stopped" (i.e. the result of "paasta stop/start") is only accurate at the instance level. It is wrong and misleading to display it for each config
- "enabled/disabled" is not very clear
After some thinking and some consultation with mfield, here's what I did:
- paasta level "started/stopped" is reported only at the top level (parallel with git sha), and no longer as part of individual configs
- Change "enabled/disabled" to "scheduled/not scheduled"
-- mfield noticed that there are sort of three states here: enabled, disabled because the whole service is disabled, disabled because this is an old version that we're keeping around for history. We couldn't think of a great way to communicate …
> Mrtyler rejigger status

- paasta_itests/steps/setup_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_cli/cmds/mark_for_deployment.py
- paasta_tools/remote_git.py
- paasta_tools/utils.py
- tests/paasta_cli/test_cmds_mark_for_deployment.py
- tests/test_remote_git.py
This converts mark-for-deployment to use dulwich so you don't need a local checkout.
This will be necessary for non-jenkins use cases and will be handy for the "rollback" command.
Some extra code was necissary in the `remote_git` module to support this. I would like @EvanKrall to look extra carefully at that, it was my first time using dulwich.
Manual testing:
```
kwa@dev13-devc:~/Projects/devops (master) $ git branch -a -v
remotes/origin/paasta-nova-devc.demo                1aaf828 devops demo 2
(py)kwa@dev13-devc:~/Projects/paasta (use_dulwich_for_mark_for_deployment) $ ./paasta_tools/paasta_cli/paasta_cli.py mark-for-deployment -u git@git.yelpcorp.com:services/devops -c 700bda5e32aae2345af581af29494ef095bd9666 -l nova-devc.demo -s devops
Marked 700bda5e32aae2345af581af29494ef095bd9666 …
```
> Use dulwich for mark for deployment

- yelp_package/dockerfiles/trusty/Dockerfile
the link to dh-virtualenv was 404ing (I guess they removed the old version when they released 0.10-0~81) and causing Jenkins + Travis to fail. This fixes that (Travis should pass tests now?).
> update dh-virtualenv location

- docs/source/about/contract.rst
Currently our contract doc is on google drive. This migrates it to the repo so it can be available in the normal docs, and when the contract changes it can be updated with the same PR
> Added first pass at paasta-contract transplant

- paasta_tools/paasta_cli/cmds/local_run.py
- tests/paasta_cli/test_cmds_local_run.py
I this a small step towards ad-hoc "batches", I think a large portion will of the use cases will want to just get an interactive shell, so this makes it a little bit easier as you will be able to just say "-I"
> Make local-run default to use bash if set to be interactive

- paasta_tools/paasta_cli/cmds/rollback.py
- tests/paasta_cli/test_cmds_rollback.py
paasta_rollback is meant to be a more user friendly cli option for mark_for_deployment. There is some room for improvements, still (so work in progress).
Example usage:
`paasta_rollback -c %cluster% -i %instance% -s %example_service% -k %commit_sha%`
> Added paasta_rollback command

- setup.py
- use `/usr/bin/env python` over `/usr/bin/python`
- coding pragma must be in the first 2 lines (shebang must be first, so => second!)
- exclude should have a star to avoid adding sub-packages
- setup_requires setuptools is silly given setuptools is imported at the top of the file
> Minor fixups to setup.py

- yelp_package/extra_requirements.txt
This makes `paasta logs` work for more environments internally
> Bump scribereader requirement

- Makefile
This target will currently fail outside of Yelp. Use the machine's
FQDN to determine if it is a Yelp box. If it is, run the target.
If it is not, simply display a warning.
This should hopefully help avoid confusion as to why the target fails to work.
> Only allow the itest_% Makefile target to run at Yelp

- paasta_tools/utils.py
- tests/paasta_cli/test_cmds_itest.py
- tests/paasta_cli/test_cmds_push_to_registry.py
- tests/test_utils.py
I made an unhelpful comment on another review of 'we should remove this'. So here it is.
> remove hardcoded docker registry location

- paasta_tools/paasta_cli/cmds/rollback.py
- tests/paasta_cli/test_cmds_rollback.py
Paasta rollback now accepts none, one or a list of instances. If any are wrong it will give a warning and carry on with the valid ones.
Added a bunch of tests to verify the behaviour on each case.
> Paasta rollback now accepts none, one or a list of instances.

- paasta_tools/paasta_cli/cmds/local_run.py
- paasta_tools/utils.py
- tests/paasta_cli/test_cmds_local_run.py
This is more of a RFC, this is not complete yet.
This adds new mutually exclusive args to `local-run`: `--build` and `--pull`. Eventually it will (try to) auto-detect to make it require fewer command line args for day-to-day use.
> Enabled local-run to work on docker images on registries instead of building locally

- docs/source/workflow.rst
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
After our recent outage, I think 1 minute is too aggressive. This bumps it to 5 minutes. This reduces our overall churn rate and gives more breathing room to the distributed system to recover from network issues.
> Bump max_consecutive_failures to 30 (5 minutes)

- paasta_tools/paasta_cli/cmds/local_run.py
- paasta_tools/utils.py
- tests/paasta_cli/test_cmds_local_run.py
This is to improve the new adhoc batch stuff.
Without devnull as stdin, it just hangs expecting you to type in a username+password. I'm going to make the call that we never want to do this in paasta?
Also I added a small flag to allow streaming the output, so you *see* the pull so you get better feedback as it is being pulled. (instead of waiting with no output)
> Make local-run stream the docker-pull with /dev/null as stdin

- paasta_itests/marathon.feature
- paasta_itests/steps/marathon_steps.py
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
configure_nerve built against newer paasta_tools was getting an error: 
```
File "/usr/bin/configure_nerve", line 9, in <module>
load_entry_point('nerve-tools==0.8.27', 'console_scripts', 'configure_nerve')()
File "/usr/share/python/nerve-tools/lib/python2.7/site-packages/nerve_tools/configure_nerve.py", line 195, in main
new_config = generate_configuration(get_services_running_here_for_nerve(), opts.heartbeat_path)
File "/usr/share/python/nerve-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 743, in get_services_running_here_for_nerve
return get_marathon_services_running_here_for_nerve(cluster, soa_dir) + \
File "/usr/share/python/nerve-tools/lib/python2.7/site-packages/paasta_tools/marathon_tools.py", line 673, in …
```
> Fix InvalidJobNameError in marathon_services_running_here

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/fsm/questions.py
Fixed the one I cared about, found another with:
```bash
git grep 'sys.stderr.write' | grep -v '\n["'"'"']' | grep ')'
```
> Fix some sys.stderr.writes that don't have their newlines

- general_itests/fake_soa_configs_validate/fake_invalid_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_invalid_service/marathon-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/marathon-test-cluster.yaml
- general_itests/steps/validate_steps.py
- general_itests/validate.feature
- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_validate.py
This pull request fixes #126 . It is designed to supplement the existing unit tests which already test most of the functionality of `paasta validate`.
> Paasta validate itests

- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
This was a feature request from @gchin.
In the beginning when we only had marathon, this logic made sense. Now I think it can be better if it the human readable output was more "aware" of what kind of job it is, which influences what it means to be "stopped or started".
At the same time, a service with 0 instances is considered "stopped" when you run paasta stop, so we we improve this message and just say "stopped", even if you didn't literally use the paasta stop command?
> Improve the human readable state of services depending on their type

- tests/cli/test_cmds_validate.py
as it stands, we rely on assumptions on the behaviour of ChronosJobConfig.validate for the paasta validate unit tests. This removes those assumptions using Mocks so that we don't have to update these unit tests every time the behaviour of ChronosJobConfig.validate changes.
> remove assumptions from paasta validate tests

- paasta_itests/chronos.feature
- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/environment.py
- paasta_itests/paasta_metastatus.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/setup_chronos_job.feature
- paasta_itests/steps/chronos_steps.py
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_chronos_job_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/setup_chronos_job.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_setup_chronos_job.py
This is a first pass at adding support for dependent jobs: a user can now add a 'parents' key to the yelpsoa-configs for their job and have a dependent job created.
A user specifies the parent for a dependent job in the format `service.instance`. This value is an array, and must be specified as so in the soa config.
When the job object is formatted into the JSON to be POSTed to Chronos, the 'service.instance' is translated into the 'full' job name by finding the most recent job associated with that service instance.
Caveats:
- The 'parent' job must already be launched in chronos before the dependent job is launched #147
- Validation for a matching job is done at launch time, rather than at 'validate' time.
- parents is an array, and setting the ``parent`` value as a string rather than …
> First support for creating dependent jobs - Fixes #140, #141, #146

- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- tests/cli/test_cmds_validate.py
This change attempts to bring out schemas (used for validation) in line with http://paasta.readthedocs.org/en/latest/yelpsoa_configs.html . I manually tested it against all of our existing yelpsoa configs with no unexpected results. While doing this, I discovered a small bug with the validate command that prevented it from validating all yaml files (and I fixed it).
Closes #129
> Extend schemas

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
This fixes #124. Thanks to @Rob-Johnson and @asottile for their help.
> Run command inside sh c local run

- paasta_tools/deploy_chronos_jobs
- paasta_tools/list_chronos_jobs.py
- paasta_tools/list_marathon_service_instances.py
The shuf command shuffles lines, but list_chronos_jobs outputs 1
space-delimited line. This fixes #154
> Make deploy_chronos_services shuffle

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_check.py
This will avoid `paasta check` message such as:
```
✗ There are some instance(s) in deploy.yaml that are not referenced
by any marathon instance:
cluster-name.batch-name, cluster-name2.batch-name
You should probably delete these deploy.yaml entries if they are unused.
```
when there is a chronos-*.yaml file referencing the instance.
This change also will not show:
```
✗ No marathon.yaml exists, so your service cannot be deployed.
Push a marathon-[superregion].yaml and run `paasta generate-pipeline`.
More info: http://y/yelpsoa-configs
```
if a chronos.yaml file exists (and will show a more accurate message if neither yaml file exists).
Closes #110
> Consider chronos*.yaml for deploy checks (Closes: #110)

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
internal ticket PAASTA-2455.
This passes the `accepted_resource_roles` parameter through marathon.yaml into the marathon config, allowing for apps to be deployed to dedicated hardware.
> Allow users to set accepted_resource_roles in marathon yamls.

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_check.py
This change adds support for a --yelpsoa-config-root argument in `paasta check`. I believe I have updated all of the checks it does to properly handle this directory. All of the PaaSTA tests are also passing locally.
> Add --yelpsoa-config-root argument to 'paasta check'

- paasta_tools/paasta_metastatus.py
Used the table formatting tools in paasta_tools.utils to clean up very verbose metastatus formatting for long hostnames.
> Fixed formatting for very verbose paasta metastatus

- general_itests/steps/deployments_json_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- tests/test_chronos_tools.py
- tests/test_generate_deployments_for_service.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
- tests/test_monitoring_tools.py
- tests/test_setup_chronos_job.py
- tests/test_setup_marathon_job.py
- tests/test_utils.py
InstanceConfig and it's children MesosServiceConfig and ChronosJobConfig now directly store service name, cluster and instance. This should enable some cleaner code in the future.
> made InstanceConfig take service, cluster and instance as args

- paasta_tools/bounce_lib.py
- paasta_tools/graceful_app_drain.py
Added a script to drain and kill a marathon app.
> Added a script to drain and kill a marathon app as gracefully as possible

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Running paasta metastatus -vv on a cluster with no mesos slaves will no longer throw an exception (hopefully)
This also takes into account running paasta metastatus on a mesos setup with no frameworks, or no tasks in a framework.
> fixed paasta_metastatus -vv when there are no mesos slaves

- .travis.yml
- general_itests/steps/paasta_execute_docker_command.py
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_itests/steps/marathon_steps.py
- paasta_itests/steps/mesos_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_chronos_job_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- requirements-dev.txt
- tests/test_bounce_lib.py
- tests/test_check_chronos_jobs.py
- tests/test_check_marathon_services_replication.py
- tests/test_chronos_serviceinit.py
- tests/test_chronos_tools.py
- tests/test_cleanup_marathon_jobs.py
- tests/test_drain_lib.py
- tests/test_generate_deployments_for_service.py
- tests/test_generate_services_yaml.py
- tests/test_marathon_tools.py
- tests/test_monitoring_tools.py
- tests/test_paasta_metastatus.py
- tests/test_setup_chronos_job.py
- tests/test_setup_marathon_job.py
- tests/test_utils.py
- tox.ini
This probably requires some explaining (and may not be entirely complete).
Currently tox sets `PYTHONPATH=paasta_tools/` which is entirely unrealistic in a real running situation, writing code which depends on this will pass under test but fail miserably when run in an integration scenario.
I also had to change `py.test` to `python -m pytest`.  The former puts the bin/ directory on the pythonpath.
I removed the line in tox and then fixed all the things that broke because of it.
> Remove PYTHONPATH hax when running tests

- tox.ini
This will use py27 on machines that have `python` that is not python2.7 (such as lucid)
I didn't notice this when changing this since I was developing on trusty (and travis uses precise)
> Force python2.7 in other tox environments

- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_check.py
- tests/cli/test_cmds_validate.py
This will allow `paasta check` to notify users of additional errors with their service. It will catch things such as invalid yelpsoa config syntax (based on the jsonschemas) and invalid chronos schedules.
Closes #128
> Make paasta check call validate (Closes #128)

- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- tests/test_marathon_tools.py
- tests/test_setup_marathon_job.py
I investigated *why* this happens, I do believe it is the race between killing a task in a previous test and reading it in the next. Here is some correlated logs:
```
Scenario: The crossover bounce works
Given a working paasta cluster
And a new healthy app to be deployed
And an old app to be destroyed
When there are 2 old healthy tasks
And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated
crossover bounce creating new app with app_id bounce.test1.newapp.confighash
Then the new app should be running
And the old app should be running
When there are 1 new healthy tasks
And deploy_service with bounce strategy "crossover" and drain method "noop" is initiated
crossover bounce draining 1 old tasks with app_id /bounce.test1.oldapp.confighash
crossover bounce …
```
> Catch the 'bean not found' error. Fixes #172

- .travis.yml
- tests/test_chronos_tools.py
- tox.ini
Make local runs of tox faster by moving pre-commit to testenv:general_itest, moving coverage into its own testenv, and speeding up a unit test that was taking 1 second.
> Make tox faster

- docs/source/generated/paasta_tools.graceful_app_drain.rst
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Docker containers created by local_run will now have a $HOST variable containing the hostname of the machine the container is running on.
> added a HOST variable to docker containers

- paasta_tools/check_marathon_services_replication.py
This should fix a lot of the health checks that started failing after PR 145
> Converts marathon's `started_at` to the local tz

- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/setup_chronos_job.feature
- paasta_itests/steps/chronos_steps.py
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- paasta_tools/setup_chronos_job.py
- tests/test_chronos_tools.py
- tests/test_setup_chronos_job.py
This reverts the revert + adds the config sha to the 'description' field of the chronos job so that jobs are only bounced when necessary.
> Remove tags chronos jobs

- paasta_itests/setup_chronos_job.feature
- paasta_itests/steps/setup_chronos_job_steps.py
- paasta_tools/setup_chronos_job.py
Address #147 by catching `InvalidParentError` in `setup_chronos_job` and returning a 0 exit code.
Alternatively, we could add logic to `list_chronos_jobs` to shuffle the jobs while maintaining parent-dependent relationships. That's not currently possible because the `xargs -P 5` in 
[deploy_chronos_jobs](https://github.com/Yelp/paasta/blob/42ae5c252fd80e08dea2885e09b3c11949748311/paasta_tools/deploy_chronos_jobs#L3)) is likely to de-serialize the jobs again.
> skip dependent jobs if they are created before their parent

- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_tools/cleanup_chronos_jobs.py
- tests/test_cleanup_chronos_jobs.py
This should make deploying robj's change easier and also prevent random chronos jobs from mixing in with paasta jobs in the future.
This also makes `cleanup_chronos_jobs` behave more like `cleanup_marathon_jobs`.
> made cleanup_chronos_jobs remove all non-paasta jobs

- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
- paasta_tools/cleanup_chronos_jobs.py
- tests/test_check_chronos_jobs.py
When instances are removed from a `chronos-*.yaml` `cleanup_chronos_jobs` now sends an OK status to sensu.
> made cleanup_chronos_jobs send OK on sensu

- docs/source/installation/getting_started.rst
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/utils.py
- tests/cli/test_cmds_check.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/cli/test_cmds_rollback.py
- tests/cli/test_cmds_status.py
- tests/cli/test_cmds_validate.py
- tests/test_generate_deployments_for_service.py
Placing multiple instances in a deploy group makes it so they are all deployed with the same docker container and are deployed at the same time (as specified in deploy.yaml). However, they can be controlled independently by flagging deploy_state and force_bounce in git refs.
> Enabled deploy_groups

- yelp_package/Makefile
Currently running `make release` leaves setup.py in a state that doesn't conform to PEP8. This makes it so we have to run pre-commit twice when pushing a new release.
That sucks so I fixed it.
> make release no longer breaks PEP8

- paasta_itests/steps/marathon_steps.py
- paasta_tools/cleanup_chronos_jobs.py
Primary: @EvanKrall 
Seems so obvious amirite?
I've kept the get_local_slave_state but only if the assertion fails, I need it to debug why this didn't work.
> Use acutal running tasks for marathon_services_running_here_works itest

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_start_stop_restart.py
Bugged == of the format 'paasta-paasta-cluster.instance'.
Also added an itest that makes sure generate deployments works properly with force_bounce and state tags.
> added support for old bugged refs/tags

- paasta_tools/bounce_lib.py
- paasta_tools/setup_marathon_job.py
- tests/test_bounce_lib.py
- tests/test_setup_marathon_job.py
This changes the bounce function interface so that the bounce code knows which old tasks are healthy and which are not. Specifically, I split the `old_app_live_tasks` into two groups: happy and unhappy. These are determined by `get_happy_tasks`.
This allows the bounce functions (specifically, crossover) to make decisions about which old tasks to kill, instead of treating them identically.
> Have crossover bounce prefer killing unhealthy tasks.

- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
Config files that use deploy groups will no longer fail paasta check.
> added deploy_group to valid schemas for paasta check

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
This has become pretty easy now that we are wrapping kill_task.
> Gracefully handle killing a marathon task that is already dead. PAASTA-1219

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Following http://paasta.readthedocs.org/en/latest/upgrading_mesos.html . This is step 1 to bump the version of Mesos that is installed in the integration tests.
> Upgrade mesos to 0.23.1-0.2.61.ubuntu1404

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
Use the full GPG fingerprint rather than just the short id. This avoids
accidentally adding the wrong key per
http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html
Closes #212
> Use full GPG fingerprints

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/remote_git.py
- paasta_tools/utils.py
- tests/test_remote_git.py
In an effort to migrate us from branches to tags, this first pull request updates `mark_for_deployment` to tag as well as create a branch. Since branches are still being created like normal and no other code has been updated to switch from branches to tags, this should be a safe change.
The change to CHAGNELOG.md was to make the pre-commit hook happy.
> Mark for deployment tags

- paasta_tools/marathon_serviceinit.py
- tests/test_marathon_serviceinit.py
During a bounce you may not have a marathon app running, or it may have just went away.
We guard if the app_id is not running in the first place on non-verbose mode, so here is me doing it for verbose mode.
> Catch the race between inspecting a marathon app that isn't running during a bounce. PAASTA-1721

- docs/source/yelpsoa_configs.rst
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
The healthcheck_mode option was added to nerve-tools, but it is not actually loaded from the config file since the 'healthcheck_mode' key is not in the whitelist.
> Add healthcheck_mode to service config

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/utils.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_cmds_start_stop_restart.py
- tests/cli/test_utils.py
This fixes a bug where paasta start and stop wouldn't work on tasks using deploy groups.
> made paasta start/stop deploy-group aware

- paasta_tools/utils.py
I don't know how we got along without this so far. The PAASTA_ stuff just exaggerated it?
> Use json.dumps to get more consistent hash keys

- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
...into multiple parts, without having to use Mesos's roles.
> WIP: Implement 'pool': An attribute & constraint that lets you split a cluster

- paasta_tools/cli/schemas/chronos_schema.json
Should fix #217.
I wasn't sure what's allowed as a job name, so I used "`^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$`".
`parents` array:
```
mesosstage_robj_child:
parents:
- example_service.mesosstage_robj_parent
cmd: 'echo "I am a batch"'
monitoring:
team: noop
deploy_group: dev-stage.everything
(py27)gcioffi@dev9-devc:~/git/paasta (update_chronos_json_schema-issue-217) $ paasta_tools/cli/cli.py check -y ~/git/yelpsoa-configs -s example_service | grep schema.*chronos
✓ Successfully validated schema: chronos-mesosstage.yaml
```
`parents` string:
```
mesosstage_robj_child:
parents: example_service.mesosstage_robj_parent
cmd: 'echo "I am a batch"'
monitoring:
team: noop
deploy_group: dev-stage.everything
(py27)gcioffi@dev9-devc:~/git/paasta (update_chronos_json_schema-issue-217) $ …
```
> Update chronos json schema #217

- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- tests/test_chronos_serviceinit.py
- tests/test_chronos_tools.py
This is slightly wasteful, in that we're doing the lookups for the parent jobs multiple times. I'm ok with that for now, but probably a case where we can optimize if we get to the point where it's impacting on performance.
Closes #96
> Show details of parents in output of ``paasta status``

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
Allow `parents` jobs to be passed in the config as an array or a string, see #149.
Note that the `parents` key isn't currently schema-validated (will be fixed in #217).
Closes #149
> allow a string or array value for the 'parents' key of a dependent job

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
This new itest should avoid us adding code that modifies deployments.json in such a way that new services no longer have a desired_state of 'start'. This should help avoid incidents like #223 from happening again.
> Add a new itest to assert new services have a desired_state of start

- paasta_tools/contrib/kill_orphaned_docker_containers.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_execute_docker_command.py
- tests/test_mesos_tools.py
- tests/test_paasta_execute_docker_command.py
This is an experimental script that looks at the *slave* state and kills orphaned containers.
With the new mesos upgrade, it left behind a bunch. Some of the bug reports suggest that when you do upgrades to blow away the metadata..... In the future after we do an upgrade we can run this script in dry-run mode to see?
Comments welcome, but I want to ship this before the weekend so our boxes don't continue to have really full disks, bogus orphaned tasks running everywhere, and clusters out of resources.
Longer term maybe we can run this as a monitoring check, returning 0 if there is no bogus containers, and 1 if there is some.
> Added experimental manual mesos task reconciliation script (orphan killer)

- docs/source/yelpsoa_configs.rst
- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
Also clarify docs on constraints.
> Add extra_constraints, which doesn't override default constraints.

- paasta_tools/generate_deployments_for_service.py
The deploy groups change left an extra arg to a method in generate_deployments. This removes it.
> removed unnecessary arg from generate_deployments.get_desired_state

- paasta_tools/contrib/kill_orphaned_docker_containers.py
reduced runtime  by casting running container list to a set
We check for the membership of every running docker container id against the list of running containers that are in mesos. Since checking membership in a list is an O(n) operation, this runs in quadratic time. Changing to a set reduces the runtime to linear since sets have constant-time lookup.
> reduced kill_orphaned_docker_containers runtime

- paasta_tools/chronos_serviceinit.py
- tests/test_chronos_serviceinit.py
> paasta status - show the value of schedule_time_zone (PAASTA-2389)

- docs/source/yelpsoa_configs.rst
- general_itests/fake_soa_configs/fake_deployments_json_service/marathon-test_cluster.yaml
- general_itests/fake_soa_configs_fsm_wizard/paasta_service/marathon-SHARED.yaml
- general_itests/fake_soa_configs_local_run/fake_simple_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_local_run/fake_simple_service/marathon-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_invalid_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_invalid_service/marathon-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/chronos-test-cluster.yaml
- general_itests/fake_soa_configs_validate/fake_valid_service/marathon-test-cluster.yaml
- paasta_itests/docker-compose.yml
- paasta_itests/paasta_metastatus.feature
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_tools/check_mesos_resource_utilization.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/marathon_tools.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/utils.py
- tests/cli/test_cmds_validate.py
- tests/test_check_mesos_resource_utilization.py
- tests/test_chronos_tools.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
- tests/test_mesos_tools.py
- tests/test_paasta_metastatus.py
- tests/test_utils.py
This is a first pass at adding this functionality. I went through trying to find all of the places we deal with cpu/mem and adjusted the code to also deal with disk space. I'm sure I've missed a spot or two in the code, but all of the tests are currently passing. I wanted to get this pull request tossed up so that I can get some feedback.
> Add support for disk resource isolation

- docs/source/deploy_groups.rst
Fixed a small typo in docs/source/deploy_groups.rst where the example
code used deploy_groups instead of deploy_group.
> Fixed typo in docs/source/deploy_groups.rst

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/remote_git.py
- paasta_tools/utils.py
- tests/test_generate_deployments_for_service.py
- tests/test_remote_git.py
Fix issues where a tag ending in '-deploy' was interpreted as stop
* Fix an issue with the recently added itest to make it actually call mark-for-deployments before testing the desired_state
* Add a whitelist that will prevent states other than 'start' and 'stop' from getting written to deployments.json (we will add 'deploy' later)
Without the `valid_states` code, the 'New services have a desired_state of "start"' itest fails as expected. With the new code, it passes.
Closes #223
> Mark for deployment tags take2

- paasta_tools/cli/cmds/logs.py
Seems like we should be consistent about using verbose everywhere
> Use verbose flags instead of debug in paasta logs

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/utils.py
- tests/cli/test_cmds_metastatus.py
Sample output:
```
matts@dev2-devc:~/paasta (master) $ python paasta_tools/cli/cli.py metastatus -c nova-prod
Cluster: nova-prod
Note:              Viewing raw dashboards in prod requires an extra proxy. See https://docs.google.com/document/d/1OXEcmSubOG8T0RHFETh3GM98AF0MXj-1vQL6x8xLJO0/edit#heading=h.anrifrwk9e2r
Chronos RO:        http://chronos-nova-prod.yelpcorp.com (LDAP Login)
Mesos:             http://mesos.paasta-nova-prod.yelp (Requires Prod Proxy, see note at the end)
To run metastatus: paasta metastatus -c nova-prod (requires prod access)
Smartstack:        http://paasta-nova-prod.yelp:3212  (Requires Prod Proxy, see note at the end)
Signalfx:          https://app.signalfx.com/#/dashboard/CYJklh9AYAo?sources%5B%5D=superregion:nova-prod
Marathon RO: …
```
> made metastatus read from /etc/paasta to get dashboards

- paasta_tools/contrib/delete_old_marathon_deployments.py
- requirements.txt
- setup.py
I don't know "why" this has started happening, and I don't consider this to be a normal condition, but somehow we get these marathon deployments that are left behind for a long period of time, and they seem to harm bounces.
This seems like a good start at remediation, just killing deployments that have been around for a long time?
Almost all the time what is left behind are the remnants of the "kill and scale" procedures we do, so I "think" this is safe? I'll start by manually running this in a few clusters to kick them, and then maybe automate this.
> Added experimental script to kill old marathon deployments

- paasta_tools/cli/cmds/check.py
- tests/cli/test_cmds_check.py
It was pointed out that when `paasta check` tests for a team and proxy_port, it displays a failure when a custom soa_dir is specified. This PR properly passes the soa_dir argument to fix that issue.
> Update paasta check sensu_check and smartstack_check to pass soa_dir

- paasta_tools/check_marathon_services_replication.py
- tests/test_check_marathon_services_replication.py
> marathon tasks with started_at of None are now unhealthy

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
Apparently mesos 0.23 and up execute the command healthchecks *in* the container, so we no longer need our wrapper script. (see also https://github.com/mesosphere/marathon/issues/2140)
> No longer use paasta_execute_in_container for command healthchecks.

- paasta_tools/setup_chronos_job.py
Fixes this trace:
```
File "/usr/bin/setup_chronos_job", line 234, in <module>
main()
File "/usr/bin/setup_chronos_job", line 193, in main
output=error_msg,
File "/usr/bin/setup_chronos_job", line 93, in send_event
soa_dir=soa_dir,
File "/usr/share/python/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/chronos_tools.py", line 159, in load_chronos_job_config
raise UnknownChronosJobError('No job named "%s" in config file chronos-%s.yaml' % (instance, cluster))
paasta_tools.chronos_tools.UnknownChronosJobError: No job named "None" in config file chronos-norcal-prod.yaml
```
> made setup_chronos_jobs handle non-existant jobs

- general_itests/steps/fsm_wizard_steps.py
- paasta_tools/cli/cmds/fsm.py
- paasta_tools/cli/fsm/questions.py
- paasta_tools/utils.py
- tests/cli/fsm/fsm_test.py
- tests/cli/fsm/questions_test.py
This changes the default deploy order to stage -> prod canary -> prod non-canary & dev
@EvanKrall @asottile you can argue for or against this here
> re-ordered default deploy order in fsm

- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_validate.py
This should fix #148 .
Catches two types of config errors:
- Parents whose name is invalid (!= `service_name.instance_name`). Similar to what the JSON schema also enforces.
- Parents that are referenced in a dependent job, but are not actually configured.
Note that the second validation won't let a "`ServiceA` child" depend on a "`ServiceB` parent". That's the best we can do without parsing the entire `yelpsoa-configs` tree.
In my opinion `paasta_tools/cli/cmds/validate.py`, in order to validate the Chronos config, needs to know too many details about `ChronosJobConfig`. If need be, I'm happy to move as much of that logic into `paasta_tools/chronos_tools.py` as possible, so that the latter is in charge of the validation and the former just prints out the outcome.
> validate dependent jobs' parents - issue 148

- docs/source/workflow.rst
- docs/source/yelpsoa_configs.rst
- paasta_itests/docker-compose.yml
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Pass the `--env_vars_prefix` argument to Marathon. By using this argument, we can avoid having it hog the `PORT` environment variable.
I'm removing the warnings in the docs. The contract still notes the requirement to use port 8888. I have also removed the hack in `local_run` to explicitly set the `PORT` environment variable to match production.
Fixes #152
> Pass --env_vars_prefix to marathon and remove local_run workaround

- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
Currently, `paasta validate` complains about marathon/chronos configs that contain these keys. This change fixes that so they show up as valid.
I am also wondering if it is worth adding some more logic around the constraints to make `paasta validate` aware of invalid constraints.
> Add extra_constraints and pool to schemas for paasta validate

- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/cook_image.py
- paasta_tools/cli/cmds/generate_pipeline.py
- paasta_tools/cli/cmds/itest.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/push_to_registry.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/cmds/security_check.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_cook_image.py
- tests/cli/test_cmds_generate_pipeline.py
- tests/cli/test_cmds_itest.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/cli/test_cmds_push_to_registry.py
- tests/cli/test_cmds_rollback.py
- tests/cli/test_cmds_validate.py
We use sys.exit in many many places. It seems easier if we just return a number and let that go back to the cli entrypoint and let it sys.exit in a central place.
It simplifies a lot of our testing and stuff. We still sys.exit early in other places when we panic, but that is ok I think.
> Use returncode instead of sys.exit in the paasta cli

- paasta_tools/cli/cmds/check.py
Right now if there are chronos jobs that aren't listed in `deploy.yaml`, `paasta check` prints out a list of marathon instances instead.
Example:
```
✗ There are some instance(s) you have asked to run in chronos that
do not have a corresponding entry in deploy.yaml:
You should probably add entries to deploy.yaml for them so they
are deployed to those clusters.
```
> Fix an output bug in paasta check

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We now use Marathon's `--env_vars_prefix` option. This change makes sure that services run with `local-run` have `MARATHON_PORT` set similarly to how it would be set once deployed.
> Set MARATHON_PORT env variable in local-run

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
This change actually performs the mesos 0.24.1 upgrade. I split it out of my previous PR so that we could be certain the mesos.cli upgrade would work properly.
> Mesos 0.24.1

- paasta_itests/itest_utils.py
- paasta_itests/steps/mesos_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/mesos_tools.py
- requirements.txt
- setup.py
- tests/test_mesos_tools.py
- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
This reverts commit 28ebb20a109d7539989d1cbc639acdd25b540f61.
Conflicts:
paasta_tools/mesos_tools.py
tests/test_mesos_tools.py
> Revert "Upgrade mesos.cli for mesos 0.24.1 upgrade"

- general_itests/environment.py
- general_itests/steps/paasta_execute_docker_command.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/contrib/kill_orphaned_docker_containers.py
- paasta_tools/paasta_execute_docker_command.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
- tox.ini
Fixes #287 and also enables us to use TLS in the future to secure Docker's api
> Allow paasta to use docker http api

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
> send OK event when a chronos job has been disabled

- paasta_itests/itest_utils.py
- paasta_itests/steps/mesos_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/mesos_tools.py
- requirements.txt
- setup.py
- tests/test_mesos_tools.py
This reverts commit 9ada5bc579e3bfbaff6c5e961e91f43e59335326.
We reverted the mesos.cli upgrade on Friday. This change performs the upgrade again.
> Redo mesos.cli upgrade

- docs/source/workflow.rst
- docs/source/yelpsoa_configs.rst
Mention that Marathon adds environment variables that are prefixed with `MARATHON_` and that it won't touch user-specified env variables.
> Update docs to note Marathon env_var_prefix

- general_itests/steps/paasta_execute_docker_command.py
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_serviceinit.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
- tests/test_chronos_serviceinit.py
- tests/test_mesos_tools.py
`paasta status -vv` displays, for each Mesos task in the output (Marathon, Chronos, running and non-running) 10 lines from the tail of both `stdout` and `stderr`.
Happy path. `stdout`/`stderr` are purposely not indented (if they were, long lines wrapping would arguably make the output more confusing).
Exceptions come from `mesos.cli`, they are trapped and displayed (`paasta status` still returns zero in that case).
> Add stdout/err tail snippet to paasta status -vv (PAASTA-3268)

- paasta_tools/marathon_tools.py
`self.config_dict.get('autoscaling', default_params)` doesn't work if `'autoscaling'` is only a partial dict -- e.g. there are two default params and `'autoscaling'` only contains one of them.
> fixed the default autoscaling config args

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
The mesos.cli upgrade appears to be working fine now. This PR is in preparation of trying the mesos 0.24.1 upgrade again.
> Do the mesos upgrade again

- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
`paasta status -v` returns the list of Non-Running Tasks in a random
order. Also it only shows the last 10, so you might see old runs but not
the more recent ones.
This change orders the not_running_tasks list by start time. Since
they're reversed in status_mesos_tasks_verbose they'll be printed from
the latest one to the oldest one.
AFAICT this script is run directly on the mesos master, so I wasn't able to really try it.
> Order tasks in verbose paasta status

- paasta_itests/docker-compose.yml
- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
This change updates mesos/marathon/chronos to use [authentication](http://mesos.apache.org/documentation/latest/authentication/) to communicate. This more closely matches production, and it should allow us to spot issues (such as those caused by the mesos 0.24.1 upgrade) faster.
This PR also changes the itests to use mesos 0.23.1 again for the time being.
> Use authentication with mesos in itests

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
I finally managed to get mesos 0.24.1 to pass the tests and have marathon properly authenticate. We were getting bitten by https://issues.apache.org/jira/browse/MESOS-3560
This issue is fixed in 0.26.0 via a breaking change.
> Mesos 0.24.1 Passes Tests!

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Add more detail to the output of paasta_metastatus. When used with the current Mesos test data, output at the moment looks like: 
```
Habitat         CPU free  RAM free  Disk free
test-habitat-2  50.00     1000.00   200.00
test-habitat    0.00      1000.00   100.00
```
With this change it looks like: 
```
Habitat         CPU (free/total)  RAM (free/total)  Disk (free/total)
test-habitat-2  50.00/50.00       1000.00/1000.00   200.00/200.00
test-habitat    0.00/50.00        1000.00/1000.00   100.00/200.00
```
> Print metastatus free resources alongside total resource capacity

- paasta_tools/utils.py
- tests/test_utils.py
This depends on #281 and fixes #64.
This branch makes another LogWriter implementation: `file`, which writes to a specified file. I expect most people to want the file opened in append mode, so I've set that as the default.
It also allows you to format the path based on service / component / level / cluster / instance, in case you want different files per service or something.
cc @hashbrowncipher for sanity-checking my usage of flock and io.
> Make FileLogWriter, which writes json-formatted log lines to a specified file.

- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
PR #295 taught `paasta status -v` to sort/truncate the list of non running Mesos tasks. It introduced a bug that broke `paasta status -vv`: the truncated list of tasks was not consistently used throughout the code, leading to an `Can only zip same-length lists` exception.
b974221d08c9a3bc01793b494ac04d98b51ef717 fixes said bug and updates the tests.
01df0eed16b30ac0ff2578a555bfb192905e1032 attempts to remove some duplication in `status_mesos_tasks_verbose`.
> Fix `paasta status -vv`

- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
Currently paasta restart -c accepts only one cluster. There has been an internal request to allow -c to use a list of clusters. 
There is some inconsistency around how this is currently implemented, with emergency_scale, emergency_restart, emergency_stop, emergency_start, restart and local_run using ```--cluster```, and logs, status and metastatus supporting ```--clusters```.
> Allow 'paasta re.start -c' to use a list of clusters

- requirements.txt
Mesos has been upgraded to 0.24.1 everywhere. The final step to finish this upgrade is to bump the version of `mesos.interface` in `requirements.txt` to 0.24.1
> Upgrade mesos.interface to 0.24.1

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
During local-run if for any reason the health check fails, then local-run exists with a stacktrace, and leaves the container running.
> Catch failed responses during http healthcheck

- paasta_tools/cli/cmds/fsm.py
TL;DR a comma at the end of a line causes a statement to be interpreted as a 1-tuple
Before:
```
---
- pipeline:
- instancename: itest
- instancename: security-check
- instancename: push-to-registry
- instancename: performance-check
- instancename: stage.everything
trigger_next_step_manually: true
- instancename: prod.canary
trigger_next_step_manually: true
- instancename: prod.non_canary
- instancename: dev.everything
```
After:
```
---
pipeline:
- instancename: itest
- instancename: security-check
- instancename: push-to-registry
- instancename: performance-check
- instancename: stage.everything
trigger_next_step_manually: true
- instancename: prod.canary
trigger_next_step_manually: true
- instancename: prod.non_canary
- instancename: dev.everything
```
> fixed paasta fsm creating invalid deploy.yaml

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Currently the outputs of ```paasta metastatus -vv``` and ```paasta metastatus -vvv``` are quite inconsistent. 
```paasta metastatus -vv``` will return: 
```
Hostname             CPU free  RAM free  Disk free
test3.somewhere.www  22.00     920.00    200.00
test.somewhere.www   25.00     0.00      150.00
test2.somewhere.www  500.00    750.00    200.00
```
While ```paasta metastatus -vvv``` will return: 
```
Habitat                 CPU (free/total)  RAM (free/total)  Disk (free/total)
somenametest-habitat-2  522.00/522.00     1670.00/1670.00   400.00/400.00
somenametest-habitat    25.00/75.00       0.00/100.00       150.00/250.00
```
This PR brings the two output formats somewhat into cohesion and also uses ```humanize``` to make the outputs a little more friendly to users: 
```paasta …
```
> Make -vv output consistent with -vvv output, humanize figures

- paasta_tools/cli/schemas/chronos_schema.json
A couple of services were failing `paasta validate` because of this.
Fixes #338
> added schedule_time_zone to chronos schema

- paasta_tools/utils.py
- tests/test_utils.py
Fixes #60 
The test added in this commit fails without this change with error `UnboundLocalError: local variable 'proctimer' referenced before assignment`
> fixed _run throwing an error when popen failed with a timeout

- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_utils.py
Fixed a bug where your entire `monitoring.yaml` config changes would be blown away if an instance had any monitoring configs. Probably applies to non-monitoring config files as well.
> stopped per-instance configs from nuking global defaults

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Fixes #348 
Should these healthchecks return False when Mesos says it has 0 available cpu/mem/disk?
> made metastatus print sane errors if mesos states it has 0 resources

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_start_stop_restart.py
- tests/test_generate_deployments_for_service.py
This change migrates us from using branches to using tags for deployments. Ever since #252 was merged, we have been creating -deploy tags in addition to the git branches. With this change, we will now actually use those tags and stop creating branches.
> Use tags rather than branches for deployments

- docs/source/yelpsoa_configs.rst
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/marathon_tools.py
- tests/test_check_marathon_services_replication.py
Being able to configure per-component monitoring would be useful for certain services. Currently replication percentages can only be checked across the board via one command line argument to `check_marathon_services_replication.py`, and this PR moves this configuration to an instance's yelpsoa configuration file in the `replication_crit` key. 
The default of 50 is retained if the `replication_crit` value is not specified. According to puppet and opengrok check_marathon_services_replication is not in use with an argument anywhere.
> Move configuration of replication monitoring to yelpsoa config

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
closes #333 
marathon only expects strings even it'd be logical to do otherwise,
so stringify every value to be sure it'll be ok.
> stringify any constraint vals for marathon

- paasta_tools/contrib/mass-deploy-tag.sh
This script was used to help prepare for merging #326 . It is likely useless as-is, but it can serve as an example in making mass changes to all service git repositories.
> Add mass-deploy-tag.sh to contrib/

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
I had this swapped when I added `deep_merge_dictionaries`.
I'd like this to be pushed out quickly because atm @gstarnberger is getting spammed with alerts.
> fixed a bug where smartstack.yaml was overriding marathon.yaml

- yelp_package/Makefile
- yelp_package/bintray.json.in
- yelp_package/dockerfiles/trusty/Dockerfile
This fixes a few issues: For some reason, travis(dpl) didn't like my includePattern; it didn't try uploading anything. I've changed the pattern to be more generous, so I've made it so we don't drop dh-virtualenv*.deb into dist/ when running itest_trusty.
I also noticed I wasn't properly setting the date in bintray.json, so I fixed that.
> Fix bintray upload

- general_itests/environment.py
- paasta_itests/environment.py
- tox.ini
This switches us to use https://github.com/ribozz/behave-pytest , which will provide us with some more information when an assertion fails (actual and expected values). Some of the output will look a bit off (due to how we have color/formatting in our output), but it should still help with debugging test failures.
> Use behave-pytest for pytest-style asserts

- paasta_itests/docker-compose.yml
- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Now that I think I've sorted out all of the issues with mesos 0.24.1, it is time to upgrade to 0.25.0. I encountered one [issue](https://www.mail-archive.com/user@mesos.apache.org/msg04937.html) with this upgrade which I fixed (I will make a similar change within Puppet).
I will obviously hold off on merging this change until we are sure we have 0.24.1 working everywhere.
> Upgrade to mesos 0.25.0

- .travis.yml
This prevents pypi deployments from messing with dist/ on the itest_trusty build.
In testing my original bintray uploading branch, the pypi deployment wasn't running (since it only runs on tags), so my testing worked just fine. Once I merged, however, the uploads stopped working. It appears that the pypi development does something to the dist/ directory (cleans it out?), so if the pypi and bintray deployers both run on the same build, bintray won't work.
This should also prevent us from uploading the same package to pypi 6 times in one go.
> Only deploy to pypi on py27 build

- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/steps/chronos_steps.py
- paasta_itests/steps/cleanup_chronos_job_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/cleanup_chronos_jobs.py
- paasta_tools/cli/cmds/validate.py
- tests/cli/test_cmds_validate.py
- tests/test_cleanup_chronos_jobs.py
closes #324 
This makes ``cleanup_chronos_jobs`` aware of temporary jobs. It will only clean any temporary jobs up when:
- the job has completed (either successfully or unsuccessfully)
- the job completed > 24 hours ago.
By keeping the job around for 24 hours, the job will continue to be visible to users via ``paasta status`` once the run has completed (so service authors can inspect the job to find the current status)
> Ensure cleanup jobs understands tmp jobs

- paasta_tools/cleanup_marathon_jobs.py
- tests/test_cleanup_marathon_jobs.py
Right now there are potentially 3 sensu alerts that could be thrown on a marathon service, this cleanup resolves them all.
> Make the marathon cleanup script resolve all related sensu events.

- paasta_tools/chronos_rerun.py
> fix escaping in chronos_rerun help string

- paasta_tools/cleanup_chronos_jobs.py
- tests/test_cleanup_chronos_jobs.py
closes #388 
There was a missing cast of string -> datetime, causing the comparison of time to fail.
> parse the datetime string from lastruntime in chronos jobs

- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- requirements.txt
- setup.py
- tests/test_marathon_tools.py
- yelp_package/dockerfiles/itest/marathon/Dockerfile
Apparently, our old version of marathon is trying to access newly renamed mesos endpoints. This issue (among other things) should be fixed by upgrading.
> Upgrade to marathon 0.13.1 in itests

- docs/source/upgrading_marathon.rst
Our marathon upgrade procedure has changed a bit since the last time we upgraded. This change updates our docs.
> Make the marathon upgrade docs match current practice

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
This function needs to tolerate the situation where we could potentially give it an appid without a leading slash (like from a generated appid or a user provided one) or from the API which might return leading slashes. (the api is not consistent when it provides a leading slash or not.)
> Make is_app_id_running tolerate leading slashes

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
This is the most recent release of Mesos, so after this upgrade, we will finally be up-to-date.
> Upgrade mesos to 0.28.0-2.0.16.ubuntu1404 in itests

- yelp_package/dockerfiles/itest/marathon/Dockerfile
With the mesos 0.26.0 upgrade underway, we can begin testing marathon 0.14.2 (which was tested against mesos 0.26.0).
> Upgrade tests to use marathon 0.14.2

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_local_run.py
Before:
```
matts@dev2-devc:~/paasta (master) $ sudo python paasta_tools/cli/cli.py local-run -s example_service -c mesosstage -i mesosstage_main -p -y /nail/home/matts/yelpsoa-configs/
File "paasta_tools/cli/cli.py", line 99, in <module>
main()
File "paasta_tools/cli/cli.py", line 95, in main
File "/nail/home/matts/paasta/paasta_tools/cli/cmds/local_run.py", line 681, in paasta_local_run
pull_image=pull_image,
File "/nail/home/matts/paasta/paasta_tools/cli/cmds/local_run.py", line 592, in configure_and_run_docker_container
soa_dir=args.yelpsoa_config_root,
File "/nail/home/matts/paasta/paasta_tools/cli/utils.py", line 618, in get_instance_config
soa_dir=soa_dir
File …
```
> made local run create a fresh deployments.json

- yelp_package/dockerfiles/itest/mesos/Dockerfile
- yelp_package/dockerfiles/itest/mesos/mesos-secrets
- yelp_package/dockerfiles/itest/mesos/mesos-slave-secret
https://issues.apache.org/jira/browse/MESOS-2281 deprecates using plain text credentials for authentication in Mesos 0.29.0. The bug that forced us to move off of json credentials has been fixed. This PR switches us back to using json.
> Use json for mesos authentication

- requirements.txt
We've upgraded to mesos 0.28.0. This bumps up mesos.interface in requirements.txt.
> Bump mesos.interface to 0.28.0

- yelp_package/dockerfiles/itest/marathon/Dockerfile
Now that we are running mesos 0.28.0, we can try and upgrade to marathon 0.15.3. This is the most recent release of marathon.
> Upgrade marathon to 0.15.3-1.0.463.ubuntu1404 in itests

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
This reverts commit c8eaa31533407ff3400776b1abf1c611e192515d, reversing
changes made to c0733d2541c6a4d963ba6a344f42ab2e12fbd876.
This was done for good reason, as documented in our soa-configs:
>  Although Chronos supports an empty start time to indicate that the job should start immediately, we do not allow this. In a situation such as restarting Chronos, all jobs with empty start times would start simultaneously, causing serious performance degradation and ignoring the fact that the job may have just run.
> Revert "Merge branch 'dont-require-start-time'"

- paasta_tools/marathon_serviceinit.py
- tests/test_marathon_serviceinit.py
Sample output
```
>>> from paasta_tools.marathon_serviceinit import perform_command
>>> perform_command('status', 'paasta_canary', 'mesosstage_main', 'mesosstage', 1, '/nail/etc/services')
State:      Running - Desired state: Started
Marathon:   Healthy - up with (5/5) instances. Status: Running.
Marathon app ID: /paasta--canary.mesosstage--main.gitc19f9731.configdbd127ab
App created: 2016-04-05 12:42:35.199000 (5 days ago)
Tasks:
Mesos Task ID                         Host deployed to           Deployed at what localtime         Health checks
a57cc3df-0011-11e6-b964-0242a1bf1f9a  mesos2-uswest1cdevc:31194  2016-04-11T11:17 (16 minutes ago)  PASSING
7bf354da-0010-11e6-a226-0242e21a17e4  mesos1-uswest1cdevc:31583  2016-04-11T11:09 (24 minutes ago)  PASSING …
```
> added healthcheck output to marathon status

- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
- tests/test_check_chronos_jobs.py
- tests/test_chronos_tools.py
closes #421 
The issue was a bit more of an edge case than I realised - it occurred to me that this wasn't consistent, and we weren't always being told about > 1 job existing when we had Chronos rerun jobs around.
What I found was:
- we filter **enabled** jobs when looking for chronos jobs belonging to a service_instance in ``check_chronos_jobs``
- when running ``chronos_rerun`` we launch a job with ``disabled: False``. If ``disabled: True``, then Chronos refuses to run the job at all. Instead, we control the 'run once' functionality using the repeat value in the schedule field (``R1/start-time/interval``)
- Chronos **disables** the job once the job has been run, and adjusts the schedule to have ``R0``
- As a result, the extra job only triggers the issue of > 1 job showing up for a …
> ignore temporary jobs when checking chronos jobs

- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/rerun.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_rerun.py
- tests/cli/test_utils.py
- tests/test_chronos_tools.py
Closes #323.
A `paasta rerun` command allows Users to re-run Chronos jobs.
> create a frontend paasta rerun command

- paasta_tools/marathon_tools.py
I fixed this a while ago but it looks like it got re-included in a merge. Specifying `portMappings` with `--net=host` causes launching the docker container to fail.
The TF2 server will not go to space today ):
> removed portMapping from non-bridge nets

- paasta_tools/chronos_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_utils.py
the value of the arg for ``--memory-swap`` is required to be >= the
``mem`` param passed to docker - it also doesn't accept float values,
so we round whatever value is set in the mem field up to the closest MB. 
The only reason we haven't been bitten by this is because none of our 
soa-configs specify a float value for mem, but having tested it, it definitely causes apps 
to fail.
> always round --memory-swap param up to closest mb

- paasta_tools/cli/cmds/check.py
it's also valid to have "export DOCKER_TAG ?= ...", etc.
Fixes #439
> Make DOCKER_TAG check less strict

- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
There are 3 `execute_*_on_remote_master` functions:
- `execute_paasta_serviceinit_on_remote_master` →  `output`
- `execute_paasta_metastatus_on_remote_master` → `output`
- `execute_chronos_rerun_on_remote_master` →  `(rc, output)`
Only the latter required fixing (making sure it always return a tuple).
> fix "paasta rerun" crashes (PAASTA-4152)

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
I'm not really so sure we have to alert/page all the peoples just because something hasn't been deployed yet. These lines have mostly caused a bunch of pages to people who don't need to be paged for this.
Pretty much nobody cares when they are setting up a new service, so I think it would be better if we just "move along" as if it wasn't a big deal and exit 0.
> Don't alert teams if a service hasn't been deployed yet

- paasta_tools/cli/cmds/metastatus.py
```
matts@dev2-devc:~$ paasta metastatus -c norcal-prod -vvv
File "/usr/bin/paasta", line 120, in <module>
main()
File "/usr/bin/paasta", line 116, in main
File "/usr/share/python/paasta-tools/lib/python2.7/site-packages/paasta_tools/cli/cmds/metastatus.py", line 104, in paasta_metastatus
print_cluster_status(cluster, args.verbose, soa_dir)
TypeError: print_cluster_status() takes at most 2 arguments (3 given)
```
> fixed error running paasta metastatus

- requirements.txt
- setup.py
- yelp_package/dockerfiles/itest/marathon/Dockerfile
Marathon 1.1.1 has been released. Let's upgrade to it.
This will fail in Travis until @solarkennedy's [PR](https://github.com/thefactory/marathon-python/pull/92) is merged and a new version of marathon-python is released.
> Use marathon 1.1.1 in itest and upgrade marathon-python

- docs/source/autoscaling.rst
- paasta_tools/autoscaling_lib.py
- paasta_tools/marathon_tools.py
- tests/test_autoscaling_lib.py
Autoscaling now only considers CPU usage by default when autoscaling
> made the default metrics provider mesos_cpu

- paasta_tools/check_chronos_jobs.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/chronos_rerun.py
- paasta_tools/chronos_tools.py
- paasta_tools/cleanup_chronos_jobs.py
- paasta_tools/cleanup_marathon_jobs.py
- paasta_tools/cli/cmds/check.py
- paasta_tools/cli/cmds/emergency_scale.py
- paasta_tools/cli/cmds/emergency_stop.py
- paasta_tools/cli/cmds/fsm.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/cli/utils.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/generate_services_file.py
- paasta_tools/graceful_app_drain.py
- paasta_tools/list_chronos_jobs.py
- paasta_tools/list_marathon_service_instances.py
- paasta_tools/marathon_tools.py
- paasta_tools/monitoring_tools.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/setup_chronos_job.py
- paasta_tools/setup_marathon_job.py
Also made `chronos_tools.DEFAULT_SOA_DIR` and `marathon_tools.DEFAULT_SOA_DIR` reference `utils.DEFAULT_SOA_DIR`
This makes it easier to have a configurable DEFAULT_SOA_DIR for different environments.
> removed service_configuration_lib.DEFAULT_SOA_DIR

- paasta_tools/cli/cmds/cook_image.py
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
closes internal ticket PAASTA-4142 - paasta local-run doesn't interpolate tron-style datestrings when running chronos jobs.
> interpolate datestrings when using local-run with a chronos job

- docs/source/index.rst
- docs/source/isolation.rst
- docs/source/yelpsoa_configs.rst
I've seen a number of times where users have been surprised by what the 'mem' and 'cpu' values actually mean. This should provide a clearer idea for people who are interested in understanding the details of both how task allocation works, and how the mem + cpu values are used in cgroups.
> add a first pass at some docs explaining isolation.

- CHANGELOG.md
- README.md
- comparison.md
- paasta_tools/cli/cmds/cook_image.py
- paasta_tools/cli/cmds/itest.py
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/paasta_tabcomplete.sh
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/cli/utils.py
- yelp_package/CHANGELOG.md
- yelp_package/bintray.json.in
Read the Docs just sent out an email informing users that they are moving project subdomains from readthedocs.org to readthedocs.io. They will automatically forward users from the old domain to the new one, but they are encouraging projects to update any links they might have.
> Switch from readthedocs.org->readthedocs.io

- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/bounce_lib.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/monitoring/check_classic_service_replication.py
- paasta_tools/monitoring/check_synapse_replication.py
- paasta_tools/monitoring/replication_utils.py
- paasta_tools/setup_marathon_job.py
- paasta_tools/smartstack_tools.py
- paasta_tools/utils.py
- tests/monitoring/test_check_classic_service_replication.py
- tests/monitoring/test_check_synapse_replication.py
- tests/monitoring/test_replication_utils.py
- tests/test_bounce_lib.py
- tests/test_check_marathon_services_replication.py
- tests/test_marathon_serviceinit.py
- tests/test_mesos_tools.py
- tests/test_setup_marathon_job.py
Like it says. Stop hard-coding synapse port, and make it configurable through the system paasta config. It defaults to the current value, so ideally even without updating our system paasta config, nothing should break.
> Make synapse port configurable via SystemPaastaConfig

- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/paasta_serviceinit.py
This patch enables paasta_serviceinit status to process multiple instance in one ssh session. For each instance, "instance:instance_name" is added to the output so that the client can parse accordingly.
The options added are --service and --instances.
$ sudo .tox/py27/bin/paasta_serviceinit.py -s robj-test-service -i main,memo-test status
The argument service_instance is now optional to keep backward compatibility. It will be replaced eventually when the client code is updated. At that time, service and instances will become mandatory arguments.
(py27)$ .tox/py27/bin/paasta_serviceinit.py
usage: paasta_serviceinit.py [-h] [-v] [-D] [-d SOA_DIR] [-s SERVICE]
[-i INSTANCES] [-a APP_ID] [--delta DELTA]
[service_instance]
{start,stop,restart,status,scale}
The patch is manually tested with …
> PAASTA-4182 enable paasta_serviceinit status with multiple service instances

- paasta_tools/cli/cmds/emergency_restart.py
- paasta_tools/cli/cmds/emergency_scale.py
- paasta_tools/cli/cmds/emergency_stop.py
- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/cmds/rerun.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_metastatus.py
- tests/cli/test_cmds_rerun.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
- tests/test_utils.py
This makes it so you don't have to use the fake ".yelp" TLD for discovering where paasta masters are.
> Make the FQDN format configurable; previously hard-coded as paasta-%s.yelp

- paasta_tools/check_chronos_jobs.py
- paasta_tools/check_marathon_services_replication.py
- tests/test_check_chronos_jobs.py
- tests/test_check_marathon_services_replication.py
This adds a bit more whitespace to the chronos checks to be kinda markdown-style.
Also adds lots more action items in the marathon checks, and tests!
> Greatly improve the output of check_marathon_services replication

- paasta_itests/setup_marathon_job.feature
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/marathon_tools.py
- tests/test_autoscaling_lib.py
cc @mjksmith @heathvini
Defaulting to max_instances is probably a safer setting than min for production services with no data at all in zk. This is also true if we have a catastrophic failure of zk.
Originally I thought I might need to edit the PID logic, but I think this achieves the desired effect?
> Default to using the max instance count when autoscaling without decision data

- paasta_tools/mesos_tools.py
With this patch, mesos master state fetches are consistently under a small fraction of a second except for the 1st fetch. requests_cache code is not touched because requests_cache alone produced fetch latencies above one second.
> PAASTA-4412 monkey patch MesosMaster.state to increase caching TTL

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_local_run.py
This will allow users to check the docker command paasta will run for local-run without actually doing a build, pull, or run.  The output is on stdout in json format.
> paasta local-run --dry-run

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling_lib.py
- paasta_tools/bounce_lib.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/check_mesos_resource_utilization.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- paasta_tools/cleanup_marathon_jobs.py
- paasta_tools/cli/cmds/logs.py
- paasta_tools/cli/utils.py
- paasta_tools/contrib/delete_old_marathon_deployments.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- paasta_tools/monitoring/check_classic_service_replication.py
- paasta_tools/monitoring_tools.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/setup_chronos_job.py
- paasta_tools/setup_marathon_job.py
- paasta_tools/utils.py
Fixes #490
primary: @Rob-Johnson 
This changes how we log to stdout/err. Notably this makes it so log level (DEBUG) is global to the thing, so *everything* will start outputting, like kazoo, marathon, etc. This is probably a good thing.
Also it corrects the logging in our library files to just use their own __name__ and not to do any basicConfig themselves.
> Be more consistent about how we log to stderr

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
there is no -i option to paasta logs
> fix the bad command shown in check_chronos_jobs output

- paasta_tools/cli/cmds/emergency_start.py
closes internal PAASTA-4430
/cc @drolando
> fix execute_paasta_serviceinit_call for emergency-start

- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- tests/test_chronos_serviceinit.py
closes #457 
I'm open to ideas for the wording here - originally I started with Temporary: False, but decided that didn't really indicate that this was a 'rerun' job
```
(py27)bash-4.1# ./paasta_tools/paasta_serviceinit.py status -s paasta_canary -i sensu_canary
Desired:    Scheduled
Job:     paasta_canary sensu_canary
Status:   Scheduled  Launched by rerun: False
Last:     OK (2016-05-05T04:50, 59 seconds ago)
Schedule: R/2016-05-05T12:00:00.000Z/PT10M (UTC) Epsilon: PT60S
Command:  sensu-scheduled-canary.sh
Mesos:    Not running
```
> Show temporary status chronos jobs

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling_lib.py
This is one of those things where I want to be sure of the "Why" when this thing calculates decisions.
This change makes it at the normal log level it answers the first why, and with -v it answers the second why, and -vv answers the deepest whys (you see boto xml responses and junk)
> Log lots more things when doing cluster autoscaling

- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
Our current approach to determine the mesos leader relies on following the redirects. mesos.cli uses zookeeper. Let's use that.
I will work on adding some itests to properly test this change (especially the scenarios where we are unable to connect to zookeeper for some reason).
Fixes #498
> Use mesos.cli for get_mesos_leader

- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/utils.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
Multiple instances of a service is passed to the endpoint with the -i option in a comma-separated list of instances. The result of each instance is streamed back the client and prefixed with spaces accordingly, 2 for the instance line and 4 for the rest.
> Make paasta status use the multi-instance endpoint

- docs/source/yelpsoa_configs.rst
- paasta_tools/chronos_tools.py
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
Primary: @Rob-Johnson 
This came out of some review feedback.
I guess the tests are passing kinda "artificially" because of inheritance. Should I move or duplicate some tests out of marathon_tools and into utils?
I'm also adding deploy_whitelist but not deploy_blacklist support, and documenting them.
Also updating the schema.
Closes #456
> Make marathon and chronos constraint logic a bit more consistent

- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/deploy_marathon_services
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
This patch enables setup_marathon_job.py handle a list of service.instance to take advantage of mesos master state caching.  
{code}
$ .tox/py27/bin/setup_marathon_job.py --help
usage: setup_marathon_job.py [-h] [-d SOA_DIR] [-v]
SERVICE.INSTANCE [SERVICE.INSTANCE ...]
Creates marathon jobs.
{code}
We have a 60 seconds caching TTL at this point, and we have 244 service instances on prod. I am breaking into 4 chunks, hoping each chunk can finish within 60s. In addition, I removed service list shuffling. IMO, deploying instances of the same service in the same chunk process has better locality.
{code}
list_marathon_service_instances  | xargs -n 64 -r -P 4 .tox/py27/bin/setup_marathon_job.py
{code}
> Make setup_marathon_job capable of handling a list of service.instance

- debian/paasta-tools.links
- setup.py
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/itest/ubuntu.sh
I would like to start a new trend where we prepend our "plumbing" scripts with `paasta_` to make it more obvious what the command is for and where it came from.
`autoscale_cluster` is kinda unadorned. Is it for scaling a kubernetes cluster? A mysql one? Who knows.
This is actually an easy migration because in the links file you can specify multiple symlinks and deprecate the old ones. I didn't do that with this PR, but I will in the next one if shipit.
> Make paasta_autoscale_cluster and use console_scripts for it

- paasta_tools/chronos_serviceinit.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_serviceinit.py
Current http request cache is installed at either marathon or chronos serviceinit per service.instance. Move it up at paasta serviceinit to serve all service instances.
> Move http request cache install up to paasta serviceinit

- paasta_tools/contrib/graceful_container_drain.py
primary @giuliano108 
this just skips the non-paasta containers, rather than bailing out
> just pass on non-paasta rather than skipping in graceful_container_drain.py

- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
The commit https://github.com/Yelp/paasta/commit/71280ede5558a75dba28b6cdbc572495294e5045#diff-7d4e89c64360b719f36a1ca16d58607cL505 changed the ordering of the args passed to paasta serviceinit. Internally, some of the sudoers rules we have in place broke because they relied on this ordering. This reverts that change, moving back to the previous layout.
This change also changes the way in which the serviceinit command is created so that whitespace arrangement is sorted in one place.
@giuliano108 primary - this fixes internal ticket PAASTA-4457
> make the command the last arg to serviceinit

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/check_mesos_resource_utilization.py
- paasta_tools/cleanup_marathon_jobs.py
- paasta_tools/deploy_chronos_jobs
- paasta_tools/deploy_marathon_services
This will move the complexity of our adhoc leader-locking to the caller (cron job).
It has a nice side effect of not requiring an operator to run these scripts on the current leader.
> Dont try to do mesos leader detection in any script

- debian/control
Fixes #477 
The dh-virtualenv docs recommend ${Python:Depends}, but this is not going to work out great for all ubuntu's, so I chose to hard-code it instead.
> Hardcode a python2.7 dep to be compatible with all ubuntu

- paasta_itests/environment.py
- paasta_tools/deploy_marathon_services
- paasta_tools/setup_marathon_job.py
This patch restores the fast bouncing by handling multiple instances in setup_marathon_job. requests_cache is installed to keep http requests during the execution of setup_marathon_job.
> install requests_cache for setup_marathon_job, restore fast bouncing

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
There isn't really a ticket associated with this - it's just some cleanup ahead of the work I'm doing for internal PAASTA-4188
- Changes the tuples we were previously using to a real named tuple 'HealthCheckResult' so that there are less magic array indexes dotted around the code
- Move the logic for formatting the output from 'unhealthy' health checks to a single formatting function
- Normalise the capitalisation of some of the output that's printed.
> Use named tuples in paasta metastatus

- paasta_tools/paasta_maintenance.py
get_mesos_leader only returns the hostname. We need an actual URL for paasta_maintenance.
It looks like this got dropped during one of the refactors. Without this change, paasta_maintenance throws an error.
> Specify schema/port in paasta_maintenance

- paasta_tools/check_chronos_jobs.py
When `check_chronos_jobs` runs and iterates over all the jobs, it has logic to understand to not alert on disabled jobs.
However we filter out those disabled jobs in the first place, which means we get a kind of bogus alert:
foo isn't in chronos at all, which means it may not be deployed yet
But it is in chronos, it is just disabled. This code makes it so check_chronos_jobs includes disabled jobs, so they can hit the "it is ok, it is disabled" logic later on.
> Enabling checking of disabled chronos jobs

- paasta_tools/paasta_serviceinit.py
- paasta_tools/setup_marathon_job.py
An exception happened on one of the lucy instances and "paasta status" terminated.
Patch was tested simply with ".tox/py27/bin/paasta_serviceinit.py status -s robj-test-service -i main,autoscale_to_heck,memo-test". The "permission denied" exception occurs three times instead of once without the patch.
> continue serviceinit when an exception occurs on one service.instance

- docs/source/index.rst
- docs/source/installation/getting_started.rst
- docs/source/system_configs.rst
In this branch I've documented most currently-existing SystemPaastaConfig options. (I didn't include `cluster_autoscaling_resources` because I'm not sure what to say about that.)
I've also spruced up the getting started docs.
These are changes that I think would be useful for anybody setting up a Paasta cluster for the first time, guided by my recent experience setting up a cluster for Eat24.
> Document the system paasta config options

- paasta_tools/setup_marathon_job.py
Marathon client uses requests to list_apps. It should be get cached. Otherwise, create_marathon_app will timeout since it cannot confirm the new app has been created.
> disabling requests_cache when creating/deleting a marathon app

- paasta_itests/docker-compose.yml
- tox.ini
This change makes it possible to tag paasta_itests with `@wip` and then run them with `tox -e paasta_itests -- --tags=wip`. Previously, we were not passing the `{posargs}` properly down the stack.
> Support passing posargs through to paasta_itests

- paasta_tools/contrib/kill_orphaned_docker_containers.py
(Pdb) p container["Names"][0]
u'/mesos-34e6f338-dfa2-48e2-a798-40b0b0d318d5-S14.1ef2bcd1-0f65-41ae-b703-c2a1002d675c'
The leading slash needs to be removed.
> remove leading slash from docker container name

- paasta_tools/marathon_tools.py
Using this flag will resolve the HTTP 409 exception when killing marathon tasks. Detailed root cause analysis is in paasta-4156.
Unit test was to reboot robj-test-service.memo-test and run sudo .tox/py27/bin/setup_marathon_job.py robj-test-service.memo-test to make sure the change is exercised.
> Use the force=True flag to kill marathon tasks

- docs/source/conf.py
- docs/source/yelpsoa_configs.rst
- requirements-dev.txt
`sphinxcontrib-autorun` shows the command being executed along with its output in a syntax highlighted textarea. We really just want plain text. This is what `sphinxcontrib-programoutput` produces.
> Use sphinxcontrib-programoutput instead of sphinxcontrib-autorun

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
> Marathon expects docker parameters to be strings, not integers.

- paasta_tools/setup_marathon_job.py
This is an alternative for https://github.com/Yelp/service_configuration_lib/pull/11 in case there are concerns for fixing service_configuration_lib.
> disable service_configuration_lib yaml cache when setting up marathon jobs

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
if a slave has 0 available and 0 usage, then catch the ZeroDivisionError
and set usage to 0
> set utilization to 0 on zero division error

- paasta_tools/setup_marathon_job.py
- requirements.txt
- setup.py
With service-configuration-lib 0.10.1, the service_configuration_lib.disable_yaml_cache workaround is no longer needed.
> upgrade service-configuration-lib to 0.10.1

- paasta_itests/steps/setup_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/performance_check.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_cleanup_marathon_jobs.py
- tests/test_marathon_tools.py
- tests/test_paasta_metastatus.py
- tests/test_setup_marathon_job.py
chronos.json, marathon.json, performance-check.json
I suspect I may have missed something(s), but all the unit and integration tests pass.
This will have to be paired with config changes in puppet too.
I'm not sure if I need to change the changelog at all? Or if there's any documentation that needs to be updated?
Closes #515
> Get rid of "special" config files

- tox.ini
Fixes #503. Since we pass through arguments anyway, you can get full output with (stdout for a failing test is still displayed):
`tox -- -s`
> Reduce logging verbosity during tests

- paasta_itests/cleanup_marathon_job.feature
- paasta_itests/itest_utils.py
- paasta_itests/steps/cleanup_marathon_job_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/cleanup_marathon_jobs.py
- tests/test_cleanup_marathon_jobs.py
* Makes cleanup script more defensive. If it is going to delete more than half the marathon services it will now exit by default. It can be forced manually.
* Add integration tests for the cleanup script.
> Add kill threshold

- general_itests/steps/deployments_json_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
This adds support to the paasta cli for specifying multiple instances when starting or stopping. This should make it easier to bounce all the instances for a service in one go or to specify a specific set of instances.
> Paasta start/stop/restart multiple instances

- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- paasta_tools/paasta_serviceinit.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
2 parts to this fix, first, don't blindly assume a run_paasta_serviceinit command succeeds, actually check the return code to make sure. 
Secondly within paasta_serviceinit, we're catching Exception, unfortunately KeyboardInterrupt is derived from BaseException so the catch doesn't get triggered.
These messages are produced by the ssh command because we run with the `-t` flag. However, we don't really need informative messages out of ssh in the status command, so I've added the ability to ignore the output of ssh itself when executing paasta serviceinit remotely.
This allows critical commands like emergency scale, stop etc to still have output but allows for selective suppression.
> Make paasta_serviceinit exit more suitably when a command fails.

- .gitignore
- general_itests/fake_soa_configs_local_run/fake_simple_service/chronos-test-cluster.yaml
- general_itests/local_run.feature
- general_itests/steps/local_run_steps.py
- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
The command the container is supposed to run is being passed to
pipes.quote() once in get_docker_run_cmd() and once again in
run_docker_container().
If the string contains anything that pipes.quote thinks should be
quoted then we end up with some very weird results. For example
_"echo 'Hello' && sleep 60_" turns to "_echo foo '"'"'&&'"'"' sleep 60_".
The fix is to pass the whole command through pipes.quote() only once.
Fixes #555
> Fix command quoting issues

- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/utils.py
- tests/cli/test_cmds_metastatus.py
Instead of throwing an exception we catch the KeyError raised when
dashboard_links has not been defined, or there is no cluster with the
name requested, and print the relevant error message.
Fixes #530
> Handle missing dashboard_links gracefully

- paasta_itests/docker-compose.yml
- paasta_itests/itest_utils.py
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/marathon_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- yelp_package/dockerfiles/itest/mesos/Dockerfile
TL;DR: this tells the mesosslave to use docker to run itests, and bind mounts /var/run/docker.sock and /usr/bin/docker into the mesosslave(s) to use the host's docker.
It also updates a bunch of tests to actually work in docker
Closes #373
Should be followed up by something to deal with #576
> Use docker containerizer to run itests.

- paasta_tools/chronos_serviceinit.py
- tests/test_chronos_serviceinit.py
Adds chronos task status to the output of paasta status.
> Add chronos status to paasta status output

- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/marathon_schema.json
- tests/cli/test_cmds_validate.py
Correct mistake in docs. We no longer default to /bin/true:
97091a889f1315318533bfd1033b96e95d66674e
> Correct healthcheck_cmd docs

- paasta_tools/autoscaling_lib.py
- paasta_tools/bounce_lib.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- tests/test_autoscaling_lib.py
- tests/test_marathon_tools.py
This fixes #472. Previously we were only checking for a health check
result and not the actual content of the results (as the documentation
already states). Now we check that the a task is healthy before we
consider it for autoscaling.
> Make autoscaling wait for tasks to be healthy

- paasta_tools/cli/cli.py
- paasta_tools/cli/cmds/logs.py
Don't stop execution of the paasta logs command if we encounter an empty stream
> Fix logging for cli comamnds by having a basicConfig by default. 

- docs/source/autoscaling.rst
- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
This changes the logic in the service autoscaling lib to autoscale
services that don't have any healthcheck defined. If a service does have
a healthcheck defined the logic should be unchanged, i.e. we wait for
the healthcheck to pass before we autoscale.
> Tolerate autoscaling for tasks with no healthcheck

- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
I guess for whatever reason ``-v -v -v`` doesn't work anymore, and you have to have ``-vvv`` instead in metastatus. Probably happened in the recent rewrite.
> PAASTA-4980 fix regression in -v option for metastatus

- .travis.yml
- paasta_itests/bounces.feature
- paasta_itests/docker-compose.yml
- paasta_itests/itest_utils.py
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Fixes #576.
I also found that some of the tests were calling `/bin/sleep infinity` inside a container, which makes the metastatus tests a race condition -- sometimes the container dies and the resource allocation gets cleaned up before metastatus is run.
This change also paves the way for me to refactor setup_service/deploy_service/do_bounce.
> Make itests use "real" configs by having them call setup_service instead of deploy_service

- paasta_tools/autoscaling_lib.py
The provider was getting a namedtuple from metastatus but treating it
like a dictionary and causing a TypeError. I guess metastatus changed at
some point introducing this bug.
I know this should have tests etc. but I'd rather add those on my other branch where I'm refactoring this code quite a bit.
> Fix autoscaler metrics provider

- paasta_tools/cli/cmds/logs.py
- paasta_tools/utils.py
- requirements.txt
- setup.py
- tests/cli/test_cmds_logs.py
1. Warn when trying to grab logs from shared streams like chronos and marathon
2. Fix deploy component not going to devc to get logs
3. Use ujson for much faster processing of logs
Internal tickets: PAASTA-5033, PAASTA-5038
> Various logging improvements:

- paasta_tools/cli/cmds/logs.py
Pass an argument to time.sleep that works on more systems
> Log `paasta logs` errors to stderr, fixes #604. 

- docs/source/system_configs.rst
- paasta_tools/utils.py
- tests/test_utils.py
This ensures we perform a deep merge of each config file rather
than just a dict update. The motivation is for cluster autocaler
config files which are generated by terraform and currently only
the last one is active.
Here's an example where we want to have one file for each SFR but merge together in `cluster_autoscaling_resources`:
```
{
"cluster_autoscaling_resources": {
"aws_spot_fleet_request.${cluster_name}-slaves": {
"type": "aws_spot_fleet_request",
"id": "${sfr_id}",
"pool": "${pool}",
"min_instances": ${min_instances},
"max_instances": ${max_instances}
}
}
}
```
> Deep merge config files

- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
The task counts are no longer a dictionary. This fixes the resulting TypeError.
> Fix bug handling task counts in autoscaler

- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
When no deployments are in progress, the previous logic incorrectly believes that the task is running
> Fix delayed and suspended status when no deployments are in progress

- paasta_tools/cli/schemas/marathon_schema.json
Fixes `paasta validate` to allow http drain method
> Allow http drain method in configs

- paasta_tools/cli/cmds/local_run.py
- requirements.txt
- setup.py
This will also fix the socket timeout on kernel>=4.4 and python>=2.7 (fixed in 1.0.1 in ephemeral-port-reserve)
> Use packaged ephemeral-port-reserve

- debian/paasta-tools.links
- paasta_itests/paasta_api.feature
- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/__init__.py
- paasta_tools/api/api.py
- paasta_tools/api/settings.py
- paasta_tools/api/views/__init__.py
- paasta_tools/api/views/instance.py
- paasta_tools/api/views/service.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_serviceinit.py
- requirements.txt
- setup.py
- tests/api/test_instance.py
- tests/api/test_service.py
This is the first set of paasta api changes to enable further development. The functionality is not yet complete and several important pieces (itests, swagger etc.) are not in place. 
$ curl localhost:5054/v1/robj-test-service
{"instances": "robj_test,main,autoscale_to_heck,memo-test"}
$ curl localhost:5054/v1/robj-test-service/memo-test/status
{"instance": "memo-test", "State": "Running", "Desired state": "Started", "Git sha": "29f0937c", "service": "robj-test-service"}
> paasta api changes to enable deployment changes in puppet

- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
Make sure we check the state of the SFR as early as possible. Make sure
we check if it doesn't exist. Currently we don't check if it doesn't
exist and this can cause a boto ClientError later on.
> Check spotfleet status before we gather metrics

- yelp_package/dockerfiles/itest/chronos/Dockerfile
Adds our own release of chronos into the integration test suite.
Running `make itest` passes with this change in place.
> PAASTA-5190: Updating chronos to yelp release in itests

- paasta_tools/autoscaling_lib.py
@matthewbentley recently updated our instance weights for our SFRs. Turns out they don't have to be integers. And also there's an AWS limit on capacity so it makes sense to use smaller values!
Instance weights for SFRs don't have to be integers. This ensures that
we treat them as floats when deciding what to set as the target capacity
and how many hosts to kill.
> Ensure we treat instance weights as floats

- paasta_itests/docker-compose.yml
- paasta_itests/paasta_api.feature
- paasta_itests/paasta_metastatus.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/setup_marathon_job.feature
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/marathon_steps.py
- paasta_itests/steps/paasta_api_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/graceful_app_drain.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_maintenance.py
- paasta_tools/setup_marathon_job.py
- tests/test_paasta_maintenance.py
- tests/test_setup_marathon_job.py
- tox.ini
This is still a work in progress. But I decided to open up a PR to get a little more visibility.
This change attempts to make setup_marathon_job aware of hosts that are marked as draining (at-risk). If it notices that an application has tasks running on such hosts, it will scale up the application by that number.
I still need to add some paasta_itests for this change.
Connects to #376
> Make setup_marathon_job aware of hosts marked as draining

- paasta_tools/autoscaling_lib.py
AWS supports float values for instance weights in an SFR but only integers for target capacity, e.g. https://github.com/boto/botocore/blob/develop/botocore/data/ec2/2016-04-01/service-2.json#L15432
This reverts treating everything as a float and adds some rounding when we set target capacity.
> Revert float change

- paasta_itests/setup_marathon_job.feature
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/drain_lib.py
- paasta_tools/setup_marathon_job.py
- tests/test_drain_lib.py
- tests/test_setup_marathon_job.py
This should allow apps with working HTTP drain endpoints to at least successfully bounce. This doesn't account for all the possible errors that could happen but we aren't sure what the desired behavior should be in those cases so we'll wait until they happen.
> Add validation of HTTP drain method and fix bounce errors

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
This is what happens in real deploys, so this is what we should do.
> Change local-run to healthcheck via GET

- paasta_itests/docker-compose.yml
https://reviews.apache.org/r/45454/ breaks our itest/example cluster setup
This manifested in a weird way. In the itests and example cluster: slaves were dying when launched with docker errors saying that it couldn't remove a container because it was not found. The root cause was running containers from other slaves were seen as orphans by the new agents that were starting up. This leads to a race to delete in which one of the new agents succeeds but any others fail. Weirdly this worked fine on travis, presumably they do something funky with the docker socket?
> Fix itests orphaned containers bug.

- .travis.yml
Either we need to do this or remove the apt-get steps and go with the latest version that Travis installs.
> Fix travis docker-engine

- paasta_tools/chronos_serviceinit.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos_tools.py
- paasta_tools/utils.py
- tests/test_chronos_serviceinit.py
- tests/test_mesos_tools.py
There are times I just wanted more than 10 lines, but didn't want to run paasta logs.
This makes it so -vvvvvv will work.
Also lots of kwargs to make sure I got all the args right in the right order.
> Make paasta status print lines proprotional to how verbose they requested

- yelp_package/dockerfiles/itest/chronos/Dockerfile
Syslog takes a moment to startup. Occassionally chronos was beating it
and then crashing because it was unable to log.
> Fix itest rsyslog race

- paasta_tools/autoscaling_lib.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_maintenance.py
- tests/test_autoscaling_lib.py
- tests/test_mesos_tools.py
- tests/test_paasta_maintenance.py
This starts to tick off the items in #619 
* This makes the autoscaler check that a host has drained before it
terminates the instance.
* It also passes the hostname to the drain call, which is what the
maintenance library expects.
* Adjust the times we send to the maintenance library which expects
nanoseconds.
> Add support for maintenance mode to autoscaler

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling_lib.py
- paasta_tools/mesos_tools.py
- tests/test_autoscaling_lib.py
- tests/test_paasta_maintenance.py
@nhandler this adds the undrain action and fixes https://github.com/Yelp/paasta/issues/619
I've been testing this out in mesosstage. Happily, it seems to work well. The draining is very fast there because the autoscaler is deliberately picking the hosts with no tasks running! It'll be interesting to test it out in a more loaded cluster.
> Autoscaler maintenance cleanup windows

- paasta_itests/steps/setup_marathon_job_steps.py
I don't know what has changed in travis and jenkins environments.  Since we have a good itest passing rate on dev boxes and travis/jenkins do not always fail, the failure does not seem to be a requests_cache related bug. Let's try give the test more time (maximum 20x0.5=10 to 30x1=30).
> increase wait time to alleviate itest run_until_number_tasks failures

- paasta_itests/environment.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/setup_marathon_job.py
This change restores commit 8eb42bbe37536bf744a72bec0cf3be4ad8a15111. requests_cache will get uninstalled where it is installed. It will avoid the risk of running setup_marathon_job.main() multiple times in itests.
> Move requests_cache uninstall out of itest scenario cleanup

- docs/source/about/smartstack_interaction.rst
- docs/source/deploy_groups.rst
- docs/source/yelpsoa_configs.rst
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/marathon_tools.py
- tests/cli/test_cmds_validate.py
- tests/test_marathon_tools.py
@EvanKrall I think that this hack is sufficient for PaaSTA to _support_ multiple namespaces being advertised from a single instance. I believe there is more cleanup to do in the drain and bounce code to fully get rid of ``nerve_ns``, but I'd like to take this iteratively since folks are blocking on  this.
What does this do:
* Adds a ``registration_namespaces`` option, maintaining backwards compatibility with ``nerve_ns``; also introduces the concept of registrations instead of tightly coupling to implementation details
* Refactors MarathonServiceConfig to provide ``get_registration_namespaces`` and powers ``get_nerve_ns`` off of that.
What is still to do in follow ups:
* Completely remove ``nerve_ns``
* Refactor the drain_lib, bounce_lib, and monitoring code to check more than just the …
> Backwards compatible way to support multiple nerve namespaces

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
> Log exceptions as single events, to be formatted on the tailing side. Fixes #669

- paasta_tools/mesos_tools.py
mesos.cli has a default 5 seconds caching. Extra caching is provided by requests_cache EXPLICITLY in both serviceinit and setup_marathon_job. Clients (serviceinit, setup_marathon_job) should have the capability to enable/disable caching based on their requirements. Thus, revert this IMPLICIT caching in mesos_tools.
> remove mesos master state.json monkey patch

- paasta_tools/paasta_maintenance.py
- tests/test_paasta_maintenance.py
The `is_host_drained` function currently does not work when run against a host not known to mesos. This is problematic, as it prevents us from utilizing this function in monitoring checks. Currently, we will see a traceback like the following:
```
File "/usr/bin/paasta_maintenance", line 594, in <module>
if paasta_maintenance():
File "/usr/bin/paasta_maintenance", line 580, in paasta_maintenance
return is_safe_to_kill(hostnames[0])
File "/usr/bin/paasta_maintenance", line 472, in is_safe_to_kill
return is_host_drained(hostname) or hostname in 
File "/usr/bin/paasta_maintenance", line 483, in is_host_drained
slave_task_count = task_counts[hostname].count
KeyError: 'some-hostname'
```
This change will cause `is_host_drained` to return `True` rather than a …
> Make paasta_maintenance is_host_drained work for hosts not in mesos

- paasta_tools/autoscaling_lib.py
- tests/test_autoscaling_lib.py
I broke up the large autoscale_sevices function and made it skip services that haven't been deployed yet. (instead of raising an exception early.)
> Autoscaler skip non deployed

- paasta_tools/autoscaling_lib.py
- paasta_tools/utils.py
- tests/test_autoscaling_lib.py
This moves the AWS region to be set per autoscaling resources. This
means we don't have to assume that the paasta master only governs one
AWS region.
This moves the drain timeout and target utilization to be per pool
configurable in the paasta system config. This supports moving slow
draining containers to their own pool.
> Move paasta autoscaler config

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
This reverts commit a5e97eb7b2a85c0ca4e2c5661cc308314b4e341b.
We're not going to be rolling forward with this until Mesos releases 1.0.1 to address some bugs in the 1.0 release. At the same time, we're trying to understand why we're having flakiness in our integration tests. By reverting to a previous known 'good' version where we haven't seen such flakiness, we take one factor out of what might be causing it, and also bring our integration tests back in line with the version of Mesos we're actively developing against.
> Revert "Upgrade mesos from 0.28.2 to 1.0.0 in itests"

- paasta_tools/cli/cmds/start_stop_restart.py
- tests/cli/test_cmds_start_stop_restart.py
rather than failing silently, exit early when the user specifies
an invalid cluster. An invalid cluster is one which the service
specified in the command is *not* deployed to, or, if the user
specifies an instance in the command, an invalid cluster is any
cluster which that service/instance is not deployed to.
> check validity of clusters in start/stop/restart

- docs/source/yelpsoa_configs.rst
- paasta_tools/utils.py
- tests/test_utils.py
Adds a new "ulimit" configuration option that allows to pass --ulimit arguments to Docker.
> allow to pass --ulimit arguments to docker

- docs/source/yelpsoa_configs.rst
- paasta_tools/utils.py
- tests/test_utils.py
Adds a new "cap-add" configuration option that allows to pass --cap-add arguments to Docker.
> allow to pass --cap-add arguments to docker

- paasta_tools/paasta_maintenance.py
- tests/test_paasta_maintenance.py
Moving print statements so they don't show up in logs which use this as a library.
@nhandler I've just moved the print statements that were showing up in the autoscaler log. Would you be happy if I took this further and moved all the printing into `paasta_maintenance()`?
> Move print statements in paasta_maintenance

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
This fixes #698 and reverts the test change. The test should not have been changed as it would have caught the regression.
> Fix local-run --dry-run

- docs/source/yelpsoa_configs.rst
- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_utils.py
This provides a unified environment variable for applications to look at regardless of how they're scheduled.
> Add PAASTA_DOCKER_IMAGE environment variable.

- paasta_tools/api/api.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/version.py
- paasta_tools/paasta_metastatus.py
I've wanted to find out the remote paasta version a few times so I've added it to metastatus here.
I've added a version endpoint in the API too for when we start using the API in our command line clients. @huadongliu can you check I haven't broken anything by moving the services endpoint?
> Add version to metastatus

- paasta_itests/paasta_api.feature
- paasta_itests/steps/paasta_api_steps.py
itests without the paasta-api tests are failing in our jenkins environment. So paasta-api itests should be unrelated to the failures.
> Add back paasta-api itests

- paasta_tools/cli/schemas/marathon_schema.json
I recently added two new options, but forgot to add them to the json schema for the marathon config.
> add ulimit and cap_add settings to json schema

- paasta_itests/setup_marathon_job.feature
Dare me?
The argument here is that these are providing relatively little value if we already have confidence that `get_instances()` works correctly, regardless of whether that value comes from ZK or from on disk.
We already have itests that setup_marathon_job can smoothly scale up and down in response to instance count.
> Removed zookeper scaling itests

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
this fixes #708 until I can fix this 'properly'. @solarkennedy I've run the itest locally and the output is correct again - please merge + release as we discussed? FYI, I couldn't just revert the previous commit because it included some other logic now required, including adding the ``get_mesos_state_summary_from_leader`` function. (me--)
> use the full state endpoint in metastatus again

- build-manpages.sh
- docs/source/isolation.rst
We have a lot of useful information in our generated documentation. Sometimes, it is useful to be able to reference it right from the terminal without needing to open up a browser. This change will allow you to type `man paasta-tools` to do so.
I also fixed a few warnings that were appearing because of ioslation.rst
I was also toying with the idea of generating PDF or single-page HTML docs, but I felt that might be overkill.
> Manpage Version of Generated Docs

- .coveragerc
- paasta_tools/chronos_tools.py
- paasta_tools/tron_command_context.py
- paasta_tools/tron_timeutils.py
- requirements.txt
- setup.py
bravado swagger client is preferred by paasta-api. bravado requires 'twisted >= 14.0.0'. However, paasta-tools currently uses tron which requires 'Twisted >=10.0.0, <=12.3'. This patch is to copy the minimum required files from tron to paasta-tools. 
I didn't pull corresponding unit tests because command_context_test.py requires other tron modules. timeutils_test.py is clean but I want to treat it the same as command_context_test.py.
> Removed external tron dependency

- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/client.py
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/api/test_client.py
- tests/cli/test_cmds_status.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
$ USE_API_ENDPOINT=true .tox/py27/bin/paasta status -s robj-test-service -i main
Pipeline: https://jenkins.yelpcorp.com/view/services-robj-test-service
cluster: mesosstage
instance: main
Git sha:    72ac8530 (desired)
State:      Bouncing (crossover) - Desired state: Started
Marathon:   Healthy - up with (2/2) instances. Status: Running
$ paasta status -s robj-test-service -i main
Pipeline: https://jenkins.yelpcorp.com/view/services-robj-test-service
cluster: mesosstage
instance: main
Git sha:    72ac8530 (desired)
State:      Bouncing (crossover) - Desired state: Started
Marathon:   Healthy - up with (2/2) instances. Status: Running
Mesos:      Healthy - (4/2) tasks in the TASK_RUNNING state.
Smartstack:
norcal-devc - Critical - in haproxy with (0/2, 0%) total backends UP in this …
> Added a paasta status option to use the api endpoint

- paasta_tools/cli/cmds/logs.py
Also print scribereader commands if using scribe
> Make paasta logs verbose by default

- paasta_tools/paasta_maintenance.py
- tests/test_paasta_maintenance.py
Move print statements out of function calls to prevent them showing up when these functions are imported elsewhere.
Follow up to #687
> Remove print statements

- paasta_tools/bounce_lib.py
- paasta_tools/marathon_tools.py
- paasta_tools/mesos_tools.py
- tests/test_bounce_lib.py
- tests/test_marathon_tools.py
- tests/test_mesos_tools.py
``mesos_tools.get_mesos_slaves_grouped_by_attribute`` previously called the ``/state`` endpoint to gather info about slaves. switch to using the ``/slaves`` endpoint instead, and refactor a little to move some filtering to the callers.
I think this could be a fairly big win, given that it was called in the bounce lib's ``get_happy_tasks`` function
> use the /slaves endpoint rather than /state where possible

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/mesos_tools.py
- tests/test_check_marathon_services_replication.py
- tests/test_marathon_serviceinit.py
we were mocking get_mesos_slaves_grouped_by_attribute in a lot of
places, so the api changes weren't noticed by the tests. this fixes
it's usage in more places
> fix brokeness from get_mesos_slaves_grouped_by_attribute

- paasta_tools/api/api.py
service_configuration_lib caches files by default. This is a quick fix to unblock mmb by disabling service_configuration_lib caching completely. In the long term, pyinotify should offer a better solution since we don't expect service configs to change frequently. Unit test:
1. run paasta-api;
2. curl service/instance/status;
3. change services/service/marathon-cluster.yaml, e.g. mem;
4. curl service/instance/status again and verify config sha is different.
> Disable service_configuration_lib caching of service configs in paasta-api

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
So I don't have to keep getting out a calculator, this adds a percentage
utilization for per-attribute groupings in paasta metastatus.
> Add percentages for attribute usage in metastatus

- paasta_tools/cleanup_marathon_jobs.py
- paasta_tools/setup_marathon_job.py
- tests/test_cleanup_marathon_jobs.py
- tests/test_setup_marathon_job.py
I gave this alert a good-ole college try, but it was just *way* too noisy.
There are just too many ways for bounce progress to slow down.
Also in the lucy case the bounce is pretty much *always* in progress anyway.
> Remove bounce_progress sensu ttl alert

- paasta_tools/cli/schemas/marathon_schema.json
We added support for these options a while ago (and list them in our docs), but we never updated the schema file to support them. As a result, `paasta validate` claims they are invalid fields.
> Add backoff_factor and max_launch_delay seconds to marathon schema

- yelp_package/dockerfiles/mesos-paasta/Dockerfile
These packages are now needed for the playground container
as per 7b2e4be4d84ac98a198c29474b52c8969b6aafd5
> Adding dependencies

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
Due to #730, in paasta metastatus -vvv, it is possible to get a DivizionByZero error if the host has all resources reserved, giving it a total of 0 resources.
> Fix potential paasta_metastatus DivizionByZero

- example_cluster/docker-compose.override.yml
- example_cluster/paasta/api.json
- yelp_package/dockerfiles/mesos-paasta/start.sh
This enables the new paasta-api server on the mesosmaster in the docker-compose playground. It also exposes it to localhost on 5054
> Add api to docker playground

- paasta_tools/autoscaling_lib.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_maintenance.py
- tests/test_autoscaling_lib.py
- tests/test_mesos_tools.py
- tests/test_paasta_maintenance.py
* Use state summary where possible in autoscaler
* Check which box is best to kill after each termination. This is useful because mesos will have changed the distribution of tasks when draining the first box it kills.
* Split out get_count_running_tasks_on_slave into mesos tools to keep paasta_maintenance cleaner.
> Autoscaler box decision

- paasta_tools/marathon_serviceinit.py
Well, I don't like this and neither should you. I would like a different opinion on what to do here.
This function returns mesos tasks, but it uses the mesos-cli `fltr` stuff which is just "x in task", so `main` matches `main_sfo`.
One way to stop this is to add a terminator at the end, which is what I did. We could put this at a different layer?
> Make marathon_serviceinit filter mesos tasks properly

- paasta_itests/setup_chronos_job.feature
- paasta_itests/steps/chronos_steps.py
- paasta_itests/steps/setup_chronos_job_steps.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- tests/test_chronos_serviceinit.py
- tests/test_chronos_tools.py
This function is kinda leftover from when we had multiple jobs per instance in chronos, where it was "ok" to see a bunch and discards all the duplicates and pick the most "recent" one.
This is now "wrong" in many cases and has lead to bugs where setup_chronos_job is picking the "first" one, which is a tmp job!
This change makes it so we don't even include disabled (tmp/rerun) jobs, and raises an exception if we ever are silently trying to discard duplicate jobs, which really should not happen anymore, right?
If I'm wrong, then at the very lease this thing should be called `get_jobs` and let the caller discard things I think? To me it is an exception if a caller asks to get the job for a service/instance and the code can't figure out which job is correct.
> Make get_job_for_service_instance only return one chronos job ever

- tests/test_autoscaling_lib.py
@EvanKrall, I finally got round to fixing #711 because I was nearly about to reimplement the same slow test somewhere else!
This test was pausing because despite mocking time.sleep the timeout
excception was not raising until the 1 second had elapsed. This commit
makes time.sleep fire the timeout exception instead.
> Fix test pausing for 1 sec

- paasta_tools/check_chronos_jobs.py
- paasta_tools/paasta_metastatus.py
- requirements.txt
- setup.py
closes internal PAASTA-6590
with the changes in [#24](https://github.com/asher/chronos-python/pull/24) we can now remove the checks for socket errors.
> upgrade chronos-python and remove catching socket exceptions

- paasta_itests/itest_utils.py
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/mesos_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/mesos/cfg.py
- paasta_tools/mesos/cluster.py
- paasta_tools/mesos/completion_helpers.py
- paasta_tools/mesos/exceptions.py
- paasta_tools/mesos/framework.py
- paasta_tools/mesos/log.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos/mesos_file.py
- paasta_tools/mesos/parallel.py
- paasta_tools/mesos/parser.py
- paasta_tools/mesos/slave.py
- paasta_tools/mesos/task.py
- paasta_tools/mesos/util.py
- paasta_tools/mesos/zookeeper.py
- paasta_tools/mesos_tools.py
- requirements.txt
- setup.py
- tests/test_mesos_tools.py
rather than forking, let's bring this into the paasta
project. This brings in everything that was needed for
the itests to pass - we'll save clearing out the bits we don't
need for the future.
Note that I've had to change [this](https://github.com/Yelp/paasta/compare/vendor-mesos-cli?expand=1#diff-b32f029cd959a6adcdcdb50bbdf326d2R43). I think I need to update the license at the top of the file to [make a note of what's changed?](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))
itests pass locally for me. I'll iterate from here to try and pick out the bits that we actually need (but follow up with separate PRs)
> import mesos_cli as a subpackage in paasta_tools

- paasta_tools/cli/cmds/mark_for_deployment.py
We need to pass the shortened service name i.e. without 'services-'
> Fix mark for deployment service name

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
When we mark a service for deploy we shouldn't wait for stopped instances because they shouldn't be running.
> Don't wait for stopped instances

- paasta_tools/mesos/master.py
this will mean that we retry the ZK connection if a node is down.
the ``max_tries`` number is 10 here - any ideas for a better magic number? 5 doesn't make too much sense, because it'll pick a random host in the cluster (so we can't guarantee that 5 retries == 5 unique hosts)
> update mesos master to retry zk connection PAASTA-5245

- paasta_itests/itest_utils.py
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/cleanup_marathon_job_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/mesos/cfg.py
- paasta_tools/mesos/cluster.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos/parallel.py
- paasta_tools/mesos/slave.py
- paasta_tools/mesos_tools.py
- paasta_tools/utils.py
- tests/test_mesos_tools.py
closes #484
previously we had hacks around the codebase to ensure
that environment variables were set before importing
mesos-cli because of it's load-at-import-time behaviour.
This removes that, and makes the configuration a parameter
to the constructor methods of those objects in mesos-cli
that use them.
to do this, I've added a new ``mesos_config`` config dict to the
system paasta config, wherein the operator can declare a 'path'
variable defining the path to the mesos-cli config. Right now,
I've added in a default to the current location, which points at
the previously hardcoded ``/nail/etc/mesos-cli.json``.
In future, it'd be nice if we didn't have such a file at all, and instead
created the config in this same ``mesos_config`` dict, but this is a
reasonable first step.
Finally, I've …
> remove import-time config loading in mesos-cli

- paasta_tools/autoscaling_lib.py
- paasta_tools/marathon_tools.py
- paasta_tools/mesos/cluster.py
- paasta_tools/mesos/exceptions.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos/zookeeper.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_metastatus.py
- tests/test_autoscaling_lib.py
- tests/test_marathon_tools.py
- tests/test_mesos_maintenance.py
- tests/test_mesos_tools.py
- tests/test_paasta_metastatus.py
more cleanup. This time, I've targeted the monkey patching we were doing in ``mesos_tools``. 
- I've removed the ``log.fatal`` calls from the mesos-cli modules, instead replacing them with the relevant exceptions (we were monkey patching log.fatal to get this behaviour before).
- Replaced the implementation of ``mesos.Master.slaves`` with the version we had in mesos-tools, wherein we exact match on the id, rather than partial matching
- removed the ``get_mesos_state_from_current_leader`` function in ``mesos_tools``. When you create a new ``mesos.Master`` object, it calculates the current leader in it's constructor and redirects all requests to that leader, so we don't need this extra level of checking.
- removed the ``get_mesos_state_summary_from_current_leader`` function from …
> cleanup patching of mesos modules in mesos_tools

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_maintenance.py
- paasta_tools/utils.py
- tests/test_paasta_maintenance.py
I would like to get this code out for early review.
No, there are not tests, it is mostly me experimenting with all the different smartstack replication-related stuff and putting them together in a "slave-centric" way.
I tried to reuse as many of the existing functions I could to extract the data I need.
> Add is_safe_to_drain logic to protect healthy instances

- paasta_tools/api/views/autoscaler.py
TIL `view_config` has to match the route you set up, it can't just have the same `route_name`.
> I **think** this will fix the pyramid autoscaling api

- tests/test_autoscale_all_services.py
- tests/test_autoscale_cluster.py
Kind of a noddy test but would have picked up some ImportErrors that I
introduced recently so better than 0 coverage.
@nhandler this covers your comment in https://github.com/Yelp/paasta/pull/763 itests are pretty difficult with the autoscaler(s) but this would have at least caught the ImportError.
> Test main methods in autoscaling scripts

- .pre-commit-config.yaml
- paasta_tools/contrib/mock_patch_checker.py
- requirements.txt
Example:
```
(general_itests)matts@some-hostname:~/paasta (master) $ pre-commit run --all-files
Trim Trailing Whitespace...........................................................................................................................................Passed
Fix End of Files...................................................................................................................................................Passed
autopep8 wrapper...................................................................................................................................................Passed
Check docstring is first...........................................................................................................................................Passed
Check …
```
> pre-commit hook that checks for mock.patch invocations without autospec

- paasta_tools/mesos/master.py
- paasta_tools/mesos/slave.py
- paasta_tools/paasta_metastatus.py
For two reasons:
- it makes the interface to functions in the api
inconsistent (property based vs function based)
- it *forces* caching on the user of the api.
> remove @CachedProperty decorator from master + slave state

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Splitting up the very large scale_aws_spot_fleet_request function in to
component parts. Not intending to change any logic here, just make the
code and tests easier to read.
> Refactor SFR cluster autoscaler

- paasta_tools/mesos/exceptions.py
- paasta_tools/mesos/master.py
@solarkennedy here is some more 'cleanup' - some of this was hinted at from pylint, and some just from observation.
- added in the missing ``MultipleTasksForIDError``
- removed some of the compatibility layer that attempted to parse the old format that mesos used to serialize the current leader to ZK
- fix a typo in the ``task`` function.
The remaining pylint things are:
```
(py27) robj@robj-yelp-mb:~/workspace/paasta_tools cleanup-pylint % pylint -E paasta_tools/mesos/
No config file found, using default configuration
************* Module paasta_tools.mesos.cluster
E: 59,14: Module 'paasta_tools.mesos.exceptions' has no 'FileNotFoundForTask' member (no-member)
************* Module paasta_tools.mesos.master
E:161,43: Value 'self.state' is unsubscriptable (unsubscriptable-object) …
```
> more cleanup with hints from pylint

- paasta_tools/mesos/cluster.py
- requirements-dev.txt
- tox.ini
Without writing a bunch of tests for all the mesos_cli code, I want to catch errors like these. I'm not sure how they really slipped through the cracks this whole time?
Syntastic in my editor can tell this is a typo! I want travis to do the same, so I'm adding pylint.
The problem is... it is detecting a lot of errors. I'm starting off with just this one file and then we can expand?
I'm adding a failing test first so you can see the error and then a commit to make the tests pass.
> Fix FileNotFoundForTask exception error

- paasta_tools/api/api.py
- paasta_tools/api/development.ini
- setup.py
- yelp_package/dockerfiles/mesos-paasta/start.sh
This allows us to run the API in a development mode with sensible
logging and auto reloading on code changes.
This shouldn't change how things are working if you call the `paasta-api` script but should allow us to use `pserve`
@mjksmith this solves our internal ticket PAASTA-6599
> Configure the API for development mode

- paasta_itests/environment.py
- paasta_itests/setup_marathon_job.feature
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/paasta_maintenance.py
- paasta_tools/paasta_metastatus.py
- paasta_tools/setup_marathon_job.py
- tests/test_mesos_maintenance.py
- tests/test_paasta_metastatus.py
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/trusty/mesos-slave-secret
Due to the way we implemented maintenance mode's "draining", it is possible for tasks to get rescheduled onto the at-risk/draining host. To help avoid this and speed up the draining process, we decided to use dynamic reservations. Now, when a host is marked as 'draining', we will create a dynamic reservation for all free resources on the box (preventing anything new from being scheduled there). We will continue to dynamically reserve all free resources each time we kill a task running on the box. Eventually, all resources on the host will be dynamically reserved. The reservations will be removed once the box is undrained.
This change also updates `paasta_metastatus` so that dynamically reserved resources count as `used` resources. This should help us catch issues where we dynamically …
> Make setup_marathon_job dynamically reserve resources

- paasta_itests/paasta_serviceinit.feature
- paasta_tools/cli/cmds/emergency_restart.py
- paasta_tools/cli/cmds/emergency_start.py
- paasta_tools/cli/cmds/emergency_stop.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/paasta_serviceinit.py
- tests/test_marathon_serviceinit.py
IRL, the actual effect of these emergency commands is what normal users would call a "restart", because old tasks die and new tasks get launched by the bounce.
Therefore, that is what I've called the new command, as it "restarts" tasks ungracefully.
In practice, the implementation is to scale down the marathon app to 0 and let the bounce bring it back up.
> Make paasta emergency-restart simply kill inflight tasks

- paasta_tools/cli/cmds/mark_for_deployment.py
I think our codebase could use more ctrl-c help in many places to make it more friendly.
> Added KeyboardInterrupt handling for mark_for_deployment

- requirements.txt
- setup.py
- tox.ini
- yelp_package/dockerfiles/trusty/Dockerfile
Looks like we forgot to bump this version during the mesos upgrade.
> Use proper version of mesos in trusty dockerfile

- paasta_itests/environment.py
- paasta_tools/mesos/framework.py
- paasta_tools/mesos/master.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_metastatus.py
- tests/mesos/test_master.py
- tests/test_paasta_metastatus.py
closes #798 
- add healthcheck functions to metastatus for asserting the number of connected, disconnected, active, inactive frameworks
- update the ttl of the cached leader in MesosMaster to 5 seconds
- remove some duplication from metastatus
- update the MesosMaster.frameworks function to use the ``/master/frameworks`` endpoint, rather than ``state``
> Check connected frameworks

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
This cause a slow MTTR because of a typo.
Granted during rollback situation users should use `rollback`, but using `mark-for-deployment` is not "wrong".
ping @gstarnberger 
Internal ticket PAASTA-6673
> Added a warning when using mark-for-deployment on a non-in-use deploy group

- .travis.yml
- yelp_package/Makefile
- yelp_package/dockerfiles/xenial/Dockerfile
- yelp_package/dockerfiles/xenial/mesos-slave-secret
This change makes Travis start to build paasta-tools for xenial. It does *not* change the version of Ubuntu we use in things like `paasta_itests` (that remains `trusty` for now). It also doesn't touch the bintray upload settings (which are set to only upload when `make itest_trusty` is called on a tagged release). So overall, this should be a pretty simple and low-risk change.
> Start supporting xenial

- yelp_package/Makefile
- yelp_package/bintray.json.in
This change attempts to DRY up the Makefile a bit. In order to do so, I also enabled bintray uploads for lucid and xenial (in addition to the already enabled trusty). I don't think that should cause any problems.
> DRY up the Makefile

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
My dynamic reservation change broke our calculations of available resources in metastatus. I meant to treat a reserved resource as used, as if we reserve all the resources on a box, it has no free resources for tasks to run. But I put a `-` instead of a `+`.
> Fix metastatus

- paasta_tools/paasta_metastatus.py
- requirements.txt
- setup.py
- tests/test_paasta_metastatus.py
closes #806 
For now, this always returns OK, so won't ever trigger a page.
> add info about queuing chronos tasks to metastatus

- paasta_tools/cli/cmds/performance_check.py
- paasta_tools/utils.py
- tests/cli/test_cmds_performance_check.py
Performance-check used to take in 'commit' and 'image' parameters and passed those explicitly to a performance check service endpoint defined in paasta configs.
This change makes it so that the service endpoint and general params are defined in a performance-check.yaml file in soa-configs. If no performance-check.yaml file is found then this command exits immediately.
> Performance-check uses a config file

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
We were previously converting from MB to GB before adding dynamic
reservations (MBs). This change adds the dynamic reservations before
doing the unit converion.
> Fix metastatus health calculations

- example_cluster/docker-compose.override.yml
- paasta_tools/api/views/instance.py
- paasta_tools/cli/cmds/docker_exec.py
- paasta_tools/cli/cmds/docker_inspect.py
- paasta_tools/cli/cmds/docker_stop.py
- paasta_tools/cli/cmds/sysdig.py
- paasta_tools/cli/utils.py
- paasta_tools/mesos_tools.py
- tests/api/test_instance.py
- tests/cli/test_cmds_docker_exec.py
- tests/cli/test_cmds_docker_inspect.py
- tests/cli/test_cmds_docker_stop.py
- tests/cli/test_cmds_sysdig.py
- tests/cli/test_utils.py
- tests/test_mesos_tools.py
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/start-slave.sh
- yelp_package/dockerfiles/playground/Dockerfile
I've been playing with this on the sly since I had the idea at mesoscon but thought I'd post it up to see if anyone's interested.
It's a bit hacky, but the idea is: you run `paasta sysdig -s my-service -i main -c my-cluster` and you get jumped over SSH to a random host that's running the service and `csysdig` is launched with filters to show the mesos tasks running for that instance on that host. You can then jump into the containers or process etc.
If others like the idea I'll tidy it up and add some tests but I wanted to get some opinions before I spend the time.
Some issues:
* We have to ssh first to a box in the cluster to get the marathon credentials.
* The marathon credentials are embedded in the URL that then ends up in the command line (so anyone else on the paasta node running …
> PaaSTA docker_exec, docker_stop, sysdig, docker_inspect

- paasta_tools/mesos/master.py
- tests/mesos/test_master.py
After 3d07cbeacc4cfe0e9556500a1e51cbe4b49e5f4c we are getting the
frameworks from the proper endpoint. However, we aren't caching the
response as we were with the state endpoint. This means that anywhere
which calls the master.framework (which includes things like
task.framework) had to make a new HTTP call to /master/frameworks each
time.
This manifested in slow runs of the autoscaler where we happen to call
task.framework once per task in the cluster. See
get_mesos_task_count_by_slave in mesos_tools.
This adds the same caching as is used on the state.json endpoint.
> Add caching on frameworks endpoint in mesos-cli

- debian/paasta-tools.links
- paasta_tools/cleanup_maintenance.py
- paasta_tools/mesos_maintenance.py
- setup.py
- tests/test_mesos_maintenance.py
We've ended up with resources left reserved for maintenance on boxes that are marked as `up`. We have boxes marked as `draining` and `down` that are either non-existent or no longer preparing for a change that prevents them from being `up`.
This is a first pass at a cleanup script. It is designed to run in a cron job on the leader in each cluster.
Is this a bit extreme? Possibly. It relies on the assumption that the majority of our draining will be handled by tools with strictly enforced timeouts. In the event a human is manually performing maintenance, they will need to be very careful to set the maintenance window appropriately (but this is becoming more and more rare).
> Add cleanup_maintenance script

- paasta_tools/cli/cmds/performance_check.py
- tests/cli/test_cmds_performance_check.py
Added logic to strip "service-" from the beginning of the service param that's passed in to the performance-check command. I followed the same pattern used for the cook-image command.
> Strip "service-" from service parameter in performance_check

- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/chronos_serviceinit.py
- paasta_tools/marathon_serviceinit.py
It is a super common question when users say "why does it say running" when their service is "stopped".
> Change the words a bit on paasta status

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
Haven't seen this happen but mark-for-deployment could incorrectly say
an instance is deployed if there is an error returned from the paasta
api. This seems undesirable so this widens the exception handling to
make it assume the instance isn't deployed if the paasta api returns
errors.
> Make mark for deployment more resilient

- paasta_tools/mesos/cluster.py
- tests/mesos/test_cluster.py
closes PAASTA-6732
- fix the typo causing the original bug
- remove the globals in use
- remove the option to *not* make this throw an exception.
- add some tests to better understand its behaviour
> PAASTA-6732 fix exception in cluster.py when trying to throw FileNotFoundForTaskException

- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/api_docs/swagger.json
- paasta_tools/api/views/autoscaler.py
- paasta_tools/api/views/exception.py
- paasta_tools/api/views/instance.py
- tests/api/test_autoscaler.py
We want to make sure the service.instance exists and the desired_instance count is between min and max instance counts.
> $ curl -X POST -d '{"desired_instances":4}' http://paasta-mesosstage.yelp:5055/v1/services/robj-test-service/autoscale_to_heck2/autoscaler
> ERROR: Unable to load service config for robj-test-service.autoscale_to_heck2
> 
> $ curl -X POST -d '{"desired_instances":3}' http://paasta-mesosstage.yelp:5055/v1/services/robj-test-service/autoscale_to_heck/autoscaler
> {"status":"SUCCESS","desired_instances":3}
> 
> $ paasta status -s robj-test-service -i autoscale_to_heck
> cluster: mesosstage
> instance: autoscale_to_heck
> Git sha:    ba88d9ce (desired)
> State:      Running - Desired state: Started
> Marathon:   Healthy - up with (4/3) instances. Status: Deploying
> Mesos: …
> Validate paasta api update_autoscaler_count request

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/push_to_registry.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
- tests/cli/test_utils.py
I had hard time using this tool with y-m when I tried to feed it short urls. It wasn't failing fast, but with this it will.
> Added type validation on git commit cli inputs

- paasta_tools/autoscaling/autoscaling_service_lib.py
This speeds up the autoscaler in our largest cluster by 7x.
> added request caching for service autoscaler

- paasta_tools/cli/cmds/get_latest_deployment.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/cli/utils.py
- paasta_tools/generate_deployments_for_service.py
- tests/cli/test_cmds_rollback.py
- tests/cli/test_utils.py
- tests/test_generate_deployments_for_service.py
A number of things related to deploy groups / rollback / mark-for-deployment that I've addressed while working with the tools:
* Added tab completion wherever I could
* Made mark-for-deployment not require a git url like rollback
* Added a deploy_group column to rollback's suggestions (more to come on that front after this PR)
* `get_instance_config_for_service` => `get_instance_configs_for_service`
* Moved `get_instance_configs_for_service` to utils (can't move it to the big utils due to cross-imports)
* Tried to make the cli short-args more universal without breaking things
Let me know if this is too much and I can split up some things, but some of this has to be shipped together.
> Added tab-completion where we use deploy_groups

- .pre-commit-config.yaml
- paasta_itests/steps/paasta_api_steps.py
- paasta_tools/api/views/autoscaler.py
- paasta_tools/api/views/instance.py
- paasta_tools/bounce_lib.py
- paasta_tools/cli/fsm/autosuggest.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/monitoring/check_synapse_replication.py
- paasta_tools/paasta_serviceinit.py
This probably fixes #609
I also added a hook to prevent this from regressing
If you actually want to catch `SystemExit`, `KeyboardInterrupt`, `SystemError`, explicitly use `except BaseException:`
> Remove catchall excepts

- paasta_tools/contrib/delete_old_marathon_deployments.py
Per the advice in https://github.com/mesosphere/marathon/issues/4581
Additionally I've added an internal review to stop running this script, I bet we don't need it anymore.
> Don't use force when deleting a deployment

- general_itests/deployments_json.feature
- general_itests/steps/deployments_json_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_start_stop_restart.py
- tests/test_generate_deployments_for_service.py
- tests/test_marathon_tools.py
We're starting to run into problems from storing docker image by git branch instead of by deploy group (adhoc batches, paasta get_currently_deployed_sha).
As far as I remember we kept this in when we were switching to deploy groups because it allowed per-serviceinstance rollbacks and didn't involve changing `deployments.json` so it was easy to validate that deploy groups were working (just diff old and new `deployments.json` and expect no changes).
After this, a second change needs to be pushed that removes the v1 `deployments.json` and switches the rest of paasta over to v2.
> store docker image by deploy group

- paasta_tools/cli/cmds/mark_for_deployment.py
- requirements.txt
- setup.py
- tests/cli/test_cmds_mark_for_deployment.py
This adds a progress bar and *lots* more debug logging available with -v.
I dare say at yelp we should make -v the default in jenkins. It isn't like humans are looking at it all day, but when it *does* fail, we will want to see the debug logs I've added here. 
Here is what it looks like with verbose mode:
```
$ paasta mark-for-deployment --wait-for-deployment -c c19f9731c2665b4508d69f6263a8f502ad247489 -s paasta_canary -l everything -u git@git.yelpcorp.com:services/paasta_canary   -v
Marked c19f9731c2665b4508d69f6263a8f502ad247489 in for deployment in deploy group everything
Waiting for deployment of c19f9731c2665b4508d69f6263a8f502ad247489 for 'everything' complete...
0% ( 0 of 18) |                                                                                                        | …
```
> Made mark-for-deployment way more verbose and have a progress bar

- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
This reverts commit 6ad55802ff01e101151fecfd04746cc888dc8463.
Although I can't explain "why", this is the only change I've made recently related to marathon bouncing/killing/scaling. So I would like to revert it in an attempt to make marathon more stable.
> Revert "Try not scaling down before deleting marathon apps."

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/test_autoscale_cluster.py
I'll want to try this out in mesosstage before I do much more work on it. Feel free to have a look and give me some feedback but you may want to hold off giving a thorough review until I'm confident this works!
Major changes:
* Use FulfilledCapacity rather than current TargetCapacity as base for calculation of new TargetCapacity
* Set a property on each resource marking it as cancelled and process these resources first.
* If scaling a cancelled resource: only remove instances if the cluster is otherwise over provisioned or at target.
* Gradually scale down cancelled resources
> Add code to cleanup cancelled SFRs

- requirements.txt
- yelp_package/dockerfiles/itest/marathon/Dockerfile
This is a test to see if marathon 1.4.0-snap18 behaves better than 1.3.0.
The bintray debs were built by our internal package building infrastructure and then manually uploaded. If we decide to stick with this unreleased version of marathon, I'll get automatic uploads to bintray setup.
> Use marathon 1.4.0-snap18 in our itests

- paasta_tools/cli/cmds/check.py
- tests/cli/test_cmds_check.py
`paasta check` uses the `makefile_responds_to` function to check if the Makefile responds to a given target. However, the way that function works sometimes gives false negatives - the check fails sometimes when the Makefile actually does respond to a given target.
When a Makefile includes `$(MAKE) -C SOME_DIR $(MFLAGS)` and `SOME_DIR/Makefile` is a makefile, that line gets executed even when we specify the `-q` flag - see https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html#MAKE-Variable.
Here, the `-q` flag is passed into the inner MAKE invocation via `$(MFLAGS)`, which causes the inner invocation to exit with 0 or 1 if successful. If the inner MAKE exits with 1, the original MAKE gives an error.
In other words, with this pattern, `make test`  works fine, but `make -q …
> Update `makefile_responds_to` to handle common recursive Makefile pattern

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
This makes it safe to put configs in place for autoscaling groups before
we have the code to scale them.
> Skip unimplemented autoscaler resources

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Obviously I don't like this as a "solution" but I am interested to see
if it makes a difference in practice.
> Sleep to throttle AWS API calls to SFR API

- requirements-dev.txt
This module seems to have disappeared from pypi...
This installs it from github for now. To keep the build passing.
> Install sphinxcontrib-programoutput from github

- paasta_tools/cli/cli.py
I can't think of any reason not to do this at this layer.
If we do need to catch this in a more fine-grained way, we can still do that with an inner try/catch.
> Globally catch KeyboardInterrupt and exit 1 on cli commands

- requirements-dev.txt
github.com/lunaryorn/sphinxcontrib-programoutput no longer exists but I can install sphinxcontrib-programoutput from pypi.
Edit: crap. @solarkennedy says this won't work because only the wheel exists and dh-virtualenv doesn't install from wheels.
> Fix the build again

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Because we use non integer weights for spots and because we are
conservative when scaling down it is possible for the autoscaler to get
stuck when scaling down SFRs
This applies the same fix applied for cancelled SFRs where we force the
autoscaler to kill at least one instance when it is scaling down.
> Fix stuck downscaling of SFRs

- docs/source/about/smartstack_interaction.rst
- docs/source/deploy_groups.rst
- docs/source/yelpsoa_configs.rst
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/cli/schemas/marathon_schema.json
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- paasta_tools/paasta_maintenance.py
- tests/cli/test_cmds_validate.py
- tests/test_check_marathon_services_replication.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
- tests/test_paasta_maintenance.py
This PR adds support for multiple registrations from a single PaaSTA instance. Allowing things like exposing a single container under multiple smartstack advertisements.
> Multiple registrations

- general_itests/fake_soa_configs_local_run/fake_simple_service/adhoc-test-cluster.yaml
- general_itests/local_run.feature
- general_itests/steps/local_run_steps.py
- paasta_tools/adhoc_tools.py
- paasta_tools/chronos_rerun.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/rerun.py
- paasta_tools/cli/cmds/validate.py
- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/utils.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_chronos_job.py
- paasta_tools/utils.py
- requirements.txt
- setup.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_utils.py
- tests/test_adhoc_tools.py
- tests/test_chronos_tools.py
- tests/test_long_running_service_tools.py
- tests/test_marathon_tools.py
- tests/test_setup_chronos_job.py
- tests/test_utils.py
We need to hold off shipping this until we fix all of the Makefiles and jenkins jobs that don't specify `-i`.
> Revert "Revert "added support for adhoc jobs""

- paasta_tools/check_chronos_jobs.py
- tests/test_check_chronos_jobs.py
We should not send OK for when a chronos job is "fresh". They are "fresh" all the time because we update the job all the time.
Instead this state means we just shouldn't send an event, because we don't have any information. We shouldn't report it as failing (we don't know that yet) nor should we send a resolve (as it hasn't actually run properly yet)
So I think the right thing to do is simply skip and move on until we have data.
There are a lot of ways to do this though, let me know if you don't like this approach.
Internal ticket PAASTA-6658
> Make check_chronos_jobs ignore fresh jobs

- docs/source/yelpsoa_configs.rst
- paasta_tools/long_running_service_tools.py
Turns out we did need this! Relates to #745.
> Added back in healthcheck_port smartstack parameter

- paasta_tools/cli/cmds/emergency_restart.py
- paasta_tools/cli/cmds/emergency_start.py
- paasta_tools/cli/cmds/emergency_stop.py
- paasta_tools/cli/cmds/metastatus.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/cli/utils.py
- requirements-dev.txt
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_cmds_metastatus.py
- tests/cli/test_cmds_status.py
- tests/cli/test_utils.py
- tests/test_check_chronos_jobs.py
- tests/test_cleanup_chronos_jobs.py
Fixes #718 
Also upgraded `mock` to `2.0.0` to fix a bug with `side_effect` that caused some unexpected behaviour.
> Made paasta status and paasta metastatus return nonzero on ssh error

- paasta_tools/cli/cmds/get_latest_deployment.py
- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/deployment_utils.py
- tests/cli/test_cmds_get_latest_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/test_deployment_utils.py
Now that @mjksmith has v2 deployments out, extracting the existing deployed git sha is trivial.
After this ships it will be very easy to add auto-rollback.
> Added get_currently_deployed_sha and better rollback hints

- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
internal PAASTA-7052
To quote:
The docker containerizer silently rewrites your memory requirements to 32MB if you set memory to a number below that [code](https://github.com/apache/mesos/blob/ceee0c386d5126880733e1ede07f3522272cf75b/src/slave/containerizer/docker.cpp#L1694). When it does so, it doesn't update the memory-swap limit too (which we use to make sure that containers cannot swap). As a result, docker fails to launch your container with the following error:
```
Nov 14 09:02:30 myhost dockerd: time="2016-11-14T09:02:30.359740861-08:00" level=error msg="Handler for POST /v1.22/containers/create returned error: Minimum memoryswap limit should be larger than memory limit, see usage."
```
It's pretty non obvious why this happens, so lets just force this on users in paasta validate.
> add minimum 32MB memory requirement PAASTA-7052

- paasta_tools/adhoc_tools.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/utils.py
- tests/test_adhoc_tools.py
- tests/test_utils.py
Right now `local-run --build` prompts for a deploy group even though it doesn't need to know the git sha
> Local run build fix

- paasta_tools/cli/cmds/generate_pipeline.py
- tests/cli/test_cmds_generate_pipeline.py
Resolves #895.
Realistically we are not going to make fab_repo soa-dir aware any time soon, so I would rather we remove this misleading option.
If we do make all the yelp repo tools parameterized or we change to jenkins job builder or something, we can easily add this option back in.
> Removed the soa_dir option from generate-pipeline

- paasta_tools/chronos_serviceinit.py
unintentionally included in d484d15714f84d7fc1908902520ab8afa2eb376c
> remove include_temporary from chronos_serviceinit

- .dockerignore
- docs/source/installation/example_cluster.rst
- example_cluster/docker-compose.override.yml
- requirements-dev.txt
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/start.sh
- yelp_package/dockerfiles/playground/Dockerfile
- yelp_package/dockerfiles/playground/start.sh
This moves the installation of the python requirements into the docker
build. This speeds up the startup a bunch and also means that you can
make sure you have the correct requirements by running `docker-compose
build` to rebuild all the containers.
@Rob-Johnson as I mentioned this is possible because of being able to customise the context in docker-compose. Previously I couldn't think of a way to do it.
> Move requirements to build for example cluster

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
Sample error:
```
Warning! You're running a container in interactive mode.
This is *NOT* how Mesos runs containers.
To run the container exactly as Mesos does, omit the -I flag.
cannot enable tty mode on non tty input
make: *** [itest] Error 1
```
> fixed local run 'no tty message' not appearing with --build

- general_itests/steps/deployments_json_steps.py
- paasta_itests/steps/paasta_native_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/adhoc_tools.py
- paasta_tools/api/views/instance.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/info.py
- paasta_tools/cli/cmds/status.py
- paasta_tools/deployment_utils.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/marathon_tools.py
- paasta_tools/native_mesos_scheduler.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/utils.py
- tests/api/test_instance.py
- tests/cli/test_cmds_info.py
- tests/cli/test_cmds_status.py
- tests/test_adhoc_tools.py
- tests/test_chronos_tools.py
- tests/test_deployment_utils.py
- tests/test_generate_deployments_for_service.py
- tests/test_marathon_tools.py
- tests/test_utils.py
This removes the v1 deployments json and make all of `paasta_tools` use the new v2 format.
> Use v2 deployments

- paasta_itests/setup_chronos_job.feature
- paasta_tools/chronos_tools.py
- requirements.txt
- setup.py
- tests/test_chronos_tools.py
- yelp_package/dockerfiles/itest/chronos/Dockerfile
Updates validation of the ``schedule`` field to allow cron-style schedule strings. I've verified that the library being used, ``python-crontab``, has a specification for the cron-schedule strings consistent with that which the library used in Chronos does.
Taken from internal ticket PAASTA-7161:
> I've kind of done an adhoc integration test to see which cron schedules Chronos will be able to parse  from the current Tronfig. I took all the current tronfig cron schedules and parsed them with the same parser Chronos uses.
```
scala> val lines = fromFile("/tmp/test-crons").getLines
lines: Iterator[String] = non-empty iterator
scala> val parsed = lines.map(cron => Try(unixCronParser.parse(cron)))
parsed: Iterator[scala.util.Try[com.cronutils.model.Cron]] = non-empty iterator
scala> …
```
> Add cron support

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_mark_for_deployment.py
Also addresses #894 a bit by doing a normal print with some whitespace indentation instead of a verbose logline.
Also don't print rollback instructions twice, and especially not with auto-rollback.
> Cosmetic cleanups for wait_for_deployment

- paasta_tools/check_marathon_services_replication.py
- paasta_tools/setup_chronos_job.py
- tests/test_setup_chronos_job.py
This causes `setup_chronos_job` to not fail when a chronos service has not been deployed yet
> made send_event not load deployments

- paasta_tools/smartstack_tools.py
- tests/test_smartstack_tools.py
synapse commit dd5843c987740a5d5ce1c83b12b258b7253784a8 reordered the
parts in the backend name generated by synapse. The commit adds
backwards compatible support for the new new layout
primary @mjksmith
> fix parsing of backend names in haproxy

- tox.ini
I'm pretty sure someone told me that we needed all of these `basepython`s and other things for a reason, but reading the tox docs and the fact that the tests still pass (pending Travis' confirmation) seems to indicate that we're just making our toxfile needlessly confusing.
> [WIP] Removed duplication from tox.ini

- paasta_tools/chronos_tools.py
It was logging messages whenever it couldn't parse a cron, which happens
every time we run setup_chronos_job with on a job with an ISO8601 schedule.
Turn down the logging.
> make python-crontab less noisy

- requirements-dev.txt
closes #932 
the new version was throwing errors. this is the easy fix for now.
> pin docutils dependency to old version

- paasta_tools/chronos_tools.py
- paasta_tools/utils.py
- tests/test_chronos_tools.py
Given that we don't validate, you won't get any errors until deploy
time. This adds validation to the chronos cmd so we pick it up with
paasta validate
> PAASTA-7203 validate chronos cmds

- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/chronos_steps.py
- paasta_tools/chronos_serviceinit.py
before now, there was no way to interrupt in-flight tasks for a job
launched with 'paasta rerun'. This change includes the tasks launched by
paasta rerun in those killed by paasta emergency-stop
> PAASTA-7038 include rerun jobs in emergency-stop

- paasta_tools/contrib/check_registered_slaves_aws.py
This is deliberately a bit rough around the edges, it will be cleaner once I finish my other autoscaler branch. In the meantime I'd like to ship this out and set it up in sensu to see how noisy it will be.
--
This is a quick attempt to give us visibility of AWS resources that
don't end up registering in mesos.
This covers a lot of potential problems with the bootstrap process.
This could be better:
* maybe should check how long a resource has been hanging around for
* also check ASGs (I will update this when I merge my ASG branch)
> Check AWS instances register in mesos

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
How about this instead?
This is a new PR that obsoletes https://github.com/Yelp/paasta/pull/935
> support nerve namespaces in puppet service dir

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
We will need to do this upgrade before we can upgrade Marathon. Let's start testing it out.
> Upgrade mesos to 1.1.0

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
internal ticket: PAASTA-7205  
* wait-for-deployment should check status of all instances at least once even if timeout is small.
* wait-for_deployment should not re-check instances that are already deployed.
> wait-for-deployment improvements

- paasta_tools/cli/cmds/local_run.py
I'm sure we are going to have more errors like this.
But I wasn't able to create a failing test for this! I guess inside the test python the encoding is always "correct".
I'm up for other suggestions on how to approach this.
Internal ticket: PAASTA-7267
> Don't colorize the output of local-run

- paasta_tools/cli/cmds/local_run.py
- paasta_tools/utils.py
- tests/cli/test_cmds_local_run.py
I'm not really sure "when" it is right to "fail fast" and when it is right to just bubble up a return code.
But for this PR I'm bubbling up the return code more in the hopes that we get better exit codes.
Internal ticket PAASTA-7261
> Make local-run pass through return_codes for proper exititing

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
> Make local-run healthchecking more strict about error codes. Fixes #678

- yelp_package/dockerfiles/mesos-paasta/start.sh
- yelp_package/dockerfiles/playground/start.sh
After https://github.com/Yelp/paasta/pull/941 the paths changed so we
need to fix our symlink hack that simulates installing the deb in the
example cluster.
> Fix paths in example cluster

- paasta_tools/chronos_tools.py
- tests/test_chronos_tools.py
closes #957 
the isodate library returns different datatypes to the period parsing
function according to whether there is a yearly or monthly period
included in the string. Our checking was assuming that the type returned
was always a timedelta, and failing when it was not.
> issue 957 fix parsing of monthly/yearly periods

- general_itests/steps/local_run_steps.py
We are seeing `general_itests` fail due to local-run timing out (60s). This change tries bumping that timeout to 90s.
> Bump local-run timeout from 60s->90s for travis

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
SFRs only return one instance per reservation from the describe ec2
instances call. However ASGs do return several instances per
reservation. This makes it so we just build one list of instances which
is compatible for both.
Also suddenly today so do SFRs. I guess AWS changed something or we've just been "luckily" getting one instance per reservation in the past...
> Fix multiple instances per reservation

- paasta_tools/native_mesos_scheduler.py
- tests/test_native_mesos_scheduler.py
Just a little Friday afternoon work to make the Paasta native Mesos scheduler a bit more feature-complete.
> Make native mesos scheduler pass volumes, docker parameters, network mode, and choose a port.

- paasta_tools/paasta_metastatus.py
this was seen in PAASTA-7696 when Marathon couldn't elect a leader.
by catching it, metastatus will return 1 when marathon throws this
kind of error.
I've removed the printing of the error message, because they're often unhelpful, as in the case of this ticket where the error from the marathon client was actually a JSON decoding error caused by marathon returning plain HTML
> catch InternalServerError talking to Marathon

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
I think we can't mix kwargs and *args and pass in positional args and expect everything to work.
The test did fail and repro drolandos thing, real tdd :)
> Use kwargs consistently in autoscaling_lib

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/mesos_tools.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/test_mesos_tools.py
After the change in c266cf76d8e0e78b5f7889d61c9a4638f5fdd2d3 the
interaction with mesos_tools is incorrect. This corrects it so that we
pass the input mesos tools is expecting and then update the
PaastaAWSSlave object locally.
@Rob-Johnson can you sanity check this. I'd really like to do away with the weird dictionary that comes back from `get_mesos_task_count_by_slave`. But this feels like a slightly easier and safer change for now. This is just to merge it into my autoscaler-asg branch before I merge the lot to master and cut a release.
> Correct task count objects

- paasta_tools/cli/schemas/marathon_schema.json
- tests/cli/test_cmds_validate.py
This should validate the top level key in marathon-<cluster>.yaml which
becomes the marathon app ID. It compares it to an adapted regex that
marathon itself uses to validate the app ID.
https://github.com/Yelp/paasta/compare/validate-marathon-ids?expand=1#diff-0f83d210889c5e0c676f023e9b29c835R8 is the new line (lol structured data in a diff)
@solarkennedy this should do what you suggested
> Check marathon IDs are valid

- docs/source/bouncing.rst
- docs/source/conf.py
- docs/source/yelpsoa_configs.rst
- requirements-dev.txt
This module has caused us issues on a number of occasions. We are using it minimally, and nobody really seems to care about it. Let's just remove it and go back to static lists.
> Remove use of the sphinxcontrib-programoutput module in docs

- requirements.txt
- yelp_package/dockerfiles/trusty/Dockerfile
Think I've tracked this down to the fact that we have pinned six==1.9.0
and setuptools now needs a newer version.
Can't see any reason why it was pinned so let's see if the tests pass
with the new version.
> Fix the build

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
This change reduces wait-for-deployment running time (when git_sha is already deployed) from 4m50 to 1m12 for yelp-main prod.
It creates separate threads for each paasta cluster and up to 5 threads per cluster to query API.
> async version of wait-for-deployment

- .gitignore
- Makefile
- test.sh
I know this is kinda nuts but it does make the tests pass on a dev box.
I'm basically adding an intermediate venv which we install the latest
versions of pip + virtualenv. This way tox creates a virtualenv with
sufficiently new tools to work consistently.
> Add intermediate venv

- Makefile
- docs.sh
- itest.sh
As per 012b276696017760c3026d0c6e8c56e2719e607c this makes our tox
commands run in an intermediate virtual env. This is a workaround to the
requirements not installing in a venv without the latest version of pip
+ virtualenv etc.
> Spread the extra venv to other tests

- yelp_package/dockerfiles/lucid/Dockerfile
As per 95ed63dface91540b32e6801674bf5b1ffc78c0f
As mentioned in https://github.com/Yelp/paasta/pull/976 I thought we
might need to bump the lucid versions too...
> Latest pip + venv on lucid too

- docs/source/yelpsoa_configs.rst
deploy_whitelist example is incorrectly formatted.
> Fix quotes typo

- paasta_tools/autoscale_cluster.py
- paasta_tools/bounce_lib.py
- paasta_tools/check_marathon_services_replication.py
- paasta_tools/generate_deployments_for_service.py
- paasta_tools/monitoring/check_classic_service_replication.py
- paasta_tools/monitoring/check_synapse_replication.py
- paasta_tools/utils.py
- tests/cli/test_utils.py
- tests/monitoring/test_check_synapse_replication.py
- tests/test_adhoc_tools.py
- tests/test_autoscale_cluster.py
- tests/test_bounce_lib.py
- tests/test_check_marathon_services_replication.py
- tests/test_generate_deployments_for_service.py
- tests/test_utils.py
- tox.ini
This gets ~some of the tests passing in python3 and gives us a way to whitelist in file-by-file as files are converted to passing (while preventing them from regressing)
> Make more tests pass in python3

- paasta_tools/setup_marathon_job.py
This ocassionally fails which can stall the bounce. I guess there's a
race condition with other maintenance code in the autoscaler/cron jobs.
This should at least prevent the bounce from erroring out.
> Try except for reserve all in bounce

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
This call is unnecessary if we are terminating the box. When we
shutdown we run "down" and then "up" which clears the draining state on
the master. We also have cleanup scripts running. So we should only
undrain if we fail to terminate etc.
@nhandler should be primary on this
> Remove extra undrain call

- tox.ini
This makes it easier to hit rebuild if you see a transient failure
because one of the itest containers is slow/hanging.
> Docker compose down before we start the itests

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
We get these exceptions pretty frequently in our large clusters when we
are creating multiple apps at the same time. Currently the exception is
raised all the way up which causes setup_marathon_job to exit 1 and for
our deploy loop to start over. This catches the exception and continues
on. I think it should be safe because we will simply try again next time
to create the new marathon app.
> Handle create app lock failure gracefully

- paasta_tools/paasta_metastatus.py
- tests/test_paasta_metastatus.py
this will be reverted when
https://github.com/thefactory/marathon-python/pull/167 is merged, but
until then we need to catch this to fire off an alert when Marathon
can't agree on a leader
> catch ValueError when getting marathon status

- debian/paasta-tools.links
- paasta_tools/get_mesos_leader.py
- setup.py
We have an `am_i_mesos_leader` script, but we don't have any easy way to get the hostname of the current leader. This change adds a new `get_mesos_leader` script to do that.
CC @somic @EvanKrall
> Add a get_mesos_leader script

- paasta_tools/mesos_maintenance.py
- paasta_tools/paasta_maintenance.py
- tests/test_mesos_maintenance.py
We have received reports that `paasta_maintenance status` is hard to understand. This is because it spits out the raw json (you can pipe it to `jq` to make it pretty). This change makes `paasta_maintenance status` use a more human-friendly output format. The old output is available under a `paasta_maintenance cluster_status` command.
This is internal ticket PAASTA-6990
> Make paasta_maintenance status human-friendly

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
* Change to threshold of healthy tasks found in marathon rather than requiring match to number of instances we set
* Ensure we *always* scale up to min_instances when we're currently below regardless of what we find running
> Make service autoscaler lenient on running tasks

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Fixes #979
We currently constrain to a `MAX_CLUSTER_DELTA` when scaling up or down.
This prevents sudden large changes when the autoscaler has made a
mistake. However, an operator increasing `min_capacity` on a resource
should trump this situation. This commit makes it so that we never set a
new capacity that is lower than the current `min_capacity`.
> Ensure the cluster scaler jumps to min_capacity

- general_itests/steps/deployments_json_steps.py
- general_itests/steps/fsm_steps.py
- general_itests/steps/tail_paasta_logs.py
- paasta_itests/environment.py
- paasta_itests/itest_utils.py
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/mesos_maintenance.py
- paasta_tools/native_mesos_scheduler.py
- paasta_tools/setup_marathon_job.py
- paasta_tools/utils.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/cli/test_cmds_logs.py
- tests/test_marathon_serviceinit.py
- tests/test_marathon_tools.py
- tests/test_mesos_maintenance.py
- tests/test_mesos_tools.py
- tests/test_monitoring_tools.py
- tests/test_native_mesos_scheduler.py
- tests/test_paasta_execute_docker_command.py
- tests/test_setup_chronos_job.py
- tests/test_setup_marathon_job.py
- tox.ini
Most of this was just straightforward contextlib switching.
There's one concering change in tests/autoscaling/test_autoscaling_service_lib.py (from  paasta_tools/autoscaling/autoscaling_service_lib.py).  The math here (copied from wikipedia) was incorrectly doing integer division (the default of `/` in python2) -- I switched it to floating point division (py3 default) via `from __future__ import division`.
I split the tedious nested changes into the first commit and the interesting bits into the second commit.
The version test can't pass until we fix version conflicts (I've submitted a patch to mesos to allow protobuf>=3 in mesos.interface to resolve the only remaining conflict).
> All the unit tests pass in python 3!

- paasta_tools/remote_git.py
- tests/test_remote_git.py
> Fix remote_git for non-ascii tags

- paasta_tools/remote_git.py
- tests/test_remote_git.py
After we changed to decoding git refs to unicode strings we also need to
make sure to encode back to bytes before we send to dulwich. Otherwise
we see: refname is not a bytestring: u'refs/tags...'
I've also converted the shas back to bytes although I'm not sure we
really needed to...
I'm going to try and add some itests that will catch bugs like this in
the future. But I'll do that seperately. cc @asottile
> Send git refs as byte strings

- paasta_tools/cli/cmds/itest.py
- paasta_tools/cli/cmds/push_to_registry.py
There are still some use cases where we *don't* want to stream the output (where we capture it instead), but for itest and push I think it is ok to log and not stream. (as all logs go to stdout/err anyway).
Should I put a check to not allow a caller to stream and log at the same time to prevent someone from duplicating output again?
Fixes #1004
> Don't stream already logged loglines

- tox.ini
- yelp_package/dockerfiles/trusty/Dockerfile
- yelp_package/dockerfiles/xenial/Dockerfile
pyxx-none-any means "pure python, any platform".  These are actually cpython2.7 wheels for linux_x86_64 and are *not* compatible with python3 or other versions of cpython or pypy
> Give the mesos wheel names more-correct impl / plat

- paasta_itests/setup_marathon_job.feature
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
In 0c950d0e43434222b598d8b8fc7da8c1383a666e we moved the lock in
`setup_marathon_job` to prevent race conditions between multiple bounce
loops which run at the same time. One motivation was seeing HTTP 409
conflicts from marathon when the bounce attempts to create the same app
twice. It turns out that this is still possible since we
`get_all_marathon_apps` outside the lock which can lead to two bounces
deciding to create the same app, resulting in HTTP 409 from marathon.
We could move this call into the lock but this would incurr a
performance hit as it would be called once per service instance. Instead
I am catching the error which I am pretty sure is safe. Essentially a
second bounce may decide it needs to create an app that already exists
but this is now a silent failure and the bounce …
> Catch 409 conflict when bouncing marathon apps

- docs/source/yelpsoa_configs.rst
Refer to the CEP (y/CEP650) for more details. This directive already has the requisite interpreter in synapse-tools (https://github.com/Yelp/synapse-tools/pull/19).
> Adding PaaSTA docs for proxied_through

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
Marathon can return None for started_at if the task is brand new. In
this case the `is_old_task_missing_healthchecks` should return False
because the task can't be considered old. Currently it is throwing an
exception which is not helpful!
> Assume task with no started at is new

- .travis.yml
- example_cluster/example-cluster-test.sh
- example_cluster/example-services/hello-world/marathon-testcluster.yaml
- example_cluster/tests/check-api.sh
- example_cluster/tests/check-metastatus.sh
- example_cluster/tests/check-status.sh
- example_cluster/tests/start-new-service.sh
- tox.ini
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/playground/Dockerfile
Our itests are slightly limited. This aims to test a few cases that may
be missed by the itests. It is essentially a set of bash tests for
paasta that run basic paasta commands and expect a 0 error code.
For the first iteration we are:
* deploying a new service by running the same commands we run in Jenkins
pipelines
* running metastatus and status commands
* checking that the paasta api runs
* checking that the api shows that the hello world service is "Running"
> Add example cluster test suite

- paasta_tools/docker_wrapper.py
This didn't get caught during tests because the tests specify args themselves rather than sys.argv. 
% venv/bin/paasta_docker_wrapper --version
Docker version 1.11.2, build e2d06fe
> don't strip argv[0] twice in docker_wrapper

- paasta_tools/cli/cmds/wait_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
Do not fail wait-for-deployment when the git server is temporary unreachable.
internal ticket: PAASTA-8599
> Do not fail wait-for-deployment when the git server is unreachable

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/paasta_metastatus.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
This adds optional info on the cluster autoscaler to metastatus. It
works by using the autoscaling library to retrieve details on the
resources it is responsible for and contacting AWS to find the current
capacities of the resources. The motivation is so an operator can
easily see the settings relavent to the autoscaler and the current
capacity. Fixes #984
It is behind a command line flag so should be safe to ship as is. At
yelp this will need a wrapper script on the master that ensures the
autoscaling configs are synced from S3 and that there are AWS
credentials in the environment.
> Add optional autoscaling info to metastatus

- paasta_tools/check_chronos_jobs.py
- paasta_tools/chronos_tools.py
- requirements.txt
- tests/test_check_chronos_jobs.py
* take the job timezone into account when calculating interval for crontab-format schedules
* replace my custom UTC TZ class with pytz.utc.
* bump pytz 
I wasn't able to add a test for this case, because datetime objects can't be monkey-patched.
> Fix crontab interval

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
cc @bchess 
Do we support env vars with spaces in them?
Because when local run was passing `--env="MESOS_TASK_ID=foo"` to the wrapper it interpreted the var as `u'"MESOS_TASK_ID': foo"'}`
> Make local_run use the new docker wrapper

- paasta_tools/cli/cmds/mark_for_deployment.py
to prevent re-querying status of the same instances every 10 seconds.
> Increase internal query timeout in wait-for-deployment to 60 seconds

- paasta_tools/mesos/master.py
Just putting this up there as a potential easy thing that might
alleviate our performance issues in our biggest clusters.
Currently can take ~4s to get state.json so a 5s cache can't be helping
a lot. We could make this configurable if anyone feels strongly?
Otherwise I can't see it hurting that much.
cc @EvanKrall @solarkennedy not really a real fix but it is at least an easy one. I think we call `_frameworks` quite a bit because it seems to be used to get a list of tasks. i.e. `mesos.master.tasks`
> Cache expensive endpoints more

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
We're double quoting the custom command received via `paasta local-run -C`. This is probably fine if the command is a single word, but it fails if it's something slightly more complex like "make test" since bash will now consider the entire string as the command name.
I'm not sure if this is the best way to check the command inside the docker run args list, but afaik the custom command must always be at the end of the docker run, so this should be fine.
With `pipes.quote`, the test failed like:
```
def test_get_docker_run_cmd_quote_cmd():
memory = 555
random_port = 666
container_name = 'Docker' * 6 + 'Doc'
volumes = ['7_Brides_for_7_Brothers', '7-Up', '7-11']
env = {}
interactive = True
docker_hash = '8' * 40
command = ['make', 'test']
net = 'host'
docker_params = []
actual = …
```
> Properly quote custom paasta local-run command

- Makefile
- docs.sh
- test.sh
- yelp_package/dockerfiles/lucid/Dockerfile
- yelp_package/dockerfiles/mesos-paasta/Dockerfile
- yelp_package/dockerfiles/playground/Dockerfile
- yelp_package/dockerfiles/trusty/Dockerfile
Now make test is a little bit smarter. It doesn't systematically delete the .paasta virtualenv
Non primary runs of make test now takes 8 seconds on my laptop.
> Integrated test.sh in Makefile

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
@bukzor This should fix your issue. I tried running your itest command with this fixed and it worked.
The new test failed without the fixed since the code was generating a command like:
`[u'sh', u'-c', [u'sh', u'-c', u'make test']]`
> Fix paasta local-run to support array commands

- paasta_tools/check_chronos_jobs.py
- paasta_tools/monitoring_tools.py
- tests/test_check_chronos_jobs.py
- tests/test_monitoring_tools.py
internal ticket: PAASTA-7870
* If realert_every is defined in chronos-<cluster>.yaml for the job, that value will be used.
* If the job doesn't have 'realert_every' in chronos-<cluster>.yaml, the value will be guessed based on the job interval.
* If the job doesn't have interval and has no 'realert_every' in chronos-<cluster>.yaml, paasta will read it from monitoring.yaml or will use the default value -1.
I'm not sure whether the guessed value should be more preferable than the one from monitoring.yaml or not.
On the one hand silently overriding values set in monitoring.yaml doesn't look good to me.
On the other hand if we don't override monitoring.yaml, people will have to remove 'realert_after' from monitoring.yaml and put it to marathon-<cluster>.yaml for every instance to be able to …
> Make realert_every be a function of the interval

- tox.ini
MacOS doesn't have `/usr/bin/python3`, let's just use `python3` instead. The only reason we specify an interpreter executable with a full path is because we don't want to get into trouble if a virtual environment is already active. Since the one activated for Paasta in the Makefile is a Python 2 one we shouldn't run into issues.
> Don't specify path to Python 3 executable in tox.ini

- debian/rules
this causes pip to try downloading packages from non-reachable host with 4 retries.
> Don't use yelp's pypi if not available

- paasta_tools/chronos_serviceinit.py
- tests/test_chronos_serviceinit.py
rerunning tasks means that there can be >1 task for a job in flight.
closes #1013
> #1013 1 mesos tasks for a chronos job != CRITICAL

- paasta_tools/contrib/utilization_check.py
I wanted a script that gave me an easier entrypoint for finding
utilization data of arbitrary sets of hosts in the cluster than
metastatus can provide. This is pretty simple: reads a list of hosts
from stdin and prints a json dump of total, used, perc for the list
of inputs. I can put this behind the api next, but this'll do for now
@mattmb this is a first pass of what we spoke about in meat-space. lmk
what you think.
Here's it working
```
(paasta-tools) robj@paasta1-uswest1adevc:~/dev_paasta  % mco find -F "paasta_pool=default" -F "paasta_cluster=norcal-devc" | python paasta_tools/contrib/utilization_check.py
{"mem": {"perc": 47.72612940201327, "total": 2369484.0, "used": 1130863.0}, "disk": {"perc": 7.5974465585857285, "total": 9745906.0, "used": 740440.0}, "cpus": {"perc": …
```
> add contrib script for calculating utilization

- tox.ini
Reverts Yelp/paasta#1085
brew is not recommended way to install python apparently
> Revert "Don't specify path to Python 3 executable in tox.ini"

- .coveragerc
- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/mesos/task.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/cli/test_cmds_wait_for_deployment.py
A very quick optimization of the mesos cpu metrics provider to get stats asynchronously.
It shows 12% improvement in dev, which is a quite good result because dev services don't have enough instances to leverage gevent.
The next steps will be:
1. to support all provider
2. to query each mesos slave only once
3. will not query /slave(1)/state.json on every slave when collecting stats, because we probably don't need it.
3. (optional) to upgrade gevent
> gevent proof of concept for the service autoscaling

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Mesos 1.2.0 has been released. This change updates our itests to use this new version.
Changelog: https://github.com/apache/mesos/blob/1.2.0/CHANGELOG
This relates to internal ticket PAASTA-9514
> Use Mesos 1.2.0 in itests

- paasta_tools/marathon_serviceinit.py
People were interpreting this with the left hand side being the "existing" state (configured) and the right hand side as the "desired" state (start/stopped) and thinking that a mistmatch meant that it was wrong.
> Change words for desired state in marathon_serviceinit

- paasta_tools/drain_lib.py
- tests/test_drain_lib.py
These are the tasks we were crashing on:
MarathonTask::{'started_at': None, 'staged_at': None, 'state': u'TASK_UNKNOWN', 'ip_addresses': [], 'app_id': u'/geocoder.main.gitbae12aef.configa5d0ae8b', 'id': u'geocoder.main.gitbae12aef.configa5d0ae8b.cda16aec-0e80-11e7-a1c8-aef0de6ab313', 'local_volumes': [], 'service_ports': [], 'host': u'10-40-18-14-uswest1cdevc.dev.yelpcorp.com', 'version': None, 'health_check_results': [], 'slave_id': u'650b33b1-1997-415b-83b5-ed5ac440562c-S996', 'ports': []}
So I made all the draining stuff just return `None` if there is no port to talk to and drain.
> Make the drain lib handle the situation where a task is UNKNOWN and has no ports

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/frameworks/constraints.py
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/paasta_remote_run.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_constraints.py
- tests/frameworks/test_native_scheduler.py
constraints for #1087 
this supports EQUALS, LIKE, UNLIKE, MAX_PER and UNIQUE
in CLI this adds repeatable adrgument to remote-run: `--cons <attr>,<OP>[,<val>]`, in paasta_remote_run, `--constraints-json`
all constraint-related code is in paasta_tools/frameworks/constraints.py, in native scheduler we have `self.constraints` read from configs or cli (cli has precedence), `self.constraint_state` and `self.constraint_state_lock` for stateful constraints (only max_per for now), state is swapped every time call to `driver.acceptOffers` succeeds. state is locked around processing each offer and in statusUpdate when processing dead tasks.
> Remote run constraints support

- build-manpages.sh
- requirements.txt
This relates to #1118 . The issue was that `paasta --version` was resulting in a traceback with the error, `pkg_resources.DistributionNotFound: The 'PyStaticConfiguration>=0.10.3' distribution was not found and is required by yelp-clog`. This got passed to `help2man`'s `--version-string` unquoted, causing problems. I've bumped up the version of `PyStaticConfiguration`, added some extra quoting, and tried to make the manpage script fail in a more obvious manner.
> Use proper quoting and a newer PyStaticConfiguration to fix manpages

- paasta_tools/cli/cmds/get_latest_deployment.py
- tests/cli/test_cmds_get_latest_deployment.py
I'm trying to do `THING=$(paasta get-latest-deployment || other thing)` but I end up with `A deployment could not be found for super-production in example_happyhour` and red ansi color codes in my variable :)
> Send "A deployment could not be found" to stderr

- paasta_tools/generate_all_deployments
- paasta_tools/generate_deployments_for_service.py
- tests/test_generate_deployments_for_service.py
This is a precursor to the work on paasta-deployd. It means that
deployments.json files will only be written to if they are being
updated. This makes it possible to watch for inotify updates to that
file and perform a bounce based on inotify events.
Note that this will probably change the behaviour of:
https://github.com/Yelp/paasta/blob/master/paasta_tools/generate_all_deployments#L9
In fact, we definitely need to do something or it will be deleting things that haven't changed in a while. Do we really need that cleanup? I guess if a folder removes all it's marathon-* files then we need to remove the deployents.json...
> Only update deployments.json if changed

- paasta_tools/autoscale_cluster.py
- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/test_autoscale_cluster.py
Current behavior in cluster autoscaler is that with ```-vv``` all logging is set to level=DEBUG.
Turns out it's too verbose - this includes debug output of not only autoscaler but also all underlying libraries like boto and kazoo.
In this CR, we preserve current behavior at ```-vvv``` but at ```-vv``` we have underlying libs log at INFO while autoscaler logs at DEBUG.
> better verbosity levels for cluster autoscaler

- paasta_itests/environment.py
- paasta_itests/itest_utils.py
- paasta_itests/paasta_native.feature
- paasta_itests/paasta_remote_run.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/setup_marathon_job.feature
- paasta_itests/static_port.feature
- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/paasta_native_steps.py
- paasta_itests/steps/setup_marathon_job_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_native_serviceinit.py
- tox.ini
So this is pretty embarrasing but I added this test and it doesn't catch
the SystemExit that is called by setup_marathon_job. As a result our
itests are exiting whenever this test runs but seeming to be "green"
because the exit is with a 0 error code :-(
Merging this will "break" the build on master but in reality it's been
broken for quite a while!
Fixes #1110
> "Fix" the itests

- paasta_tools/cli/cmds/mark_for_deployment.py
Just a little thing that held up a ym push the other day -- I think the autoscaler must have scaled down while a bounce was in progress.
> Let wait-for-deployment finish when instance count is more than expected.

- paasta_tools/cli/schemas/marathon_schema.json
From the docs (https://paasta.readthedocs.io/en/latest/yelpsoa_configs.html#marathon-clustername-yaml):
```
bounce_margin_factor: proportionally increase the number of old instances to be drained when the crossover bounce method is used. 0 < bounce_margin_factor <= 1. Defaults to 1 (no influence). This allows bounces to proceed in the face of a percentage of failures. It doesn’t affect any other bounce method but crossover.
```
> Update schema to require that 0 < bounce_margin_factor <= 1

- docs/source/yelpsoa_configs.rst
This updates the docs on proxy_port to be accurate for discovery only services.
> Updating docs to reflect discovery only services

- paasta_tools/chronos_serviceinit.py
- paasta_tools/chronos_tools.py
- paasta_tools/marathon_serviceinit.py
- paasta_tools/marathon_tools.py
- paasta_tools/mesos_tools.py
- paasta_tools/paasta_serviceinit.py
- paasta_tools/utils.py
- tests/test_chronos_serviceinit.py
- tests/test_marathon_serviceinit.py
- tests/test_mesos_tools.py
* cache get_current_tasks() for paasta status explicitly
* cache cronos.client for paasta status
* always cache get_service_instance_list for 5 seconds
'paasta status -s yelp-main -c norcal-prod' takes 20 seconds.
'paasta status -s yelp-main -c norcal-prod -v' takes 3m20s.
> More caching for paasta status

- paasta_itests/paasta_deployd.feature
- paasta_itests/steps/paasta_deployd_steps.py
This checks that we spot changes to deployments.json and bounce
successfully.
> Add another itest for deployd file watcher

- requirements.txt
- setup.py
There was a new release https://pypi.python.org/pypi/pyOpenSSL today
that breaks our build because we've pinned cryptography. This upgrades
it to see if we get a clean build.
> A new version of pyOpenSSL requires this upgrade

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/marathon_serviceinit.py
- tests/autoscaling/test_autoscaling_service_lib.py
- tests/test_marathon_serviceinit.py
Inspired by recent addition of cluster autoscaling to metastatus this
will give service autoscaling info in paasta status. Still need to fix
some tests and check it works properly. Just chucking up for visibility.
> Add service autoscaling info to status

- setup.py
The previous fix which changed the exact pin of 1.4 to 1.7 is not the right fix. Paasta doesn't even import cryptography, it shouldn't be enforcing an == relationship. Let's see if we can pass tests without the pin.
@mattmb
> Remove cryptography exact pin from setup.py

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
I'd missed that we can get a MetricsProviderNoDataError from
filter_autoscaling_tasks so this was bubbling up into paasta status.
This moves it into the try block so we catch it safely and return the
partial data we can.
> Catch no data when geting autoscaling info

- paasta_tools/utils.py
Currently the TimeoutError is thrown but the main thread will still
continue to wait for the function thread to finish before it exits
itself. Setting the daemon flag means that the child thread will be
killed if the main thread dies, which it does on receiving the timeout
exception.
Internally: PAASTA-10556
> Fix threaded timeout decorator

- paasta_itests/steps/bounces_steps.py
- paasta_tools/deployd/workers.py
- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
This adds an extra return variable to setup_marathon_job with a time in
which the service instance it is deploying should be bounced again. To
start with this aims to be simple and naive. If it thinks everything is
steady state it returns -1, if it thinks more work needs to be done it
returns 60 (seconds). This can be further nuanced in the future.
This extra return variable is consumed by the paasta deployd workers
which can then re-add services to the bounce queue. For the existing
cron jobs the extra variable is just ignored.
> Make setup_marathon_job return bounce_again var

- paasta_tools/autoscaling/autoscaling_service_lib.py
- tests/autoscaling/test_autoscaling_service_lib.py
Even if there are not enough healthy tasks to get a completely accurate
calculation on utilization we should still scale up if the remaining
tasks are overutilized. This should prevent the autoscaler becoming
"wedged" if there are a few unhealthy tasks lingering in a small pool of
total tasks. This should preserve the current behaviour if the
utilization suggests we need to scale down. That is we still bail and do
nothing rather than scaling down because it could be risky to do so with
incomplete data.
> Ensure we always scale up if task data missing

- paasta_itests/steps/bounces_steps.py
- paasta_itests/steps/marathon_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_tools/bounce_lib.py
- tests/test_bounce_lib.py
This was added because we were overwhelming marathon. However, the
problem was with a pretty old version of marathon so we're hoping we no
longer need to be so conservative!
> Remove create_app_lock when creating marathon apps

- paasta_tools/deployd/master.py
- paasta_tools/deployd/metrics.py
- tests/deployd/test_metrics.py
Before we just sent the q length. The size of the dict is really the
more interesting thing. This also logs debug entries on the NoMetrics
provider so you can see what's going on when developing without having a
real metrics cluster.
> Send length of inbox as gauge

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/cli/utils.py
- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/frameworks/native_scheduler.py
- paasta_tools/mesos/master.py
- paasta_tools/paasta_remote_run.py
paasta remote-run gets subcommands: start / stop / list
paasta remote-run start:
- fix dry-run on master
- run in background with --detach
- optionally name your run with --run-id <blah>
paasta remote-run list: lists all active frameworks for specific cluster/service/instance with their respective run ids and framework ids
paasta remote-run stop: stop remote-run of cluster/service/instance by it's run id (-R) or framework id (-F)
> remote-run start/stop/list, --detach for background mode, optional --run-id for naming your runs

- paasta_tools/cli/utils.py
mesos creds are not readable to everyone, run it with sudo
also wait for remote-run to exit when interrupted
> sudo remote-run on mesos master

- paasta_tools/cli/cmds/remote_run.py
- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/paasta_remote_run.py
- tests/frameworks/test_adhoc_scheduler.py
run multiple copies of remote-run task when -j (--instances) flag passed. default to 1.
> remote-run -j | --instances <number>

- paasta_tools/list_marathon_service_instances.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
- tests/test_list_marathon_service_instances.py
- tests/test_setup_marathon_job.py
Optimize the time it takes to run 'list_marathon_service_instances -m' by calling get_draining_hosts() only once.
Internal ticket: PAASTA-7989
With this change it takes ~30 seconds to run it in norcal-prod.
> Optimize list_marathon_service_instances -m

- tests/deployd/test_leader.py
This test was flapping ~10% of the time. I guess it was relying on the
thread it was calling to actually have started and run something. This
mocks away the threading and seems to be reliable.
> Fix flappy deployd test

- paasta_tools/setup_chronos_job.py
- paasta_tools/setup_marathon_job.py
We have to catch these and send them back to the user, otherwise they just crash things and nothing bounces.
> Catch NoSlavesAvailableError errors. PAASTA-8692

- paasta_tools/frameworks/adhoc_scheduler.py
- paasta_tools/frameworks/native_scheduler.py
- tests/frameworks/test_adhoc_scheduler.py
lets fail fast, when trying to load config rather than after registering the framework and building a task
> ensure adhoc scheduler service config has cmd

- paasta_tools/cli/cmds/push_to_registry.py
- tests/cli/test_cmds_push_to_registry.py
If the image isn't in the registry docker returns something like:
``{"name":"hello-world","tags":null}``
This was causing an exception when `is_docker_image_already_in_registry`
should be returning False. This affects new services and blocks them
from being able to push-to-registry.
> Fix tags being null when checking registry

- paasta_tools/api/api.py
- paasta_tools/api/client.py
- paasta_tools/utils.py
`sys.modules` usually means one of two things:
- hacks
- bugs
I changed these to *explicitly* import their dependencies for checking `__file__` (I imagine this was originally copypaste from stackoverflow and then spread to other places in the codebase?)
> Don't pingpong with sys.modules for __file__

- paasta_tools/deployd/watchers.py
- paasta_tools/long_running_service_tools.py
- tests/deployd/test_watchers.py
First stab at watching zookeeper for changes to the number of instances.
I'll add some itests + unit tests before I merge this but it works for me in the example cluster.
> Watcher for deployd for autoscaling

- paasta_tools/mesos/slave.py
Every mesos.task.stats call initiates 2 HTTP requests to mesos slaves.
The first request (/slave(1)/state.json) is used to find correlation between task_id and executor_id.
And the second one (/monitor/statistics.json) is used to get stats for the executor_id.
I used this script to confirm that executor_id is equal to task_id in paasta so that we can skip querying /slave(1)/state.json.
```
from paasta_tools.marathon_tools import get_marathon_client
from paasta_tools.marathon_tools import load_marathon_config
from paasta_tools.mesos_tools import get_all_running_tasks
marathon_config = load_marathon_config()
marathon_client = get_marathon_client(
url=marathon_config.get_url(),
user=marathon_config.get_username(),
passwd=marathon_config.get_password())
all_mesos_tasks = …
```
> executor_id is always equal to task_id

- paasta_tools/cli/cmds/start_stop_restart.py
- paasta_tools/remote_git.py
This uses the default timeout of 10 seconds for the "timeout" decorator
```
jgl@prod-machine:~$ time paasta start -s example_happyhour -c norcal-stageg -i main
File "/usr/bin/paasta", line 11, in <module>
load_entry_point('paasta-tools==0.62.3', 'console_scripts', 'paasta')()
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cli.py", line 122, in main
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/start_stop_restart.py", line 266, in paasta_start
return paasta_start_or_stop(args, 'start')
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/start_stop_restart.py", line 202, in paasta_start_or_stop
remote_refs = …
```
> Add a timeout for when git server cannot be reached

- paasta_tools/utils.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
InstanceConfig should not be a dict object. It's not used as a dict - there's nothing stored directly in it. A few tests were relying on this and incorrectly not actually testing what they meant to test.
> InstanceConfig is not a dict

- paasta_tools/cli/cmds/check.py
We currently are not passing the path to yelpsoa-configs to the function that checks the `git_url` field in `service.yaml`. This makes it hard to check that a new service with a custom `git_url` is configured correctly prior to pushing. This change fixes that.
This is internal ticket PAASTA-11129
> Make paasta check -y look at the correct git_url

- paasta_tools/deployd/master.py
Sleeping 1 here is pretty slow on startup if you have a large number of
service instances as we do. This should speed up the startup a lot.
> Speed up processing inbox loop

- paasta_tools/deployd/master.py
- paasta_tools/utils.py
We want to configure these rates separately since you want to check all
services quickly but maybe don't need to bounce all services quickly
when public config changes.
> Split startup vs big bounce rate

- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/deployd/workers.py
- tests/deployd/test_watchers.py
As with the public config it doesn't make much sense to add things to
the bounce queue if their sha has not changed. This adds the same check
to changes to marathon-* files and deployments.json.
In addition I have disabled the yaml cache on the service configuration
lib since it was interfering with checking the sha. I'm pretty sure
we're not reading the configs frequently enough to need a cache.
> Make deployd check marathon ID before bouncing

- paasta_itests/steps/setup_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/firewall_update.py
- paasta_tools/mesos_tools.py
- paasta_tools/utils.py
- requirements.txt
- setup.py
- tests/test_chronos_tools.py
- tests/test_firewall_update.py
- tests/test_utils.py
(I need to squash this before I actually merge)
This introduces support into paasta-tools InstanceConfig for the 'dependencies.yaml' file, and the 'security' dictionary within marathon-* and chronos-*.yaml files. 
Perhaps the biggest impacting change is to the chronos config loading. I make load_chronos_job_config to be more consistent with load_marathon_job_config - it now loads (and merges) the full general_config.
Using these changes I also introduce paasta_firewall_update, a CLI command that will watch the synapse services directory for changes to dependencies that occur on services that are running on this box. There are some TODOs in this file - all it does right now is log. Later we'll hook this up to something that updates iptable rules.
Internal ticket PAASTA-10896
> Dependency & security support, and inotify-based synapse file watcher

- paasta_tools/cli/cmds/local_run.py
- tests/cli/test_cmds_local_run.py
They are redundant since we don't use any shell to execute 'docker run'.
They cause a problem with xenial images in new docker versions.
Internal ticket: OPS-11477
> Remove quotes around environment variables in local-run

- paasta_tools/firewall.py
- paasta_tools/iptables.py
- setup.py
- tests/test_firewall.py
- tests/test_iptables.py
This adds code to create and manage iptables rules as part of the PaaSTA firewalls CEP.
The only public entrypoint right now is one function `general_update`, which could be run from a cronjob. It sets up standard rules (such as the `PAASTA` chain), then generates a list of desired rules, diffs them against existing rules, and makes any necessary adjustments. Currently it uses fake data for "list of service instances on this host" and "desired rules for the service".
In the future, we'll need to figure out the integration points between this code and other processes (e.g. the docker wrapper and the inotify watcher).
Some things that need to be done before merge:
For now I'm just running the function manually and modifying the hard-coded test data.
It sets up the `PAASTA-INTERNET` chain, …
> Add code for working with iptables

- .travis.yml
- Makefile
- tox.ini
This enables the use of [tox-pip-extensions](https://github.com/asottile/tox-pip-extensions) when they're available. For users who haven't added tox-pip-extensions, there is no change.
At Yelp, this means we'll be able to take advantage of [pip-custom-platform](https://github.com/asottile/pip-custom-platform) in order to install binary deps from platform-specific wheels, and [venv-update](https://github.com/Yelp/venv-update) to speed up tox.
To actually use the private index server, you'll have to use `tox -i https://pypi.yelpcorp.com/simple`:
```
$ rm -rf .tox && time tox -i https://pypi.yelpcorp.com/simple --notest
[...]
tox -i https://pypi.yelpcorp.com/simple --notest  32.04s user 3.14s system 91% cpu 38.238 total
$ rm -rf .tox && time tox --notest
[... it fails with some build error, …
```
> Use tox-pip-extensions when available

- paasta_tools/firewall_update.py
- tests/test_firewall_update.py
This makes turns `paasta_firewall_update` have two modes:
* `paasta_firewall_update cron`
* `paasta_firewall_update daemon`
They share a few options (soa_dir, verbose), but the inotify one has some of its own options (like max update frequency) which don't apply to the cron command.
```
ckuehl@mesos1-uswest1cdevc:~/paasta$ .tox/py27/bin/paasta_firewall_update --help
usage: paasta_firewall_update [-h] [-d soa_dir] [-v] {daemon,cron} ...
Monitor synapse changes and update service firewall rules
positional arguments:
{daemon,cron}         mode to run firewall update in
optional arguments:
-h, --help            show this help message and exit
-d soa_dir, --soa-dir soa_dir
define a different soa config directory (default
/nail/etc/services)
-v, --verbose
```
``` …
```
> Add cron option to paasta_firewall_update

- debian/paasta-tools.links
- paasta_tools/cli/schemas/chronos_schema.json
- paasta_tools/cli/schemas/marathon_schema.json
- tests/cli/test_cmds_validate.py
Before:
```
$ /nail/sys/bin/paasta validate -y ~/proj/yelpsoa-configs -s example_happyhour
✓ Successfully validated schema: marathon-STAGE.yaml
✗ Failed to validate schema. More info: http://paasta.readthedocs.io/en/latest/yelpsoa_configs.html: /nail/home/ckuehl/proj/yelpsoa-configs/example_happyhour/marathon-mesosstage.yaml
Validation Message: Additional properties are not allowed ('security', 'dependencies_reference' were unexpected)
✓ Successfully validated schema: marathon-DEV.yaml
✓ Successfully validated schema: chronos-PROD.yaml
✓ Successfully validated schema: adhoc-norcal-prod.yaml
✓ Successfully validated schema: marathon-pnw-devc.yaml
✓ Successfully validated schema: marathon-PROD.yaml
✓ chronos-mesosstage.yaml has a valid instance: example_child_job.
✓ chronos-mesosstage.yaml …
```
> Add firewall-related keys to schema validation for Marathon and Chronos

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
sanitize_for_config_hash() accidentally modifies the input dictionary, resulting in paasta labels being stripped from marathon configs
> Fix paasta labels from being removed from marathon config

- paasta_tools/deployd/watchers.py
- tests/deployd/test_watchers.py
Catch this exception when checking the marathon app id.
> Fix deployd watcher NoDockerImage exception

- .travis.yml
- paasta_itests/chronos_rerun.feature
- paasta_itests/cleanup_chronos_jobs.feature
- paasta_itests/paasta_serviceinit.feature
- paasta_itests/steps/chronos_rerun_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/chronos_rerun.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/rerun.py
- paasta_tools/cli/utils.py
- paasta_tools/utils.py
- tests/cli/test_cmds_rerun.py
- tests/test_chronos_rerun.py
- tests/test_chronos_tools.py
- tests/test_mac_address.py
- tox.ini
paasta rerun will re-execute only the job identified by ``(cluster, service, instance)`` from the command line arguments. It implicitly [removes all the references to the parents](https://github.com/Yelp/paasta/blob/master/paasta_tools/chronos_rerun.py#L145) and [schedules the job to start as soon as possible](https://github.com/Yelp/paasta/blob/master/paasta_tools/chronos_rerun.py#L148).
> 'paasta rerun' creates a copy of the specified PaaSTA scheduled job and
executes it immediately. Parent-dependent relationships are ignored: 'pasta
rerun' only executes individual jobs.
This PR introduces a new command line argument to the ``rerun`` command. The new argument, ``--rerun-type``, will allow the user to customize the rerun policy used for a specific ``(cluster, service, instance)``:
* …
> Allow `paasta rerun` of dependent jobs

- paasta_tools/firewall.py
- paasta_tools/firewall_update.py
- paasta_tools/smartstack_tools.py
- tests/test_firewall.py
- tests/test_firewall_update.py
This gets the cronjob correctly applying rules, with the exception of still using fake mac addresses. You can see it in action on `mesos1-uswest1cdevc`, where I'm running instances of `example_happyhour` and `robj-test-service` in both monitor and block mode. (Try e.g. `sudo iptables-save` to see the rules it's set.)
It supports the `internet` well-known name, allowing access to smartstack (but currently only via yocalhost), and monitor/block mode.
> Start to hook up iptables rules with real world state

- paasta_tools/mesos_tools.py
Currently, passing a bad {white,black}list will cause the autoscaler to crash. This PR will catch this kind of ValueError, assume the slave does NOT pass, logs, and continues.
Question: is this assumption sound? Or would it be better to assume it passes the lists?
> Catch ValueErrors in processing {white,black}lists

- docs/source/installation/example_cluster.rst
- example_cluster/tests/start-new-service.sh
We can't do this check in the example cluster because the registry URL
is "wrong". The registry has to be listed as localhost because it is
local to where the daemon is running. However localhost from the cli
tools does not resolve to the docker host and so we get a connection
error. Skipping the check with --force works fine.
@philipmulcahy: @Rob-Johnson and I worked out all we need to do is add `--force`!
> Skip check for existing image in example cluster

- paasta_tools/setup_marathon_job.py
- tests/test_setup_marathon_job.py
Only call get_draining_hosts once per bounce, and handle a potential ReadTimeout exception by failing out with an error message, and retrying the bounce again in 60 seconds
> Refactor get_draining_hosts

- paasta_tools/firewall.py
- tests/test_firewall.py
It was expecting a format like this:
```yaml
main:
smartstack: ['npm.main', 'pypi.main']
well-known: ['internet']
```
instead we're using this format:
```yaml
main:
- smartstack: npm.main
- smartstack: pypi.main
- well-known: internet
```
> Make firewall cronjob parse dependencies correctly

- paasta_tools/firewall.py
- paasta_tools/firewall_update.py
- tests/test_firewall.py
- tests/test_firewall_update.py
Sorry for making this one PR - it may be easier to read the commits independently.
The first one was pretty straightforward - modify ensure_service_chains() to take an optional filter kwarg, and then have firewall_update pass in the services it cares about via that kwarg.
Second change was to add support for the synapse backends in the iptables rules. This got a little more involved because we needed a new config_dir to be passed around (the synapse_service_dir) and I didn't like having to add it to the ServiceGroup namedtuple. So instead I refactored ServiceGroup to eliminate storing soa_dir, and made "rules" a method instead of a property. So there are definitely some style differences. The only material thing I can think this affects is that the chain_name() sha no longer factors in …
> inotify actually does updates, and include backends in iptables rules

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
just pass the instance ids we want as a paramter, rather than
filtering using private ip addresses, which isn't supported
> fix call to describe_instance_status

- paasta_tools/deployd/watchers.py
- tests/deployd/test_watchers.py
listdir can fail, if there's nothing in the folder or listdir fails then
we don't need to proactively bounce so just return from that function
> Catch OSError watching new folder

- paasta_tools/docker_wrapper.py
- tests/test_docker_wrapper.py
For #1281. Identify --env-file args and load their contents as environment variables
> add support for --env-file to docker_wrapper

- paasta_tools/firewall.py
- paasta_tools/firewall_logging.py
- paasta_tools/firewall_update.py
- paasta_tools/iptables.py
- paasta_tools/utils.py
- requirements.txt
- setup.py
- tests/test_firewall.py
- tests/test_firewall_logging.py
- tests/test_firewall_update.py
- tests/test_iptables.py
This adds log-prefix and limit to monitor mode.
target_parameters ended up being a bit trickier than expected because adding a REJECT rule will cause iptables to automatically imply a "--reject-with icmp-port-unreachable" rule. This ends up causing comparison problems when loaded back in. To fix, I require that reject-with always be specified in the case of REJECT.
> Add support for logging with prefix and limits

- paasta_tools/marathon_tools.py
- tests/test_marathon_tools.py
This reverts commit e4ebd16b8dc67b5b023f592f12e7beeb9e31edb0.
To be clear this is *disabling* MESOS_HTTP checks again
cc @Rob-Johnson
> Revert "Revert "Revert "default healthcheck type to MESOS_HTTP"""

- paasta_tools/docker_wrapper.py
- paasta_tools/firewall.py
- paasta_tools/firewall_update.py
- tests/test_docker_wrapper.py
- tests/test_firewall.py
- tests/test_firewall_update.py
Integration!
Refactored ensure_service_chains() again - rather than reading all running services and taking an optional filter kwarg, you just pass in the ones that you want in the first place.
prepare_new_container() is a new function that ensures the right rules and chains are in place to allow access with a particular MAC.
I left a TODO: currently we're setting up iptables rules for all containers with security settings, regardless of mac address. We may want to only affect mac addresses that have the prefix that indicates they were generated from docker_wrapper... not sure if it really matters though? Either way you're opting-in via your soa-configs settings.
> docker_wrapper inserts firewall rules in preparation of running

- paasta_tools/mesos_tools.py
- paasta_tools/metrics/metastatus_lib.py
- tests/metrics/test_metastatus_lib.py
we only want to calculate resource utilization of running tasks (and
thus ignore those that aren't actually using allocated resources).
internal PAASTA-11698
> only count non-terminal tasks in metastatus

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
amazon sets limits of 100 instances ids in the filter - batch the call
into sets of 99
> batch calls to describe_instance_status

- paasta_itests/steps/paasta_native_steps.py
- paasta_tools/adhoc_tools.py
- paasta_tools/chronos_tools.py
- paasta_tools/frameworks/native_service_config.py
- paasta_tools/long_running_service_tools.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
- tests/test_marathon_tools.py
While working on allowing per-service docker registries, we noticed that we were missing the soa_dir in some places. This change adds soa_dir as a field in our InstanceConfig objects
> Add soa_dir as field in InstanceConfig and subclasses

- paasta_tools/cli/utils.py
If `-v` and `--rerun-type=graph` are passed to paasta rerun, line 568 will end up being `--run-all-related-jobs-v`, which would probably not work.
> Fix a potential problem when -v and --rerun-type=graph are passed to paasta rerun

- paasta_tools/chronos_rerun.py
- tests/test_chronos_rerun.py
After the first experiment on mesosstage I noticed that the graph dependency was not correct.
It was caused by the fact that ``chronos_rerun.clone_job`` was not modifying the cloned job config.
I have fixed it and added a test for ensuring that this will still be valid
> chronos_rerun.clone_job should modify only cloned config

- tests/cli/test_utils.py
Added a small unittest to prevent regression caused by "wrong" ``chronos_rerun_graph`` generated SSH command.
This is a test only change :)
> Add unittest for run_chronos_rerun with run_all_related_jobs flag

- paasta_tools/check_marathon_services_replication.py
Since CRITICAL sends pages, it makes sense to list the critical lines first.
I am not sure if this needs extra tests.
> Re-order replication check output to list CRITICAL before OK

- paasta_tools/firewall.py
- paasta_tools/iptables.py
- tests/test_firewall.py
- tests/test_iptables.py
stricter handling of iptables parameters to preserve symmetry with how they're read back out of iptables:
- parameter values must always be tuples
- must use dashes instead of underscores
> stricter handling of iptables parameters

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
PAASTA-7692
Could it be as simple as this? 'region' vs 'datacenter' confusion is because slave attributes have datacenter=us-west-1, while autoscaler config (from S3) has region=us-west-1.
@solarkennedy @mattmb
> let autoscaler measure capacity at region level instead of superregion

- paasta_tools/firewall.py
- paasta_tools/iptables.py
- tests/test_firewall.py
- tests/test_iptables.py
This adds a function called reorder_chain() that ensures that all rules of a chain have REJECT being last, and LOG being second-last.
I have admittedly mixed feelings about it. Changing the existing behavior of ensure_chain() is pretty complex - it'd require a diff algo. So instead this is its own separate function. This way the code is reasonably simple to follow IMHO. I also wanted something that will fix existing chains, like if we introduce a bug with ordering at any point, or a failure results in inconsistent state. This is a straightforward way to fix any existing chain.
It doesn't cause any unnecessary reordering - it preserves order of existing ACCEPT rules. There's probably a way to do it with fewer operations, I'd need to break out my sorting algorithms. OTOH, it doesn't do any …
> Enforce ordering on iptables rules

- paasta_tools/firewall.py
- paasta_tools/iptables.py
- tests/test_firewall.py
..  to help identify what they refer to.
Example iptables -S output:
```
-A PAASTA.example_ha.8891d16afc -d 169.254.255.254/32 -p tcp -m comment --comment "proxy_port yelp-main.internalapi" -m tcp --dport 20666 -j ACCEPT
-A PAASTA.example_ha.8891d16afc -d 10.40.10.88/32 -p tcp -m comment --comment "backend yelp-main.internalapi" -m tcp --dport 31719 -j ACCEPT
-A PAASTA.example_ha.8891d16afc -d 10.40.24.254/32 -p tcp -m comment --comment "backend yelp-main.internalapi" -m tcp --dport 31918 -j ACCEPT
-A PAASTA.example_ha.8891d16afc -d 10.40.22.153/32 -p tcp -m comment --comment "backend yelp-main.internalapi" -m tcp --dport 31063 -j ACCEPT
-A PAASTA.example_ha.8891d16afc -d 169.254.255.254/32 -p tcp -m comment --comment "proxy_port pypi.main" -m tcp --dport 20641 -j ACCEPT
-A …
```
> Add comments on iptables ACCEPT lines

- paasta_tools/drain_lib.py
- paasta_tools/marathon_tools.py
- tests/test_drain_lib.py
Fixes #1287
@EvanKrall Is a timeout of 15 seconds enough time? Do we want to catch the timeout and proceed anyway when in `stop_draining`?
> Add timeout to HTTP draining requests

- paasta_tools/firewall.py
- tests/test_firewall.py
Internal ticket: PAASTA-11414
If we can't get configuration for an instance type, just ignore it instead of breaking all of the firewall infrastructure.
> Tolerate weird instance types in firewall update

- yelp_package/dockerfiles/itest/marathon/Dockerfile
Marathon 1.4.5 is released.
https://github.com/mesosphere/marathon/releases/tag/v1.4.5
The only change in this release is:
```
MARATHON-7479 Fixes major deployment plan computation performance regression for Marathon instances containing a large number of apps (500+).
```
This is internal ticket: PAASTA-11880
> Upgrade itests to use Marathon 1.4.5

- yelp_package/dockerfiles/itest/chronos/Dockerfile
- yelp_package/dockerfiles/itest/marathon/Dockerfile
- yelp_package/dockerfiles/itest/mesos/Dockerfile
Mesos 1.3.0 has been released. It appears to fix the issues we noticed while testing 1.2.0. Let's start evaluating it.
This is internal ticket PAASTA-9514
> Upgrade to mesos 1.3.0

- docs/source/system_configs.rst
- docs/source/yelpsoa_configs.rst
- paasta_itests/steps/bounces_steps.py
- paasta_tools/chronos_tools.py
- paasta_tools/cli/cmds/local_run.py
- paasta_tools/cli/cmds/push_to_registry.py
- paasta_tools/frameworks/native_service_config.py
- paasta_tools/marathon_tools.py
- paasta_tools/utils.py
- tests/cli/test_cmds_itest.py
- tests/cli/test_cmds_local_run.py
- tests/cli/test_cmds_push_to_registry.py
- tests/frameworks/test_adhoc_scheduler.py
- tests/frameworks/test_native_scheduler.py
- tests/test_chronos_tools.py
- tests/test_marathon_tools.py
- tests/test_setup_chronos_job.py
- tests/test_utils.py
This PR allows service owners to specify their own docker registry to use.
Currently, the docker registry is set at a system-wide level in the system config.  This system-wide docker registry will still be the default, but service owners can optionally specify a different registry by setting the "docker_registry" key in their service configuration file.
> Allow for per-service docker registry

- requirements.txt
- setup.py
@jglukasik is having dependency version conflicts with protobuf -- mesos.interface needs < 3, signalform needs >3.5.
> Remove mesos.interface now that we use pymesos.

- paasta_tools/autoscaling/ec2_fitness.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
- tests/autoscaling/test_ec2_fitness.py
we need to sort chronos_tasks and tasks in descending order, since we
want to save those instances which have the most tasks attached.
> fix fitness evaluation of mesos slaves

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
To address the issue in this stack trace:
```
{u'slaveId': '8f86d7a7-210c-4def-a439-d39baf6f0eb3-S2576', u'resources': '[{"role": "maintenance", "scalar": {"value": 239776.0}, "type": "SCALAR", "name": "disk", "reservation"
: {"principal": "mesos_slave"}}, {"role": "maintenance", "scalar": {"value": 113628.0}, "type": "SCALAR", "name": "mem", "reservation": {"principal": "mesos_slave"}}, {"role": "
maintenance", "scalar": {"value": 1.5}, "type": "SCALAR", "name": "cpus", "reservation": {"principal": "mesos_slave"}}]'}
File "/usr/bin/paasta_autoscale_cluster", line 11, in <module>
load_entry_point('paasta-tools==0.65.16', 'console_scripts', 'paasta_autoscale_cluster')()
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/autoscale_ …
```
> Catch SlaveDoesNotExist exception in autoscaler

- MANIFEST.in
- setup.py
`package_data` is used only for binary distributions (like doing `python setup.py bdist_wheel`) and not source distributions. The way we build our wheels (since 2016-12-13) is by taking the source distribution (which is missing the package data) and turning it into wheels.
Using `MANIFEST.in` will put the package data in both source and binary distributions.
I ran `setup.py bdist_wheel` and `setup.py sdist` both before and after this change, and diffed the list of files:
```diff
--- before/before       2017-06-20 11:58:56.633670501 -0700
+++ after/after 2017-06-20 11:58:51.137596501 -0700
@@ -69,10 +69,23 @@
./sdist/paasta-tools-0.65.26/paasta_tools/cli/cmds/__init__.py
./sdist/paasta-tools-0.65.26/paasta_tools/cli/cmds/rerun.py
./sdist/paasta-tools-0.65.26/paasta_tools/cli/cmds/info.py …
```
> Switch from package_data to manifest file to fix missing package data in internal wheels

- paasta_tools/cli/cmds/mark_for_deployment.py
Another case where the error message would be a lot more helpful if it told you what it was actually trying to talk to.
> Better error message telling you which cluster the problem was with

- paasta_tools/deployd/master.py
- tests/deployd/test_deployd_master.py
This adds an output to scribe for paasta-deployd if scribe is already
configured as a log_writer.
I think this is a sane way to get the deployd logs into scribe. I haven't tested this and I suspect I might need to tweak the formatter to get hostname and time? Anyone who knows more about scribe got any thoughts?
> Add ScribeHandler to paasta-deployd

- paasta_tools/cli/cmds/local_run.py
'action=store_true' means this argument will ony be a true/false flag.
Right now paasta local-run errors out if you run it with '--port 9999',
because it's not expecting the 9999 option.
> Fix paasta local-run port argument

- paasta_tools/docker_wrapper.py
- paasta_tools/firewall.py
- paasta_tools/firewall_update.py
- paasta_tools/utils.py
- tests/test_docker_wrapper.py
- tests/test_firewall_update.py
- tests/test_utils.py
Introduce a `timed_flock` contextmanager to utils, and use it in the paasta_firewall stuff:
- firewall_update cron will flock upon calling general_update(). Exceptions are not caught, causing the cron to fail.
- firewall_update inotify daemon will flock upon calling ensure_service_chains(). Exceptions will log an error but not propagate, allowing the daemon to continue running.
- docker_wrapper will flock upon calling prepare_new_container(). Exceptions will print to stderr but not propagate. The underlying docker command will still be executed.
This presumes that /var/run/paasta is writable. /var/run/paasta/mac-address is already required for use by the docker_wrapper, so this shouldn't really be anything new.
Internal ticket PAASTA-11247
> Adding a timed flock to firewall operations

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
Currently we get the weight of each instance from AWS and then we sum
those weights. Due to floating point arithmetic we can end up with a
killable capacity that is slightly less than the desired change. This
additional rounding should stop the autoscaler getting wedged.
> Fix rounding error: cluster autoscaler

- paasta_tools/deployd/workers.py
- tests/deployd/test_workers.py
I don't really like catching all exceptions but in this case it seems
reasonable just because it's hard to know everything that could go wrong
in setup_marathon_job, especially as it has to talk to marathon's API
and could end up getting a weird response.
The motivation is to prevent a service not being bounced again when
there happens to be some transient exception thrown in the worker.
> Catch any exception running setup_marathon_job

- paasta_tools/mesos_tools.py
- tests/test_mesos_tools.py
Inside the debug line for handling this exception, I print the task.
Well, the __str__ method of task, calls task.slave, which then throws
another SlaveDNE exception within the handler, so it doesnt get caught
Now, just print the task id, instead of the whole task (id + slave)
> Fix issue in handling SlaveDoesNotExist exception

- paasta_tools/cli/cmds/mark_for_deployment.py
- paasta_tools/cli/cmds/wait_for_deployment.py
- paasta_tools/cli/utils.py
- tests/cli/test_cmds_mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
- tests/cli/test_utils.py
It is rather frustrating not being able to simply copy/paste a short git sha displayed in other tools into `paasta wait-for-deployment`. This PR attempts to fix that. It modifies `mark-for-deployment` and `wait-for-deployment` to accept a short git sha as an argument. It will then attempt to convert this to a full sha and pass that full sha around internally.
This is internal ticket PAASTA-10534
> Make mark and wait for deployment commands accept a short git sha

- paasta_tools/deployd/common.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/deployd/workers.py
- paasta_tools/utils.py
- tests/deployd/test_common.py
- tests/deployd/test_watchers.py
- tests/deployd/test_workers.py
If a worker fails to bounce a service due to an exception then it will
back off trying exponentially. This is especially to be kind to Marathon
incase it is overwhelmed and causing the bounces to fail.
cc @solarkennedy
> Add exponential back off deployd

- paasta_tools/deployd/master.py
Lets go back to just stdout because it captures everything, not just
logging.
> Simplify logging for deployd

- paasta_tools/deployd/watchers.py
- tests/deployd/test_watchers.py
* Handle timeouts/connection errors speaking to mesos
* Handle the fact that a host can finish draining and then start draining again in the future!
> Fix maintenance watcher

- paasta_itests/steps/paasta_deployd_steps.py
- paasta_tools/deployd/common.py
- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- tests/deployd/test_common.py
- tests/deployd/test_deployd_master.py
- tests/deployd/test_watchers.py
When deployd starts it must evaluate every service with a run of setup
marathon job to ensure it hasn't "missed" an event (e.g. autoscaling or
deployment). However, when we start we can prioritise services that we
know are deploying becuase their app ID has changed. This way if there
is a leader election or restart of deployd: bouncing/deploying services
will be at the front of the queue when it starts up.
Note the bulk of this is just moving stuff around. `prioritise_bouncing_services` is the new bit.
> Make deployd prioritise bouncing services on start

- paasta_tools/utils.py
Very minor change. I was reading through @bchess's PR #1314 and noticed the Timeout context manager is not restoring existing signal handlers should they exist. Most likely this is not and never will be an issue, but it's probably better safe than sorry.
> Restore old signal handler on exit

- paasta_tools/deployd/master.py
This object is a generator so wasn't very useful in a log line!
> Fix log line in deployd

- paasta_tools/firewall.py
- tests/test_firewall.py
> Don't fail firewall updates when a deleted service still has running containers

- paasta_tools/docker_wrapper.py
- paasta_tools/firewall.py
Because /var/run is a tmpfs so is empty upon boot/reboot. Internal ticket PAASTA-12034
> Changing firewall-related paths to be /var/lib/paasta instead of /var/run/paasta

- paasta_tools/deployd/master.py
- tests/deployd/test_deployd_master.py
The log line was "consuming" the generator :-( so this was not working
and my test wasn't catching it because it wasn't using a mock of what
the output actually would have been.
> Fix deployd prioritising bouncing services

- paasta_tools/deployd/master.py
- paasta_tools/deployd/watchers.py
- paasta_tools/utils.py
- tests/deployd/test_watchers.py
This makes the frequency at which we poll mesos's maintenance API from
deployd configurable. The motivation is so we can throttle load against
the mesos master by polling less frequently.
I've also increased the default from 20 to 30 seconds
cc @solarkennedy we may need to bump higher in our biggest cluster but I suspect 30 is okay elsewhere.
> Make maintenance polling frequency configurable

- paasta_tools/deployd/common.py
- tests/deployd/test_common.py
I'm not 100% on the root cause of this exception but the deploy daemons
file watcher certainly shouldn't die as a result. The safest thing is to
catch it and assume the service needs a bounce. Then it will be up to
the worker to have a go at deploying the service and back off it sees
the same error.
> Catch InvalidJobNameError in deployd

- requirements.txt
- setup.py
Got errors like:
```
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: soa_dir=soa_dir,
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/check_chronos_jobs.py", line 99, in send_event
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: soa_dir=soa_dir,
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/paasta_tools/monitoring_tools.py", line 203, in send_event
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: **result_dict)
Jul 12 17:27:05 mesos1-uswest1cdevc cron_check_chronos_jobs: File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/pysensu_yelp/__init__.py", line 324, in send_event
Jul 12 17:27:05 …
```
> Pysensu is not py36 compatible until 0.3.4

- paasta_tools/firewall.py
paasta firewal is sad on python3 because this constant has a b in front of it.
I removed the b.
> Fixup firewall.py for py3

- paasta_tools/oom_finder.py
- setup.py
internal ticket: PAASTA-567
This script looks for OOM records in /var/log/messages.
When it finds something, it tries to obtain service and instance name using 'docker inspect' and generates a record in the following format:
```
date/time hostname container_id service.instance
```
I'm going to run the script via cron every minute and stream its output to kafka using stdin2scribe.
> paasta_oom_finder, initial commit

- yelp_package/extra_requirements_yelp.txt
Found by acoover, paasta logs doesn't work because scribereader had non absolute imports until 0.2.6 ...
I've upgraded to 0.2.6 and am testing paasta logs locally from the lucid package.
> Scribereader was not py3 compatible until 0.2.6

- paasta_tools/cli/cmds/local_run.py
Otherwise, when --port=5000 is provided, one gets,
```
File "/usr/bin/paasta", line 11, in <module>
load_entry_point('paasta-tools==0.65.38', 'console_scripts', 'paasta')()
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cli.py", line 122, in main
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/local_run.py", line 892, in paasta_local_run
dry_run=args.action == 'dry_run',
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/local_run.py", line 824, in configure_and_run_docker_container
framework=instance_type,
File "/opt/venvs/paasta-tools/local/lib/python2.7/site-packages/paasta_tools/cli/cmds/local_run.py", line 538, …
```
> Fix the type of user_port to avoid TypeError in socket.socket

- paasta_tools/paasta_remote_run.py
Previously Ctrl+C doesn't work. The patch was tested with kill -SIGINT|SIGTERM pid.
> Fix remote run signal handler

- paasta_itests/steps/bounces_steps.py
- paasta_tools/deployd/watchers.py
- paasta_tools/deployd/workers.py
- paasta_tools/marathon_tools.py
- paasta_tools/setup_marathon_job.py
For some calls to /v2/apps we need to embed the tasks in the results. I
don't think we need the task failures and embedding them is deprecated
because it implies embedding everything else. See:
https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2apps
Unfortunately embedding tasks still implies embedding deployments which
I think we also don't need. However, this is supposed to change at some
point in the future.
If the itests pass then I think this is safe and it should reduce the
load on marathon slightly.
> Ask marathon to embed tasks not failures

- paasta_tools/autoscaling/autoscaling_service_lib.py
- paasta_tools/cli/cmds/rollback.py
- paasta_tools/mesos/master.py
- tests/autoscaling/test_autoscaling_service_lib.py
* fixes bytes handling from zk by explicitly decoding
* fixes a bug in paasta rollback that deals with tuple comparison instead of string comparison
> Python3 bytes

- paasta_tools/utils.py
After the Python 3 upgrade, I noticed I didn't get all of the output in paasta local-run (including the URL) until after I hit ^C. Flushing explicitly fixes that.
> Call flush() in paasta_print

- .pre-commit-config.yaml
trivial upgrade, just wanted to make sure this repo doesn't get hit by some not-so-good bugs in 0.6.0
> Upgrade add-trailing-comma to 0.6.1

- paasta_tools/cli/fsm/autosuggest.py
- tests/cli/fsm/test_autosuggest.py
We used to allocate proxy_port sequentially, so the assumption was that all ports were compacted at the bottom of the port range. Under that assumption, max() was sufficient. Now, we allocate randomly, so we need to consider the set of all ports from each file.
> Fix bug where paasta fsm was suggesting ports that were already in use

- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_metastatus.py
- tests/metrics/test_metastatus_lib.py
```
Resources Grouped by region
Region      CPU (used/total)   RAM (used/total)        Disk (used/total)      Agent count
fakeregion  2.0/10.0 (20.00%)  200.0M/512.0M (39.06%)  80.0M/100.0M (80.00%)  1
Resources Grouped by pool
Pool     CPU (used/total)   RAM (used/total)        Disk (used/total)      Agent count
default  2.0/10.0 (20.00%)  200.0M/512.0M (39.06%)  80.0M/100.0M (80.00%)  1
```
> Add agent count to paasta metastatus -vv

- paasta_tools/api/views/instance.py
- tests/api/test_instance.py
The paasta api needs to be "cheap" for wait for deployment.
We can't afford fetching state.json on the non-verbose mode of this, especially with the heavy load of wait-for-deployment polling constantly.
> Only get slave data from the paasta api on verbose mode

- .travis.yml
This is useful for "interactive" debugging against travis-ci without making a pull request.
It seems @macisamuele already had this set up, this makes it more generic
> CI test branches prefixed with `travis-ci-`

- paasta_tools/list_marathon_service_instances.py
- tests/test_list_marathon_service_instances.py
- tests/test_setup_marathon_job.py
Closing https://github.com/Yelp/paasta/pull/1389 in favor of this new approach.
Turns out this was a much simpler fix than I realized, and just requires adding NoSlavesAvailableError as an except in a try block in `get_desired_marathon_configs`. I added a test in `test_list_marathon_service_instance`, it fails without the NoSlaves catch, passes with it.
I started this by digging a lot into setup_marathon_job. I ended up writing a test to ensure `deploy_marathon_service` handled the NoSlavesAvailableError correctly. I was surprised to find the test pass, before I ever added code to `setup_marathon_job`. It was then that I took a closer look at the stack trace, and realized that `list_marathon_service_instances` was the real culprit. I think I'll leave the test to check against regressions …
> Handle NoSlavesException from list_marathon_service_instances

- paasta_tools/firewall_update.py
- tests/test_firewall_update.py
inotify filenames were bytestrings so the `suffix == '.json'` test was failing :(
> Bug fixes to firewall_update related to py3 upgrade

- paasta_tools/cli/cmds/push_to_registry.py
- tests/cli/test_cmds_push_to_registry.py
Filing for comments, but I still need to add tests. This would be to support eat24 localhost registries
> When checking the registry, fallback to trying http as well

- docs/source/yelpsoa_configs.rst
This was confusing for users of paasta expecting 3.0 features to be
available in Yelp's infrastructure, and not knowing about the features we've added to 2.4
> add a note describing Yelp's fork of Chronos.

- paasta_tools/drain_lib.py
We currently don't set a timeout which means we rely on the kernel
deciding when to give up on a TCP connection. This can often be several
minutes which is way too long. This sets it to 15s explicitly.
> Add a sane timeout when talking to hacheck

- general_itests/fake_simple_service/Dockerfile
- yelp_package/dockerfiles/gitremote/Dockerfile
- yelp_package/dockerfiles/itest/zookeeper/Dockerfile
I'll eventually follow up with more of these, this makes it easier to get all of the compose containers running python3.6
> Use xenial for more dockerfiles

- yelp_package/dockerfiles/itest/hacheck/Dockerfile
This branch:
- upgrades `hacheck` to use yelp's master branch
- uses xenial instead of trusty
- some docker best practices
previous passing run: https://travis-ci.org/asottile/paasta/builds/260310790?utm_source=email&utm_medium=notification
> Convert more dockerfiles to xenial

- paasta_tools/paasta_remote_run.py
- tests/cli/test_cmds_local_run.py
Bumped task-proc to latest.
test_run_docker_container_with_user_specified_port test was failing on master because check_if_port_free is not mocked out. So, if port 1234 is taken on the box where these tests are running, then this unit test fails. Mocked it out to fix the test.
> Bump task-proc and fix a unit test.

- paasta_tools/firewall.py
- tests/test_firewall.py
The yelpsoa-configs look like this:
```yaml
main:
- cidr: '169.229.226.0/25'
port: 80
- cidr: '169.229.226.0/25'
port: 443
- cidr: '169.229.226.128/25'
- cidr: '169.229.226.12'
```
> Add support for whitelisting CIDR/port combinations

- paasta_tools/firewall.py
- tests/test_firewall.py
This reverts commit 0f4e7ff821e814065e6ce18d3b9c747b89abb277, reversing changes made to e50e1fdf5574035c235047ab0958b7e67bbd4c3b.
We decided to just whitelist this explicitly on the few services that require it.
> Revert "Merge pull request #1417 from chriskuehl/whitelist-google-public-dns"

- paasta_tools/oom_logger.py
- tests/test_oom_logger.py
This change should add name of the process invoked OOM killer to the log.
> Add process name to the oom log

- paasta_tools/deployd/common.py
- tests/deployd/test_common.py
1. I'm deciding *not* to list service.instances that are not ready for some reason (broken deployments, image, etc)
2. I'm caching NoDeployments, as it was crashing deployd and causing it to start over.
> Make deployd skip deploys on broken instances

- paasta_itests/capacity_check.feature
- paasta_itests/paasta_api.feature
- paasta_itests/steps/paasta_api_steps.py
- paasta_itests/steps/paasta_metastatus_steps.py
- paasta_itests/steps/paasta_serviceinit_steps.py
- paasta_itests/steps/setup_steps.py
- paasta_tools/monitoring/check_capacity.py
- tests/monitoring/test_check_capacity.py
Allows to specify attributes and override the defaults per attribute value.  Also allows checking each attribute individually or by the combination of different attributes.
RFC: is this a sensible way to do this?
(Still needs tests, itests)
Examples:
```
root@0fdabc955099:/work/paasta_tools# ./monitoring/check_capacity.py --disk 79
CRITICAL cluster testcluster disk usage: superregion: unknown is at 80.0 percent disk, maximum 79.0 percent
```
```
root@0fdabc955099:/work/paasta_tools# ./monitoring/check_capacity.py --disk 79 --attributes region,pool --cross-product-check
CRITICAL cluster testcluster disk usage: superregion: unknown, region: fakeregion, pool: default is at 80.0 percent disk, maximum 79.0 percent
```
```
root@0fdabc955099:/work/paasta_tools# ./monitoring/check_capacity.py …
```
> Add capacity_check health check

- paasta_tools/mesos_maintenance.py
- paasta_tools/metrics/metastatus_lib.py
- tests/api/test_resources.py
- tests/metrics/test_metastatus_lib.py
closes JIRA PAASTA-12410
rather than counting *all* reserved resources as used, only count the
resources reserved by the maintenance mode
> only consider maintenance role for utilization

- paasta_tools/deployd/master.py
- paasta_tools/utils.py
- tests/deployd/test_deployd_master.py
In order to gradually bounce all services it is important to have the
option to disable the oracle like behaviour on startup. In other words
if we know we need to bounce all services gradually we don't want
deployd to bounce everything right away when it starts up.
> Make deployd startup oracle optional

- paasta_tools/marathon_tools.py
configure_nerve just trusts the port, so I think this is all we need to support puppet services registering multiple service ports at once.
cc @matthewmcarlson
> Support multiple puppet service ports

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- tests/autoscaling/test_autoscaling_cluster_lib.py
When scaling SFRs we have to always kill one instance when down scaling.
This prevents us getting stuck when the non integer value of capacity
would take us below our integer target.
However, we can't set a capacity of 0 because it is not allowed by AWS
so we still need to prevent the autoscaler attempting to set a target of
0 even when it means it kills 0 instances. In addition, we must kill the
instance if the SFR is cancelled, it is safe to do so because we don't
need to set a target capacity on a cancelled SFR.
> Fix scaling SFRs to less than 1

- paasta_tools/autoscaling/autoscaling_cluster_lib.py
- paasta_tools/cli/schemas/adhoc_schema.json
- paasta_tools/metrics/metastatus_lib.py
- paasta_tools/paasta_remote_run.py
- paasta_tools/utils.py
- tests/api/test_resources.py
- tests/metrics/test_metastatus_lib.py
- tests/test_utils.py
- add gpus resource to remote-run and basic instance config (in utils)
- add gpus functions for basic instance config
- add gpus to adhoc service schema (used by py-gitolite hooks to check yelpsoa-configs)
- add tests for gpus in utils; none for remote-run since no tests yet
- add gpus to paasta metastatus as another resource
- modify the ResourceInfo namedtuple to have gpus default to 0
- tox
- manual testing for instance gpus
- manual testing for adhoc service schema - added a gpus instance in yelpsoa-config's taskproc-canary service and ran it against my schema using cli.cmds.validate
- I will run an end-to-end test once I have updated yelpsoa-configs - validation hooks should use paasta's updated gpus schema
- Does anyone know if I need to update any version numbers or what the …
> Add gpu resource for remote-run and cli (for hook validation)

- paasta_tools/cli/cmds/mark_for_deployment.py
- tests/cli/test_cmds_wait_for_deployment.py
Ticket: OPSIMP-2795
If we're 100% on some code version, we don't need to wait just because we're currently scaling up. As a middle ground (instead of just completely ignoring the current instance count, which can sometimes be wrong), factor in the bounce_margin_factor when determining how many instances must be healthy before we're "deployed".
The new error looks like this (for a service with bounce_margin_factor of 0.9):
```
yelp-main.some_instance on norcal-prod isn't scaled up yet, has 44 out of 45 required instances (out of a total of 50)
```
> Factor bounce_margin_factor into wait-for-deployment

- paasta_tools/firewall.py
- tests/test_firewall.py
Tested this via example_happyhour on mesosstage, the rules look like this:
```yaml
- cidr: '169.229.226.0/24'
port: '1:200'
- cidr: '169.229.226.0/24'
port: '1024:65535'
```
We want this in order to use sauce-connect (it wants to whitelist ports 1024-65535).
> Allow port ranges for CIDR rules

- paasta_tools/cli/cmds/generate_pipeline.py
- tests/cli/test_cmds_generate_pipeline.py
fab_repo has been updated to work with GitHub remotes and Nowait's pipelines are now taking advantage of this.  PAASTA-12492 is the internal ticket that has the other relevant changes that have already been submitted.
> Remove validation that prevents github remotes
